cosmos/cosmos-sdk

- CHANGELOG.md
- x/auth/vesting/msg_server.go
expected work: 
```
cronosd tx vesting create-vesting-account crc13l5jnsydy3z5wevegpkmyechc0qvpjc2thwedr 1000000basetcro 1654325260092 --from=validator --keyring-backend=test --chain-id=cronos_777-1 --fees=2000000basetcro --home=$CHOME --broadcast-mode block
{"body":{"messages":[{"@type":"/cosmos.vesting.v1beta1.MsgCreateVestingAccount","from_address":"crc18z6q38mhvtsvyr5mak8fj8s8g4gw7kjjtsgrn7","to_address":"crc13l5jnsydy3z5wevegpkmyechc0qvpjc2thwedr","amount":[{"denom":"basetcro","amount":"1000000"}],"end_time":"1654325260092","delayed":false}],"memo":"","timeout_height":"0","extension_options":[],"non_critical_extension_options":[]},"auth_info":{"signer_infos":[],"fee":{"amount":[{"denom":"basetcro","amount":"2000000"}],"gas_limit":"200000","payer":"","granter":""}},"signatures":[]} …
```
> fix: add base account getter

- baseapp/baseapp.go
- runtime/builder.go
- runtime/module.go
- simapp/app.go
This PR adds a way to provide through depinject BaseApp's MsgServiceRouter, required for `x/auth`. Ref: #12125
---
I have...
I have...
> feat: add MsgServiceRouter to Baseapp (and runtime's provideCodecs)

- depinject/features/prefer.feature
Closes: #XXXX
---
I have...
I have...
> test(depinject): add preference feature

- docs/core/grpc_rest.md
The fully qualified service method path should have a `/` between the service and the method name.
---
I have...
I have...
> docs: fix protobuf service method path for rpc

- CHANGELOG.md
- x/upgrade/keeper/keeper.go
- x/upgrade/keeper/keeper_test.go
Replaces #11705 and only targets v0.45.x
ref: https://github.com/cosmos/cosmos-sdk/issues/11707
---
I have...
I have...
> fix: Refactor GetLastCompletedUpgrade [v0.45.x]

- CHANGELOG.md
- x/staking/client/cli/flags.go
- x/staking/client/cli/tx.go
- x/staking/client/testutil/cli_test.go
- x/staking/client/testutil/suite.go
Closes: #12311 
This is a backport PR of #10684 to release into v0.45
---
I have...
I have...
> fix: edit validator bug from cli

- CHANGELOG.md
- x/staking/keeper/validator.go
We had a chain upgrade that introduced [bech32 prefix change and dual prefix support](https://medium.com/likecoin/likecoin-new-wallet-address-format-the-story-of-like1-443c6a0bfca6) in our cosmos-sdk fork, and after ~21 days of running the upgrade, our chain halted due to this issue. Details of our chain halt incident [can be found here](https://blog.like.co/2022-05-27-chain-halt-incident-report/)
The root issue is in `x/staking`, `DeleteValidatorQueue` does a string comparison instead of bytes, which would cause panic when dequeueing validator if the address string format is changed (in our case, default bech32 prefix changed).
I am not sure if this should be considered as a useful fix for general case, since changing bech32 prefix and dual prefix support seems not common. I am also not …
> fix: Use bytes instead of string comparison in delete validator queue

- store/streaming/file/service.go
This change fixes resource leaks that were present due a rigid
error return path and didn't invoke .Close until the last line
of each method. This change fixes the problem by using a named
return error variable and if the return error value is nil, we
derive its final value from the unconditionally defer os.File.Close
value, which matches the prior logic but now fixes the flaw.
Fixes #12336
Fixes #12337
Fixes #12338
> fix: store/streaming/file: fix os.File leaks in (*StreamService).Listen methods

- .github/workflows/check-docs.yml
- .github/workflows/cosmovisor-release.yml
- .github/workflows/deploy-docs.yml
- .github/workflows/labeler.yml
- .github/workflows/lint-pr.yml
- .github/workflows/lint.yml
- .github/workflows/proto.yml
- .github/workflows/release-sims.yml
- .github/workflows/release.yml
- .github/workflows/sims-045.yml
- .github/workflows/sims-046.yml
- .github/workflows/sims.yml
- .github/workflows/stale.yml
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: nathannaveen <42319948+nathannaveen@users.noreply.github.com>
> chore: Set permissions for GitHub actions

- simapp/params/weights.go
- testutil/sims/app_helpers.go
- x/capability/capability_test.go
- x/slashing/simulation/operations_test.go
- x/slashing/testutil/app.yaml
- x/slashing/testutil/app_config.go
Discovered while migrating `x/staking`: The simulation test suite actually do not actually test anything in operation. I have missed the coverage change shown here: https://github.com/cosmos/cosmos-sdk/pull/12315#issuecomment-1163288887.
context: https://github.com/cosmos/cosmos-sdk/pull/12315#issuecomment-1165490713
---
I have...
I have...
> test: fix `x/slashing` operations test

- CHANGELOG.md
- RELEASE_NOTES.md
Updates the release notes and changelog for v0.45.6 release.
---
I have...
I have...
> chore: update release notes

- store/types/store.go
- x/staking/keeper/msg_server.go
This is an oft added function for many projects that's probably more clear to implement as needed, but is probably mostly just a gap in the standard library. 
This function is removed in more recent versions of tendermint (as tendermint no longer uses it.) 
---
I have...
I have...
> fix: remove dependency on tendermint internal library

- CHANGELOG.md
Sync the main changelog with the latest v0.45 version.
---
I have...
I have...
> chore: sync changelog

- CHANGELOG.md
- x/mint/types/params.go
Ensure `GoalBonded` must be positive.
---
I have...
I have...
> fix: update x/mint parameter validation

- cosmovisor/CHANGELOG.md
- cosmovisor/README.md
- cosmovisor/RELEASE_NOTES.md
In the cosmovisor docs, correctly identify the backup directory configuration variable as `DAEMON_DATA_BACKUP_DIR` (instead of the incorrect `DAEMON_BACKUP_DIR`).
---
I have...
I have...
> docs: Fix the backup config variable name in the cosmovisor docs.

- x/upgrade/keeper/keeper.go
Followup on https://github.com/cosmos/cosmos-sdk/pull/12264
Removes sort and finds latest upgrade in place rather than adding additional sorting.
PS: not sure if this should be ported to other branches.
---
I have...
I have...
> chore: optimize get last completed upgrade

- CHANGELOG.md
- types/errors/errors.go
- x/auth/ante/fee.go
- x/auth/ante/fee_test.go
- x/auth/ante/testutil_test.go
Update `DeductFeeDecorator` to prevent 0-gas txs.
closes: #12415
---
I have...
I have...
> fix!: prevent 0 gas txs

- api/cosmos/feegrant/v1beta1/feegrant.pulsar.go
- proto/cosmos/feegrant/v1beta1/feegrant.proto
- x/feegrant/doc.go
- x/feegrant/feegrant.pb.go
- x/feegrant/spec/01_concepts.md
Closes: #12422 
---
I have...
I have...
> docs(x/feegrant): use `coins` instead of `tokens`

- snapshots/manager.go
`BaseApp` method `SetSnapshot` sets `BaseApp.snapshotManager.extensions` with a nil value, this will cause nil map error whenever `BaseApp.snapshotManager.extensions` is used, so I change it to an empty map instead.
I have...
I have...
Closes: #XXXX
---
I have... …
> fix: use empty map instead of nil value for setting BaseApp.snapshotManager.extensions  (#12031)

- CHANGELOG.md
- x/auth/tx/service.go
- x/auth/tx/service_test.go
- removes the enforcement of a single equal sign in `GetTxsEvent` which was preventing querying by base64 encoded signatures.
- switches event string check to regex.
Closes: #12471 
---
I have...
I have...
> fix(x/auth): allow multiple = signs in `GetTxsEvent`

- x/staking/keeper/val_state_change.go
Fix panic string in staking/val_state_change.go::UnbondingToUnbonded
Closes: #XXXX
---
I have...
I have...
> fix: panic string in staking/val_state_change.go::UnbondingToUnbonded

- CHANGELOG.md
- go.mod
- go.sum
Resolves https://github.com/cosmos/cosmos-sdk/issues/9568 which should be re-opened and closed after this PR is merged
Resolves https://github.com/cosmos/cosmos-sdk/issues/5759
Likely resolves https://github.com/cosmos/cosmos-sdk/issues/10818
The `replace` for 99designs/keyring to a Cosmos fork of keyring (cosmos/keyring) was added in https://github.com/cosmos/cosmos-sdk/pull/9563
Removal of the `replace` was tracked in https://github.com/cosmos/cosmos-sdk/issues/9568 but never completed.
The original issue was fixed in upstream: https://github.com/99designs/keyring/pull/87 so this PR removes the `replace` and upgrades to the latest release of 99designs/keyring.
---
please add links to any relevant …
> refactor: remove cosmos/keyring

- x/auth/keeper/migrations.go
- x/auth/migrations/v043/store_test.go
- x/auth/migrations/v046/store_test.go
- x/auth/migrations/v4/migrate.go
- x/auth/migrations/v4/migrator_test.go
- x/auth/module.go
- x/crisis/keeper/migrator.go
- x/crisis/migrations/v2/migrate.go
- x/crisis/migrations/v2/migrate_test.go
- x/crisis/module.go
- x/distribution/keeper/migrations.go
- x/distribution/migrations/v3/migrate.go
- x/distribution/migrations/v3/migrate_test.go
- x/distribution/module.go
- x/slashing/keeper/migrations.go
- x/slashing/migrations/v3/migrate.go
- x/slashing/migrations/v3/migrator_test.go
- x/slashing/module.go
The PRs that are migrating away from `x/params`, I realized folks are defining the migration path incorrectly -- it's supposed to be the **_consensus_** version.
> chore: fix migration paths

- testutil/configurator/configurator.go
- types/query/filtered_pagination_test.go
- types/query/pagination_test.go
Closes: #12584
- refactored tests to use a test suite initialized by `depinject`
- dependency on `simapp` replaced by 3 dependencies on modules used in the integration test: bank, auth, and params.
- introduces a prototype composable AppConfig configurator which I plan to reuse and refine in the future test refactors 
---
I have...
I have...
> refactor(types): remove dependency on simapp in integration test

- CHANGELOG.md
- x/auth/ante/fee.go
- x/auth/ante/fee_test.go
Closes: #12588
Solution:
- allow zero gas in simulation mode
- don't check min-gas-price in simulation mode
Please backport to 0.46.
---
I have...
I have...
> fix: auto gas don't work

- x/auth/ante/sigverify.go
https://github.com/cosmos/cosmos-sdk/blob/f9f92f20d8545203c4c6784bfad3fc88e1f82926/x/auth/ante/sigverify.go#L313
There is a wrong comment.
---
I have...
I have...
> docs: correct confusing comments in ante.IncrementSequenceDecorator

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/feature-request.md
Closes: #12692 
remove admin use from issue templates
> chore: remove admin use from templates

- CHANGELOG.md
Compiled and squashed all RCs changelogs back into the v0.46.0 section.
---
I have...
I have...
> chore: v0.46.0 Final Release changelog

- cosmovisor/CHANGELOG.md
- cosmovisor/cmd/cosmovisor/version.go
Prepare for cosmovisor v1.2.0 release.
---
I have...
I have...
> chore: cosmovisor v1.2.0 release updates

- CHANGELOG.md
- x/params/types/common_test.go
- x/params/types/subspace.go
- x/params/types/subspace_test.go
- imp(params): Add GetParamSetIfExists to prevent panic on breaking param changes
- test
- imp(params): Add GetParamSetIfExists to prevent panic on breaking param changes
Closes: #XXXX
---
I have...
I have...
> feat: Add `GetParamSetIfExists` to prevent panic on breaking param changes

- CHANGELOG.md
- x/bank/migrations/v2/store.go
- x/bank/migrations/v2/store_test.go
- x/bank/types/keys.go
This PR adds a convenience method for constructing the key necessary to query for the account's balance of a given denom. 
I ran into this issue since we are using ABCI query now to perform balance requests because we are also requesting merkle proofs for the returned balance [here](https://github.com/celestiaorg/celestia-node/pull/911/files#diff-0ee31f5a7bd88e9f758e6bebdf3ee36365519e55a451098d9638c39afe5eac42R144).
It would be nice to have a definitive convenience method for constructing the key.
[Ref.](github.com/celestiaorg/celestia-node/pull/911)
> feat: Add convenience method for constructing key to access account's balance for a given denom

- CHANGELOG.md
- UPGRADING.md
- depinject/README.md
- docs/architecture/adr-038-state-listening.md
- simapp/app.go
- simapp/app_legacy.go
- simapp/app_test.go
- simapp/sim_bench_test.go
- simapp/sim_test.go
- simapp/simd/cmd/cmd_test.go
- simapp/simd/cmd/root.go
- simapp/simd/main.go
- simapp/test_helpers.go
- tests/e2e/server/export_test.go
- x/gov/genesis_test.go
- x/gov/module_test.go
- x/staking/module_test.go
Closes: #XXXX
Investigating the possibility of using injected encoding params in `NewSimApp` and simplify `NewSimApp` constructor arguments.
---
I have...
I have...
> refactor!: use injected encoding params in simapp

- x/staking/keeper/delegation.go
- x/staking/keeper/delegation_test.go
- x/staking/keeper/querier.go
- x/staking/keeper/slash_test.go
- x/staking/simulation/decoder_test.go
- x/staking/types/delegation.go
- x/staking/types/delegation_test.go
The changes in https://github.com/cosmos/cosmos-sdk/pull/12554 without https://github.com/cosmos/cosmos-sdk/pull/12578
> fix: make ModuleAccountInvariants pass for IS SDK changes

- math/dec.go
- math/dec_test.go
Noticed in an audit of Quicksilver's code while examining the Quo* code, that there were
2 invocations of a multiplication with precisionReuse of the simplified form:
```go
a *= b
a *= b
```
but those can be folded into
```go
a *= (b * b)
```
of which b is computed at init time, thus (b * b) can also be computed
at init time, so the final form becomes
```go
a *= b_squared
```
While here, added benchmarks for the change.
The results of this change yield performance improvements
```shell
name                    old time/op    new time/op    delta
LegacyQuo-8               43.1ns ± 1%    37.1ns ± 3%  -14.00%  (p=0.000 n=14+15)
LegacyQuoTruncateMut-8    35.2ns ± 1%    28.8ns ± 3%  -18.27%  (p=0.000 n=15+15)
LegacyQuoRoundupMut-8      287ns ± 2%     283ns ± 3% …
```
> perf: math: precompute & use square of precisionReuse instead of 2 repeated computations

- CHANGELOG.md
- RELEASE_NOTES.md
> chore: 0.45.7 changelog prep

- tx/textual/valuerenderer/bench_test.go
- tx/textual/valuerenderer/dec.go
- tx/textual/valuerenderer/dec_test.go
- tx/textual/valuerenderer/int.go
- tx/textual/valuerenderer/int_test.go
Adds validation to reject non-digits before & after decimal points,
along with tests to verify and lock-in this enforcement.
Fixes #12811
> fix: tx/textual/valuerenderer: reject non-digits in dec + int

- x/distribution/keeper/grpc_query.go
- x/distribution/keeper/grpc_query_test.go
- x/distribution/module.go
Closes: #12465 
- Wraps keeper with querier struct.
- I've referenced x/staking code. The only difference is querier in x/distr reference keeper with value object not as a pointer. I think it doesn't need to reference with the pointer because querier does not update keeper's state.
- Run `grpc_query_test.go` test cases after refactoring and those are passed
---
I have...
I have...
> refactor: x/distr module create querier

- x/staking/spec/01_state.md
Docs fix - removes an extra `"` in the staking/state docs.  Typo at https://docs.cosmos.network/main/modules/staking/01_state.html
---
I have...
- N/A [X] added `!` to the type prefix if API or client breaking change
- N/A [X] provided a link to the relevant issue or specification
- N/A [X] followed the guidelines for [building modules](https://github.com/cosmos/cosmos-sdk/blob/main/docs/building-modules)
- N/A [X] included the necessary unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/main/CONTRIBUTING.md#testing)
- N/A [X] added a changelog entry to `CHANGELOG.md`
- N/A [X] included comments for [documenting Go …
> docs(staking): typo in staking/state

- x/gov/spec/02_state.md
ref: https://github.com/cosmos/cosmos-sdk/pull/12410#discussion_r931754456
---
I have...
I have...
> docs: typo in metadata type description

- x/group/spec/05_client.md
This PR updates the current docs for the groups module REST endpoints in v0.46. The current endpoint prefix is `/cosmos/group/v1beta1/...` which is incorrect and has been updated to `/cosmos/group/v1/...`
For example:
```
curl localhost:1317/cosmos/group/v1beta1/group_info/1
{
"code": 12,
"message": "Not Implemented",
"details": [
]
}
```
```
curl localhost:1317/cosmos/group/v1/group_info/1
{
"info": {
"id": "1",
"admin": "cosmos15e...",
"metadata": "",
"version": "3",
"total_weight": "3",
"created_at": "2022-01-01T12:12:12.999999Z"
}
}
```
---
I have...
your …
> docs: Update REST endpoints for group module documentation

- .github/workflows/proto-docker.yml
- CHANGELOG.md
- contrib/devtools/Dockerfile
Use ghcr to store the proto-builder image at ghcr.io/cosmos/proto-builder
---
I have...
I have...
> ci: Use go 1.19 for proto build environment

- CHANGELOG.md
- x/capability/types/keys.go
- x/capability/types/keys_test.go
ref: #11726
---
I have...
I have...
> fix: Use fixed length hex for pointer at FwdCapabilityKey (backport #11737)

- core/internal/testpb/modules.go
Closes: #12883 
`depinject` dependency ordering is not deterministic where there are multiple tree traversal solutions satisfying the graph, AFAIK it's not a design goal though.
---
I have...
I have...
> fix: flaky appconfig test

- .golangci.yml
- CHANGELOG.md
- Makefile
This PR updates `make format` so that:
* gofumpt is run
* golangci-lint run ./... --fix is run
* the correct files are excluded from formatting changes
---
I have...
I have...
> chore: update make format

- CHANGELOG.md
- x/upgrade/abci.go
otherwise, it panic because it expect the key is migrated
Closes: #12904
Need to backport to 0.46.
---
I have...
I have...
> fix: move downgrade verification after store migration

- README.md
The previous GoDoc badge never renders for me so I fixed the badge link based on the [Go badge tool]( https://pkg.go.dev/badge/?path=https%3A%2F%2Fpkg.go.dev%2Fgithub.com%2Fcosmos%2Fcosmos-sdk)
Before | After
--- | ---
> fix: Go badge

- CHANGELOG.md
- client/docs/swagger-ui/swagger.yaml
- server/api/server.go
- server/swagger.go
- simapp/app.go
- simapp/app_legacy.go
Closes: #12149
Superseded #12352
Ran `sh scripts/protoc-swagger-gen.sh`
---
I have...
I have...
> refactor: helper method for register swagger api

- simapp/app.go
Closes: #13001 
This pull request contains fixes for creation of software-upgrade by submit-legacy-proposal
---
I have...
I have...
> fix: fix the gov proposals

- simapp/app.go
- simapp/app_config.go
- simapp/app_legacy.go
- simapp/app_test.go
- x/bank/module.go
- The `app.go` should use the permission from the app config instead of the map. This was a left-over from the legacy app.
- As we are touching `app_legacy.go` this replicates #13002 here in `app_legacy.go`
- Improve blocked address test to actually check against blocked accounts (instead of the default module accounts with permissions)
---
I have...
I have...
> fix: use module permission from app_config in `app.go`

- CHANGELOG.md
- server/export.go
- tests/e2e/server/export_test.go
Closes: #13024
---
I have...
I have...
> fix: exporting the blockParams regression

- CHANGELOG.md
- baseapp/abci.go
Closes: #13040
---
I have...
I have...
> fix: missing return statement in BaseApp.Query

- CHANGELOG.md
- x/authz/keeper/keeper.go
- x/authz/keeper/keeper_test.go
Closes: #13027 
This PR adds the `GetAuthorization` function to the `x/auth` module/keeper.
---
I have...
I have...
> feat(x/authz): Add the GetAuthorization function.

- CHANGELOG.md
- RELEASE_NOTES.md
Prepare v0.45.8 release changelog.
---
I have...
I have...
> chore: v0.45.8 release changelog

- CHANGELOG.md
- x/auth/simulation/decoder.go
- x/auth/simulation/decoder_test.go
Closes: #13028
This PR adds handling for the `AccountNumberStoreKeyPrefix` in the simulation decoder for the `x/auth` module.
---
I have...
I have...
> feat(x/auth): Add auth sim decoder case for AccountNumberStoreKeyPrefix

- baseapp/baseapp.go
- server/mock/store.go
- server/rollback.go
- server/types/app.go
- server/util.go
- store/iavl/store.go
- store/iavl/tree.go
- store/rootmulti/rollback_test.go
- store/rootmulti/store.go
- store/types/store.go
Closes: #11333
To make rollback command actually work, we need to:
- ~patch tendermint to allow rollback block store: https://github.com/tendermint/tendermint/pull/8101~
- ~patch iavl to allow delete latest saved version: https://github.com/cosmos/iavl/pull/483~, no need to patch iavl, just use the `LoadVersionForOverwriting`.
~tests to be added later.~ tests added.
---
I have...
I have...
> fix: rollback command don't actually delete multistore versions

- x/slashing/types/genesis.go
For use in https://github.com/cosmos/interchain-security/pull/313 to speed up integration tests
> fix: decrease minimums for genesis parameters

- x/crisis/client/cli/tx_test.go
Use `require` instead of `assert` in x/crisis CLI Tendermint Mock tests
---
I have...
I have...
> refactor: Use `require` instead of `assert` in x/crisis CLI test

- CHANGELOG.md
- baseapp/baseapp.go
- server/mock/store.go
- server/rollback.go
- server/util.go
- store/iavl/store.go
- store/iavl/tree.go
- store/rootmulti/rollback_test.go
- store/rootmulti/store.go
- store/types/store.go
* rollback command don't actually delete multistore versions
Closes: #11333
- add unit tests
- use LoadVersionForOverwriting
- update tendermint dependency to 0.35.x release branch
Co-authored-by: Aleksandr Bezobchuk <alexanderbez@users.noreply.github.com>
flushMetadata after rollback
Update server/rollback.go
Co-authored-by: Aleksandr Bezobchuk <alexanderbez@users.noreply.github.com>
fix build
gofumpt
* fix unit test
(cherry picked from commit 51d2de582d036ece4af10267e889f6fdd97f8acf)
* fix unit test
* changelog
* api breaking changelog
Co-authored-by: yihuang <huang@crypto.com>
Closes: #XXXX
---
I have...
*All items are required. Please add a note …
> fix: rollback command don't actually delete multistore versions (backport #11361)

- go.mod
- go.sum
- x/bank/app_test.go
https://github.com/cosmos/cosmos-sdk/pull/11981 introduced a simapp dependency to the SDK, which we don't want.
This PR fixes that and https://github.com/cosmos/cosmos-sdk/actions/workflows/dependencies-review.yml should be required before a merge for avoiding regression.
---
I have...
I have...
> fix: remove newly introduced simapp dependency

- client/rpc/validators.go
- cosmovisor/args.go
- cosmovisor/args_test.go
- cosmovisor/errors/multi.go
- server/util_test.go
- types/events.go
- x/distribution/types/proposal.go
- x/params/types/proposal/proposal.go
This change removes a code pattern that I noticed while on a late night audit of cosmovisor in which
strings.Builder.WriteString(fmt.Sprintf(...))
calls were being made, yet that's counterproductive to using fmt.Fprintf which will check whether the writer implements .WriteString and then avoids the need to firstly build a string using fmt.Sprintf.
The performance wins from this change transcend all dimensions as exhibited below:
```shell
name            old time/op    new time/op    delta
DetailString-8    5.48µs ±23%    4.40µs ±11%  -19.79%  (p=0.000 n=20+17)
name            old alloc/op   new alloc/op   delta
DetailString-8    2.63kB ± 0%    2.11kB ± 0%  -19.76%  (p=0.000 n=20+20)
name            old allocs/op  new allocs/op  delta
DetailString-8 …
```
> perf: all: remove unnecessary allocations from strings.Builder.WriteString(fmt.Sprintf(...))

- cosmovisor/CHANGELOG.md
- cosmovisor/README.md
- cosmovisor/RELEASE_NOTES.md
Closes: #11305
Prepares for tagging Cosmovisor 1.3.0
---
I have...
I have...
> docs: prepare cosmovisor 1.3.0 release

- .github/workflows/lint.yml
- Makefile
ref https://github.com/cosmos/cosmos-sdk/pull/13186#issuecomment-1243579902
---
I have...
I have...
> chore: pin version of golangci-lint

- .github/workflows/docker.yml
- Makefile
Separate build commands
---
I have...
I have...
> chore: separate build flags

- baseapp/abci.go
- baseapp/baseapp.go
- types/context.go
- types/mempool.go
- types/tx_msg.go
- x/auth/tx/builder.go
Ref: #13150 
Followed by: #13262 
I am proposing `Select(...)` instead of `ReapMaxBytes(...)` as in [ADR-60](https://github.com/cosmos/cosmos-sdk/blob/main/docs/architecture/adr-060-abci%2B%2B-phase-i.md#prepareproposal), since the `ProcessProposal` steps can be simplified from
>1. Reap one or more transactions from the priority queue and collect them into one of two buffers -- valid and invalid.
> 2. For transactions that DO NOT violate the nonce validation, they are included in the valid buffer.
> 3. For transactions that DO violate the nonce validation, they are included in the invalid buffer.
> 4. Continue this process until the desired number of valid transactions are reaped or until the mempool is empty.
> 5. Provide Tendermint the list of all transactions from the valid buffer.
> …
> feat: add mempool interfaces

- crypto/keys/secp256k1/internal/secp256k1/secp256_test.go
Fixes an oversight that hadn't been considered when the build guards were added to the other files in the same directory, that this test requires linking with code that hooks into cgo. This change adds the build guard
+build cgo
Fixes #13266
> fix: crypto/keys/secp246k1/*: add +build cgo guard to avoid failure with CGO_ENABLED=0

- client/v2/cli/builder.go
- client/v2/cli/flag/field.go
- client/v2/cli/flag/message.go
- client/v2/cli/flag/pagination.go
- client/v2/cli/query.go
- client/v2/cli/query_test.go
- client/v2/go.mod
Ref #11775 
This moves:
* `github.com/cosmos/cosmos-sdk/client/v2` -> `cosmossdk.io/client/v2` (we need vanity URL updates for this)
* `github.com/cosmos/cosmos-sdk/client/v2/cli` -> `cosmossdk.io/client/v2/autocli` since `autocli` seems better
---
I have...
I have...
> refactor!: autocli go.mod and package naming

- server/grpc/gogoreflection/fix_registration.go
Closes: #XXXX
---
I have...
I have...
> fix: Fix golangci-lint issue

- CHANGELOG.md
- baseapp/abci.go
- tests/e2e/tx/service_test.go
it was removed accidentally, add it back.
please backport to 0.46.
---
I have...
I have...
> fix: streaming listeners are not called for deliver tx event

- UPGRADING.md
- client/v2/internal/buf.lock
- third_party/proto/README.md
Protos for v0.46 have been re-pushed https://buf.build/cosmos/cosmos-sdk/docs/8cb30a2c4de74dc9bd8d260b1e75e176
(due to https://github.com/bufbuild/buf/issues/1415#issuecomment-1251535877)
---
I have...
I have...
> fix: fix buf commit

- x/gov/client/cli/prompt.go
- x/gov/client/cli/prompt_test.go
Reported by cosmos/gosec in https://github.com/cosmos/cosmos-sdk/security/code-scanning/5730. This change checks for errors from strconv.Atoi in which case we were susceptible to out of range errors, this change also adds tests to prevent regressions.
Fixes #13346
> fix: x/gov/client/cli: fix integer overflow in parsing int prompted values

- orm/go.mod
- orm/go.sum
- orm/model/ormdb/json.go
- store/internal/proofs/helpers.go
- types/module/module.go
- x/auth/keeper/keeper.go
- x/bank/module.go
- x/genutil/client/cli/migrate.go
Uses golang.org/x/exp/maps.(Keys, Values) to sort out flagged
potential non-determinism issues due to map iteration which is
randomized in maps.
These were flagged by cosmos/gosec in
* https://github.com/cosmos/cosmos-sdk/security/code-scanning/724
* https://github.com/cosmos/cosmos-sdk/security/code-scanning/725
* https://github.com/cosmos/cosmos-sdk/security/code-scanning/726
* https://github.com/cosmos/cosmos-sdk/security/code-scanning/727
* https://github.com/cosmos/cosmos-sdk/security/code-scanning/728
* https://github.com/cosmos/cosmos-sdk/security/code-scanning/729
* https://github.com/cosmos/cosmos-sdk/security/code-scanning/782
* https://github.com/cosmos/cosmos-sdk/security/code-scanning/813
* https://github.com/cosmos/cosmos-sdk/security/code-scanning/814
* …
> chore: all: use golang.org/x/exp/maps.(Keys, Values) where necessary

- x/gov/client/cli/prompt.go
- x/gov/client/cli/prompt_test.go
Adds more rigorous checks to ensure that the output is as expected with range failures. While here also added control tests to ensure that we can parse integers within range of int.
Updates #13346
> fix: x/gov/client/cli: update & tighten Prompt.Parse tests

- math/CHANGELOG.md
- math/uint.go
- math/uint_test.go
Closes: #13087
---
I have...
I have...
> feat: add uint `IsNil` method

- CHANGELOG.md
- types/utils.go
Closes: #11241
---
I have...
I have...
> refactor!: remove deprecated `sdk.NewLevelDB`

- docs/spec/store/README.md
Closes: #XXXX
---
I have...
I have...
> docs: add IAVL concurrent use warning/explanation

- baseapp/baseapp.go
Closes: #13388 
---
we could add a notice inside `baseapp.LoadVersion()` so that user could be informed about the possible following fast node migration.
I have...
I have...
> feat: Add notice for possible iavl fast node migration

- .github/workflows/build-skip.yml
- .github/workflows/test-e2e-skip.yml
- .github/workflows/test-integration-skip.yml
- baseapp/baseapp.go
- tests/e2e/group/tx.go
- x/auth/client/testutil/suite.go
Closes: #13383
Add comments as requested in https://github.com/cosmos/cosmos-sdk/pull/13361#discussion_r979007431
---
I have...
I have...
> fix: attempt at fixing flaky e2e tests

- CHANGELOG.md
- server/start.go
Closes: #XXXX
---
I have...
I have...
> fix: add close for grpcOnly mode

- CHANGELOG.md
- baseapp/abci.go
- baseapp/baseapp.go
- baseapp/options.go
- baseapp/streaming.go
- docs/architecture/adr-038-state-listening.md
- docs/core/store.md
- simapp/app.go
- store/cachemulti/store.go
- store/streaming/README.md
- store/streaming/constructor.go
- store/streaming/constructor_test.go
- store/streaming/file/README.md
- store/streaming/file/example_config.toml
- store/streaming/file/service.go
- store/streaming/file/service_test.go
Refs: https://github.com/cosmos/cosmos-sdk/issues/13324
Hello 👋 this PR introduces the second stage of changes to support [ADR-038](https://github.com/cosmos/cosmos-sdk/pull/8012) state listening. This is rebased on top of the [first segment](https://github.com/cosmos/cosmos-sdk/pull/8551), which introduces the low level changes to the MultiStore and KVStore interfaces and implementations, the new WriteListener types, and the new listen.KVStore type.
In this segment we introduce the StreamingService interface, an implementation that writes out to files, and it's integration and configuration at the BaseApp level.
The idea was to have the first segment reviewed independently first but if people think it is easier/more time efficient to review both at the same time then we could start here. …
> feat: ADR-038 Part 2: StreamingService interface, file writing implementation, and configuration (backport #8664)

- .github/workflows/staticmajor.yml
Brings in a static analyzer that catches leaking resources like unclosed file handles, networking handles etc that can't easily be caught except in very critical code reviews as well as a bunch of other static analyzers that Orijtech Inc produces.
> ci: .github/workflows: add staticmajor to catch leaking resources

- CHANGELOG.md
- baseapp/abci.go
- baseapp/baseapp.go
- baseapp/options.go
- baseapp/streaming.go
- docs/architecture/adr-038-state-listening.md
- docs/core/store.md
- simapp/app.go
- store/cachemulti/store.go
- store/streaming/README.md
- store/streaming/constructor.go
- store/streaming/constructor_test.go
- store/streaming/file/README.md
- store/streaming/file/example_config.toml
- store/streaming/file/service.go
- store/streaming/file/service_test.go
Ref: https://github.com/cosmos/cosmos-sdk/issues/13324
Hello 👋 this PR introduces the second stage of changes to support [ADR-038](https://github.com/cosmos/cosmos-sdk/pull/8012) state listening. This is rebased on top of the [first segment](https://github.com/cosmos/cosmos-sdk/pull/8551), which introduces the low level changes to the MultiStore and KVStore interfaces and implementations, the new WriteListener types, and the new listen.KVStore type.
In this segment we introduce the StreamingService interface, an implementation that writes out to files, and it's integration and configuration at the BaseApp level.
The idea was to have the first segment reviewed independently first but if people think it is easier/more time efficient to review both at the same time then we could start here. …
> feat: ADR-038 Part 2: StreamingService interface, file writing implementation, and configuration (#8664)

- CHANGELOG.md
- RELEASE_NOTES.md
Prepare `v0.46.2` release.
---
I have...
I have...
> chore: prepare `v0.46.2` release

- .github/workflows/staticmajor.yml
- CHANGELOG.md
- UPGRADING.md
- runtime/types.go
- server/export.go
- server/types/app.go
- simapp/app_test.go
- simapp/export.go
- simapp/sim_test.go
- simapp/simd/cmd/root.go
- tests/e2e/server/export_test.go
- testutil/sims/simulation_helpers.go
- types/module/module.go
- types/module/module_test.go
Upstreams https://github.com/osmosis-labs/cosmos-sdk/pull/336 with extra checks.
---
I have...
I have...
> feat!: specify module to export

- CHANGELOG.md
- UPGRADING.md
- simapp/export.go
- types/module/module.go
- types/module/module_test.go
Upstream https://github.com/osmosis-labs/cosmos-sdk/pull/339
---
I have...
I have...
> refactor: split `ExportGenesis` into two functions to maintain backwards compatibility

- cosmovisor/upgrade.go
Enumerates and improves on the error checking for non-existance errors to clearly return unhandled errors such as access restrictions, unaccessible volumes etc, when trying to download binaries. The prior code assumed that either the file existed or the only error to be returned would be about the file not existing, yet this isn't always true.
Fixes #13469
> fix: cosmovisor: isolate and return masked errors that are not non-existence errors

- docs/building-modules/simulator.md
A simple PR for fixing a broken link that existed in the documentation of [simulator.md](https://github.com/cosmos/cosmos-sdk/blob/main/docs/building-modules/simulator.md)
> docs: fix broken link in simulator.md

- .github/workflows/build-docs.yml
- .github/workflows/deploy-docs.yml
Apparently, I was using npm `8.5.5` on my machine (Fedora 36) and that's the only version that does not have a bug with overrides: https://github.com/npm/cli/issues/4942
This forces the npm version to be `8.5.5`.
---
I have...
I have...
> ci: fix build docs

- x/nft/client/cli/tx_test.go
This PR fixes the wrong config returned in x/nft CLI tests
> fix: small fix in x/nft CLI tests

- simapp/sim_test.go
Fixes the simulations failure: https://github.com/cosmos/cosmos-sdk/actions/runs/3229864440/jobs/5287681195
You can verify with the following command, as CI skips that test.
```sh
cd simapp
go test . -run TestAppImportExport -Enabled=true -NumBlocks=2 -Genesis= -Verbose=true -Commit=true -Seed=2 -Period=5 -ExportParamsPath /tmp/sim-logs-983113732/sim_params-1.json -ExportStatePath /tmp/sim-logs-983113732/sim_state-1.json -v -timeout 24h
```
---
I have...
I have...
> fix: fix simulations failure

- x/distribution/keeper/allocation.go
Closes: #13520
Note, this is NOT SM breaking. Just a minor perf improvement to not do the same math over and over again.
---
I have...
I have...
> refactor: Improve AllocateTokens

- CHANGELOG.md
Add missing changelog entry from #11582 
---
I have...
I have...
> chore: CHANGELOG update

- CHANGELOG.md
- types/staking.go
- x/genutil/client/cli/init.go
- x/genutil/client/cli/init_test.go
https://github.com/cosmos/cosmos-sdk/pull/9776 is not so useful, as it changes only the default denomination for the staking module.
More modules use `sdk.DefaultBondDenom`, such as `gov`, leading to a mix of `stake` and the chosen denomination.
---
I have...
I have...
> feat: overwrite default denom in `init` cmd

- simapp/simd/cmd/root.go
I noticed that in simd we're using `tmcli.NewCompletionCmd` instead of cobra's built-in completion command. Maybe at some point cobra didn't have this functionality, but now the built-in functionality is better and also supports fish and powershell. So we should encourage apps to just use default cobra completion.
Not sure if any CHANGELOG entry is needed because this is just simapp.
---
I have...
I have...
> feat!: use built-in cobra completion command

- CHANGELOG.md
- x/mint/types/params.go
- x/slashing/types/params.go
- x/staking/types/params.go
Closes: #13550
Ensure all parameter validation ensures that decimal types are non-nil.
---
I have...
I have...
> fix: update param validation to fail on nil dec

- docs/architecture/adr-050-sign-mode-textual-annex2.md
- docs/architecture/adr-050-sign-mode-textual.md
- tx/textual/valuerenderer/bench_test.go
- tx/textual/valuerenderer/bytes.go
- tx/textual/valuerenderer/bytes_test.go
- tx/textual/valuerenderer/coin_test.go
- tx/textual/valuerenderer/coins.go
- tx/textual/valuerenderer/coins_test.go
- tx/textual/valuerenderer/dec.go
- tx/textual/valuerenderer/duration.go
- tx/textual/valuerenderer/duration_test.go
- tx/textual/valuerenderer/int.go
- tx/textual/valuerenderer/timestamp.go
- tx/textual/valuerenderer/timestamp_test.go
- tx/textual/valuerenderer/types.go
- tx/textual/valuerenderer/valuerenderer_test.go
Refs: #11970
Changes target of `SIGN_MODE_TEXTUAL` rendering to be a structured datatype
instead of lines of ASCII text. This avoids the complexities of in-band, signaling and
allows more capable signing devices not to be hindered by the limitations of those less
capable.
---
I have...
NOTE: changelog intentionally omitted - we'll add an entry when
#11970 is complete.
I have...
> feat: structured screens for SIGN_MODE_TEXTUAL

- CHANGELOG.md
- RELEASE_NOTES.md
- simapp/helpers/test_helpers.go
- simapp/test_helpers.go
- x/authz/simulation/operations.go
- x/bank/simulation/operations.go
- x/distribution/simulation/operations.go
- x/genutil/gentx_test.go
- x/gov/simulation/operations.go
- x/simulation/util.go
- x/slashing/simulation/operations.go
- x/staking/simulation/operations.go
We had to revert #12437 due to an API breaking change in `v0.45.9`.
This brings back the fix in a non API breaking change way (using the same name and signature we have in v0.46).
---
I have...
I have...
> feat: add `GenSignedMockTx`

- x/authz/module/module.go
- x/capability/module.go
- x/crisis/module.go
- x/distribution/module.go
- x/evidence/module.go
- x/feegrant/module/module.go
- x/gov/module.go
- x/group/module/module.go
- x/mint/module.go
- x/slashing/module.go
- x/staking/module.go
- x/upgrade/module.go
BeginBlock, Endblock extension introduced in https://github.com/cosmos/cosmos-sdk/pull/12603
---
I have...
I have...
> chore: Check BeginBlock, Endblock extensions

- crypto/hd/hdpath.go
- crypto/keys/secp256k1/secp256k1.go
- crypto/keys/secp256k1/secp256k1_internal_test.go
- crypto/keys/secp256k1/secp256k1_nocgo.go
- crypto/keys/secp256k1/secp256k1_nocgo_test.go
- crypto/keys/secp256k1/secp256k1_test.go
- go.mod
- go.sum
- server/rosetta/converter.go
- simapp/go.mod
- simapp/go.sum
- tests/go.mod
- tests/go.sum
Similar to Tendermint's PR,
https://github.com/tendermint/tendermint/pull/9250
Note that crypto/ledger is not updated in this PR, because if its dependency on the R and S values being exposed by ParseDERSignature.
Closes #13423 
CC @odeke-em
> chore(crypto): update btcec to v2

- server/start.go
- server/types/app.go
- testutil/network/util.go
Amend #13497 such that we can still keep the feature while not breaking the existing `Application` interface.
---
I have...
I have...
> refactor: Amend #13497

- x/gov/keeper/msg_server.go
There is a warning when casting a `uint` to an `int`. For instance, [here](https://github.com/cosmos/cosmos-sdk/pull/13532/files#diff-50a11739adeec5335e446d4444326785c040c57da2c65abe9b9713aec18183ffR122). When it is just for a format, it does not make sense since `strconv` exposes a function for `uint`. This is the point of this PR.
---
I have...
I have...
- Had fails for `github.com/cosmos/cosmos-sdk/store/tools/ics23/iavl`, which seems unrelated.
> refactor: Use FormatUint instead of converting to int.

- docs/docs/basics/00-app-anatomy.md
- docs/docs/core/00-baseapp.md
- x/slashing/README.md
ref: https://github.com/cosmos/cosmos-sdk/issues/13456
I came across outdated documentation again and broken links. This removes them.
We do *not* need to merge this now (although we must before `v0.47` tagging).
We still need to go over all the documentation again, so more will probably come.
If the rendering issue is too pressing: https://docs.cosmos.network/main/core/baseapp#checktx, then we should merge, I'll create another PR later for removing outdated documentation.
---
I have...
I …
> docs: remove outdated documentation

- CHANGELOG.md
- x/distribution/keeper/delegation.go
- x/distribution/keeper/delegation_test.go
Related to https://github.com/cosmos/cosmos-sdk/pull/13340 and also noticed by Terra https://github.com/terra-money/cosmos-sdk/commit/996da0f5fc5783fc4aae896be643500df88680c2
In v0.45.9, the WithdrawDelegationRewards returns a invalid coins when delegation rewards are zero.  While this isn't state breaking, it does break state for modules depending on valid coins being returned without a zero value.
Technically an api breaking change from v0.45.9.
---
I have...
I have...
> fix: (v0.45.x) regression in return value of WithdrawDelegationRewards when rewards are zero

- CHANGELOG.md
- server/config/config.go
This PR adds back in, the setting of the `PruningKeepEvery` config field in `GetConfig`.
When #13321 was backported to v0.45.x (#13338), it accidentally carried with it a change to the server config's `GetConfig` function that removed the setting of the `PruningKeepEvery` field. That field has been removed in `main` and `release/v0.46.x`, but still exists in `release/v0.45.x`.
This PR is targeting `release/v0.45.x` because it is only applicable there.
---
I have...
I have...
> fix(server): v0.45.x Populate the PruningKeepEvery config entry in GetConfig.

- core/coins/format.go
Instead of 2 unnecessary int64(uint32) casts, then a negative check, this change checks magnitudes before the respective subtractions and then converts uint64(uint32) which avoids the possible integer overflow warnings generated by gosec.
Fixes https://github.com/cosmos/cosmos-sdk/security/code-scanning/6713
Fixes https://github.com/cosmos/cosmos-sdk/security/code-scanning/6714
Fixes https://github.com/cosmos/cosmos-sdk/security/code-scanning/6715
Fixes https://github.com/cosmos/cosmos-sdk/security/code-scanning/6716
> fix: core/coins: skip 2 int64(uint32) casts by comparison checks and silence gosec warnings

- tx/textual/internal/testdata/message.json
- tx/textual/internal/testdata/string.json
- tx/textual/internal/testpb/1.proto
- tx/textual/internal/testpb/1.pulsar.go
- tx/textual/valuerenderer/message.go
- tx/textual/valuerenderer/message_test.go
- tx/textual/valuerenderer/string.go
- tx/textual/valuerenderer/string_test.go
- tx/textual/valuerenderer/valuerenderer.go
Closes: #12713 
Refs: #12878
Sign mode textual value renderers for string and message.
I have...
I have...
> feat: string and message value renderers for textual

- api/cosmos/reflection/v1/reflection.pulsar.go
- proto/cosmos/reflection/v1/reflection.proto
Follow-up to #13597 so I don't need a go.mod `replace` in #13281 
---
I have...
I have...
> refactor!: simplify cosmos.reflection.v1

- CHANGELOG.md
- client/tx/factory.go
- client/tx/tx_test.go
Ref: https://github.com/cosmos/cosmos-sdk/issues/9122
This PR adds a validation check to prevent simple inclusion of a valid mnemonic in a tx by adding a validation to the tx factory.
I have...
I have...
> fix: prevent simple inclusion of a valid mnemonic

- CHANGELOG.md
Changelog.md incorrectly reference ics23 v8.0.0, instead of v0.8.0.
This PR rectifies this.
No functional change.
> chore: update CHANGELOG.md to correctly reference ics23 version

- simapp/simd/cmd/root.go
On `main` every time you'd run only `simd`, a `data` directory was created in the current path.
---
I have...
I have...
> fix: stop creating empty `data` dir

- x/group/internal/orm/index.go
- x/group/internal/orm/table.go
Instead of nakedly always returning nil, instead return the actual close errors.
Fixes https://github.com/cosmos/cosmos-sdk/security/code-scanning/6295
Fixes https://github.com/cosmos/cosmos-sdk/security/code-scanning/6296
> fix: x/group/internal/orm: return iterator close errors

- CHANGELOG.md
ref: #13673 
---
I have...
I have...
> chore: fix --dry-run flag not working issue's changelog

- CHANGELOG.md
- RELEASE_NOTES.md
Closes: #XXXX
---
I have...
I have...
> chore: prepare 0.46.4 changelog

- .github/workflows/tag.yml
- CHANGELOG.md
ref https://github.com/cosmos/cosmos-sdk/pull/13674#issuecomment-1298832284
---
I have...
I have...
> ci: notify for 0.45.x releases

- docs/docusaurus.config.js
Closes: #13488
---
I have...
I have...
> docs: fix algolia

- docs/.vuepress/config.js
Follow-up of #13729
---
I have...
I have...
> docs: fix algolia on 0.45

- README.md
https://tokei.rs/ returns an HTTP 502
> fix: remove broken lines of code badge

- testutil/cli/tm_mocks.go
- x/auth/client/cli/suite_test.go
- x/authz/client/cli/tx_test.go
- x/bank/client/cli/query_test.go
- x/bank/client/cli/suite_test.go
- x/crisis/client/cli/tx_test.go
- x/distribution/client/cli/suite_test.go
- x/evidence/client/cli/tx_test.go
- x/feegrant/client/cli/tx_test.go
- x/genutil/client/cli/gentx_test.go
- x/gov/client/cli/tx_test.go
- x/group/client/cli/tx_test.go
- x/mint/client/cli/query_test.go
- x/nft/client/cli/tx_test.go
- x/slashing/client/cli/query_test.go
- x/staking/client/cli/tx_test.go
- x/upgrade/client/cli/tx_test.go
ref: https://github.com/cosmos/cosmos-sdk/pull/13692#discussion_r1012135353
---
I have...
I have...
> refactor: extract `MockTendermintRPC` to `testutil/cli`

- go.mod
- go.sum
- simapp/go.mod
- simapp/go.sum
- simapp/test_helpers.go
- testutil/sims/app_helpers.go
As simapp must not be imported and helpers have been extracted to testutil/sims` 
Removes unnecessary helpers from SimApp. 
---
I have...
I have...
> refactor: cleanup simapp

- CHANGELOG.md
- store/iavl/store.go
Ref: #12012
A set failure will eventually trigger an app-hash mismatch, which is a headache to investigate without any error logs.
---
I have...
I have...
> refactor: add error log when iavl set failed

- CHANGELOG.md
- server/export.go
- tests/e2e/server/export_test.go
Closes: #13331
Add --output-document flag to the export CLI command to allow writing genesis state to a file.
Added a new flag `--output-ducument` for `simd export`.
```shell
$ simd export --help
Export state to JSON
Usage:
simd export [flags]
Flags:
...
--output-document string       Exported state is written to the given file instead of STDOUT
```
---
I have...
I have...
> feat: add --output-document flag to the export CLI command to allow writing genesis state to a file instead of STDOUT

- baseapp/msg_service_router.go
adds sanity check to prevent foot guns for app devs 
---
I have...
I have...
> chore: add sanity check in handler 

- CHANGELOG.md
- UPGRADING.md
- tests/e2e/nft/grpc.go
- x/nft/README.md
Follow-up of #13836 for docs.
---
I have...
I have...
> docs: add documentation for nft module

- CHANGELOG.md
- x/bank/migrations/v046/keys.go
- x/bank/migrations/v046/store.go
- x/bank/migrations/v046/store_test.go
Closes: #XXXX
---
I have...
I have...
> feat(bank): Add helper for v0.46 denom migration

- CHANGELOG.md
- RELEASE_NOTES.md
After this PR we can release 0.46.5.
---
I have...
I have...
> chore: impove 0.46.5 release notes

- x/group/internal/math/dec.go
Closes: #13912
---
I have...
I have...
> chore: remove typo

- types/coin.go
Simplifies and makes clearer the code in removeZeroCoins by removing unnecessary checks that boiled down to still running in the same final for loop.
Fixes #13958
> fix: types: remove unnecessary/pedantic code from removeZeroCoins

- CHANGELOG.md
- go.mod
- go.sum
Closes: #XXXX
---
I have...
I have...
> chore: bump tendermint to 0.34.24

- crypto/types/compact_bit_array.go
Noticed while examining a bunch of profiles, that the for loop inside (*CompactBitArry).NumTrueBitsBefore unnecessarily consumed a bunch of time:
```shell
7.55s      9.88s (flat, cum) 93.38% of Total
240ms      250ms     88:func (bA *CompactBitArray) NumTrueBitsBefore(index int) int {
.          .     89:	onesCount := 0
70ms      340ms     90:	max := bA.Count()
70ms       70ms     91:	if index > max {
.          .     92:		index = max
.          .     93:	}
.          .     94:	// below we iterate over the bytes then over bits (in low endian) and count bits set to 1
2.54s      2.76s     95:	for elem := 0; elem < len(bA.Elems); elem++ {
```
but we can use the native for loop that produces indices while iterating over slices. Just by simply changing the form results in an improvement …
> perf: crypto/types: use native slice index producing for loop in (*CompactBitArry).NumTrueBitsBefore

- tools/cosmovisor/args.go
Fixes #14031
Fixes https://github.com/cosmos/cosmos-sdk/security/code-scanning/6794
> fix: tools/cosmovisor: return on failing to remove existing symlink

- CHANGELOG.md
- baseapp/options.go
- snapshots/types/options.go
Fix for
Closes: #13766
---
I have...
I have...
> fix(baseapp): fix snapshot interval bug

- .github/PULL_REQUEST_TEMPLATE.md
Minor one. Fix the broken link to the [building modules](https://github.com/cosmos/cosmos-sdk/blob/main/docs/docs/building-modules) doc.
---
I have...
I have...
> chore: fix link to "building modules" doc

- CHANGELOG.md
- baseapp/abci.go
- baseapp/streaming.go
- store/streaming/file/service.go
Use go context on abcilistener instead of sdk native context. 
Im not sure if I need to unwrap the context before? 
---
I have...
I have...
> refactor: use go context instead of sdk.Context

- math/CHANGELOG.md
- math/dec.go
- math/int.go
- math/int_test.go
Optimizes and tests FormatInt by removing inefficient string concatenation but also making it so much clearer with how one would express adding thousand separators in natural language. It uses a combination of strings.Builder whose values can be grown
The performance improvement is stark in every dimension:
```shell
$ benchstat before.txt after3.txt
name                          old time/op    new time/op    delta
DecimalValueRendererFormat-8    4.48µs ± 1%    2.11µs ± 2%  -52.90%  (p=0.000 n=10+10)
name                          old alloc/op   new alloc/op   delta
DecimalValueRendererFormat-8    3.62kB ± 0%    0.78kB ± 0%  -78.59%  (p=0.000 n=10+10)
name                          old allocs/op  new allocs/op  delta
DecimalValueRendererFormat-8      83.0 ± 0%      28.0 ± 0%  -66.27% …
```
> fix: math: optimize and test FormatInt + simplify LegacyNewDecFromStr

- server/start.go
ref https://github.com/cosmos/cosmos-sdk/issues/13695#issuecomment-1331819707
Note: 0.46 already contains the change but we backport for adding the comment.
---
I have...
I have...
> fix: do not shadow clientCtx in start.go

- x/auth/ante/fee.go
Closes: #XXXX
Right now this error message contains the word "not" twice. I don't think we want the double negative here ;-)
Example:
```
regen1sk9nwk0w7kct04tsdscqvg5knn6kzz7yq59arx does not not allow to pay fees for regen1n9dpmra4d2gvu22jmxv7tenjy0mdymfg70hd48: basic allowance: fee limit exceeded
```
---
I have...
I have...
> chore: correct language for fee granter error

- server/config/config_test.go
Closes: #13955
---
I have...
I have...
> chore: Test for Server Config Read

- runtime/app.go
Fixes an inconsistency in checking for duplicates in ModuleManager's Modules[name] then also basicManager[name] in which memoization could happen for .Module[name] but fail after a duplicate check in basicManager[name]. This change instead only memoizes the AppModule after the duplicate checks have all cleared.
Fixes #14006
> fix: runtime: fix (*App).RegisterMoodules inconsistency in checking/memoizing appModule

- server/config/config.go
- server/config/toml.go
default should be safer than unbound 
---
I have...
I have...
> chore: bound mempool size by default

- crypto/ledger/ledger_mock.go
- crypto/ledger/ledger_notavail.go
- crypto/ledger/ledger_secp256k1.go
- go.mod
- simapp/go.mod
- simapp/go.sum
- tests/go.mod
- tests/go.sum
ref: https://github.com/cosmos/cosmos-sdk/pull/13513#issuecomment-1334018225
kindly pinging @elias-orijtech
```go
cd crypto/ledger
go test ./... -tags='ledger,test_ledger_mock'
ok      github.com/cosmos/cosmos-sdk/crypto/ledger      0.118s
```
---
I have...
I have...
> refactor: update crypto/ledger to btcec/v2

- CHANGELOG.md
- server/mock/app_test.go
- server/util.go
- simapp/simd/cmd/root.go
provide a simple Defaultbaseapp options function so we can avoid chains missing when we add flags. 
---
I have...
I have...
> refactor: provide a helper for baseapp options

- types/handler_test.go
remove unnecessary test suite for a single test 
---
I have...
I have...
> refactor: remove suite from chaindecorator handler test

- .github/workflows/build.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/dependabot-update-all.yml
- .github/workflows/dependencies-review.yml
- .github/workflows/lint.yml
- .github/workflows/release-cosmovisor.yml
- .github/workflows/release-rosetta.yml
- .github/workflows/release.yml
- .github/workflows/sims-045.yml
- .github/workflows/sims-046.yml
- .github/workflows/sims-047.yml
- .github/workflows/sims-nightly.yml
- .github/workflows/sims.yml
- .github/workflows/test.yml
- simapp/go.mod
- simapp/go.sum
- tools/cosmovisor/RELEASE_NOTES.md
- tools/rosetta/.goreleaser.yml
- tools/rosetta/RELEASE_NOTES.md
Closes: #XXXX
---
I have...
I have...
> ci: add goreleaser for rosetta and add go cache

- types/query/fuzz_test.go
Motivated during a security audit that found some crashes from code that uses types.query.Paginate, this change adds a fuzzer that'll leverage oss-fuzz to run continuously.
> test: types/query: add fuzzer for Paginate

- client/flags/flags.go
- go.mod
Superseed https://github.com/cosmos/cosmos-sdk/pull/14243
Fixes the GRPC flag conflict that reads a map by default.
This breaks all queries wherever https://github.com/cosmos/cosmos-sdk/pull/14051 has been merged. 
---
I have...
I have...
> fix: fix grpc flag conflict

- baseapp/baseapp.go
- types/handler.go
Addressing feedback from comments in https://github.com/cosmos/cosmos-sdk/pull/13940.
Closes: #XXXX
---
I have...
I have...
> fix: Added godoc for the PostHandler and reference comment for follow up PR

- x/gov/README.md
Closes: #14312
cc @ysv, is this wording clearer for you?
---
I have...
I have...
> docs: improve voting wording

- server/config/config.go
- server/config/toml.go
- server/grpc/gogoreflection/fix_registration.go
- server/grpc/grpc_web.go
- server/mock/helpers.go
- server/util.go
ref: #14256
---
I have...
I have...
> chore: audit server package

- CHANGELOG.md
- UPGRADING.md
- baseapp/baseapp.go
- types/events.go
- types/events_test.go
Closes: #14295
---
I have...
I have...
> fix: improve baseapp event emission

- CHANGELOG.md
- docs/spec/SPEC_MODULE.md
- tests/integration/distribution/keeper/delegation_test.go
- tests/integration/staking/keeper/slash_test.go
- tests/integration/staking/keeper/validator_test.go
- testutil/mock/types_module_module.go
- types/module/module_test.go
- x/evidence/keeper/infraction.go
- x/evidence/testutil/expected_keepers_mocks.go
- x/evidence/types/expected_keepers.go
- x/slashing/README.md
- x/slashing/keeper/infractions.go
- x/slashing/keeper/keeper.go
- x/slashing/keeper/keeper_test.go
- x/slashing/testutil/expected_keepers_mocks.go
- x/slashing/types/expected_keepers.go
- x/staking/keeper/slash.go
- x/staking/keeper/slash_test.go
- x/staking/testutil/expected_keepers_mocks.go
- x/staking/types/expected_keepers.go
Remembered a conversation about reverting the breaking change when auditing x/slashing.
ref: https://github.com/cosmos/cosmos-sdk/issues/14255, https://github.com/cosmos/cosmos-sdk/issues/14158
---
I have...
I have...
> refactor: revert API breaking change on Slash

- baseapp/abci.go
- baseapp/abci_test.go
- x/bank/keeper/grpc_query.go
Closes: #14375
---
I have...
I have...
> fix: panic recovery in PrepareProposal and ProcessProposal Handlers

- CHANGELOG.md
- types/context.go
- types/events.go
This PR modifies the `sdk.Context` to support passing in the EventManager as an interface. This is useful for chains who want to add custom event behaviour to their application.
> refactor(context): Pass `EventManager` to the context as an interface.

- docs/docs/building-apps/02-app-mempool.md
ref: https://github.com/cosmos/cosmos-sdk/pull/14381#discussion_r1055375873
---
I have...
I have...
> docs:  update mempool/ABCI docs

- CHANGELOG.md
- x/gov/migrations/v046/convert.go
- x/gov/migrations/v046/convert_test.go
backport #14347
---
I have...
I have...
> feat(gov): support v1.Proposal in v1beta1.Proposal.Content (backport #14347)

- x/gov/genesis.go
- x/gov/migrations/v4/json_test.go
- x/gov/types/v1/genesis.go
ref: #14358, https://github.com/cosmos/cosmos-sdk/issues/14093#issuecomment-1357805499
Checked migrate genesis that works properly from a 0.46 genesis vs 0.47 genesis.
---
I have...
I have...
> fix(gov): don't export deprecated params

- CHANGELOG.md
- x/gov/migrations/v046/store.go
Ref: https://github.com/cosmos/cosmos-sdk/pull/14335#issuecomment-1358516057
If you are already on 0.46 and you have ongoing proposal with voting during the 0.46.7 migration then the following line will fail:
https://github.com/cosmos/cosmos-sdk/blob/v0.46.7/x/gov/migrations/v046/store.go#L54
If you are not on v0.46 and planning to migrate to v0.46, then the module migration will update the votes anyway. 
We don't need to expose that function.
---
I have...
I have...
> feat!: remove x/gov/migrations/v046.Migrate_V046_6_To_V046_7

- .golangci.yml
This PR increases the golangci-lint timeout to 10 minutes, and tells it to run concurrently.
It is not worthy of a changelog entry.
reason: I noticed the linter had timed out in 
* #14410 
---
I have...
I have...
> chore: longer golang-ci timeout

- CHANGELOG.md
- baseapp/baseapp.go
- server/mock/store_test.go
- store/cachekv/benchmark_test.go
- store/store.go
- testutil/context.go
- x/group/internal/orm/testsupport.go
- x/group/keeper/invariants_test.go
- x/params/types/subspace_test.go
pass logger to store instead of always setting NoOplogger 
---
I have...
I have...
> refactor: pass logger to store

- store/rootmulti/store.go
From what I read, LSM backend used by the sdk prefer the keys to be commited in ascending order. Right now, there's no logic enforcing the order of `rootmulti.Store.stores` and so when `rootmulti.Store` commit, we can't be sure that we're commiting the module stores in ascending order. 
---
I have...
I have...
> chore: Enforce order of store commits in root store

- baseapp/block_gas_test.go
- baseapp/utils_test.go
- x/auth/testutil/app_config.go
- x/authz/testutil/app_config.go
- x/capability/testutil/app_config.go
- x/distribution/testutil/app_config.go
- x/evidence/testutil/app_config.go
- x/feegrant/testutil/app_config.go
- x/group/testutil/app_config.go
- x/mint/testutil/app_config.go
- x/nft/testutil/app_config.go
- x/params/testutil/app_config.go
- x/slashing/testutil/app_config.go
- x/staking/testutil/app_config.go
Thanks to https://github.com/cosmos/cosmos-sdk/pull/14415 we can clean up the different app config with the strict minimum.
---
I have...
I have...
> chore: clean-up app config

- docs/architecture/adr-024-coin-metadata.md
`name` is a mandatory field and should be present in this example.
Origin:  https://github.com/ignite/cli/issues/3351
Related code: https://github.com/cosmos/cosmos-sdk/blob/main/x/bank/types/metadata.go#L20
---
I have...
I have...
> docs: add missing field in denom metadata example

- CHANGELOG.md
- x/gov/README.md
- x/group/README.md
It makes more sense if the `authors` field in the proposal metadata is an array of strings instead of single string (since a proposal can have more than one authors).
Discussion on twitter: https://twitter.com/hxrts/status/1608373720996880387
---
I have...
I have...
> docs: use an array of strings as authors in proposal metadata

- tests/integration/store/rootmulti/rollback_test.go
Closes: #14496 
ref : #14145 #12332
---
I have...
I have...
> chore: Replace testify with gotest.tools in store tests

- tests/integration/slashing/keeper/keeper_test.go
Closes: #14498 
ref: #14145 #12332 
---
I have...
I have...
> chore: Replace testify with gotest.tools in slashing integration tests

- CHANGELOG.md
- x/group/keeper/keeper_test.go
- x/group/keeper/msg_server.go
Closes: https://github.com/cosmos/cosmos-sdk/issues/14485
Noticed that we don't actually don't test events in group. I've just added a check on some others tests.
I did not do it everywhere because one annoying thing is that the tests use the same context.
When we remove the suite, we should check the events properly too.
---
I have...
I have...
> fix: wrong address set in `EventUpdateGroupPolicy`

- CHANGELOG.md
- simapp/state.go
- testutil/sims/simulation_helpers.go
- types/module/simulation.go
- x/auth/simulation/genesis.go
- x/bank/simulation/genesis.go
- x/bank/simulation/genesis_test.go
- x/gov/simulation/genesis.go
- x/gov/simulation/genesis_test.go
- x/mint/simulation/genesis.go
- x/mint/simulation/genesis_test.go
- x/staking/simulation/genesis.go
- x/staking/simulation/genesis_test.go
- Add new property `BondDenom` to `SimulationState` struct in `types/module/simulation.go`
- Changed the `x/modules/simulation/genesis.go` mostly to use the new property
---
I have...
I have...
> refactor: add option to set `bondDenom` on simulations

- CHANGELOG.md
- x/bank/keeper/grpc_query.go
- x/bank/keeper/grpc_query_test.go
- x/bank/keeper/view.go
Closes: #14536
---
I have...
I have...
> fix: validate denom in bank grpc queries

- x/bank/types/send_authorization.go
- x/bank/types/send_authorization_test.go
Closes: #XXXX
We don't need changelog as it was never released.
---
I have...
I have...
> fix: fix allow list bypassed when whole spend limit used

- core/store/store.go
return error on store interface instead of panic 
---
I have...
I have...
> refactor:  add error to store interface

- crypto/types/multisig/multisignature.go
Closes: #8027
---
I have...
I have...
> refactor: use len check instead of nil check in multisignature

- CHANGELOG.md
- api/cosmos/base/snapshots/v1beta1/snapshot.pulsar.go
- proto/cosmos/base/snapshots/v1beta1/snapshot.proto
- snapshots/types/snapshot.pb.go
-> PR against main https://github.com/cosmos/cosmos-sdk/pull/14597 
See https://github.com/cosmos/cosmos-sdk/pull/14591#discussion_r1068044503
It is not clear for me what is the consensus. If we want to re-add it, here is a PR for it.
Otherwise, we can just leave it as it.
---
I have...
I have...
> chore: deprecate unused messages instead of removing them

- CHANGELOG.md
- RELEASE_NOTES.md
- go.mod
- go.sum
Prepare v0.46.8 release.
Add replace to point to Informal System fork of Tendermint (as per [twitter.com/informalinc/status/1613580977980473346](https://twitter.com/informalinc/status/1613580977980473346)).
Changes tested against a Quicksilver node (`v0.46.8-0.20230107121918-36784a8a7a93`).
---
I have...
I have...
> chore: prepare v0.46.8 release 

- store/streaming/file/service_test.go
Ran `make test` before tagging, and this showed up.
We had the same issue in v0.46 last time, and we fixed it.
---
I have...
I have...
> fix: fix failing test in 0.45

- CHANGELOG.md
- store/cachekv/internal/btree.go
- store/cachekv/store.go
- store/cachekv/store_test.go
Closes: #14786
Solution:
- do a copy on btree before iteration
minimal change to fix the iteration issue compared with #14378, I guess it's not consensus breaking because it fix a bug which is probably not triggered on production yet?
---
I have...
I have...
> fix: nested iterator on cache store

- .gitignore
- depinject/debug.go
Closes: #12575
This should make working with depinject a bit nicer.
Needs to be tested manually.
---
I have...
I have...
> feat(depinject): send logging to file instead of stderr

- types/config.go
Closes: #6782
This pr merely changes the lock to a readlock for checking if the config is sealed. Id say this is Fine to close the issue, we have a larger issue on refactor the config global that explains the proposal better. 
---
I have...
I have...
> chore: change lock to Rlock

- tools/confix/data/v0.46-app.toml
- tools/confix/data/v0.47-app.toml
- tools/confix/data/v0.48-app.toml
ref: https://github.com/cosmos/cosmos-sdk/pull/14863/files#r1093608866
This is what I meant in my message, for Confix to work standalone, we need to keep in sync the configuration with the latest changes.
---
I have...
I have...
> chore: add `iavl-lazy-loading` in standalone confix

- .github/workflows/test.yml
- contrib/rosetta/configuration/data.sh
- contrib/rosetta/docker-compose.yaml
- server/start.go
I wondered why https://github.com/cosmos/cosmos-sdk/pull/14888 needed to enable the API server, while it was needing only the GRPC server.
Turns out this PR https://github.com/cosmos/cosmos-sdk/pull/14652 added a regression, where the gRPC server was only started when the API server is (as gRPC-Web and gRPC-Gateway are on the same port, we need a gRPC instance there).
This PR adds a condition to still start the gRPC server even when the API is disabled.
We can then revert https://github.com/cosmos/cosmos-sdk/pull/14888 as well.
No changelog required because we are on main and this was never released.
---
I have...
*All items are required. Please add …
> fix: allow grpc server enabled even when api off

- log/go.mod
- log/go.sum
- log/logger.go
- log/noop_logger.go
the difference in return value on the method `With` breaks compatibility with Comet's logger interface 
---
I have...
I have...
> refactor: modify interface to match comets

- CHANGELOG.md
- x/staking/genesis.go
Updates: https://github.com/crypto-org-chain/chain-main/pull/918
---
I have...
I have...
> fix: return named error for write validators

- CHANGELOG.md
- store/rootmulti/store.go
Closes: #14916
Exclude in-mem KVStore from Commit info commitments. 
---
I have...
I have...
> fix: exclude mem store from commit info

- x/authz/README.md
Closes: #11990 
---
I have...
I have...
> docs: update authz docs with pruning details

- CHANGELOG.md
- RELEASE_NOTES.md
Closes: #XXXX
---
I have...
I have...
> chore: prepare v0.45.13 release notes

- docs/architecture/adr-050-sign-mode-textual.md
- x/tx/textual/encode.go
- x/tx/textual/internal/testdata/tx.json
Small clean-ups after a post-merge review from @JimLarson of #14730. ref: https://github.com/cosmos/cosmos-sdk/pull/14730#discussion_r1090864374
---
I have...
I have...
> chore: Clean-ups after Textual Title/Content PR

- CHANGELOG.md
- crypto/keys/secp256k1/secp256k1_test.go
- simapp/app_v2.go
- simapp/params/params.go
- simapp/sim_bench_test.go
- simapp/sim_test.go
- testutil/sims/state_helpers.go
Closes: https://github.com/cosmos/cosmos-sdk/issues/14971, https://github.com/cosmos/cosmos-sdk/issues/13379
Thanks @gjermundgaraba for noticing! This will be helpful for v0.47+.
The UGPRADING.md already contains sufficient information.
---
I have...
I have...
> refactor!: extract `AppStateFn` out of simapp

- CHANGELOG.md
- types/events.go
Closes: #14983 
---
I have...
I have...
> fix: allow unknown fields in ParseTypedEvent

- x/gov/keeper/deposit.go
TL;DR: the code tried to delete all deposits with a prefix, this doesn't work. We need to delete each deposit with its own key.
Previously it was trying to delete a non-existing key, so when comparing the balance of the gov module account vs the amount of deposits they didn't match because the deposit tokens were burnt/refunded but the deposit object was never deleted.
Also included some renamings of variables to make it easier to read
---
I have...
I have...
> fix: x/gov ChargeDeposit delete deposits

- CHANGELOG.md
- x/capability/capability_test.go
- x/capability/keeper/keeper.go
Closes: #15015
The `capability` module's `InitMemStore` function increments `gasMeter` non-deterministically across validators.
When a validator is restarted, [InitMemStore](https://github.com/dydxprotocol/cosmos-sdk/blob/bc3d81996dfcb6d823596a9c2dbf73dce4337dd6/x/capability/module.go#L153) is called during `BeginBlock` of the next committed block. This function performs some store operations which increment `GasUsed` on the `GasMeter` [here](https://github.com/dydxprotocol/cosmos-sdk/blob/bc3d81996dfcb6d823596a9c2dbf73dce4337dd6/x/capability/keeper/keeper.go#L125-L145).
So long as `SetGasMeter` is always called as part of the AnteHandler chain (which is the current behavior of the default AnteHandler chain [here](https://github.com/dydxprotocol/cosmos-sdk/blob/dydx-fork-v0.47.0-alpha2/x/a …
> fix: `x/capability` `InitMemStore` should not consume gas

- CHANGELOG.md
- baseapp/msg_service_router.go
- x/authz/keeper/keeper.go
- x/authz/module/module.go
- x/gov/keeper/keeper.go
- x/group/keeper/keeper.go
- x/group/keeper/proposal_executor.go
Closes: #15023 
provide an interface for message router instead of passing the direct type to modules
this is a stop gap until we land adr33
---
I have...
I have...
> chore: add message router interface

- x/auth/vesting/README.md
update vesting readme to reflect other message types that are supported 
---
I have...
I have...
> chore: update vesting readme

- types/mempool/priority_nonce.go
- types/mempool/priority_nonce_test.go
- types/mempool/sender_nonce.go
- Following the robustness principle (thanks @kocubinski for pointing out the name that I never knew)
- Make mempool types public
- Return concrete types from constructors
- Use the bech32 address instead of the public key HEX string
- Implement `NextSenderTx` (I'm open to adding this to the interface) 
---
I have...
I have...
> chore: UX Mempool Tweaks

- core/appconfig/config_test.go
- core/appmodule/option.go
Remove one duplicated import, and prefer to append a slice rather than iterating over each element to be appended.
---
I have...
I have...
> chore(core): fix staticcheck issues

- orm/model/ormdb/module_test.go
- orm/model/ormtable/table_impl.go
- orm/model/ormtable/table_test.go
There were several errors that were unchecked, all but one in test code. Discovered with staticcheck.
---
I have...
I have...
> chore(orm): add missing error checks

- CHANGELOG.md
- client/flags/flags.go
- x/genutil/client/cli/init.go
- x/genutil/client/cli/init_test.go
Closes: #15027.
Added flag "--initial-height" to the init command. Tested manually. LMK if that needs to be covered.
The parameter needs to be provided as int, because the genesis doc accepts int. However, this PR defaults negative block heights to 1.
---
I have...
I have...
> feat: add --initial-height flag to cli init cmd

- x/tx/aminojson/json_marshal_test.go
- x/tx/textual/bench_test.go
- x/tx/textual/coin_test.go
- x/tx/textual/message.go
Fix one unchecked error in test, one copy-paste error that resulted in a benchmark checking the wrong set of values, one warning about use of context.WithValue, and one ineffective variable assignment.
---
I have...
I have...
> chore(tx): fix staticcheck issues

- log/CHANGELOG.md
- log/bench_test.go
- log/zerolog.go
The zerolog Fields method accepts a `[]any` in the same format we use in the Logger interface's methods, so translating the slice to a map is unnecessary.
Include microbenchmark to prove this difference.
Before omitting getLogFields:
```
BenchmarkLoggers/zerolog/empty_key_vals-10         	11605411	        90.57 ns/op	      24 B/op	       1 allocs/op
BenchmarkLoggers/zerolog/single_string-10          	 6691237	       179.2 ns/op	      56 B/op	       3 allocs/op
BenchmarkLoggers/zerolog/single_small_int-10       	 6597535	       182.6 ns/op	      56 B/op	       3 allocs/op
BenchmarkLoggers/zerolog/single_largeish_int-10    	 6357801	       189.6 ns/op	      56 B/op	       3 allocs/op
BenchmarkLoggers/zerolog/single_float-10           	 5022015	       240.0 ns/op	      56 B/op	       3 …
```
> refactor(log): elide keyval translation to map

- .github/dependabot.yml
Spreads the checks of the go.mod through the week.
Normally we should only care about `/` and `/simapp` thanks to the scripts that automatize the dependency bumping in all modules. However, on Monday, if there is a dependency update, then we get a big spam.
---
I have...
I have...
> ci: limit dependabot spam

- CHANGELOG.md
- x/gov/keeper/keeper.go
- x/gov/module.go
- x/group/module/module.go
use message router interface instead of concrete impl throughout 
ref: #15035 
---
I have...
I have...
> chore: use message router interface

- server/grpc/server_test.go
- tests/e2e/tx/service_test.go
- types/module/module_int_test.go
- x/authz/keeper/grpc_query_test.go
- x/capability/keeper/keeper_test.go
- x/group/keeper/keeper_test.go
- x/upgrade/abci_test.go
- x/upgrade/plan/downloader_test.go
- x/upgrade/plan/info_test.go
There were several test suite methods that had a value receiver, and which were being ignored for linting. Instead of ignoring the error, use pointer receivers to properly avoid lock copying.
And use a local copy of one loop variable in a possible closure.
---
I have...
I have...
> test: use pointer receivers to avoid lock copies

- tests/integration/bank/keeper/deterministic_test.go
On CI, with an unrelated change, we observed
`TestGRPCQuerySpendableBalances` failing with this message:
```
deterministic_test.go:156: [rapid] panic after 26 tests: invalid coin set 1A..,1A..: duplicate denomination A..
```
This occurred at: https://github.com/cosmos/cosmos-sdk/actions/runs/4304610752/jobs/7505884172#step:5:42
As noted in the message, this was reproducible with passing `-rapid.seed=17310147078983591311`.
Instead of several independent calls to producing a string with rapid, prefer `rapid.SliceOfNDistinct` in order to ensure that all denoms are unique, thereby avoiding the panic in `sdk.NewCoins`.
---
I have...
*All items are …
> test: fix flakiness due to duplicate denoms

- server/grpc/server_test.go
NewClient was deprecated in favor of NewClientAuto, in jhump/protoreflect v1.14.0. Dependabot recently updated us from v1.12 to v1.15, and the linter has been complaining about the use of the deprecated function.
---
I have...
I have...
> test(server/grpc): avoid using deprecated protoreflect function

- client/docs/config.json
- client/docs/swagger-ui/swagger.yaml
- docs/.gitignore
- docs/build-all.sh
- docs/post.sh
- docs/pre.sh
- docs/sidebars.js
- x/README.md
Closes: https://github.com/cosmos/cosmos-sdk/issues/15112
ref: https://github.com/cosmos/cosmos-sdk/pull/15209#issuecomment-1450586804
Note: there is no endpoint to query behind, as it will be the same swagger that there are on nodes, but on GH Pages (where our docs is deployed).
---
I have...
I have...
> docs: add swagger ui in docs

- CHANGELOG.md
- client/grpc/cmtservice/util.go
- tests/e2e/client/grpc/cmtservice/service_test.go
Closes: #14079
`LatestBlockResponse` & `BlockByHeightResponse` types'  field `sdk_block` was incorrectly casted `proposer_address` bytes to `cosmosvaloper` address. But Tendermint/CometBFT return bytes of consensus address `cosmosvalcons`. 
---
I have...
I have...
> fix: Change proposer address cast for `sdk_block` conversion

- log/bench_test.go
- log/logger.go
And clean up a couple benchmarks, to move unrelated allocations out of the hot loop.
The specialized nop logger runs about 3x faster than the zerolog wrapper around a zerolog.Nop instance.
Since the nop logger is part of the exported API, and since the implementation is very simple, we should continue to offer the faster version.
---
I have...
I have...
> refactor(log): restore customized nop logger

- CHANGELOG.md
- crypto/keyring/keyring.go
The gosec linter has been complaining about this. On one hand, it's just a hash, but on the other hand, there is no apparent reason it needs to be readable by anyone other than the owner.
Also use the preexisting keyhashFilePath variable, instead of concatenating a forward-slash value, which may not work properly on Windows.
---
I have...
I have...
> fix(crypto/keyring): disallow non-owner reads of keyhash

- x/bank/keeper/keeper.go
@julienrbrt 
(can get really spammy when we run our evm's estimate gas)
> perf(x/bank): 👉🥺👈 (reduce logging verbosity)

- CHANGELOG.md
- x/bank/keeper/keeper.go
- x/gov/testutil/expected_keepers_mocks.go
Adds `GetAllDenomMetaData` to the bank keeper interface. This enables other modules to refer to it in their `expected_keepers`, for example in `x/wasm`. This PR is therefore a prerequisite for adding denom metadata querying to cosmwasm.
---
I have...
I have...
> feat(x/bank): update keeper interface to include GetAllDenomMetaData

- CHANGELOG.md
- x/genutil/collect.go
this pr removes the requirement of having an ip in memo field when collecting gen txs 
---
I have...
I have...
> chore: remove requirement on user ips

- CHANGELOG.md
- simapp/state.go
- types/simulation/types.go
backport: https://github.com/cosmos/cosmos-sdk/pull/15305
---
I have...
I have...
> feat: add extend cb to avoid unmarshal state twice for sim test (backport: #15305)

- CHANGELOG.md
- x/staking/types/authz.go
This PR addresses review comments on #15164.
---
I have...
I have...
> chore: address review comments on #15164

- CHANGELOG.md
- UPGRADING.md
IBC and CosmWasm were getting issues from v0.47 where goleveldb was bumped to a broken version.
In the backported PR we can add the replace in siampp too.
---
I have...
I have...
> docs: update replace mention in UPGRADING.md

- CHANGELOG.md
- simapp/state.go
fix backport: https://github.com/cosmos/cosmos-sdk/pull/15305 to align [genesisState](https://github.com/cosmos/cosmos-sdk/blob/release/v0.47.x/testutil/sims/state_helpers.go#L48) with v0.47.x
---
I have...
I have...
> feat: add extend cb with genesisState for sim test (backport: #15305)

- docs/rfc/README.md
- docs/rfc/_category.json
- docs/rfc/rfc-template.md
This pr adds an RFC section for items that may not need adrs right away or to capture ongoing conversations 
---
I have...
I have...
> docs: add rfc section

- x/gov/keeper/proposal.go
- x/gov/simulation/decoder.go
- x/gov/types/keys.go
Fixes a bug in which the VotingPeriodProposal index would remain when calling `DeleteProposal`. Previously we were doing this only when calling `SetProposal`.
This was the cause of simulations failing on main, because the proposal was being deleted but this key wasn't so when importing the state in a second app this key wasn't being re-created (because there was no proposal); so when comparing the states, this key was missing.
---
I have...
I have...
> fix: delete VotingPeriodProposalKey when deleting proposal

- CHANGELOG.md
- tools/cosmovisor/CHANGELOG.md
- tools/cosmovisor/README.md
- tools/cosmovisor/args.go
- tools/cosmovisor/args_test.go
- tools/cosmovisor/cmd/cosmovisor/run.go
- tools/cosmovisor/cmd/cosmovisor/version.go
Closes: #15359
Introduces DAEMON_DISABLE_LOGS env variable for Cosmovisor, when set to true, Cosmovisor won't write any logs into stdout. That is useful when you need to run a subcommand that returns a valid JSON but Cosmovisor's logging makes it invalid.
Additionally, I removed the logic with always disabled logging in `cosmovisor version --output json`, as this is redundant and isn't as flexible as the DAEMON_DISABLE_LOGS approach.
---
I have...
I have...
> feat: allow disabling cosmovisor logs

- tools/cosmovisor/CHANGELOG.md
- tools/cosmovisor/README.md
- tools/cosmovisor/cmd/cosmovisor/config.go
- tools/cosmovisor/cmd/cosmovisor/init.go
- tools/cosmovisor/cmd/cosmovisor/main.go
- tools/cosmovisor/cmd/cosmovisor/root.go
- tools/cosmovisor/cmd/cosmovisor/run.go
- tools/cosmovisor/cmd/cosmovisor/run_test.go
- tools/cosmovisor/cmd/cosmovisor/version.go
- tools/cosmovisor/cmd/cosmovisor/version_test.go
ref https://github.com/cosmos/cosmos-sdk/issues/15360#issuecomment-1465178429
ref https://github.com/cosmos/cosmos-sdk/pull/15362#discussion_r1133254426
---
I have...
I have...
> feat(cosmovisor): add install disclaimer and config command

- .github/workflows/test.yml
The issue is sonarcloud does not run on forks from external contributors.
This is what prohibited us to make the job of our components required.
This PR replicates https://github.com/cosmos/interchain-security/pull/768.
I have purposely not added this logic our `repo-analysis` job as it makes no sense, as this job will never be required.
IMO, afterward, we should make all `test-*` required (cc @tac0turtle).
---
I have...
I have...
> ci: disable sonarcloud on forks

- baseapp/abci.go
This will be later needed to get VoteInfos in modules' BeginBlock once we move to Core API (we stopped passing `abci.RequestBeginBlock` and only pass the context). 
Q: We would need to backport it to all the versions that support Core API? (cc @aaronc )
---
I have...
I have...
> feat: Add VoteInfos to context in BeginBlock

- CHANGELOG.md
- store/CHANGELOG.md
This PR (https://github.com/cosmos/cosmos-sdk/commit/8944ab6781649bd0d00819e9f3dbd6b11db54b5c) added a wrong changelog (and at the wrong place).
---
I have...
I have...
> chore: fix changelog due to previous PR

- x/distribution/keeper/params.go
rename clientCtx to ctx, because it is not client
Closes: #XXXX
---
I have...
I have...
> refactor: Rename clientCtx to ctx in distr params.go

- types/module/core_module.go
It was Adapator 😅 
Closes: #XXXX
---
I have...
I have...
> refactor: fix spelling of Adaptor

- CHANGELOG.md
- tests/integration/bank/keeper/keeper_test.go
- x/bank/README.md
- x/bank/client/cli/tx.go
- x/bank/keeper/keeper_test.go
- x/bank/keeper/msg_server.go
- x/bank/keeper/send.go
- x/bank/types/msgs.go
- x/bank/types/msgs_test.go
- x/gov/testutil/expected_keepers_mocks.go
When re-looking at https://github.com/cosmos/cosmos-sdk/issues/12610
Noticed the very valid argument of: https://github.com/realiotech/cosmos-sdk/pull/24.
https://github.com/cosmos/cosmos-sdk/pull/12670 indeed reverted too much.
This clean-up the API to make it more understandable what is the behavior of `InputOutputCoins`.
---
I have...
I have...
> refactor(bank): update `InputOutputCoins` arguments

- types/mempool/priority_nonce.go
- types/mempool/sender_nonce.go
> docs: update mempool Select godoc

- CHANGELOG.md
- RELEASE_NOTES.md
Prepare v0.45.15 release.
cc @troian you can expect a tag after this PR is merged.
---
I have...
I have...
> chore: prepare v0.45.15 release

- README.md
- docs/architecture/adr-057-app-wiring.md
ignite cli lags sdk and has been causing many issues for users, since we dont coordinate with them we shouldnt recommend the product for users 
---
I have...
I have...
> docs: remove ignite cli

- x/staking/README.md
Closes: #3732
add a note stating that once tombstoned the validators consensus key can not be reused on the chain the tombstoning happened on. 
I couldnt find the original doc, went through old versions so decided to add a note only
---
I have...
I have...
> docs: add note on tombstoning

- core/appconfig/config.go
Closes: #XXXX
---
I have...
I have...
> docs(core): add documentation in error message

- RELEASE_PROCESS.md
- UPGRADING.md
- docs/.gitignore
- docs/docs/building-apps/03-app-upgrade.md
- docs/docs/building-apps/03-migrations.md
- docs/docs/migrations/00-intro.md
- docs/docs/migrations/01-intro.md
- docs/docs/migrations/_category_.json
- docs/docusaurus.config.js
- docs/post.sh
- docs/pre.sh
Attempts to re-arrange and clarify migration docs.
Comes from the params discussions.
---
I have...
I have...
> docs: re-arrange and clarify migration docs

- go.mod
- go.sum
- simapp/go.mod
- simapp/go.sum
- tests/go.mod
- tests/go.sum
Bumping `hashicorp/go-getter` to `v1.7.1` to escape antivirus trigger for `v1.7.0`. The fix is documented in https://github.com/hashicorp/go-getter/pull/424.
---
I have...
> chore: bump hashicorp/go-getter to escape antivirus trigger

- CHANGELOG.md
- x/gov/keeper/proposal.go
If the error is already a ErrNoProposalHandlerExists, just return it. Otherwise, wrap it as a ErrInvalidProposalContent.
Closes: #XXXX
---
I have...
I have...
> fix(x/gov): Return ErrInvalidProposalContent in SubmitProposal when legacy handler returns an error. (backport #13051)

- x/evidence/types/expected_keepers.go
- x/feegrant/client/cli/tx_test.go
- x/feegrant/keeper/keeper_test.go
- x/feegrant/migrations/v2/store_test.go
- x/feegrant/module/abci_test.go
- x/feegrant/simulation/decoder_test.go
- x/feegrant/simulation/genesis.go
Closes part of: #14405 
---
I have...
I have...
> refactor: remove aliases from types/math.go in evidence and feegrant

- CHANGELOG.md
- types/coin.go
- types/coin_test.go
- types/fuzz_test.go
This change fixes a scenario in which Coin.Validate() would panic when given a nil Amount. While here, added a fuzz test along with unit/regression tests.
Fixes #15690
> fix: types: ensure .Amount is non-nil in Coin.Validate()

- math/CHANGELOG.md
- math/int.go
- math/int_test.go
`math.FormatInt` was panicking when passing in an empty string, we should return an error instead.
Closes: #XXXX
---
I have...
I have...
> fix(math): `FormatInt` returns error on empty string

- simapp/internal/testnet/cometrpc_test.go
- simapp/internal/testnet/cometstarter_test.go
- testutil/testnet/cometrpclock.go
- testutil/testnet/cometstarter.go
- testutil/testnet/nodehelpers.go
Add a RPCListen method on the CometStarter type to enable RPC listening on a randomly chosen port.
Add guards to prevent more than one concurrent RPC-enabled Comet node, to account for the shared global state that Comet v0.37 uses for the RPC service. Include a test to ensure an error occurs when two RPC nodes are attempted to be started at concurrently.
As detailed in comments, once the SDK adopts Comet v0.38+, we can remove these guards and allow multiple concurrent RPC nodes. Note that Comet has not released v0.38 at time of commit.
---
I have...
your handle …
> feat(testnet): allow a single active Comet RPC service

- depinject/container.go
- depinject/debug.go
- depinject/errors.go
- depinject/internal/codegen/value.go
- depinject/location.go
- depinject/provider_desc_test.go
- avoid else branch on conditionals whose primary branch has an unconditional return
- consistent receiver naming
- avoid naked return in long function with named return values
---
I have...
- [ x reviewed "Files changed" and left comments if necessary
I have...
> style: address linter issues in depinject module

- x/tx/CHANGELOG.md
- x/tx/signing/directaux/direct_aux.go
- x/tx/signing/directaux/direct_aux_test.go
- x/tx/signing/std/handler_map.go
The package name was failing revive linting, and also the official package naming doc at https://go.dev/blog/package-names says not to use underscores in package names.
Doing the package name as a standalone PR to keep the scope narrow during a rename. There are other linter issues that need to be fixed in a followup PR.
---
I have...
I have...
> style!: rename direct_aux package to directaux

- types/module/testutil/codec.go
- x/bank/app_test.go
- x/bank/bench_test.go
- x/bank/simulation/operations.go
- x/gov/simulation/operations.go
- x/slashing/app_test.go
- x/staking/app_test.go
- x/staking/simulation/operations.go
While running a memory profile on the test-sim-nondeterminism tests, I saw that there was a non-negligible amount of allocations occurring in moduletestutil.MakeTestEncodingConfig. Many of those calls were only retrieving the TxConfig field from the returned value, so I extracted a smaller method that only produces a TxConfig, and used that where possible.
I don't have numbers to quantify the difference in allocations, as different runs use different seeds. Clearly the new implementation does less work for the same effect.
---
I have...
your handle next to the …
> refactor: create TxConfig directly in simulations

- x/crisis/keeper/msg_server.go
- x/crisis/keeper/msg_server_test.go
- x/crisis/types/msgs.go
ref: https://github.com/cosmos/cosmos-sdk/issues/15648
---
I have...
I have...
> refactor(crisis): move `ValidateBasic`logic to `msgServer`

- x/consensus/keeper/keeper.go
- x/consensus/types/msgs.go
ref: https://github.com/cosmos/cosmos-sdk/issues/15648
---
I have...
I have...
> refactor(consensus): move `ValidateBasic` logic to `msgServer`

- x/tx/signing/textual/duration_test.go
- x/tx/signing/textual/fuzz_test.go
- x/tx/signing/textual/testdata/fuzz/FuzzIntValueRendererParse/5838cdfae7b16cde
- x/tx/signing/textual/testdata/fuzz/FuzzIntValueRendererParse/e521654378d1371f
- x/tx/signing/textual/testdata/fuzz/FuzzTimestampJSON/7fee543ff80f1279
- x/tx/signing/textual/timestamp_test.go
Found by fuzzing, this change changes the tests to check that the final roundtripped result is compared using standardizes timestamppb and durationpb methods: .AsTime() and .AsDuration() respectively. The reason is that if one passes in a value of:
timestamppb.Timestamp{Secs:0, Nanos: 1_000_000_001}
which is technically the same as:
timestamppb.Timestamp{Secs:1, Nanos: 1}
the tests would fail spuriously yet when turned into a time.Time object they produce the exact same value.
The same applies for a Duration.
Also while here, added more fuzz tests.
Fixes #15761
> fix: x/tx/signing/textual: use standardized Timestamp+Duration comparators in tests

- CHANGELOG.md
- baseapp/abci.go
- baseapp/abci_test.go
- baseapp/baseapp.go
- docs/architecture/adr-064-abci-2.0.md
Set `initialHeight` in `BaseApp` _always_. Use that in `getContextForProposal` instead of assuming first block == 1.
This PR is a fix only for chains that are **NEW** and starting with `InitialHeight > 1`...which is probably no one but it's good to fix anyway.
---
I have...
I have...
> fix: use initialHeight correctly

- .github/workflows/sims-045.yml
- .github/workflows/sims-046.yml
- .github/workflows/sims-047.yml
- .github/workflows/sims-nightly.yml
- .github/workflows/sims.yml
Closes: #15790 
change channel the bot is suppose to post too 
---
I have...
I have...
> fix: slack channel

- .github/dependabot.yml
We are somewhat frequently running into API limits being exceeded for GitHub actions. Set each dependabot job to run during "off hours" of commit times for cosmos-sdk.
I produced a crude histogram of the hour of the day, UTC, of the most recent 1000 commits with this short shell script:
```console
$ git log -1000 --format='%cI' | awk -F T '{print $2}' | awk -F : '{print $1}' | sort | uniq -c | sort -r
84 16
82 17
79 14
70 11
69 18
62 15
62 12
62 10
61 19
56 20
54 13
46 21
46 09
38 22
26 23
26 00
24 08
18 07
12 06
12 01
4 02
3 05
2 04
2 03
```
Since the fewest commits happen between 0200 and 0500 UTC, I configured all the dependabot jobs to start at 0200 and increment by 5 minutes on each declaration. This is by no means scientific, but it seems like a good guess for how to minimize …
> ci: set desired times for dependabot scheduling

- client/rpc/rpc_test.go
Closes: #15570 
revert t.skips since issue in comet is solved 
---
I have...
I have...
> chore: revert comet test skips

- simapp/sim_test.go
temporary reduce simulation times to speed up ci times 
---
I have...
I have...
> ci: short term reduction in sims 

- CHANGELOG.md
- x/auth/ante/sigverify.go
Closes: #XXXX
Upon verifying signatures, we overwrite error messages for legacy amino signers, due to high possibility that sequence number is the potential cause of failure for verifying signature. However, for other cases, we should return error message of why signature verification failed, instead of overwriting the original error message.
---
I have...
I have...
> chore: Better logging for signature verification failure

- docs/docs/building-modules/15-depinject.md
Some users missed implementing the `appmodule.AppModule` interface when using depinject.
This fails to give any clear error, this PR improves the docs for avoiding that.
---
I have...
I have...
> docs(depinject): explain need `appmodule.Module` interface

- Makefile
Prior to this change, the headers in the console output would read:
Running unit tests for module ./depinject
Running unit tests for module ./errors
Now, they print the actual Go module, which is more clear about what is being tested:
Running unit tests for module cosmossdk.io/depinject
Running unit tests for module cosmossdk.io/errors
---
I have...
I have...
> test: print full module name for headers during 'make test'

- CHANGELOG.md
- client/keys/list.go
Make sure that the expected output format is honored. this println is breaking scripts that expect json output when requesting json output
A recent change caused listing of an empty key set to always print a response string to stdout. This means you can't structure scripts around the keys list query, as requesting json won't return json. This breaks existing code.
---
I have...
I have...
> fix: list keys output for empty keys

- tests/e2e/authz/tx.go
These two cases appeared to be copy-paste errors. They are identical to the adjacent test case. They each took about 4s on my machine without using the race detector, so removing these will save more than 8 seconds from this test package on CI, which does use the race detector and which is likely to be slower than my workstation.
---
I have...
I have...
> test: remove duplicated authz e2e test cases

- CHANGELOG.md
- baseapp/abci.go
This pr sets the latest votes to voteinfo in prepare and process proposal. The Prepare Proposal step introduced a conversion from ExtendedCommitInfo to abci.VoteInfo.
The ExtendedVoteInfo is meant to be used with vote extensions which are not handled yet 
---
I have...
I have...
> refactor(baseapp): set vote info to latest votes

- go.mod
- go.sum
This PR bumps cosmossdk.io/core in sdk 47 because ibc-go is using a newer one, and this was causing integration difficulties. 
---
I have...
I have...
> build(deps): bump cosmossdk.io/core to v0.5.1

- simapp/sim_test.go
- x/group/simulation/genesis.go
- x/simulation/client/cli/flags.go
Closes: #15741
Checks if the group policy address has been used already, skip or retry if it has been used already.
I didn't add a changelog nor any additional tests, but if you want those things too, I would be happy to do so.
---
I have...
I have...
> fix: unique constraint violation for group policy sim genesis

- client/v2/autocli/app.go
- client/v2/autocli/common_test.go
- client/v2/autocli/flag/address.go
- client/v2/autocli/flag/builder.go
- codec/address/bech32_codec.go
- tools/hubl/go.mod
- tools/hubl/go.sum
- tools/hubl/internal/config.go
- tools/hubl/internal/load.go
- tools/hubl/internal/remote.go
- x/auth/keeper/bech32_codec.go
ref: https://github.com/cosmos/cosmos-sdk/pull/15906#discussion_r1176481235
---
I have...
I have...
> feat(hubl): cache bech32 prefix

- CHANGELOG.md
- RELEASE_NOTES.md
Prepare v0.47.2 release.
---
I have...
I have...
> chore: prepare v0.47.2 release

- .github/workflows/test.yml
- .golangci.yml
Skips the fix_regsitration.go from golangci-lint.
This isn't the first time golangci-lint has been flaky on it, which isn't handy when our linter job is required.
---
I have...
I have...
> ci: skip fix registration for linting

- server/api/server.go
- server/log/cmt_logger.go
- server/start.go
- testutil/network/util.go
- testutil/testnet/cometstarter.go
- x/genutil/client/cli/init_test.go
I wanted to backport the cmt_logger file to v0.47 (and some other functions we have on), so allowing cosmossdk.io/log to be used there.
However noticed on main our wrapper as an incorrect name. It isn't only limited to zerolog.
---
I have...
I have...
> chore: rename comet logger wrapper

- CHANGELOG.md
- go.mod
- go.sum
- server/log/cmt_logger.go
- server/util.go
- simapp/go.mod
- simapp/go.sum
- tests/go.mod
- tests/go.sum
Use `cosmossdk.io/log` in v0.47 instead of CometBFT logger.
The default implementation uses zerolog, which makes the logger identical to v0.45 and v0.46 but this time with filtering fixed.
Purposely not backporting helpers like in https://github.com/cosmos/cosmos-sdk/pull/15358, as it will be a v0.48 improvement :)
---
I have...
I have...
> feat: use cosmossdk.io/log in v0.47

- CHANGELOG.md
- x/group/migrations/v2/migrate.go
- x/group/migrations/v2/migrate_test.go
Closes: #XXXX
---
I have...
I have...
> fix(x/group): v2 migration

- baseapp/abci_utils.go
Update `ValidateVoteExtensions` to ensure at least 2/3 validators, by voting power, have submitted valid vote extensions as specified by the SDK ABCI++ ADR.
---
I have...
I have...
> chore: Update ValidateVoteExtensions

- .github/workflows/build.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/dependabot-update-all.yml
- .github/workflows/dependencies-review.yml
- .github/workflows/lint.yml
- .github/workflows/release-cosmovisor.yml
- .github/workflows/release-rosetta.yml
- .github/workflows/release.yml
- .github/workflows/sims-045.yml
- .github/workflows/sims-046.yml
- .github/workflows/sims-047.yml
- .github/workflows/sims-nightly.yml
- .github/workflows/sims.yml
- .github/workflows/test.yml
- simapp/app_v2.go
Same reason that for https://github.com/cosmos/cosmos-sdk/pull/16049 but for v0.47.
---
I have...
I have...
> ci: bump go in CI

- CHANGELOG.md
- tests/e2e/gov/tx.go
- tests/integration/aminojson/aminojson_test.go
- tests/integration/distribution/keeper/grpc_query_test.go
- tests/integration/distribution/keeper/msg_server_test.go
- tests/integration/gov/keeper/grpc_query_test.go
- tests/integration/staking/keeper/common_test.go
- tests/integration/staking/keeper/unbonding_test.go
- tests/integration/staking/keeper/validator_bench_test.go
- tests/integration/staking/keeper/validator_test.go
- testutil/testnet/genesis.go
- types/dec_coin.go
- types/dec_coin_test.go
- types/denom.go
- types/denom_internal_test.go
- types/math.go
- x/auth/tx/aux_test.go
- x/auth/vesting/types/vesting_account.go
- x/distribution/keeper/delegation.go
- x/gov/keeper/msg_server_test.go
- x/gov/migrations/v3/convert.go
- x/gov/migrations/v4/store_test.go
- x/mint/keeper/keeper_test.go
- x/staking/keeper/msg_server_test.go
- x/staking/migrations/v5/migrations_test.go
ref #14405
removes some unused aliases from math.go
---
I have...
I have...
> refactor(math)!: remove aliases in math

- baseapp/abci_utils.go
- baseapp/baseapp.go
- baseapp/options.go
- Support default no-op handlers
- Add setters for handlers
---
I have...
I have...
> chore: vote ext opts

- client/grpc_query_test.go
- testutil/sims/app_helpers.go
- types/module/module_test.go
- types/msgservice/validate_test.go
- x/consensus/exported/exported.go
- x/consensus/keeper/keeper.go
ref: https://github.com/cosmos/cosmos-sdk/issues/12272
---
I have...
I have...
> refactor(types & client): fix tests 

- baseapp/abci.go
- client/grpc_query_test.go
- testutil/sims/app_helpers.go
ref #12272 
---
I have...
I have...
> refactor(core): use working hash in finalizeblock instead of flush

- CHANGELOG.md
- docs/docs/run-node/01-run-node.md
- server/util.go
Closes: https://github.com/cosmos/cosmos-sdk/issues/13874 / https://github.com/cosmos/cosmos-sdk/issues/13874#issuecomment-1540023787
---
I have...
I have...
> feat: default to noop mempool when max-txs is negative

- crypto/ledger/ledger_test.go
Closes: #16035 
add build flags to ledger test files, we had them set elsewhere just not in the file that housed the tests 
---
I have...
I have...
> chore: run ledger tests when flags are set

- x/auth/vesting/client/cli/tx.go
ref https://github.com/cosmos/cosmos-sdk/issues/15978
---
I have...
I have...
> chore(auth/vesting): fix typo in `create-period-vesting-account` cmd example

- testutil/integration/router.go
- testutil/sims/app_helpers.go
- testutil/testnet/cometstarter.go
- testutil/testnet/network.go
- testutil/testnet/nodehelpers.go
> chore(ABCI++): update/fix testutil tests

- CHANGELOG.md
- x/staking/keeper/delegation.go
- x/staking/keeper/delegation_test.go
- x/staking/types/delegation.go
Closes: #16042 
An earlier change in #12967  introduced behaviour that causes the `AfterUnbondingInitiated` staking hook to be called with an invalid `unbondingId` in `SetUnbondingDelegationEntry`. The issue affects unbonding operations, redelegation behaviour does not seem to be affected. The issue can cause interchain-security provider chains to panic.
---
I have...
I have...
> fix: call AfterUnbondingInitiated for new unbonding entries only

- client/snapshot/dump.go
The staticmajor job has been failing since https://github.com/cosmos/cosmos-sdk/pull/16067 because a defer close was forgotten.
https://github.com/cosmos/cosmos-sdk/actions/runs/4947335317/jobs/8846568187?pr=16104.
Already added in the mergify PRs, but this one is for main.
---
I have...
I have...
> chore(client): add missing defer close in new snapshot command

- x/feegrant/filtered_fee.go
- x/feegrant/filtered_fee_test.go
EDIT: Fix the bug. The internal allowance update was never propagated to the parent `AllowedMsgAllowance`.
This test is designed to reproduce an infinite Feegrant bug that occurs when using `AllowedMsgAllowance` with an internal `BasicAllowance`.
I suspect that [this line](https://github.com/scrtlabs/cosmos-sdk/blob/61091b357e/x/feegrant/basic_fee.go#L31) does not update the internal `BasicAllowance` after using part of the grant. This may be related to [this line](https://github.com/scrtlabs/cosmos-sdk/blob/61091b357e/x/feegrant/filtered_fee.go#L47) as well.
Thanks @DrPresident from Shade Protocol for initially reporting this issue.
---
I have... …
> Fix Infinite Feegrant Bug

- CHANGELOG.md
- tests/integration/gov/keeper/keeper_test.go
- x/gov/keeper/grpc_query.go
- x/gov/keeper/keeper_test.go
- x/gov/module.go
- x/gov/types/keys.go
Closes: #16105
---
I have...
I have...
> refactor(gov)!: decouple gRPC query methods from Keeper

- x/auth/migrations/legacytx/stdsign.go
- x/auth/tx/legacy_amino_json.go
Ref: #16094 
---
I have...
I have...
> chore(x/auth): deprecate legacy aminojson sign mode

- core/CHANGELOG.md
I had to do it manually (`git log --pretty=oneline core/v0.6.1..core/v0.7.0 ./core/**` for each tag and then cherry-picking the PR) because the changelog generation brings too much false positive.
I think for getting a better changelog generation and remove the replace hell we have in our mono-repo, we should greatly limit the number of PRs touching multiples go mod and make them more contained.
It seems like we attempted doing this a while ago (see description), but I wonder why it hasn't sticked https://github.com/cosmos/cosmos-sdk/pull/13115. The downside doing that is that we need to tag way more.
I do not think we can get both of best world (pretty generated changelogs and big PRs). Personally I am fine with manual changelogs, but we really need to keep them up to date. Doing them …
> docs: add core changelog

- CHANGELOG.md
- client/snapshot/dump.go
- store/snapshots/manager.go
return proper errors
Closes: #XXXX
---
I have...
I have...
> fix: snapshot commands panic if snapshot don't exists

- CHANGELOG.md
- server/api/server.go
The GRPC-to-REST gateway converts protobuf responses to JSON. However the marshalling we use for this adds indentation, consuming unnecessary bandwidth for all FE users. I believe I was told that indentation was getting to 20% of bandwidth on queries to full nodes from app.osmosis.zone.
This PR just stops sending the whitespace here.
I believe this is non-breaking, because I'm unaware of any consumer of JSON content, that would break from removal of whitespace.
This shouldn't add debugging overhead, as every browser comes with great JSON viewers, that work independent of the whitespacing.
---
I have...
*All items are required. Please add a note if …
> perf: Remove indentation in REST respones

- client/snapshot/dump.go
- store/snapshots/manager.go
Closes: #XXXX
---
I have...
I have...
> fix: snapshot error message wording

- math/CHANGELOG.md
- math/dec.go
- math/dec_test.go
Speeds up the Dec.Sqrt() routine which is in a hot loop for Osmosis AMM code.
This is done by lowering heap allocations, through better use of constant re-use, or mutative methods.
Old:
```
BenchmarkLegacySqrtOnMersennePrime-16               23086             51408 ns/op           26730 B/op	     726 allocs/op
```
New:
```
BenchmarkLegacySqrtOnMersennePrime-16    	   39177	     28938 ns/op	   11864 B/op	     214 allocs/op
```
More important than the pure raw time, is the number of allocations, as those induce system overheads in Garbage Collection at scale, that don't get represented in the micro-bench here.
---
I have...
*All items are required. …
> perf: Speedup Dec.Sqrt()

- testutil/sims/tx_helpers.go
- x/slashing/abci_test.go
- x/slashing/app_test.go
- x/slashing/simulation/operations_test.go
ref: #12272
---
I have...
I have...
> fix(slashing): slashing test failures

- CHANGELOG.md
- testutil/testdata/codec.go
- types/tx/ext.go
- types/tx/types.go
* this change was included b0e82f96407025d2b14f87d60430396dfc975903
* to avoid breaking change from v0.46.x to v0.47.x
Closes: #XXXX
---
I have...
I have...
> fix: rename back TxExtensionOptionI

- x/staking/types/keys.go
Closes: #XXXX
---
I have...
I have...
> fix: duplicate prefix in staking keys

- simapp/app.go
Closes: #XXXX
---
I have...
I have...
> fix simapp tests

- baseapp/abci.go
- baseapp/abci_test.go
- baseapp/baseapp_test.go
- baseapp/msg_service_router_test.go
- baseapp/snapshot_test.go
- baseapp/streaming_test.go
- baseapp/utils_test.go
- go.mod
ref #12272 
---
I have...
I have...
> refactor(baseapp): fix tests

- server/start.go
Very minor PR, should hopefully be a straightforward review/merge. 
The startup server function was 207 lines long, and requires some careful attention to whats going on. I find myself having to look at it semi-occasionally. This PR moves things to sub-functions in a fully compatible manner, and it now takes 109 lines. With minor changes in some follow-ups, this can significantly reduce further. 
This PR does some basic splitting up of components of the function, into smaller functions. It surely can be done better, but I essentially did this just to look at it better, so thought this incremental progress would be useful to PR. This area of the code definitely deserves more attention / better refactoring in the future though!
Its fully compatible as far as I can tell. Comments are left in …
> refactor: Split up server functions a bit

- CHANGELOG.md
- baseapp/baseapp.go
- server/start.go
- server/types/app.go
Closes: #16192
---
I have...
I have...
> feat: add Close method for resource cleanup in graceful shutdown

- CHANGELOG.md
- x/gov/types/v1/vote.go
Closes: #16230
Added json dependency in vote.go types of gov module
I have...
I have...
> fix: rawlog JSON formatting of proposal_vote option field

- CHANGELOG.md
- server/start.go
- server/types/app.go
Address some TODO's I left in server/start.go from #15041 
This PR has five changes, beyond some line count / complexity reduction. Namely:
- Get and validate config before doing any store work
- Start the trace server before opening the database
- Actually close the trace server 
- Don't create a p2p node key when you are in grpc only mode
- Extract common starting logic between startStandAlone and startInProcess
These weren't done in #15041 in order for that PR to be changing no functionality.
---
I have...
your handle next to the items reviewed if you only …
> refactor: More cleanup of server/start.go

- server/start.go
- server/util.go
Applies Yi-huang's simplification from https://github.com/cosmos/cosmos-sdk/pull/16208 .
Makes ListenForQuitSignals optionally block, and thus removes the messy complications inside of startInProcess. I believe that this PR should have no changes over prior PR's.
---
I have...
I have...
> refactor: Apply Yihuang's server blocking improvement

- baseapp/baseapp.go
- simapp/app.go
- x/circuit/module.go
set the circuit breaker in app.go as an example of how to set it
---
I have...
I have...
> chore: set circuitbreaker in app.go as example

- types/context.go
wile reading code i realised that everywhere else we have a time.UTC call except headerInfo()
---
I have...
I have...
> fix: headerInfo time UTC()

- api/cosmos/group/v1/events.pulsar.go
- x/gov/keeper/proposal_test.go
- x/group/events.pb.go
- x/group/keeper/msg_server_test.go
- https://github.com/cosmos/cosmos-sdk/pull/16268#discussion_r1206502186
- https://github.com/cosmos/cosmos-sdk/pull/16191#pullrequestreview-1441260235
---
I have...
I have...
> chore: implement feedback of automerged prs

- CHANGELOG.md
- baseapp/baseapp.go
- baseapp/circuit.go
- baseapp/msg_service_router.go
ref #14226 
add baseapp setter to circuit breaker in order to be used in 0.46 
---
I have...
I have...
> chore: add baseapp circuit breaker setter

- CHANGELOG.md
- client/prompt_validation.go
- client/prompt_validation_test.go
Closes: https://github.com/cosmos/cosmos-sdk/issues/16307
---
I have...
I have...
> fix: allow any address in `ValidatePromptAddress`

- core/gas/meter.go
ref #14683 
this pr adds gas meter to core api, in a follow up pr we will wire it into runtime 
---
I have...
I have...
> feat(core): add gas meter

- CHANGELOG.md
- x/gov/keeper/proposal.go
This reverts commit f89d955e03e2143c6f985f692f87da0557e0654b.
The error code change breaks `LastResultsHash`.
The original change is released on `v0.46.12` already, we might need to remove that version, after `v0.46.13` release.
Closes: #XXXX
---
I have...
I have...
> fix: Revert "fix(x/gov): Return ErrInvalidProposalContent in SubmitProposal when legacy handler returns an error. (backport #13051) (#15667)"

- tests/integration/aminojson/aminojson_test.go
- tests/integration/aminojson/repeated_test.go
- x/tx/CHANGELOG.md
- x/tx/signing/aminojson/bench_test.go
- x/tx/signing/aminojson/json_marshal.go
- x/tx/signing/aminojson/json_marshal_test.go
This change gives (aminojson.Encoder).Marshal the ability to sort field names before marshalling, mimicking the outward behavior of encoding/json.Marshal and thus eliminating a long prior roundtrip that required sdk.*SortJSON which would take the produced JSON and encoding/json.Unmarshal it to an interface firstly, then encoding/json.Marshal it out to get the field names sorted. While here, this change adds an opt-out field to aminojson.EncoderOptions called "DoNotSortFields", in case one wants to preserve legacy behavior for compatibility checks/reasons.
The performance benchmarks from before and after reveal improvements
```shell
name         old time/op    new time/op    delta
AminoJSON-8    76.4µs ± 1%    61.7µs ± 2%  -19.28%  (p=0.000 n=9+10)
name …
```
> feat: x/tx/signing/aminojson: Marshal sort fields

- CHANGELOG.md
- server/util.go
The SDK seems opinionated about some comet config parameters.
However, it renders the override of those parameters by an app useless and with no feedback.
This adds a check that keeps the SDK opinionated if the value is the default comet value.
Which allows app devs to overwrite those value if they want to.
---
I have...
I have...
> fix: do not overwrite comet config when set in `InterceptConfigsPreRunHandler`

- client/snapshot/cmd.go
- client/snapshot/export.go
- client/snapshot/list.go
- client/snapshot/load.go
- docs/docs/run-node/01-run-node.md
- go.mod
- server/cmt_cmds.go
- simapp/go.mod
- store/snapshots/README.md
Small improvements for the snapshots commands.
ref: https://github.com/cosmos/cosmos-sdk/pull/16248, https://github.com/cosmos/cosmos-sdk/pull/16249
Tested v0.46.13, with a Stride node (for #16248), ~~with the only issue that I cannot export a snapshot of a state-synced node (first state sync from p2p, dump snapshots, go further in height, try to export it and then the following).~~
```go
$ ./build/strided snapshots export
Exporting snapshot for height 3931257
Error: failed to generate snapshot chunk 0: iavl export failed for version 3931257: version does not exist
```
~~It does not work because this is nil: https://github.com/cosmos/iavl/blob/7afdfcd69dc956facacd4977c6658f3107f5db33/mutable_tree.go#L778
If I comment it out, it is then working fine. As this code has been there for a long …
> chore: small snapshot commands & docs improvement

- baseapp/abci_utils.go
- baseapp/baseapp.go
- docs/docs/building-apps/02-app-mempool.md
Closes: #XXXX
---
I have...
I have...
> chore: change prepare and process proposal to be NoOps by default

- CHANGELOG.md
- UPGRADING.md
Closes: https://github.com/cosmos/cosmos-sdk/issues/16428, ref https://github.com/cosmos/cosmos-sdk/issues/16420 (only for main)
---
I have...
I have...
> docs: improve upgrading.md and changelog

- baseapp/circuit.go
- baseapp/msg_service_router.go
ref: https://github.com/cosmos/cosmos-sdk/pull/16415#discussion_r1218253866
---
I have...
I have...
> refactor: avoid breaking change due to #16415 included in v0.50

- CHANGELOG.md
- store/rootmulti/store.go
StateSync restore over p2p network and the new v0.47 local snapshot BOTH FAIL after restore due to AppHash mismatch.
Exclude `memory:capability` store to follow logic in commitStores()
Reference for proper commit info building:
https://github.com/cosmos/cosmos-sdk/blob/main/store/rootmulti/store.go#L1176
---
I have...
I have...
> fix: StateSync Restore by excluding memory store

- CHANGELOG.md
- tests/integration/distribution/keeper/grpc_query_test.go
- tests/integration/distribution/keeper/msg_server_test.go
- x/distribution/keeper/allocation.go
- x/distribution/keeper/allocation_test.go
- x/distribution/keeper/delegation.go
- x/distribution/keeper/genesis.go
- x/distribution/keeper/hooks.go
- x/distribution/keeper/keeper.go
- x/distribution/keeper/store.go
- x/distribution/keeper/validator.go
- x/distribution/migrations/v2/store_test.go
- x/distribution/simulation/decoder_test.go
- x/distribution/simulation/operations_test.go
- x/distribution/types/keys.go
- x/staking/simulation/operations_test.go
Closes: https://github.com/cosmos/cosmos-sdk/issues/16460
---
I have...
I have...
> refactor(distribution)!: use collections for ValidatorCurrentRewards

- codec/proto_codec.go
- x/tx/signing/aminojson/aminojson.go
Completes PR #16062 by removing sortJSON now that aminojson.Encoder sorts fields by default. sortJSON was left as a TODO
Updates #2350
Updates #16254
> chore: finish TODO of removing defunct sortJSON

- client/v2/autocli/common.go
- client/v2/autocli/query.go
- tools/hubl/internal/remote.go
Seen that hubl didn't support the output flag that is supported by `client/v2`.
This PR adds it. It as well removes in `client/v2` the empty line when returning a `yaml`. 
---
I have...
I have...
> feat(hubl): support output flag

- baseapp/abci.go
set headerinfo and cometinfo where needed 
---
I have...
I have...
> chore: set headerinfo where needed in baseapp

- CHANGELOG.md
- RELEASE_NOTES.md
- go.mod
- go.sum
Closes: #XXXX
---
I have...
I have...
> build(deps): bump cometbft to v0.34.29

- tools/cosmovisor/CHANGELOG.md
- tools/cosmovisor/README.md
- tools/cosmovisor/args.go
- tools/cosmovisor/args_test.go
- tools/cosmovisor/cmd/cosmovisor/add_upgrade.go
- tools/cosmovisor/cmd/cosmovisor/init.go
- tools/cosmovisor/cmd/cosmovisor/init_test.go
- tools/cosmovisor/cmd/cosmovisor/main.go
- tools/cosmovisor/cmd/cosmovisor/run.go
- tools/cosmovisor/cmd/cosmovisor/run_config.go
- tools/cosmovisor/cmd/cosmovisor/version.go
add COSMOVISOR_COLOR_OUTPUT as an option to enable/disable colored logs add COSMOVISOR_TIMEFORMAT_LOGS as an option to configure/disable timestamp prefix in the logs
Closes: #XXXX
---
I have...
I have...
> feat(cosmovisor): enable logger configuration with env variable

- CHANGELOG.md
- tests/integration/distribution/keeper/grpc_query_test.go
- tests/integration/distribution/keeper/msg_server_test.go
- x/distribution/keeper/alias_functions.go
- x/distribution/keeper/allocation.go
- x/distribution/keeper/allocation_test.go
- x/distribution/keeper/delegation.go
- x/distribution/keeper/genesis.go
- x/distribution/keeper/grpc_query.go
- x/distribution/keeper/hooks.go
- x/distribution/keeper/invariants.go
- x/distribution/keeper/keeper.go
- x/distribution/keeper/keeper_test.go
- x/distribution/keeper/store.go
- x/distribution/keeper/validator.go
- x/distribution/migrations/v2/store_test.go
- x/distribution/simulation/decoder_test.go
- x/distribution/simulation/operations_test.go
- x/distribution/types/keys.go
Closes: #16591 
---
I have...
I have...
> refactor(distribution)!: use collections for ValidatorOutstandingRewards state management

- CHANGELOG.md
- baseapp/abci_test.go
- baseapp/baseapp.go
- baseapp/baseapp_test.go
Closes: #16610
Update `runTx` to ensure each message has a registered handler.
---
I have...
I have...
> fix!: Ensure Handler Exists for Messages

- tools/hubl/internal/compat.go
Closes:  #16600
This PR corrects an unhandled error on hubl reflection over msgName types.
- Adds error handling to the server communication function
- Fixes the cause of the issue
The error have been happening because the original messages started with a `/` character, while the grpc server expects names without the `/` character.
---
I have...
* [*] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
* [*] added `!` to the type prefix if API or client breaking change
* [*] targeted the correct branch (see [PR Targeting](https://github.com/cosmos/cosmos-sdk/blob/main/CONTR …
> fix(hubl): malformed msgName and error handling 

- testutil/configurator/configurator.go
I wanted to use `configurator.ModuleOption`, outside of the SDK, but this was not useful because it was private.
This pr simply makes it public.
---
I have...
I have...
> chore: make `configurator.Config` public

- testutil/configurator/configurator.go
follow-up of #16624 because I forgot to make the field public, so I still cannot use it.
---
I have...
I have...
> chore: make configurator.Config.ModuleConfigs public

- x/tx/CHANGELOG.md
- x/tx/decode/decode_test.go
- x/tx/decode/unknown.go
Catches a panic from an invalid length prefix found by fuzzing. This change instead returns an error and a test.
Fixes #16680
> fix: x/tx/decode: fix (*Decoder).Decode crash with invalid length prefix

- CHANGELOG.md
- UPGRADING.md
ref: https://github.com/cosmos/cosmos-sdk/issues/16651 (part 1 and other upgrading.md improvements)
---
I have...
I have...
> docs: improve upgrading.md and changelog for autocli changes

- x/tx/signing/aminojson/json_marshal.go
Reverts a change that added json.NewEncoder which unfortunately adds newlines to JSON output, and that was failing tests.
> fix: x/tx/signing/aminojson: revert json.NewEncoder that added newlines

- CHANGELOG.md
- server/start.go
long running abci handshake can be used to profile block execution, but we need to make graceful shutdown works with it.
Closes: #16202
---
I have...
I have...
> feat: make abci handshake graceful interruptible

- x/authz/msgs.go
ref: #16504 
---
I have...
I have...
> chore: remove GetSigners from x/authz

- server/grpc/gogoreflection/serverreflection.go
When testing the server changes (ref https://github.com/cosmos/cosmos-sdk/issues/16698), I have noticed that grpcui and grpcurl were broken because of that update.
follow-up of https://github.com/cosmos/cosmos-sdk/pull/16534.
I think we should strive for compatibility and still revert f235aae as well for the SDK.
cc @tac0turtle as you were involved in the discussion in #16534
---
I have...
I have...
> fix: revert f235aae (part 2)

- CHANGELOG.md
- tools/cosmovisor/CHANGELOG.md
- tools/cosmovisor/README.md
- tools/cosmovisor/args.go
- tools/cosmovisor/args_test.go
- tools/cosmovisor/process.go
- tools/cosmovisor/process_test.go
- tools/cosmovisor/testdata/download/cosmovisor/preupgrade.sh
Validators/Infrastructure providers need the ability to execute custom scripts for backup, alerting, and other functions prior to upgrade.  
Set environment variable COSMOVISOR_CUSTOM_PREUPGRADE=preupgrade.sh to execute `.simapp/cosmovisor/preupgrade.sh` during upgrade.
Custom script is run with 2 arguments [ Upgrade Name, Upgrade Height ]
For example:
`.simapp/cosmovisor/preupgrade.sh v2 2000` for upgrade v2 at height 2000
---
I have...
I have...
> feat(cosmovisor): add ability to run custom preupgrade script

- CHANGELOG.md
- x/auth/vesting/msg_server.go
- x/auth/vesting/types/vesting_account.go
- x/auth/vesting/types/vesting_account_test.go
Caught in an audit, this change panics when a PeriodicVestingAccount's constituent period lengths are negative, or if the total .EndTime has overflown.
/cc @elias-orijtech
> fix(x/auth/vesting): panic on overflowing & negative EndTimes for PeriodicVestingAccount

- CHANGELOG.md
- tests/integration/auth/migrations/v2/store_test.go
- x/auth/simulation/genesis.go
- x/auth/vesting/msg_server.go
- x/auth/vesting/types/genesis_test.go
- x/auth/vesting/types/vesting_account.go
- x/auth/vesting/types/vesting_account_test.go
- x/bank/keeper/grpc_query_test.go
- x/bank/keeper/keeper_test.go
- x/genutil/genaccounts.go
ref: https://github.com/cosmos/cosmos-sdk/pull/16733#discussion_r1244880033
---
I have...
I have...
> refactor(vesting)!: improve validate functions and return error in constructor

- .golangci.yml
- tests/integration/distribution/keeper/grpc_query_test.go
- tests/integration/distribution/keeper/msg_server_test.go
- x/distribution/abci.go
- x/distribution/keeper/genesis.go
- x/distribution/keeper/hooks.go
- x/distribution/keeper/msg_server.go
- x/distribution/keeper/store.go
- x/distribution/types/msg.go
Tracking issue #16512
- Handle some unhandled errors (both in tests and in main code)
- Return error in `SetPreviousProposerConsAddr`
- Removed `GetSigners`
---
I have...
I have...
> refactor(x/distribution): audit changes

- CHANGELOG.md
Closes: XXXX
---
I have...
I have...
> chore: add v0.50.0-alpha.1 changelog to main

- collections/CHANGELOG.md
- collections/README.md
- collections/codec/alternative_value.go
- collections/codec/alternative_value_test.go
- collections/codec/bool.go
- collections/colltest/codec.go
- collections/indexes/multi.go
- collections/indexes/multi_test.go
- collections/indexes/reverse_pair.go
- collections/indexes/reverse_pair_test.go
- collections/keyset.go
- collections/keyset_test.go
Closes: #16771 
---
I have...
I have...
> feat(collections): add alternative value codec

- log/CHANGELOG.md
- log/go.mod
- log/go.sum
- log/logger.go
- log/logger_test.go
- log/options.go
In the SDK implementation of `cosmossdk.io/log` there is a confusion between the `trace` level (like error,info,debug,...) and displaying the stack trace of an error. The logger currently does not support the latter, while the `--trace` flag is for that. This PR adds the functionality to the logger lib.
---
I have...
I have...
> feat(log): add stacktrace display option

- x/gov/abci.go
…posals
Inverts the condtion for updating deposits for either failing or unexpedited proposals to make it simpler to read and maintain for the future.
Fixes #16807
> style(x/gov): invert & simplify EndBlocker conditions for expedited proposals

- CHANGELOG.md
- client/pruning/main.go
- simapp/simd/cmd/root.go
- simapp/simd/cmd/root_v2.go
Closes: https://github.com/cosmos/cosmos-sdk/issues/16855
Right now, passing the home flag is mandatory otherwise it panics. It isn't a great UX, as every other SDK commands do not require to always pass a flag.
Looking as well now how to make the ux for this command better.
In the backport, I'll do it non-breaking for v0.46 and v0.47.
---
I have...
I have...
> fix(cli): improve `prune` command ux

- baseapp/abci.go
- baseapp/abci_test.go
- baseapp/baseapp_test.go
- baseapp/msg_service_router_test.go
- baseapp/streaming_test.go
- server/mock/app_test.go
- simapp/test_helpers.go
- tests/e2e/server/export_test.go
- tests/integration/bank/app_test.go
- tests/integration/distribution/keeper/msg_server_test.go
- tests/integration/slashing/keeper/keeper_test.go
- tests/integration/store/rootmulti/rollback_test.go
- testutil/integration/example_test.go
- testutil/integration/options.go
- testutil/integration/router.go
- testutil/sims/tx_helpers.go
- x/simulation/simulate.go
- x/slashing/app_test.go
- x/staking/app_test.go
…fix initialHeight + add ProcessProposal in tests/sims (#16794)"
This reverts commit 0fd6227a06bda30166d5ef43046b5ea36ccf3645.
Preparing the ground to make the necessary fixes for VE persistence. We previously thought ProcessProposal was going to be called during block replay, but it's not like that so this previous PR actually broke block replay.
Some of the changes made here are going to be kept but it's easier to revert the entire thing and then cherry pick whatever we want to keep.
---
I have...
your handle next to the items reviewed if you only reviewed …
> fix: Revert 16794

- tests/e2e/tx/benchmarks_test.go
The benchmark is lifted from E2ETestSuite from the same package, with irrelevant state checks removed.
On my M1 macOS:
$ go test -run ^$ -bench=.
goos: darwin
goarch: arm64
pkg: github.com/cosmos/cosmos-sdk/tests/e2e/tx
BenchmarkTx
BenchmarkTx-8   	    4108	    268935 ns/op
Modifying the benchmark for v0.47.0:
$ go test -run ^$ -bench=.
goos: darwin
goarch: arm64
pkg: github.com/cosmos/cosmos-sdk/tests/e2e/tx
BenchmarkTx
BenchmarkTx-8   	    3772	    301750 ns/op
So a nice (10%) speed-up in main.
CC @odeke-em 
CC @tac0turtle who had the idea to benchmark against v0.47.0 to catch regressions.
> perf: benchmark end-to-end transaction submit

- x/gov/README.md
Closes: #16909 
---
I have...
I have...
> docs: Clarify gov docs

- tools/cosmovisor/CHANGELOG.md
- tools/cosmovisor/README.md
- tools/cosmovisor/args.go
- tools/cosmovisor/args_test.go
- tools/cosmovisor/cmd/cosmovisor/add_upgrade.go
- tools/cosmovisor/flags.go
- tools/cosmovisor/process_test.go
- tools/cosmovisor/scanner.go
- tools/cosmovisor/scanner_test.go
- tools/cosmovisor/testdata/norecase/cosmovisor/genesis/bin/dummyd
- tools/cosmovisor/testdata/norecase/cosmovisor/upgrades/Chain2/bin/dummyd
Follow up for:
https://github.com/cosmos/cosmos-sdk/pull/16549/files#r1245473528
Add option for cosmovisor to use upgrade plan names without automatic lower case.  
This is helpful when using original non-case changed plan names from:
* online web based chain explorers
* output of `daemond q gov proposals`
* output of `daemond q upgrade plan`
Some validators automate the configuration of daemon upgrades but do not have automatic lower case tooling 
Validators who copy and paste from explorers to avoid typos in plan names can manually edit, but that manual edit can introduce typos.
Some plan names may use characters that do not have obvious lower case rules.  For example lower case of "ΔİΞ" = "δiξ" but not all validators know how golang's internal libraries implement lower casing.
---
*All …
> feat(cosmovisor): Cosmovisor upgrade plan without automatic lower case

- simapp/sim_test.go
Before we were panicking in InitGenesis, so there was a recover in place to intercept up any possible initGenesis returning an empty validator set. Now InitGenesis doesn't panic, so we have to check the error its returning
---
I have...
I have...
> fix: Sims failing and not skipping with empty valset

- CHANGELOG.md
- api/cosmos/base/v1beta1/coin.pulsar.go
- proto/cosmos/base/v1beta1/coin.proto
- types/coin.pb.go
- x/tx/signing/aminojson/internal/buf.lock
Related to: https://github.com/cosmos/cosmos-sdk/pull/16918
---
I have...
I have...
> chore(proto): deprecated IntProto and DecProto

- store/CHANGELOG.md
- x/tx/CHANGELOG.md
- x/tx/signing/aminojson/encoder.go
Partly revert https://github.com/cosmos/cosmos-sdk/pull/16684. Using the `Encode` methods adds an unnecessary newline.
This leads to a small diff when marshaling compared to previously https://github.com/cosmos/cosmos-sdk/actions/runs/5524118523/jobs/10075983329
---
I have...
I have...
> chore(x/tx): partly revert `NewEncoder` usage

- x/auth/tx/service.go
- x/auth/tx/service_test.go
Closes https://github.com/cosmos/cosmos-sdk/issues/16993
> fix: query tx events with `>=` and `<=` operators

- x/bank/client/cli/tx.go
Closes: https://github.com/cosmos/cosmos-sdk/issues/16948
---
I have...
I have...
> docs: change bank multi-send command description

- CHANGELOG.md
- RELEASE_NOTES.md
- go.mod
Prepare v0.46.14 release.
Tested on the following mainnets:
- Mars Hub
---
I have...
I have...
> chore: prepare v0.46.14

- runtime/builder.go
- runtime/events.go
- runtime/module.go
- runtime/services/autocli.go
- runtime/types.go
ref: #16858
---
I have...
I have...
> chore(runtime): audit

- Makefile
- client/docs/config.json
- client/docs/swagger-ui/swagger.yaml
- contrib/devtools/Dockerfile
Closes: https://github.com/cosmos/cosmos-sdk/issues/17013
---
I have...
I have...
> chore(client): add missing modules from swagger

- CHANGELOG.md
- RELEASE_NOTES.md
Prepare v0.50 beta release.
~~Blocked on https://github.com/cosmos/cosmos-sdk/pull/17006 (only PR on main with a backport flag to v0.50).~~
Blocked on https://github.com/cosmos/cosmos-sdk/pull/16958
I am first going to release v0.46.14 and v0.47.4 in the afternoon and then remove changelog entries here with already release features/fixes.
After the tag, I'll open a PR bumping all modules with the tags, and then a third PR adding those modules to simapp in release/v0.50.x
---
I have...
I …
> chore: prepare v0.50 beta

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/lint.yml
- .golangci.yml
- Makefile
- scripts/go-lint-all.bash
Closes: https://github.com/cosmos/cosmos-sdk/issues/16240
Should speed up the run from ≃ 15min to some seconds-2min depending on the PR.
When we bump or change golangci-lint config, it will run on the whole codebase.
---
I have...
I have...
> ci: speed up lint job

- x/staking/keeper/msg_server.go
Closes: #XXXX
---
I have...
I have...
> refactor(x/staking): Use ValidatorAddrCodec

- CHANGELOG.md
- x/circuit/keeper/msg_server.go
- x/circuit/keeper/msg_server_test.go
Closes: #17087
---
I have...
I have...
> fix(x/circuit): `msg_url` is skipped when publishing events

- CHANGELOG.md
- client/flags/flags.go
- client/keys/add.go
- math/CHANGELOG.md
- math/int.go
- simapp/simd/cmd/testnet.go
- x/gov/README.md
- x/gov/keeper/keeper.go
- x/gov/keeper/msg_server_test.go
- x/gov/keeper/proposal.go
- x/gov/types/errors.go
- x/group/keeper/msg_server.go
- x/group/keeper/msg_server_test.go
- x/staking/keeper/msg_server.go
Cherry-pick some small cosmos sdk changes fom Injective fork: https://github.com/cosmos/cosmos-sdk/compare/v0.47.3...InjectiveLabs:cosmos-sdk:v0.47.3-inj-1
These should not be backported to v0.47 but still good for v0.50.
---
I have...
I have...
> chore: cherry-pick some inj changes

- simapp/sim_bench_test.go
The simulations that use either `BenchmarkFullAppSimulation` or `BenchmarkInvariants` are failing with error:
`panic: invalid chain-id on InitChain; expected: , got: simulation-app`
For example, running `make test-sim-benchmark` is a way to reproduce this issue.
The error is gone once the chain-id is properly set also in those two functions.
---
I have...
I have...
> fix(simapp): set chain-id on `NewSimApp` for sim bench tests

- x/staking/migrations/v5/keys.go
- x/staking/migrations/v5/migrations_test.go
- x/staking/migrations/v5/store.go
we have found a bug earlier that we are using the same prefix key for `UnbondingIDKey` & `DelegationByValIndexKey` [ref](https://github.com/cosmos/cosmos-sdk/pull/15731/files/74a8a890a77ef5caaca10bed7eab613cba25d07b#diff-c06d258288f3f4e86f19a61cd7a01fce7b5203b5c8aeb7019461bacf7944bb26R43) and that's been addressed in #16176, but we missed to update the key in staking migrations.
Closes: #XXXX
---
I have...
I have...
> fix(x/staking): `DelegationsByValidator` migrations

- CHANGELOG.md
- baseapp/abci_test.go
- baseapp/abci_utils.go
Bug occurs when a transaction will exceed the gas limit but will still be within the maximum block size, causing the `&&` condition to be false. This triggers the `else` which will add the transaction to the block but not check to ensure the gas it consumes keeps it within the limit.
---
I have...
I have...
> fix(abci): Validators can propose blocks that exceed the gas limit.

- x/circuit/keeper/msg_server.go
- x/circuit/keeper/msg_server_test.go
…able to trip them
Closes: #17106
Fix a bug where a user with permission for two messages would not be able to trip them
---
I have...
I have...
> fix(circuit): partial perms bug fix 

- store/CHANGELOG.md
- store/snapshots/manager.go
Avoid creating a goroutine every [Commit](https://github.com/cosmos/cosmos-sdk/blob/9a42a3e7a0a3f1fa31fe9e6c4409a733d15b2ce2/baseapp/abci.go#L843)
---
I have...
I have...
> perf: start the goroutine after need to create a snapshot

- simapp/simd/cmd/root.go
- simapp/simd/cmd/root_v2.go
Avoid being unable to directly parse the data in `viper` into [CustomAppConfig](https://github.com/cosmos/cosmos-sdk/blob/54ed7dab3982dfd667bf7ad3afcd6c6fbc8f3c61/simapp/simd/cmd/root_v2.go#L158) through `viper.Unmarshal(config)`, although `CustomAppConfig` here is not used, but I think it should be demonstrated in simapp.
> refactor(simapp): add `,squash` tag

- tools/confix/cmd/config.go
- tools/confix/cmd/mutate.go
* The `--verbose` flag usually has a shorter `-v`
* The `-s` flag makes it easier to modify `config.toml` when you know the risks
---
I have...
I have...
> feat(confix): add shorthand flag to `set` cmd cli

- CHANGELOG.md
- UPGRADING.md
- server/config/config.go
- server/config/toml.go
- server/mock/store.go
- tools/confix/data/v0.50-app.toml
This config was not used and seem not present from IAVL v1.0.0.
---
I have...
I have...
> refactor: remove `iavl-lazy-loading` from config

- baseapp/abci.go
- go.mod
- go.sum
- simapp/go.mod
- simapp/go.sum
- tests/go.mod
- tests/go.sum
follow-up #17158 
---
I have...
I have...
> perf(abci): removes the goroutine when call `SnapshotIfApplicable`

- x/auth/client/cli/decode.go
- x/auth/client/cli/encode.go
- x/auth/client/cli/tx_multisign.go
- x/genutil/client/cli/gentx.go
> refactor: hide `--output` flags that don't work

- CHANGELOG.md
- x/auth/keeper/grpc_query.go
- x/auth/keeper/grpc_query_test.go
Closes: #17204
`account.GetPubKey()` explicitly states that it can return nil, so I don't think we should return an internal error on that case.
---
I have...
I have...
> fix(x/auth): internal error on AccountInfo when PubKey is nil

- client/keys/add_ledger_test.go
- client/keys/add_test.go
- client/keys/delete_test.go
- client/keys/export_test.go
- client/keys/import_test.go
- client/keys/list_test.go
- client/keys/migrate_test.go
- client/keys/rename_test.go
- client/keys/root.go
- client/keys/root_test.go
- client/keys/show_test.go
- simapp/simd/cmd/root.go
- simapp/simd/cmd/root_v2.go
Closes: #XXXX
---
I have...
I have...
> refactor(keys): remove duplicate `--home` flag

- log/CHANGELOG.md
- log/logger.go
* Fix marshal [lazy](https://github.com/cometbft/cometbft/blob/main/libs/log/lazy.go) in `zerolog`
before
```
3:57PM INF starting node with ABCI CometBFT in-process module=server
3:57PM INF service start impl=multiAppConn module=proxy msg={}
3:57PM INF service start connection=query impl=localClient module=abci-client msg={}
3:57PM INF service start connection=snapshot impl=localClient module=abci-client msg={}
3:57PM INF service start connection=mempool impl=localClient module=abci-client msg={}
3:57PM INF service start connection=consensus impl=localClient module=abci-client msg={}
3:57PM INF service start impl=EventBus module=events msg={}
3:57PM INF service start impl=PubSub module=pubsub msg={}
3:57PM INF service start impl=IndexerService module=txindex msg={}
3:57PM INF ABCI …
```
> fix(log): add fallback to `Stringer` when type do not implement `json.Marshaler` interface

- testutil/context.go
- Adding a new test helper to add flexibility for creating a test context with multiple store keys (kvstore, transientstore, memstore)
Closes: #16998 
---
I have...
I have...
> feat(testutil): adding DefaultContextWithKeys test helper

- CHANGELOG.md
- client/rpc/rpc_test.go
- client/rpc/status.go
* Deprecated `clientCtx.LegacyAmino`
* Add json tag for consistency with [/status](http://127.0.0.1:26657/status?) api
> feat(cli): `status` cmd cli support output text

- CHANGELOG.md
- client/pruning/main.go
- server/export.go
- server/export_test.go
- server/rollback.go
- server/start.go
- server/util.go
- server/util_test.go
- simapp/simd/cmd/root.go
- simapp/simd/cmd/root_v2.go
- tests/e2e/server/export_test.go
- x/genutil/client/cli/collect.go
- x/genutil/client/cli/commands.go
- x/genutil/client/cli/genaccount.go
- x/genutil/client/cli/genaccount_test.go
- x/genutil/client/cli/gentx.go
- x/genutil/client/cli/gentx_test.go
- x/genutil/client/cli/init.go
- x/genutil/client/cli/init_test.go
- x/genutil/client/testutil/helpers.go
Ref: #17197
---
I have...
I have...
> refactor(cli): remove duplicate `--home` flag

- log/CHANGELOG.md
- log/go.mod
- log/go.sum
Closes: https://github.com/cosmos/cosmos-sdk/issues/16829
(Note the TODO still needs to implemented due to https://github.com/rs/zerolog/pull/560; however, we can still tag a 1.2.0).
Reviewers can do their DD with `git difftool log/v1.1.0 julien/prepare-log -- log`.
---
I have...
I have...
> chore: prepare log 1.2.0

- CHANGELOG.md
- tests/integration/distribution/keeper/msg_server_test.go
- x/distribution/types/params.go
- x/distribution/types/params_test.go
This change fixes a scenario in which Params.Validate() would panic when given a nil CommunityTax.
Fixes [#17235](https://github.com/cosmos/cosmos-sdk/issues/17235)
---
I have...
I have...
> fix(x/distribution): add nil check in Params.ValidateBasic

- CHANGELOG.md
- x/gov/client/cli/prompt.go
- x/group/client/cli/prompt.go
It is annoying to always have to specify the metadata. This add a flag to skip it.
---
I have...
I have...
> feat(gov,group): allow `draft-proposal` to skip metatada prompt

- CHANGELOG.md
- baseapp/abci.go
- baseapp/abci_test.go
- baseapp/baseapp.go
- docs/architecture/adr-064-abci-2.0.md
- docs/docs/core/00-baseapp.md
- types/context.go
This allows non-validators to verify votes. I've also removed `voteExtensionState` from baseapp and `ExecModeVoteExtension`.
---
I have...
I have...
> fix: Allow VerifyVoteExtensions without ExtendVote

- docs/docs/core/06-grpc_rest.md
Clarifies the valid paths for ABCI "/store/…" requests.
I have...
I have...
> docs: Better describe ABCI-exposed /key and /subspace store APIs

- docs/docs/basics/00-app-anatomy.md
- docs/docs/basics/02-query-lifecycle.md
- docs/docs/building-modules/09-module-interfaces.md
- docs/docs/core/07-cli.md
- docs/docs/run-node/02-interact-node.md
Fixes links to [Running a Node: Configuring the Node Using `app.toml` and `config.toml`](https://docs.cosmos.network/main/run-node/run-node#configuring-the-node-using-apptoml-and-configtoml) (many of which were using a probably-outdated `#configuring-the-node-using-apptoml` page anchor).
I have...
I have...
> docs: fix app.toml links

- CHANGELOG.md
- client/context.go
- client/context_test.go
https://github.com/cosmos/cosmos-sdk/pull/17187 removed the usage of `PrintObjectLegacy` in the codebase, which was deprecated for several versions. We can then remove this in v0.51.
---
I have...
I have...
> refactor!: remove `clientCtx.PrintObjectLegacy`

- docs/docs/tooling/00-protobuf.md
Fixes one typo in `docs/docs/tooling/00-protobuf.md`.
---
I have...
I have...
> docs: fix typo in `00-protobuf.md`

- CHANGELOG.md
- math/CHANGELOG.md
- math/int.go
- math/int_test.go
Closes: #17342
---
I have...
I have...
> fix(math): defend NewIntFromBigInt argument mutation

- docs/docs/migrations/_category_.json
- docs/docs/modules/_category_.json
remove "sdk" from modules and migrations. The user is reading the cosmos sdk docs should be self explanatory its the sdk modules and migrations 
---
I have...
I have...
> chore: remove sdk from side bar

- client/v2/autocli/app.go
- client/v2/autocli/builder.go
- client/v2/autocli/common.go
- client/v2/autocli/msg.go
- client/v2/autocli/query.go
- client/v2/go.mod
- x/crisis/autocli.go
- x/gov/autocli.go
Add a logger to client/v2. Note, by default the logging is disabled in client/v2 if no logger is provided.
In root_v2 we supply a no-op logger so it is as well disabled by default.
While playing with it, it surfaced a bug where it could happen that some subcommands could be added due to duplicate module keys.
Additionally, duplicate subcommands would not be correctly enhanced. This is fixed here as well.
---
I have...
I have...
> fix(client/v2): fix duplicate modules addition and add logger

- x/staking/keeper/liquid_stake.go
- x/staking/keeper/liquid_stake_test.go
- x/staking/keeper/msg_server.go
When re-delegating to an existing validator bond delegation, upstream changes to the validator struct are accidentally overwritten, preventing a validator set update. More specifically, in `msg_server.Delegate`, `IncreaseValidatorBondShares` is called with a `validator` struct; however, at this point, the validator struct is stale relative to the underlying validator in the store, which was modified above by `k.Delegate`. Thus, the validator in the store is overwritten.
[[Relevant code](https://github.com/cosmos/cosmos-sdk/blob/feature/v0.45.x-ics-lsm/x/staking/keeper/msg_server.go#L230-L242)]
```go
validator, found := k.GetValidator(ctx, valAddress)
...
k.Delegate(..., validator,...) // updates the validator in the store but does not change the validator variable
...
if …
```
> bug: lookup and return validators from liquid stake accounting functions

- .github/workflows/build.yml
- flake.lock
- flake.nix
Closes: #17437
- pin nixpkgs to latest master
---
I have...
I have...
> ci: Re-enable rocksdb backend in build.yml

- CHANGELOG.md
- RELEASE_NOTES.md
Prepare v0.46.15 release.
Tested on the following mainnets:
* N/A: the change set does not require tests on mainnets.  
---
I have...
I have...
> chore: prepare v0.46.15

- math/CHANGELOG.md
- math/int.go
- math/int_test.go
`.Size()` panics in the new math/v1.1.0 when there Int is nil:
cf: https://github.com/cosmos/cosmos-sdk/actions/runs/5921098375/job/16053189698?pr=17472
After this PR I'll tag v1.1.1.
---
I have...
I have...
> fix(math): fix panic in `.Size()`

- api/cosmos/bank/module/v1/module.pulsar.go
- api/cosmos/gov/v1beta1/query_grpc.pb.go
- proto/cosmos/accounts/v1/accounts.proto
- proto/cosmos/accounts/v1/query.proto
- proto/cosmos/accounts/v1/tx.proto
- proto/cosmos/gov/v1beta1/query.proto
- x/gov/types/v1beta1/query.pb.go
Closes: #XXXX
cref: https://github.com/osmosis-labs/osmosis/issues/6025
`Vote` Query in the gov module would return error upon trying to query any proposal that has already been finished. 
This is because how we delete all voter related data once the proposal has been finished.
Let's add a doc for this query for now so that people using it can avoid confusion.
After this PR, I am willing to make subsequent PR where we change error message. As of right now, trying to query passed governance would return "Voter not found for proposal" Whilst what we can do instead, is get lastest gov prop number from state, and if proposal has been already finished, return a different error, such as "Proposal already passed, cannot query vote state" etc. 
---
*All items are required. Please add a note to …
> docs: Improve docs for vote query

- math/CHANGELOG.md
- math/fuzz_test.go
- math/int.go
- math/int_test.go
This is a simpler version of #16263 that only optimizes values that fit in 53 bits. It is possible to optimize values that fit in 64 bits by using big.Int.BitLen and math.Log2(10), but it doesn't seem worth the complexity, especially given the revert of #16263.
I didn't succeed in beating big.Int.Marshal for values that don't fit in 64 bit.
CC @odeke-em @julienrbrt
> perf: optimize math.Int.Size for small values

- x/authz/keeper/keeper.go
- x/authz/keeper/keeper_test.go
When there are multiple authorizations, the cachedValue in the authorization will be assigned after the first grant is unmarshaled, and the cachedValue will not be assigned again for the second and subsequent grants
Because the grant is only created once.
both v0.46.x and v0.47.x have this problem.
---
I have...
I have...
> fix(x/authz): GetAuthorizations

- baseapp/abci_test.go
- baseapp/baseapp_test.go
- baseapp/grpcrouter_test.go
- baseapp/msg_service_router_test.go
Sometimes tests are failing in CI because the test logger does not work properly.
This updates it to always use a no-op logger within the baseapp tests.
---
I have...
I have...
> test(baseapp): use no-op logger

- SECURITY.md
Amends the SECURITY.md for the reporting refresh, aligned with the content at https://github.com/cosmos/security/blob/main/SECURITY_WITHBOUNTY.md
---
I have...
* [n/a] added a changelog entry to `CHANGELOG.md`
I have...
> docs: align SECURITY.md for refresh

- baseapp/baseapp.go
Allows for easier debugging when panics occur during tx execution. Willing to change the log message if needed.
Closes: #XXXX
---
I have...
I have...
> chore: log panic recovery in runTx

- store/storage/pebbledb/batch.go
- store/storage/pebbledb/db.go
- store/storage/pebbledb/iterator.go
- store/storage/rocksdb/db.go
- store/storage/sqlite/batch.go
- store/storage/sqlite/db.go
- store/storage/sqlite/iterator.go
- store/storage/storage_test_suite.go
- store/storage/util/bytes.go
The PebbleDB and SQLite SS backends did not handle range deletes correctly as illustrated by #17505. This PR addresses handling deletes correctly for those aforementioned backends.
* For SQLite, we handle this via a new tombstone column where the value indicates the version it's being deleted at (if not already tombstoned). This allows us to query and iterate correctly.
* For PebbleDB, we essentially do the exact same thing we do for SQLite, except we modify the value to contain the tombstone as a suffix.
* Fix iteration lower bound bug for PebbleDB
* Add more test coverage
ref: #17505
credit: @yihuang for the test updates
---
I have...
*All items …
> fix: properly handle deletes in ss stores

- tools/cosmovisor/README.md
this pr adds maintained versions to the readme
---
I have...
I have...
> chore: add maintained versions of cosmovisor to readme

- CHANGELOG.md
- x/genutil/types/genesis.go
Closes: #17570
---
I have...
I have...
> feat(x/genutil): Allow creation of AppGenesis without a file lookup

- CHANGELOG.md
- RELEASE_NOTES.md
- x/authz/keeper/keeper.go
- x/authz/keeper/keeper_test.go
Prepare v0.47.5 release:
Tested on the following mainnets:
* Juno
---
I have...
I have...
> chore: prepare v0.47.5

- docs/docs/building-modules/01-module-manager.md
Noticed while reviewing the deployed docs for https://github.com/cosmos/cosmos-sdk/pull/17575/ backport.
Follow up of https://github.com/cosmos/cosmos-sdk/issues/17554
---
I have...
I have...
> docs: update mm docs

- tools/rosetta/README.md
Closes: #17608 
This PR fixes the Rosetta documentation on the `release/0.47.x` branch so it is compatible with CosmosSDK 0.47.x.
---
I have...
I have...
> docs(rosetta): fix documentation

- x/staking/genesis.go
- x/staking/keeper/keeper.go
- x/staking/keeper/keeper_test.go
- x/staking/keeper/val_state_change.go
- x/staking/keeper/validator.go
Closes: #XXXX
Here https://github.com/cosmos/cosmos-sdk/pull/17498/files#diff-b751d8b426a3bbcb08ccee5040c1eff9f0ec8d88bde9103506ae1bf8767d6b25R229, the collections map should not have a bytes value but an gogoproto.Int64Value
Initially posted by @testinginprod on slack channel
---
I have...
I have...
> refactor(x/staking): Use gogotypes Int64Value instead of bytes for LastValidatorPower

- x/auth/keeper/keeper.go
- x/distribution/keeper/keeper.go
- x/evidence/keeper/keeper.go
- x/feegrant/keeper/keeper.go
- x/gov/keeper/keeper.go
- x/slashing/keeper/keeper.go
- x/staking/keeper/keeper.go
Closes: #17588 
---
I have...
I have...
> docs: Add k/v docs in structs using collections

- server/start.go
the `app.Close` is called in the `appCleanupFunc`, so no need to call in other places.
---
I have...
I have...
> remove duplicated app.Close call

- CHANGELOG.md
- orm/internal/codegen/file.go
- orm/internal/codegen/index.go
- tests/integration/rapidgen/rapidgen.go
- x/bank/keeper/view.go
- x/distribution/keeper/keeper.go
- x/feegrant/keeper/keeper.go
- x/gov/keeper/keeper.go
- x/gov/types/v1beta1/codec.go
- x/slashing/keeper/keeper.go
- x/staking/keeper/keeper.go
Closes: -
---
I have...
I have...
> chore: fix nolint comments

- CHANGELOG.md
- server/config/config.go
- server/config/config_test.go
- server/config/toml.go
Closes: #XXXX
---
I have...
I have...
> fix(config): mempool.max-txs configuration is invalid

- api/cosmos/accounts/v1/query.pulsar.go
- api/cosmos/accounts/v1/query_grpc.pb.go
- api/cosmos/accounts/v1/tx.pulsar.go
- api/cosmos/accounts/v1/tx_grpc.pb.go
- proto/cosmos/accounts/v1/accounts.proto
- proto/cosmos/accounts/v1/query.proto
- proto/cosmos/accounts/v1/tx.proto
- scripts/protocgen.sh
- x/accounts/account_test.go
- x/accounts/internal/implementation/api_builder.go
- x/accounts/internal/implementation/implementation.go
- x/accounts/internal/implementation/implementation_test.go
- x/accounts/internal/implementation/protoaccount.go
- x/accounts/keeper.go
- x/accounts/keeper_test.go
- x/accounts/msg_server.go
- x/accounts/msg_server_test.go
- x/accounts/query_server.go
- x/accounts/query_server_test.go
- x/accounts/v1/query.pb.go
- x/accounts/v1/tx.pb.go
Closes: https://github.com/cosmos/cosmos-sdk/issues/17615
---
I have...
I have...
> feat(accounts): Add message server and query server logic.

- CHANGELOG.md
- client/keys/add.go
- client/keys/add_test.go
Closes:
#10388
---
I have...
I have...
> feat: add base64 Pubkeys from cli

- CHANGELOG.md
- baseapp/baseapp.go
Close databases opened by cosmos-sdk during BaseApp shutdown.
Code previously reviewed in #17094
Only code for database close in this PR for use in current and past cosmos-sdk releases.
---
I have...
I have...
> feat: CV Close databases opened by cosmos-sdk during BaseApp shutdown

- CHANGELOG.md
- types/mempool/priority_nonce.go
- types/mempool/priority_nonce_test.go
Closes: #17392 
---
I have...
I have...
> fix: nil pointer ref priority nonce mempool iterator

- orm/encoding/encodeutil/util.go
This change removes an impossible len overflow check; the Go spec guarantees that len will always fit inside int per https://go.dev/ref/spec#Length_and_capacity and also by the time that len overflows int*, one would have run out of memory by then, given that int is guaranteed to be either 32-bits or 64-bits depending on the architecture, and even if we looked at virtual memory that is backed by virtual pages, the max memory mapped in-process will be the max of 32-bits or 64-bits.
Fixes #17616
/cc @elias-orijtech
> refactor: orm/encoding/encodeutil: remove impossible len overflow check

- types/module/module.go
reported by ibc that migrations were returning nil when passing using hasABCIGenesis as module1 would have been nil
---
I have...
I have...
> fix: genesis on migrations

- core/CHANGELOG.md
- core/comet/service.go
this pr pulls out core changes to a separate pr and makes the entire comet core a struct 
---
I have...
I have...
> refactor!: comet_info to struct

- UPGRADING.md
- docs/docs/build/building-apps/03-app-upgrade.md
- x/upgrade/README.md
ref: https://github.com/cosmos/cosmos-sdk/pull/17732#discussion_r1325035015
---
I have...
I have...
> docs: improve upgrade docs on preblocker

- CHANGELOG.md
- types/simulation/account.go
- types/simulation/account_test.go
- x/authz/simulation/operations.go
- x/bank/simulation/operations.go
- x/distribution/simulation/operations.go
- x/gov/simulation/operations.go
- x/group/simulation/operations.go
- x/nft/simulation/operations.go
- x/simulation/util.go
- x/slashing/simulation/operations.go
- x/staking/simulation/operations.go
As part of the simulator rewrite, this change makes RandomFees useful where a sdk.Context is not available.
CC @odeke-em
> refactor: remove unused context argument from types/simulation.RandomFees

- math/CHANGELOG.md
- math/fuzz_test.go
- math/int.go
- math/int_test.go
This reverts commit 952328a4ed1ea3db2cd3f3e6196421c4786286a8.
Closes: #XXXX
#17497 introduces a state-break. Validated on the Osmosis node.
The state break is probably stemming from using `float64`
For background, I've been backporting the switch to `math/v1.1.2` to v19 Osmosis node:
https://github.com/osmosis-labs/osmosis/pull/6341
Initially, my node failed at height **X + 30**. Debugging identified this as the cause: https://github.com/cosmos/cosmos-sdk/pull/17725
I proceeded by opening the PR against `main` and update the `math` dependency to my branch in #17725.
Note that my branch included the state-compat fix and #17497 on top of `math/v1.1.2` tag. #17497 is the only unreleased change.
After updating, my node started failing at height **X** (30 heights before the previous one). It …
> fix(math): Revert "perf: optimize math.Int.Size for small values (#17497)"

- depinject/README.md
Closes: #17743 
Since #12797, it's no longer possible to use non-exported functions as providers. The README used to contain examples with function literals as provider, so this change replaces them with exported functions.
An additional change updates the `BindInterface` arguments, which wasn't working on my side when running this code in go module called "duck".
---
I have...
I have...
> docs(depinject): replace non-exported provider functions

- UPGRADING.md
Another amendment for link correction
---
I have...
I have...
> docs: fix UPGRADING.md link

- store/iavl/store.go
- store/listenkv/store.go
- store/rootmulti/store.go
- store/streaming/constructor.go
- store/tracekv/store.go
A-7
Relates to https://github.com/cosmos/cosmos-sdk/pull/17794, but targets v0.47.
Store is its own go.mod on main.
---
I have...
I have...
> refactor(store): add missing error checks in store

- x/genutil/collect.go
This change moves []os.DirEntry close to where it is used and also reuses the already created sdk.AccAddress.String() []byte->string (sure it is cached but unnecessary to re-invoke) as a key to the balancesMap.
Fixes #17814 
/cc @elias-orijtech
> chore(x/genutil): cleanup CollectTxs

- docs/learn/advanced/00-baseapp.md
- docs/learn/advanced/01-transactions.md
- docs/learn/advanced/02-context.md
- docs/learn/advanced/04-store.md
- docs/learn/advanced/05-encoding.md
- docs/learn/advanced/06-grpc_rest.md
- docs/learn/advanced/07-cli.md
> docs: fix typos

- client/keys/import_test.go
Fixes undefined behavior that could result in test flakes on various environments by creating a unique directory per sub-test run of Test_runImportHexCmd. (*testing).T.TempDir() must not be mucked around with.
Fixes #17854
> test(client/keys): deflake Test_runImportHexCmd by a unique directory per sub-test run

- client/v2/autocli/testdata/help-deprecated-msg.golden
- client/v2/autocli/testdata/help-deprecated.golden
- client/v2/autocli/testdata/help-echo-msg.golden
- client/v2/autocli/testdata/help-echo.golden
- client/v2/autocli/testdata/help.golden
Found while auditing v0.50.0-beta0 vs v0.50.0-rc0. In the future, one can verify absence by running
```shell
$ git grep '\s\+$' | cut -d":" -f1 | sort | uniq
```
Fixes #17851
> chore(client/v2): remove trailing whitespace in golden files

- client/v2/autocli/app.go
- client/v2/autocli/builder.go
- client/v2/autocli/common_test.go
- client/v2/autocli/testdata/help-deprecated-msg.golden
- client/v2/autocli/testdata/help-deprecated.golden
- client/v2/autocli/testdata/help-echo-msg.golden
- client/v2/autocli/testdata/help-echo.golden
Closes: https://github.com/cosmos/cosmos-sdk/issues/17853
Reverts https://github.com/cosmos/cosmos-sdk/commit/35d93a97e6871ca334903d21f82e8f7811d0adce. The tests weren't run there because it did contain go code. The tests fail without those spaces, and running `go test ./... -update` re-adds them.
---
I have...
I have...
> chore(client/v2): better method naming

- x/nft/keeper/genesis.go
- x/nft/keeper/grpc_query.go
- x/nft/keeper/grpc_query_test.go
- x/nft/keeper/keeper_test.go
- x/nft/keeper/msg_server_test.go
- x/nft/keeper/nft.go
- x/nft/keeper/nft_batch.go
- x/nft/module/module.go
- x/nft/simulation/genesis.go
- x/nft/simulation/genesis_test.go
- x/nft/simulation/operations.go
ref https://github.com/cosmos/cosmos-sdk/issues/13140
this pr removes .String calls from the nft module. 
---
I have...
I have...
> chore(nft): remove address.String() calls from nft

- x/gov/client/cli/prompt.go
Closes: https://github.com/cosmos/cosmos-sdk/issues/17849
---
I have...
I have...
> chore(x/gov): improve `PromptMetadata` readability

- client/keys/import_test.go
Closes: 
#17854
---
I have...
I have...
> test(client/keys): Test_runImportCmd unique dir per test

- types/errors/README.md
Closes: #17448
Add a readme to the errors package in order to inform users separate from the godoc. 
---
I have...
I have...
> docs: add a readme to the types/errors package

- x/staking/keeper/alias_functions.go
Removes redundant returns and extraneous code.
Fixes #17844
> chore(x/staking/keeper): remove redundant code/returns

- x/README.md
- x/protocolpool/README.md
ref: #17657 
---
I have...
I have...
> docs(x/protocolpool): Update README.md 

- server/cmt_cmds.go
remove home grown version of bootstrap api 
---
I have...
I have...
> refactor(server): use bootstrap api from comet 

- api/cosmos/tx/signing/v1beta1/signing.pulsar.go
- client/docs/swagger-ui/swagger.yaml
- client/flags/flags.go
- proto/cosmos/tx/signing/v1beta1/signing.proto
- simapp/simd/cmd/root.go
- simapp/simd/cmd/root_v2.go
- types/tx/signing/signing.pb.go
- x/auth/tx/config/config.go
Extracting some changes from https://github.com/cosmos/cosmos-sdk/pull/17913
We were overwriting the tx options defined, which was letting the config fallback to the global config instead of the address codecs.
Ref: #17822
---
I have...
I have...
> fix(simapp): do not overwrite tx options

- baseapp/abci_utils.go
Closes: #XXXX
---
I have...
I have...
> refactor(abci): Pass context to `TxSelector`

- baseapp/abci_utils.go
Closes: #XXXX
---
I have...
I have...
> feat(abci): Add context to SelectedTxs

- x/staking/README.md
Fixes some typos noticed while reading through the x/staking README.
> chore(x/staking): fix some README typos

- CHANGELOG.md
- x/slashing/migrations/v4/keys.go
- x/slashing/migrations/v4/migrate_test.go
Closes: #18004
---
I have...
I have...
> fix: fixed key in slashing bitmap migration

- CHANGELOG.md
- x/staking/keeper/slash.go
This change hoists out, the parsing of non-changing validator address and delegator address which before were being re-parsed in every loop of the redelegation entries, parsing them once and reusing the already parsed addresses.
Fixes #18032
> fix(x/slashing/keeper): hoist non-changing addresses parsing out of redelegation loop

- baseapp/abci.go
- baseapp/abci_test.go
In v0.47.x when recovering from a panic during PrepareProposal we return a proposal that includes all the transactions that it got from RequestPrepareProposal. This was later modified (without a clear reason afaik, maybe just by mistake).
---
I have...
I have...
> fix: keep behavior from v0.47 in PrepareProposal panic recovery

- baseapp/options.go
- runtime/app.go
- runtime/builder.go
- simapp/app_v2.go
> fix(runtime): PreBlocker getting overwritten if set as a baseapp option

- CHANGELOG.md
- x/consensus/keeper/keeper.go
- x/consensus/keeper/keeper_test.go
- x/consensus/types/msgs.go
A40
check for nil params
---
I have...
I have...
> chore: check for nil params

- x/authz/genesis.go
- x/authz/module/module.go
A20
this pr proposes removing validate genesis as it was not doing anything before, its unclear if its needed? 
---
I have...
I have...
> refactor(x/authz): extend validate genesis

- CHANGELOG.md
- x/bank/exported/exported.go
- x/bank/keeper/keeper_test.go
- x/bank/keeper/migrations.go
- x/bank/migrations/v4/gen_state_test.go
- x/bank/migrations/v4/store.go
- x/bank/migrations/v4/store_test.go
- x/bank/types/params_legacy.go
Updates: #18107
---
I have...
I have...
> fix(x/bank): miss keypair of SendEnabled to restore legacy param set before migration

- docs/.vuepress/config.js
- store/streaming/file/service.go
Without this fix block meta data files emitted by the file state streaming grow forever since each successive file contains the txs of all prior blocks.  This just resets the tx list between blocks.
---
I have...
I have...
> fix(store/streaming): reset BlockMetadata between blocks

- CHANGELOG.md
- x/staking/keeper/slash.go
This change makes Keeper.Slash return early if there are no tokens to burn! This change also skips invoking the
.Hooks().BeforeValidatorSlashed hook because literally there is no slashing that can happen if there are no tokens to burn.
Given that the result of burning zero tokens SHOULD be a no-operation (noop) but we go through the whole routine, assuming no zero tokens would be burnt, one could argue on a protocol implementation/conformation that with zero tokens to burn, invoking Keeper.RemoveValidatorTokens which invokes:
Keeper.DeleteValidatorByPowerIndex
-> (Keeper.DeleteValidatorByPowerIndex)
-> validator.RemoveTokens
-> Keeper.SetValidator
-> Keeper.SetValidatorByPowerIndex
was causing a potential self inflicted Byzantine risk because that operation is non-atomic (it ran through a …
> perf(x/staking/keeper): make Slash return early iff zero tokens to burn

- CHANGELOG.md
- RELEASE_NOTES.md
- x/authz/keeper/keeper.go
- x/authz/keeper/keeper_test.go
Closes: #XXXX
---
I have...
I have...
> chore: prepare release notes v0.46.16

- CHANGELOG.md
- docs/docs/user/run-node/01-run-node.md
- server/start.go
Backports https://github.com/cosmos/cosmos-sdk/pull/18110
---
I have...
I have...
> feat(server): Start grpc and api server in standalone mode (v0.50.x)

- CHANGELOG.md
- x/gov/abci.go
- x/gov/keeper/deposit.go
- x/gov/keeper/hooks_test.go
- x/gov/keeper/proposal.go
- x/gov/keeper/vote.go
- x/gov/types/expected_keepers.go
- x/gov/types/hooks.go
A-9
No fix for v0.47 as we cannot introduce an api breaking change and cannot know if the hook failed.
---
I have...
I have...
> refactor(x/gov)!: let hooks return an error

- CHANGELOG.md
- Makefile
- baseapp/baseapp.go
- baseapp/options.go
- baseapp/test_helpers.go
- simapp/sim_test.go
- testutil/sims/state_helpers.go
- types/context.go
- x/auth/ante/sigverify.go
- x/auth/ante/sigverify_test.go
- x/group/simulation/operations.go
- x/simulation/client/cli/flags.go
- x/simulation/simulate.go
cosmos sdk provides a powerful simulation testing capability, and one of the simulation modes `TestFullAppSimulation` allows for simulation testing using data from `genesis.json`. The original implementation can be found at [https://github.com/cosmos/cosmos-sdk/pull/3428](https://github.com/cosmos/cosmos-sdk/pull/3428). However, with the release of v0.40.0, there have been significant changes to the code and `TestFullAppSimulation` is no longer being maintained.
The following are my steps:
To begin, the chain-related data can be initialized using the following command, at least 2 accounts must be added for genesis account, otherwise when executing SimulateMsgSend, two accounts will be selected to meet the conditions from != to and it will fall into an infinite loop.
```bash
simd init …
```
> fix(simulation): Fix all problems `make test-sim-custom-genesis-fast` for simulation test.

- x/gov/types/v1/params.go
A-14
Target v0.47 as this logic is already present in v0.50+
---
I have...
I have...
> refactor(x/gov): backport MinInitialDepositRatio validation from v0.50 to v0.47

- x/authz/generic_authorization.go
> fix(authz): check string is not empty

- math/CHANGELOG.md
- math/int.go
- math/int_test.go
Closes: #XXXX
---
I have...
I have...
> feat(math): Add mutative api for NewIntFromBigInt

- x/authz/go.mod
fix `golangci-lint run` for `x/authz`, as module `x/gov` go.mod was changed by [PR 18428](https://github.com/cosmos/cosmos-sdk/pull/18428) with `replace cosmossdk.io/api => ../../api`
I have...
> ci: fix x/authz golangci-lint run failed

- CHANGELOG.md
- RELEASE_NOTES.md
Prepare v0.47.6 release notes.
Tested again the following mainnets:
---
I have...
I have...
> chore: prepare v0.47.6 release notes

- CHANGELOG.md
Removes duplicated changelog items on [18026](https://github.com/cosmos/cosmos-sdk/pull/18026)
---
I have...
I have...
> chore: Fixed changelog duplicated items

- CHANGELOG.md
- baseapp/internal/protocompat/protocompat.go
ref: https://github.com/cosmos/cosmos-sdk/pull/18653#discussion_r1418926392
---
I have...
I have...
> fix(baseapp):  protocompat.go gogoproto.Merge does not work with custom types

- CHANGELOG.md
- x/gov/go.mod
- x/gov/types/v1/genesis.go
- x/gov/types/v1/genesis_test.go
> feat(x/gov): better gov genesis validation

- .github/pr_labeler.yml
- .github/workflows/pr_labeler.yml
PR labeler is currently broken: https://github.com/cosmos/cosmos-sdk/actions/runs/7187043385/job/19573747514
---
I have...
I have...
> ci: fix pr labeler

- docs/learn/beginner/01-tx-lifecycle.md
- x/circuit/README.md
related https://github.com/cosmos/cosmos-sdk/pull/18637     
A-26
---
I have...
I have...
> docs: add ante precision

- CHANGELOG.md
- baseapp/baseapp.go
- baseapp/regression_test.go
This change ensures that we correctly check if the app has a nil commit multistore before trying to dereference it or invoking .Seal()
Fixes #18726
> fix(baseapp): correctly check errors before sealing in BaseApp.Init

- x/auth/client/tx.go
Ref #18692 
Following function `ReadTxsFromFile` looks odd:
1. define out param with `tx []sdk.Tx`
2. then define a new variable named `txs []sdk.Tx`
3. `tx, err := txDecoder(txBytes)` another `tx` variable is defined
Although this does no effect for running, but it's odd and worse for read.
```go
func ReadTxsFromFile(ctx client.Context, filename string) (tx []sdk.Tx, err error) {
var fileBuff []byte
var txs []sdk.Tx
if filename == "-" {
fileBuff, err = io.ReadAll(os.Stdin)
} else {
fileBuff, err = os.ReadFile(filename)
}
if err != nil {
return nil, fmt.Errorf("failed to read batch txs from file %s: %w", filename, err)
}
// In SignBatchCmd, the output prints each tx line by line separated by "\n".
// So we split the output bytes to slice of tx bytes,
// last element always be empty bytes. …
```
> style(x/auth): improve code readability and update exported function comment

- .github/workflows/misspell.yml
Skip *.bin files in codespell to avoid warnings like:
WARNING: Cannot decode file using encoding "utf-8": ./tests/e2e/tx/testdata/tx_amino1.bin
WARNING: Trying next encoding "iso-8859-1"
Also avoids potential file corruption since using -w param. 
---
I have...
I have...
> chore: skip .bin files in codespell

- CHANGELOG.md
- x/feegrant/CHANGELOG.md
- x/feegrant/keeper/keeper.go
- x/feegrant/keeper/keeper_test.go
When the grantee `UseGrantedFees` is invoked, two scenarios can trigger the revoke of the allowance:
Scenario 1: Time expiration
Scenario 2: Allowance completely used up
https://github.com/cosmos/cosmos-sdk/blob/e352f57b81e522f11cf446ef21b6a4ff92ad0914/x/feegrant/basic_fee.go#L25-L41
In scenario 1, an error will be returned indicating that the transaction call has failed. A failed call means that all states will be rolled back, so revoke the allowance in this case is not meaningful. The revoke can only be effective when the error is nil.
> imp(feegrant): ensure we only execute revokeAllowance if there is no error is the grant is to be removed

- CHANGELOG.md
- x/auth/tx/service.go
We were puzzled by the huge gas wanted value output in the simulation failure response (`With gas wanted: '18446744073709551615' and gas used: '318310'`), thought we made some mistake in building the tx, but actually it's not the gas wanted we set in the tx, but due to an `InfinitGasMeter` is set in simulation mode bypassing the tx gas limit, which makes the `GasWanted` to be `MaxUint64`.
We suggest to remove this misleading value from the response.
Closes: #XXXX
---
I have...
I have...
> fix(x/auth): remove misleading gas wanted value from tx simulation failure response

- CHANGELOG.md
- x/auth/CHANGELOG.md
- x/auth/ante/sigverify.go
Closes: #XXXX
---
I have...
I have...
> refactor(auth): Move sig verification out of the for loop, into the authenticate method.

- docs/learn/learn.md
Quick fix, updating links
I have...
I have...
> docs: fix for links

- CHANGELOG.md
- client/tx/factory.go
Closes: #XXXX
In recent 0.47.7 version tx.Factory added new feild `fromName` , but it is only only set by `NewFactoryCLI` 
we need to set `fromName` using `withFromName()` because we need use this to simulate the txn without using `NewFactoryCLI`
---
I have...
I have...
> feat(client): add `WithFromName` to tx factory

- client/v2/autocli/flag/coin.go
- core/CHANGELOG.md
- core/coins/format.go
- core/coins/format_test.go
- x/tx/CHANGELOG.md
- x/tx/signing/textual/coins.go
- x/tx/signing/textual/coins_test.go
Moving `FormatCoins` to x/tx/signing/textual given that that's the only place where it's being used.
Closes: #XXXX
---
I have...
I have...
> chore: move FormatCoins to x/tx

- CHANGELOG.md
- types/coin.go
Coins.Sort() performs a heap allocation, even though sort.Sort() is in place.
This is because the compiler is doing {something} called runtime.convTSlice which internally makes a copy of the entire slice.
We should ideally find a solution that avoids this malloc for every Coins.Sort() of all sizes, but just eliminating it for slices of length <= 1 is already a big win, as Sort's are used throughout the Add and Sub logic.
(At least its a 2 second CPU savings win in Osmosis epoch code)
I have...
> perf: Speedup coins.Sort() when coins is of length 1

- math/CHANGELOG.md
- math/int.go
Remove a duplicate Overflow check from int.Mul
Note that big.Int's bitlength is the bit len of the absolute value of a number.
(In any base) if I multiply a `x` digit integer by a `y` digit integer, the resulting answer's digit-length is at most `x + y - 1`. You prove this to yourself by considering the result if you take a number bigger than the biggest `x` and `y` digit number.
I'll fix the base to `2` to explain this.
`2^x` is bigger than any x digit number, same for `2^y` and y.
`2^x * 2^y = 2^(x + y)` which is the smallest x+y digit number. Therefore the maximum product of a x digit and y digit number must be less than `2^(x+y)` which means its at most `x+y-1` bits.
This is the bit length check we are already doing!
So it suffices to just do one of the two checks.
In this pr I have …
> perf: Remove duplicate overflow check from int.Mul

- CHANGELOG.md
- types/dec_coin.go
Similar to PR #18875, I think that we should avoid this heap allocation if len(coins) <= 1.
> perf: Speedup DecCoin.Sort() when coins is of length 1

- CHANGELOG.md
- baseapp/abci_test.go
- baseapp/abci_utils.go
- baseapp/abci_utils_test.go
Closes: #18893
---
This PR resolves issue opened in #18893. This PR adds a validator address cache to `ValidateVoteExtensions` which ensure's that multiple of the same vote extensions cannot be included in the extended commit info.
I have...
I have...
> fix: Dedup Vote Extensions in `ValidateVoteExtensions`

- store/rootmulti/store.go
Closes: #XXXX
---
I have...
I have...
> fix(store/v1): Do not panic on prune in `Commit`

- server/v2/appmanager/service.go
- server/v2/core/appmanager/app.go
This pr adds VerifyBlock to the app manager in server/v2. The app manager has a new method for the prepare handler in which application developers can set a handler to verify contents of the block 
---
I have...
I have...
> feat(server/v2): add Verify block call 

- errors/CHANGELOG.md
- errors/errors.go
- errors/errors_test.go
- x/gov/abci.go
- x/gov/keeper/grpc_query.go
- x/gov/keeper/proposal.go
- Addition of reducing the indentation of "if block" for module `x/gov`
- Addition of return earlier when checked error is nil in `errors.IsOf`
> refactor(x/gov): reduce "if block" indentation

- server/v2/appmanager/service.go
- server/v2/core/transaction/validation.go
- server/v2/grpc/server.go
- server/v2/grpcweb/server.go
- server/v2/stf/mock/tx.go
- server/v2/stf/stf.go
- server/v2/stf/stf_builder.go
- server/v2/stf/stf_test.go
- server/v2/transaction/codec.go
This pr adds an api for validator set updates. This can only be called by one module in a chain. It is always called after endblocker, avoiding the need for ordering the module along side other modules 
---
I have...
I have...
> feat(server/v2): add valsetupdate API

- CHANGELOG.md
- server/util.go
Closes: #18781
---
I have...
I have...
> fix(server): consensus failure while restart node with wrong `chainId` in genesis

- CHANGELOG.md
- testutil/network/network.go
Closes: #XXXX
---
I have...
I have...
> test: add NodeURI for clientCtx

- UPGRADING.md
- docs/architecture/adr-070-unordered-account.md
- simapp/ante.go
- simapp/app.go
- simapp/app_v2.go
- x/auth/ante/unordered.go
- x/auth/ante/unordered_test.go
- x/auth/ante/unorderedtx/manager.go
- x/auth/ante/unorderedtx/manager_test.go
- x/auth/ante/unorderedtx/snapshotter.go
- x/auth/ante/unorderedtx/snapshotter_test.go
https://github.com/cosmos/cosmos-sdk/pull/18641 addresses the core implementation of unordered txs. However, a crucial component to safely support unordered txs is the ability to ensure the map that stores them is durable and consistent[1] across all nodes.
Specifically, when a node restarts, the unordered tx manager (map), needs to be populated with all NON-STALE unordered txs that have been committed so far, i.e. unordered transactions whose TTL value is yet to expire.
We propose to do this by simply writing to a file. However, we also need to address the case of where a new node joins a network via state sync. As it will naturally not have this file, we will also implement a snapshotter extension that will allow the manager (map) to be populated.
Ref:
* [1] The map only needs to be …
> feat: [ADR-070] Unordered Transactions (2/2)

- telemetry/metrics.go
Closes: #XXXX
---
I have...
I have...
> fix(config): metrics

- testutil/mock/logger.go
Ref: #18898 
fix errors
```shell
types/context_test.go:72:23: cannot use logger (variable of type *mock.MockLogger) as "cosmossdk.io/log".Logger value in argument to ctx.WithLogger: *mock.MockLogger does not implement "cosmossdk.io/log".Logger (missing method Warn)
types/context_test.go:98:39: cannot use logger (variable of type *mock.MockLogger) as "cosmossdk.io/log".Logger value in argument to types.NewContext: *mock.MockLogger does not implement "cosmossdk.io/log".Logger (missing method Warn)
```
> fix(testutil): mock logger missing method Warn

- codec/types/any_internal_test.go
This wrong tag value doesn't have an impact on the results of the test, but it's indeed set with the wrong value🤣 which may be have an impact in the future
> fix(codec/types): fix struct tag value

- .golangci.yml
Make it easier to see if a linter has already been added
> chore: sort linters in golangci-lint config

- tests/starship/tests/config.go
Found another wrong struct tag value, which still doesn't have an impact on the results of the test, but it's indeed set with the wrong value
> fix(tests/starship): fix struct tag value

- CHANGELOG.md
- x/slashing/abci.go
- x/slashing/keeper/infractions.go
- x/slashing/keeper/params.go
- x/slashing/types/params.go
Pretty light performance improvement. Its a been a consistent small point that validators missed block tracking appears in CPU profiles. (DB key format / data layout is the bigger issue to fixing) 
This at least removes the param deserialization of it. I don't have a "fair" benchmark to compare with on-hand over a large period, but on an IAVL v0 benchmark during 100 blocks with high CPU load, it appears params deserialziation is taking `.8%` of the CPU time for block execution.
Go tests are broken on my laptop rn for the SDK, hopefully this works without too many back + forths :pray:
I won't be able to fix too many follow-ups in a hot loop because of this, so happy to close if its not worth the overhead. (Or have someone else take over!)
This should be fully state compatible.
---
*All …
> perf: Don't deserialize params for every validator in slashing

- CHANGELOG.md
- x/slashing/CHANGELOG.md
- x/slashing/types/params.go
Follow up pr from https://github.com/cosmos/cosmos-sdk/pull/18959
---
I have...
I have...
> chore(x/slashing): follow up

- CHANGELOG.md
- types/result.go
- types/result_test.go
- x/auth/go.mod
Closes: #18906 
replace amino json encoding with standard library json encoding. We can opt for a faster lib if we want as well. 
---
I have...
I have...
> chore(types): replace amino json encoder with stdlib

- docs/learn/beginner/01-tx-lifecycle.md
- docs/learn/beginner/02-query-lifecycle.md
Closes: #18971
Edits `docs/learn/beginner/01-tx-lifecycle.md` and `docs/learn/beginner/02-query-lifecycle.md` to remove and fix some typos that I notice while going through the documentation. This points to https://docs.cosmos.network/main/learn/beginner/tx-lifecycle and https://docs.cosmos.network/main/learn/beginner/query-lifecycle respectively. I reviewed the effected changes in the built in markdown renderer in visual studio code to make sure that the spacing in the tx lifecycle state changes diagram particularly, looks acceptable.
---
I have...
- docs shouldn't affect tests
- seems like overkill for a minor change
- I don't know how to do this, …
> docs: Fix typos, broken link, spacing in diagram

- api/cosmos/accounts/v1/query.pulsar.go
- api/cosmos/accounts/v1/query_grpc.pb.go
- proto/cosmos/accounts/v1/query.proto
- tests/e2e/accounts/account_abstraction_test.go
- x/accounts/query_server.go
- x/accounts/v1/query.pb.go
SimulateUserOperation can be used by Bundlers to simulate the outcome of the execution of a UserOp.
The rationale for not using SimulateTX is to give granularity over the operation itself.
If we were to simulate a TX the bundler would most likely receive a response with more information pertaining the execution of the TX and not the operation itself. This also removes burden from the state machine to execute a full tx when only the op is needed.
---
I have...
I have...
> feat(accounts): Add Query to simulate a UserOperation

- testutil/network/util.go
Closes: #18992
Makes the change in the `FreeTCPAddr` to check if the port is free on `127.0.0.1` since `localhost` is not always equal to that IP as a standard.
Should not affect any systems where `localhost` is equal to that IP. Would only fix it for systems where that is not the case.
---
I have...
I have...
> fix(testutil): fix FreeTCPAddr localhost usage

- contrib/images/simd-env/Dockerfile
Closes: #19006 
fix docker image, i made a mistake and was copying the wrong go.mod
---
I have...
I have...
> fix: copy correct go.mod into container 

- client/v2/autocli/builder.go
- client/v2/autocli/flag/address.go
- client/v2/autocli/flag/builder.go
- client/v2/autocli/query_test.go
Tiny nits when looking at client/v2 code
---
I have...
I have...
> refactor(client/v2): use address codec instead of global

- docs/architecture/PROCESS.md
- docs/architecture/adr-069-gov-improvements.md
- docs/rfc/PROCESS.md
- docs/rfc/rfc-001-tx-validation.md
- store/proof.go
- x/staking/README.md
This PR fixes typos in the codebase.
Please review it, and merge if everything is fine.
If there are proto changes, run `make proto-gen` and commit the changes.
> chore: fix spelling errors

- CONTRIBUTING.md
Since PR #18579, there is no more other.md, and the link leads to a File not found : https://github.com/cosmos/cosmos-sdk/blob/main/.github/PULL_REQUEST_TEMPLATE/other.md
Deleted that part of the sentence. That's it. Hope I could be of any help.
> chore: updating CONTRIBUTING.md dead link

- orm/model/ormdb/module_test.go
Refer to #19040 
PR #19040  removed some imports and caused the test failed to run
---
I have...
I have...
> fix(orm): run module_test failed

- store/database.go
- store/proof.go
- store/storage/pebbledb/iterator.go
- store/storage/sqlite/iterator.go
This pr fixes all the issues reported by running `make lint`, except for the linting of module `cosmossdk.io/simapp` with `--build-tags=app_v1`.
```shell
linting module cosmossdk.io/simapp [2024-01-15T09:48:10+00:00]
app_config.go:70:2: var `moduleAccPerms` is unused (unused)
moduleAccPerms = []*authmodulev1.ModuleAccountPermission{
^
app_config.go:82:2: var `blockAccAddrs` is unused (unused)
blockAccAddrs = []string{
^
app_config.go:95:2: var `appConfig` is unused (unused)
appConfig = appconfig.Compose(&appv1alpha1.Config{
^
```
If the issues reported by linting `cosmossdk.io/simapp` with `--build-tags=app_v1` could be fixed, I think we could add a git hook for `make lint`, this will prevent contributors from pushing their commits without running `make lint`, reduce the times that team …
> ci: fix `make lint` reported issues

- x/staking/simulation/operations.go
Fix computations in the `TokenizeShares` operations making the staking-simulation tests pass again. 
---
I have...
I have...
> fix: update `TokenizeShares` operation in staking simulation

- api/cosmos/accounts/testing/counter/v1/counter.pulsar.go
- codec/collections.go
- proto/cosmos/accounts/testing/counter/v1/counter.proto
- runtime/gas.go
- simapp/app.go
- tests/e2e/accounts/wiring_test.go
- x/accounts/internal/implementation/context.go
- x/accounts/internal/implementation/encoding.go
- x/accounts/internal/implementation/implementation.go
- x/accounts/internal/implementation/protoaccount.go
- x/accounts/keeper.go
- x/accounts/testing/counter/counter.go
- x/accounts/testing/counter/v1/counter.pb.go
- x/accounts/utils_test.go
This PR allows accounts to have access to the binary codec, which is required for saving in state protobuf objects, and the gas service which is useful for AA implementers that need to consume gas (eg: sig verify gas cost). 
---
I have...
I have...
> feat(accounts): Add codec.BinaryCodec and Gas to dependencies.

- server/v2/cometbft/abci.go
- server/v2/cometbft/query.go
Removed the subpath parsing, now we expect the request Path to be `/store/<storeName>` and then the key is provided in the Data field.
---
I have...
I have...
> fix: remove subpaths in query

- x/auth/CHANGELOG.md
- x/auth/tx/builder.go
- x/auth/tx/builder_test.go
Closes: #19094
---
I have...
I have...
> fix: allow empty public keys when setting signatures

- store/commitment/iavl/tree.go
- store/commitment/iavl/tree_test.go
- store/commitment/store.go
- store/commitment/tree.go
- store/database.go
- store/root/store.go
- store/root/store_test.go
As we've discussed the solution for migration of apps to use store v2, we agreed that the easiest and most straightforward solution is to allow usage of store v2 using IAVL v0/v1 as the SC backend, while the SS backend and IAVL v2 syncs asynchronously in a background process.
Note, per the ADR, all queries go through SS. However, during the migration ONLY, i.e. syncing, SS won't have any historical data. So during migration ONLY, we want queries to fallback to SC when that data is not present in SS.
This PR adds support for such a feature.
ref: https://github.com/cosmos/cosmos-sdk/issues/18603
---
I have...
*All items are required. Please add a note …
> feat(store/v2): Fallback to SC on queries

- UPGRADING.md
Fixes a broken link to vote-extension documentation in the `BaseApp` section.
---
I have...
I have...
> docs: vote-extensions link in UPGRADING.md

- docs/DOC_WRITING_GUIDELINES.md
fix typo "OPTIONAL -> "OPTIONAL"
---
I have...
- docs shouldn't affect tests
- I don't think it's necessary to fix typo in CHANGELOG.md.
I have...
> docs: Fix typo in DOC_WRITING_GUIDELINES.md

- CHANGELOG.md
- baseapp/oe/optimistic_execution.go
Closes: #19197
---
I have...
I have...
> fix(OE): Remove usage of pointer in logs

- CHANGELOG.md
- Makefile
- simapp/simd/cmd/testnet.go
`--`-prefixed "long options" (as opposed to `-`-prefixed POSIX-style "short options") come from GNU, which recommends names composed of words: https://www.gnu.org/software/libc/manual/html_node/Argument-Syntax.html
> GNU adds <em>long options</em> to these conventions.  Long options consist of <samp>--</samp> followed by a name made of alphanumeric characters and dashes.  Option names are typically one to three words long, with hyphens to separate words.  Users can abbreviate the option names as long as the abbreviations are unique.
This PR therefore deprecates `--v` in favor of a new `--validator-count` spelling, and adds a corresponding POSIX-style `-n`  alias.
---
please add links to any relevant …
> chore(simapp): Deprecate --v in favor of --validator-count, -n

- baseapp/abci.go
Ensure ABCI listeners always execute in `FinalizeBlock`, regardless if OE is enabled or not. I opted to do this via a `defer` to make it as clean as possible.
closes: #19196
---
I have...
I have...
> fix(baseapp): ensure ABCI listeners always run in FinalizeBlock

- client/v2/CHANGELOG.md
- client/v2/autocli/app.go
- client/v2/autocli/builder.go
- client/v2/autocli/msg.go
- simapp/simd/cmd/root.go
- simapp/simd/cmd/root_v2.go
Ref: https://github.com/cosmos/cosmos-sdk/pull/19215
We do not need to overwrite tx config now that we have context sharing: https://github.com/cosmos/cosmos-sdk/pull/19060.
in app v1, textual is set in the root.go, so we can directly use the correct TxConfig from the clientCtx.
For app v2, we have already instantiated TxConfig in the default clientCtx.
---
I have...
I have...
> refactor(client/v2,simapp): align and simplify sign mode wiring

- server/v2/appmanager/appmanager.go
- server/v2/appmanager/go.mod
- server/v2/cometbft/abci.go
- server/v2/cometbft/go.mod
- server/v2/core/appmanager/app.go
- server/v2/core/store/gas.go
- server/v2/stf/gas.go
- server/v2/stf/stf.go
- server/v2/stf/stf_router.go
- server/v2/stf/stf_test.go
- server/v2/stf/types.go
this pr brings back preblock in the same way it exists in baseapp 
---
I have...
I have...
> refactor(server/v2): bring back preblock 

- CHANGELOG.md
- x/staking/keeper/validator.go
- x/staking/keeper/validator_test.go
Refactor `GetLastValidators` to not error in the sanity check when the cursor moves beyond `MaxValidators`. We remove the error and return nil so we can handle cases where the validator set is **decreased**.
---
I have...
I have...
> fix(x/staking): Refactor GetLastValidators 

- docs/architecture/adr-003-dynamic-capability-store.md
Fix the variable from k to ck for consistent and correct reference within the ScopeToModule method of the CapabilityKeeper struct.
---
I have...
I have...
> docs: Fix typo in adr-003-dynamic-capability-store.md

- tests/integration/staking/simulation/operations_test.go
- tests/sims/slashing/operations_test.go
Closes: #19253
Use the consensus key when creating validators in the tests module.
---
I have...
I have...
> test: use correct key types when creating validators

- core/appmodule/module.go
- go.mod
- go.sum
- simapp/go.mod
- simapp/go.sum
- simapp/gomod2nix.toml
Depinject didn't know how to fill-in map[string]appmodule.AppModule without this method.
Note, for avoiding a depinject import, we just add it directly to the AppModule struct.
This isn't breaking because we had that before.
---
I have...
I have...
> refactor(core): fix depinject detection

- scripts/hooks/pre-commit.sh
Related #19075
This is inspired by [cometbft/cometbft](https://github.com/cometbft/cometbft), `--fast` flag would make lint more faster
```shell
$ golangci-lint run --help |grep fast
--fast   Run only fast linters from enabled linters set (first run won't be fast)
```
> refactor: Add `--fast` flag to accelerate lint for git pre-commit hook

- .github/workflows/dependabot-update-all.yml
`save-state` and `set-output` commands used in GitHub Actions are deprecated and [GitHub recommends using environment files](https://github.blog/changelog/2023-07-24-github-actions-update-on-save-state-and-set-output-commands/).
This PR updates the usage of `set-output` to `$GITHUB_OUTPUT`
---
I have...
I have...
> ci: Use GITHUB_OUTPUT over set-output command

- log/CHANGELOG.md
2023-01-10 -> 2024-01-10
---
I have...
- docs shouldn't affect tests
- I don't think it's necessary to fix typo in CHANGELOG.md.
I have...
> docs(log): fixed incorrect changelog date

- x/tx/CHANGELOG.md
- x/tx/signing/textual/coins.go
- x/tx/signing/textual/internal/testdata/coin.json
Currently if a coin is `amount: 123 denom: ATOM, 123 STAKE`, it will be displayed to the user in a screen as `123 ATOM, 123 STAKE`. Now with this fix, the value renderer will error if it sees a comma.
This is not an issue for x/bank transactions given that we check with a regex those denoms, but it could be an issue for any other module that does not check for denoms when handling coins.
There could be other cases in which a `;` could be passed and the user mistakenly takes it as a separator, but I don't think we should make the checks in the formatter that extensive
---
I have...
*All items are required. Please add a note if the item is not …
> fix(textual): error if a formatted coin contains a comma

- baseapp/abci_utils.go
- baseapp/abci_utils_test.go
Follow up PR to improve readability in the code and tests
---
I have...
I have...
> test(baseapp): Refactor tx selector tests + better comments 

- internal/testutil/cmd.go
- internal/testutil/cmd_test.go
As the function's [comment](https://github.com/cosmos/cosmos-sdk/blob/main/internal/testutil/cmd.go#L11) described, I think `testutil.ResetArgs` is indeed well suited to be a test helper function.
It's designed for unit testing, so it's ok to own a param `t *testing.T`. And with `t *testing.T` being introduced, now we can remove the `panic`, replacing it with `t.Error`, this is more friendly to unit tests.
I have reconstructed the test cases and split them into groups, making them more clearer and easier to understand
> refactor(internal): change `testutil.ResetArgs` to a test helper function

- tests/integration/bank/keeper/deterministic_test.go
- x/bank/keeper/grpc_query.go
- x/bank/keeper/grpc_query_test.go
- x/bank/keeper/send.go
- x/bank/migrations/v3/store.go
- x/bank/migrations/v3/store_test.go
This PR skips running `addDenomReverseIndex` in `bank/v3` migration.
This operation was prohibitively expensive to run on the Cosmos Hub (required 128GB RAM) and took 5h to complete.
After consulting with the cosmos-sdk core team, it was deemed this migration is safe to skip as whitnessed by changes on osmosis' fork:
* https://github.com/osmosis-labs/cosmos-sdk/commit/15259ccd2249d2f3f413e0de7b8e27fe4cc6169a (disable migration)
The `DenomOwners` query that used the underlying index was disabled to avoid returning incomplete information (since the index would not contain all denom owners but only those who with recent transfers):
* https://github.com/osmosis-labs/cosmos-sdk/commit/7d98c6aea6614476eb1c708fbe5ddbe80e775260#diff-96f86cc0c27fc2ab4dc09f7cf4cb73a423ded3c71dbcd2b2a4182e6277f3b94dL …
> chore!: skip addDenomReverseIndex in bank v3 migration

- x/bank/app_test.go
- x/gov/README.md
- x/gov/keeper/deposit.go
- x/gov/keeper/export_test.go
- x/gov/keeper/msg_server.go
- x/gov/keeper/msg_server_test.go
- x/gov/types/errors.go
Backport of PR [18189](https://github.com/cosmos/cosmos-sdk/pull/18189)
---
I have...
I have...
> fix(x/gov): backport - limit deposited coins to accepted proposal denom PR 18189

- math/int.go
- math/int_test.go
- math/uint.go
- math/uint_test.go
Backporting PRs #17352 and #18214: Defend NewIntFromBigInt and NewUIntFromBigInt argument mutation.
---
I have...
I have...
> fix(math): Backport of pull requests #17352 and #18214 to feature/v.0.47.x-ics-lsm branch

- x/gov/abci.go
- x/gov/keeper/deposit.go
- x/gov/keeper/hooks_test.go
- x/gov/keeper/proposal.go
- x/gov/keeper/vote.go
- x/gov/types/expected_keepers.go
- x/gov/types/hooks.go
Backport of PR #18173: Introduce & handle errors returned by the gov module hooks
---
I have...
I have...
> fix(x/gov): Backport of pull request #18173 to feature/v.0.47.x-ics-lsm branch

- x/authz/keeper/keeper.go
- x/authz/keeper/keeper_test.go
- x/authz/module/abci.go
This is a partial backport of https://github.com/cosmos/cosmos-sdk/pull/18737.
Txs and events were not migrated.
AutoCLI was not migrated because it does not exist on v47.
---
I have...
I have...
> fix(x/authz)!: limit expired authz grant pruning to 200 per block

- x/feegrant/keeper/keeper.go
- x/feegrant/keeper/keeper_test.go
- x/feegrant/module/abci.go
This is a partial backport of https://github.com/cosmos/cosmos-sdk/pull/18047.
Txs and were not migrated.
EndBlocker behaviour was not changed since v47 x/feegrant::EndBlocker cannot produce an error during operation.
AutoCLI was not migrated because it does not exist on v47.
---
I have...
I have...
> fix(x/feegrant)!: limit expired feegrant pruning to 200 per block

- go.mod
- go.sum
- simapp/go.mod
- simapp/go.sum
- tests/go.mod
- tests/go.sum
Closes: https://github.com/cosmos/cosmos-sdk/issues/19374
Attempt to use the latest api from main in release/v0.50.x to fix the issue where api v0.7.2 didn't contain the released changes from gov.
We should still verift how autocli reacts given that we will be adding unreleased things into api (normally this https://github.com/cosmos/cosmos-sdk/pull/18324 should nicely hide those commands, but let's see).
Once I confirm everything works in CI and locally, we can tag api v0.7.3 and bump it here.
---
I have...
your handle next to the items reviewed if you only …
> build(deps): bump to cosmossdk.io/api v0.7.3

- math/CHANGELOG.md
- math/dec.go
Pretty slight performance speedup to Dec, by removing an unneeded Cmp against 0, with just using Sign.
This isn't that big of a systemic impact, but noticed it while I was looking at some code so thought I'd make a driveby PR.
---
I have...
I have...
> perf: Remove unneeded cmp in Ceil and marshalTo

- x/staking/simulation/operations.go
Fix a small bug in the `TokenizeShare` simulation introduced by the LSM SDKv47 upgrade.
Closes: #XXXX
---
I have...
I have...
> test: fix `TokenizeShare` simulation

- simapp/app.go
Closes: #XXXX
---
I have...
I have...
> fix(simapp): typo in GetStoreKeys

- CHANGELOG.md
- server/util.go
Closes: #XXXX
We noticed that after upgrading to cosmos-sdk v0.47.8+, our node panics upon restart. We traced the issue to https://github.com/cosmos/cosmos-sdk/pull/18920/files, which changes the way the node creates `DefaultBaseappOptions` at startup time.
Specifically, [this line](https://github.com/cosmos/cosmos-sdk/pull/18920/files#diff-f7a5b3de7e2284cfc3a3deca80a48a336566e6bc0b682a90156e691d876f38a2R507) assumes that the node uses `goleveldb` and tries to read the db files in `goleveldb` format, but our nodes use `rocksdb` by default.
After a node stop and restart, the node panics with
```
nibid start
panic: failed to initialize database: EOF
goroutine 24 [running]:
github.com/cosmos/cosmos-sdk/server.DefaultBaseappOptions({0x4551480, 0x4000df9340}) …
```
> fix: use proper `db_backend` type when reading chain-id

- .github/workflows/pr_labeler.yml
- .github/workflows/test.yml
- CHANGELOG.md
- testutil/sims/app_helpers.go
We weren't running `make test`  on direct merge on CI
Which is inconsistent with our other release branches: https://github.com/cosmos/cosmos-sdk/blob/release/v0.47.x/.github/workflows/test.yml
---
I have...
I have...
> ci: run test pipeline on merge v0.50 branch

- x/staking/keeper/delegation.go
- x/staking/keeper/query_utils.go
Closes: #XXXX
This PR fixes a couple of sections where the error is already checked to be nil, or the wrong error is checked
---
I have...
I have...
> fix(staking): fix impossible conditions

- CHANGELOG.md
- RELEASE_NOTES.md
- baseapp/abci_utils.go
- baseapp/info.go
Prepare v0.50.5
Compare: https://github.com/cosmos/cosmos-sdk/compare/v0.50.4...20386b3c5348f7ec6c23a9527fccc9d84211396e
---
I have...
I have...
> chore: prepare v0.50.5

- client/cmd.go
- client/config/config.go
- client/v2/autocli/common_test.go
- server/start.go
- store/db/rocksdb_noflag.go
- store/root/migrate_test.go
- tests/integration/server/grpc/server_test.go
- tests/starship/tests/suite.go
- tools/hubl/internal/load.go
- x/accounts/defaults/lockup/lockup.go
- x/accounts/defaults/lockup/protov2_wrapper.go
fix dependency update linting issues 
---
I have...
I have...
> chore: linting fixes

- simapp/upgrades.go
This fixes a 🐛 as the store key for accounts is not the module name. To be consistent, I have used the store keys for the other types as well
---
I have...
I have...
> fix(simapp): use correct store keys for upgrade

- client/flags/flags.go
- client/v2/autocli/testdata/help-echo-msg.golden
It wasn't clear to me why `gas-prices` could take a fraction of a denom, since they are indivisible. This clarifies how the value is calculated.
---
I have...
I have...
> docs: clarify gas-prices option

- CHANGELOG.md
- baseapp/abci.go
Closes: #19992
Updates baseapp.go to respond to queries with a "not found" error code rather than "invalid request" when the specified height has been pruned.
---
I have...
I have...
> feat(baseapp)!: Indicate pruning with "not found" rather than "invalid request"

- client/v2/CHANGELOG.md
- client/v2/autocli/common_test.go
- client/v2/autocli/query.go
Closes: https://github.com/cosmos/cosmos-sdk/issues/19975
---
I have...
I have...
> fix(client/v2): add encoder for `cosmos.base.v1beta1.DecCoin`

- CHANGELOG.md
- RELEASE_NOTES.md
- x/circuit/CHANGELOG.md
- x/evidence/CHANGELOG.md
- x/feegrant/CHANGELOG.md
- x/nft/CHANGELOG.md
- x/upgrade/CHANGELOG.md
Closes: #XXXX
---
I have...
I have...
> chore: update v0.50.6 release notes

- runtime/v2/app.go
- runtime/v2/go.mod
- runtime/v2/module.go
- runtime/v2/store.go
- simapp/v2/app_di.go
Closes: https://github.com/cosmos/cosmos-sdk/issues/19722
---
I have...
I have...
> refactor(runtime/v2): remove store v1 dep

- go.mod
- simapp/go.mod
- tests/go.mod
- tools/cosmovisor/go.mod
- tools/rosetta/go.mod
pushed directly to 47 but accidentally bumped the go version 
---
I have...
I have...
> chore: downgrade to go 1.19

- CHANGELOG.md
- baseapp/baseapp.go
- baseapp/grpcserver.go
- baseapp/options.go
- runtime/app.go
- runtime/builder.go
- runtime/module.go
Partial backport of https://github.com/cosmos/cosmos-sdk/pull/19571.
Expose grpc query router via depinject. 
---
I have...
I have...
> feat(baseapp): expose grpc query router via depinject.

- store/v2/commitment/iavl/tree.go
`Remove` behavior is inconsistent with store/v1.  This fixes it. 
See: https://github.com/cosmos/cosmos-sdk/blob/d7cc6de7cce55b6f0fab99e730a576978b1f90d7/store/cachekv/store.go#L159
https://github.com/cosmos/cosmos-sdk/blob/d7cc6de7cce55b6f0fab99e730a576978b1f90d7/store/iavl/store.go#L218-L224
---
I have...
I have...
> fix(store/v2): Remove should not error on miss

- CHANGELOG.md
- x/consensus/keeper/keeper.go
- x/consensus/keeper/keeper_test.go
replaces: https://github.com/cosmos/cosmos-sdk/pull/20314
---
I have...
I have...
> fix(x/consensus): harden consensus params proposal

- CHANGELOG.md
- x/distribution/types/msg.go
Closes: #XXXX
`MsgWithdrawTokenizeShareRecordReward.GetSignBytes()` uses `legacy.Cdc` instead of `ModuleCdc`. As a result it's not marshalled properly into the amino-json format, because it's not registered in `legacy.Cdc`.
The expected format is:
```json
{"type":"cosmos-sdk/MsgWithdrawTokenizeReward","value":{"owner_address":"cosmos...","record_id":"2"}
```
The current format is:
```json
{"owner_address":"cosmos...","record_id":"2"}
```
---
I have...
I have...
> fix(distribution): wrong codec usage

- tools/hubl/internal/compat.go
```go
if err != nil {
panic(err)
}
```
Since err has been checked above, it's better to panic with a detailed error message instead of a nil
> refactor(tools/hubl): don't use nil panic

- CHANGELOG.md
- go.mod
- go.sum
Closes: #XXXX
- update changelog
- bump hashicorp/go-getter to 1.7.4 to address https://pkg.go.dev/vuln/GO-2024-2800
---
I have...
I have...
> chore: prepare for v0.47.14-ics-lsm

- docs/build/building-modules/00-intro.md
- x/bank/README.md
This pr adds some light weight documentation on permissions in the system. It also touches on why bank does not place restrictions on moduletoaddress and moduletomodule sends. 
---
I have...
I have...
> docs: add docs on permissions

- CHANGELOG.md
- x/staking/keeper/validator.go
Closes: NA
Removes panic from GetLastValidators
---
I have...
I have...
> fix!: remove panic from GetLastValidators

- CHANGELOG.md
- x/authz/module/module.go
- x/feegrant/module/module.go
Closes: https://github.com/cosmos/cosmos-sdk/issues/20589
Better UX so that the keeper provided by depinject in the app as well contain the bank keeper.
We cannot make the UX better than that without have a breaking change. 
Users that want to have the bank keeper in the authz and feegrant modules and aren't using depinject need to call this themselves (however, shouldn't be needed as the check is in the message handling flow -- which takes the keeper from  the app module).
---
I have... …
> refactor(x/authz,x/feegrant): provide updated keeper in depinject

- math/dec_test.go
Description
Adds coverage for Dec testing for new decimal type for addition function
---
I have...
I have...
> feat(math): Upstream GDA based decimal type - Add function coverage

- CHANGELOG.md
- x/group/errors/orm.go
`x/group` shouldn't claim `"orm"` codespace. This was fixed in v0.50, but should be backported to v0.47. This prevents the upgrade of Regen Ledger to v0.47:
```
panic: error with code 11 is already registered: "can't update object with missing or invalid primary key"
goroutine 1 [running]:
cosmossdk.io/errors.RegisterWithGRPCCode({0x2b8eb61, 0x3}, 0xb, 0x2, {0x2b9e38d, 0xd})
/home/robert/go/pkg/mod/cosmossdk.io/errors@v1.0.1/errors.go:43 +0x265
cosmossdk.io/errors.Register({0x2b8eb61?, 0x0?}, 0x96be10?, {0x2b9e38d?, 0x5552090?})
/home/robert/go/pkg/mod/cosmossdk.io/errors@v1.0.1/errors.go:35 +0x28
github.com/cosmos/cosmos-sdk/x/group/errors.init()
/home/robert/projects/cosmos/regen/cosmos-sdk/x/group/errors/orm.go:12 +0x2f3
```
> fix(x/group): orm codespace name

- math/dec.go
- math/dec_rapid_test.go
- math/dec_test.go
Minor fixes and updates
---
I have...
I have...
> Fix tests and minor refactoring

- CHANGELOG.md
- client/cmd.go
Closes: #18430 
This PR fixes the grpc query deserialization issue with `math.LegacyDec` which is only happening with v0.47 releases.
---
I have...
I have...
> fix: panic `math.LegacyDec` deserialization

- CHANGELOG.md
- RELEASE_NOTES.md
- client/keys/add.go
- client/v2/CHANGELOG.md
- x/upgrade/CHANGELOG.md
https://github.com/cosmos/cosmos-sdk/compare/v0.50.7...release/v0.50.x
Needs: https://github.com/cosmos/cosmos-sdk/pull/20909
---
I have...
I have...
> chore: prepare v0.50.8

- math/dec.go
- math/dec_rapid_test.go
- math/dec_test.go
> Review comments

- math/dec.go
- math/dec_rapid_test.go
- math/dec_test.go
> feat(math): Upstream GDA based decimal type (docs)

- CHANGELOG.md
- client/tx/tx.go
- client/tx/tx_test.go
- simapp/simd/cmd/testnet.go
- simapp/v2/simdv2/cmd/testnet.go
- testutil/cli/cmd.go
- testutil/network/network.go
- x/auth/client/tx.go
Closes: https://github.com/cosmos/cosmos-sdk/issues/21430
We can use a `client.Context` in `tx.Sign` as it contains an address codec.
The change is minimally breaking as we always have a `client.Context` available when using `tx.Sign` and client.Context contains as well the command context.
---
I have...
I have...
> feat(client): use address codec for tx.Sign

- CHANGELOG.md
Closes: #XXXX
---
I have...
I have...
> chore: correct date cl v0.50.10

- runtime/v2/builder.go
- runtime/v2/module.go
- runtime/v2/store.go
- runtime/v2/types.go
- simapp/v2/app_di.go
Contained in: #21912 
---
I have...
I have...
> refactor(runtime/v2): use StoreBuilder

- runtime/v2/app.go
- runtime/v2/builder.go
- runtime/v2/manager.go
- runtime/v2/services/genesis.go
- simapp/v2/app_di.go
- simapp/v2/app_test.go
- simapp/v2/export.go
Alternative to: #21678 
---
I have...
I have...
> refactor(genutil): export genesis with val set implementation 

- core/CHANGELOG.md
- core/server/config.go
Part of: https://github.com/cosmos/cosmos-sdk/pull/22267
Introduces a `ConfigMap` type into core which can be used to inject modules with their fully realized configuration parsed form CLI flags and viper.
---
I have...
I have...
> feat(core): add ConfigMap type

- docs/user/run-node/08-onchain-multisig.md
> docs: fixed typo in threshold and quorums section of onchain multi-sig guide in user guide section of sdk docs

- tests/systemtests/upgrade_test.go
Fixes the testnet setup for chain upgrade system test
---
I have...
I have...
> test(system): Correct legacy chain initializer

- tests/integration/staking/keeper/delegation_test.go
- x/staking/client/cli/tx.go
- x/staking/keeper/liquid_stake.go
- x/staking/keeper/msg_server.go
- x/staking/keeper/tokenize_share_record.go
Changes only affect the LSM feature branches and tags.
---
I have...
I have...
> chore!: improve lsm err handling and testing

- CHANGELOG.md
- RELEASE_NOTES.md
Prepares v0.50.11: https://github.com/cosmos/cosmos-sdk/compare/v0.50.10...release/v0.50.x
Possibly blocked on 0044 and 0043
---
I have...
I have...
> chore: prepare v0.50.11

- x/distribution/keeper/keeper.go
- x/distribution/keeper/msg_server.go
Before distributing tokenized share rewards, the recipient's address must be verified. If the address is on the blocked list, the rewards should not be sent.
I have...
I have...
> fix: Check blocked addresses before sending tokenize shares rewards

- x/staking/keeper/slash.go
In https://github.com/cosmos/cosmos-sdk/pull/22538 we fixed slashing for redelegation, but since we don't want to fail if error is occurred when decreasing tokens, this is fixed in this pr.
I have...
I have...
> fix: LSM slasing of redelegation 

- testutil/configurator/configurator.go
- testutil/sims/address_helpers.go
- x/staking/testutil/helpers.go
This PR backports the changes made on main to the SDK while migrating integration tests.
ref: https://github.com/cosmos/cosmos-sdk/pull/22850#discussion_r1883514136
---
I have...
I have...
> chore: Using context.Context in x/staking and testutil test helper

- baseapp/abci_utils.go
- testutil/configurator/configurator.go
- x/staking/keeper/cons_pubkey.go
This PR backports the changes made on main while migrating x/staking integration tests.
ref: https://github.com/cosmos/cosmos-sdk/pull/22813#discussion_r1883512353
---
I have...
I have...
> chore: backport x/staking integration test migration changes

- server/v2/CHANGELOG.md
- server/v2/appmanager/CHANGELOG.md
- server/v2/cometbft/CHANGELOG.md
- server/v2/stf/CHANGELOG.md
- store/v2/CHANGELOG.md
Prepares v2 for tagging. After this PR I'll remove the replaces and ready to tag.
---
I have...
I have...
> chore: prepare v2 beta (1/3)

- CHANGELOG.md
- server/rollback.go
- server/util.go
- simapp/simd/cmd/commands.go
This pr allows for the rollback cmd to be replaced with other designs allowing other consensus engines to do rollbacks
---
I have...
I have...
> feat(server): make rollback command generic

- crypto/hd/hdpath_test.go
- crypto/ledger/encode_test.go
these examples cause test build errors are not important. we can always uncomment
> chore: comment out examples

- x/auth/signing/sig_verifiable_tx.go
restore this interface as it was removed and some clients rely on it
> chore: restore `TxWithTimeoutHeight` 

- simapp/simd/cmd/testnet.go
- testutil/key.go
- testutil/key_test.go
- testutil/network/network.go
- x/auth/signing/sig_verifiable_tx.go
Restores the `testutil.GenerateSaveCoinKey` signature to what it was in `v0.50`.  This change was introduced at some point does not seem necessary to break until we have a good reason:
1. it is a test utility
2. everywhere it was used in our codebase, it still used the global config path, and users can set this if they really need to
> chore: restore key testutil

- .github/workflows/dependencies-review.yml
This [vuln](https://github.com/cosmos/cosmos-sdk/actions/runs/13915084637/job/38936560326?pr=24023) keeps going off in our CI, but it is for versions of [Comet <= v0.38.16](https://pkg.go.dev/vuln/GO-2025-3443).  We use v0.38.17, but still get this error, so I am turning the check into a warning until we have a fix / move to comet v1.0.1
> chore: create temp fix for faulty vuln report in  CI

- simapp/simd/cmd/testnet.go
Closes: #23975
previously, you could do `init-files --v 3` to init testnet files with 3 validators. the flag has since been named to `--validator-count` with a shorthand of `-n`, but i think moving this to `-v` would be a more intuitive break. 
---
I have...
I have...
> chore: make validator-count flag less breaking

- .github/workflows/proto-registry.yml
- .github/workflows/proto.yml
- client/v2/internal/buf.yaml
- depinject/internal/appconfig/buf.yaml
- depinject/internal/appconfiggogo/buf.yaml
- proto/buf.yaml
- tests/integration/tx/internal/buf.yaml
- x/tx/internal/testpb/buf.yaml
- x/tx/signing/aminojson/internal/buf.yaml
- x/tx/signing/textual/internal/textualpb/buf.yaml
removes this warning:
```
**WARN    Category DEFAULT referenced in your buf.yaml is deprecated. It has been replaced by category STANDARD.
The concept of a default rule has been introduced. A default rule is a rule that will be run
if no rules are explicitly configured in your buf.yaml. Run buf config ls-lint-rules or
buf config ls-breaking-rules to see which rules are defaults. With this introduction, having a category
also named DEFAULT is confusing, as while it happens that all the rules in the DEFAULT category
are also default rules, the name has become overloaded.
As with all buf changes, this change is backwards-compatible: DEFAULT will continue to work.
We recommend replacing DEFAULT in your buf.yaml, but no action is immediately necessary.
**
```
> chore: fix proto building warning

- baseapp/block_gas_test.go
- client/utils.go
- x/distribution/client/cli/tx.go
- x/group/internal/orm/iterator_property_test.go
Closes: #XXXX
---
I have...
I have...
> chore(all): modernized code with built-in min/max

- UPGRADING.md
- baseapp/abci.go
- baseapp/baseapp.go
- baseapp/options.go
- server/config/config.go
- server/util.go
- simapp/simd/cmd/testnet.go
- tests/systemtests/upgrade_test.go
- testutil/network/network.go
- Remove all uses of `TimeoutCommit` in the codebase
- add new `NextBlockDelay` value to `baseapp` that can be set at app instantiation (we could further extend by adding a config field  but assuming this is fine for now)
> refactor: fix lint and use `NextBlockDelay` instead of `TimeoutCommit`

- UPGRADING.md
Celestia failed to upgrade to Cosmos SDK v0.50.x correctly because we missed a step when migrating to the capability module in ibc-go. See https://github.com/celestiaorg/celestia-app/issues/5340.
Ideally this PR helps prevent a similar mistake.
> docs(UPGRADING.md): improve v0.50.x release notes

- x/auth/keeper/deterministic_test.go
Delete key *storetypes.KVStoreKey from DeterministicTestSuite and remove suite.key = key in SetupTest as the raw key is not reused anywhere in this suite. The tests rely on storeService for keeper construction, making the key field redundant. Verified no linter errors.
> chore: Remove unused KVStoreKey field from DeterministicTestSuite in auth keeper tests

- types/coin_benchmark_test.go
- x/auth/ante/sigverify_benchmark_test.go
- x/tx/signing/textual/bench_test.go
BEFORE:
BenchmarkParseCoin-10 275319 4029 ns/op 2081 B/op 63 allocs/op
BenchmarkCoinsAdditionIntersect/A_1,B_1-10 5409805 297.8 ns/op 168 B/op 5 allocs/op
BenchmarkSig/secp256k1-10 8157 154376 ns/op 744 B/op 15 allocs/op
BenchmarkSig/secp256r1-10 18703 61438 ns/op 1296 B/op 24 allocs/op
BenchmarkIntValueRendererFormat-10 995870 1115 ns/op 784 B/op 19 allocs/op
AFTER:
BenchmarkParseCoin-10 270021 3902 ns/op 2081 B/op 63 allocs/op
BenchmarkCoinsAdditionIntersect/A_1,B_1-10 5444228 230.1 ns/op 168 B/op 5 allocs/op
BenchmarkSig/secp256k1-10 8332 147734 ns/op 744 B/op 15 allocs/op
BenchmarkSig/secp256r1-10 19350 60703 ns/op 1296 B/op 24 allocs/op
BenchmarkIntValueRendererFormat-10 1037956 1155 ns/op 784 B/op 19 allocs/op
reopen #25408
>  refactor: use b.Loop() in benchmark tests for better performance
