cosmos/cosmos-sdk

- app/app.go
- plugins/counter/counter.go
- plugins/ibc/ibc.go
- types/plugin.go
When trying to build a plugin that makes use of `InitChain`/`StartBlock`/`EndBlock`, I found that these methods were not being called. That's because the ABCI interface for these methods had been changed and the Basecoin ABCI app did not implement the `abci.BlockchainAware` interface, so ABCI silently stopped calling these 3 methods. This PR makes changes to properly implement the interface.
Note that the change in this PR breaks the plugin interface, although no existing plugins use these plugins so it should be trivial to upgrade.
Commit c23c01882499a9bbdfd58b334fe924f8862659f5 asserts that we don't silently drop this interface by accident in the future, but I'm not sure if this is a ghetto way to do this.
> Implement abci.BlockchainAware interface

- README.md
- cmd/commands/flags.go
- cmd/commands/query.go
- cmd/commands/tx.go
- cmd/commands/utils.go
- cmd/commands/utils_test.go
- docs/guide/basecoin-basics.md
- docs/guide/example-plugin.md
- docs/guide/ibc.md
- docs/guide/src/example-plugin/plugin.go
- plugins/counter/counter_test.go
- types/coin.go
closes #24 
closes #27 
added query subcommand register
modified the CLI to allow for multiple coin types sending to the transaction
fix Coin.IsGTE logic
> CLI Updates, Coin fix

- cmd/commands/utils_test.go
- plugins/counter/counter.go
- state/state.go
- state/state_test.go
- types/account.go
- types/account_test.go
- types/coin_test.go
- types/kvstore.go
- types/kvstore_test.go
- types/plugin.go
- types/plugin_test.go
- types/tx_test.go
NOTE this is branched from queryReg which is in the PR, should merge after PR #26
> Unit tests

- README.md
I followed the instructions and wrote down all the things that I had to do to get there
* Install Golang
* Install `glide`
* Set `$GOPATH` env var
* Make sure all the links I added point to the right place
This means `basecoin start` has succeeded (apparently) but the messaging is unclear. Should we add a note in the README to decipher it, or should we change the messaging?
```
~/go/src/github.com/tendermint/basecoin (develop) $ basecoin start 
no existing db, creating new db 
No genesis file at genesis.json, skipping... 
NOTE[03-01|12:56:51] Waiting for new connection...            module=abci-server
```
> Update README for n00bs

- state/execution.go
Fixed the formatting on an error message in AppTx (may not be reachable, since the same check occurs in CheckTx).
> Changed the format for the error message from %d to %v

- docs/guide/install.md
* Add `git pull origin master` to instructions if you have to run `make get_vendor_deps` and `make install` manually
> Update install.md to include git pull

- docs/go_basics.md
I helped @srm out on slack today to compile tendermint with a bugfix branch of go-p2p and realized there was no documentation for working with non-master branches here.  So I added some text.  Please give feedback and update, or just merge to develop.
> Added info on working with branches to the go basics guide

- cmd/basecli/adapters.go
- cmd/basecli/main.go
- glide.yaml
compressed main.go - no global access needed for those commands
referenced state in the key generation to eliminate code dup
added execute with debug
> base-cli cleanup

- cmd/commands/start.go
- glide.lock
- glide.yaml
```
$ basecoin start
loading existing db
I[06-02|06:18:29.290] Done setting Account via SetOption           module=app result=Success
I[06-02|06:18:29.290] Starting Basecoin with Tendermint            module=main chain_id=test_chain_id
ERROR: Expected either "info", "debug", "error" or "none" level, given state:info,*:error
```
> parse log level using tmlibs/cli/flags package (Fixes #97)

- .gitignore
- Makefile
- clitest/basictx.sh
- clitest/ibc.sh
- cmd/basecli/commands/adapters.go
- cmd/basecli/commands/apptx.go
- cmd/basecli/commands/cmds.go
- cmd/basecli/commands/query.go
- cmd/basecli/commands/sendtx.go
- cmd/basecli/counter/counter.go
- cmd/basecli/counter/query.go
- cmd/basecli/main.go
- cmd/counter/cmd.go
- glide.lock
- glide.yaml
Conjunction with https://github.com/tendermint/light-client/pull/21
> replace basecli state presenters with cmds

- cmd/basecli/commands/cmds.go
- cmd/basecli/counter/counter.go
- cmd/basecli/counter/query.go
- cmd/basecli/main.go
I wanted to make the process flow a bit more clear when generating a new AppTx transaction. Rather than passing around an `AppTx` struct to be have flags directly inserted into it, flags are parsed and fed to back up to the custom plugin app-tx command and then added to an `AppTx` struct as it's created. 
Additionally a few more commands that an plugin will typically not need to consider when developing the appTx have been clumped together and exported to the bcmd command (`BroadcastTx`)
Lastly, one nuance implication of these changes is they are more conducive to more complex multi-transaction commands which a developer may wish to implement. The common flags can be pulled as variables and applied to multiple transactions this way instead of needing to cross reference the previous …
> reorganize basecli appTx commands

- .gitignore
- docs/guide/basecoin-plugins.md
- docs/guide/ibc.md
- tests/cli/basictx.sh
- tests/cli/common.sh
- tests/cli/counter.sh
- tests/cli/ibc.sh
> bash testing cleanup

- Makefile
- app/app.go
- glide.lock
- tests/cli/common.sh
- tests/cli/restart.sh
This branch is an attempt to address the problem that all heights are off after the restart, and thus the light-client cannot make a decent proof.
There was a purported fix in `merkleeyes:fix-restart-height`, this PR adds a cli test to demonstrate the problem, and updates the glide dependencies to the most recent version of that branch.
When all tests pass and the merkleeyes branch is merged into develop, then this will be ready to merge.
To see the test issue, check out this branch, and try the following.
```
make all
DEBUG=1 ./tests/cli/restart.sh
```
`make all` updates all dependencies, compiles the binaries and runs all tests.  Assuming this fails, run the second command to get more debug output on fixing the restart test.  Notably the output of the basecoin server log.
> WIP: #106 wrong height on restart

- cmd/basecli/commands/apptx.go
- cmd/basecli/commands/cmds.go
I feel like the refactor from this structural change should maybe extend to sendTx - also maybe to the `SignAndPostTx` function in light client - like maybe we shouldn't need to wrap the Tx before sending here. gtg now but maybe we can discuss these changes and group in with this PR
> Add Signers in ReadAppTxFlags

- CHANGELOG.md
- cmd/basecli/commands/cmds.go
- cmd/basecli/commands/query.go
- cmd/basecoin/commands/init.go
- cmd/basecoin/commands/reset.go
- cmd/basecoin/commands/root.go
- cmd/basecoin/commands/start.go
- cmd/basecoin/main.go
- glide.lock
- glide.yaml
- tests/cli/basictx.sh
- tests/cli/common.sh
- tests/cli/counter.sh
- tests/cli/ibc.sh
This fixes up a number of issues with the cli tools, to make it easier to used based on testnet feedback.
Fixes:
#130 
#113 
#135
#137
> improve cli flags

- Makefile
- app/app.go
- app/genesis.go
- cmd/basecli/commands/auto.go
- cmd/basecli/commands/query.go
- cmd/basecli/main.go
- cmd/basecoin/commands/init.go
- cmd/basecoin/commands/key.go
- cmd/basecoin/commands/plugin_util.go
- cmd/basecoin/commands/reset.go
- cmd/basecoin/commands/root.go
- cmd/basecoin/commands/start.go
- cmd/basecoin/commands/utils.go
- cmd/basecoin/commands/version.go
- cmd/basecoin/main.go
- docs/guide/counter/cmd/counter/main.go
- docs/guide/counter/cmd/countercli/commands/counter.go
- docs/guide/counter/cmd/countercli/commands/query.go
- docs/guide/counter/plugins/counter/counter.go
- docs/guide/counter/plugins/counter/counter_test.go
- errors/common.go
- errors/main.go
- modules/coin/errors.go
- modules/coin/genesis.go
- modules/coin/handler.go
- modules/coin/store.go
- modules/coin/tx.go
- modules/fee/errors.go
- modules/fee/handler.go
- version/version.go
Only partially though, but should merge this PR so you can work more on it. Will pick up tomorrow again. 
Many small cleanups - also setting up for golint. If there are changes you want to make before merging please feel free to push them np. 
Core work in this PR is to:
- app/
- cmd/ 
- docs/guide/counter/
- errors/
- modules/
- vendor/
> golint + general cleanup

- app/app_test.go
- cmd/basecli/commands/query.go
- context.go
- docs/guide/counter/cmd/countercli/commands/query.go
- docs/guide/counter/plugins/counter/counter.go
- errors/common.go
- modules/coin/errors.go
- modules/coin/handler.go
- modules/coin/handler_test.go
- modules/coin/store.go
- modules/roles/error.go
- modules/roles/handler.go
- modules/roles/handler_test.go
- modules/roles/middleware.go
- modules/roles/middleware_test.go
- modules/roles/store.go
- modules/roles/store_test.go
- modules/roles/tx.go
- stack/dispatcher.go
- stack/helpers.go
- stack/helpers_test.go
- stack/helperware.go
- stack/middleware.go
- stack/mock.go
- stack/prefixstore.go
- stack/state_space_test.go
This addresses issue #150 and is a nice demo of adding a simple module with all the parts (handler, middleware, storage, custom errors, custom tx).
It can be used to create N-of-M accounts, to release with enough sigs.  You can also use multiple role wrappers to create (A and B) or C type logic
This also introduces state spaces for each module, so they only have access to a subset of the data store and cannot modify data of other modules without going through IPC.
> Add roles (multisig wallets)

- client/rest/README.md
- client/rest/handlers.go
- client/rest/proxy.go
- client/rest/types.go
- cmd/baseserver/README.md
- cmd/baseserver/main.go
A server that can be ran on port 8998
```shell
$ go get -u -v github.com/tendermint/basecoin/cmd/baseserver
$ baseserver init
$ baseserver serve
```
Implemented:
needed
This base code to get the handlers starters was adapted from:
* https://github.com/tendermint/go-crypto/blob/master/keys/server
* https://github.com/tendermint/basecoin/blob/unstable/client/commands/proxy/root.go
Updates #186
> client/rest, cmd/baseserver: started a basecoin REST client

- client/commands/init.go
- client/commands/proofs/get.go
- client/commands/proofs/root.go
- tests/cli/basictx.sh
You can now add `--trust-node` or `export BC_TRUST_NODE=1` when running any `basecli query` subcommand and it doesn't do any proofs, and doesn't even require init.
Eg. on a running basecoin node, you can simply run:
`basecli query account 0EFF929AA4A6D561FC53C00A9F878B929CAF3040 --node=localhost:46657 --trust-node`
> Add a flag to skip all query proofs

- .gitignore
- client/commands/proofs/get.go
- client/rest/cmd.go
- client/rest/handlers.go
- client/rest/types.go
- cmd/baseserver/main.go
- glide.lock
- modules/coin/rest/handlers.go
After offline emails and a video call with @ethanfrey,
a goal was decided to move things around i.e:
Due to that move, there is a lot of overlap between needed
code and utils so extracted common code to make
https://github.com/tendermint/tmlibs/pull/33
so make sure to pull in that commit into your tmlibs tree.
> client/rest, modules/coin/rest: moved code around

- app/store.go
- state/bonsai.go
- state/kvcache.go
- state/kvstore.go
- state/merkle.go
- state/merkle_test.go
I realized in the store overhaul, that KVCache no longer syncs in a deterministic order (as I had hoped not to need it for the merkle Tree).  That means that in multiple node setups, one would soon have consensus failure as the AppHash would diverge even for the same contents. (But not in the one-node unit tests...)
Added a test case to ensure that applying changes to DeliverTx and then Committing them produces a deterministic hash, and now order the key sync properly.
> Fix-up store

- docs/guide/key-management.md
- finishes #192 
- provides an overview of the commands for the `basecli keys` sub-command.
> docs: key management guide

- docs/guide/roles-and-multi-sig.md
> docs: roles and multi sig

- Makefile
- cmd/baseserver/README.md
- cmd/baseserver/main.go
- modules/coin/rest/handlers.go
- modules/roles/rest/handlers.go
- tests/cli/rest.sh
Implements doCreateRole
```shell
$ curl -X POST http://localhost:8998/build/create_role --data '{"role":
"abcdef", "sigs": 1, "signers": [{"addr":
"4FF759D47C81754D8F553DCCAC8651D0AF74C7F9", "app": "role"}]}'
```
```HTTP
HTTP/1.1 200 OK
Content-Type: application/json
Date: Fri, 04 Aug 2017 05:49:19 GMT
Content-Length: 233
{
"type": "role/create",
"data": {
"role": "616263646566",
"min_sigs": 1,
"signers": [
{
"chain": "",
"app": "role",
"addr": "4FF759D47C81754D8F553DCCAC8651D0AF74C7F9"
}
]
}
}
```
Updates #200
> modules/coin/rest: implemented doCreateRole

- cmd/baseserver/main.go
- modules/nonce/rest/handlers.go
This PR adds a REST handler for querying a sequence number via `/query/nonce/{signature}`.
> Started implementing nonce REST query handler

- state/kvcache.go
- state/merkle_test.go
The caching was writing cached reads again, which apparently changed the app hash (as the height of the node changed, even if the data didn't). This means the AppHash changes even in blocks with no tx.
This was exposed by a combination of historical queries and the ticker in gaia. But was a hidden bug in cosmos-sdk since the Canada retreat....
If we can merge this, we can save gaia!
> Bugfix: stable app hash

- Makefile
- examples/basecoin/Makefile
- examples/counter/Makefile
- examples/eyes/Makefile
Make basecoin compile again.
Just took out a few unix-isms from the Makefiles so it is more generic
> Windows compatibility

- CODEOWNERS
- examples/basecoin/app/app.go
- examples/basecoin/app/capkeys.go
- examples/basecoin/app/msgs.go
- examples/basecoin/app/routes.go
- examples/basecoin/app/sdkapp.go
- examples/basecoin/app/stores.go
- x/auth/account.go
- x/bank/wire.go
Group init functions into 4:
initCapKeys, initStores, initSDKApp, initRoutes.
Makes it clearer where things go, as the top-level init* methods correspond to their filenames.
* To create more capabilities keys, modify initCapKeys in app/capkeys.go
* To create more stores, modify initStores in app/stores.go
* To add more msg handlers, modify app/routes.go
* You probably don't need to touch app/sdkapp.go
> Sdk2 basecoinapp init

- types/coin.go
- types/coin_test.go
closes #356 
`Plus(coinB Coins)` rever return a coin with a 0 amount.
> Add tests for coins

- baseapp/baseapp.go
- baseapp/context.go
While working on testing app logic in https://github.com/tendermint/clearchain/tree/cosmos-sdk
I needed a way to actually set the initial state. As a flexible, yet simple, approach to exposing write access to the database, I wished to expose NewContext to the app constructor, so it may be used in the main function.
Example usage here: https://github.com/tendermint/clearchain/blob/cosmos-sdk/app/app.go#L66-L70
This can be called by test code init, or init from genesis file. A more complex solution may be added, but some general way to access the data store from main is always helpful.
> Expose NewContext, so I can initialize accounts

- baseapp/baseapp.go
- store/cachemultistore.go
- store/iavlstore.go
- store/iavlstore_test.go
- store/rootmultistore.go
- store/rootmultistore_test.go
- store/types.go
- types/errors.go
- types/result.go
- types/store.go
Add a Queryable interface, implemented by both rootMultiStore and iavlStore.
Path is assumed to be "/_storename_/_subpath_"
Multistore will look up the store by name, and if it is registered, and implements Queryable,
then it delegates the query to the substore.
iavlStore implements Query as the old sdk did in the application level. Tested it works directly on the iavlStore as expected.
> Add Proper query to BaseApp and rootMultiStore

- baseapp/baseapp.go
- baseapp/baseapp_test.go
- baseapp/context.go
- baseapp/genesis.go
- baseapp/router.go
- baseapp/testapp.go
- examples/basecoin/app/app.go
- examples/basecoin/app/app_test.go
- examples/basecoin/app/init_baseapp.go
- examples/basecoin/app/testapp.go
- examples/basecoin/cmd/basecoind/main.go
- types/coin.go
- types/coin_test.go
- types/context.go
- types/errors.go
- types/genesis.go
- types/handler.go
- types/signature.go
- types/store.go
- types/tx_msg.go
closes #339 
This PR includes some cleanup to make go-lint compliant
> Initialize Genesis State

- examples/basecoin/app/init_handlers.go
- x/auth/mapper.go
- x/bank/handler.go
- x/bank/mapper.go
CoinMapper is now called CoinKeeper to differentiate it from
AccountMapper. A Mapper retrieves things from a store. A Keeper exposes
functionality of coins and maintain invariants.
bank.NewHandler takes a CoinKeeper instead of the entire AccountMapper.
closes #426
> Refactor CoinMapper

- examples/dummy/main.go
- examples/dummy/tx.go
During transaction processing we retrieve the type of msg and based on
that we get the applicable handler from the router. This means that the
router should only receive messages that it knows how to handle. Instead
of using Get interfaces, we should cast to the actual type of
transaction and then access the transaction details that way.
It's okay to panic here, because if the DummyHandler receives a message
that it cannot cast to the expected type it means something is wrong
with the router. Instead of retrieving an arbitrary key by chance we
should panic.
> Strongly typed transactions in handlers

- baseapp/baseapp.go
- baseapp/baseapp_test.go
- examples/basecoin/app/app.go
- examples/basecoin/app/app_test.go
- types/abci.go
Begin/EndBlock handlers: https://github.com/cosmos/cosmos-sdk/issues/346
Background context for a block: https://github.com/cosmos/cosmos-sdk/issues/353
> baseapp: ctxCheck and ctxDeliver, begin/endBlocker

- Makefile
The whole point of things being in one repo is that we dont have to do a zillion glide updates.
So I am going to strongly advocate in favour of just using the top-level vendor dir for all testing and so in the SDK.
Otherwise, every time we break the SDK API, we have to perform glide magic in the examples dir. Madness!
> MERGE: makefile: dont use sub vendor deps

- baseapp/baseapp.go
Currently we are aborting running a transaction after the AnteHandler in
case it is a checkTx. This means that the handler never gets the chance
to check the validity of a transaction. Furthermore the AnteHandler
should not handle CheckTx logic.
The AnteHandler should handle global validation, whereas each Handler
should handle module validation.
closes #433
> REVIEW: Don't abort after AnteHandler if CheckTx

- baseapp/baseapp_test.go
- client/keys/wire.go
- client/tx/root.go
- client/tx/search.go
- client/tx/tx.go
- examples/basecoin/app/app.go
- examples/basecoin/types/account.go
- glide.lock
- glide.yaml
- mock/app.go
- store/wire.go
- wire/wire.go
- x/auth/ante.go
- x/auth/baseaccount.go
- x/auth/baseaccount_test.go
- x/auth/commands/account.go
- x/auth/mapper.go
- x/bank/commands/sendtx.go
- x/bank/wire.go
This is another take at PR https://github.com/cosmos/cosmos-sdk/pull/504 for issue https://github.com/cosmos/cosmos-sdk/issues/547
It's unclear when Tendermint will be updated to new go-wire. In the meantime, let's revert to old go-wire so we can launch testnets with the new SDK!
> revert to old go-wire

- client/builder/builder.go
- client/keys.go
- client/lcd/helpers.go
- client/lcd/lcd_test.go
- client/lcd/main_test.go
- client/lcd/root.go
- examples/basecoin/cmd/basecli/main.go
- examples/basecoin/cmd/basecoind/main.go
- server/init.go
- server/key.go
- server/start.go
- server/start_test.go
- types/tx_msg.go
- x/auth/ante.go
- x/bank/rest/root.go
- x/bank/rest/sendtx.go
https://github.com/cosmos/cosmos-sdk/issues/624
> lcd test cleanup

- docs/spec/README.md
- docs/spec/staking/definitions and examples.md
- docs/spec/staking/spec-technical.md
This part is ready for review @rigelrozanski @ebuchman. 
It does not contains yet fee-related logic, full unbonding of a candidate, liveliness transactions and stashing logic. We also haven't defined yet withdrawal logic. These should be addressed in the following PRs.
Please review the whole technical-spec and examples document, not just the content of this PR, as the previous version was merged to develop without review process.
> WIP: Staking Specification

- examples/basecoin/app/app.go
- examples/basecoin/cmd/basecli/main.go
- examples/basecoin/types/account.go
- examples/kvstore/tx.go
- mock/tx.go
- store/iavlstore.go
- types/account.go
- types/errors.go
- types/errors_test.go
- types/tx_msg.go
- x/auth/commands/account.go
- x/auth/rest/query.go
- x/auth/rest/root.go
- x/ibc/commands/relay.go
Parse is for Human Readable
Decode is for Machine Readable
https://github.com/cosmos/cosmos-sdk/issues/651
also fixes #649 
Decoders need to check for empty bytes.
> ParseAccount -> AccountDecoder; check for empty bytes

- examples/basecoin/cmd/basecoind/main.go
- server/show_node_id.go
Ref #704 (just `show_node_id`, not the rest of the command set yet)
> Add show_node_id command (closes #704)

- client/input.go
- client/keys/add.go
> Fix key add override bug

- client/builder/builder.go
- examples/basecoin/x/cool/commands/tx.go
- x/bank/commands/sendtx.go
- x/ibc/commands/ibctx.go
- x/ibc/commands/relay.go
- x/staking/commands/commands.go
It makes no sense to have passphrase as the parameter to builder which generates a lot of duplicate code.
> Encapsulate Get Passphrase Logic in Builder

- baseapp/baseapp.go
- baseapp/baseapp_test.go
- baseapp/router.go
- client/lcd/lcd_test.go
- examples/basecoin/app/app.go
- examples/basecoin/app/app_test.go
- examples/basecoin/x/cool/keeper.go
- examples/kvstore/main.go
- mock/app.go
- types/errors.go
- types/initgenesis.go
- x/auth/rest/query.go
Work in progress, more tests to come.
@rigelrozanski Thoughts?
> Per-module genesis initialization

- examples/basecoin/cmd/basecoind/main.go
- server/show_validator.go
> Add show_validator command from tendermint to basecoind

- x/stake/pool.go
- x/stake/pool_test.go
Includes basic tests and integration tests with random state / random operations.
Ref https://github.com/cosmos/cosmos-sdk/issues/731
> WIP: Staking pool tests

- CHANGELOG.md
- version/version.go
We should be making this kind of version bump immediately after release
> changelog and version

- x/stake/test_common.go
None of the modules should be importing from basecoin!
> stake: register auth.BaseAccount, not basecoin AppAccount

- x/stake/keeper.go
- x/stake/keeper_test.go
- x/stake/test_common.go
- x/stake/types.go
Ref #737
Awaiting rebase of `rigel/tick-tests` onto `develop`
Still need to write initial genesis info on `basecoind init` / `democoind init`
> Implement InitGenesis for staking

- x/stake/pool.go
- x/stake/pool_test.go
- x/stake/types.go
Only difference from existing tests - simulate a list of candidates instead of a single candidate.
This fails (nondeterministically, due to the timestamp RNG seeding):
```bash
--- FAIL: TestIntegrationInvariants (0.03s)
Error Trace:	pool_test.go:349
pool_test.go:378
Error:      	Should be false
Test:       	TestIntegrationInvariants
Messages:   	Applying operation "Added 194 tokens to candidate A58856F0FD53BF058B4909A21AEC019107BA6160 (assets: 1234, liabilities: 4947, delegatorShareExRate: {53489282989 214451589715})" resulted in negative candidate.Liabilities: -5 (candidate.Assets: 1428, candidate.PubKey: {PubKeyEd25519{0B485CFC0EECC619440448436F8FC9DF40566F2369E72400281454CB552AFB50}})
FAIL
```
> Simplified multi-candidate staking pool tests

- version/command.go
Per request of @greg-szabo - easier to parse in automated tooling
> Dash instead of space in version output

- x/stake/errors.go
- x/stake/handler.go
- x/stake/handler_test.go
- x/stake/keeper.go
- x/stake/keeper_test.go
- x/stake/pool_test.go
- x/stake/test_common.go
- x/stake/tick.go
- x/stake/tick_test.go
- x/stake/types.go
tick uses time 
staking has an endblock
closes #290 
closes #736 
replaces #752
> staking endblock /tick upgrade

- .dockerignore
- Dockerfile
One step towards easier testnet setup. CC @martindale - this should eliminate dealing with GOPATH on testnet servers.
Instructions at the top of the Dockerfile. Designed to be built locally after cloning the repository - we could also set up [automated builds](https://docs.docker.com/docker-hub/builds/) if that would be helpful for validators.
Changes nothing else, can be reviewed & merged.
> Add basic Dockerfile to build all binaries and export gaiad

- CHANGELOG.md
- client/context/viper.go
- client/core/context.go
- client/core/core.go
- examples/democoin/x/cool/commands/tx.go
- examples/democoin/x/pow/commands/tx.go
- x/bank/commands/sendtx.go
- x/ibc/commands/ibctx.go
- x/simplestake/commands/commands.go
- x/stake/commands/tx.go
Ref https://github.com/cosmos/cosmos-sdk/issues/810
> Misc CLI fixes

- x/bank/keeper.go
- x/bank/keeper_test.go
Closes #802
Also added test coverage to bank keepers.
> Adding more specialized keepers to bank

- CHANGELOG.md
- client/context/helpers.go
- client/context/viper.go
- cmd/gaia/cli_test/cli_test.go
Ref https://github.com/cosmos/cosmos-sdk/issues/950
Maybe we want to add this to the go-bash tests?
> Fix auto-sequencing (closes #950)

- cmd/gaia/app/genesis.go
- server/init.go
This ensures that users can rename the genesis transactions and they
will still be in the same order.
ref #940 #987
> Sort all genesis transaction by node id

- README.md
ref #1009
we require go1.10 elsewhere so might as well update it here.
> require go1.10 minimum

- CHANGELOG.md
- x/auth/msgs.go
- x/auth/stdtx.go
- x/auth/wire.go
- x/bank/client/rest/sendtx.go
- x/bank/msgs.go
- x/bank/msgs_test.go
- x/bank/wire.go
- x/stake/msg.go
- x/stake/params.go
- x/stake/pool.go
- x/stake/wire.go
The bank and auth modules now uses their own codecs to encode and decode Msgs into JSON. 
This closes #558. The code is adapted from Adrian's PR #534.
> Change to go-wire UnmarshalJSON for bank transactions

- CHANGELOG.md
- client/rpc/block.go
- client/rpc/root.go
- client/rpc/validators.go
- cmd/gaia/cli_test/cli_test.go
- cmd/gaia/cmd/gaiacli/main.go
- cmd/gaia/cmd/gaiad/main.go
- server/util.go
Implementation of #1068 
Old:
```
- gaiad
- export
- help
- init
- show_node_id
- show_validator
- start
- unsafe_reset_all
- version
- gaiacli
- init
- status
- block
- validatorset
- txs
- tx
- account
- validator
- validators
- delegation
- delegations
- send
- transfer
- relay
- create-validator
- edit-validator
- delegate
- unbond
- rest-server
- keys
- version
- help
```
New:
```
- gaiad
- init
- start
- tendermint
- unsafe_reset_all
- show_node_id
- show_validator
- export
- version
- help
- gaiacli
- init
- status
- state
- block
- validatorset
- txs
- tx
- stake
- validator
- validators
- delegation
- delegations
- create-validator
- edit-validator
- delegate
- unbond
- ibc
- transfer
- relay
- account
- send
- rest-server
- keys
- version
- help
```
> Refactored gaiacli and gaiad commands into subcommands

- x/slashing/handler.go
- x/slashing/keeper.go
- x/slashing/tick.go
Closes https://github.com/cosmos/cosmos-sdk/issues/1114
Slashing tests still reference staking for now (they need to create validators), perhaps those can be moved to a common testsuite later.
> Swap x/slashing to sdk.ValidatorSet

- baseapp/baseapp_test.go
This adds some more tests to baseapp, per #556. This PR includes tests for CheckTx, and it checks that runTx works as expected given certain types of invalid messages.
> Baseapp: Adding more tests

- CHANGELOG.md
- types/account.go
- x/auth/stdtx.go
- x/bank/msgs.go
- x/bank/msgs_test.go
- x/ibc/types.go
- x/slashing/msg.go
- x/slashing/msg_test.go
- x/stake/msg.go
Closes https://github.com/cosmos/cosmos-sdk/issues/1150.
> Use bech32 encoding for msg.GetSignBytes()

- CHANGELOG.md
- cmd/gaia/app/app.go
- x/auth/mock/simulate_block.go
- x/slashing/app_test.go
- x/slashing/keeper.go
- x/slashing/keeper_test.go
- x/slashing/signing_info.go
Closes https://github.com/cosmos/cosmos-sdk/issues/1199
Closes https://github.com/cosmos/cosmos-sdk/issues/1196
Can be cherry-picked for a testnet hotfix. This PR **does** change the state machine.
> Slashing bugfixes (start height, handler registration)

- Gopkg.lock
- x/auth/mock/simulate_block.go
- x/slashing/app_test.go
`make test` on develop is broken because of a fast-forward merge (in this case, of account numbers).
> Fix testcases (another fast-forward merge issue)

- cmd/gaia/testnets/README.md
> testnet readme usability overhaul

- .circleci/config.yml
- CHANGELOG.md
- client/lcd/lcd_test.go
- server/start_test.go
- server/test_helpers.go
Closes #1259. I've checked this on all usages of defer in the sdk.
> Don't run defers if it would result in an NPE

- CHANGELOG.md
- examples/democoin/x/cool/app_test.go
- examples/democoin/x/pow/app_test.go
- x/auth/mock/app.go
- x/auth/mock/auth_app_test.go
- x/bank/app_test.go
- x/ibc/app_test.go
- x/slashing/app_test.go
- x/stake/app_test.go
> Refactor Complete Setup to not take in a testing parameter

- cmd/gaia/testnets/README.md
The `gaiacli edit-validator` command was incomplete. I figured out what fields were needed. I believe every validator would love to know as well.
Also, I added quotes around moniker. People didn't know that you need quotes around monikers with spaces in them.
> testnet readme: how to edit validator description

- client/lcd/test_helpers.go
- x/auth/ante.go
I guess this still needs to be fixed properly by setting ChainID on InitChain.
Also bumped the log level to Debug.
With this change, the signature verification seems to pass, but the test halts because after the first block the sole validator gets unbonded. I.e we see the following in the logs after the first block: 
```
I[06-21|07:34:35.029] Updates to validators                        module=state updates="[{\"address\":\"\",\"pub_key\":\"AT/+aaL1eB0477Mud9JMm8Sh8BIvOYlPGC9KkIUmFaE=\",\"power\":0}]"
```
Maybe a bug in new unbonding ?
> fix ante. set lcd log to debug

- baseapp/baseapp.go
- examples/democoin/x/cool/keeper_test.go
- examples/democoin/x/pow/handler_test.go
- examples/democoin/x/pow/keeper_test.go
- examples/democoin/x/simplestake/keeper_test.go
- types/context.go
- types/context_test.go
- types/lib/linear_test.go
- x/auth/ante_test.go
- x/auth/context_test.go
- x/auth/feekeeper_test.go
- x/auth/mapper_test.go
- x/bank/keeper_test.go
- x/ibc/ibc_test.go
- x/slashing/test_common.go
- x/stake/test_common.go
> Remove TxBytes from NewContext

- CHANGELOG.md
- Makefile
- tools/Makefile
Previously, the install scripts weren't installing golint and gometalinter.
This commit fixes this, and installs tendermint's linter, and the HEAD of
the gometalinter repository. Now `make all` should work.
Closes #1052 , Closes #1190
> tools: Fix makefile install scripts

- CHANGELOG.md
- server/util.go
When loading the config file, this now checks in the sdk if the file
already exists. If not, it writes a config with different defaults.
The defaults differ by having the profiler listen address set,
and increasing the receive / send rates.
Closes #1098
> server: Use differing defaults from tendermint

- CHANGELOG.md
- tests/util.go
Adds a helper method to tests/util.go for waiting for N blocks to
pass. This is useful for situations when you need to wait for
multiple blocks to pass, but don't know the current block number.
In general, this is safer than using "wait for height", since the
block height could have advanced further than expected while the
test was running.
Resolves remaining point in #1283
> tests: add method to wait for n blocks to pass

- CHANGELOG.md
- types/tx_msg.go
- x/auth/ante.go
This method is an unneccessary requirement on Tx. Auth casts the Tx
to StdTx, so the memo can be obtained in previous usecases from
StdTx. This also makes it more clear for when something is
implementing StdTx vs Tx.
Resolves #1375
> types: remove GetMemo from Tx

- CHANGELOG.md
- types/rational.go
- types/rational_test.go
This now uses the underlying golang big.rat's string function,
instead of casting to num and den which are int64s.
Closes #1258
> types/rat: Fix overflowing in printing

- CHANGELOG.md
- x/auth/ante.go
No longer necessary, and confusing.
> Remove Viper from ante handler

- .circleci/config.yml
- CHANGELOG.md
- Makefile
- client/lcd/lcd_test.go
- examples/democoin/app/app_test.go
- examples/democoin/cmd/democoind/main.go
- examples/democoin/x/simplestake/keeper_test.go
- store/iavlstore_test.go
- tools/Makefile
- x/stake/client/cli/tx.go
- x/stake/keeper/delegation.go
- x/stake/keeper/inflation_test.go
- x/stake/keeper/validator_test.go
This errors on assignments that don't actually do anything. i.e.
x, err := myFunc(1)
y, err = myFunc(2)
This will call out that the first function's call error was never
used.
In this commit, I've sometimes made the second variable actually used, causing a greater changelog, though I think it was the correct update.
Ref #1417
> tools: Add ineffassign linter

- CHANGELOG.md
- client/context/helpers.go
- client/context/viper.go
- x/bank/client/cli/sendtx.go
This PR addresses https://github.com/cosmos/cosmos-sdk/issues/1193.
It adds an async flag to gaiacli send, to allow for many async txs in the same block. 
For now, sequence will have to be supplied from a script with --sequence if you want to send a lot of txs very quickly. Otherwise it will grab the first sequence from tendermint, but then it will continue to try the same sequence number. This can be updated once there is a way to store sequences locally (see comments in #1193) 
I don't think tests are needed, since this is just a cli call that uses funcs that already exist. I have tested it on a local testnet with branch develop and it works. 
Once you guys approve the changes, I will add in the async flag to democoin and basecoin, update changelog, and see if any docs need to be …
> Add async flag and functionality to gaiacli send

- docs/core/app1.md
- docs/core/app4.md
- docs/core/examples/app2.go
- docs/spec/slashing/end_block.md
- examples/README.md
Closes #1456
* [ X] ~Updated Gaia/Examples~
> docs: Fix dependencies, from monorepo merge

- .circleci/config.yml
- client/lcd/lcd_test.go
- client/lcd/test_helpers.go
- tests/util.go
```
ok      github.com/cosmos/cosmos-sdk/client/lcd 10.824s
```
Much better.
The `WaitFor` funcs were totally broken. Also made the block commit time 10x faster
> client/lcd: fix tests

- docs/index.rst
With forthcoming new docs website, we need to deprecate RTD. This PR is meant to be to master because develop lost all the RTD build stuff. DO NOT MERGE until the new docs site is up and running. But it also must be merged before the next SDK release.
* [N/A] Wrote tests
* [] Updated CHANGELOG.md
* [N/A] Updated Gaia/Examples
> add link to new docs location

- .circleci/config.yml
- Makefile
- baseapp/baseapp_test.go
- client/context/helpers.go
- client/lcd/lcd_test.go
- client/lcd/root.go
- client/lcd/test_helpers.go
- cmd/gaia/app/app.go
- cmd/gaia/cli_test/cli_test.go
- cmd/gaia/cmd/gaiad/main.go
- examples/democoin/app/app.go
- examples/democoin/cmd/democoind/main.go
- server/constructors.go
- server/init.go
- server/mock/app.go
- server/start.go
- store/rootmultistore.go
- store/rootmultistore_test.go
- tests/gobash.go
- tests/process.go
- tests/util.go
- x/stake/client/cli/tx.go
Updates a bunch of stuff in `tests`. Not sure where that `Process` code comes from but it seems a bit  buggy.
Still not 100% sure why I have to read from the Stdout pipe on some of those commands, otherwise the tests halt. But this seems to work.
Fixes circle too so we catch these if they fail.
Also fixed the unbond/redelegate commands to take the flags.
Our CLI still needs a lot of work.
> various fixes for test_cli

- docs/clients/ledger.md
This adds a brief `README` that details how to use the `ledger` app with `gaiacli`.
> Add Ledger Instructions

- docs/clients/ledger.md
- types/rational.go
- types/rational_test.go
> ready-for-review: check new rat decimal string length

- CHANGELOG.md
- cmd/gaia/cli_test/cli_test.go
* Makes all cli tests use .test_gaiad, .test_gaiacli instead of the
same directories as the default binaries
* Abstracts alot of the functionality for setting up the server into
a single function / file-wide constants. This is to reduce
code duplication, especially since some of this functionality
depends on each test setting up the keys in the same way.
Closes #1461, #1557
> tests: cli_tests no longer call `unsafe_reset_all` on local env

- CHANGELOG.md
- x/auth/client/cli/account.go
- x/bank/client/cli/sendtx.go
Now provides better error messages when the account you're sending
from has no money, or it has insufficient funds. (Avoids making
the user interpret ABCI errors)
closes #1489
> gaiacli: Improve error messages for `send` command

- CHANGELOG.md
- client/context/helpers.go
- client/context/types.go
- client/context/viper.go
- client/flags.go
- examples/democoin/x/cool/client/cli/tx.go
- examples/democoin/x/pow/client/cli/tx.go
- examples/democoin/x/simplestake/client/cli/commands.go
- x/bank/client/cli/sendtx.go
- x/gov/client/cli/tx.go
- x/ibc/client/cli/ibctx.go
- x/slashing/client/cli/tx.go
- x/stake/client/cli/tx.go
closes #1436
One question I have is if EnsureSignBuildBroadcast should have printResponse as a parameter, or if the governance command that used the response should just use something different.
> cli: Add async flag to all broadcasting txs

- cmd/gaia/cli_test/cli_test.go
- x/gov/client/cli/tx.go
It is standard in the sdk to use a dash for subcommands / flags
with multiple words. This makes submitproposal comply with that.
> gov/client: rename submitproposal to submit-proposal

- CHANGELOG.md
- client/lcd/test_helpers.go
- cmd/gaia/app/genesis.go
- server/init.go
- types/account.go
* `gaiad init gen-tx` makes the outputted file use bech32, with acct prefix
* `gaiad init --gen-txs` only reads bech32 with acct prefixes
The reason for using the account prefix is that in principle you could
have genesis transactions for non-validators.
Closes #1475
> gaiad: Genesis txs now use bech32 encoding of address and pubkey

- store/iavlstore.go
For testnets at least we should have the default be to keep all history so that bug hunting is easier.
Once other PRs (#1533 and #1580) come in we can have config / command line options to enable pruning manually for those that want to run lower disk usage nodes.
> store: Setting default back to archive mode / no pruning

- CHANGELOG.md
- baseapp/baseapp.go
- client/keys/add.go
- server/testnet.go
- server/util.go
- store/iavlstore.go
- tools/Makefile
- tools/gometalinter.json
- types/errors.go
- types/int.go
- types/rational.go
- x/auth/ante.go
- x/gov/client/rest/rest.go
- x/ibc/client/cli/relay.go
- x/stake/client/cli/tx.go
- x/stake/client/rest/tx.go
- x/stake/keeper/inflation_test.go
- x/stake/keeper/slash.go
- x/stake/keeper/validator.go
Gocyclo is a code complexity linter. It uses cyclomatic complexity.
Cyclomatic complexity essentially measures the number of different
paths code could go through. (The conditional in a for loop counts
as adding one path) It looks at this on a per-function level. The
idea that this would be enforcing is that if there are too many
different paths code can go through in a function, it needs to be
better split up. (A function with too many code paths is hard to
reason about)
The complexity which we want the linter to start failing on is
configurable. The default is 10. Change the "Cyclo" parameter in
`tools/gometalinter.json` to try other values.
I've left the errors in this first commit, just so everyone can take a look. (Plus
its likely I don't understand most of the functions well enough …
> tools: Add code complexity linter, gocyclo

- CHANGELOG.md
- x/stake/handler.go
- x/stake/handler_test.go
- x/stake/stake.go
- x/stake/types/errors.go
> prevent create-validator with duplicate pubkey

- baseapp/baseapp.go
- baseapp/helpers.go
> Cleanup Baseapp

- CHANGELOG.md
I've reordered the entries to have entries tagged under the same module put together. (I think it was kinda weird with them not together before)
Additionally I've added the following entries:
* Added MinInt and MinUint functions
* The keys sub-module is now in the sdk
* [keys] New keys now have 24 word recovery keys, for heightened security
* \#872  - recovery phrases no longer all end in `abandon`
Feel free to close this issue though, if there was some ordering, or we think that any sort of ordering doesn't matter. I don't feel strongly about it
> changelog: Reorder items in the changelog

- baseapp/baseapp.go
- x/mock/app_test.go
- x/stake/app_test.go
- x/stake/keeper/key.go
basically just run `make format`
also removed the nolint on baseapp.runtx, since joon made a pr to clean that function up
> Fix unformatted files

- CHANGELOG.md
- client/keys/update.go
- crypto/keys/keybase.go
- crypto/keys/keybase_test.go
- crypto/keys/types.go
Achieved by refactoring the parameter newpass as follows:
* (newpass string) -> (getNewpass func() (string, error))
Closes #1629
> keys: Keybase.Update no longer asks for newpass if oldpass is incorrect

- CHANGELOG.md
- client/lcd/lcd_test.go
- cmd/gaia/cli_test/cli_test.go
- x/gov/client/cli/tx.go
- x/gov/client/rest/rest.go
- x/gov/depositsvotes.go
- x/gov/errors.go
- x/gov/keeper.go
- x/gov/msgs.go
- x/gov/msgs_test.go
- x/gov/proposals.go
> ready-for-review:  Gov modules enums marshalJSON to String

- CHANGELOG.md
- x/stake/handler.go
- x/stake/handler_test.go
- x/stake/keeper/delegation.go
> R4R: Redelegation doesn't subtract from liquid

- CHANGELOG.md
- baseapp/baseapp.go
- client/lcd/test_helpers.go
- cmd/gaia/app/app.go
- cmd/gaia/cmd/gaiad/main.go
- cmd/gaia/cmd/gaiadebug/hack.go
- docs/clients/node.md
- examples/basecoin/cmd/basecoind/main.go
- examples/democoin/cmd/democoind/main.go
- server/constructors.go
- server/export.go
- server/mock/store.go
- server/start.go
- store/cachekvstore.go
- store/cachemultistore.go
- store/dbstoreadapter.go
- store/gaskvstore.go
- store/iavlstore.go
- store/prefixstore.go
- store/rootmultistore.go
- store/tracekvstore.go
- store/tracekvstore_test.go
- store/types.go
- types/store.go
* Implemented `TraceKVStore`
* Cleaned up some godocs (mostly server, stores and baseapp)
* Cleaned up structure in server constructors
* Added a CLI flag for KVStore tracing output (such a flag dictates tracing is desired opposed to needing two separate flags)
* Updated <root/cache>MultStore to support store tracing
<hr>
closes: #1523
> Implementation of TraceKVStore

- CHANGELOG.md
- baseapp/options.go
- cmd/gaia/app/app.go
- cmd/gaia/cmd/gaiad/main.go
- cmd/gaia/cmd/gaiadebug/hack.go
- examples/basecoin/app/app.go
- examples/basecoin/cmd/basecoind/main.go
- server/mock/store.go
- server/start.go
- store/iavlstore.go
- store/iavlstore_test.go
- store/rootmultistore.go
- types/store.go
> Pruning cleanup

- .github/PULL_REQUEST_TEMPLATE.md
> PR Template Admin Section

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/feature-request.md
- .github/ISSUE_TEMPLATE/issue-template.md
Two issue templates created:
- Bug Report
- Feature Request
Here is an idea of what it will look like https://help.github.com/articles/about-issue-and-pull-request-templates/
> Add Issue Templates

- cmd/gaia/app/app.go
- cmd/gaia/cmd/gaiadebug/hack.go
- x/params/keeper.go
- x/params/keeper_test.go
- x/params/msg_status.go
- x/slashing/app_test.go
- x/slashing/handler_test.go
- x/slashing/keeper.go
- x/slashing/keeper_test.go
- x/slashing/params.go
- x/slashing/signing_info_test.go
- x/slashing/test_common.go
- x/slashing/tick_test.go
> Global Paramstore

- Gopkg.lock
- Gopkg.toml
- Makefile
- crypto/ledger_secp256k1.go
- x/gov/client/cli/tx.go
This adds dep status to the lint process. Also fixes linting errors
that existed earlier. (not sure why they didn't show up on CI)
Closes #1574
For Admin Use:
> tools: Ensure Gopkg.lock is correct in linting

- Gopkg.lock
- Gopkg.toml
- client/lcd/lcd_test.go
- client/lcd/test_helpers.go
- server/export.go
- server/init.go
> update to tm0.22.4-rc0 and bring back lcd test

- types/coin_test.go
- types/rational.go
- types/rational_test.go
- types/utils_test.go
Make table driven tests in /types follow the format described in #1664
For Admin Use:
> types: Switch table driven test error messages to new format

- CHANGELOG.md
- server/util.go
- version/version.go
- x/gov/keeper.go
- x/gov/keeper_test.go
> update params for x/gov and default config

- CHANGELOG.md
- baseapp/baseapp_test.go
- baseapp/router.go
Previously only alphabetic characters were allowed.
Closes #1587
For Admin Use:
> baseapp: Allow alphanumerics in routes

- CONTRIBUTING.md
- types/coin_test.go
- types/rational.go
- types/rational_test.go
- types/utils_test.go
Indicates to use require's and asserts, and to use table driven
tests, with error messages as described in #1664.
Closes #1664
I don't think any of the below are relevant.
For Admin Use:
> contribution guide: Add guidelines for testing

- docs/DOCS_README.md
same file in Tendermint
For Admin Use:
> docs: how they're updated

- CHANGELOG.md
- x/stake/genesis.go
- x/stake/genesis_test.go
- x/stake/types/validator.go
Closes #1666 
- Also added revoked to human-readable validator, this is why it's so important to have all the functions close to the type definition
For Admin Use:
> R4R: Add Stake Genesis Intra-Tx Counter

- PENDING.md
- baseapp/baseapp.go
- client/lcd/lcd_test.go
- cmd/gaia/app/app.go
- cmd/gaia/cmd/gaiadebug/hack.go
- server/init.go
- x/gov/test_common.go
- x/slashing/app_test.go
- x/slashing/test_common.go
- x/stake/app_test.go
- x/stake/genesis.go
- x/stake/genesis_test.go
- x/stake/keeper/key.go
- x/stake/keeper/test_common.go
> Initialization of POS chain

- PENDING.md
- cmd/gaia/cli_test/cli_test.go
- docs/sdk/clients.md
- docs/sdk/gaiacli.md
- x/gov/client/cli/tx.go
- x/slashing/client/cli/tx.go
- x/stake/client/cli/tx.go
> R4R: CLI use --from consistently

- x/gov/proposals.go
close #1756 
All details  in #1756.
For Admin Use:
> x/gov: fix the bug about turning VoteOption byte to String

- Gopkg.lock
- PENDING.md
- client/lcd/lcd_test.go
- cmd/gaia/cli_test/cli_test.go
- cmd/gaia/cmd/gaiacli/main.go
- x/gov/client/cli/tx.go
- x/gov/client/rest/rest.go
> ready-for-review:  Query the votes on a proposal

- PENDING.md
- x/bank/app_test.go
* Update `x/bank` app unit tests to be (mostly) table-driven
* Cleaned up existing unit tests
closes: #1546 
<hr>
For Admin Use:
> Table-Driven Bank Module Unit Tests

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
Based on this PR https://github.com/cosmos/cosmos-sdk/pull/1792 which was opened before adequate discussion had taken place, unfortunately the contributing docs didn't indicate a procedure which includes discussion in an issue before coding
* [n/a] Updated all relevant code comments
* [n/a] Wrote tests
* [n/a] Added entries in `PENDING.md`
* [n/a] Updated `cmd/gaia` and `examples/`
For Admin Use:
> R4R: Contributing Guidelines advocate early discussion b4 coding

- CHANGELOG.md
- Gopkg.lock
- PENDING.md
- x/gov/tally.go
- x/gov/tally_test.go
Closes https://github.com/cosmos/cosmos-sdk/issues/1787
For Admin Use:
> Fixed governance bug with iterate delegations

- PENDING.md
- cmd/gaia/testnets/README.md
- docs/validators/validator-setup.md
- x/stake/client/cli/flags.go
also fixes #1766
- [n/a] Wrote tests
For Admin Use:
> R4R: CLI keybase-sig -> identity

- PENDING.md
- baseapp/baseapp.go
- cmd/gaia/app/app_test.go
> Fix gaiad export

- Makefile
- PENDING.md
- cmd/gaia/cli_test/cli_test.go
- cmd/gaia/cli_test/doc.go
This is done to make go test ./... work for people using the sdk as a sdk.
Closes #1806
For Admin Use:
> tests: Move cli tests behind a build flag

- PENDING.md
- server/init.go
This PR should close #1804
breaking changes were made in #1373 which broke the `gen-tx` mechanism in init. 
Example commands which demonstrate the break:
```
gaiad init gen-tx --name=foo --home=$HOME/foobar                                           
.............. > respond with some JSON indicating success 
gaiad init --gen-txs -o --home=$HOME/foobar
ERROR: Error{The genesis file must have at least one validator}
```
That final error should not be occurring. (basically non of the validators from any `gen-tx` are being processed and added to the genesis.json)
The current roll-back (aka my first commit here) has the Tendermint validators in the genesis file, which I think we've already removed? Not totally sure, I'm assuming that still needs to be updated in this PR @mossid …
> WIP fix gen-tx

- .github/PULL_REQUEST_TEMPLATE.md
- docs/RELEASE_PROCESS.md
During a discussion with @jaekwon, @cwgoes, @ValarDragon, @jlandrews today we came up with a possible release checklist to start using when cutting SDK releases. I've added the process we agreed to in a document at `docs/RELEASE_CHECKLIST.md`. I think we should use this process (except the fuzz testing) for the [`v0.23` release](https://github.com/cosmos/cosmos-sdk/pull/1769) as a test run. 
This would mean we need to spend tomorrow using the [Plain English test "script"](https://docs.google.com/document/d/1KJJy1Llg83CxtPnNYdz86G67sUqTvyjcHkm7A3CTQ2A/edit) to ensure the functionality of the release before cutting it.  We would also need buy in on the `CHANGELOG.md` updates proposed in the release process.
Tagging @zmanian and @ebuchman for comment and feedback.
> Add a Release Process for SDK

- PENDING.md
- x/stake/client/cli/flags.go
- x/stake/client/cli/tx.go
Addresses #1828 
For Admin Use:
> Must specify amount flag

- PENDING.md
- x/stake/genesis.go
- x/stake/genesis_test.go
Closes https://github.com/cosmos/cosmos-sdk/issues/1839
For Admin Use:
> Fix genesis bond intra-tx counter bug

- .circleci/config.yml
This commit makes it such that circle CI only shows the module whose
tests it is currently running in the log, unless a test fails. For each
failing test, it will display the test name and all of the log output. This is done to make
our log output far more scrollable. We lose no information in debugging.
For Admin Use:
> CI: Reduce log output

- PENDING.md
- x/stake/handler.go
- x/stake/keeper/validator.go
This removes running the power update logic on handleMsgEditValidator,
as its unnecessary.
Closes #1815
For Admin Use:
> x/stake: Speed up handleMsgEditValidator

- PENDING.md
- cmd/gaia/app/app.go
- x/gov/endblocker_test.go
- x/gov/handler.go
- x/gov/test_common.go
> R4R: Add slashing to governance for non-voting validators

- PENDING.md
- cmd/gaia/cli_test/cli_test.go
- cmd/gaia/cmd/gaiacli/main.go
- x/gov/client/cli/tx.go
> R4R: Query-proposals CLI command

- PENDING.md
- client/lcd/lcd_test.go
- x/slashing/client/rest/query.go
- [z] Added entries in `PENDING.md` that include links to the relevant issue or PR that most accurately describes the change.
- [n/a] Updated `cmd/gaia` and `examples/`
As discussed in #1866, REST endpoint `/slashing/signing-info/{ validator }` should take `cosmosValPub` rather than existing `cosmosVallAddr` in order to maintain consistency between REST and CLI interfaces.
For Admin Use:
> update signing info endpoint

- .github/PULL_REQUEST_TEMPLATE.md
This PR adds a quick note about checking the Spec to the PR template. I added to an existing item.
> Add note about checking spec to the PR template

- PENDING.md
- client/input.go
- cmd/gaia/app/genesis.go
- cmd/gaia/cli_test/cli_test.go
- cmd/gaia/testnets/README.md
- tests/gobash.go
I believe `gen-tx` would lend itself to having a better UX if the user could provider their own desired key password when generating a key. The default is used if nothing is provided.
I'm not sure if anything is automated that uses `gen-tx`, if so this might break that and we could simply decline ☹️ 
<hr>
For Admin Use:
> R4R: gen-tx: Support User Given Key Passwords

- types/int_test.go
Currently they take ~1 minute on circle CI. There isn't a significant reason
for this to delay all our tests. This commit reduces the time spent on these
tests by a factor of 20.
For Admin Use:
> types: Reduce size of TestImmutability<Arith\U>Int tests

- crypto/keys/keybase_test.go
Currently the crypto/keys tests take 2 minutes in circle CI.
A significant portion of this time is due to the bcrypt security
parameter. Changing it for these tests should reduce the time significantly.
For Admin Use:
> crypto/keys: Reduce bcrypt parameter in tests

- store/rootmultistore_test.go
The helper function `newMultiStoreWithMounts` in `rootmultistore_test.go` creates 3 substores for use in tests. It currently passes in a `db` parameter with each store, which causes them to share the db and overwrite each other's nodedbs. On current tests this doesn't fail because none of them reload the multistore from db. I've added a few lines which do this in one test, and it fails non-deterministically with different errors depending on the map iterator order in `commitStores`, with the last store written overwriting values of the previous stores, for things such as root hash.
Switching `newMultiStoreWithMounts` to pass in `nil` to each store causes it to use a prefix store on the db in the `rootMultiStore` which solves the problem and seems like the intended behavior of the helper …
> RootMultiStore test helper bugfix

- PENDING.md
- server/util.go
> enable indexing of all tags by default

- Gopkg.lock
- x/stake/client/rest/query.go
> R4R: fixed delegations endpoint

- docs/validators/validator-faq.md
Just updating the val faq with latest info.
Closes https://github.com/cosmos/cosmos-sdk/issues/1885
For Admin Use:
> Update validator faq

- Gopkg.lock
- Gopkg.toml
- version/version.go
- x/slashing/params.go
Suggested additions prior to release, see https://github.com/cosmos/cosmos-sdk/pull/1991#issuecomment-412486822.
For Admin Use:
> Stage onto release/v0.24.0

- Makefile
Closes #2005
Changelog update seems unwarranted, as this is really just a minor UI improvement that changes no workflow.
For Admin Use:
> makefile: Improve error message when LEDGER_ENABLED=True & no gcc

- PENDING.md
- cmd/gaia/app/app.go
This caused an error with non-determinism between nodes with same
gaiad version and genesis. Fixes the issue (we think) for what we saw in internal testnets.
For Admin Use:
> Rename transient store key to be a unique key.

- Makefile
- PENDING.md
If dep already sees its scratch directory (.vendor-new), dep ensure fails. This rm -rf's that directory so that `make get_vendor_deps` doesn't fail.
For Admin Use:
> dep: Fix error with scratch directory

- types/decimal.go
This is done by making the function mutative. A non-mutative variant
is created for functions that depend on it being non-mutative.
~Needs rebase once #2029 is merged. (That build error is still present in LCD tests, these tests pass once that is included)~ Rebased
No changelog entry required imo, since big decimal is new to this release.
For Admin Use:
> decimal: Remove unnecessary allocation in bankers round chop

- examples/README.md
Using the addresses in Bech32 form
For Admin Use:
> The examples aligned to Bech32

- client/lcd/lcd_test.go
- x/stake/client/rest/query.go
- x/stake/client/rest/utils.go
Use the owner address instead of pubkey address in queries, 
Also no more iteration to find a validator, see this issue for more:
Closes https://github.com/cosmos/cosmos-sdk/issues/2032
For Admin Use:
> R4R staking lcd bugfix

- CHANGELOG.md
- cmd/gaia/cmd/gaiacli/main.go
- x/stake/client/cli/query.go
> R4R: Fix repeated cmds in CLI for staking (v.0.24.0 release)

- PENDING.md
- x/stake/client/cli/query.go
- x/stake/client/cli/tx.go
- x/stake/types/delegation.go
- x/stake/types/errors.go
- x/stake/types/validator.go
* Introduce new `Err{NoDelegation,Bad{Redelegation,UnbondingDelegation,Validator}Addr}` functions in stake's types.
* `stake/types.Unmarshal{Validator,UBD,RED}()`:
- Return consistent errors on address validation failures.
* `stake/types.UnmarshalValidator()`:
- Perform address validation first to avoid attempting unmarshalling at all if the latter fails.
* Replace `MustUnmarshalDelegation()` with `UnmarshalDelegation()` calls and handle errors gracefully rather than panicking to fix #1831 and #1907.
> Handle unmarshalling failures gracefully in x/stake commands

- Gopkg.lock
- cmd/gaia/app/sim_test.go
- x/mock/app.go
- x/mock/simulation/random_simulate_blocks.go
**REBASE ONTO DEVELOP ONCE SLASHING-SIMULATION IS MERGED**
(Lets please merge that first, with CI disabled.)
No pending entry required, randomized testing is new to this release
For Admin Use:
> Make randomized simulation deterministic from a given seed

- PENDING.md
- client/lcd/lcd_test.go
- cmd/gaia/app/genesis.go
- cmd/gaia/cli_test/cli_test.go
- docs/sdk/clients.md
- docs/spec/staking/transactions.md
- docs/validators/validator-setup.md
- examples/democoin/mock/validator.go
- types/stake.go
- x/gov/tally.go
- x/slashing/app_test.go
- x/slashing/client/cli/flags.go
- x/stake/app_test.go
- x/stake/client/cli/flags.go
- x/stake/client/rest/query.go
- x/stake/handler_test.go
- x/stake/keeper/_store.md
- x/stake/keeper/delegation.go
- x/stake/keeper/slash.go
- x/stake/keeper/validator.go
- x/stake/keeper/validator_test.go
- x/stake/types/validator.go
- x/stake/types/validator_test.go
- [**cli**] Flag `--address-validator` renamed to `--validator`
- [**types**] `Validator` interface's `GetOwner()` renamed to `GetOperator()`
- [**x/stake**] `Validator.Owner` renamed to `Validator.Operator`
Relevant issue: #1901
> Rename stake Validator.Owner -> .Operator

- cmd/gaia/app/sim_test.go
- x/bank/simulation/sim_test.go
- x/gov/simulation/sim_test.go
- x/mock/simulation/random_simulate_blocks.go
- x/stake/simulation/sim_test.go
> Fix non-deterministic map iteration in fuzzer

- CHANGELOG.md
- PENDING.md
- x/stake/keeper/validator.go
- x/stake/keeper/validator_test.go
* Fix invalid power comparison
* Add to unit tests to check this invariant
* Add defensive panic
closes: #2070
----
For Admin Use:
> R4R: Fix Invalid Cliff Validator Power Comparison

- CHANGELOG.md
- PENDING.md
- x/stake/keeper/validator.go
- x/stake/keeper/validator_test.go
* Fix broken invariant when previously bonded validator decreases in power below cliff validator
closes: #2071 
----
For Admin Use:
> R4R: Fix broken invariant of bonded validator power decrease

- docs/light/api.md
Closes #1305, #1762 
This PR is only docs for #1979
For Admin Use:
> R4R: Rename LCD endpoints (Docs)

- PENDING.md
- client/rpc/block.go
> R4R: Remove --select in block command

- PENDING.md
- docs/sdk/sdk-by-examples/simple-governance/submit-proposal.md
- x/gov/client/cli/tx.go
- x/gov/client/cli/tx_test.go
Closes #1852.
Closes #1776.
For Admin Use:
> R4R: Support a proposal JSON file in submit-proposal

- Gopkg.lock
- PENDING.md
- client/flags.go
- client/keys/show.go
- client/keys/utils.go
- client/tx/search.go
- server/tm_cmds.go
This PR closes #1970, #1971, #1967, and #1969.
> R4R: CLI UX Updates #1

- docs/spec/auth/vesting.md
> Vesting Spec

- PENDING.md
- types/errors.go
- types/errors_test.go
Closes #2044 and cosmos/voyager#1131
New error formatting:
- `err.Error()`:
```
ERROR:
Codespace: 1
Code: 9
Message: "unknown address"
ERROR:
Codespace: 1
Code: 10
Message: "insufficient coins"
```
- `err.ABCILog()`:
```
{"codespace":1,"code":9,"abci_code":65545,"message":"unknown address"}
{"codespace":1,"code":10,"abci_code":65546,"message":"insufficient coins"}
```
---
______
For Admin Use:
> R4R: Parsed Err msgs

- .circleci/config.yml
- Makefile
- PENDING.md
- examples/basecoin/cli_test/cli_test.go
- examples/democoin/cli_test/cli_test.go
Test `basecoind init && basecoind start` sequence for both basecoin and democoin.
Closes: #1632
______
For Admin Use:
> Simple integration tests for {base,demo}coind

- CHANGELOG.md
- Gopkg.lock
- Gopkg.toml
- version/version.go
- fixes unbounded WAL growth
Ref: https://github.com/tendermint/tendermint/issues/2259
Tendermint PR: https://github.com/tendermint/tendermint/pull/2261
______
For Admin Use:
> update to tm v0.23.1

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
> Update PR template for release process

- docs/spec/other/bech32.md
The existing bech32 human readable prefix is too long esp for user accounts.  This shortens them.
For employee accounts, we need to ensure that we convert correctly by first decoding using the old prefix, then encoding again with the new prefix, as it changes the last few base32 checksum characters.
> Update bech32 human readable spec

- PENDING.md
- cmd/gaia/app/sim_test.go
- x/bank/simulation/msgs.go
- x/bank/simulation/sim_test.go
- x/gov/simulation/msgs.go
- x/gov/simulation/sim_test.go
- x/mock/simulation/random_simulate_blocks.go
- x/mock/simulation/types.go
- x/slashing/simulation/msgs.go
- x/stake/simulation/msgs.go
- x/stake/simulation/sim_test.go
> simulation: rename TestAndRunTx to Operation, make timestamp randomized

- cmd/gaia/app/genesis.go
- x/stake/keeper/delegation.go
- x/stake/keeper/delegation_test.go
- x/stake/keeper/slash_test.go
- x/stake/keeper/validator_test.go
- x/stake/types/validator.go
- x/stake/types/validator_test.go
Now when we delegate out token, we have to conver token amount from sdk.Int to int64.
```
validator, pool, newShares = validator.AddTokensFromDel(pool, bondAmt.Amount.Int64())
```
```
// AddTokensFromDel adds tokens to a validator
func (v Validator) AddTokensFromDel(pool Pool, amount int64) (Validator, Pool, sdk.Dec) {
```
However, I think this is not reasonable. Because this may take a risk of overflow. Besides, using int64 as amount in AddTokensFromDel is weird, we just do a weird data type covertion:
```
sdk.Int -> int64 -> sdk.Dec
```
```
type Int struct {
i *big.Int
}
```
```
type Dec struct {
*big.Int `json:"int"`
}
```
Both sdk.Int and sdk.Dec are big int. Why we need to truncate amount from sdk.Int to int64 and extend to sdk.Dec again?
> Change delegation amount from int64 to sdk.Int

- Gopkg.lock
- PENDING.md
- store/iavlstore.go
- store/iavlstore_test.go
Note each defer occurs a 30ish ns overhead here, which is significant
for IAVL iteration. We were previously using around 3-4 defers. (2 in
next, one in Valid, one in Key, one in Value) This slows down the entire
application quite significantly, as we require fast iteration.
This benchmark is just for the next operation, we will see 50% of this performance gain in the Valid and Value functions as well, so the performance gain in practice may be 2x this. 
Before:
```
BenchmarkIAVLIteratorNext-8   	 3000000	       534 ns/op	       0 B/op	       0 allocs/op
```
After:
```
BenchmarkIAVLIteratorNext-8   	 3000000	       466 ns/op	       0 B/op	       0 allocs/op
```
This means this change could give us around 140 ns of improvement per iteration -- quite significant.
- Targeted PR against …
> Speedup IAVL iterator by removing defers when unneeded.

- PENDING.md
- baseapp/baseapp.go
- baseapp/baseapp_test.go
- client/context/context.go
- client/context/query.go
- client/flags.go
- client/lcd/lcd_test.go
- client/lcd/version.go
- client/utils/rest.go
- client/utils/utils.go
- client/utils/utils_test.go
- cmd/gaia/cli_test/cli_test.go
- docs/sdk/clients.md
- docs/sdk/core/app1.md
- docs/sdk/core/examples/app2.go
- types/handler.go
- x/auth/ante.go
- x/auth/ante_test.go
- x/auth/client/context/context.go
- x/auth/client/rest/query.go
- x/bank/client/rest/sendtx.go
- x/gov/client/rest/rest.go
- x/gov/client/rest/util.go
- x/ibc/client/rest/transfer.go
- x/params/msg_status.go
- x/slashing/client/rest/tx.go
- x/stake/client/rest/tx.go
Relevant issue: #1246
* Change `--gas=0` semantic in order to enable gas auto estimate.
* REST clients have been modified to simulate the execution of the tx first to then populate the context with the estimated gas amount returned by the simulation.
* The simulation returns both an unadjusted gas estimate and an adjusted one. The adjustment is required to ensure that the ensuing execution doesn't fail due to state changes that might have occurred. Gas adjustment can be controlled via the CLI's `--gas-adjustment` flag.
Closes: #1246
For Admin Use:
> Simulate transactions by default to set gas automatically

- x/gov/client/cli/tx.go
- x/gov/client/rest/rest.go
closes #2125
______
For Admin Use:
> R4R: Governance CLI uses Querier

- PENDING.md
- cmd/gaia/app/sim_test.go
- x/bank/simulation/msgs.go
- x/bank/simulation/sim_test.go
- x/gov/simulation/msgs.go
- x/mock/simulation/random_simulate_blocks.go
- x/mock/simulation/types.go
- x/slashing/simulation/msgs.go
- x/stake/simulation/msgs.go
Addresses one of the points in #1924 
The intent of this is to allow for simulating things like slashing for not
voting on a governance proposal. To test this, you would queue all the validator votes
in future blocks, and keep track of which ones you didn't slash. Then you could add queue a
"check governance slashing operation" after the voting period is over.
I'm saving writing a test for "Check governance slashing operation" for a separate PR. 
______
For Admin Use: …
> simulation: Allow operations to specify future operations

- PENDING.md
- crypto/ledger.go
- crypto/ledger_secp256k1.go
closes: #2064 
----
______
For Admin Use:
> R4R: Load Ledger Device at Runtime

- .circleci/config.yml
- Makefile
- PENDING.md
We want CI to be running the lock in the repo, not generating a new one.
Linting ensures that the lock file is up to date, so thats not a concern here.
I hope that this will prevent the upload_coverage error in https://circleci.com/gh/cosmos/cosmos-sdk/24023 from happening again.
I believe we discussed doing this previously @cwgoes. 
______
For Admin Use:
> CI: Make CI not update the lock file

- x/slashing/client/cli/tx.go
- x/stake/client/cli/query.go
I observed that while there weren't any non-usages of cobra.ExactArgs that I could find, there were a few places that were using `cobra.ExactArgs(0)` rather than `cobra.NoArgs` so I fixed them.
Closes #885.
______
For Admin Use:
> Use cobra.NoArgs where appropriate

- CHANGELOG.md
- PENDING.md
- docs/getting-started/create-testnet.md
- networks/remote/ansible/roles/setup-validators/tasks/main.yml
- server/init.go
> Rename --gen-txs to --with-txs

- PENDING.md
- server/tm_cmds.go
- server/util.go
Closes #1274.
______
For Admin Use:
> Add show-address command

- PENDING.md
- examples/democoin/mock/validator.go
- types/stake.go
- x/slashing/errors.go
- x/slashing/handler.go
- x/slashing/handler_test.go
- x/slashing/test_common.go
- x/stake/handler.go
- x/stake/handler_test.go
- x/stake/keeper/delegation.go
* Add `Delegation` to `ValidatorSet` type. The motivation was to be able to determine
if a validator has a self-delegation in the unjail message handler.
* Note, the keeper implementing the `ValidatorSet` interface already has `Delegation` defined.
* Update `handleMsgUnjail` to not allow a validator to unjail itself if it has no
self-bonded delegation (it may have other delegated power).
* Update `handleMsgDelegate` to allow a validator to self-bond when jailed.
* Added unit tests to ensure the following:
When a validator removes it's final self-bonded share:
* the validator is jailed (existing behavior)
* delegators cannot delegate to said validator
* the validator CAN self-delegate to itself
* validator cannot unjail themselves UNLESS they have self self-bonded
* after self-bonding and …
> R4R: Ensure Legacy Validator Delegation Invariants

- docs/RELEASE_PROCESS.md
- Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/cosmos-sdk/blob/develop/CONTRIBUTING.md#pr-targeting)) - Targeted master, cherry-picked change from develop.
______
For Admin Use:
> Hotfix: double curlies breaks vuepress - single curlies does not

- PENDING.md
- client/context/context.go
- client/flags.go
- client/lcd/lcd_test.go
- client/utils/rest.go
- client/utils/utils.go
- cmd/gaia/cli_test/cli_test.go
- docs/sdk/clients.md
- examples/democoin/x/cool/app_test.go
- examples/democoin/x/pow/app_test.go
- x/auth/ante.go
- x/auth/ante_test.go
- x/auth/client/context/context.go
- x/auth/client/rest/query.go
- x/bank/app_test.go
- x/bank/client/rest/sendtx.go
- x/gov/client/rest/rest.go
- x/gov/client/rest/util.go
- x/ibc/app_test.go
- x/ibc/client/rest/transfer.go
- x/mock/app_test.go
- x/mock/test_utils.go
- x/slashing/app_test.go
- x/slashing/client/rest/tx.go
- x/stake/app_test.go
- x/stake/client/rest/tx.go
Add an extra simulate flag support to both CLI tx commands and RESTful endpoints to trigger the simulation of an unsigned transaction. Relevant changes:
* Turning `--dry-run` causes the `--gas` flag to be ignored. The simulation will return the estimate of the gas required to actually run the transaction.
* Adjustment is no longer required. It now defaults to `1.0`.
* In some test cases accounts retrieved from the state do not come with a `PubKey`. In such cases, a fake `secp256k1` key is generated and gas consumption calculated accordingly.
Closes: #2110
______
For Admin Use: …
> R4R: Implement a simulate-only CLI flag/field for REST endpoints

- x/stake/keeper/slash.go
It used to print the decimal number, which has an extra factor of 10**10,
and is thus confusing.
Before:
```
I[09-01|20:48:46.742] Validator 0C42E48313EF7B6E45985050F608000190EDEF5F slashed by slashFactor 100000000, burned 6500000000 tokens module=x/stake 
```
After:
```
I[09-01|20:53:29.445] Validator 67C75D900A905BC804600A1AE16CA29470510BCD slashed by slashFactor .0500000000, burned 48000000000 tokens module=x/stake 
```
A changelog entry feels unnecessary here, as decimals are new to this release.
______
For Admin Use:
> Make the slashing logger print a string representation of slashFactor

- PENDING.md
- x/stake/keeper/validator.go
In simulation, this was shown to cause a 4x speedup for the entire system (with IAVL commits + GoLevelDB). There are no safety concerns here, as amino encoding is deterministic. This 4x speedup scales to even bigger block / operation sizes.
I think it is very reasonable to have a cache just for these get validator calls. Its like an L1 CPU cache, we have caching for something that is getting used often and we know is a bottleneck.
______
For Admin Use: …
> Improve GetValidator speed

- Makefile
- PENDING.md
- cmd/gaia/app/sim_test.go
The reason these are grouped together is that its important to be able to turn off the db for simulations easily. 
REBASE ONTO DEVELOP ONCE #2187 is merged
______
For Admin Use:
> simulation: display db size at end of simulation, add makefile entries

- PENDING.md
- baseapp/setters.go
Closes #1441
______
For Admin Use:
> baseapp: Remove baseapp.SetTxDecoder()

- PENDING.md
- tools/Makefile
- tools/gometalinter.json
We can investigate re-introducing our own fork #postlaunch.
Closes #2211
I chose to leave this commented in the makefile, as a reminder that were considering re-including postlaunch. If we ever decide to remove it permanently, lets delete it then. (Though I guess it is easy enough to add back, I don't feel a need to bikeshed this so if anyones opposed, I'll delete it now)
______
For Admin Use:
> tools: Remove gocyclo

- Makefile
- cmd/gaia/app/sim_test.go
- x/mock/simulation/random_simulate_blocks.go
Now that we properly initialize governance, a ton of governance slashing
doesn't happen in the first few blocks. Because of this, we can run through
blocks in the range (0,200) quite rapidly. This PR acknowledges that and
increases many of the default block heights.
______
For Admin Use:
> simulation: Minor changes

- PENDING.md
- client/context/context.go
- client/flags.go
- client/lcd/lcd_test.go
- client/utils/rest.go
- client/utils/utils.go
- cmd/gaia/cli_test/cli_test.go
- crypto/keys/keybase.go
- docs/sdk/clients.md
- x/auth/stdtx.go
- x/bank/client/cli/sendtx.go
- x/bank/client/rest/sendtx.go
- x/gov/client/cli/tx.go
- x/gov/client/rest/util.go
- x/gov/msgs.go
- x/ibc/client/cli/ibctx.go
- x/ibc/client/rest/transfer.go
- x/ibc/types.go
- x/slashing/client/cli/tx.go
- x/slashing/client/rest/tx.go
- x/stake/client/cli/tx.go
- x/stake/client/rest/tx.go
The new CLI `--generate-only` flag builds an unsigned transaction and writes it to STDOUT. Likewise, REST clients can now append `generate_only=true` to a request's query arguments list and expect a JSON response carrying the unsigned transaction.
Closes: #966
______
For Admin Use:
> R4R: Implement generate-only option for commands that create txs

- crypto/keys/keybase.go
> checked error on Fprintf

- docs/RELEASE_PROCESS.md
> R4R: Suggest opening pending PR back to develop

- Makefile
- PENDING.md
- client/input.go
- client/lcd/lcd_test.go
- client/utils/utils.go
- cmd/gaia/cli_test/cli_test.go
- cmd/gaia/cmd/gaiacli/main.go
- docs/light/api.md
- docs/sdk/clients.md
- x/auth/client/cli/sign.go
- x/auth/client/context/context.go
- x/auth/client/rest/query.go
- x/auth/client/rest/sign.go
Add `sign` command to sign transactions generated with the `--generate-only` flag.
Closes: #1953 
______
For Admin Use:
> R4R: Implement command/REST endpoint for offline signing #1953

- cmd/gaia/app/sim_test.go
- x/gov/simulation/msgs.go
- x/gov/simulation/sim_test.go
In a future PR, functionality to test that slashing occured properly should be added.
#2225 still occurs at block heights greater 210. I think thats independent of this though, and that this functionality is good to merge.
______
For Admin Use:
> simulation: Make governance simulation use future operations to schedule votes

- cmd/gaia/app/app.go
- cmd/gaia/app/sim_test.go
- cmd/gaia/cmd/gaiadebug/hack.go
- docs/sdk/core/app3.md
- docs/sdk/core/examples/app3.go
- docs/sdk/core/examples/app4.go
- docs/sdk/sdk-by-examples/simple-governance/app-constructor.md
- docs/sdk/sdk-by-examples/simple-governance/app-structure.md
- examples/basecoin/app/app.go
- examples/democoin/app/app.go
- examples/democoin/x/cool/app_test.go
- examples/democoin/x/pow/app_test.go
- examples/democoin/x/simplestake/keeper.go
- examples/democoin/x/simplestake/keeper_test.go
- x/bank/bench_test.go
- x/bank/keeper_test.go
- x/bank/simulation/sim_test.go
- x/distribution/keeper.go
- x/gov/simulation/msgs.go
- x/gov/simulation/sim_test.go
- x/ibc/app_test.go
- x/slashing/app_test.go
- x/stake/app_test.go
- x/stake/keeper/delegation.go
- x/stake/keeper/keeper.go
- x/stake/simulation/sim_test.go
Closes #2267
______
For Admin Use:
> Rename coinKeeper -> bankKeeper

- PENDING.md
- client/context/query.go
- cmd/gaia/cli_test/cli_test.go
When running with --json, commands should produce
correctly JSON-encoded output.
Closes: #2265
______
For Admin Use:
> R4R: Fix CLI commands JSON output

- x/auth/ante.go
Currently we generate a new private key for every tx simulation run. Not only is this unnecessary from a speed point of view, it is accessing the cryptographic RNG which doesn't really feel right. We had plans for making a minimum amount of entropy for privkey generation, so this could even cause delays in this operation once thats implemented. 
This just replaces that pubkey derivation with a static "dummy" pubkey. I don't see any safety concerns with this.
______
For Admin Use: …
> make tx simulation no longer generate new privkeys

- PENDING.md
- client/lcd/lcd_test.go
- cmd/gaia/cli_test/cli_test.go
- cmd/gaia/cmd/gaiacli/main.go
- docs/light/api.md
- docs/sdk/clients.md
- x/auth/client/rest/query.go
- x/bank/client/cli/broadcast.go
- x/bank/client/rest/broadcast.go
- x/bank/client/rest/sendtx.go
Implement `broadcast` command/REST endpoint to submit transactions generated offline with `--generated-only` and the `sign` command.
Closes: #1954 
______
For Admin Use:
> R4R: New broadcast command

- store/transientstore.go
Currently transient store doesn't implement store type interface. As a result, when calculating commitStores, the transient store will also be included, which is unexpected.
```
func commitStores(version int64, storeMap map[StoreKey]CommitStore) commitInfo {
storeInfos := make([]storeInfo, 0, len(storeMap))
for key, store := range storeMap {
// Commit
commitID := store.Commit()
if store.GetStoreType() == sdk.StoreTypeTransient {
continue
}
// Record CommitID
si := storeInfo{}
si.Name = key.Name()
si.Core.CommitID = commitID
// si.Core.StoreType = store.GetStoreType()
storeInfos = append(storeInfos, si)
}
ci := commitInfo{
Version:    version,
StoreInfos: storeInfos,
}
return ci
}
```
Now, we have two params store. One is IAVL store and another one is transient. 
```
keyParams: …
```
> transient store missed to implement store type interface

- x/stake/keeper/validator.go
I think standardizing this is good, and makes it easier to glance through the code.
______
For Admin Use:
> R4R: x/staking: standardize validator record not found error

- x/stake/keeper/validator.go
This improved the code clarity for me significantly. (Lets you abstract more implementation details as you try to understand the logic)
______
For Admin Use:
> R4R: x/staking: Use variable names in switch case

- PENDING.md
- cmd/gaia/app/sim_test.go
- store/transientstore.go
- x/mock/simulation/random_simulate_blocks.go
- x/mock/simulation/util.go
If the logs are large, it gets written to a file. Additionally, this PR also does a slight refactor so that simulation returns an error. This means when we do SIGTERM/ SIGINT the database cleanup code still gets ran. 
______
For Admin Use:
> simulation: Write logs on panic

- PENDING.md
- client/context/context.go
- client/flags.go
- client/lcd/lcd_test.go
- client/utils/utils.go
- cmd/gaia/cli_test/cli_test.go
- docs/light/api.md
- docs/sdk/clients.md
- x/auth/client/txbuilder/txbuilder.go
- x/bank/client/rest/sendtx.go
- x/gov/client/rest/util.go
- x/ibc/client/rest/transfer.go
- x/slashing/client/rest/tx.go
- x/stake/client/rest/tx.go
Make --gas flag accept a conventional "simulate" string value in addition
to integers. Passing --gas=simulate would trigger the tx simulation and
set the gas according to the gas estimate returned by the simulation.
Any other integer value passed to --gas would be interpreted as-is and
and set as gas wanted value.
Closes: #2300
______
For Admin Use:
> R4R: Change --gas=0 semantic and introduce --gas=simulate

- Gopkg.lock
- PENDING.md
- examples/README.md
- store/multistoreproof.go
- store/multistoreproof_test.go
- store/rootmultistore.go
We already made this decision awhile ago, and have had tendermint switched
for awhile. I was surprised to find ripemd still used within the storeinfo.
This actually leads me to think the new "byter" API change in the tendermint
PR, for RFC compliance is better, as it avoids things like this from ever happening.
______
For Admin Use:
> Remove ripemd160 entirely

- Makefile
- PENDING.md
- cmd/gaia/app/sim_test.go
- x/bank/simulation/sim_test.go
- x/gov/simulation/sim_test.go
- x/mock/simulation/random_simulate_blocks.go
- x/mock/simulation/types.go
- x/stake/simulation/sim_test.go
The intent of this is to reduce the amount of proposals submitted, to speed up the simulation a bit. At the moment there are too many calls, so its overly computationally intensive. (Especially as each proposals schedules ~50 votes)
This also reduces the number of msg edit validators, since I don't think thats a useful thing for the fuzzer to be spending cycles on.
______
For Admin Use:
> simulation: Add weighted operation

- docs/architecture/README.md
- docs/architecture/adr-template.md
I believe we've been discussing adding these templates for awhile. I think its more amenable for longer proposals than github issues (as it allows threads of conversation), and was also desired in #1192
______
For Admin Use:
> Copy ADR template from Tendermint

- cmd/gaia/app/genesis.go
- cmd/gaia/app/genesis_test.go
- cmd/gaia/cmd/gaiadebug/hack.go
- cmd/gaia/testnets/STATUS.md
- docs/resources/whitepaper.md
- docs/spec/staking/transactions.md
closes #2279. The only remaining usage of revoked not updated is the usage in the faq, but that is because "jailed" didn't grammatically make sense in those sentences, whereas revoked did still make sense.
______
For Admin Use:
> Update revoked -> jailed in the docs, and in minor places within cmd.

- client/rpc/block.go
- client/rpc/validators.go
- client/tx/search.go
- x/stake/client/rest/utils.go
* When we query validatorset, we may not provide height. The the height pointer may be null. So here I replaced `*height` with `validatorsRes.BlockHeight`
* The same problems also exist in getBlock. I replaced `*height` with `res.Block.Height`.
* FormatTxResults has a useless parameters which was added by me. I correct it here.
> R4R: bugfix in validatorset query and refactor transaction search

- PENDING.md
- baseapp/baseapp_test.go
- docs/sdk/core/examples/app1.go
- docs/sdk/core/examples/app2.go
- examples/democoin/x/cool/types.go
- examples/democoin/x/oracle/oracle_test.go
- examples/democoin/x/oracle/types.go
- examples/democoin/x/pow/types.go
- examples/democoin/x/simplestake/msgs.go
- examples/kvstore/tx.go
- server/mock/tx.go
- types/tx_msg.go
- x/bank/msgs.go
- x/gov/msgs.go
- x/ibc/types.go
- x/mock/app_test.go
- x/slashing/msg.go
- x/stake/types/msg.go
This is to facillitate ease of implementing #1406. (Tags for messages
could then be added dynamically)
Ultimately once we make the router support hiearchical routing, (#770)
we can then remove the name field and just the parse info for tags from that.
Until then, we can parse the tag name as
`fmt.Sprintf("%s %s", msg.Type(), msg.Name())`
______
For Admin Use:
> R4R: Add a name field to the message type

- x/gov/simulation/msgs.go
This PR basically makes the simulator not schedule a ton of votes for proposals that fail (due to the validator not having enough money left).
On `make test_sim_gaia_fast`
Before: 
```
gov/MsgVote/false => 23335
```
after
```
gov/MsgVote/false => 15110
```
Fixing the remaining failing votes seems a bit more complicated, as we have to ensure the proposal has enough money before those votes. We could perhaps schedule deposits as well, but I'll save that for a future PR.
No changelog entry needed.
______
For Admin Use:
- Squashed all commits, uses message "Merge pull …
> R4R: simulation: reduce number of failed governance msgs

- store/cachekvstore_test.go
- x/auth/mapper_test.go
These method were surprisingly slow from the profiling.
(Mapper.Get accounted for 2.7% of time taken, GetKey also took an
interestingly large portion of time)
These benchmarks may not be intrinsically that useful, so feel free
to close the PR. Figured since I wrote them, may as well PR it.
______
For Admin Use:
> Added a couple of benchmarks

- .circleci/config.yml
- Makefile
- PENDING.md
- client/lcd/lcd_test.go
- tests/test_cover.sh
- version/command.go
- version/version.go
Simplify version handling, rely on git describe
Closes: #1941
______
For Admin Use:
> R4R: Simplify version handling, rely on git describe

- client/context/context.go
- client/rpc/validators.go
If network connection has problems or full node url is not valid, then the certifier creation will fail and return error. Previous error handler is just panic, I think it is not elegant and will confuse users. So here I improved the error handler:
* Print error message
* Imform user how to solve the problems.
Besides, I remove duplicate import:
`tmTypes "github.com/tendermint/tendermint/types"`
> R4R: Improve error handler in certifier creation

- PENDING.md
- client/lcd/certificates.go
- client/lcd/certificates_test.go
- client/lcd/root.go
- docs/light/getting_started.md
In order to guarantee a secure connection between apps and the LCD the communication must be encrypted - even if clients and server run on the same local machine, credentials must never be transmitted in clear text.
Upon start up, if no certificate/key file pair is supplied by the user, the server generates a self-signed certificate and a key; both are stored as temporary files and removal is guaranteed on exit.
This new behaviour is now enabled by default, though users are provided
with a `--insecure` flag to switch it off.
See #595
______
For Admin Use:
- Squashed all commits, uses message "Merge pull request #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/master/README.md …
> R4R: Implement HTTPS for the LCD REST server

- cmd/gaia/app/benchmarks/txsize_test.go
This shows that the size of a send tx from 1 input to 1 output is 173 bytes. (Will decrease by 6 bytes once we update tendermint versions!)
This is good information to have, though we need to find the correct place
to put it. I put this in gaia, because eventually it would probably be useful
to see an example of how to build each message type and their respective
sizes all in one place.
______
For Admin Use:
> Add an example for the size of a transaction

- docs/spec/bank/WIP_keeper.md
- docs/spec/bank/keeper.md
- docs/spec/bank/state.md
> R4R:  Bank Denom Metadata Spec

- PENDING.md
- docs/spec/governance/state.md
- x/gov/endblocker_test.go
- x/gov/handler.go
- x/gov/queryable.go
- x/gov/tally.go
- x/gov/tally_test.go
closes #2256
______
For Admin Use:
> R4R:  removed governance slashing

- client/lcd/lcd_test.go
When `VERSION` is missing (e.g. when you run the test manually or all the LCD tests manually for that matter), the `TestVersion` test will fail. Simply skip it if the env var is not set.
Not sure if this warrants a PENDING log update.
----
______
For Admin Use:
> Skip LCD Test TestVersion When ENV Var is Missing

- PENDING.md
- types/decimal.go
- types/decimal_test.go
- x/stake/keeper/slash.go
This is for usage within the slash function, to minimize operations
required to slash each unbonded and redelegating account.
closes #2407 
______
For Admin Use:
> decimal: Add a method to multiply a decimal by an Int.

- client/context/broadcast.go
- client/context/context.go
- client/lcd/root.go
- examples/democoin/x/cool/client/cli/tx.go
- examples/democoin/x/pow/client/cli/tx.go
- examples/democoin/x/simplestake/client/cli/commands.go
- x/bank/client/cli/broadcast.go
- x/bank/client/cli/sendtx.go
- x/gov/client/cli/tx.go
- x/ibc/client/cli/ibctx.go
- x/slashing/client/cli/tx.go
- x/stake/client/cli/tx.go
This changes .Logger to .Output, as it isn't used anywhere except as os.Stdout.
Merging this without review based on best judgement.
> CLIContext.Logger -> .Output as it isn't a logger

- PENDING.md
- cmd/gaia/app/sim_test.go
- x/bank/simulation/msgs.go
- x/bank/simulation/sim_test.go
Ref #1924
______
For Admin Use:
> simulation: Make bank testing auth configurable

- docs/README.md
> Add quick start section to the docs readme.

- PENDING.md
- client/lcd/lcd_test.go
- client/lcd/test_helpers.go
- Refactored `InitializeTestLCD` to properly include proposing validator in genesis state.
- Don't use consensus pubkey for operator address, but instead generate a unique one.
closes #2416
closes #2034
----
______
For Admin Use:
> R4R: LCD: Properly Init Proposing Validator in Tests

- PENDING.md
- x/stake/keeper/key.go
- x/stake/keeper/key_test.go
Improves memory efficiency of getting store keys
This is done by removing repeated appends, which will create a new
slice if theres insufficient capacity, and instead creating a key
of the correct size, and then copying the data into it.
This PR also Removes empty bytes from ValidatorPowerRank store key
Closes #2433
Please do not squash, and review commit by commit.
______
For Admin Use:
> Staking store keys bug fix + memory improvement

- PENDING.md
- x/auth/mapper.go
- x/auth/mapper_test.go
In Ethermint, when an account (contract) is suicided or is empty, it'll need to be removed from state. Being that StateDB in Ethermint will utilize the account mapper for external accounts and contract accounts, we need this functionality.
If we don't feel safe this this in the SDK, the alternative is to make account mapper an interface that I can implement in Ethermint with the additional method of removal.
----
______
For Admin Use: …
> R4R: Support removal of accounts in account mapper

- PENDING.md
- cmd/gaia/app/genesis.go
- x/stake/genesis.go
- x/stake/genesis_test.go
Closes #890
______
For Admin Use:
> Add ValidateGenesis to staking, add more tests

- PENDING.md
- cmd/gaia/app/sim_test.go
- docs/spec/staking/end_block.md
- docs/spec/staking/transactions.md
- types/context.go
- types/store.go
- x/slashing/handler_test.go
- x/stake/client/cli/tx.go
- x/stake/client/rest/tx.go
- x/stake/handler.go
- x/stake/handler_test.go
- x/stake/keeper/delegation.go
- x/stake/keeper/delegation_test.go
- x/stake/keeper/key.go
- x/stake/keeper/test_common.go
- x/stake/simulation/msgs.go
- x/stake/simulation/sim_test.go
- x/stake/stake.go
- x/stake/tags/tags.go
- x/stake/types/codec.go
- x/stake/types/delegation.go
- x/stake/types/msg.go
- x/stake/types/msg_test.go
closes #2393
______
For Admin Use:
> R4R:  Unbonding and Redelegations Queue

- client/lcd/lcd_test.go
- client/lcd/test_helpers.go
- cmd/gaia/app/genesis.go
- cmd/gaia/app/test_utils.go
- Update genesis app state initialization logic to allow for properly creating more than one validator during LCD tests.
- Updated existing `TestBonding` to create two validators instead of one to provide an example.
Throughout this process, I've realized that the existing genesis logic is a bit convoluted, confusing and would warrant some rewriting. 
closes: #2339
----
______
For Admin Use:
> R4R: Fix LCD Validator Initialization

- client/lcd/swagger-ui/index.html
this file will be over-ridden on the next release. It is required to prevent the website build from failing (after implementing swagger on `develop` & the staging site)
> HOTFIX: add temporary file to sync build with website (RPC)

- PENDING.md
- docs/spec/params/README.md
- docs/spec/params/keeper.md
- docs/spec/params/subspace.md
- store/prefixstore_test.go
- x/params/doc.go
- x/params/keeper_test.go
- x/params/subspace/subspace.go
- x/params/subspace/table.go
- x/params/subspace/table_test.go
Closes: #2490
#2232 was merged so this branch contains some of the addressing to the comments there 
______
For Admin Use:
> R4R: Paramstore Followup

- PENDING.md
- x/stake/handler_test.go
- x/stake/keeper/delegation.go
- x/stake/types/errors.go
Quick fix to #1402 for GoS, but we should eventually add an index instead.
Simply prevents redelegation by delegator `D` from validator `A` to validator `B` if any existing redelegation by `D` from `A` to `B` already exists. Includes a testcase.
______
For Admin Use:
> R4R: Block conflicting redelegations

- PENDING.md
- x/stake/keeper/key.go
- x/stake/keeper/key_test.go
Ref #2439, although it doesn't address all of that issue (only fixing the current key, not changing the Tendermint power calculation).
______
For Admin Use:
> R4R: Fix validator power key

- types/utils.go
- types/utils_test.go
- x/stake/keeper/key.go
Adds test for the format & parse of time in sdk utils.  Also removes duplicate code from stake module. 
Continuation of #2516
______
For Admin Use:
> R4R:  SDK Sortable Time Format Test

- client/utils/rest.go
It was introduced in #2215, it's presently unnecessary and
it is clearly breaking cross compilation.
______
For Admin Use:
> Remove 'import "C"' from client/utils package

- PENDING.md
- docs/spec/staking/end_block.md
- docs/spec/staking/transactions.md
- x/stake/keeper/delegation.go
- x/stake/keeper/delegation_test.go
- x/stake/keeper/slash.go
- x/stake/keeper/validator.go
closes #1673
______
For Admin Use:
> R4R:  Refactor validator deletion

- PENDING.md
- x/bank/client/cli/sendtx.go
Closes: #2547
______
For Admin Use:
> R4R: Mark --to and --amount flags required for gaiacli tx send

- PENDING.md
- client/lcd/lcd_test.go
- x/stake/client/rest/query.go
- x/stake/client/rest/utils.go
- x/stake/querier/queryable.go
- x/stake/querier/queryable_test.go
Closes #2477 
___
______
For Admin Use:
> R4R: validator outgoing redelegations and unbonding delegations

- PENDING.md
- cmd/gaia/cli_test/cli_test.go
- cmd/gaia/cmd/gaiacli/main.go
Closes #2567 
___
______
For Admin Use:
> R4R: Cmds for query deposits

- Gopkg.lock
- PENDING.md
- client/keys/add.go
- client/keys/delete.go
- client/keys/update.go
- client/keys/utils.go
- client/keys/utils_test.go
- client/lcd/test_helpers.go
- crypto/keys/keybase.go
- crypto/keys/types.go
- server/init.go
Expose calls to acquire non-blocking read lock on LevelDB stores.
Change `GetKeyBase()` so that it opens stores in read-only mode by default.
Add `GetKeyBaseWithWritePerm()` to acquire write locks on stores.
Closes: #1255
______
For Admin Use:
> R4R: Don't acquire lock on read-only keybase

- Gopkg.lock
- PENDING.md
- client/keys/add.go
- client/keys/delete.go
- client/keys/update.go
- client/keys/utils.go
- client/lcd/test_helpers.go
- server/init.go
This is a PR for #1255 
make keybase opened with readonly option for query-purpose to support better parallelization between gaiacli
This change enabled parallelization between read and write of keys db via gaiacli, so most of operations can be parallelized except multiple add/update keys to keys db at the same time (but sending transactions and serve rest-server can be parallelized!) **in trust mode**
There are more work to do to supprt non-trust mode, which have to made change to tendermint code. The remainning work mostly reside on make open and close dbprovider in verifier fine grained. 
```
func NewVerifier(chainID, rootDir string, client lclient.SignStatusClient, logger log.Logger) (*lite.DynamicVerifier, error) {
logger = logger.With("module", "lite/proxy") …
```
> [R4R] #1255 make keybase opened with readonly option for query-purpose cli commands 

- client/keys/new.go
- Use `GetKeyBaseWithWritePerm`
- Cleanup user prompt formatting
closes: #2592
---- 
______
For Admin Use:
> R4R: Fix DB Write Permissions for `gaia keys new`

- CHANGELOG.md
- PENDING.md
- client/keys/new.go
- client/keys/show.go
- client/keys/update.go
- client/keys/utils.go
- client/keys/utils_test.go
- crypto/keys/keybase.go
- crypto/keys/mintkey/mintkey.go
- docs/config.js
- x/auth/client/rest/sign.go
- x/distribution/keeper/allocation.go
- x/distribution/keeper/hooks.go
- x/gov/client/cli/tx.go
- x/gov/client/rest/rest.go
- x/gov/client/utils.go
- x/slashing/client/rest/query.go
- x/slashing/client/rest/tx.go
Merge v0.25.0 release branch back to develop.
______
For Admin Use:
> Merge release back to develop

- docs/sdk/clients.md
- docs/validators/validator-setup.md
closes #2530 
______
For Admin Use:
> fix flags in docs

- PENDING.md
- x/stake/keeper/delegation.go
- x/stake/keeper/delegation_test.go
- x/stake/types/errors.go
Closes https://github.com/cosmos/cosmos-sdk/issues/2610
______
For Admin Use:
> R4R: Block redelegations to the same validator

- Makefile
- cmd/gaia/app/sim_test.go
Due to requiring app.Commit() at the moment, golevel db is significantly faster than a memdb. This allows simulating 500 blocks in about 1 minute. We should still make the transient store clear on end block, not commit though.
______
For Admin Use:
> Speedup simulator by switching to goleveldb

- CHANGELOG.md
- PENDING.md
- docs/sdk/clients.md
- docs/validators/validator-setup.md
- x/stake/client/cli/flags.go
- x/stake/client/cli/tx.go
Release PR: #2603 
______
For Admin Use:
> Merge 0.25.0 back to develop

- x/mock/simulation/random_simulate_blocks.go
- x/mock/simulation/util.go
There was an off by one error in the log printing function previously
______
For Admin Use:
> simulation: Print last block when there is an error

- docs/PRIORITIES.md
- docs/resources/diagrams/todo.md
> R4R: Add list recommended diagrams 

- PENDING.md
- client/utils/utils.go
- cmd/gaia/cli_test/cli_test.go
- docs/sdk/clients.md
- x/auth/client/cli/sign.go
- Exit with error if the user is attempting to sign with a key whose address is not among those who are expected to sign the transaction.
- Add --print-signature-only to output only the generated signature.
- When --print-sigs is on, validate signatures order and report errors if there's any.
______
______
For Admin Use:
> R4R: Various sign command improvements

- PENDING.md
- client/lcd/certificates.go
- x/mock/simulation/constants.go
- x/mock/simulation/random_simulate_blocks.go
This enables simulating periods of high load, and periods of low to no load.
(low load because future ops will still terminate in that time frame)
Once this is merged, I think we should just delete #1924, and make a new issue tagged postlaunch for those remaining items. 
The LCD change is from make format. 
______
For Admin Use:
> Make simulation use a transition matrix for block size

- PENDING.md
- cmd/gaia/cmd/gaiacli/main.go
- cmd/gaia/cmd/gaiad/main.go
- cmd/gaia/cmd/gaiadebug/main.go
- examples/democoin/cmd/democli/main.go
- examples/democoin/cmd/democoind/main.go
- types/address.go
- types/address_test.go
- types/config.go
This request fixes - https://github.com/cosmos/cosmos-sdk/issues/1336
______
For Admin Use:
> R4R: Configurable Bech32 prefix for SDK users

- docs/spec/auth/vesting.md
Update the vesting spec per discussion in #2168.
I recommend viewing the spec in it's markdown format opposed to the diff.
----
______
For Admin Use:
> R4R: Update Vesting Spec

- client/keys/utils.go
Waiting on a fix for syndtr/goleveldb#240.
closes: #2630
______
For Admin Use:
> R4R: Revert read-only leveldb database

- Makefile
- PENDING.md
- x/mock/simulation/util.go
- x/stake/keeper/test_common.go
- x/stake/simulation/msgs.go
This also had to change the default seed, since with the previous one it
actually got into a state where there were no validators left bonded, lol.
This also changes Unbond msgs from failing with almost 100% probability to now
only failing with 33% probability.
Thus more of the state machine is getting tested!
This does slow it down a fair amount (went from 500 blocks in ~55 seconds, to now 500 blocks in 100 seconds) but I think this is a fair trade-off since now its actually testing these, whereas before it wasn't. 
Before:
```
stake/MsgDelegate/false => 650
stake/MsgDelegate/true => 2896
stake/MsgBeginUnbonding/false => 3481
stake/MsgBeginUnbonding/true => 70
```
After:
```
stake/MsgDelegate/false => 291
stake/MsgDelegate/true => 2864
stake/MsgBeginUnbonding/false => 1156 …
```
> [R4R] simulation: Make validator choice use validator set

- PENDING.md
- x/bank/simulation/invariants.go
- x/distribution/simulation/invariants.go
- x/gov/simulation/invariants.go
- x/mock/simulation/random_simulate_blocks.go
- x/mock/simulation/types.go
- x/mock/simulation/util.go
- x/slashing/simulation/invariants.go
- x/stake/simulation/invariants.go
This got introduced recently, but wasn't actually needed, hence the reversion
______
For Admin Use:
> simulation: Remove header from Invariant

- Gopkg.lock
- Gopkg.toml
- client/context/query.go
- store/iavlstore.go
- store/multistoreproof.go
- store/multistoreproof_test.go
- store/rootmultistore.go
This PR is a continuation of #2679. It complete the v0.26 update by finalizing proof and verification updates.
There are issues however:
- A local testnet cannot get past 1 block.
- `TestVerifyMultiStoreQueryProof` passes locally for me but not on CI.
/cc @jaekwon 
---- 
______
For Admin Use:
> [WIP] Update to TM v0.26.0 - Part II

- Gopkg.lock
- Gopkg.toml
- PENDING.md
- client/lcd/lcd_test.go
- client/utils/rest.go
- cmd/gaia/app/sim_test.go
- cmd/gaia/cli_test/cli_test.go
- docs/spec/governance/state.md
- docs/spec/governance/transactions.md
- types/utils.go
- x/gov/client/cli/tx.go
- x/gov/client/rest/rest.go
- x/gov/depositsvotes.go
- x/gov/endblocker_test.go
- x/gov/errors.go
- x/gov/genesis.go
- x/gov/handler.go
- x/gov/keeper.go
- x/gov/keeper_keys.go
- x/gov/keeper_test.go
- x/gov/msgs.go
- x/gov/msgs_test.go
- x/gov/params.go
- x/gov/proposals.go
- x/gov/queryable.go
- x/gov/simulation/msgs.go
- x/gov/simulation/sim_test.go
- x/gov/tally.go
closes #2637 
______
For Admin Use:
> R4R: Switch gov proposal-queues to use iterators

- Gopkg.lock
- Gopkg.toml
- PENDING.md
- cmd/gaia/app/genesis_test.go
- cmd/gaia/init/collect.go
- cmd/gaia/init/init.go
- cmd/gaia/init/testnet.go
- cmd/gaia/init/utils.go
- General cleanup of init structure
- Support creating genesis file with a given canonical time
closes: #2691 
-----
______
For Admin Use:
> [R4R] Update testnet to use canonical genesis time

- PENDING.md
- store/cachekvstore.go
- types/store.go
Haven't written tests, but merging for 0.26.0 before I forget.
Also added an issue for testing: https://github.com/cosmos/cosmos-sdk/issues/2707
> Do not allow nil values to be set in CacheKVStore

- PENDING.md
- x/stake/types/msg.go
closes: #2711 
/cc @HaoyangLiu 
----
______
For Admin Use:
> [R4R]: Add commission data to MsgCreateValidator signature bytes

- CHANGELOG.md
- PENDING.md
- client/lcd/root.go
Temporarily disable insecure mode in Gaia Lite until #2715 has been addressed.
----
______
For Admin Use:
> [R4R]: Temporarily disable gaia lite insecure mode

- PENDING.md
- cmd/gaia/init/testnet.go
> R4R: Add --chain-id to testnet command

- CHANGELOG.md
- cmd/gaia/cmd/gaiad/main.go
- cmd/gaia/init/genesis_accts.go
> R4R: Add small utility to add account to genesis.json after gaiad init

- Gopkg.lock
- Gopkg.toml
This PR is to fix the tendermint related issues we are running into with the current testnet. There are two:
- Prometheus is broken. This PR currently fixes that issue
- Seed nodes don't sync for some reason. Fix is currently being worked on here.
> Gaia-9000: Update to TM 0.26.1-rc2

- PENDING.md
- x/stake/client/cli/tx.go
There used to be `unbond begin` and `unbond complete` complete commands in the staking module. This was changed. This PR just fixes the command.
> R4R: Fix unbonding command flow

- x/bank/keeper.go
The bank keeper was broken up into sub-interfaces (view, send, main). However, we were repeating a bulk of the methods in each. This simply removes duplicate code and DRYs it up.
----
______
For Admin Use:
> [R4R]: Cleanup bank keeper

- Gopkg.lock
- Gopkg.toml
Simple upgrade to actual released version instead of rc (released this morning).
> [R4R] Update to tendermint v0.26.1

- PENDING.md
- x/stake/client/cli/tx.go
This PR fixes the same issue as #2727
> R4R: Fix redelegation command follow up to #2727

- Gopkg.lock
- Gopkg.toml
- PENDING.md
- same as https://github.com/tendermint/tendermint/pull/2822
- the amino update fixes an overflowing int issue that is preventing builds on 32 bit platforms
______
For Admin Use:
> update to amino 0.14.1

- Makefile
Set GOBIN varialble if not set before.
______
For Admin Use:
> R4R: Fix Makefile targets dependencies

- docs/spec/distribution/overview.md
Was re-reading through the spec and found some sentences that were worded...weirdly, so this PR simply includes some minor Markdown fixes and a few bits of rephrasing.
----
______
For Admin Use:
> [R4R] Slight cleanup of distribution specification

- PENDING.md
- cmd/gaia/app/genesis.go
- cmd/gaia/cmd/gaiad/main.go
- cmd/gaia/init/init.go
- cmd/gaia/init/init_test.go
- cmd/gaia/init/testnet.go
- docs/_attic/sdk/sdk-by-examples/simple-governance/bridging-it-all.md
- docs/examples/basecoin/cmd/basecoind/main.go
- docs/examples/democoin/cmd/democoind/main.go
- server/init.go
- server/util.go
Picking #2675 up from where @jaekwon  left it.
Code cleanup, AppInit is no longer required.
______
For Admin Use:
> R4R: Remove AppInit

- README.md
- docs/.vuepress/config.js
- docs/gaia/join-testnet.md
- docs/intro/README.md
Closes https://github.com/cosmos/cosmos-sdk/issues/2818
> R4R: DOCS: fix links and add cli to sidebar

- PENDING.md
- cmd/gaia/init/genesis_accts.go
- cmd/gaia/init/genesis_accts_test.go
> R4R: add-genesis-account: validate app state accounts

- docs/README.md
- docs/gaia/gaiacli.md
> ongoing lil improvements

- PENDING.md
- client/flags.go
- client/keys/utils.go
- client/lcd/root.go
- client/lcd/test_helpers.go
- cmd/gaia/cmd/gaiacli/main.go
- docs/examples/basecoin/cmd/basecli/main.go
- docs/examples/democoin/cmd/democli/main.go
> R4R: Expose LCD router, allowing devs to register custom routes from their modules

- baseapp/baseapp.go
- store/cachemultistore.go
- types/context.go
Before, app.initializeContext was ignoring the ctx's MultiStore and setting a new one from the app, which was making things pretty confusing.
Also, before, context.multiStore() used to be unexposed, but there's no real need to because MultiStore doesn't expose the keys.  So this is now exposed to make the PR here possible and simplify the baseapp logic a bit.
If context.MultiStore() were the CommitMultiStore, there is an least-authority security issue, because the CommitMultiStore exposes more than is safe for ante-handlers and handlers to work with, but with the current BaseApp implementation, this is not an issue as the context.MultiStore() passed in to ante-handler, handler, beginBlocker, and endBlocker are all CacheMultiStores.
Related issue: …
> Make Queriers use checkState context but cache wrapped

- PENDING.md
- baseapp/baseapp_test.go
- types/tx_msg.go
- x/auth/ante.go
- x/auth/stdtx.go
- x/auth/stdtx_test.go
* Add `ValidateBasic` to the `sdk.Tx` interface
* Update `auth.StdTx` to implement said interface
* Update ante handler to call `ValidateBasic`.
* Note, this check could (maybe should?) live in `BaseApp`, but having in the ante handler paved the way of least resistance in terms of changing unit tests.
closes: #2779
----
______
For Admin Use:
> [R4R] Transaction ValidateBasic

- PENDING.md
- client/utils/utils.go
- cmd/gaia/init/gentx.go
- x/auth/client/cli/sign.go
- x/bank/client/cli/sendtx.go
- x/gov/client/cli/tx.go
- x/ibc/client/cli/ibctx.go
- x/slashing/client/cli/tx.go
- x/stake/client/cli/tx.go
- Replace STDIN/STDOUT redirection in `gaiad gentx` with subcommands command line options to redirect streams to file since viper does not handle redirection well.
- Use `BuildCreateValidatorMsg` to build a `MsgCreateValidator` rather than redirecting to `gaiacli tx stake create-validator`.
- `PrintUnsignedStdTx` now takes an `io.Writer` object.
- Mark `--pubkey`, `--amount` and `--moniker` as required flags instead of validating them manually.
______
For Admin Use:
> R4R: gaiad gentx subcommands refactoring

- PENDING.md
- docs/examples/basecoin/cmd/basecli/main.go
- docs/examples/democoin/cmd/democli/main.go
Logic has changed recently and commands are now enriched with flags by default.
Closes: #2884
______
For Admin Use:
> R4R: Don't get command through client.{Get,Post}Commands()

- PENDING.md
- cmd/gaia/cli_test/cli_test.go
- cmd/gaia/init/gentx.go
- x/auth/client/cli/sign.go
Don't call gaiacli tx sign. Use utils.SignStdTx() instead.
This is to avoid command redirection and reduce the use of viper's global variables.
Closes: #2875 
______
For Admin Use:
> R4R: GenTx command refactoring - take #2

- Makefile
- PENDING.md
- scripts/Makefile
Issue: #2766 
Please see old PR #2767 for discussion.
______
For Admin Use:
> R4R: Added goimports tool to get_tools. Fixed get_tools build.

- x/distribution/alias.go
- x/distribution/keeper/allocation.go
- x/distribution/keeper/validator.go
- x/distribution/simulation/invariants.go
- x/distribution/types/dec_coin.go
- x/distribution/types/validator_info.go
Fixes issues seen with seed `99` in `jae/simulator_improvements`
reference https://github.com/cosmos/cosmos-sdk/issues/2906
______
For Admin Use:
> R4R Zero Power Block fees to community pool

- client/lcd/root.go
PR #2900 introduced a change where the Gaia Lite service was started in a goroutine (not sure if intentional?) and thus the parent process exited. The parent process must not exist but rather be controlled by another service/process (e.g. systemd) manager.
Being that this was introduced in a non-release, I don't think we need a PENDING log entry here.
Also, I don't think this addresses #2907 (which I cannot reproduce).
----
______
For Admin Use: …
> R4R: Fix starting Gaia Lite

- PENDING.md
- baseapp/baseapp.go
- client/lcd/lcd_test.go
- cmd/gaia/app/app.go
- cmd/gaia/cli_test/cli_test.go
- cmd/gaia/cmd/gaiadebug/hack.go
- docs/gaia/gaiacli.md
- x/distribution/alias.go
- x/distribution/handler.go
- x/distribution/tags/tags.go
- x/gov/handler.go
- x/gov/tags/tags.go
- x/slashing/app_test.go
- x/slashing/handler.go
- x/slashing/keeper_test.go
- x/stake/app_test.go
- x/stake/client/rest/query.go
- x/stake/handler.go
- x/stake/simulation/sim_test.go
- x/stake/stake.go
- x/stake/tags/tags.go
Closes #2941
The tags of the staking EndBlocker have been ignored by now and action tags were added twice for some transactions.
CC @cwgoes - could we get this in for v0.27.0 since this is a blocker for our block explorer?
______
For Admin Use:
> R4R: Fix tag usage in handlers and EndBlocker

- PENDING.md
- baseapp/baseapp.go
- types/context.go
- x/stake/handler.go
- x/stake/handler_test.go
- x/stake/keeper/test_common.go
- x/stake/stake.go
- x/stake/types/errors.go
Closes #2945 
______
For Admin Use:
> Only allow supported pubKey types

- PENDING.md
- x/distribution/types/msg.go
Closes #2940
______
For Admin Use:
> R4R: Fix duplicate json key in SetWithdrawAddress

- PENDING.md
- client/keys/delete.go
- crypto/keys/keybase.go
- crypto/keys/keybase_test.go
- Add --yes flag to skip confirmation.
- Keybase.Delete() does not check passphrase == "yes" anymore. It's command line tool responsibility to prompt user for confirmation when deleting ledger/offline keys.
Closes: #2921
______
For Admin Use:
> R4R: Prompt user for confirmation when deleting ledger and offline keys

- cmd/gaia/cmd/gaiadebug/main.go
> gaiadebug: fix addr fmt to print bech32 and hex

- PENDING.md
- client/keys/delete.go
- cmd/gaia/cli_test/cli_test.go
- crypto/keys/keybase.go
- crypto/keys/keybase_test.go
- crypto/keys/types.go
Skip passphrase check when --force is on and delete keys unconditionally.
Closes: #2961
______
For Admin Use:
> R4R: add --force to keys delete for unattended execution

- cmd/gaia/cli_test/cli_test.go
Also remove unnecessary tests.WaitForNextNBlocksTM() calls
which slow down tests execution.
______
For Admin Use:
> R4R: Cleanup home dirs when cli testcases exit with success

- PENDING.md
- cmd/gaia/app/benchmarks/txsize_test.go
- x/auth/ante.go
- x/auth/ante_test.go
- x/auth/client/txbuilder/txbuilder.go
- x/auth/stdtx.go
- x/bank/app_test.go
- x/mock/app.go
This was not needed to be included within the tx body, as its in the
state.
Closes #2952 
______
For Admin Use:
> R4R: Don't serialize Account Number and Sequence Number in signatures

- Gopkg.lock
- Gopkg.toml
- PENDING.md
- client/config.go
- cmd/gaia/cli_test/cli_test.go
Closes: #2734
______
For Admin Use:
> R4R: Fix gaiacli config and make it non-interactive only

- PENDING.md
- crypto/keys/keyerror/errors.go
Closes: #2993
______
For Admin Use:
> R4R: change wrong password message

- PENDING.md
- cmd/gaia/app/app.go
- cmd/gaia/app/export.go
- cmd/gaia/app/invariants.go
- docs/spec/mint/begin_block.md
- docs/spec/mint/state.md
- x/distribution/alias.go
- x/distribution/types/dec_coin.go
- x/mint/abci_app.go
- x/mint/minter.go
- x/mint/minter_test.go
Closes https://github.com/cosmos/cosmos-sdk/issues/2967
Changes:
- Tokens are minted for the previous block before distributing rewards
- Inflation rate is now recalculated each block instead of each hour
- For zero-height export, delegation withdrawal infos / validator withdrawal infos are not deleted but instead reset to height 0
Standard checklist:
______
For Admin Use:
> R4R: Inflation bug fixes

- client/lcd/root.go
Currently trying to send transactions through the LCD fails because the `cliCtx` in the LCD doesn't have an `AccountDecoder`. This PR adds the one line fix necessary.
While this doesn't pop up in gaia for some reason (repro case below):
```bash
$ gaiad init --chain-id foo --moniker foo
$ gaiacli keys add jack
$ gaiacli keys add alice
$ gaiad add-genesis-account $(gaiacli keys show jack -a) 1000STAKE,1000jackToken
$ gaiad add-genesis-account $(gaiacli keys show alice -a) 1000STAKE,1000aliceToken
$ gaiad gentx --from jack
$ gaiad collect-gentxs
$ gaiad start
$ gaiacli rest-server --chain-id foo
$ curl -k -s https://localhost:1317/bank/accounts/{{ .Alice.Address }}/transfers --data-binary '{"base_req":{"name":"jack","password":"foobarbaz","chain_id":"foo","account_number":"0","sequence":"1"}, …
```
> R4R: Add Account Decoder to the LCD

- PENDING.md
- client/utils/utils.go
- cmd/gaia/cli_test/cli_test.go
- x/auth/client/cli/sign.go
- x/auth/client/txbuilder/txbuilder.go
Fully verify the signature during `gaiacli tx sign --validate-signatures`
closes: #2991
----
______
For Admin Use:
> R4R: Fully verify the signature in `gaiacli tx sign`

- PENDING.md
- cmd/gaia/app/app_test.go
- cmd/gaia/app/genesis.go
- cmd/gaia/init/gentx.go
- x/distribution/alias.go
- x/distribution/types/fee_pool.go
- x/distribution/types/genesis.go
- x/gov/genesis.go
- x/slashing/genesis.go
Closes #3009 
still some more genesis checks to write missing in the modules, added some empty structs there though and these reference issues: 
REF: #3007, #3008
______
For Admin Use:
> R4R: Add Missing genesis checks in Gaia

- cmd/gaia/app/invariants.go
- cmd/gaia/cmd/gaiareplay/main.go
- types/decimal.go
- x/stake/simulation/invariants.go
- Add back non-negative stake check (cannot be just positive because we keep validators in the unbonding queue)
- Fix linter
cc @jaekwon 
______
For Admin Use:
> Updates to negative stake fix

- cmd/gaia/app/invariants.go
- cmd/gaia/cmd/gaiareplay/main.go
- types/decimal.go
- x/stake/genesis.go
- x/stake/handler_test.go
- x/stake/keeper/delegation_test.go
- x/stake/keeper/key.go
- x/stake/keeper/test_common.go
- x/stake/keeper/val_state_change.go
- x/stake/keeper/validator.go
- x/stake/keeper/validator_test.go
- x/stake/querier/querier_test.go
- x/stake/simulation/invariants.go
- x/stake/types/validator.go
Upon debugging https://github.com/cosmos/cosmos-sdk/issues/3019, I discovered, in order,:
(1) the transactions of the offending block aren't relevant.
(2) stake.EndBlocker is the offender.
(3) UnbondAllMatureValidatorQueue is the offender.
(4) that RemoveValidator was being called.
(5) the pool is being passed around in places where it is unnecessary.
(6) that this validator had 0 shares and *negative* staking tokens.
(7) RemoveTokens is not being re-used, and it lacks sanity checks.
There are 2 bugs here that are addressed here:
* negative staking token can happen because RemoveDelShares isn't clipping properly.
* RemoveValidator is not removing the tokens properly from the pool.
Also, the pool is removed where unnecessary, and RemoveTokens is reused.
I've verified that these changes …
> Fix negative stake & invariance bug

- Makefile
- cmd/gaia/cmd/gaiakeyutil/main.go
- types/decimal.go
- x/distribution/keeper/hooks.go
- x/distribution/keeper/validator.go
- x/distribution/keeper/validator_test.go
- x/distribution/simulation/invariants.go
Fixes regression introduced by https://github.com/cosmos/cosmos-sdk/pull/2984.
Continuiation of https://github.com/cosmos/cosmos-sdk/pull/3033 , which didn't fix the simulation issues.
(candidate) Complete solution for https://github.com/cosmos/cosmos-sdk/issues/3019, 9002 halt bug.
From #2984, it isn't sufficient to take the fee pool rewards of a validator.  Since we don't track delegator accums (as we do with validator accums), and because `onValidatorModified >updateValidatorDistInfoFromPool` is also being called upon delegation updates (or at least I believe this is the reason), it is necessary to also withdraw self delegation.
TODO: I don't think self-delegation should be required to be modified here... consider using a delegation hook to do the self-delegation withdraw part instead, …
> Fix updateValidatorDistInfoFromPool

- PENDING.md
- scripts/multisim.sh
- store/gaskvstore.go
- store/gaskvstore_test.go
- types/gas.go
- x/auth/ante.go
- x/auth/ante_test.go
- x/auth/stdtx_test.go
- x/bank/keeper.go
TODO: Create a new issue to unify gas constants in one place, and improve tests.
Recommended best-guess estimates for gas for GoS:
```
50,000 bytes per block.
1,500,000 gas per block.
50,000 bytes being written x 30 gas/byte-written ~= 1,500,000 gas
750 writes to store x 2000 gas/store-set ~= 1,500,000 gas
```
> R4R: Update gas costs to more reasonable numbers for GoS

- PENDING.md
- cmd/gaia/app/export.go
- scripts/multisim.sh
- x/slashing/keeper_test.go
- x/stake/genesis.go
- x/stake/genesis_test.go
- x/stake/handler.go
- x/stake/keeper/delegation.go
- x/stake/keeper/delegation_test.go
- x/stake/keeper/keeper.go
- x/stake/keeper/key.go
- x/stake/keeper/key_test.go
- x/stake/keeper/slash_test.go
- x/stake/keeper/test_common.go
- x/stake/keeper/validator.go
- x/stake/keeper/validator_test.go
- x/stake/querier/querier_test.go
- x/stake/stake.go
- x/stake/types/genesis.go
- x/stake/types/validator.go
See: https://github.com/cosmos/cosmos-sdk/issues/2909#issuecomment-442112000
Addresses #3049
Related to #3051 (better alternative)
This includes the (inverted) address of the validator in the power key.
This also completely removes the IntraTxCounter, simplifying the code.
Before, some of the tests were testing the bug condition, e.g. the tests were previously broken.  This fixes everything AFAIK.
I'm confident enough about this PR that I believe strongly that we should merge this in for GoS.
> R4R use address instead of bond height / intratxcounter for deduplication

- PENDING.md
- x/auth/stdtx.go
- x/auth/stdtx_test.go
closes #3068
----
______
For Admin Use:
> R4R: Check for gas overflow in tx validation

- PENDING.md
- baseapp/baseapp.go
- types/errors.go
- x/auth/stdtx.go
- x/auth/stdtx_test.go
Closes https://github.com/cosmos/cosmos-sdk/issues/3071
______
For Admin Use:
> R4R: Catch overflows in gas wanted

- .circleci/config.yml
Tiny PR to make the CI test meaningful again - we should manually run longer simulations prior to release.
______
For Admin Use:
> R4R: Run fewer blocks on CI multi-seed simulation

- PENDING.md
- client/flags.go
- cmd/gaia/cli_test/cli_test.go
- cmd/gaia/init/collect.go
- cmd/gaia/init/gentx.go
- cmd/gaia/init/init.go
- cmd/gaia/init/testnet.go
- x/stake/client/cli/flags.go
It was lost in the last genesis workflow refactoring.
Also address structs initializations as per #2835.
______
For Admin Use:
> R4R: Reintroduce collect-gentxs's --gentx-dir flag

- PENDING.md
- client/keys/list.go
Fixes: https://github.com/cosmos/cosmos-sdk/issues/2470
cc @faboweb @fedekunze @sabau
> R4R: Fix Quoted JSON Return 

- docs/clients/lite/getting_started.md
Closes: #3086
______
For Admin Use:
> R4R: Fix gaia lite docs on REST server's SSL flags

- x/stake/keeper/keeper.go
- x/stake/keeper/validator.go
Fixes: https://github.com/cosmos/cosmos-sdk/issues/3074
cc @cwgoes
> R4R: Move validator cache to the keeper in stake

- docs/.vuepress/config.js
- adds [algolia](https://community.algolia.com/docsearch/) for full-txt docs search
- fixes the "Last Updated" feature
- same PR as https://github.com/tendermint/tendermint/pull/3004
- this won't work on staging until https://github.com/algolia/docsearch-configs/pull/672 lands
> full-text search for docs

- docs/intro/README.md
Fix directory listing in SDK intro so that it gets the path to the examples right (docs/examples/ as opposed to examples/).
______
For Admin Use:
> Fix directory listing in intro

- PENDING.md
- client/lcd/lcd_test.go
- client/lcd/swagger-ui/swagger.yaml
- cmd/gaia/app/app.go
- cmd/gaia/cli_test/cli_test.go
- docs/gaia/gaiacli.md
- x/slashing/client/cli/query.go
- x/slashing/client/module_client.go
- x/slashing/client/rest/query.go
- x/slashing/params.go
- x/slashing/querier.go
- x/slashing/querier_test.go
* Implement and mount slashing query (only query params right now)
* Fix JSON tags for params (snakecase -- this "technically" makes it a breaking change)
* Add CLI command to query slashing params
* Add API route to query slashing params
~~TODO: Docs???~~
closes: #2399
----
______
For Admin Use:
> R4R: x/slashing Query Params

- PENDING.md
- client/lcd/lcd_test.go
- client/tx/search.go
- x/gov/client/cli/query.go
- x/gov/client/rest/rest.go
- x/gov/client/rest/utils.go
- x/gov/client/utils/query.go
- x/gov/handler.go
- x/gov/msgs.go
- x/gov/tags/tags.go
* Fix broken proposal ID tags. It was being amino encoded before which did not allow for querying.
* Add `Action` tag to voting and deposit handlers
* Exposed tx searching function (`SearchTxs`)
closes: #2879 
closes: #2880 
/cc @johnmcdowall 
----
______
For Admin Use:
> R4R: x/gov Get Vote(s)/Deposit(s) Updates

- Makefile
- cmd/logjack/main.go
This re-introduces a utility that is deep in the tendermint github history, called logjack.
It uses tendermint/libs/autofile Groups to allow piping stdin into a file that gets auto-rotated.
There surely exist other tools that do the same, but this tool works and requires nothing but existing tendermint dependencies to build, thus is quite portable.  logrotate and cron are a pain to use.
Usage:
./build/gaiad <options> | ./build/logjack -head logs/gaiad.log
> Welcome back, logjack

- cmd/logjack/main.go
Temporary fix for https://github.com/cosmos/cosmos-sdk/pull/3126#issuecomment-448014996, but I think we should consider reverting the original PR in the future.
______
For Admin Use:
> R4R: Fix linter errors

- x/auth/ante.go
- x/auth/ante_test.go
This PR achieves a middle ground @cwgoes and I discussed during an Ethermint discussion where while we wait on #2996 to be finalized and merged (as to not block Ethermint), we expose the necessary auxiliary/helper functions in the ante handler to be used by Ethermint.
This keeps the code DRY and does not block Ethermint.
----
______
For Admin Use:
> R4R: Expose necessary ante handler auxiliary functions

- PENDING.md
- client/config.go
- client/flags.go
- cmd/gaia/cli_test/cli_test.go
- types/utils.go
- x/auth/client/txbuilder/txbuilder.go
- Remove DefaultChainID(). User needs to suplly chain ID via either config or flag.
- Mark --chain-id as required by all tx commands.
- Fix gaiacli config values containing underscores.
Underscore '_' character is not automagically translated into hyphen '-'. Viper values wouldn't be affected.
- Refresh gaiacli config tests
Closes: #810
______
For Admin Use:
> R4R: Don't fallback to any default values for chain id

- PENDING.md
- cmd/gaia/app/genesis.go
- cmd/gaia/app/genesis_test.go
- cmd/gaia/cli_test/cli_test.go
- cmd/gaia/init/testnet.go
- docs/_attic/sdk/core/examples/app2_test.go
- docs/gaia/deploy-testnet.md
- types/coin.go
- types/coin_test.go
- types/context_test.go
- x/auth/ante_test.go
- x/gov/client/cli/tx.go
- x/stake/types/errors.go
- x/stake/types/params.go
Closes: #3064
______
For Admin Use:
> R4R: Make coins denoms case insensitive

- PENDING.md
- x/auth/ante.go
- x/auth/ante_test.go
- Don't read all accounts in one go as signature verification
could fail before last signature is checked.
- TestAnteHandlerFees now checks whether fees were actually
deducted from the account as well as the fee keeper collected
them.
Thanks: @ValarDragon for pointing this out
Closes: #3093
______
For Admin Use:
> R4R: x/auth: fetch one account after another

- x/stake/client/cli/tx.go
> FIX: small typo in stake/client/cli/tx.go

- PENDING.md
- x/distribution/keeper/hooks.go
- x/distribution/keeper/validator.go
Fixes #3160 
Alternatively, we could also do this in `takeValidatorFeePoolRewards`
______
For Admin Use:
> R4R: Withdraw commission on self bond removal

- .circleci/config.yml
- PENDING.md
Closes #2498 
______
For Admin Use:
> R4R: added macos integration tests

- PENDING.md
- cmd/gaia/app/sim_test.go
- x/slashing/genesis.go
> R4R: Add slashing genesis validation

- CHANGELOG.md
- PENDING.md
- client/lcd/test_helpers.go
- cmd/gaia/app/app.go
- cmd/gaia/app/app_test.go
- cmd/gaia/app/sim_test.go
- cmd/gaia/cmd/gaiad/main.go
- cmd/gaia/cmd/gaiareplay/main.go
- cmd/logjack/main.go
- x/distribution/keeper/hooks.go
- x/distribution/keeper/validator.go
Point release for GoS fixes (which will be breaking, so `v0.29` I suppose).
This should see further review and simulation testing.
PR back to develop: https://github.com/cosmos/cosmos-sdk/pull/3166.
______
For Admin Use:
> GoS point release

- CHANGELOG.md
- PENDING.md
- client/lcd/test_helpers.go
- cmd/gaia/app/app.go
- cmd/gaia/app/app_test.go
- cmd/gaia/app/sim_test.go
- cmd/gaia/cmd/gaiad/main.go
- cmd/gaia/cmd/gaiareplay/main.go
- cmd/logjack/main.go
- x/distribution/keeper/hooks.go
- x/distribution/keeper/validator.go
Release PR: https://github.com/cosmos/cosmos-sdk/pull/3165.
______
For Admin Use:
> Merge GoS point release back to develop

- PENDING.md
- client/flags.go
- client/lcd/lcd_test.go
- cmd/gaia/cli_test/cli_test.go
- docs/gaia/gaiacli.md
--gas=simulate caused confusion and could be
mistaken for the --simulate flag.
Closes: #3162
______
For Admin Use:
> R4R: change --gas=simulate to --gas=auto when sending txs

- PENDING.md
- baseapp/baseapp.go
- baseapp/options.go
- cmd/gaia/init/testnet.go
- server/config/toml.go
- server/util.go
* Support minimum fees on a local testnet (default `1stake`)
* Fix parsing/loading gaiad config (it was never being parsed/respected when it already existed)
----
______
For Admin Use:
> R4R: Support min fees in a localnet and fix gaiad config

- PENDING.md
- client/lcd/lcd_test.go
- client/lcd/swagger-ui/swagger.yaml
- client/lcd/test_helpers.go
- docs/gaia/gaiacli.md
- x/gov/client/cli/query.go
- x/gov/client/module_client.go
- x/gov/client/rest/rest.go
- x/gov/client/utils/query.go
closes: #3027
/cc @johnmcdowall 
I'm not totally thrilled on the solution because it blurs the line of what really belongs in the LCD and what doesn't, as far as querying state is concerned. But maybe this is an exception.
----
______
For Admin Use:
> R4R: Implement Proposal Proposer client interfaces

- .gitattributes
This was really bugging me so I investigated and turns out it's quite easy to fix.
Github uses https://github.com/github/linguist to get the language stats for a repo. A simple `.gitattributes` file can tell it to ignore certain files. We have about 75k lines of javascript in `client/lcd/swagger-ui`. With this commit, github will ignore files in that dir when computing language stats. Running the linguist tool locally, here's a before and after this commit:
Before:
```
cosmos-sdk$ github-linguist 
62.87%  JavaScript
34.34%  Go
1.56%   Python
0.50%   Makefile
0.42%   HCL
0.22%   Shell
0.07%   HTML
0.02%   Dockerfile
```
After:
```
cosmos-sdk$ github-linguist 
92.65%  Go
4.20%   Python
1.35%   Makefile
1.14%   HCL
0.60%   Shell
0.07%   Dockerfile
```
Much better!
Apparently it can take some …
> R4R Use .gitattributes to ignore JS files - this is not a js repo :)

- PENDING.md
- types/coin.go
- types/coin_test.go
Quoth @ValarDragon:
> This stems from a buggy coins.IsValid function. In the IsValid function, https://github.com/cosmos/cosmos-sdk/blob/develop/types/coin.go#L140, it just checks if the coins object is sorted and only has coins with postive value. However when there are multiple tokens, (the default case in the switch statement), the first denom doesn't get its coins value checked for being positive. This means the first denom can be negative or zero. (Recall that its a signed big int >_>, I really wish the uint war would end with everyone being convinced of uints)
This PR adds in desired checks in `coins.IsValid()` and adds a testcase for a negative first-denom coin.
______
For Admin Use:
- Squashed …
> R4R: Fix token printing bug

- types/coin.go
- types/coin_test.go
We didn't check the casing on the single coin case within is_valid. This also changes default-case handling to re-use logic on the single coins case.
______
For Admin Use:
> Fix another is_valid bug

- PENDING.md
- cmd/gaia/app/export.go
- x/slashing/genesis.go
- x/slashing/hooks.go
- x/slashing/slashing_period.go
- x/slashing/slashing_period_test.go
closes: #3187
----
______
For Admin Use:
> R4R: Reset slashing periods on export

- docs/README.md
- docs/gaia/installation.md
- docs/gaia/join-testnet.md
- docs/gaia/validators/validator-setup.md
> R4R: Docs: Fix links and other small improvements

- PENDING.md
- client/lcd/swagger-ui/swagger.yaml
Closes #2948 
______
For Admin Use:
> R4R: Change swagger host for online API requests

- PENDING.md
- x/stake/client/cli/query.go
- x/stake/client/cli/utils.go
- x/stake/keeper/delegation.go
- x/stake/keeper/query_utils.go
- x/stake/keeper/sdk_types.go
- x/stake/keeper/validator.go
- x/stake/types/delegation.go
- x/stake/types/validator.go
closes https://github.com/cosmos/cosmos-sdk/issues/3233
______
For Admin Use:
> R4R: Remove KV marshalling split

- cmd/gaia/cli_test/cli_test.go
- types/coin.go
- types/coin_test.go
- x/auth/ante.go
The intended behavior in the mempool is that any denom specified in the configuration parameter `--minimum` should be sufficient to pay fees. The current behavior requires all denoms to pay fees.
______
For Admin Use:
> The semantics of specifying multiple fees in configuration should be OR instead of AND

- PENDING.md
- baseapp/baseapp.go
- x/auth/ante.go
For a given block, if a tx fails/aborts, we _currently_ do not update the context and as such the `defer`ed function call in `BaseApp#runTx` still uses the `infiniteGasMeter` and subsequent txs may well exceed the limit.
closes: #3242
----
______
For Admin Use:
> R4R: Fix runTx Gas Consumption during Tx Aborting

- PENDING.md
- baseapp/baseapp_test.go
- baseapp/options.go
- cmd/gaia/cmd/gaiad/main.go
- cmd/gaia/cmd/gaiadebug/hack.go
- cmd/gaia/cmd/gaiareplay/main.go
- docs/examples/basecoin/cmd/basecoind/main.go
- server/mock/store.go
- store/codec.go
- store/dbstoreadapter.go
- store/iavlstore.go
- store/multistoreproof_test.go
- store/pruning.go
- store/rootmultistore.go
- store/rootmultistore_test.go
- store/transientstore.go
- types/store.go
closes: #3194
Allows custom configuration for syncable strategy
> R4R: Configurable pruning

- PENDING.md
- client/lcd/swagger-ui/swagger.yaml
- x/gov/handler.go
- x/gov/keeper.go
- x/gov/proposals.go
- x/gov/querier.go
closes #2859
______
For Admin Use:
> R4R:  Rename Proposal TallyResult to FinalTallyResult

- cmd/gaia/cli_test/test_helpers.go
Rely on `ioutil.TempDir()` for safe randomized generation of cli tests home directories.
______
For Admin Use:
> R4R: Create separate directories for cli tests

- .circleci/config.yml
- PENDING.md
> R4R: build gaia docker image during CI

- PENDING.md
- server/tm_cmds.go
- server/util.go
> R4R: Add tendermint version command

- cmd/gaia/cmd/gaiad/main.go
We need to load the latest height if we aren't loading a specific height.
______
For Admin Use:
> R4R: Non-zero-height export fix

- PENDING.md
- baseapp/baseapp_test.go
- client/keys/add.go
- client/utils/utils.go
- cmd/gaia/cli_test/cli_test.go
- cmd/gaia/cli_test/test_helpers.go
- cmd/gaia/cmd/gaiacli/main.go
- cmd/gaia/cmd/gaiad/main.go
- cmd/gaia/cmd/gaiareplay/main.go
- cmd/gaia/init/genesis_accts.go
- docs/examples/democoin/x/simplestaking/client/cli/commands.go
- docs/gaia/gaiacli.md
- x/auth/ante.go
- x/auth/ante_test.go
- x/auth/client/cli/multisign.go
- x/auth/client/cli/sign.go
- x/auth/client/rest/sign.go
- x/gov/genesis_test.go
Habemus multisig:
* New `keys add --multisig` flag to store multisig keys locally.
* New `multisign` command to generate multisig signatures.
* New `sign --multisig` flag to enable multisig mode.
* Add multisig transactions support in ante handler
* `gaiad add-genesis-account` can now take both account addresses and key names
Closes: #3198
______
For Admin Use:
> R4R: Multisig support

- PENDING.md
- client/lcd/root.go
Closes: #2715
______
For Admin Use:
> R4R: reintroduce gaia server's insecure mode

- PENDING.md
- client/config.go
- client/flags.go
- client/rpc/block.go
- client/rpc/validators.go
- client/tx/query.go
- client/tx/search.go
- cmd/gaia/cli_test/test_helpers.go
- cmd/gaia/cmd/gaiacli/main.go
- docs/gaia/gaiacli.md
--chain-id must be a persistent flag to be successfully read from config.
Closes: #810
______
For Admin Use:
> R4R: fix regression in gaiacli config file handling

- PENDING.md
- cmd/gaia/app/app.go
- cmd/gaia/app/genesis.go
- cmd/gaia/app/genesis_test.go
- cmd/gaia/app/sim_test.go
- docs/spec/auth/vesting.md
- x/auth/account.go
- x/auth/account_test.go
- x/auth/codec.go
- x/bank/keeper_test.go
- x/bank/simulation/msgs.go
- x/mock/simulation/account.go
- x/mock/simulation/simulate.go
- Fix `GetVestedCoins` bug where block time is past vesting end time
- Update time fields on vesting account(s) to `int64` from `time.Time`
- Update constructors to directly take a `*BaseAccount` as this will allow vesting accounts to have the account number/sequences inherited 
- Update genesis logic to support vesting accounts
- Add vesting account support to simulation
closes: #3305
----
______
For Admin Use:
- Squashed all commits, uses message "Merge pull request #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/master/README.md#merg …
> R4R: Genesis Vesting Accounts & Simulation

- PENDING.md
- client/lcd/lcd_test.go
- types/decimal.go
- types/decimal_test.go
closes #3039 
______
For Admin Use:
> R4R: Increase decimal precision to 18

- PENDING.md
- client/lcd/lcd_test.go
- client/lcd/test_helpers.go
- cmd/gaia/app/genesis.go
- cmd/gaia/app/sim_test.go
- docs/spec/distribution/hooks.md
- docs/spec/staking/tags.md
- x/gov/client/utils/query.go
- x/slashing/handler_test.go
- x/slashing/keeper_test.go
- x/slashing/test_common.go
- x/staking/app_test.go
- x/staking/client/cli/tx.go
- x/staking/client/rest/query.go
- x/staking/client/rest/tx.go
- x/staking/handler.go
- x/staking/handler_test.go
- x/staking/keeper/delegation.go
- x/staking/keeper/delegation_test.go
- x/staking/keeper/test_common.go
- x/staking/keeper/val_state_change.go
- x/staking/keeper/validator.go
- x/staking/querier/querier_test.go
- x/staking/simulation/msgs.go
- x/staking/staking.go
- x/staking/test_common.go
- x/staking/types/codec.go
- x/staking/types/msg.go
- x/staking/types/msg_test.go
- x/staking/types/validator.go
closes https://github.com/cosmos/cosmos-sdk/issues/3289
______
For Admin Use:
> R4R: Staking misc rename

- PENDING.md
- cmd/gaia/app/app.go
- docs/gaia/gaiacli.md
- x/distribution/alias.go
- x/distribution/client/cli/query.go
- x/distribution/client/cli/util.go
- x/distribution/client/module_client.go
- x/distribution/keeper/querier.go
- x/distribution/keeper/querier_test.go
Adds queriers and distribution CLI query commands for:
- Module parameters
- Outstanding (un-withdrawn) rewards
- Outstanding validator commission
- Validator slashes
- Current delegator rewards (if they were to be withdrawn)
Closes https://github.com/cosmos/cosmos-sdk/issues/3307
Closes https://github.com/cosmos/cosmos-sdk/issues/2359
______
For Admin Use:
> R4R: Distribution Queriers & CLI query commands

- docs/examples/basecoin/cmd/basecoind/main.go
Adds a function to fix #3142 to initialise the Cosmos SDK to use the same Bech32
prefixes as those which basecli uses.
______
For Admin Use:
> WIP: custom Bech32 prefixes break tutorial code

- PENDING.md
- client/flags.go
- cmd/gaia/cmd/gaiacli/main.go
- cmd/gaia/cmd/gaiad/main.go
- docs/gaia/gaiacli.md
- server/util.go
> R4R: add command to generate bash completion for gaia{d,cli}

- PENDING.md
- client/config.go
- cmd/gaia/cli_test/cli_test.go
It defaults to false, users can override it via gaiacli config
and avoid to append --indent to all commands:
$ gaiacli config indent true
Closes: #2607
______
For Admin Use:
> R4R: make gaiacli config handle "indent" flag

- .circleci/config.yml
- Makefile
- PENDING.md
- version/command.go
- version/version.go
Closes: #1894
______
For Admin Use:
> R4R: enrich version command's output

- PENDING.md
- x/bank/msgs.go
- x/bank/msgs_test.go
- x/distribution/types/msg.go
- x/gov/msgs.go
- x/slashing/msg.go
- x/staking/types/msg.go
Ensure all messages include canonical `type` and `value` fields when generating message bytes to sign over.
closes: #3336 
----
______
For Admin Use:
> R4R: Ensure Canonical Message Signature Bytes

- PENDING.md
- types/dec_coin.go
- types/decimal.go
- x/distribution/keeper/delegation.go
- x/distribution/keeper/validator.go
Closes https://github.com/cosmos/cosmos-sdk/issues/3354
Always round down when calculating rewards in F1 fee distribution. As far as I can tell, this fixes all the F1-related simulation issues, but I haven't yet run a long multi-seed test.
______
For Admin Use:
> R4R: Round down when calculating rewards (fixes F1 sim bug)

- x/auth/simulation/fake.go
Only consider spendable coins when attempting to deduct fees in simulation.
closes: #3353
----
______
For Admin Use:
> R4R: Fix Fee Usage for Vesting Accounts in Simulation 

- x/staking/keeper/delegation.go
The "balance" during unbonding can be zero either from the remaining shares being zero or from truncation. In either case, there is no need to track undelegation (which would result in a safety check trip/panic).
closes: #3362
----
______
For Admin Use:
> R4R: Only Track Undelegation for non-zero Amounts

- PENDING.md
- client/context/broadcast.go
- client/context/context.go
- client/flags.go
- cmd/gaia/cli_test/cli_test.go
- cmd/gaia/cli_test/test_helpers.go
- server/tm_cmds.go
gaiad tendermint show-{address,validator} now take --machine-parseable/-m
for machine parseable output.
Closes: #3249
______
For Admin Use:
> R4R: remove --json flag from all commands

- PENDING.md
- cmd/gaia/cli_test/cli_test.go
- server/config/config.go
- server/config/toml.go
- server/start.go
Ref #3241
______
For Admin Use:
> R4R: Use dash-separated flags for minimus gas prices

- x/auth/simulation/fake.go
- x/distribution/keeper/delegation.go
- x/distribution/keeper/delegation_test.go
- x/distribution/keeper/hooks.go
- x/distribution/keeper/store.go
- x/distribution/keeper/validator.go
- x/distribution/simulation/invariants.go
- x/staking/genesis.go
Closes https://github.com/cosmos/cosmos-sdk/issues/3366
`AfterDelegationModified` was called twice, and the distribution module wasn't quite correctly tracking references - it now correctly tracks the reference for the latest period, which we need to know regardless of whether or not a delegation started it.
Still fails due to other simulation issues.
______
For Admin Use:
> R4R: F1 storage simulation debugging

- .gitignore
cc @alessio 
Doesn't need `PENDING.md`.
______
For Admin Use:
> R4R: Add vendor-deps to `.gitignore`

- x/staking/genesis.go
- x/staking/keeper/delegation.go
Hooks should only be called in genesis when we're importing from *non*-exported state.
______
For Admin Use:
> R4R: Fix staking hooks on import exported state

- PENDING.md
- docs/spec/staking/messages.md
- docs/spec/staking/state.md
- x/staking/keeper/delegation.go
- x/staking/keeper/delegation_test.go
- x/staking/keeper/params.go
- x/staking/types/errors.go
- x/staking/types/params.go
closes #3270
______
For Admin Use:
> R4R: limit unbonding delegation / redelegations

- Makefile
- docs/gaia/installation.md
- docs/gaia/join-testnet.md
Replace get_vendor_deps with vendor-deps in Makefile.
> Update docs get_vendor_deps -> vendor-deps

- PENDING.md
- cmd/gaia/app/app.go
- cmd/gaia/app/genesis.go
- cmd/gaia/app/genesis_test.go
- cmd/gaia/cli_test/cli_test.go
- cmd/gaia/cli_test/test_helpers.go
- cmd/gaia/init/collect.go
- cmd/gaia/init/genesis_accts.go
- cmd/gaia/init/gentx.go
- cmd/gaia/init/testnet.go
- cmd/gaia/init/utils.go
Implement genesis file sanitization to avoid failures at chain init.
* Add GenesisState.Sanitize(). It sorts genesis accounts and
coin sets to ensure genesis state passes validation.
* gaia app calls GenesisState.Sanitize() on initFromGenesisState()
before processing the genesis state.
Closes: #3390
______
For Admin Use:
> R4R: Implement GenesisState.Sanitize()

- PENDING.md
- cmd/gaia/cli_test/cli_test.go
- cmd/gaia/cli_test/test_helpers.go
- cmd/gaia/cmd/gaiad/main.go
- cmd/gaia/init/validate_genesis.go
Fixes: https://github.com/cosmos/cosmos-sdk/issues/3398
______
For Admin Use:
> R4R: Add validate-genesis command

- PENDING.md
- cmd/gaia/cli_test/cli_test.go
- cmd/gaia/cli_test/test_helpers.go
- cmd/gaia/init/validate_genesis.go
- x/slashing/client/cli/query.go
Fixes: #3393 
______
For Admin Use:
> R4R: Fix query signing-info panic

- PENDING.md
- x/distribution/client/cli/query.go
> R4R: Fix query distr slashes

- PENDING.md
- cmd/gaia/app/genesis.go
- cmd/gaia/app/genesis_test.go
- docs/gaia/genesis.md
closes: #3418
partially addresses: #3406
______
______
For Admin Use:
> R4R: Add Vesting Account Genesis Validation

- PENDING.md
- client/context/context.go
- client/context/query.go
- client/lcd/lcd_test.go
- client/lcd/swagger-ui/swagger.yaml
- client/lcd/test_helpers.go
- client/utils/rest.go
- client/utils/utils.go
- docs/.vuepress/config.js
- docs/clients/service-providers.md
- docs/gaia/gaiacli.md
- docs/gaia/ledger.md
- x/auth/client/rest/sign.go
- x/bank/client/cli/sendtx.go
- x/bank/client/rest/sendtx.go
- x/distribution/client/cli/tx.go
- x/gov/client/cli/tx.go
- x/gov/client/rest/rest.go
- x/ibc/client/cli/ibctx.go
- x/ibc/client/cli/relay.go
- x/ibc/client/rest/transfer.go
- x/slashing/client/cli/tx.go
- x/slashing/client/rest/tx.go
- x/staking/client/cli/tx.go
- x/staking/client/rest/tx.go
- Minor CLI context and utils cleanup
- REST now allows using an address OR key name (just like the CLI ⚡️)
- This does cause a **breaking** change (`name` => `from`, again just like the CLI ⚡️)
- Update `CompleteAndBroadcastTxREST`
- Remove generate only logic (this now should be handled in each respective REST handler)
- Use `prepareTxBuilder` which will allow account number and nonce to be derived from state
- Update swagger
- Remove any notion `generate_only` and `simulate` as query params (these were deprecated long agooooo)
- Update `name` to `from`
- Formatting fixes from @faboweb 
closes: #3284
----
______
For Admin Use:
- Added appropriate …
> R4R: Gaia Lite Generate Only Support (w/o Keybase)

- PENDING.md
- x/gov/errors.go
- x/gov/msgs.go
- x/gov/msgs_test.go
closes #3420
______
For Admin Use:
> R4R:  Add length caps for governance proposal titles and descriptions

- Makefile
- PENDING.md
- cmd/gaia/app/sim_test.go
- scripts/multisim.sh
- x/mock/simulation/simulate.go
Closes #3182 
Includes new Makefile commands `test_sim_gaia_custom_genesis_fast` and `test_sim_gaia_custom_genesis_multi_seed`, which both default to using `~/.gaiad/config/genesis.json`.
To test with the `gaia-10k` genesis, download [this file](https://github.com/cosmos/testnets/raw/master/gaia-10k/genesis.json) to `~/.gaiad/config/genesis.json` and run one of those new commands.
______
For Admin Use:
> R4R: Simulate from a genesis file

- Makefile
- Remove --long from git describe. Appending commit info on tagged
revisions is redundant.
- $(subst v,,$(shell git describe --tags --long)) was removing any
occurrence of 'v'. Rather we want to remove only the 'v' prefix
from tags.
______
For Admin Use:
> Small fixes for Makefile

- x/gov/codec.go
- x/gov/msgs_test.go
Register `x/gov` message types on `init`. This will ensure message signature bytes have the canonical type and value fields.
closes: #3443
----
______
For Admin Use:
> R4R: Register x/gov Message Types on init

- PENDING.md
- client/context/context.go
- client/lcd/test_helpers.go
Replaces https://github.com/cosmos/cosmos-sdk/pull/3191
Closes: https://github.com/cosmos/cosmos-sdk/issues/2432
Recreate the singleton verifier if the home directory has changed.
This means that LCD proofs now test lite client verification.
______
For Admin Use:
> R4R: LCD proof verification

- PENDING.md
- client/flags.go
- client/lcd/root.go
The `rest-server` command didn't respect persistent flags such as `--chain-id` and `--trust-node` if they were passed on the command line.
______
For Admin Use:
> R4R: make rest-server respect persistent flags

- PENDING.md
- cmd/gaia/init/gentx.go
Let gentx generation continue when gaiad is unable to retrieve
machine's external IP and print a warning message.
Closes: #3424
______
For Admin Use:
> R4R: allow generation of gentxs with empty memo field

- PENDING.md
- client/errors.go
- client/utils/errors.go
- client/utils/rest.go
- client/utils/utils.go
- docs/gaia/gaiacli.md
- x/auth/client/txbuilder/txbuilder.go
- x/bank/client/rest/sendtx.go
- x/gov/client/rest/rest.go
- x/ibc/client/rest/transfer.go
- x/slashing/client/rest/tx.go
- x/staking/client/rest/tx.go
closes: #3423
----
______
For Admin Use:
> R4R: Allow Simulation and Gen Only in REST Client

- PENDING.md
- x/auth/ante.go
- x/auth/client/txbuilder/txbuilder.go
- x/slashing/params.go
closes #2509
follow up issues:
https://github.com/cosmos/cosmos-sdk/issues/3472
https://github.com/cosmos/cosmos-sdk/issues/3473
______
For Admin Use:
> R4R: Sanitize Dec.Roundint64

- PENDING.md
- client/flags.go
- client/lcd/root.go
- docs/clients/lite/getting_started.md
- `--insecure` flag is removed.
- `--tls` is now used to enable secure layer.
Closes: #3465
______
For Admin Use:
> gaiacli switches back to insecure mode by default

- PENDING.md
- client/utils/rest.go
Make error responses turn into JSON responses.
______
For Admin Use:
> R4R: Introduce RESTful error responses

- .circleci/config.yml
- Makefile
- README.md
- snapcraft.yaml
> Build.snapcraft.io integration

- PENDING.md
- client/lcd/lcd_test.go
- client/lcd/test_helpers.go
- client/rest/rest.go
- client/rest/types.go
- client/rpc/block.go
- client/rpc/root.go
- client/rpc/status.go
- client/rpc/validators.go
- client/tx/broadcast.go
- client/tx/query.go
- client/tx/search.go
- client/utils/utils.go
- x/auth/client/rest/query.go
- x/auth/client/rest/sign.go
- x/bank/client/rest/broadcast.go
- x/bank/client/rest/sendtx.go
- x/gov/client/rest/rest.go
- x/ibc/client/rest/transfer.go
- x/slashing/client/rest/query.go
- x/slashing/client/rest/tx.go
- x/staking/client/rest/query.go
- x/staking/client/rest/tx.go
- x/staking/client/rest/utils.go
Move REST-related types and functions out of client/utils into a new client/rest package.
______
For Admin Use:
> R4R: client/utils/ reorganization

- client/flags.go
Really closes: #3465
______
For Admin Use:
> R4R: disable TLS flag by default

- PENDING.md
- x/auth/account.go
- x/auth/account_test.go
Removes the performance optimization when querying to see if vesting coins are in the correct state and just use AmountOf.
This bug was discovered on Game of Stakes 5.
Fixes #3483 and #3482 
Would be benefit from multicoin unit tests.
_____
For Admin Use:
> R4R: Checking Vesting Coins with AmountOf

- PENDING.md
- x/gov/tally.go
closes #3457
______
For Admin Use:
> R4R:  Gov validator power sdk.Int

- PENDING.md
- baseapp/baseapp.go
- client/context/broadcast.go
- client/context/context.go
- client/lcd/lcd_test.go
- client/lcd/test_helpers.go
- client/tx/query.go
- client/tx/search.go
- client/utils/utils.go
- cmd/gaia/cli_test/cli_test.go
- cmd/gaia/cli_test/test_helpers.go
- types/result.go
- types/tags.go
- types/tags_test.go
- x/bank/client/cli/broadcast.go
- x/bank/keeper.go
- x/gov/handler.go
- x/gov/tags/tags.go
- x/slashing/handler.go
- x/slashing/tags/tags.go
- x/staking/client/rest/query.go
- x/staking/client/rest/utils.go
- x/staking/handler.go
- x/staking/tags/tags.go
Replaces: https://github.com/cosmos/cosmos-sdk/pull/3277
______
For Admin Use:
> R4R: Make tags and responses legible

- PENDING.md
- x/gov/genesis.go
- x/gov/genesis_test.go
While working on increasing coverage, I noticed a typo in a possibly critical area.
It does not seem to have an impact at this moment but I would suggest the fix gets applied soon.
I have only included a test for the specific bug/fix. In the next few days, we will increase coverage in other PRs.
______
For Admin Use:
> R4R: Fixing bug in genesis Equal

- PENDING.md
- client/lcd/lcd_test.go
- client/rpc/validators.go
- cmd/gaia/cmd/gaiacli/main.go
- Use consensus address bech32 prefixing
- Use `CLIContext#PrintOutput`
closes: #3501
---
______
For Admin Use:
> R4R: Fix validator address encoding in tm validator set command

- PENDING.md
- client/keys/add.go
Show the mnemonic by default.
closes: #3518
----
______
For Admin Use:
> R4R: Show Mnemonic by Default

- Makefile
- PENDING.md
- docs/_attic/sdk/core/examples/app1.go
- tests/test_cover.sh
- types/coin.go
- x/auth/stdtx.go
- x/bank/keeper.go
- x/bank/simulation/invariants.go
- x/gov/msgs.go
> R4R: get rid of double negatives: IsNotNegative -> IsAnyNegative

- .circleci/config.yml
Small improvement to circleci config file
______
For Admin Use:
> localnet does not require setup_dependencies

- cmd/gaia/app/sim_test.go
Just a fix after the Tendermint power reduction PR; I don't think this merits `PENDING.md`.
______
For Admin Use:
> R4R: Multiply initial simulation token amounts by 1e6

- client/utils/utils.go
- cmd/gaia/cli_test/cli_test.go
- cmd/gaia/cli_test/test_helpers.go
- cmd/gaia/init/gentx.go
- docs/gaia/gaiacli.md
- docs/gaia/ledger.md
- x/auth/client/cli/account.go
- x/auth/client/cli/multisign.go
- x/auth/client/cli/sign.go
- x/bank/client/cli/broadcast.go
- x/bank/client/cli/sendtx.go
- x/distribution/client/cli/query.go
- x/distribution/client/cli/tx.go
- x/gov/client/cli/query.go
- x/gov/client/cli/tx.go
- x/ibc/client/cli/ibctx.go
- x/slashing/client/cli/query.go
- x/slashing/client/cli/tx.go
- x/staking/client/cli/flags.go
- x/staking/client/cli/query.go
- x/staking/client/cli/tx.go
- x/staking/client/cli/utils.go
cc @alessio and @alexanderbez 
______
For Admin Use:
> R4R: CLI flags to args

- .circleci/config.yml
Some packages aren't showing up in codecov.io due to the use of `basename` to generate unique per-package coverage files.
______
For Admin Use:
> Don't overwrite coverage files

- cmd/gaia/cli_test/cli_test.go
This reduces the time to run the CLI tests from `~364.132s` to `~163.029s`
> R4R: Speed up CLI tests

- PENDING.md
- cmd/gaia/cli_test/cli_test.go
- docs/gaia/gaiacli.md
- docs/spec/auth/gas_fees.md
- server/config/config.go
- server/config/toml.go
- server/start.go
- types/coin.go
- types/coin_test.go
- types/dec_coin.go
- types/int.go
- x/auth/ante.go
- x/auth/ante_test.go
- Reintroduce OR semantics for comparing tx fees to validator min fees.
- Update config and CLI usage to use `;` instead of `,` for min gas prices as a deliminator 
----
______
For Admin Use:
> R4R: Reintroduce Fees OR Semantics

- baseapp/baseapp.go
- client/context/broadcast.go
- client/context/errors.go
- client/context/query.go
- client/input.go
- client/keys/add.go
- client/keys/show.go
- cmd/gaia/init/validate_genesis.go
- crypto/keys/keybase.go
- server/export.go
- server/start.go
- server/util.go
- x/auth/client/txbuilder/txbuilder.go
- x/bank/client/cli/sendtx.go
- x/gov/client/cli/tx.go
- x/gov/client/rest/rest.go
- x/gov/depositsvotes.go
- x/gov/proposals.go
- x/staking/client/cli/utils.go
Removing pkg/errors when standard packages could be used
(as discussed in https://github.com/cosmos/cosmos-sdk/pull/3517#discussion_r254971154.)
I dont think this deserves an entry in Pending.md, but I am happy to add it if necessary.
______
For Admin Use:
> R4R: Removing pkg/errors when not necessary

- PENDING.md
- cmd/gaia/cli_test/test_helpers.go
- cmd/gaia/init/genesis_accts.go
- cmd/gaia/init/genesis_accts_test.go
- cmd/gaia/init/init.go
closes: #3484
----
______
For Admin Use:
> R4R: Support Vesting Accounts in `add-genesis-account`

- PENDING.md
- client/lcd/lcd_test.go
- client/lcd/swagger-ui/swagger.yaml
- cmd/gaia/cli_test/cli_test.go
- cmd/gaia/cli_test/test_helpers.go
- cmd/gaia/cmd/gaiacli/main.go
- x/auth/client/cli/broadcast.go
- x/auth/client/cli/encode.go
- x/auth/client/cli/multisign.go
- x/auth/client/cli/sign.go
- x/auth/client/rest/broadcast.go
- x/auth/client/rest/encode.go
- x/auth/client/rest/query.go
- x/auth/client/util.go
- x/auth/client/util_test.go
- x/bank/client/rest/sendtx.go
This PR adds a `/tx/encode` endpoint to Gaia to take a JSON-ified transaction, serialize it using the Amino wire format, and return the serialized bytes encoded to a base64 string.  The wire format is necessary to determine a transaction's hash, so it's useful for client applications that want to build their own transactions without being dependent on wire serialization changes.  I've also included an equivalent `gaiacli tx encode` command.
- N/A: Discussed the feature with the Cosmos devs in Slack
______
For Admin Use:
- Squashed all commits, uses message "Merge …
> R4R: Add tx/encode endpoint and CLI command

- PENDING.md
- client/lcd/lcd_test.go
- cmd/gaia/cli_test/cli_test.go
- x/staking/handler.go
- x/staking/handler_test.go
- x/staking/keeper/delegation.go
- x/staking/keeper/delegation_test.go
- x/staking/keeper/slash.go
- x/staking/keeper/slash_test.go
- x/staking/querier/querier_test.go
- x/staking/simulation/invariants.go
- x/staking/types/delegation.go
- x/staking/types/delegation_test.go
- x/staking/types/msg.go
Followup from https://github.com/cosmos/cosmos-sdk/pull/3507
Closes https://github.com/cosmos/cosmos-sdk/issues/3541
______
For Admin Use:
> R4R: Don't store denominations in staking

- client/rest/rest.go
- client/utils/utils.go
- x/auth/account.go
- x/auth/ante.go
- x/auth/client/txbuilder/txbuilder.go
- x/auth/client/txbuilder/txbuilder_test.go
- x/auth/codec.go
- x/auth/feekeeper.go
- x/auth/genesis.go
- x/auth/keeper.go
- x/auth/params.go
- x/auth/stdtx.go
- x/bank/errors.go
- x/bank/genesis.go
- x/bank/keeper.go
- x/bank/msgs.go
- x/bank/params.go
This is the results of a code review of the `x/auth` and `x/bank` modules by @sunnya97 and @jackzampolin
> R4R: x/auth and x/bank review results

- PENDING.md
- types/int.go
- types/int_test.go
(partially?) addresses #1008
----
______
For Admin Use:
> R4R: General Sanitization & Gas Cost Review

- docs/gaia/delegator-guide-cli.md
Legal recommendations :)
______
For Admin Use:
> R4R: Add warning and disclaimer

- cmd/gaia/app/genesis.go
- x/staking/simulation/invariants.go
Fixes two issues discovered when using an alternative bond token denomination other than `stake`
- Invariant checker uses default denom
- `collect-gentx` uses default denom when computing supply.
______
For Admin Use:
> Fixes for non-default staking token

- PENDING.md
- types/result.go
closes: #3585 
______
______
For Admin Use:
> R4R: Fix setting tx hash when nil

- Makefile
- PENDING.md
Running `make test_unit` was failing because a tag was missing.
I think that this tiny fix does not require an entry in pending.md but I am happy to do it if required.
______
For Admin Use:
> R4R: Fix for make test_unit

- PENDING.md
- client/keys/add.go
- client/keys/add_ledger_test.go
- client/keys/add_test.go
- crypto/keys/codec.go
- crypto/keys/hd/hdpath.go
- crypto/keys/keybase.go
- crypto/keys/keybase_test.go
- crypto/keys/types.go
- crypto/keys/types_test.go
- crypto/ledger_test.go
Closes https://github.com/cosmos/cosmos-sdk/issues/3573
______
For Admin Use:
> R4R: Fixes gaia/keybase storage of ledger accounts

- PENDING.md
- types/errors.go
- types/errors_test.go
- x/auth/ante.go
- x/bank/keeper.go
* Improve funds-based SDK error messages
* Allow unicode to not be escaped in JSON (e.g. so error messages will actually display `<`)
----
______
For Admin Use:
> R4R: Improve SDK Error Messages & Allow Unicode

- PENDING.md
- types/coin.go
- types/coin_test.go
We weren't checking for the case where the denom is not present in required fees.
closes: #3617
/cc @zmanian 
----
______
For Admin Use:
> R4R: Fix Fee Comparison

- PENDING.md
- types/result.go
closes: #3585
----
______
For Admin Use:
> R4R: Return an empty TxResponse

- Gopkg.lock
- Gopkg.toml
- PENDING.md
> R4R: Upgrade to tendermint 0.30.0 final

- PENDING.md
- crypto/keys/mintkey/README.md
- crypto/keys/mintkey/mintkey.go
- crypto/keys/mintkey/mintkey_bench_test.go
Closes https://github.com/cosmos/cosmos-sdk/issues/3547
______
For Admin Use:
> R4R: Bcrypt investigations / benchmarks

- Makefile
- PENDING.md
- docs/gaia/installation.md
- version/version.go
This PR adds build tags to the version command:
cosmos-sdk: 0.31.1-10-gfe548c08
git commit: fe548c0829a4f232028329ec2b93d9e4dcdb4447
vendor hash: 1aec7edfad9888a967b3e9063e42f66b28f447e6
**build tags: netgo ledger**
go version go1.11.5 linux/amd64
This is useful to understand which features were enabled when building the binary.
The issue is related to https://github.com/cosmos/cosmos-sdk/issues/3528
______
For Admin Use:
- Squashed all commits, uses message "Merge pull request #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/master/READ …
> R4R: Indicate build flags in version

- PENDING.md
- x/auth/account.go
closes: #3648 
----
______
For Admin Use:
> R4R: Add JSON Struct Tags to Vesting Accounts

- PENDING.md
- types/staking.go
- x/distribution/types/expected_keepers.go
- x/gov/tally.go
- x/mint/abci_app.go
- x/mint/expected_keepers.go
- x/staking/keeper/alias_functions.go
- x/staking/types/validator.go
closes #3646
______
For Admin Use:
> R4R: mint use total supply instead of power

- PENDING.md
- client/lcd/lcd_test.go
- client/lcd/test_helpers.go
- client/tx/query.go
- types/result.go
Fixes: https://github.com/cosmos/cosmos-sdk/issues/3639
cc @alexanderbez @alessio
> R4R: Tx Query return values

- client/keys/show.go
- client/keys/show_test.go
- cmd/gaia/cmd/gaiakeyutil/main.go
- store/prefix/store_test.go
- types/address.go
- types/address_test.go
This PR closes #3675 
______
For Admin Use:
> Refactored prefixes as constants

- PENDING.md
- baseapp/baseapp.go
We were not setting the block header time provided to us by `RequestInitChain` -- this impacts only block zero. This is critical for any operations that happen during block zero that depend on the block time (e.g. creating a validator's commission).
closes: #3411
/cc @jbibla 
----
______
For Admin Use:
> Update InitChain to Include Time in Block Header

- PENDING.md
- baseapp/baseapp.go
- client/context/context.go
- types/rest/rest.go
- types/result.go
- types/result_test.go
Essentially this PR updates the `TxResponse#Log`  type to be directly what the BaseApp encodes as the log. In other words, client will no longer have to manually JSON decode this value.
/cc @cosmos/cosmos-ui this finally gets you what you want ⚡️ 
----
______
For Admin Use:
> JSON Decode Log in REST Client

- PENDING.md
- client/lcd/lcd_test.go
closes https://github.com/cosmos/cosmos-sdk/issues/3559
______
For Admin Use:
> R4R: lcd test unexpected slashing in TestBonding

- PENDING.md
- cmd/gaia/cli_test/test_helpers.go
- x/auth/client/cli/sign.go
closes: #3711
----
______
For Admin Use:
> Use from instead of name CLI flag for the tx sign cmd

- Gopkg.lock
- Gopkg.toml
- PENDING.md
- client/keys/show.go
- client/keys/show_test.go
- crypto/keys/keybase_test.go
- crypto/keys/types.go
- crypto/keys/types_test.go
- crypto/ledger_mock.go
- crypto/ledger_secp256k1.go
This PR closes #3658 
It requires unreleased Ledger app Cosmos v1.1.0
______
For Admin Use:
> R4R: CLI support for showing bech32 addresses in Ledger devices

- PENDING.md
- store/types/utils.go
Closes https://github.com/cosmos/cosmos-sdk/issues/3727
cc @mossid 
______
For Admin Use:
> R4R: Return on zero-length byte array input

- docs/gaia/launch/blog-2-en.md
> docs: minor link edits to blog 2

- PENDING.md
- cmd/gaia/cli_test/test_helpers.go
- crypto/keys/lazy_keybase.go
The "short-term" approach to #3716.
I initially attempted to set `chmod -R 0700` on the parent Keybase directory and recursively on all its contents after any `NewGoLevelDB` call (see commit: dfd9deeb03da55d06403ab2a4a221508a75b84a7). 
However, I am able to use the Keybase just fine, but some tests fail on CI because a `ldb` file is missing? Strange. So, I opted to _only_ set `0700` on the parent Keybase directory (`keys`). This should be good enough. Correct me if I'm wrong @alessio or @mircea-c.
----
______
For Admin Use:
- Squashed all commits, uses message …
> Update Client Keys Permissions to 0700

- PENDING.md
- cmd/gaia/app/sim_test.go
- docs/spec/governance/01_concepts.md
- docs/spec/governance/02_state.md
- x/gov/genesis.go
- x/gov/params.go
Closes https://github.com/cosmos/cosmos-sdk/issues/3753
______
For Admin Use:
> Remove governance_penalty

- PENDING.md
- cmd/gaia/init/gentx.go
closes #3730
______
For Admin Use:
> R4R:  Gentx workflow for offline keys

- PENDING.md
- types/dec_coin.go
- types/dec_coin_test.go
- x/distribution/keeper/allocation.go
Related to https://github.com/cosmos/cosmos-sdk/pull/3722
OUTSTANDING TODO: pull out #3722's test into its own test that would fail without these changes.
> R4R: Cap(clip) reward to remaining coins in AllocateTokens

- x/bank/app_test.go
> R4R:  Testing sequence increment if not enough balance for send

- PENDING.md
- x/auth/ante.go
- x/auth/ante_test.go
- x/auth/test_utils.go
- x/bank/app_test.go
- x/ibc/app_test.go
- x/mock/app.go
- x/slashing/app_test.go
- x/staking/test_common.go
Disable the use of ED25519 account key pairs as these result in completely untested code execution paths.
closes: #3751
----
______
For Admin Use:
> Disable ED25519 Account Keys

- PENDING.md
- types/coin.go
- types/dec_coin.go
* Use a more precise regular expression to match denom strings (e.g. [[:lower:]] instead of [[:alpha:]]) and avoid trimming spaces.
* validateDenom() -> validateDenom() error, use mustValidateDenom() in constructors to forcibly panic when validation fails.
______
For Admin Use:
> R4R: improve denom validation

- PENDING.md
- client/context/query.go
- cmd/gaia/app/app.go
- x/auth/keeper.go
- x/auth/querier.go
- x/auth/querier_test.go
> R4R: Added querier for auth module

- PENDING.md
- snapcraft.yaml
- Allow gaiacli to access host's raw-usb slot.
- Promote the package to stable.
Closes: #3714
______
For Admin Use:
> Finalise snapcraft.yaml

- cmd/gaia/app/sim_test.go
This avoids a nil pointer dereference, e.g., when the simulator displays log messages.  This change
is intended to be consistent with:
https://github.com/cosmos/cosmos-sdk/blob/5d05b7ff0f1fb7953b581837fd4ddd8c9fde92e6/x/gov/genesis.go#L60-L63
______
For Admin Use:
> R4R: Simulator: Set Quorum field in appStateRandomizedFn

- x/gov/simulation/msgs.go
In two places in x/gov/simulation/msgs.go, a new CacheContext is created, but its corresponding
write function is never called.  Hence, the changes to that context never make it to the underlying
store.  This commit addresses that issue.
______
For Admin Use:
> R4R: Simulator: write changes to store in x/gov/simulation/msgs.go

- Makefile
- PENDING.md
- cmd/gaia/app/sim_test.go
- cmd/gaia/cmd/gaiadebug/hack.go
- cmd/gaia/cmd/gaiareplay/main.go
- crypto/keys/lazy_keybase.go
- server/constructors.go
- server/mock/app.go
- types/utils.go
Replace NewGoLevelDB() with generic NewLevelDB() calls.
DB backend is picked according to build time configuration.
Makefile:
- DB backend can be switched at compile time by
adding WITH_CLEVELDB=yes to make install.
-  Add support for user supplied ldflags and build tags.
Closes: #3719
______
For Admin Use:
> use DBBackend set at compile time

- PENDING.md
- docs/gaia/validators/validator-setup.md
- docs/translations/kr/gaia/validators/validator-setup.md
- x/staking/alias.go
- x/staking/app_test.go
- x/staking/client/cli/flags.go
- x/staking/client/cli/tx.go
- x/staking/handler_test.go
- x/staking/test_common.go
- x/staking/types/msg.go
- x/staking/types/msg_test.go
Update validator creation flow:
* Remove `NewMsgCreateValidatorOnBehalfOf` and corresponding business logic
* Ensure the validator address equals the delegator address during
`MsgCreateValidator#ValidateBasic`
closes: #3789
----
______
For Admin Use:
> Validator Creation Updates

- PENDING.md
- client/lcd/lcd_test.go
- cmd/gaia/app/export.go
- types/dec_coin.go
- types/dec_coin_test.go
- types/staking.go
- x/distribution/keeper/allocation.go
- x/distribution/keeper/delegation.go
- x/mock/simulation/util.go
- x/slashing/handler.go
- x/staking/handler_test.go
- x/staking/keeper/delegation.go
- x/staking/types/validator.go
- x/staking/types/validator_test.go
REF https://github.com/cosmos/cosmos-sdk/pull/3750
due to order of operations F1 was actually calculating stake slightly differently than staking... see the diff in the code comments for more explanation
fixes problem found here:
https://github.com/cosmos/cosmos-sdk/pull/3750#issuecomment-468477401
Also added a defensive minimum if rewards > outstanding (which could occur in the old code if everyone withdrew in the same block)
(feel free to push to this branch)
> R4R F1 mechanism rounding fix 

- PENDING.md
- types/address.go
- x/gov/depositsvotes.go
- x/gov/proposals.go
Fixes: https://github.com/cosmos/cosmos-sdk/issues/3810
There are some `Unmarshal` functions for specific structs where errors are not being returned properly. This PR fixes that.
> Fix nil returned in Unmarshal functions

- PENDING.md
- cmd/gaia/app/app.go
- cmd/gaia/app/genesis.go
- cmd/gaia/app/x/bank/handler.go
- cmd/gaia/app/x/bank/handler_test.go
- _Temporarily_ fork `x/bank` router into the gaia app modules to allow a custom message handling.
- Remove `send_enabled` genesis param
closes: #3802
credit: @sunnya97
/cc @jackzampolin @jaekwon @rigelrozanski @cwgoes 
----
______
For Admin Use:
> Custom MsgMultiSend Handler (x/bank fork)

- PENDING.md
- baseapp/baseapp.go
- baseapp/baseapp_test.go
- x/bank/app_test.go
- x/gov/endblocker_test.go
- x/gov/genesis_test.go
- x/gov/keeper_test.go
- x/gov/tally_test.go
- x/ibc/app_test.go
- x/mock/app_test.go
- x/mock/test_utils.go
- x/slashing/app_test.go
- x/staking/app_test.go
A series of small BaseApp security improvements spawned by a lovely review by @ValarDragon.
closes: #3791
closes: #3790
----
______
For Admin Use:
> BaseApp Security Improvements

- client/context/context.go
The output is currently single spaced, which IMO looks weird visually.
> JSON output for the CLI to 2 spaces

- .circleci/config.yml
- PENDING.md
Closes https://github.com/tendermint/devops/issues/198
Successful test [here](https://circleci.com/gh/cosmos/cosmos-sdk/88656)
______
For Admin Use:
> R4R: Removed complexity from docs deployment job

- client/keys/utils.go
> Modify magic string "json" to OutputFormatJSON

- docs/gaia/installation.md
Temporarily remove snap from installation instructions until it's been more thoroughly audited.
> Temporarily remove snap from installation instructions

- PENDING.md
- types/dec_coin.go
- x/distribution/keeper/keeper.go
- x/distribution/keeper/store.go
Fix `WithdrawValidatorCommission` to set the validator's remaining commission correctly (i.e. taking care of the case when the remainder is zero).
ref: #3830
closes: #3837
----
______
For Admin Use:
> Fix WithdrawValidatorCommission

- PENDING.md
- client/keys/add.go
`gaiacli keys add a123 --multisig a1,a2,a3 --multisig-threshold 2`
`gaiacli keys add temp --recover` with incorrect mnemonic
```bash
root@503a9ff8dd9c:/# gaiacli keys add a123 --multisig a1,a2,a3 --multisig-threshold 2
Key "a123" saved to disk.root@503a9ff8dd9c:/#
root@503a9ff8dd9c:/# gaiacli keys add temp --recover
Enter a passphrase to encrypt your key to disk:
Repeat the passphrase:
> Enter your bip39 mnemonic
1 2 3 4 5 6
Error: Mnemonic is not validroot@503a9ff8dd9c:/#
```
______
For Admin Use:
- Squashed all commits, uses message "Merge pull request #XYZ: …
> Add newline to echo of `gaiacli keys ...`

- PENDING.md
- types/coin.go
- types/coin_test.go
This is a sub-PR of https://github.com/cosmos/cosmos-sdk/pull/3678
It also removes duplicate tests.
______
For Admin Use:
> Make IsAllGTE() more consistent

- README.md
- docs/.vuepress/config.js
- docs/README.md
- docs/gaia/README.md
- docs/gaia/delegator-guide-cli.md
- docs/gaia/gaiacli.md
- docs/gaia/installation.md
- docs/gaia/join-mainnet.md
- docs/gaia/join-testnet.md
- docs/gaia/validators/validator-faq.md
- docs/gaia/validators/validator-setup.md
All docs ready for mainnet.
Still waiting for recommended `gas-prices` to merge.
______
For Admin Use:
> Update Docs for mainnet

- README.md
- docs/.vuepress/config.js
- docs/README.md
- docs/gaia/README.md
- docs/gaia/delegator-guide-cli.md
- docs/gaia/gaiacli.md
- docs/gaia/installation.md
- docs/gaia/join-mainnet.md
- docs/gaia/join-testnet.md
- docs/gaia/validators/validator-faq.md
- docs/gaia/validators/validator-setup.md
Cherry pick https://github.com/cosmos/cosmos-sdk/pull/3838 to master
______
For Admin Use:
> Mainnet docs update to master

- client/utils/utils.go
> R4R: Add indent to prompt of `gaiacli tx send`.

- .pending/bugfixes/gaiacli/3899-Using-gaiacli-c
- client/config.go
- client/config_test.go
Config file need to be truncated while rewriting.
close: #3899
______
For Admin Use:
> R4R: Fix #3899, Using `gaiacli config node` breaks ~/config/config.toml

- .pending/bugfixes/gaiacli/3883-Remove-Height-F
- client/flags.go
- docs/gaia/gaiacli.md
- docs/translations/kr/gaia/gaiacli.md
close: #3883
______
For Admin Use:
> R4R: Remove Height Flag from CLI Queries #3883

- .pending/bugfixes/sdk/3870-Fix-DecCoins-TruncateDecimal-to-never-return-zero-coins-in
- types/dec_coin.go
- types/dec_coin_test.go
- types/decimal.go
closes: #3870
ref: https://github.com/cosmos/cosmos-sdk/issues/3909
----
______
For Admin Use:
> Fix TruncateDecimal

- .pending/improvements/sdk/3917-Allow-arbitrary-decreases-to-validator-commission-rates
- x/staking/types/commission.go
- x/staking/types/commission_test.go
closes: #3917
----
______
For Admin Use:
> Allow Unrated Decreases to Validator Commission Rates

- cmd/sdkch/main.go
Make `sdkch` generate skip empty sections/stanzas entirely.
Remove `-prune` flag, it makes very little sense as `git rm -r .pending/` is the effective way to remove pending entries.
Add `prune` command to prune empty `.pending` subdirectories.
______
For Admin Use:
> sdkch various changes

- .pending/bugfixes/gaia/3825-Validate-genesis-before-running-gentx
- cmd/gaia/init/gentx.go
- Closes #3825
______
For Admin Use:
> Validate genesis before running gentx

- client/lcd/lcd_test.go
closes https://github.com/cosmos/cosmos-sdk/issues/3739
This simple code movement should do the trick, basically, this provides only two blocks for the slash to take place if this bug is to come up again. So this bug *may* still come up once in a blue blue moon - highly unlikely though. The actual solution is to restructure the lcd so that all the validators are signing..... 
CC @alexanderbez 
______
For Admin Use:
- Squashed all commits, uses message "Merge pull request #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/master/README.md#m …
> Fix lcd-testing 303030 bug continued

- docs/gaia/delegator-guide-cli.md
- docs/gaia/installation.md
Cherry pick https://github.com/cosmos/cosmos-sdk/pull/3922 to develop
______
For Admin Use:
> Cherry pick docs update to develop

- .pending/bugfixes/sdk/3915-Remove-delimiting-support-from-ParseDecCoins
- server/config/config.go
- server/config/toml.go
- types/coin.go
- types/dec_coin.go
closes: #3915
----
______
For Admin Use:
> Remove ';' delimiting support from ParseDecCoins

- docs/clients/service-providers.md
Update documentation to include details on how to sign Cosmos transactions for service providers.
______
For Admin Use:
> Documentation on how to sign Cosmos transactions

- .pending/improvements/gaiacli/3959-Improve-error-messages-when-signing-with-ledger-devices-fails
- .pending/improvements/gaiacli/3959-Improving-error-messages-when-signing-with-ledger-devices-fails
- go.mod
- go.sum
When a ledger device tries to sign a transaction and considers the message invalid, it generates a more specific error message than what it is being shown in the CLI.
Expose this error message.
Fixes are applied in the corresponding dependencies:
https://github.com/ZondaX/ledger-cosmos-go/pull/26
https://github.com/ZondaX/ledger-go/pull/7
Closes #3959 
______
For Admin Use:
> Upgrading dependencies

- .pending/bugfixes/gaia/3974-Fix-go-env-sett
- docs/gaia/installation.md
- docs/translations/cn/gaia/installation.md
- docs/translations/kr/gaia/installation.md
close: #3974
______
For Admin Use:
> Missing `source ~/.bash_profile` when setting the go environment #3974

- .pending/improvements/gaia/3893-Improve-gaiacli-tx-sign-command
- client/flags.go
- client/utils/utils.go
- x/auth/client/cli/sign.go
- x/auth/client/txbuilder/txbuilder.go
- x/bank/client/cli/sendtx.go
- Add shorthand flags `-a` and `-s` for the account and sequence numbers respectively
- Mark the account and sequence numbers required during "offline" mode
- _Always_ do an RPC query for account and sequence number during "online" mode
- If clients wish to provide such values, they must use `--offline`. This makes the whole flow/UX easier to reason about.
closes: #3893
/cc @yangyanqing
----
______
For Admin Use:
- Squashed all commits, uses message "Merge pull request #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/master/README.md#mer …
> Fix Tx Sign Offline Mode

- .pending/improvements/sdk/3986-Update-the-Stringer-implementation-of-the-Proposal-type
- x/gov/proposals.go
Fix the `Stringer` interface implementation for the `Proposal` type:
- Add missing description
- Fix indentation
----
______
For Admin Use:
> Fix Proposal Stringer

- .pending/features/gaiacli/3937-Add-command-to-query-community-pool
- .pending/features/gaiarest/3937-Add-route-to-fetch-community-pool
- .pending/improvements/sdk/3937-Implement-community-pool-querier
- client/lcd/swagger-ui/swagger.yaml
- docs/gaia/gaiacli.md
- x/distribution/client/cli/query.go
- x/distribution/client/module_client.go
- x/distribution/client/rest/query.go
- x/distribution/keeper/querier.go
- x/distribution/keeper/querier_test.go
Fixes: https://github.com/cosmos/cosmos-sdk/issues/3937
> Implement client functionality for the community pool

- cmd/gaia/app/export.go
> zero export bug

- cmd/gaia/cli_test/cli_test.go
Removed in ca43225851ec1e, wanting it back to avoid
running cli tests along with unit tests.
See #3994 for more info.
______
For Admin Use:
> Reintroduce cli_test built tag

- .circleci/config.yml
- .pending/bugfixes/sdk/3977-Fix-docker-imag
- Dockerfile
- Always build regardless of the branch;
push only from develop and master.
- Add curl to packages dependencies in Dockerfile
to allow golangci-lint to be downloaded.
Closes: #3977
______
For Admin Use:
> Fix docker_image ci job

- .pending/breaking/sdk/3245-Rename-validato
- types/staking.go
- x/slashing/handler.go
- x/slashing/handler_test.go
- x/slashing/keeper.go
- x/slashing/keeper_test.go
- x/staking/keeper/slash_test.go
- x/staking/types/validator.go
close:  #3245
______
For Admin Use:
> R4R: Rename validator.GetJailed() to validator.IsJailed() #3245

- .pending/bugfixes/gaia/3656-distribution-de
- .pending/bugfixes/gaia/3999-fix-distribution-export
- cmd/gaia/app/export.go
> V0.33.1 zero export bugfix

- docs/gaia/delegator-guide-cli.md
- docs/gaia/gaiacli.md
- docs/gaia/installation.md
- docs/gaia/join-mainnet.md
- docs/gaia/validators/validator-setup.md
Fix conflicts
______
For Admin Use:
> Fix conflicts 0.34

- .pending/improvements/sdk/3916-Hex-encode-data-in-tx-responses
- client/lcd/lcd_test.go
- types/result.go
closes: #3916 
----
______
For Admin Use:
> Hex Encode Data in Tx Responses

- cmd/gaia/cmd/gaiad/main.go
- docs/gaia/join-mainnet.md
> Gaia crisis-module manual

- .pending/improvements/gaia/4042-Add-description
- docs/gaia/installation.md
- docs/translations/cn/gaia/installation.md
- docs/translations/kr/gaia/installation.md
- scripts/install/install_sdk_arm.sh
- scripts/install/install_sdk_ubuntu.sh
> Add `GO111MODULE=on` to environment.

- .pending/bugfixes/sdk/4020-Fix-queryDelegationRewards-by-returning-an-error
- CHANGELOG.md
- x/distribution/keeper/querier.go
closes: #4020 
----
______
For Admin Use:
> Fix queryDelegationRewards

- CHANGELOG.md
- types/dec_coin.go
- types/dec_coin_test.go
- x/distribution/keeper/allocation.go
* Panic on zero decimal input
* Don't include zero decimal coins in results
* Add TOC to CHANGELOG to make it easier to navigate and add entries when working against release branches.
closes: #4050 
----
______
For Admin Use:
> Fix DecCoins Bugs

- .pending/improvements/gaia/4064-Remove-dep-and-
- Makefile
- docs/_attic/sdk/sdk-by-examples/simple-governance/running-the-application.md
- docs/gaia/installation.md
- docs/translations/cn/gaia/installation.md
- scripts/install/install_sdk_arm.sh
- scripts/install/install_sdk_bsd.sh
- scripts/install/install_sdk_ubuntu.sh
- version/version.go
> R4R: Remove `dep` and `vendor` from `doc` and `version`.

- .pending/improvements/gaia/4062-Remove-cmd-gaia
- cmd/gaia/cli_test/cli_test.go
- cmd/gaia/cli_test/test_helpers.go
- cmd/gaia/init/collect.go
- cmd/gaia/init/genesis_accts.go
- cmd/gaia/init/gentx.go
- cmd/gaia/init/init.go
- cmd/gaia/init/testnet.go
- cmd/gaia/init/utils.go
- cmd/gaia/init/utils_test.go
- cmd/gaia/init/validate_genesis.go
ExportGenesisFile() overwrites all non-gaia related
sections of the genesis.json file as it always
creates a new one from scratch.
Remove cmd/gaia/init.LoadGenesisDoc() in favor of
tendermint's types.GenesisDocFromFile().
Closes: #4066 
______
For Admin Use:
> gaiad: ExportGenesisFile() incorrectly overwrites genesis

- .pending/improvements/gaia/4080-add-missing-inv
- cmd/gaia/app/sim_test.go
- x/crisis/keeper.go
- x/simulation/util.go
just noticed there were a bunch of missing simulatulations in some moreless hidden code ;) 
______
For Admin Use:
> R4R Run missing invariants during simulations

- .pending/improvements/gaiacli/3426-remove-redundant-account-check
- cmd/gaia/cli_test/cli_test.go
- x/bank/client/cli/sendtx.go
- x/gov/client/cli/tx.go
> remove duplicated account check and test

- .pending/breaking/sdk/3775-unify-sender-tag
- client/lcd/lcd_test.go
- client/lcd/swagger-ui/swagger.yaml
- cmd/gaia/cli_test/cli_test.go
- docs/spec/distribution/06_tags.md
- docs/spec/governance/04_tags.md
- docs/spec/slashing/06_tags.md
- docs/spec/staking/06_tags.md
- types/tags.go
- x/crisis/handler.go
- x/crisis/tags/tags.go
- x/distribution/alias.go
- x/distribution/handler.go
- x/distribution/tags/tags.go
- x/gov/client/utils/query.go
- x/gov/handler.go
- x/gov/tags/tags.go
- x/slashing/handler.go
- x/slashing/tags/tags.go
- x/staking/client/rest/utils.go
- x/staking/handler.go
- x/staking/tags/tags.go
Closes #3775 
cc: @faboweb @jbibla 
______
For Admin Use:
> unified sender tag

- .pending/bugfixes/sdk/3705-Return-instead-of-null-when-querying-delegator-rewards
- x/distribution/alias.go
- x/distribution/client/common/common.go
- x/distribution/keeper/querier.go
Return `[]` instead of `null` by making the initial value an empty slice literal opposed to nil.
closes: #3705 
----
______
For Admin Use:
> Fix queryDelegatorTotalRewards

- CHANGELOG.md
- types/decimal.go
- types/staking.go
- x/distribution/keeper/delegation.go
- x/distribution/keeper/validator.go
- x/staking/types/validator.go
closes: #4088
----
______
For Admin Use:
> Account for Rounding Errors in Distribution Calculations

- .pending/breaking/gaia/4053-Add-inv-che
- client/config.go
- client/keys/add.go
- client/lcd/test_helpers.go
- client/rpc/codec.go
- cmd/gaia/app/app.go
- cmd/gaia/app/app_test.go
- cmd/gaia/app/invariants.go
- cmd/gaia/app/sim_test.go
- cmd/gaia/cmd/gaiacli/main.go
- cmd/gaia/cmd/gaiad/main.go
- cmd/gaia/cmd/gaiareplay/main.go
- crypto/amino.go
- crypto/keys/hd/fundraiser_test.go
- crypto/keys/hd/hdpath_test.go
- x/auth/client/txbuilder/txbuilder.go
- x/mint/client/module_client.go
Replace gaiad's `--assert-invariants-blockly` with `--inv-check-period`
Closes: #4053
______
For Admin Use:
> Replace assertInvariantsBlockly invariantsCheckFrequency

- .pending/improvements/sdk/3914-Implement-invariant-benchmarks-and-add-target-to-makefile
- Makefile
- cmd/gaia/app/sim_test.go
- types/invariant.go
- x/auth/client/txbuilder/txbuilder.go
- x/simulation/event_stats.go
- x/simulation/simulate.go
Implement `BenchmarkInvariants` which benchmarks each respective invariant that is registered with the crisis keeper against a simulated gaia app.
__Note__: The benchmark results for most invariants is extremely negligible with few blocks (< 1000). However, some invariants, namely `distr/can-withdraw` and `staking/delegator-shares` can take relatively significant time (>3s). The benchmark values for these two invariants can greatly differ depending on simulation parameters (e.g. seed, number of blocks and block size). 
Perhaps we should also attempt to simulate state that is more representative of what we can expect to see on mainnet (100 validators, significant amount of bonds and redelegations, many accounts, etc...)
e.g.
```
$ go test -mod=readonly -benchmem -run=^$ …
```
> Invariant Benchmarks

- .circleci/config.yml
- Makefile
- cmd/gaia/Makefile
- cmd/gaia/contrib/sim/multisim.sh
- cmd/gaia/sims.mk
- contrib/devtools/Makefile
Amend targets naming convention as per [1]:
- Switch from underscore '_' separated naming scheme to dash '-'
separated naming scheme.
- Replace test with check.
Simulations now live in their own Make module.
[1] https://www.gnu.org/prep/standards/html_node/Standard-Targets.html
Closes: #4102
______
For Admin Use:
> New Makefile for gaia

- .pending/improvements/sdk/3978-Return-ErrUnknownRequest-in-message-handlers-for-unknown
- types/errors.go
- x/bank/handler.go
- x/bank/handler_test.go
- x/crisis/handler.go
- x/crisis/handler_test.go
- x/distribution/handler.go
- x/gov/handler.go
- x/gov/handler_test.go
- x/ibc/handler.go
- x/ibc/handler_test.go
- x/slashing/handler.go
- x/slashing/handler_test.go
- x/staking/handler.go
- x/staking/handler_test.go
closes: #3978 
----
______
For Admin Use:
> Return correct error on invalid messages

- Makefile
- cmd/gaia/cli_test/cli_test.go
- cmd/gaia/cli_test/test_helpers.go
Preparation work for cli tests further parallelisation.
______
For Admin Use:
> Allow user to pass a custom BUILDDIR to test_cli

- client/context/context.go
- client/flags.go
- docs/cosmos-hub/gaiacli.md
- types/result.go
> Minor Fixes

- .pending/breaking/gaiacli/4142-Turn-gaiacli-tx
- client/context/context.go
- cmd/gaia/cli_test/test_helpers.go
- docs/cosmos-hub/gaiacli.md
- x/bank/client/cli/sendtx.go
Closes: #4142
______
For Admin Use:
> Turn --from into a positional argument in gaiacli tx send

- contrib/export/v0.33.x-to-v0.34.0.py
Update the python export script to properly migrate governance state. This state machine breaking [change](https://github.com/cosmos/cosmos-sdk/pull/3779) was included in the 0.34 release but was not documented and as a result was not included in the original script.
__Note__: A node will _not_ panic if this fix is not included, however, querying for past proposals will fail.
----
______
For Admin Use: …
> Fix v0.33.x export script to port gov data correctly

- .circleci/config.yml
- Makefile
- cmd/gaia/contrib/runsim/main.go
- cmd/gaia/sims.mk
`runsim` is a tool desinged to tackle issues the team at times struggle with while working with `multisim.sh`:
* rate limiting: by default `runsim` spawn `min(10,len(seeds))` processes. Max number of processes can be passed via `-j`.
* Spawns a process each simulation *and correctly repeals it* upon program termination, regardless of what caused the program to terminate (SIGINT, SIGTERM, seeds exhaustion).
It must be noted that it is not fully ABI-compatible with `multisim.sh`:
* Different output format.
* Genesis file path must be passed via the `-g` flag.
______
For Admin Use: …
> New experimental simulation runner

- .pending/features/sdk/4099-Update-the-staking-validators-endpoint-to-support
- client/lcd/swagger-ui/swagger.yaml
- client/tx/query.go
- types/staking.go
- x/staking/alias.go
- x/staking/client/rest/query.go
- x/staking/keeper/validator_test.go
- x/staking/querier/querier.go
- x/staking/querier/querier_test.go
- x/staking/types/validator.go
Support pagination and bond status query params in the `/staking/validators` REST endpoint. The default number of validators  returned is the max number of bonded validators and the default status is bonded.
closes: #4099 
----
______
For Admin Use:
> Update Staking Validators Rest Query

- CHANGELOG.md
- client/context/context.go
- client/flags.go
- docs/cosmos-hub/gaiacli.md
- types/result.go
This cherry picks #4135 already on `develop` to v0.34.2.
----
______
For Admin Use:
> Cherry pick 4135 v0.34.2

- contrib/devtools/Makefile
1. `make tools` will not updated `clog` when `clog/main.go` was changed,
except `${GOBIN}/clog` or `tools-stamp` was deleted. `gosum` has the
same problem.
2. $(GOBIN)/gosum was just like magic number.
______
______
For Admin Use:
> Fix dependency of devtools Makefile and clean code.

- .pending/bugfixes/gaiacli/4219-Empty-mnemonic-
- client/keys/add.go
- cmd/gaia/cli_test/cli_test.go
- cmd/gaia/cli_test/test_helpers.go
close: #4219 
The following codes can NOT fail, so I move `!bip39.IsMnemonicValid(mnemonic)`  into the range of human input.
```go
if len(mnemonic) == 0 {
// read entropy seed straight from crypto.Rand and convert to mnemonic
entropySeed, err := bip39.NewEntropy(mnemonicEntropySize)
if err != nil {
return err
}
mnemonic, err = bip39.NewMnemonic(entropySeed[:])
if err != nil {
return err
}
}
```
______
For Admin Use:
- Squashed all commits, uses message "Merge pull request #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/master/README.md# …
> R4R: Empty mnemonic should return error when recover key

- .pending/breaking/sdk/4230-Change-the-type
- .pending/bugfixes/sdk/4230-Properly-set-an
- baseapp/baseapp.go
- types/result.go
- types/result_test.go
- types/tags.go
> Minor cleanup in tx tags and response format

- .pending/bugfixes/sdk/4234-https-github-co
- x/bank/client/cli/sendtx.go
> Allow tx send (generate-only) to actually work offline

- Makefile
The go.sum target does not need to depend on tools to run successfully.
Closes: #4165
______
For Admin Use:
> Remove tools from go.sum deps

- client/lcd/swagger-ui/swagger.yaml
- cmd/gaia/cli_test/cli_test.go
- cmd/gaia/lcd_test/helpers_test.go
- docs/cosmos-hub/gaiacli.md
- x/params/client/cli/tx.go
- x/params/client/rest/rest.go
- x/params/client/utils/utils.go
- x/params/client/utils/utils_test.go
The values in `changes` in Parameter change proposals are now of type `json.RawMessage` so users no longer have to string-encode them leading to a better UX.
closes #4237
----
______
For Admin Use:
> Change User Supplied Param Change Value to json.RawMessage

- .pending/breaking/sdk/The-default-signatur
- .pending/improvements/sdk/Add-SetAddressVerifi
- .pending/improvements/sdk/Add-an-additional-pa
- cmd/gaia/app/app.go
- cmd/gaia/cmd/gaiadebug/hack.go
- types/address.go
- types/address_test.go
- types/config.go
- x/auth/ante.go
- x/auth/ante_test.go
- x/mock/app.go
Resolves #3685. (Was PR #4166 before the develop branch was removed.)
Adds:
* an additional parameter to `NewAnteHandler` for a custom `SignatureVerificationGasConsumer` (the existing one is now called `DefaultSigVerificationGasConsumer)
* add an `addressVerifier` field to `sdk.Config` which allows for custom address verification (to override the current fixed 20 byte address format)
Changes:
* the `DefaultSigVerificationGasConsumer` now uses type switching as opposed to string comparison. Other zones like Ethermint can now concretely specify which key types they accept.
---
______
For Admin Use:
- Added appropriate labels to PR (ex. wip, …
> Allow custom key types and address formats

- .pending/breaking/sdk/4250-BaseApp-Query-r
- .pending/features/sdk/4250-New-BaseApp-Set
- Makefile
- baseapp/baseapp.go
- baseapp/baseapp_test.go
- baseapp/options.go
- cmd/gaia/Makefile
- cmd/gaia/app/app.go
- version/command.go
- version/version.go
The version package is meant to be a convenience utility
that provides SDK consumers with a ready-to-use version
command that produces app's versioning information from
flags passed at compile time.
It will not make sense anymore for the baseapp package
to depend on the version package once gaia will have been
migrated away from the SDK main repository as we neither
want to make assumptions nor set expectations on downstream
apps buildsystems. Thus BaseApp now provides SetAppVersion()
and AppVersion() to to allow SDK consumers to set BaseApp's
version information string once the struct is initialised.
______
For Admin Use: …
> Remove baseapp dependency on the version package

- .pending/improvements/sdk/4235-Add-parameter-c
- .pending/improvements/sdk/4235-Update-the-mint
- cmd/gaia/app/sim_test.go
- x/gov/params.go
- x/gov/simulation/msgs.go
- x/mint/keeper.go
- x/mint/params.go
- x/params/simulation/msgs.go
- x/simulation/params.go
* Add parameter change proposal simulated messages
* Fix minting module params
* Implement `params.ParamSet` so we can set params with their respective unique keys individually
closes: #4235 
----
______
For Admin Use:
> Param Proposal Simulation Messages; Minting Params Fix

- cmd/gaia/cli_test/cli_test.go
- cmd/gaia/cli_test/test_helpers.go
- cmd/gaia/lcd_test/helpers_test.go
Some tests did not clean after themselves once they ran successfully.
______
For Admin Use:
> avoid clogging /tmp with test runs leftover

- cmd/gaia/lcd_test/helpers_test.go
> Discard error returned by os.RemoveAll() when pruning test dirs

- .pending/breaking/gaiarest/3942-Support-query-t
- client/lcd/swagger-ui/swagger.yaml
- client/tx/query.go
- client/tx/utils.go
- cmd/gaia/cli_test/cli_test.go
- cmd/gaia/cli_test/test_helpers.go
- cmd/gaia/lcd_test/helpers_test.go
- cmd/gaia/lcd_test/lcd_test.go
- types/result.go
- x/gov/client/utils/query.go
- x/staking/client/rest/query.go
- x/staking/client/rest/utils.go
close: #3942
replace: #3995
______
For Admin Use:
> R4R: Support query txs' TotalCount in GET /txs 

- .pending/improvements/gaiarest/4141-Fix-txs-encode-
- client/tx/encode.go
- cmd/gaia/lcd_test/lcd_test.go
closes: #4141
replace: 4147
______
For Admin Use:
> R4R: Fix /txs/encode endpoint

- .pending/breaking/gaia/4272-Merge-gaiarepla
- Makefile
- cmd/gaia/Makefile
- cmd/gaia/cmd/gaiad/main.go
- cmd/gaia/cmd/gaiad/replay.go
> Merge gaiareplay into gaiad to reduce number of binaries

- .pending/breaking/sdk/4263-RestServer-Star
- .pending/features/sdk/4263-Add---read-time
- client/flags.go
- client/lcd/root.go
closes: #4263
----
______
For Admin Use:
> Update REST Client to Support Custom R/W Timeouts

- .pending/bugfixes/sdk/4271-Fix-addGenesisA
- .pending/features/sdk/4271-Implement-Coins
- cmd/gaia/init/genesis_accts.go
- cmd/gaia/init/genesis_accts_test.go
- types/coin.go
- types/coin_test.go
closes: #4271
----
______
For Admin Use:
> Fix addGenesisAccount

- .circleci/config.yml
> Fix 'Using --password via the CLI is insecure' when building the docker image

- .pending/breaking/sdk/4305-GenerateOrBroad
- .pending/improvements/sdk/4305-The---generate-
- client/context/context.go
- client/flags.go
- client/utils/utils.go
- cmd/gaia/cli_test/cli_test.go
- cmd/gaia/init/gentx.go
- x/bank/client/cli/sendtx.go
- x/crisis/client/cli/tx.go
- x/distribution/client/cli/tx.go
- x/gov/client/cli/query.go
- x/gov/client/cli/tx.go
- x/gov/client/module_client.go
- x/ibc/client/cli/ibctx.go
- x/params/client/cli/tx.go
- x/slashing/client/cli/tx.go
- x/staking/client/cli/tx.go
https://github.com/cosmos/cosmos-sdk/pull/4234 did not fully prohibit `--generate-only` from working offline. This PR forces `--generate-only` to work offline and removes a lot of cruft from the tx generation process all-together.
closes: #4305 
----
______
For Admin Use:
> Allow generate-only to fully operate offline

- .circleci/config.yml
- docker_tagged job failed for release 0.34.4
- Closes #4330 
______
For Admin Use:
> CircleCI: Fix insecure password via CLI

- .pending/bugfixes/sdk/4273-Fix-usage-of-Ap
- x/staking/handler.go
This change set adds a pending entry file
to @mjackson001's original PR: #4274
Closes: #4273
______
For Admin Use:
> Fix AppendTags usage error

- .pending/improvements/sdk/2286-Improve-perform
- store/cachekv/memiterator.go
- store/cachekv/store.go
- store/cachekv/store_bench_test.go
- store/cachekv/store_test.go
closes: #2286
----
______
For Admin Use:
> R4R: CacheKVStore keep sorted items

- .circleci/config.yml
- .pending/improvements/gaia/4261-Upgrade-toolcha
- .pending/improvements/gaia/4343-Upgrade-toolcha
- README.md
- docs/cosmos-hub/installation.md
- docs/translations/cn/cosmos-hub/installation.md
- scripts/install/install_sdk_arm.sh
- scripts/install/install_sdk_bsd.sh
- scripts/install/install_sdk_ubuntu.sh
> Update go to 1.12.5

- x/simulation/params.go
This fixes the "panic: Governance deposit amount must be a valid sdk.Coins amount, is 0stake" that can happen in the simulator if `DepositParams/MinDeposit` samples the integer `0`.
______
For Admin Use:
> FIX: invalid 0stake deposit amount in sim

- .pending/bugfixes/sdk/4362-simulation-setu
- cmd/gaia/contrib/runsim/main.go
- x/simulation/params.go
closes #4362
For the record what was happening is all three integers set in `InitialLivenessWeightings` were set to 0 making the "total" of that equal to zero which caused an error for rand here:
https://github.com/cosmos/cosmos-sdk/blob/a23eb322c609e2be63a0ec386222c0411715ef1e/x/simulation/transition_matrix.go#L61
______
For Admin Use:
> R4R simulator bugfix for multisim 7601778

- x/simulation/params.go
This fixes the bug when the Random Fuzzer samples a `VotingParams/VotingPeriod` integer equals to `0`.
First apply the following patch to force `VotingPeriod=0`:
```
$ git diff
diff --git a/x/simulation/params.go b/x/simulation/params.go
index 12eb8e59..7cbf3783 100644
--- a/x/simulation/params.go
+++ b/x/simulation/params.go
@@ -59,7 +59,7 @@ var (
return sdk.Coins{sdk.NewInt64Coin(sdk.DefaultBondDenom, int64(RandIntBetween(r, 1, 1e3)))}
},
"VotingParams/VotingPeriod": func(r *rand.Rand) interface{} {
-                       return time.Duration(r.Intn(2*172800)) * time.Second
+                       return time.Duration(0) * time.Second
},
"TallyParams/Quorum": func(r *rand.Rand) interface{} {
return sdk.NewDecWithPrec(334, 3)
```
Then run:
`go test ./cmd/gaia/app -run …
> Random Fuzzer fix: avoids VotingPeriod=0

- .pending/features/gaia/4373-Don-t-Burn-Depo
- x/gov/endblocker.go
- x/gov/querier.go
- x/gov/tally.go
- x/gov/tally_test.go
closes #4373 as per [Cosmos Hub Governance Proposal 6](https://hubble.figment.network/cosmos/chains/cosmoshub-2/governance/proposals/6).
______
For Admin Use:
> R4R:  Don't Burn Deposits for Rejected Governance Proposals Unless Vetoed

- .pending/improvements/sdk/3655-Improve-signatu
- x/auth/ante.go
closes: #3655
/cc @faboweb 
----
______
For Admin Use:
> Improve sig verification error message

- .pending/bugfixes/sdk/4394-Fix-signature-c
- x/auth/ante.go
- x/auth/stdtx.go
- x/auth/stdtx_test.go
closes: #4394
----
______
For Admin Use:
> Use TxSigLimit instead of default constant value

- .pending/improvements/sdk/4384-WithdrawalTxSplitting
- x/distribution/client/cli/tx.go
- x/distribution/client/cli/tx_test.go
Due to HSM limitations (Ledger Nano S), big transactions such as withdrawing rewards from a large number of validators, may be rejected to due memory constraints.
This PR introduces an additional flag that allows splitting the withdrawal messages and generates several transactions. Users can then define the maximum number of messages that they want to use.
This is related to: https://github.com/cosmos/ledger-cosmos/issues/143
While we have extended limits to Nano X in the next release, it is important to provide an alternative to users of Nano S.
______
For Admin Use: …
> allow splitting withdrawal txs

- Makefile
- go.sum
closes: #4431
----
______
For Admin Use:
> Remove draw_deps target

- .pending/features/sdk/4144-Configurable-Be
- crypto/keys/hd/hdpath.go
- crypto/keys/hd/hdpath_test.go
- crypto/keys/keybase.go
- crypto/keys/keybase_test.go
- crypto/keys/lazy_keybase_test.go
- crypto/keys/types_test.go
- crypto/ledger_mock.go
- crypto/ledger_test.go
- types/address.go
- types/config.go
close: #4144 
______
For Admin Use:
> Configurable Bip44 CoinType & HdPath for SDK users

- .pending/features/sdk/2020-New-keys-export
- client/keys/export.go
- client/keys/export_test.go
- client/keys/import.go
- client/keys/import_test.go
- client/keys/root.go
- client/keys/root_test.go
- crypto/keys/keybase.go
- crypto/keys/lazy_keybase.go
- crypto/keys/lazy_keybase_test.go
- crypto/keys/types.go
Add Keybase's ExportPrivKey()/ImportPrivKey() API calls to export/import
ASCII-armored private keys. Relevant keys subcommands are provided as well.
Closes: #2020
______
For Admin Use:
> Implement private keys export/import symmetric functionalities

- client/context/context.go
- client/keys/parse.go
- client/keys/show.go
- client/keys/utils.go
- go.mod
- server/tm_cmds.go
- types/address.go
- types/address_test.go
- version/command.go
Closes: #4371
______
For Admin Use:
> Adopt YAML as human-readable text output

- .pending/bugfixes/sdk/4455-Print-null-whil
- x/staking/client/cli/query.go
- x/staking/querier/querier_test.go
close: #4455 
______
For Admin Use:
> R4R: Using `QueryWithData` to query unbonding delegations.

- .pending/improvements/sdk/4465-Unknown-subcomm
- client/utils/utils.go
- client/utils/utils_test.go
- x/crisis/client/module_client.go
- x/distribution/client/module_client.go
- x/gov/client/module_client.go
- x/mint/client/module_client.go
- x/slashing/client/module_client.go
- x/staking/client/module_client.go
Fixes #4284
Now prints:
```
gaiacli query distr comission --trust-node cosmos1234
ERROR: unknown command "comission" for "distr"
Did you mean this?
commission
```
Adds custom argument validation for subcommands with subcommands. Doesn't affect "query" or "tx" subcommands since they reside in gaia repo. All flags except help are disabled for these commands
______
For Admin Use:
> R4R: Support "unknown commands" for subcommands

- types/invariant.go
- types/module/module.go
- x/auth/module.go
- x/bank/invariants.go
- x/bank/module.go
- x/crisis/module.go
- x/distribution/keeper/invariants.go
- x/distribution/module.go
- x/gov/module.go
- x/mint/module.go
- x/slashing/module.go
- x/staking/keeper/invariants.go
- x/staking/module.go
as per slack discussions: 
Gautier [12:53 PM]
I feel the terminology of `sdk.InvariantRouter` is a bit confusing https://github.com/cosmos/cosmos-sdk/blob/master/types/module/module.go#L237-L241. When the `RegisterInvariants` function is called, it's actually the `keeper` of the `crisis` module that is passed https://github.com/cosmos/gaia/blob/master/app/app.go#L201. Why put the routes inside the keeper itself (https://github.com/cosmos/cosmos-sdk/blob/master/x/crisis/keeper.go#L15-L23) instead of defining a new router type in the `crisis` module, and have this type implement the `sdk.invariantRouter` interface?
fp4k   [1 hour ago]
@Gautier so the crisis keeper fundamentally requires the routes to perform it’s checks, because it implements `RegisterInvariants` is makes it an …
> R4R: InvariantRouter -> InvariantRegistry

- .pending/improvements/sdk/4501-Support-height-
- client/context/context.go
- client/tx/query.go
- types/rest/rest.go
- types/rest/rest_test.go
- x/auth/client/rest/query.go
- x/distribution/client/rest/query.go
- x/gov/client/rest/rest.go
- x/mint/client/rest/query.go
- x/slashing/client/rest/query.go
- x/staking/client/rest/query.go
- x/staking/client/rest/utils.go
Fixes #4501
______
For Admin Use:
> R4R: support height queries in rest client

- types/rest/rest.go
- types/rest/rest_test.go
Follow-up of #4505
Issue: #4501
______
For Admin Use:
> Negative height paramter's value leads to undefined behaviour

- codec/codec.go
- simapp/doc.go
- simapp/params.go
- simapp/sim_test.go
- simapp/test_util.go
- x/params/simulation/msgs.go
- x/simulation/params.go
- x/simulation/simulate.go
- x/simulation/util.go
- Cleanup simulation parameter output (uses JSON now)
- Move distribution parameter generation to simulation package
- Add simulation godoc (`doc.go`)
closes: #4428
/cc @npinto 
----
______
For Admin Use:
> Simulation: Params from File

- .pending/improvements/sdk/4536-cli-context-que
- client/context/query.go
- client/rpc/root.go
- client/utils/utils.go
- client/utils/utils_test.go
- x/auth/client/rest/query.go
- x/distribution/client/cli/query.go
- x/distribution/client/common/common.go
- x/distribution/client/rest/query.go
- x/gov/client/cli/query.go
- x/gov/client/rest/rest.go
- x/gov/client/utils/query.go
- x/ibc/client/cli/relay.go
- x/mint/client/cli/query.go
- x/mint/client/rest/query.go
- x/slashing/client/cli/query.go
- x/slashing/client/rest/query.go
- x/staking/client/cli/query.go
- x/staking/client/rest/query.go
- x/staking/client/rest/utils.go
closes: #4542 
----
______
For Admin Use:
> Return account queries with height

- .pending/improvements/sdk/4553-undelegate-max-entries-check-first
- x/staking/keeper/delegation.go
- x/staking/keeper/delegation_test.go
fix the issue
Undelegate may lose the delegator’s tokens when exceed the MaxEntries of unbonding delegations #4551
> fix undelegate losing tokens issue

- .pending/improvements/sdk/4564-Allow-empty-ans
- client/input/input.go
Closes: #4564
______
For Admin Use:
> Take empty input as yes answer

- .pending/improvements/sdk/4564-Allow-empty-ans
- client/input/input.go
- client/keys/add.go
GetConfirmation() returns true if and only if the user's
input is confirmative.
The function is used in places where fat-fingering may cause
financial loss, e.g. gaiacli tx send command. Thus it seems
wiser to provide a conservative default in order to protect
users from accidental mistyping.
Closes: #4564
______
For Admin Use:
> switch GetConfirmation()'s default to no

- .pending/features/sdk/4570-Move-bank-balan
- client/context/query.go
- x/auth/alias.go
- x/auth/client/rest/query.go
- x/auth/client/rest/rest.go
- x/auth/querier_test.go
- x/bank/alias.go
- x/bank/client/rest/query.go
- x/bank/client/rest/tx.go
- x/bank/internal/keeper/keeper_test.go
- x/bank/internal/keeper/querier.go
- x/bank/internal/keeper/querier_test.go
- x/bank/internal/types/key.go
- x/bank/internal/types/querier.go
- x/bank/module.go
- x/staking/exported/exported.go
- x/staking/types/keys.go
Closes: #4560
______
For Admin Use:
> Move /bank/balances/{address} REST endpoint into /x/bank

- .pending/improvements/sdk/4556-Added-IsValid-f
- types/coin.go
- types/coin_test.go
- types/denom_test.go
closes #4556 
______
For Admin Use:
> R4R: Added IsValid to Coin

- types/decimal.go
- types/int.go
- x/auth/types/account.go
- x/auth/types/account_test.go
- x/staking/types/validator_test.go
This fixes the `gaiacli query account` cranky YAML output.
______
For Admin Use:
> Fix BaseAccount's YAML serialization

- .pending/improvements/sdk/4580-remove-block-he
- types/context.go
- types/context_test.go
closes #4578 
______
For Admin Use:
> R4R: remove BlockHeight in context

- .pending/breaking/sdk/4588-Context-does-no
- client/alias.go
- client/context/context.go
- client/lcd/root.go
- x/auth/alias.go
- x/auth/client/cli/query.go
- x/auth/client/cli/tx_multisign.go
- x/auth/client/cli/tx_sign.go
- x/auth/client/rest/query.go
- x/auth/client/rest/rest.go
- x/auth/types/account.go
- x/bank/client/cli/tx.go
- x/crisis/client/cli/tx.go
- x/distribution/client/cli/tx.go
- x/gov/client/cli/tx.go
- x/ibc/client/cli/ibctx.go
- x/ibc/client/cli/relay.go
- x/params/client/cli/tx.go
- x/slashing/client/cli/tx.go
- x/staking/client/cli/tx.go
AccountDecoder is now entirely redundant.
client package now does no longer depend on x/auth.
Context: #4488
______
For Admin Use:
> Remove auth's AccountDecoder type

- .golangci.yml
Partially address #4589 
______
For Admin Use:
> Add goconst to enabled linters

- .golangci.yml
- .pending/bugfixes/sdk/4598-fix-check-bond-
- x/staking/handler.go
- x/staking/handler_test.go
closes #4598 
______
For Admin Use:
> Fix check denom

- server/start.go
- server/test_helpers.go
- server/util.go
Although ideally we really should find a way to test the server package
functionalities in isolation, we are in fact testing it by running the binaries.
This PR aims to increase the SDK's horrible coverage stats by largely
ignoring server.
______
For Admin Use:
> Increase server package's coverage by adding DONTCOVER

- .pending/improvements/sdk/4584-Update-bank-Kee
- x/bank/internal/keeper/invariants.go
- x/bank/internal/keeper/keeper.go
- x/bank/internal/types/expected_keepers.go
- x/bank/module.go
- x/bank/simulation.go
closes #4576 
______
For Admin Use:
> R4R: use expected keeper for bank module

- README.md
Remove reference to Snap Builds, they should be built on Gaia
______
For Admin Use:
> Remove snap badge from README

- .pending/improvements/sdk/4584-Update-bank-Kee
- x/auth/alias.go
- x/auth/client/rest/query.go
- x/auth/exported/exported.go
- x/auth/keeper.go
- x/auth/types/account.go
- x/auth/types/account_retriever.go
- x/auth/types/codec.go
- x/bank/internal/keeper/invariants.go
- x/bank/internal/keeper/keeper.go
- x/bank/internal/keeper/keeper_test.go
- x/bank/internal/types/expected_keepers.go
- x/bank/module.go
- x/bank/simulation.go
A continuation of @colin-axner's work...
closes: #4576 
----
______
For Admin Use:
> x/bank: Expected Keeeper

- docs/modules/SPEC.md
ref: https://github.com/cosmos/cosmos-sdk/issues/4438
----
______
For Admin Use:
> Module Structure Spec

- .pending/bugfixes/sdk/1351-https-github-co
- store/rootmulti/store.go
- store/rootmulti/store_test.go
- types/abci.go
Closes #1351 
The fix was proposed one year ago, and was recently moved to "proposal accepted". This enables no-empty-block to be enabled with cosmos-sdk code without any other breaking changes.
Note: I don't know of any relevant documentation as this is a bugfix. Please point me to any points I need to update if any.
______
For Admin Use:
> Only change rootmultistore hash when substore hashes change

- .pending/improvements/sdk/Revert-2284-https-gi
- server/util.go
Only valid with #4613 - please merge that first
This reverts https://github.com/cosmos/cosmos-sdk/pull/2284 as with https://github.com/cosmos/cosmos-sdk/pull/4613 we now support the `create_empty_blocks` config option. There is no issue, but approval for this PR was given in a review comment: https://github.com/cosmos/cosmos-sdk/pull/4613#issuecomment-505512700
As there were no tests for the functionality I removed, I see no need to add a test that this is no longer prohibited.
______
For Admin Use:
- Squashed all commits, uses message "Merge pull request #XYZ: …
> Don't reject config files with create_empty_blocks=false

- .circleci/config.yml
- .golangci.yml
- client/input/input.go
- client/rpc/block.go
- client/rpc/validators.go
- server/test_helpers.go
- server/util.go
- simapp/export.go
- tests/util.go
- x/genutil/client/cli/gentx.go
- x/gov/simulation/msgs.go
- x/staking/client/rest/utils.go
- Added gosec, staticcheck
______
For Admin Use:
> More linters - Gosec, staticcheck

- types/events.go
- types/events_test.go
- types/result.go
When events are stringified, they'll be easier to read if they're grouped by unique type.
----
______
For Admin Use:
> Pretty/Flatten Events by Type when Stringified

- .pending/improvements/sdk/remove-debugdb-color
- store/rootmulti/store_test.go
- tests/gobash.go
- Newdebugdb is removed from tendermint
- colors is removed from tendermint
______
For Admin Use:
> Remove debugdb & colors

- .pending/bugfixes/sdk/4654-validator-slash
- x/distribution/genesis.go
- x/distribution/keeper/key.go
- x/distribution/keeper/querier_test.go
- x/distribution/keeper/store.go
- x/distribution/keeper/validator.go
- x/distribution/types/genesis.go
Followup to fuzzer bug Icarus issue:
ref https://github.com/cosmos/cosmos-sdk/issues/4653
The solution (thanks @cwgoes) is to no longer average slash events by height:
> I believe there is a bug in consolidation of slash events by height.
Consider the following sequence of slashes:
> 1. Validator `A` is slashed. A new slash event is created.
> 2. A redelegation from validator `A` to `B` is slashed. The validator's period is incremented.
> 3. Validator `A` is again slashed. The previous slash event is updated, using the period from (2).
> 4. A redelegation from validator `A` to `B` is again slashed. The second slash event is now skipped > when it ought to have been included, since the ended period of the slash event is the same as the starting period of the modified delegation (after (2)). …
> validator slash event stored by period and height

- contrib/runsim/main.go
- contrib/runsim/notification.go
> R4R: runsim pushes logs to S3 bucket

- .pending/bugfixes/sdk/4681-mint-check
- x/mint/internal/keeper/keeper.go
- x/staking/keeper/pool.go
- x/supply/internal/keeper/account.go
- x/supply/internal/keeper/bank.go
- x/supply/internal/keeper/bank_test.go
The previous function for inflating the supply on the mint module, `InflateSupply` wasn't checking for neg amounts, nor 0 amounts. The first is already checked on `mint` due to the fact that we use `NewCoin` to initialize the coins from the `BlockProvision`. This PR fixes the second one where a consensus failure was caused if the minted coins where empty. 
Note that this check also exists for the two `burn` functions in `staking/keeper/pool.go`.
Fix on Gaia: cosmos/gaia#56
cc: @rigelrozanski @alexanderbez 
here's the prev `InflateSupply`:
```go
// when minting new tokens    
func (k Keeper) InflateSupply(ctx sdk.Context, newTokens sdk.Int) {    
pool := k.GetPool(ctx)    
pool.NotBondedTokens = pool.NotBondedTokens.Add(newTokens)    
k.SetPool(ctx, pool)    
}
```
- Targeted PR against …
> Add check before minting empty coins

- types/invariant.go
- x/bank/internal/keeper/invariants.go
- x/distribution/keeper/invariants.go
- x/gov/invariants.go
- x/staking/keeper/invariants.go
- x/supply/internal/keeper/invariants.go
Addresses comments from [here](https://github.com/cosmos/cosmos-sdk/pull/4707#pullrequestreview-260607459)
Example Output:
```
Starting the simulation from time Fri Dec  2 23:09:18 UTC 6783, unixtime 151912624158
Invariants broken after BeginBlock
staking: bonded and not bonded module account coins invariant
Pool's bonded tokens: 169651462950839
sum of bonded tokens: 169651462950839
not bonded token invariance:
Pool's not bonded tokens: 4457903820927
sum of not bonded tokens: 4457903820927
module accounts total (bonded + not bonded):
Module Accounts' tokens: 174109366771766
sum tokens:              174109366771766
invariant broken: false
staking: nonnegative power invariant
found invalid validator powers
invariant broken: false
staking: positive delegations invariant
0 invalid delegations …
```
> Update Invariant Printing

- CONTRIBUTING.md
- docs/architecture/README.md
- docs/architecture/adr-template.md
- Added a ADR section to the Contributing.md
- This will streamline and create a central palce for discussions
- Currently conversations are fragmented across platfroms and different forum posts,
the aim here is to move it all to one place and create a document to be used as
reference in the future for why SDK went in this direction.
My IDE formated the .md file, I can remove this if its a problem.
______
For Admin Use: …
> ADR section to Contribution

- .pending/improvements/sdk/4640-extend-DiffKVSt
- simapp/sim_test.go
- simapp/utils.go
- simapp/utils_test.go
- store/types/utils.go
- types/store.go
closes #4640 
______
For Admin Use:
> Extend DiffKVStores to return a list of KVPairs

- simapp/sim_test.go
- simapp/utils.go
- x/simulation/simulate.go
closes: #4747
-----
______
For Admin Use:
> Simulation: Allow the use of a custom genesis time

- .clog.yaml
- .github/PULL_REQUEST_TEMPLATE.md
- go.mod
- go.sum
> Update clog & Tags

- x/staking/legacy/v0_34/types.go
- x/staking/legacy/v0_36/migrate.go
- x/staking/legacy/v0_36/types.go
- x/staking/types/commission.go
- x/staking/types/validator_test.go
> Migrate Validators v0.36

- docs/spec/bank/04_events.md
- types/events.go
- x/bank/internal/keeper/keeper.go
- x/bank/internal/types/events.go
- x/distribution/keeper/allocation.go
- x/distribution/keeper/keeper.go
- x/distribution/types/events.go
- x/gov/deposit.go
- x/gov/types/events.go
- x/mint/abci.go
- x/mint/internal/types/events.go
- x/staking/handler.go
- x/staking/types/events.go
Add some missing event attributes that would be helpful for upstream consumers and clients.
----
______
For Admin Use:
> Add New Events Attributes

- .pending/bugfixes/cli/_4763-fix-flag-min-s
- x/staking/client/cli/tx.go
Fixes: #4763 
______
For Admin Use:
> fix flag min-self-delegation

- .pending/breaking/_All-REST-responses-
- .pending/bugfixes/_Return-height-in-re
- baseapp/baseapp.go
- client/context/query.go
- types/rest/rest.go
- types/rest/rest_test.go
Thanks for pairing with me on this @alexanderbez. The approach here is to first query for the height if it is not provided and then make queries use that height. This results in atomic queries w/ height getting properly returned.
closes: #4773
> Fix Height Queries

- .circleci/config.yml
- go.mod
- go.sum
Commit that referred to tools dependency does not exist in git history because of force push. Update go.mod to refer to latest commit
______
For Admin Use:
> Update tools dependency

- .pending/bugfixes/keys/_4338-fix-multisig-o
- crypto/keys/output.go
- crypto/keys/output_test.go
- crypto/keys/types.go
- crypto/keys/types_test.go
Fixes: #4338 
______
For Admin Use:
> fix multisig output

- client/lcd/root.go
This fixes a small regression inadvertently introduced
in 99df748dda8c8 that caused the REST server to return
"http: request body too large" on POST requests handling.
closes: #4845
----
______
For Admin Use:
> Rely on rpcserver.DefaultConfig() to inherit default config values

- types/errors.go
- types/errors_test.go
Implements the first part of #4844 (the non-breaking enhancement to transform any error into a Result). Maintain the current log format (json) and types/errors behaves almost identical to sdk error (just a bit more info in log, via Wrap). 
I can add a clog entry if needed, but this is really just internal code to support later refactoring. Just wanted to do it while I still had the types/errors package in my head.
______
For Admin Use: …
> Create sdk.Result from any error type
