cosmos/cosmos-sdk

- .pending/improvements/simulation/4824-PrintAllInvaria
- types/invariant.go
- x/bank/internal/keeper/invariants.go
- x/distribution/keeper/invariants.go
- x/gov/invariants.go
- x/simulation/util.go
- x/staking/keeper/invariants.go
- x/supply/internal/keeper/invariants.go
fixes #4824 
______
For Admin Use:
> print all failed invariants only

- .pending/features/store/4724-Multistore-supp
- baseapp/baseapp.go
- baseapp/baseapp_test.go
- baseapp/options.go
- server/mock/store.go
- store/rootmulti/store.go
- store/rootmulti/store_test.go
- store/types/store.go
- store/types/store_test.go
This is needed for the regen upgrade module (#4233), as there are cases (eg. 0.34 -> 0.36) where a substore is renamed (distr -> distribution). The current master panics when trying to read the store with an unknown key. This no longer panics, and allows the user to pass in a set of rename steps to actually rename the store upon loading (so other data migration steps of individual items can function) 
Provides a few different store loaders for testing and demonstration purposes. This actual functionality probably doesn't make too much sense to an end-user until #4233 is merged, but it may be needed in cases where one does want to rename stores before doing some debugging.
- Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/cosmos-sdk/blob/develop/CONTRIBUT …
> Allow substore migrations upon multistore loading

- simapp/app.go
- simapp/sim_test.go
- x/crisis/internal/keeper/keeper.go
- x/crisis/internal/keeper/keeper_test.go
- x/crisis/module.go
- Call the crisis module's end blocker in `SimApp`
- Fix invariant registration bug by passing the crisis module by reference
- Cleanup godocs and misc
closes: #4803
----
______
For Admin Use:
> Crisis Module Manager Fixes

- .pending/bugfixes/simulation/_Fix-non-determinism
- Makefile
- simapp/sim_test.go
- x/simulation/simulate.go
- x/simulation/util.go
- Fix the broken `test_sim_nondeterminism` make target (I'm scared to know how long this was broken for)
- Fix `TestAppStateDeterminism` to use CLI input params
- Fix `SimulateFromSeed` to actually panic (returns non-zero exit code)
- Some general cleanup
----
______
For Admin Use:
> Simulation Fixes

- .pending/bugfixes/cli/_4870-Disable-the-wi
- x/distribution/client/cli/tx.go
closes: #4870
----
______
For Admin Use:
> Disable "withdraw-all-rewards" command when "--generate-only" is supplied

- .pending/bugfixes/_4868-Context-CacheC
- types/context.go
closes: #4868
----
______
For Admin Use:
> Set New EventManager in Context#CacheContext

- x/coinswap/internal/keeper/swap.go
Relates: #4443 
Correct formula should be:
```
(1000 * x * ∆y) / (997 * (y - ∆y)) + 1
```
Which the spec describes in section 3.2.2: <https://github.com/runtimeverification/verified-smart-contracts/blob/uniswap/uniswap/x-y-k.pdf>
Am I right?
______
For Admin Use:
> Fix GetInputAmount formula

- .pending/bugfixes/tendermint/_4879-Don-t-terminat
- server/start.go
Add infinite loop at the end of startStandAlone() to prevent
the server process from exiting immediately after bootstrap.
Closes: #4879
______
For Admin Use:
> Fix standalone execution

- .pending/bugfixes/store/_Fix-IAVL-Store-to-p
- store/iavl/store.go
`MutableTree#DeleteVersion` only returns standard errors now.
----
______
For Admin Use:
> Fix IAVL Store Commit

- .pending/bugfixes/_4891-Disable-queryi
- client/context/query.go
- store/rootmulti/store.go
closes: #4891
----
______
For Admin Use:
> Lite Client Query Height Fix

- .pending/bugfixes/rest/_4858-Do-not-return-
- client/context/broadcast.go
When an invalid/failed tx is submitted with `block` mode, a proper REST response should be returned. Because we were returning an error, this wasn't happening.
closes: #4858
----
______
For Admin Use:
> Fix BroadcastTxCommit Response

- CHANGELOG.md
- baseapp/baseapp.go
- client/context/query.go
closes #4903
----
______
For Admin Use:
> Various Height Query Fixes

- CHANGELOG.md
- simapp/app.go
- simapp/app_test.go
fixes #4912 
______
For Admin Use:
> fix simapp black listed addr bug

- CHANGELOG.md
- client/input/input.go
Addressing the issue encountered here: https://github.com/e-money/em-ledger/issues/1
If the user does not enter a character in response to the CLI query `confirm transaction before signing and broadcasting [y/N]:` gaiacli will crash with a panic.
> Gaiacli should not panic when user just presses enter during Y/n confirmation

- CHANGELOG.md
- x/gov/client/cli/query.go
closes: #4927
----
______
For Admin Use:
> Fix gov query vote cmd

- CHANGELOG.md
- client/context/query.go
- client/input/input.go
- x/auth/client/rest/query.go
- x/auth/types/account_retriever.go
- x/gov/client/cli/query.go
> v0.37.0 rc2 cherry picks

- CHANGELOG.md
- server/start.go
> Enable CPU Profiling via CLI flag

- docs/DOCS_README.md
- remove mention of develop and staging env
______
For Admin Use:
> Quick fix to docs to not show staging website

- README.md
- docs/README.md
- this was found by nass, thankyou
- my eidtor does a quick fix for markdown, that is why you see some more changes
______
For Admin Use:
> Quick fix for broken links

- docs/versions
For docs deployment purposes `versions` file now contains `master`, so that when docs are deployed the script checks out `master` branch and builds all required files for the website.
> switch version to master

- store/cache/cache.go
- store/cache/cache_test.go
- store/rootmulti/store.go
- store/types/store.go
> Fix CacheMultiStoreWithVersion (inter-block cache)

- x/coinswap/client/cli/query.go
- x/coinswap/client/cli/tx.go
- x/coinswap/client/rest/query.go
- x/coinswap/client/rest/rest.go
- x/coinswap/client/rest/tx.go
- x/coinswap/internal/types/params.go
- x/coinswap/internal/types/querier.go
ref #4443 
Adding cli-commands for the coinswap module.
PLEASE NOTE: This PR is up for code review and is not intended to be merged into the master atm.
______
For Admin Use:
> Add cli commands for the coinswap module.

- Makefile
> Update Makefile runsim targets

- CHANGELOG.md
- baseapp/abci.go
- baseapp/baseapp.go
- baseapp/options.go
- server/config/config.go
- server/config/toml.go
- server/start.go
closes: #4979
----
______
For Admin Use:
> Add support for halt-time

- store/rootmulti/store.go
- store/rootmulti/store_test.go
Keeping the code DRY by utilizing `GetCommitKVStore` which now does the inter-block cache check/unwrapping. This should guarantee that whenever we get a store in the mapping, it's not wrapped.
----
______
For Admin Use:
> Fix and Utilize GetCommitKVStore

- x/auth/client/cli/query.go
EnsureExists just calls GetAccount, so there is no need to do this check
> Remove unnecessary account check

- .circleci/config.yml
- Makefile
- contrib/devtools/Makefile
Snake-case names are abandoned in favor of 
kebab-case naming convention.
Remove goimports from tools.
Ref: https://github.com/cosmos/gaia/issues/120
______
For Admin Use:
> Standardise and clean up Makefile

- CHANGELOG.md
- client/context/broadcast.go
- client/context/broadcast_test.go
- go.mod
- go.sum
- types/errors.go
closes: #4972 
----
______
For Admin Use:
> Expose precheck errors from tx

- x/auth/alias.go
- x/auth/exported/exported.go
- x/auth/exported/exported_test.go
- x/auth/genesis.go
- x/auth/simulation/genesis.go
- x/auth/types/genesis.go
- x/auth/types/genesis_test.go
Auxiliary type(s) and function(s) that used to exist in `x/genaccounts` that are needed for apps to define and use their own genesis accounts.
----
______
For Admin Use:
> Auxiliary Functionality for Genesis Accounts

- .golangci.yml
- baseapp/baseapp.go
- baseapp/baseapp_test.go
- server/mock/store.go
- types/errors/errors.go
- types/events.go
- types/module/module.go
- x/auth/types/stdtx.go
- x/distribution/client/common/common.go
- x/genutil/client/cli/migrate.go
- x/genutil/client/cli/migrate_test.go
- x/genutil/gentx.go
- x/gov/module.go
- added prealloc, golint, gosec
______
For Admin Use:
> Added Prealloc, Gosec, Golint linters

- .circleci/config.yml
- CHANGELOG.md
- Makefile
- README.md
- baseapp/baseapp.go
- baseapp/options.go
- go.mod
- go.sum
- server/config/config.go
- server/config/toml.go
- server/start.go
- types/result.go
- types/result_test.go
Cherry-pick PRs/commits from `master`:
- https://github.com/cosmos/cosmos-sdk/pull/5002
- https://github.com/cosmos/cosmos-sdk/pull/4989
- https://github.com/cosmos/cosmos-sdk/pull/5032
- https://github.com/cosmos/cosmos-sdk/pull/5015
- https://github.com/cosmos/cosmos-sdk/pull/4973
- https://github.com/cosmos/cosmos-sdk/pull/5005
- https://github.com/cosmos/cosmos-sdk/pull/5069
/cc @tnachen @jackzampolin 
----
______
For Admin Use: …
> v0.37.1 RC1 Cherry Picks

- CHANGELOG.md
- x/staking/legacy/v0_36/types.go
- x/staking/legacy/v0_37/types.go
closes: #5096 
______
For Admin Use:
> fixes migrate bug #5095

- .golangci.yml
- server/export.go
- simapp/sim_bench_test.go
- simapp/sim_test.go
- x/genutil/client/cli/migrate.go
- x/genutil/client/cli/migrate_test.go
- x/genutil/legacy/v0_38/migrate.go
- x/genutil/legacy/v0_38/migrate_test.go
- x/genutil/types/types.go
- x/staking/legacy/v0_38/migrate.go
- x/staking/legacy/v0_38/types.go
- Add TODO to return error in migration command instead of panic
- Fix version in `x/staking` (v0.37 to v0.38)
- Update v0.38 migration to include staking
----
______
For Admin Use:
> Migration Testing

- CHANGELOG.md
- client/keys/migrate.go
- client/keys/migrate_test.go
- client/keys/root.go
- client/keys/root_test.go
- crypto/keys/keybase_keyring.go
- crypto/keys/lazy_keybase_keyring.go
- crypto/keys/lazy_keybase_keyring_test.go
- types/config.go
Add new command to assist users migrate their keys from the legacy
on-disk keybase to the new OS keyring-based implementation.
Ref #4754
______
For Admin Use:
> Add keys migrate command

- store/state/mapping.go
- x/ibc/03-connection/cli.go
- x/ibc/03-connection/client/cli/query.go
- x/ibc/03-connection/client/cli/tx.go
- x/ibc/03-connection/client/utils/types.go
- x/ibc/03-connection/codec.go
- x/ibc/03-connection/handler.go
- x/ibc/03-connection/handshake.go
- x/ibc/03-connection/manager.go
- x/ibc/03-connection/msgs.go
- x/ibc/03-connection/tests/types.go
- x/ibc/03-connection/types.go
- x/ibc/23-commitment/store.go
- x/ibc/23-commitment/value.go
@mossid's upstream changes to #4517
______
For Admin Use:
> ICS 03 upstream changes

- CHANGELOG.md
- client/context/context.go
- client/context/verifier.go
- client/context/verifier_test.go
- Remove global verifier
- Remove verifier home (unused)
- Add chain ID and home dir to `CLIContext`
- Implement `CreateVerifier` which any `CLIContext` may call
- Each verifier directory will exist under `{home}/{chainID}/.lite_verifier`
Example:
```go
// main or parent chain (chain as if you're running without IBC)
mainCtx := context.NewCLIContext()
// connecting IBC chain
sideCtx := context.NewCLIContext().
WithChainID(sideChainID).
WithNodeURI(sideChainNodeURI) // or .WithClient(...)
sideCtx = sideCtx.WithVerifier(
context.CreateVerifier(sideCtx, context.DefaultVerifierCacheSize),
)
```
__Note__: All contexts share the same home directory for a CLI binary (i.e. there is no `WithHomeDir`).
closes: #5116
----
- Targeted PR against correct branch (see …
> Refactor CLIContext to allow multi-chain verifiers 

- CHANGELOG.md
- server/config/config.go
- server/config/toml.go
Fixes https://github.com/cosmos/cosmos-sdk/issues/4215
______
For Admin Use:
> feat: add pruning config to toml

- simapp/state.go
When a genesis file is provided to simulation, use the file's genesis time unless a custom genesis timestamp is provided by flag.
ref: https://github.com/cosmos/cosmos-sdk/pull/4750
----
______
For Admin Use:
> Use Genesis File Timestamp

- server/config/config.go
- server/config/toml.go
- store/store.go
Regression introduced by https://github.com/cosmos/cosmos-sdk/pull/5090
closes: #5165
----
______
For Admin Use:
> Fix App Config Template

- x/ibc/mock/recv/client/cli/query.go
- x/ibc/mock/send/client/cli/query.go
Test ibc on a chain that does not send or receive any ibc packets,
`
gaiacli --home ibc0/n0/gaiacli q ibcmocksend sequence chan0
`
will get the sequence 0, but
`
gaiacli --home ibc0/n0/gaiacli q ibcmocksend next chan0
`
will return 2.
> R4R: Fix next sequence query

- CHANGELOG.md
- x/staking/client/rest/swagger.go
- x/staking/client/rest/tx.go
> Add CreateValidator and EditValidator in REST

- CHANGELOG.md
- baseapp/baseapp.go
closes: #5200
----
______
For Admin Use:
> remove duplicate events from previous messages

- .github/stale.yml
- the current stale bot label is `wontfix` which seems to be incorrect, I believe `stale` would be a more approiate label
______
For Admin Use:
> Stalebot tag

- types/decimal.go
- types/decimal_test.go
Square Roots are a generally very useful mathematical operation that is present in most Number types and should be present in our custom Number type of `sdk.Decimal`.  Some examples of things it is useful for include Proportional Slashing (#5211), quadratic voting, and other social choice theory procedures (see: https://arxiv.org/pdf/1809.06421.pdf).
______
For Admin Use:
> Added sqrt function to sdk.Decimal type

- types/errors/errors.go
- x/ibc/23-commitment/keeper/keeper.go
- x/ibc/23-commitment/types/merkle.go
- x/ibc/24-host/errors.go
- x/ibc/24-host/validate.go
- x/ibc/24-validation/validate.go
This is a starting implementation of ICS24, which validates Identifier and Paths. More validations can be added in the future.
Closes #5209 
Create a generic validation function type along with default implementations.
______
For Admin Use:
> ICS 24 Implementation

- x/ibc/04-channel/keeper/handshake.go
- x/ibc/04-channel/keeper/packet.go
*  On `ChanOpenAck`, the  counterparty channel state should be `OPENTRY`.
*  On `RecvPacket`, its self channel should be related with `RecvPacket.DestPort` and `RecvPacket.DestChannel`.
> R4R - Fix channel and packet check

- x/ibc/02-client/client/cli/tx.go
- x/ibc/02-client/keeper/keeper.go
Store consensus by `KeyConsensusState` instead of `KeyClientState`.
> R4R - Store consensus state correctly

- x/bank/internal/keeper/querier.go
- x/distribution/keeper/querier.go
- x/gov/keeper/querier.go
- x/staking/keeper/querier.go
Works towards #4741 
______
For Admin Use:
> Ensure all the empty arrays return an empty slice

- docs/interfaces/service-providers.md
> "auth/StdTx" -> "cosmos-sdk/StdTx"

- .pending/bugfixes/keys/Fix-ledger-custom-co
- CHANGELOG.md
- baseapp/baseapp.go
- client/keys/add_ledger_test.go
- crypto/ledger_mock.go
- crypto/ledger_secp256k1.go
- go.mod
- go.sum
Cherry-Pick the following from `master`:
- https://github.com/cosmos/cosmos-sdk/pull/5208
- https://github.com/cosmos/cosmos-sdk/pull/5261
- https://github.com/cosmos/cosmos-sdk/pull/4716
----
______
For Admin Use:
> v0.37.4-rc1 Cherry Picks

- x/ibc/02-client/alias.go
- x/ibc/02-client/exported/exported.go
- x/ibc/02-client/keeper/client.go
- x/ibc/02-client/keeper/keeper.go
- x/ibc/02-client/keeper/querier.go
- x/ibc/02-client/types/codec.go
- x/ibc/02-client/types/errors/errors.go
- x/ibc/02-client/types/msgs.go
- x/ibc/02-client/types/tendermint/codec.go
- x/ibc/02-client/types/tendermint/misbehaviour.go
- x/ibc/02-client/types/tendermint/misbehaviour_test.go
- x/ibc/24-host/errors.go
Address implementation of: #5076 
Create concrete implementation of Evidence interface, fill in CheckMisbehavior functionality
______
For Admin Use:
> Integrate Evidence Implementation into ICS-02

- CHANGELOG.md
- store/iavl/store.go
closes: https://github.com/cosmos/cosmos-sdk/issues/5276
credit: @wangkui0508 🎉 
----
______
For Admin Use:
> Fix IAVL Iterator Race Condition

- CHANGELOG.md
- client/keys/parse.go
Reverts cosmos/cosmos-sdk#5092 due to race condition (e.g. [here](https://circleci.com/gh/cosmos/cosmos-sdk/146878#tests/containers/3))
/cc @elvin-du any chance you can look into this?
> Revert "changed bench32prefixes, gaiacli keys parse command still use cosmos …"

- docs/intro/sdk-design.md
Just walking through the intro docs to familiarize myself I noticed links to `ocap.md` were incorrect. There was a typo in the link on line 83, and an incorrect link on line 94. I believe I updated it to the correct location.
> Fix links to ocap

- x/ibc/02-client/keeper/client_test.go
- x/ibc/02-client/keeper/keeper_test.go
- x/ibc/02-client/types/tendermint/consensus_state_test.go
- x/ibc/02-client/types/tendermint/tendermint_test.go
- x/ibc/02-client/types/tendermint/test_utils.go
closes: https://github.com/cosmos/cosmos-sdk/issues/5311
______
For Admin Use:
> ICS-02: Keeper Tests

- docs/spec/README.md
> Fix dangling link in docs/spec/

- client/keys/utils.go
- crypto/keys/keyring.go
Document the usage of the COSMOS_SDK_TEST_KEYRING
environment variable for testing purposes.
______
For Admin Use:
> Add dev docs for COSMOS_SDK_TEST_KEYRING

- CHANGELOG.md
- client/keys/delete.go
- client/keys/list.go
- client/keys/list_test.go
* Add --list-names flag to keys command for short listing.
* Make keys delete accept multiple key names at once.
Usage example:
* gaiacli keys list -n | xargs gaiacli keys delete
______
______
For admin use:
> Small non-breaking UX changes to keys {list,delete} commands

- simapp/params/weights.go
- x/distribution/alias.go
- x/distribution/client/cli/tx.go
- x/distribution/client/rest/tx.go
- x/distribution/handler.go
- x/distribution/keeper/keeper.go
- x/distribution/keeper/keeper_test.go
- x/distribution/simulation/operations.go
- x/distribution/types/msg.go
- x/distribution/types/msg_test.go
A continuation of https://github.com/cosmos/cosmos-sdk/pull/5249 that performs some cleanup, addressing some unresolved comments and supporting simulation for the new message type.
______
______
For admin use:
> Fund Community Pool -- Part II

- client/keys/utils.go
- crypto/keys/keyring.go
Missing options applied after changes from #5278. I apologize I was not thorough enough to test after the final update through the full flow. There was some logic changed just before the PR was merged in and after going through the complete flow of regenerating keys to test I noticed some cases were missed. I should have retested everything after each update, sorry.
______
______
For admin use:
> Apply options on missed keyring types

- CHANGELOG.md
- types/dec_coin.go
- types/dec_coin_test.go
Closes: #5408
______
______
For admin use:
> fix DecCoins constructor

- x/genutil/client/cli/gentx.go
Workaround for #5403, users are still prompted for password twice.
______
______
For admin use:
> Reduce password prompt duplication when using keyring's file backend

- x/ibc/02-client/client/cli/query.go
- x/ibc/02-client/client/rest/query.go
- x/ibc/02-client/client/utils/utils.go
Closes: #5423 
______
______
For admin use:
> fix ICS02 queries

- docs/architecture/adr-003-dynamic-capability-store.md
Closes https://github.com/cosmos/cosmos-sdk/issues/5416; see details on that issue.
______
For admin use:
> ADR 003 follow-up

- CHANGELOG.md
- docs/core/events.md
- x/auth/client/cli/query.go
- Remove old "tags" nomenclature
- Use `=` instead of `:` to align and be consistent with the API variant
- Cleanup events doc
______
______
For admin use:
> Update Query Txs by Events Command

- CHANGELOG.md
- docs/core/events.md
- x/auth/client/cli/query.go
Cherry-pick the following from `master`:
- https://github.com/cosmos/cosmos-sdk/pull/5482
______
______
For admin use:
> v0.37.5-rc2 🍒 Picks (Final)

- types/errors/errors.go
- types/errors/errors_test.go
Closes: #5481
Add built-in `errors.Is` and `errors.Unwrap` support for wrappedError of `types/errors`.
I had to skip the `errors.As` support, because each errors replaced with `withStack` type, so the parent won't match the original error type. I don't think that the errors.As is urgent to implement, but if I can add an extra field as `original error` it can keep the type of it.
______
______
For admin use:
> Add errors.Is support to the wrappedError

- go.mod
- go.sum
Closes: #XXX
______
______
For admin use:
> Fix keyring error message on macos

- CHANGELOG.md
- x/auth/module.go
- x/bank/module.go
- x/crisis/module.go
- x/distribution/module.go
- x/evidence/module.go
- x/genutil/client/cli/validate_genesis.go
- x/genutil/genesis.go
- x/genutil/module.go
- x/genutil/types/genesis_state.go
- x/gov/module.go
- x/mint/module.go
- x/slashing/module.go
- x/staking/module.go
- x/supply/module.go
Closes: #5086
- Ensure `gentxs` default genesis state is not `nil`
- Cleanup and add context to `ValidateGenesis` methods.
______
______
For admin use:
> Cleanup genesis state validation + Genutil

- crypto/keys/types.go
Need to move `Algo` to be the last field in the `KeyInfo` structs so that they they can unmarshal old KeyInfo amino encodings in a backwards compatible way.
Closes: #XXX
______
______
For admin use:
> Fixed backwards amino compatibility for KeyInfo types

- x/ibc/03-connection/types/connection.go
- x/ibc/04-channel/types/msgs_test.go
- x/ibc/04-channel/types/packet_test.go
- Add `ValidateBasic` tests for `MsgTimeout` and `MsgAcknowledgement` (ICS 4)
- Add `ValidateBasic` tests for `Packet` (ICS 4)
> Continue help with ICS 7 tests

- CHANGELOG.md
- crypto/keys/keyring.go
Add support for KDE Wallet service and the pass command line tool.
______
______
For admin use:
> [keyring] support for kwallet, pass

- client/context/context.go
- client/keys/add.go
- client/keys/add_ledger_test.go
- client/keys/add_test.go
- client/keys/delete.go
- client/keys/delete_test.go
- client/keys/export.go
- client/keys/export_test.go
- client/keys/import.go
- client/keys/import_test.go
- client/keys/list.go
- client/keys/list_test.go
- client/keys/migrate.go
- client/keys/show.go
- client/keys/show_test.go
- crypto/keys/keyring.go
- types/config.go
- x/auth/client/cli/tx_multisign.go
- x/auth/types/txbuilder.go
- x/genutil/client/cli/gentx.go
Remove KeyringServiceName from sdk Config structure.
Clients can pass the app name as parameter to the constructor, whilst SDK commands
will inherit it from the build flag `-x github.com/cosmos-sdk/version.Name`.
Plus, NewKeyring()'s serviceName parameter is now renamed to appName.
______
______
For admin use:
> Remove KeyringServiceName from the sdk.Config struct

- CHANGELOG.md
- types/address.go
- types/address_test.go
Per @jackzampolin's request.
______
______
For admin use:
> Add convenience functions {,Must}Bech32ifyAddressBytes

- CHANGELOG.md
- x/staking/types/historical_info.go
- x/staking/types/validator.go
- x/staking/types/validator_test.go
Add util functions :
- `ToTmValidator`: that converts a `staking.Validator` type to `*tmtypes.Validator`
- `ToTmValidators`: that converts a `staking.Validators` type to `[]*tmtypes.Validator`
______
______
For admin use:
> Staking additions for IBC

- x/auth/legacy/v0_38/migrate.go
- x/auth/legacy/v0_38/types.go
- x/auth/legacy/v0_39/migrate.go
- x/auth/legacy/v0_39/migrate_test.go
- x/auth/legacy/v0_39/types.go
- x/bank/legacy/v0_38/types.go
- x/bank/legacy/v0_39/migrate.go
- x/bank/legacy/v0_39/migrate_test.go
- x/bank/legacy/v0_39/types.go
- x/genutil/client/cli/migrate.go
- x/genutil/legacy/v0_39/migrate.go
Part III (final) PR of #5572 -- genesis migration for ADR 004 slated for v0.39:
- Remove coins from JSON encoding of existing accounts in the `x/auth` genesis state.
- Add existing account coins to new balances genesis in `x/bank`.
______
______
For admin use:
> ADR 004 Geneis Migration

- CHANGELOG.md
- x/staking/keeper/delegation.go
- x/staking/keeper/val_state_change.go
- x/staking/spec/07_events.md
Include total unbonding and redelegation balances in events.
closes: #5564 
______
______
For admin use:
> Include Amount in Complete Unbonding/Redelegation Events

- x/bank/internal/keeper/keeper.go
- x/bank/internal/keeper/keeper_test.go
With the merging of #5572, a regression occurred where when you send tokens to a new (non-existent account), the new account balance is created (in `x/bank`), _but the actual account is not created_ in `x/auth`.
______
______
For admin use:
> Create Account on SendCoins

- CHANGELOG.md
- client/context/query.go
When creating a CLI context with no trusted node and no verifier, the `/block/xxx` is crashing. This PR adds a test to make sure that the verifier is present; if not, it returns an error.
______
______
For admin use:
> Add test of missing verifier in cli context

- CHANGELOG.md
- x/genutil/types/genesis_state.go
- x/genutil/types/genesis_state_test.go
Closes: https://github.com/cosmos/cosmos-sdk/issues/5086
Ensure we never have `null` in our genesis for gentxs.
______
______
For admin use:
> ensure non-nil gentxs

- CHANGELOG.md
- baseapp/baseapp_test.go
- server/start.go
- store/cache/cache_test.go
- store/iavl/store.go
- store/iavl/store_test.go
- store/prefix/store_test.go
- store/rootmulti/store.go
- store/rootmulti/store_test.go
- store/types/pruning.go
- x/bank/internal/keeper/keeper.go
- x/bank/internal/keeper/keeper_test.go
- x/bank/spec/04_events.md
- x/gov/abci.go
- x/staking/keeper/delegation.go
- x/staking/keeper/val_state_change.go
- x/staking/spec/07_events.md
closes: #5574
______
______
For admin use:
> v0.38.1 RC1

- CHANGELOG.md
- simapp/codec/msgs.go
- x/auth/alias.go
- x/auth/client/cli/query.go
- x/auth/client/rest/query.go
- x/auth/client/rest/rest.go
- x/auth/keeper/querier.go
- x/auth/types/account_retriever_test.go
- x/auth/types/keys.go
- x/auth/types/querier.go
- x/evidence/handler_test.go
- x/evidence/types/msgs_test.go
- Add parameter querying support to `x/auth`
______
______
For admin use:
> Add Param Querying to x/auth

- x/distribution/types/types.proto
Correct `ditribution` -> `distribution`
______
______
For admin use:
> Fix typo in distribution proto package name

- docs/core/events.md
A code section in the documentation is not valid (https://docs.cosmos.network/master/core/events.html).
This fixes the documentation and adds the proto type definition in the documentation instead of a werid `XXX_Merge` function ;)
______
For admin use:
> fix type for the event documentation

- .circleci/config.yml
- CHANGELOG.md
- README.md
- go.mod
> Build with Go 1.14

- CHANGELOG.md
- baseapp/baseapp.go
closes: #5713
______
______
For admin use:
> Return Empty GasInfo on Failed Msg Validation

- .golangci.yml
- x/gov/keeper/test_common.go
Fix gocritic,deadcode warnings.
Tweat .golangcy.yml to make it work with Goland's
Golint plugin.
Explicitly disable all linters. Whitelist of enabled linters
is already provided.
______
______
For admin use:
> linter fixes

- client/keys/add_ledger_test.go
- client/keys/add_test.go
- client/keys/delete_test.go
- client/keys/export_test.go
- client/keys/import_test.go
- client/keys/list_test.go
- client/keys/migrate_test.go
- client/keys/mnemonic_test.go
- client/keys/show_test.go
- client/keys/types_test.go
- client/keys/update_test.go
- crypto/keys/keyring_test.go
- crypto/keys/lazy_keybase_test.go
- server/constructors_test.go
- server/init_test.go
- x/genutil/client/cli/init_test.go
- x/genutil/client/cli/migrate_test.go
- x/genutil/utils_test.go
- x/upgrade/types/storeloader_test.go
In Go 1.14, the testing package now includes a method,
testing.(*T).Cleanup, which aims to make creating and
cleaning up dependencies of tests easier.
Drop defer function calls in favour of Cleanup() wherever
it makes sense to do so.
______
______
For admin use:
> Replace defer with testing.T.Cleanup()

- CHANGELOG.md
- client/keys/show.go
- crypto/keys/keybase.go
- crypto/keys/keybase_base.go
- crypto/keys/keybase_test.go
- crypto/keys/keyerror/errors_test.go
- crypto/keys/keyring.go
- crypto/keys/keyring_test.go
- crypto/keys/mintkey/mintkey.go
- crypto/keys/mintkey/mintkey_test.go
- crypto/ledger_secp256k1.go
- crypto/ledger_test.go
crypto.LedgerShowAddress() is a ledger specific function
and should takes acc address prefix instead of depending
on a sdk.Config singleton.
crypto/keys/mintkey:
- decryptPrivKey() return error instead of os.Exit()ing.
- encryptPrivKey() should panic instead of os.Exit() when
bcrypt.GenerateFromPassword() call fails so that the
caller is given a chance to recover().
crypto/keys:
- SignWithLedger() does not need to be method of
baseKeybase. Method receiver is unused.
- ledgerInfo objecta may be pointers, type switch
should handle both to avoid panics.
- keyringKeybase should not provide Update() at all.
More test cases are added to increase package crypto
and subpackages overall coverage.
______
______
For admin use:
> crypto: cleanup, more testing

- CHANGELOG.md
- crypto/keys/keyring.go
Closes: #XXX
Error message is not printed when password input fails.
So it's hard to determine the cause.
```bash
> ${CLI} keys add jack
Enter keyring passphrase:
Enter keyring passphrase:
Enter keyring passphrase:
panic: too many failed passphrase attempts
```
______
______
For admin use:
> crypto: print an error message if the password input failed

- CHANGELOG.md
- types/handler.go
- types/handler_test.go
ChainAnteDecorators() panics when no arguments are supplied.
This changes its behaviour and the function now returns a nil
AnteHandler in case no AnteDecorator instances are supplied.
Closes: #5741
______
______
For admin use:
> fix types.ChainAnteDecorators() panic

- CHANGELOG.md
- x/genutil/module.go
Closes: #5765
Fix `x/genutil` `ExportGenesis` as to not return null, but instead default genesis state (`[]`), so on export, genesis validation should pass.
______
______
For admin use:
> Fix x/genutil ExportGenesis

- CHANGELOG.md
- types/module/module_test.go
- types/rest/rest.go
- types/rest/rest_test.go
Drop unused functions:
- ParseQueryParamBool()
- ParseInt64OrReturnBadRequest()
______
______
For admin use:
> types/rest: add unit tests

- CHANGELOG.md
- client/lcd/swagger-ui/swagger.yaml
- types/rest/rest.go
- types/rest/rest_test.go
- x/auth/module.go
- x/bank/module.go
- x/crisis/module.go
- x/distribution/client/cli/query.go
- x/distribution/client/common/common.go
- x/distribution/client/common/common_test.go
- x/distribution/client/rest/query.go
- x/distribution/module.go
- x/genutil/client/cli/validate_genesis.go
- x/genutil/genesis.go
- x/genutil/module.go
- x/genutil/types/genesis_state.go
- x/genutil/types/genesis_state_test.go
- x/gov/module.go
- x/mint/module.go
- x/slashing/module.go
- x/staking/module.go
- x/supply/module.go
Closes: #5716
______
______
For admin use:
> v0.37.8-RC1 Cherry Picks

- CHANGELOG.md
- crypto/keys/keybase_base.go
- crypto/keys/types.go
Revert some changes done here:
https://github.com/cosmos/cosmos-sdk/pull/5799/
______
______
For admin use:
> Revert changes for keybase encoding.

- x/ibc/04-channel/keeper/packet.go
- x/ibc/04-channel/types/events.go
Emits event with packet information on SendPacket. This is necessary so relayer can listen to events on chainA and relay any sent packets to chainB to receive
______
______
For admin use:
> Emit Packet Event on SendPacket

- CHANGELOG.md
- crypto/keys/mintkey/mintkey.go
- crypto/keys/mintkey/mintkey_test.go
Check error returned by internal call to unarmorBytes()
and handle accordingly.
Handle empty version field adequately.
______
______
For admin use:
> crypto/keys/mintkey: fix errors handling in UnarmorPubKeyBytes

- CHANGELOG.md
- crypto/keys/keybase.go
- crypto/keys/keyring.go
- crypto/keys/keyring_test.go
- crypto/keys/lazy_keybase.go
- crypto/keys/types.go
There is no issue, was commented in a call with @alessio.
______
______
For admin use:
> Remove CloseDB method from Keybase interface

- CHANGELOG.md
- baseapp/abci.go
- baseapp/baseapp_test.go
- types/result.go
- x/auth/client/tx.go
- x/auth/client/tx_test.go
Closes: #5837
______
______
For admin use:
> baseapp: add sdk.Result to simulation response

- CHANGELOG.md
- crypto/keys/keybase.go
- crypto/keys/keybase_base.go
- crypto/keys/keybase_test.go
- crypto/keys/keyring.go
- crypto/keys/keyring_test.go
Keybase implementations should return errors when
signature generation is attempted with offline/multisig
keys since theyr lack private keys.
This is a change in Keyring/Keybase.Sign() methods
semantics that have been broken for long time.
______
______
For admin use:
> crypto/keys: remove DecodeSignature from baseKeybase

- .circleci/config.yml
`.codecov.yml` is not working. We should filter out all
generated code that we don't want to be included in
the coverage report.
______
______
For admin use:
> exclude generated code from code coverage statistics

- types/errors/abci_test.go
- types/errors/errors.go
- types/errors/errors_test.go
- types/errors/stacktrace_test.go
Wrap(ErrInsufficientFunds, "40 < 500") returns strings like
"insufficient funds: 40 < 50". Although he function syntax
fits perfectly SDK app developers use case and as such it
should not be changed, the interface is still counter-intuitive
as most Golang developers may reasonably expect a different
result similar to what other popular libraries' (see [1])
would produce (e.g. "40 < 500: insufficient funds").
Follow up PR of #5876.
[1] https://godoc.org/github.com/pkg/errors#Wrapf
______
______
For admin use:
> types/errors: make Wrap() work like github.com/pkg/errors.Wrap

- CHANGELOG.md
- client/keys/add.go
- client/keys/list.go
- client/keys/parse.go
- client/keys/parse_test.go
- client/keys/show.go
- client/keys/show_test.go
- client/keys/utils.go
- crypto/keyring/db_keybase.go
- crypto/keyring/keyring.go
Keyrings store keys by name and hexbytes representation
of address. This turns keyring internal storage more
chain-agnostic and types.Config independent.
Obsolete Keybase internal state representation is not affected.
______
______
For admin use:
> crypto/keyring: change addrKey to store chain-agnostic addresses

- CHANGELOG.md
- client/config.go
- client/config_test.go
Closes: #5895
Thanks: @njmurarka for pointing this out.
______
______
For admin use:
> client: show defaults when config help screen is displayed

- x/auth/types/params.go
- x/auth/types/params_test.go
Add few test cases.
______
______
For admin use:
> x/auth: use validateMaxMemoCharacters() for memo fields

- CHANGELOG.md
- client/rpc/block.go
- client/rpc/status.go
- client/rpc/validators.go
- client/tx/tx.go
- types/rest/rest.go
- types/rest/rest_test.go
- x/auth/client/rest.go
- x/auth/client/rest/broadcast.go
- x/auth/client/rest/decode.go
- x/auth/client/rest/encode.go
- x/auth/client/rest/query.go
- x/bank/client/rest/query.go
- x/bank/client/rest/tx.go
- x/distribution/client/rest/query.go
- x/distribution/client/rest/rest.go
- x/distribution/client/rest/tx.go
- x/evidence/client/rest/query.go
- x/gov/client/rest/query.go
- x/gov/client/rest/tx.go
- x/mint/client/rest/query.go
- x/params/client/rest/rest.go
- x/slashing/client/rest/query.go
- x/slashing/client/rest/tx.go
- x/staking/client/rest/query.go
- x/staking/client/rest/tx.go
- x/staking/client/rest/utils.go
- x/supply/client/rest/query.go
- x/upgrade/client/rest/query.go
- x/upgrade/client/rest/tx.go
Closes: #XXX
______
______
For admin use:
> types/rest: convenience functions for error checking

- docs/architecture/README.md
- docs/architecture/adr-021-protobuf-query-encoding.md
/cc @alexanderbez 
______
______
For admin use:
> ADR 021 - Protocol Buffer Query Support

- x/bank/client/cli/tx.go
- x/crisis/client/cli/tx.go
ref: https://github.com/cosmos/cosmos-sdk/issues/5864
______
______
For admin use:
> x/crisis: Proto Tx CLI Command

- x/ibc/20-transfer/client/cli/tx.go
- x/ibc/20-transfer/client/rest/rest.go
- x/ibc/20-transfer/client/rest/tx.go
- x/ibc/20-transfer/handler.go
- x/ibc/20-transfer/handler_test.go
- x/ibc/20-transfer/keeper/relay.go
- x/ibc/20-transfer/keeper/relay_test.go
- x/ibc/20-transfer/types/errors.go
- x/ibc/20-transfer/types/msgs.go
- x/ibc/20-transfer/types/msgs_test.go
- x/ibc/20-transfer/types/packet.go
- x/ibc/20-transfer/types/packet_test.go
Remove "source" field from packets & messages, it is now inferred from the denom.
Closes https://github.com/cosmos/cosmos-sdk/issues/5812
> Remove source field from ICS 20 packet & message types per latest spec

- x/ibc/20-transfer/client/cli/tx.go
On `GetTransferTxCmd`, args number should be `5`.
> Fix ics20 client

- client/cmd.go
- client/cmd_test.go
Closes: #5919
updates validateCmd to search for the unknown command, ignoring any flags and their values and returning the help screen if the help flags are an argument. 
untested at the moment.. having trouble installing via gaia because this branch is on the latest sdk version which has build issues on gaia
______
______
For admin use:
> Fix validate cmd bug

- CHANGELOG.md
- x/genutil/utils.go
fixes return values from InitializeNodeValidatorFiles function
______
______
For admin use:
> x/genutil: fix InitializeNodeValidatorFiles

- x/ibc/20-transfer/handler.go
As they are marshalled as JSON.
> Unmarshal packets as JSON

- CHANGELOG.md
- x/auth/ante/sigverify.go
- x/auth/ante/sigverify_test.go
replaces: https://github.com/cosmos/cosmos-sdk/pull/5905
credit: @mjackson001
______
______
For admin use:
> Fix IncrementSequenceDecorator

- client/flags/flags.go
- x/auth/client/cli/query.go
Closes: #XXX
______
______
For admin use:
> Add flag to FlagKeyringBackend  to QueryTxsByEventsCmd

- x/params/client/cli/tx.go
- x/params/client/utils/utils.go
ref: https://github.com/cosmos/cosmos-sdk/issues/5864
______
______
For admin use:
> x/params: Protobug Tx CLI Migration

- CHANGELOG.md
- client/context/context.go
- client/context/context_test.go
- client/keys/add.go
- server/config/config.go
- server/config/toml.go
- server/pruning.go
- server/pruning_test.go
- server/start.go
- server/start_test.go
- types/rest/rest_test.go
- x/distribution/client/common/common_test.go
github.com/spf13/viper's recent releases introduced a semantic
change in some public API such as `viper.IsSet()`, which have
broken some of our flags checks. Instead of checking whether
users have changed a flag's default value we should rely on such
defaults and adjust runtime behaviour accordingly. In order to do
so, it's important that we pick sane defaults for all our flags.
The `--pruning` flag and configuration option now allow for a
fake `custom` strategy. When users elect `custom`, then the
`pruning-{keep,snapshot}-every` options are interpreted and
parsed; else they're ignored.
Zero is `pruning-{keep,snapshot}-every` default value. When
users choose to set a custom pruning strategy they are
signalling that they want more fine-grainted control, therefore
it's legitimate to expect …
> fix all bits broken by viper API changes

- CHANGELOG.md
- simapp/app.go
- x/params/alias.go
- x/params/client/cli/query.go
- x/params/keeper/querier.go
- x/params/module.go
- x/params/types/keys.go
- x/params/types/querier.go
Allow raw parameter querying by subspace. This is primarily motivated by the fact that we need to be able to query for non-module parameters (e.g. consensus parameters).
Note, this is **not** hooked up to the module manager, because it's **Proto-ready**.
______
______
For admin use:
> x/params: Raw Parameter Querying

- x/ibc/20-transfer/client/cli/tx.go
- x/ibc/20-transfer/client/rest/rest.go
- x/ibc/20-transfer/handler.go
- x/ibc/20-transfer/handler_test.go
- x/ibc/20-transfer/keeper/keeper_test.go
- x/ibc/20-transfer/keeper/relay.go
- x/ibc/20-transfer/keeper/relay_test.go
- x/ibc/20-transfer/module.go
- x/ibc/20-transfer/types/msgs.go
- x/ibc/20-transfer/types/msgs_test.go
- x/ibc/20-transfer/types/packet.go
- x/ibc/20-transfer/types/packet_test.go
Closes https://github.com/cosmos/cosmos-sdk/issues/5977
I think it will work to leave `msg.Sender` as an `sdk.AccAddress`, since that's just for the tx.
> Change address type to string

- CHANGELOG.md
- x/ibc/02-client/exported/exported.go
- x/ibc/02-client/handler.go
- x/ibc/02-client/keeper/keeper.go
- x/ibc/09-localhost/client_state.go
- x/ibc/09-localhost/client_state_test.go
- x/ibc/09-localhost/codec.go
- x/ibc/09-localhost/consensus_state.go
- x/ibc/09-localhost/doc.go
- x/ibc/09-localhost/evidence.go
- x/ibc/09-localhost/header.go
- x/ibc/09-localhost/localhost_test.go
Closes: #5543
Mostly a stripped down copy of 07-tendermint, implementing [09-localhost](https://github.com/cosmos/ics/tree/master/spec/ics-009-loopback-client).
______
______
For admin use:
> implement 09-localhost per specification

- x/ibc/03-connection/keeper/verify_test.go
- x/ibc/04-channel/keeper/packet.go
- x/ibc/04-channel/keeper/packet_test.go
- x/ibc/04-channel/types/events.go
- x/ibc/07-tendermint/types/client_state.go
- x/ibc/handler.go
cc @AdityaSripal @cwgoes @fedekunze
> Fixes for Packet Ack

- CHANGELOG.md
- client/context/context.go
- types/rest/rest_test.go
- x/distribution/client/common/common_test.go
Maintenance release:
* #5964 Fix incorrect instantiation of tmlite verifier when --trust-node is off.
______
______
For admin use:
> instantiate verifier when --trust-node is off

- CHANGELOG.md
- Makefile
- simapp/app.go
- simapp/sim_test.go
- simapp/utils.go
- simapp/utils_test.go
- types/store.go
- x/auth/module.go
- x/auth/simulation/decoder.go
- x/auth/simulation/decoder_test.go
- x/bank/module.go
- x/bank/simulation/decoder.go
- x/bank/simulation/decoder_test.go
- x/distribution/module.go
- x/distribution/simulation/decoder.go
- x/distribution/simulation/decoder_test.go
- x/gov/module.go
- x/gov/simulation/decoder.go
- x/gov/simulation/decoder_test.go
- x/mint/module.go
- x/mint/simulation/decoder.go
- x/mint/simulation/decoder_test.go
- x/slashing/module.go
- x/slashing/simulation/decoder.go
- x/slashing/simulation/decoder_test.go
- x/staking/module.go
- x/staking/simulation/decoder.go
- x/staking/simulation/decoder_test.go
Closes: #5664
cc: @alexanderbez 
______
______
For admin use:
> refactor simulation decoder

- simapp/app.go
- x/capability/keeper/keeper.go
- x/capability/keeper/keeper_test.go
- x/capability/module.go
Closes: #6039
An annoying quirk in the capability testing setup prevented us from catching the bug reported above. Created a new testcase `TestOriginalCapabilityKeeper` that reproduced the failure above and is now passing.
Created `InitGenesis` logic to set initial global index to 1
______
______
For admin use:
> Start global capability index at 1

- CHANGELOG.md
- x/auth/types/account.go
Remove custom JSON marshaling for `BaseAccount` as multsigs cannot be bech32 decoded.
______
______
For admin use:
> Remove JSON marshaler for base account

- CHANGELOG.md
- simapp/app.go
- x/staking/simulation/genesis.go
- x/staking/simulation/params.go
- x/staking/types/params.go
Closes: #XXX
______
______
For admin use:
> Update DefaultHistoricalEntries to 100

- CHANGELOG.md
- x/ibc/03-connection/alias.go
- x/ibc/03-connection/client/utils/utils.go
- x/ibc/03-connection/exported/exported.go
- x/ibc/03-connection/genesis.go
- x/ibc/03-connection/keeper/handshake.go
- x/ibc/03-connection/keeper/handshake_test.go
- x/ibc/03-connection/keeper/keeper.go
- x/ibc/03-connection/keeper/keeper_test.go
- x/ibc/03-connection/keeper/querier.go
- x/ibc/03-connection/keeper/verify_test.go
- x/ibc/03-connection/types/connection.go
- x/ibc/03-connection/types/connection_test.go
- x/ibc/03-connection/types/expected_keepers.go
- x/ibc/03-connection/types/genesis.go
- x/ibc/03-connection/types/genesis_test.go
- x/ibc/03-connection/types/querier.go
- x/ibc/07-tendermint/types/client_state_test.go
- x/ibc/09-localhost/types/client_state_test.go
- x/ibc/genesis.go
- x/ibc/genesis_test.go
- x/ibc/module.go
ref: #5948
______
______
For admin use:
> ibc/03-connection: import export GenesisState

- CHANGELOG.md
- x/genutil/client/cli/gentx.go
- x/slashing/keeper/keeper_test.go
- x/slashing/keeper/unjail.go
- x/staking/keeper/delegation.go
- x/staking/keeper/delegation_test.go
Allow a validator to _immediately_ unjail due to being jailed for falling below their minimum self-delegation _and_ never having been bonded (i.e. no signing info present), assuming they've now met their minimum self-delegation.
closes: #6004
______
______
For admin use:
> Allow Unjail of Non-Bonded Jailed Validator

- CHANGELOG.md
- server/start.go
- server/tm_cmds.go
- server/util.go
- x/genutil/utils.go
OldFilePV was deprecated in Tendermint Core v0.28 and will be removed in
upcoming v0.34.5 release.
______
______
For admin use:
> server: remove deprecated UpgradeOldPrivValFile

- .github/workflows/proto.yml
At least for me, it's helpful to split proto CI into separate lint and breakage steps. Right now before 0.39 we may be making lots of breaking changes but we always want lint to pass. Later, we will likely want to both to always pass.
______
______
For admin use:
> Split proto CI into lint and breakage checks

- .github/CODEOWNERS
> CODEOWNERS: add Aaron, Cory

- baseapp/helpers.go
- simapp/app.go
Cleaner fix than one implemented in #6127 
Uses a different helper function that explicitly creates uncached context
______
______
For admin use:
> Initialize Capabilities with Uncached Context

- CHANGELOG.md
- go.mod
- go.sum
Bump tendermint version to 0.32.11.
This release is a update to the privval server in which the kms losing communication with the server will not result in a panic
> 0.37.12: bump tendermint version to 0.32.11

- tests/cli/helpers.go
- tests/cli/simd_test.go
- x/auth/client/cli/cli_test.go
- x/auth/client/testutil/helpers.go
- x/bank/client/cli/cli_test.go
- x/slashing/client/cli/cli_test.go
- x/staking/client/cli/cli_test.go
Reference  - https://github.com/cosmos/cosmos-sdk/issues/5951
> Add cli tests for auth

- CHANGELOG.md
- client/flags/flags.go
- client/lcd/root.go
Add `max-body-bytes` CLI flag to the REST service.
> REST: Add 'max-body-bytes' Flag

- x/ibc/07-tendermint/types/test_utils.go
x/ibc/07-tendermint/types/test_utils.go: Calculate and use
machine-dependent maxInt instead of causing int overflow by
passing math.MaxInt64.
Closes: #6130
This mitigation should be applied while we wait for tendermint
to migrate away from machine-dependent integers.
> x/ibc: fix int overflow

- client/keys/parse.go
- client/keys/parse_test.go
- types/config.go
- types/config_test.go
`keys parse` uses the global configuration before
before client applications have had a chance to
apply their settings.
This change adds a `GetSealedConfig()` helper
that waits for the config to be sealed before
returning it.
fixes #5091
addresses #5283
> client/keys/parse.go: honor config changes

- CHANGELOG.md
- baseapp/baseapp.go
- baseapp/baseapp_test.go
- simapp/test_helpers.go
> baseapp: track events emitted from AnteHandler

- CHANGELOG.md
- client/context/broadcast.go
- client/context/broadcast_test.go
- types/result.go
- types/result_test.go
Adds codespace to responses of broadcast SYNC and ASYNC.
- add codespace in case of mempool errors
- set codespace from  the ABCI ResultBroadcastTx
closes: #5859
> feat(types): add codespace to broadcast(sync/async) response

- CHANGELOG.md
- x/slashing/alias.go
- x/slashing/client/cli/query.go
- x/slashing/keeper/keeper.go
- x/slashing/keeper/signing_info.go
- x/slashing/simulation/decoder.go
- x/slashing/simulation/decoder_test.go
- x/slashing/types/keys.go
Remove Get* prefix from key construction functions:
GetValidatorSigningInfoKey => ValidatorSigningInfoKey
Add *Prefix to constant prefixes:
ValidatorSigningInfoKey => ValidatorSigningInfoKeyPrefix
closes: #2747
> Remove Get* Prefixes from Key Construction Functions

- types/utils.go
Adds the ability to use any of the database backend engines supported by Tendermint while creating new Cosmos databases.
closes: #6218
> Different db support

- x/ibc/24-host/validate.go
- x/ibc/24-host/validate_test.go
Updates path validator to enforce that no path can begin or end with the separator. Previously both were allowed, but I believe this goes against the [ICS spec](https://github.com/cosmos/ics/tree/master/spec/ics-024-host-requirements) which states:
```
The separator "/" is used to separate and concatenate two identifiers or an identifier and a constant bytestring. Identifiers MUST NOT contain the "/" character, which prevents ambiguity.
```
IMO beginning or ending with the separator is ambiguous to whether the separator is apart of the identifier name (which isn't allowed) or if the second identifier is an empty string (again not allowed). It is also more logical that a separator is always used to separate either two identifiers or an identifier and a constant byte string. 
continuation …
> update path validator to enforce no beginning or ending of the separator

- .github/CODEOWNERS
- go.sum
> CODEOWNERS: remove Hans

- x/ibc-transfer/handler.go
This is one of the BUGs that IRISnet team reported to [security@cosmosnetwork.dev](http://security@cosmosnetwork.dev/), but it seems that it has not been fixed. Hacker can use this bug to attack other nodes in the network, thereby improving its ranking in the game (however we did not do so), this bug has a very serious impact on the entire schedule of GoZ!
When a Tx contains multiple ICS-20 messages, the events will be abnormal. The reason is that the following msg events will contain all the previous msg events. You can see the event `logs.events.type='send_packet'` here: https://gist.github.com/SegueII/401de4d690a0a40038ad21a4ed2536ea
This is an example using one, two and three MSGs in one Tx.
Because of event error，so `relayPacketFromQueryResponse(...)` can't get the correct result. …
> R4R: Fix ics20 event bug

- CHANGELOG.md
- x/auth/client/tx.go
- x/auth/types/txbuilder.go
The new keyring does not handle passphrases directly anymore.
---
> x/auth: remove unused passphrase arguments

- README.md
> readme: centering tags

- CHANGELOG.md
- x/bank/keeper/keeper_test.go
- x/bank/keeper/send.go
If the recipient account does not exist when handing `MsgSend`, we will save it. And we should also do this for `MsgMultiSend`.
> R4R: Save account for multi sending

- baseapp/grpcrouter.go
- baseapp/grpcrouter_helpers.go
- baseapp/grpcrouter_test.go
- codec/testdata/proto.pb.go
- codec/testdata/proto.proto
- go.mod
- go.sum
- scripts/protocgen.sh
- types/context.go
- types/context_test.go
> Add GRPCRouter

- store/iavl/proof.go
- store/iavl/store.go
- store/rootmulti/proof.go
This extends the great work in https://github.com/cosmos/cosmos-sdk/pull/6324 and allows the same code to be reused for ics23 proofs derived from `merkle.SimpleProof` as well as the current `iavl.RangeProof`. It just adds some settings to use the serialized type to select a registered ProofSpec.
If you like this, please merge into your PR before finalizing it. Once that is done, and https://github.com/cosmos/cosmos-sdk/pull/6323 is merged, then adding ics23 support for the root multistore proof should be quite easy with no code duplication.
closes: #XXXX
---
> Make CommitmentOp generic over all ics23 specs

- store/rootmulti/proof.go
- store/rootmulti/store.go
- store/rootmulti/store_test.go
- x/evidence/types/params.go
Pulling out one part of the logic from #6178 and simplifying the changes 
One step towards https://github.com/cosmos/cosmos-sdk/issues/5842
Currently we serialize the entire `commitInfo` in the root multistore proofs. This is not even a merkle proof, just all data. Before we can move to ics23 proofs, we need to use merkle proofs that can be transformed to that format (it is just an encoding, not the logic).
As discussed a few times with @cwgoes and now @AdityaSripal we use `merkle.SimpleProofsFromMap` to produce the commitment of the root multi store. This can later be converted into ics23 format, but this is a valid, testable step that can be merged to master and is an improvement over current state.
closes: #XXXX
Before we can merge this PR, please make sure that all the following items …
> Use simple merkle proof for commit info

- docs/architecture/adr-023-ibc-passive-channels.md
- docs/architecture/adr-025-ibc-passive-channels.md
This ADR is a proposal to enable "passive" IBC relayers (ones that manage a whole connection and detect when channels come and go), as well as an "attempt channel try open" callback to allow an application to decide how and whether to handle inbound channel open handshakes.
closes: #XXXX
---
> New ADR 025 for passive channels

- .github/workflows/lint.yml
- codec/legacy/codec.go
- x/auth/alias.go
- x/auth/ante/basic.go
add reason why things are `nolint`
closes: #XXXX
---
> add comments to why its nolint

- client/keys/parse.go
- client/keys/parse_test.go
- types/config.go
- types/config_test.go
Maintenance fix for #5091
Cherry-picked from 4e328d75dbe0d06f1d1a3002d31803ca039afef3
---
> [0.38.x] client/keys/parse: honor config changes

- CHANGELOG.md
- client/keys/add.go
- client/keys/add_ledger_test.go
- client/keys/add_test.go
- crypto/keyring/keyring.go
- crypto/keyring/signing_algorithms.go
- crypto/keyring/signing_algorithms_test.go
> client: fix signing algorithm

- x/ibc/02-client/client/rest/query.go
- x/ibc/02-client/client/rest/rest.go
The "height" path param is required to query consensus state but it's missing.
---
- No, but this PR is just a small/simple fix.
- No, but also the other REST API impls in x/ibc have no test codes.
- N/A
- N/A
- N/A
> x/ibc: add the missing path parameter "height" to "/ibc/clients/{client-id}/consensus-state/{height}"

- CHANGELOG.md
- simapp/app.go
- x/staking/keeper/keeper.go
- x/staking/keeper/params.go
- x/staking/types/params.go
I realized while trying to make gaia work that for some reason those types were in keeper package instead of types, it was the only one, so I moved it to be consistent.
---
> Move some Param types from Keeper to Types in staking

- CHANGELOG.md
- docs/architecture/adr-023-protobuf-naming.md
- simapp/app.go
- simapp/app_test.go
- x/bank/handler.go
- x/bank/keeper/keeper.go
- x/bank/keeper/send.go
- x/distribution/keeper/keeper.go
- x/distribution/keeper/proposal_handler.go
Renamed to `CannotSendTo`. The golang renamings were `blockListed` and `ignoreListed`. I wanted to stay away from `block` because I could see that being confused for actual blocks on the chain and `ignore` doesn't feel as self-describable as `CannotSendTo`. 
If someone has a name they think works better, I'll gladly update this pr again :+1: 
closes: #6447 
---
> rename blacklist to blocked

- go.mod
- go.sum
> deps: fix iavl revision

- x/auth/ante/sigverify.go
- x/auth/signing/verify_test.go
- x/auth/types/stdtx_test.go
Ref: https://github.com/cosmos/cosmos-sdk/pull/6428
---
> add more tests for ante sig

- simapp/cmd/simd/main.go
Completely forgot we could've used the already existing function to get pruning opts from config/CLI.
---
> cmd/simd: Use server.GetPruningOptionsFromFlags

- store/types/pruning.go
- store/types/pruning_test.go
> store/types: Fix pruning opts validation

- CHANGELOG.md
- go.sum
- server/export.go
- server/export_test.go
- x/ibc/07-tendermint/client/cli/tx.go
Before we did not include the field time_iota_ms into the genesis file while exporting, now we do. 
closes: #https://github.com/cosmos/cosmos-sdk/issues/6446
---
> Add TimeIotaMs to export GenesisFile

- store/types/pruning.go
Change the default pruning strategy to KeepEvery:100, the same as 0.38.4. This is to reduce the chance of data loss for users blindly upgrading from 0.38.0-0.38.4, due to bugs in the IAVL pruning implementation. See 0.38.5 change log for details.
---
> store: change PruningDefault to KeepEvery:100

- CHANGELOG.md
- x/staking/genesis.go
- x/staking/genesis_test.go
One-liner to export validator addresses properly.
closes: #6528
---
> Export validator addresses

- x/bank/internal/keeper/keeper.go
- x/bank/internal/keeper/keeper_test.go
Currently the bank.send event only has the recipient and amount. It is assumed that the sender of the funds is message.sender. This is often not true when a module call the bank keeper. This may be due to staking distribution, or via a cosmwasm contract that released funds (where I discovered the issue). 
For completeness, it makes sense to contain the entire triple `(sender, recipient, amount)` in the transfer event for easy parsing by clients.
I just add one more attribute to the event and fix some tests.
@alessio @alexanderbez I would like to add this to #6522 Can you please add the `backport/release/v0.38.x` label?
---
checked off. If any of the checklist items are not applicable, please leave them …
> Launchpad: Add sender info to bank transfer event

- CHANGELOG.md
- simapp/app.go
- x/auth/types/params.go
- x/bank/types/params.go
- x/crisis/types/params.go
- x/distribution/types/params.go
- x/evidence/doc.go
- x/gov/types/keys.go
- x/mint/types/keys.go
- x/slashing/types/params.go
- x/staking/types/params.go
> Remove DefaultParamspace and simplify simapp creation.

- CHANGELOG.md
- go.mod
- go.sum
- simapp/cmd/simcli/main.go
- x/auth/client/cli/cli_test.go
- x/bank/client/cli/tx.go
> cl & deps++

- .gitignore
- Makefile
- contrib/devtools/Makefile
Follow-up of #6101.
- Makefile:
Set all as actual default target.
- contrib/devtools/Makefile:
The buf target was running unconditionally.
Install protoc-gen-gocosmos along with protoc.
---
> buildsystem: various small improvements

- client/input/input.go
- client/keys/add.go
client/input/input.go: GetConfirmation() should communicate
with the user via the io.Writer instance passed in as
argument.
client/keys/add.go: replace cmd.PrintErrln() calls with
fmt.Fprintln(cmd.ErrOrStderr(), ...) because of cobra's
PrintErr* functions broken behaviour. For more information
please see https://github.com/spf13/cobra/pull/894
Closes: #6601
Thanks: @noandrea for pointing this out.
---
> client/keys: make add command's output parseable

- x/ibc-transfer/client/cli/query.go
- x/ibc-transfer/client/cli/tx.go
- x/ibc/02-client/client/cli/query.go
- x/ibc/03-connection/client/cli/query.go
- x/ibc/04-channel/client/cli/query.go
- x/ibc/04-channel/client/cli/tx.go
- x/ibc/07-tendermint/client/cli/tx.go
ref: https://github.com/cosmos/cosmos-sdk/issues/6571
---
> x/ibc: CLI Remove Viper

- CHANGELOG.md
- baseapp/abci.go
- baseapp/baseapp_test.go
- types/result.go
- x/auth/client/utils/tx.go
- x/auth/client/utils/tx_test.go
> backport 0.39.0 (launchpad): cherry pick #5839

- Makefile
- x/auth/ante/basic.go
Makefile: parse COSMOS_BUILD_OPTIONS
Look for build options in the make's COSMOS_BUILD_OPTIONS
variable. This allows one to build simd with ledger support.
References:
* https://github.com/cosmos/gaia/pull/363
* https://github.com/tendermint/tendermint/pull/4738
fix tiny typo in nolint: statement that causes golangci-lint to
misbehave.
---
> Makefile: build simd with ledger support

- CHANGELOG.md
- client/flags/flags.go
- simapp/simd/cmd/root.go
The functionality was adopted tendermint upstream, see
https://github.com/tendermint/tendermint/pull/4665
---
> client/flags: remove NewCompletionCmd()

- .circleci/config.yml
The build failed due to the Makefile's recent changes:
https://circleci.com/gh/cosmos/cosmos-sdk/177400?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
---
> fix docs build failure

- types/module/interface_module.go
- x/bank/client/cli/cli_test.go
- x/crisis/client/cli/cli_test.go
- x/crisis/client/cli/tx.go
- x/crisis/module.go
- x/crisis/types/codec.go
- x/crisis/types/msgs.go
ref: https://github.com/cosmos/cosmos-sdk/issues/6423
---
> x/crisis: In-Process CLI Integration Tests

- x/bank/client/cli/cli_test.go
- x/bank/client/cli/query.go
- x/bank/module.go
Not sure how I missed this...
---
> x/bank: Remove Context Param

- x/genutil/client/cli/gentx.go
> x/genutil: use HomeDir stored in ClientCtx

- .github/workflows/sims.yml
prs have been getting merged prior to completing sims in ci. We should just run on master to be safe
> run sims on master

- CHANGELOG.md
- codec/json.go
Noticed as part of an audit that the implementation was expensive,
and I've been informed that this function can be removed anyways
as it isn't being visibly used and a Github search doesn't turn up
useful results:
https://github.com/search?q=MarshalIndentFromJSON&type=Issues
Fixes #6666
closes: #6666
---
> codec: remove unused, untested and expensive MarshalIndentFromJSON

- CHANGELOG.md
- go.mod
- go.sum
> launchpad: bump tendermint to v0.33.6

- types/coin_benchmark_test.go
Fixes an invalid int->string conversion that will become
a vet error for Go1.15. The correct conversion was to use
fmt.Sprintf("COINZ_%d", i)
instead of
"COINZ_" + string(i)
Noticed during a coverage audit.
---
> types: fix invalid int->string conversion in benchmarks

- codec/amino.go
- codec/amino_codec_test.go
- codec/any_test.go
- codec/proto_codec_test.go
As part of an audit, adds as much visible coverage from
73.4% to about 84.2%, but after #6668 is merged, we'll
have it about 88.X% and the coverage report seems to show
only missing cases of not common scenarios, e.g. a case that'll
make jsonpb.Marshaling to fail, and which will return an error
anyways.
---
> codec: increase as much visible coverage

- CHANGELOG.md
- client/context/query.go
- client/flags/flags.go
Original pull request: #5585
---
> client: backport IBC additions

- CHANGELOG.md
- x/bank/internal/keeper/keeper.go
- x/bank/internal/keeper/keeper_test.go
Backport https://github.com/cosmos/cosmos-sdk/pull/6283/ into 0.39.x
---
> Save account for multi sending

- store/rootmulti/internal/maps/bench_test.go
- store/rootmulti/internal/maps/maps.go
Noticed during an audit, we've got duplicated code that's unused.
There were 2 type definitions:
* type kvPair types.Pair
* type KVPair types.Pair
and each had a .bytes() and .Bytes() method respectively that
then used some extra code.
This change deletes the duplicated/unnecessary code but also
while here improves the performance by removing the use of a
bytes.Buffer which is unnecessary given that we are only
length prefixed the key, length prefixing the value hence
the various helpers are unnecessary.
The added benchmarks shows the performance boost
```shell
$ benchstat before after
name           old time/op    new time/op    delta
KVPairBytes-8     146µs ± 1%     142µs ± 2%   -3.05%  (p=0.000 n=18+17)
name           old speed      new speed      delta
KVPairBytes-8  6.84GB/s ± 1% …
```
> rootmulti/internal/maps: remove duplicated code, simplify and speed up KVPPair

- x/staking/simulation/operation_test.go
- x/staking/simulation/operations.go
> x/staking/simulation/operations.go: add unit tests

- x/staking/simulation/params_test.go
> x/staking/simulation/params.go: add unit tests

- types/decimal.go
- types/decimal_test.go
Use big.Int.Cmp() and compare against zeroInt instead
of checking Bytes() against a 0-length byte slice.
Closes: #6680
Thanks: @odeke-em for the patch.
---
> types: better Dec.MarshalTo's performance

- store/cache/benchmark_test.go
- store/cache/cache.go
Noticed during my audit, the code for cache.CommitKVStoreCacheManager.Reset()
discarded the prior on every invocation i.e.
m = make(map[T(key)]T(value))
However, this can be made fast and conserve memory by using the map clearing idiom
that the Go compiler recognizes i.e.
for key := range m {
delete(m, key)
}
and turns into very fast code, instead of the extraneous map discarding.
The speed up generated is:
```shell
$ benchstat before after
name     old time/op    new time/op    delta
Reset-8     204ns ± 2%      66ns ± 9%   -67.86%  (p=0.000 n=20+20)
name     old alloc/op   new alloc/op   delta
Reset-8      384B ± 0%        0B       -100.00%  (p=0.000 n=20+20)
name     old allocs/op  new allocs/op  delta
Reset-8      3.00 ± 0%      0.00       -100.00%  (p=0.000 n=20+20)
```
Fixes #6681 …
> store/cache: speed up + conserve memory by using map clearing idiom in Reset

- CHANGELOG.md
- baseapp/baseapp.go
- baseapp/baseapp_test.go
Backport #6307 into 0.39.0
---
> Backport 0.39.x: baseapp: fix sender events accumulation

- x/auth/signing/direct/direct_test.go
Ensure that all known routes for GetSignBytes are explored for
DirectHandler.
---
> x/auth/signing/direct: increase test coverage to 100% from 83.3%

- baseapp/abci.go
- docs/architecture/adr-013-metrics.md
- docs/core/telemetry.md
- store/cachekv/store.go
- store/gaskv/store.go
- store/iavl/store.go
- telemetry/wrapper.go
- x/crisis/abci.go
- x/distribution/abci.go
- x/evidence/abci.go
- x/gov/abci.go
- x/mint/abci.go
- x/slashing/abci.go
- x/staking/abci.go
- x/upgrade/abci.go
* small doc changes
@alexanderbez : for your consideration - hide `UTC()` in the wrappers.
> telemetry: use UTC() in wrappers

- baseapp/baseapp.go
- codec/types/any.go
- types/result.go
Few minor updates to address comments from @alexanderbez that came in after merge.
Ref: #6713
---
> Small updates to #6713

- x/bank/simulation/operations_test.go
> x/bank/simulation/operations.go: add unit tests

- CHANGELOG.md
- x/staking/keeper/delegation.go
Original pull request: #6791
---
> x/staking: add call to iterator Close() method

- server/start.go
This PR will add a new flag to daemon start command to make it possible to choose the transport protocol: socket or grpc.
---
> Add transport flag to start command

- CHANGELOG.md
- client/keys/show.go
- crypto/keyring/keyring.go
- crypto/ledger/amino.go
- crypto/ledger/encode_test.go
- crypto/ledger/ledger_mock.go
- crypto/ledger/ledger_notavail.go
- crypto/ledger/ledger_real.go
- crypto/ledger/ledger_secp256k1.go
- crypto/ledger/ledger_test.go
crypto -> crypto/ledger:
- crypto.LedgerShowAddress -> ledger.ShowAddress
- crypto.NewPrivKeyLedgerSecp256k1 - > ledger.NewPrivKeySecp256k1
- crypto.NewPrivKeyLedgerSecp256k1Unsafe -> ledger.NewPrivKeySecp256k1Unsafe
Closes: #6780
---
> crypto: move ledger code to its own subfolder

- x/auth/vesting/types/vesting_account.go
- x/auth/vesting/types/vesting_account_test.go
- x/supply/internal/types/account.go
- x/supply/internal/types/account_test.go
Right before we released 0.39, we last minute introduced the removal of custom JSON marshaling for `BaseAccount` and rightfully so. However, I forgot to do the same for the remaining account types. 
Remove custom JSON marshaling for accounts. Note, this is genesis and client breaking, but worth the change in order to get migration to function properly.
/cc @alessio @ethanfrey 
---
> Backport 0.39.1: Remove Custom JSON Marshaling for Accounts

- client/lcd/root.go
Manual testing of the `--unsafe-cors` code shows that it is not working for `POST`
This is my attempt to fix it (likely the same issue is in master)
According to [the godoc](https://godoc.org/github.com/gorilla/handlers#AllowedHeaders):
"""
AllowedHeaders adds the provided headers to the list of allowed headers in a CORS request. This is an append operation so the headers Accept, Accept-Language, and Content-Language are always allowed. Content-Type must be explicitly declared if accepting Content-Types other than application/x-www-form-urlencoded, multipart/form-data, or text/plain. 
"""
And we definitely need `Content-Type` for POST-ing JSON data.
I compiled a version of `wasmd` with this patch and it produced the desired results.
closes: #XXXX
---
Before we can merge this PR, please …
> Allow Content-Type header

- CHANGELOG.md
- x/auth/vesting/types/vesting_account.go
- x/auth/vesting/types/vesting_account_test.go
- x/supply/internal/types/account.go
- x/supply/internal/types/account_test.go
Reverts cosmos/cosmos-sdk#6842 because we still need custom JSON marshaling for vesting accounts because otherwise, we get ugly nesting. **However, we keep bech32 removed.**
/cc @ethanfrey
> Revert "Backport 0.39.1: Remove Custom JSON Marshaling for Accounts"

- x/auth/legacy/v0_38/types.go
- x/auth/legacy/v0_39/migrate.go
- x/auth/legacy/v0_39/types.go
- x/auth/legacy/v0_40/migrate.go
- x/auth/legacy/v0_40/migrate_test.go
- x/bank/legacy/v0_40/migrate_test.go
- x/genutil/legacy/v0_39/migrate.go
- x/genutil/legacy/v0_39/migrate_test.go
Ref: https://github.com/cosmos/cosmos-sdk/pull/6829
Forgot to add `Coins` to JSON output. Added migration tests.
---
> Fix 0.39 x/auth Migration Types

- codec/codec.go
- codec/proto_codec.go
- codec/proto_codec_test.go
Improve ProtoCodec.MarshalBinaryLengthPrefixed by removing the need
to use a *bytes.Buffer and instead use an array and invoke
binary.PutUvarint, and directly create the respective length prefixed
concatentation.
With this change we get the following improvement in all dimensions
of throughput, bytes allocated, number of allocations per operation.
```shell
name                                     old time/op    new time/op    delta
ProtoCodecMarshalBinaryLengthPrefixed-8     295ns ± 2%     177ns ± 3%  -39.92%  (p=0.000 n=20+20)
name                                     old speed      new speed      delta
ProtoCodecMarshalBinaryLengthPrefixed-8   505MB/s ± 2%   841MB/s ± 3%  +66.44%  (p=0.000 n=20+20)
name                                     old alloc/op …
```
> codec: remove unnecessary allocations in ProtoCodec.MarshalBinaryLengthPrefixed

- client/tx/tx.go
- client/tx_generator.go
- x/auth/ante/testutil_test.go
- x/auth/tx/builder_test.go
Revert the `SetSignerInfo` function introduced in #6845.
SetSignerInfo doesn't work well with MultiSig. Here's what happens:
- you set a Msg with the multisig account (let's say with 2 accounts) as signer
- you want account1 to sign
- the current txfactory Sign does SetSignerInfo(account1, signerInfo1)
- and SetSignerInfo shouts because account1 is not in the tx's GetSigners
1. Revert to the status quo before #6845, with the "empty signature hack"
2. Replace `SetSignerInfo` with `SetSignerInfos` (with an s).
- This should work, but after playing around for ~1h, I thought it was too big a refactor, and in part related to https://github.com/cosmos/cosmos-sdk/issues/6896.
This PR implements 1.
---
checked …
> Revert `SetSignerInfo`

- server/grpc/server_test.go
Some of you may have noticed flaky tests on TestGRPC, e.g. [this one](https://github.com/cosmos/cosmos-sdk/runs/928172361#step:5:118). The SetupSuite waits until block height 2, but it seems when the test is run, the block height can vary.
This PR just checks that the header is not empty
---
> Fix gRPC flaky test

- .github/workflows/test.yml
- Makefile
- go.sum
- simapp/params/amino.go
- simapp/params/proto.go
- x/auth/tx/builder_test.go
- x/auth/tx/decoder.go
- x/distribution/types/codec.go
ref: #6213
The one remaining bug was an unregistered interface type. The `TxDecoder` errors are now wrapped for easier debugging.
---
> Fix the one remaining proto tx bug and flip the switch

- docs/architecture/adr-020-protobuf-transaction-encoding.md
- types/codec.go
Removes all vestiges of CanonicalSignBytes, which is unused
and untested.
Closes #6679
---
> types: remove unused CanonicalSignBytes

- x/params/types/deref_test.go
- x/params/types/table.go
Use a for loop to correctly and fully dereference and
extract the type for the type of ParamSetPair.Value.
Fixes #6785
---
> x/params/types: make KeyTable.RegisterType fully dereference pointers

- x/ibc-transfer/module.go
- x/ibc-transfer/types/codec.go
- x/ibc/02-client/keeper/client_test.go
- x/ibc/02-client/keeper/encoding.go
- x/ibc/02-client/keeper/keeper.go
- x/ibc/02-client/keeper/keeper_test.go
- x/ibc/02-client/types/codec.go
- x/ibc/03-connection/types/codec.go
- x/ibc/04-channel/types/codec.go
- x/ibc/07-tendermint/misbehaviour.go
- x/ibc/07-tendermint/types/client_state.go
- x/ibc/07-tendermint/types/client_state_test.go
- x/ibc/07-tendermint/types/codec.go
- x/ibc/07-tendermint/types/evidence.go
- x/ibc/07-tendermint/update.go
- x/ibc/07-tendermint/update_test.go
- x/ibc/09-localhost/types/client_state.go
- x/ibc/09-localhost/types/client_state_test.go
- x/ibc/09-localhost/types/codec.go
- x/ibc/23-commitment/types/codec.go
- x/ibc/keeper/keeper.go
- x/ibc/module.go
- x/ibc/types/codec.go
Followup to #6932 
Migrates client states to use `codec.BinaryMarshaler` in `02-client`. `ClientState` will now be passed around as a pointer. We need to maintain the amino codec registration until the flip is switched on amino encoding genesis, which will occur once IBC genesis is migrated (after consensus states migration).
Consensus state migration should be able to occur after we change the validator set to be a hash in the tendermint client: #6942. I'll probably do this change in 2 steps like client state, migrate tendermint consensus state, then flip the switch in 02-client
ref: #6254 
---
> Migrate 02-client to use proto encoded/decoded client states 

- x/ibc/02-client/client/utils/utils.go
- x/ibc/02-client/exported/exported.go
- x/ibc/02-client/keeper/client_test.go
- x/ibc/02-client/keeper/encoding.go
- x/ibc/02-client/keeper/keeper.go
- x/ibc/02-client/keeper/keeper_test.go
- x/ibc/02-client/types/codec.go
- x/ibc/03-connection/keeper/handshake_test.go
- x/ibc/03-connection/keeper/keeper.go
- x/ibc/03-connection/keeper/verify.go
- x/ibc/03-connection/keeper/verify_test.go
- x/ibc/03-connection/types/codec.go
- x/ibc/07-tendermint/misbehaviour.go
- x/ibc/07-tendermint/misbehaviour_test.go
- x/ibc/07-tendermint/types/client_state.go
- x/ibc/07-tendermint/types/client_state_test.go
- x/ibc/07-tendermint/types/consensus_state.go
- x/ibc/07-tendermint/types/consensus_state_test.go
- x/ibc/07-tendermint/types/header.go
- x/ibc/07-tendermint/types/msgs.go
- x/ibc/07-tendermint/update.go
- x/ibc/07-tendermint/update_test.go
- x/ibc/09-localhost/types/client_state.go
- x/ibc/09-localhost/types/client_state_test.go
- x/ibc/keeper/keeper.go
Proto encodes consensus state in `02-client`. Removes amino from client keeper and connection keeper. `ConsensusState` is now being passed around by reference. Genesis migration will ocurr in #6878 
ref: #6254
---
> Migrate Consensus State to being proto encoded/decoded in 02-client

- simapp/simd/cmd/root.go
- x/auth/client/cli/tx_sign.go
- x/auth/client/testutil/helpers.go
Replaces https://github.com/cosmos/cosmos-sdk/pull/6959 and fixes tests. Credit: @ethanfrey.
---
> Remove Home Flag from "tx sign"

- store/internal/maps/maps_test.go
This adds test cases for hashing of empty inputs. This behavior will change in a breaking manner when upgrading to Tendermint 0.34, due to https://github.com/tendermint/tendermint/pull/5193 which was just merged to `master`. Test cases will need to be updated when that happens. A similar change was made to IAVL in https://github.com/cosmos/iavl/pull/304.
> store: add test cases for hashing of empty inputs

- x/genutil/client/cli/migrate.go
- x/genutil/client/cli/migrate_test.go
- x/genutil/client/cli/testdata/commercio-genesis.json
Add migrate test case.
Thanks: @gsora for providing genesis test data.
---
> test case with real genesis data

- CHANGELOG.md
- types/decimal.go
- types/int.go
- types/int_test.go
> types: fix panic on Int.BigInt()

- types/coin_benchmark_test.go
Go1.15 has become stricter with conversions from string.
See https://golang.org/doc/go1.15#vet
---
> fix tests build failures with go1.15

- CHANGELOG.md
- types/coin_benchmark_test.go
- types/decimal.go
- types/int.go
- types/int_test.go
> launchpad: backport BigInt fix

- .github/CODEOWNERS
Recent changes to codeowners did not take into account github rules for codeowner files. Specifically
```
*       @global-owner1 @global-owner2
*.js    @js-owner
```
see [doc](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners#example-of-a-codeowners-file)
The ordering should be swapped, the primaries should be at the bottom.
I believe the intended function is for primary reviewers to be requested for all prs not secondary reviewers
closes: #XXXX
---
> swap codeowner ordering to follow github rules

- server/export.go
- simapp/export.go
- simapp/sim_test.go
- simapp/simd/cmd/root.go
- simapp/types.go
- x/simulation/simulate.go
Should fix `AfterImport` sim. `newApp` had gotten changed to `app` in #7135. While looking at the diffs I realized I missed some black/white list naming references so I thought it'd be fine to update those in this pr as well. 
The failing seed passed for me locally but we should wait for the full sim to run
closes: #XXXX
---
> Fix AfterImport and update black/white list variable namings

- server/api/server.go
- server/start.go
We weren't passing the correct client context to legacy API route registration.
closes: #7186
---
> Fix Legacy API Server Client Context

- CHANGELOG.md
- client/keys/add.go
- client/keys/add_test.go
Fix the command line `keys add` interactive mode
that fails when asked to generate new mnemonic.
From: https://github.com/cosmos/cosmos-sdk/pull/7049, https://github.com/cosmos/cosmos-sdk/pull/7183
Closes: #7048
Thanks: @puneet2019 for the original patch.
Thanks: @PaddyMc for the backport.
---
> client: fix keys add interactive command

- CHANGELOG.md
- types/decimal.go
- types/decimal_test.go
From: https://github.com/cosmos/cosmos-sdk/pull/7140
Thanks: @migueldingli1997 for the patch.
Closes: #7038
---
> cherry-pick #7140: Fix ApproxRoot Infinite Looping

- x/ibc/02-client/types/msgs.go
- x/ibc/02-client/types/msgs_test.go
- x/ibc/07-tendermint/types/codec.go
Since the client messages each contain `Any` we need to add UnpackInterfaces for each message. I also added tests to ensure they can be marshaled and unmarshaled for solo machine and tendermint types.
closes: #XXXX
---
> Fix 02-client message marshal and unmarshal issues

- simapp/app.go
os.ExpandEnv("$HOME/.simapp") would not work on non-POSIX systems.
Go offers a platform-agnostic function for that: [os.UserHomeDir()](https://golang.org/pkg/os/#UserHomeDir).
---
> simapp: use os.UserHomeDir() to get user's home dir

- baseapp/baseapp_test.go
- snapshots/util_test.go
Fixes #7289.
The same `err` variable was used both in the goroutine and the main thread, causing a data race. 🤦‍♂️
Also updates `setupBaseAppWithSnapshots` to actually check and wait for snapshots to be taken rather than sleeping for "some" time.
> test: fix data race in snapshots.ChunkReader test

- cosmovisor/README.md
- cosmovisor/upgrade.go
- cosmovisor/upgrade_test.go
This is a tiny feature for `cosmovisor` to allow the "binary" info to specify a portable
script by using "any" as the default architecture if there is no specific match.
---
> feat: allow "any" to specify a "binary" with no arch/os dependencies

- docs/architecture/adr-004-split-denomination-keys.md
When reading this ADR, I was confused about _denomination_. When reading this in context of tokens I always think about a unit / measure. Examples: bills denominated in $20 and $50. Or as 100 cents makes 1 dollar.
The Merriam-Webster dictionary defines [denomination](https://www.merriam-webster.com/dictionary/denomination) as:
1. an act of denominating. Eg: the denomination of prices in U.S. dollars
2. a value or size of a series of values or sizes. Eg: metric denominations
3. name, designation especially : a general name for a category
It seams that we are using the last definition (3rd).
closes: #XXXX
---
write a little …
> Added glossary explaning Denomination Key

- Makefile
> reintroduce rule to cross-build a linux binary

- testutil/network/network.go
- x/gov/client/cli/cli_test.go
> use *testing.T.TempDir() in tests

- .golangci.yml
- Makefile
- x/staking/types/data_test.go
It's better to explicitly disable default lint checkers rather then disable all of them. The main reason is that if we `golangci-lint` will have a very good and useful checker we may skip him.
Other changes:
+ removed `gofmt` command from `make lint`. It's not needed because `golangci-lint` is handling it (and it's doing it faster because gofmt doesn't need to re-read files).
+ removed `.vendor` patterns - we don't use patterns any more
---
> Makefile: drop gofmt in favor of golangci-lint

- CHANGELOG.md
- go.mod
- go.sum
The release contains a fix for dvsekhvalnov/jose2go#26,
which is needed for the file keyring backend to work with go 1.15.
From: #7397
---
> Update 99designs/keyring to v1.1.6 for go 1.15

- docs/.vuepress/config.js
- docs/package-lock.json
- docs/package.json
- package-lock.json
As a prerequisite for having multiple versions of docs deployed on docs.cosmos.network, we need launchpad docs to compile properly.
Currently when building from the `launchpad/backports` branch, docs failed to compile. This fixes that by updating `themeConfig` in `.vuepress/config.json` as well as updating the `package.json` for docs to pull from the most recent cosmos vuepress theme.
Unblocks #7413
ref #6953 
---
> Update launchpad docs to build without failing

- Makefile
Fixes bug in `make build-docs`, where comments inside of make task were causing the task to fail.
Fixes: #7413 
---
> Fix comment bug in make build-docs

- client/debug/main.go
- crypto/hd/hdpath.go
- crypto/keyring/keyring.go
- x/simulation/mock_tendermint.go
- x/staking/keeper/delegation.go
Fixes issues reported by [LGTM.com](https://lgtm.com/projects/g/cosmos/cosmos-sdk/?mode=list).
> LGTM alerts audit

- x/auth/legacy/v040/migrate.go
- x/auth/legacy/v040/migrate_test.go
- x/auth/types/codec.go
Accounts in the 0.37 exported state don't have pubkeys. When migrating these accounts to 0.40, we were packing a protobuf's Empty inside the BaseAccount's pubkey Any field.
It would be much simpler to just pack a `nil`, which outputs as `null` in the JSON.
---
> Use nil instead of protobuf.Empty in genesis BaseAccount

- x/ibc/light-clients/07-tendermint/types/upgrade.go
- x/ibc/light-clients/07-tendermint/types/upgrade_test.go
Prevent upgrades to an expired client. Fixes bug caught by @colin-axner 
Final followup to #7367 
---
> Upgrade followup #3

- CHANGELOG.md
- types/coin.go
- types/coin_test.go
- types/dec_coin.go
Backport of https://github.com/cosmos/cosmos-sdk/pull/6755
Closes: #6744
Origin: https://github.com/cosmos/cosmos-sdk/pull/6755
---
> support denoms custom validation

- codec/yaml.go
Cosmetic update to clarify the use of `jsonMarshaler` in `MarshalYAML`
Motivation: When I was reading this code first time I had to think. Today when reading it again, I had to think again (although less).
---
> docs: Update the code.MarshalYAML docs

- server/tm_cmds.go
- x/ibc/applications/transfer/keeper/relay.go
- x/ibc/core/handler.go
- x/ibc/light-clients/07-tendermint/types/upgrade_test.go
closes: #7503 
Ran "make format" as well, before committing. 
---
> Corrected 'unsafe-reset-all' help text

- simapp/app.go
- tests/mocks/types_module_module.go
- types/module/configurator.go
- types/module/module.go
- types/module/module_test.go
- x/auth/module.go
- x/auth/vesting/module.go
- x/bank/module.go
- x/capability/module.go
- x/crisis/module.go
- x/distribution/module.go
- x/evidence/module.go
- x/gov/module.go
- x/ibc/applications/transfer/module.go
- x/ibc/core/module.go
- x/ibc/testing/mock/mock.go
- x/mint/module.go
- x/params/module.go
- x/slashing/module.go
- x/staking/module.go
- x/upgrade/module.go
ref: #7500
* refactors `AppModule.RegisterQueryServices` -> `AppModule.RegisterServices`
* adds the `module.Configurator` object for use in `RegisterServices`
---
> Refactor RegisterQueryServices -> RegisterServices

- Makefile
- baseapp/params.go
- baseapp/params_test.go
- go.mod
- go.sum
- server/export.go
- simapp/test_helpers.go
- third_party/proto/confio/proofs.proto
- third_party/proto/tendermint/abci/types.proto
- third_party/proto/tendermint/types/evidence.proto
- third_party/proto/tendermint/types/params.proto
- third_party/proto/tendermint/types/types.proto
update to tendermint rc5
closes: #XXXX
---
> tendermint: update sdk to rc5

- CHANGELOG.md
Pulls in updated & cleaned-up changelog from `v0.40.x` branch into master.
[Rendered preview](https://github.com/cosmos/cosmos-sdk/blob/clevinson/update-master-changelog/CHANGELOG.md)
---
> Update changelog on master (from v0.40.x branch)

- .gitignore
In daily work, we have some files, scripts which are not comitable yet useful when working.
Seeing them in git status is annoying. Let's support them in `.gitignore`
Related to: https://github.com/cosmos/cosmos-sdk/pull/7364
> Adding a rule for private files in gitignore

- go.mod
- go.sum
Update tendermint to 0.33.8, see [1] for more information.
[1] https://github.com/golang/go/issues/40618
---
> tendermint security update

- baseapp/msg_service_router.go
As the old saying goes:
It’s harder to read code than to write it.
When reading the PR (after it was merged) I was wondering when some functions begin and when end. So I propose to reduce the nested functions and extract out what's possible.
---
> msg_service_router: reduce code complexity

- x/ibc/light-clients/06-solomachine/client/cli/tx.go
will manually test later after merge
closes: #XXXX
---
> update solo machine create client cli cmd

- x/distribution/legacy/v036/types.go
- x/genutil/legacy/v036/migrate.go
- x/genutil/legacy/v038/migrate.go
- x/genutil/legacy/v039/migrate.go
- x/genutil/legacy/v040/migrate.go
- x/gov/legacy/v040/migrate.go
- x/gov/legacy/v040/migrate_test.go
closes: #7601
Add CommunitySpendProposals in v036 distribution, and add correct migration paths until v040.
---
> Add CommunitySpendProposals in migration

- README.md
As the scaffold repo has been archived, I think it would make more sense for the readme to redirect to the starport repo instead.
closes: #XXXX
---
> Update readme to link starport instead of scaffold

- CHANGELOG.md
- x/gov/client/rest/query.go
Same issue with #7588  in master branch 
---
> launchpad: fix query params on governance votes querier

- server/api/server.go
#7540 introduced `AnyResolver` to `InterfaceRegistry` so that `ServiceMsg`s can properly be encoded as in proto JSON. This makes sure that is wired up with grpc-gateway for REST and CLI users decoding `ServiceMsg` tx's. Marking as a backport.
---
> Use InterfaceRegistry as AnyResolver for grpc-gateway

- client/keys/add.go
Running `appd keys add` command prints "important" message twice.
closes: https://github.com/tendermint/starport/issues/378
---
> Remove duplicate print message on keys add command

- CHANGELOG.md
- types/decimal_test.go
- x/gov/keeper/tally.go
Solution:
- change `(a / b) * c` to `a * c / b`
closes: #7640
---
> Fix #7640: tally calculation precision error

- CHANGELOG.md
This PR updates the CHANGELOG.md with a relevant section for v0.40.0-rc2, which will be tagged against this PR's merge commit.
It also adds in the changelog entries from `v0.40.0-rc1` which were missing, and previously only existed on the release branch. Following the discussion in #7738, we plan to start tagging RC's for Stargate (v0.40.0) directly off of master from `v0.40.0-rc2` onward.
---
> Stargate RC2 - Changelog updates & tag RC

- server/util.go
- simapp/simd/cmd/root.go
Reintroduce the `--log_level` CLI flag back as it was accidnetly removed during the recent CLI/context refactor.
closes: #7728
---
> Add log_level CLI Flag

- x/capability/genesis.go
- x/capability/keeper/keeper.go
- x/capability/keeper/keeper_test.go
Surfaced from Informal Systems IBC Audit of cosmos-sdk hash 82f15f3.
Fixes comments and some tests and add's more constraints to SetIndex per https://github.com/cosmos/cosmos-sdk/issues/7805
---
> x/cap: fix comments, SetIndex, and some tests

- x/ibc/core/spec/README.md
- x/ibc/spec/README.md
The IBC spec wasn't being rendered on the SDK docs
> ibc: spec overview

- go.sum
- version/command.go
- version/version.go
- version/version_test.go
The version command now displays the list of
build dependencies.
Also fix version's command output stream.
version's output should go to stdout as it's the command's
objective to actually display versioning information.
closes: #7835
---
> enrich versioning with build deps

- server/start.go
closes: discord issue
before: Only created a local TM rpc client when API is enabled
now: Creates a local TM rpc client when API or gRPC is enabled. Only RegisterTxService in that case.
---
> Fix creation of local RPC node in clientCtx

- CHANGELOG.md
- version/version.go
The output of the version --long command now shows
the list of build dependencies.
From: #7848
Closes: #7835
---
> enrich version --long's output with build deps

- x/ibc/light-clients/07-tendermint/types/codec.go
- x/ibc/light-clients/07-tendermint/types/header.go
- x/ibc/light-clients/07-tendermint/types/header_test.go
- x/ibc/light-clients/07-tendermint/types/upgrade.go
- x/ibc/light-clients/07-tendermint/types/upgrade_test.go
closes: #7879 
closes: #7880 
closes: #7863 
---
> Minor fixes for ibc tendermint

- x/ibc/core/24-host/validate.go
Minor fixes to some comments. Also adds a suggested code dedup from https://github.com/cosmos/cosmos-sdk/issues/7922#issuecomment-726396387
---
> x/ibc/24-host: fix some comments and dedup a function

- CHANGELOG.md
- version/version.go
The version command now displays replaced modules in build dependencies
closes: #7940
---
> version --long displays replaced build dependencies

- docs/basics/app-anatomy.md
- docs/building-modules/module-interfaces.md
- fix broken URLs in docs
Ref: https://github.com/cosmos/vuepress-theme-cosmos/issues/140
---
> docs: fix broken urls (launchpad/backports)

- x/ibc/core/04-channel/keeper/packet.go
- x/ibc/core/04-channel/keeper/packet_test.go
> SendPacket prevents sends with frozen clients

- x/simulation/simulate.go
Invoking:
c := make(chan os.Signal)
signal.Notify(c, signals...)
is explicitly called out as a bug in the os/signal docs
and should instead make that channel buffered lest
a signal could be lost.
Fixes #7950
> x/simulation: make signals channel buffered to avoid missing signals

- x/ibc/core/24-host/keys.go
handles code changes in: #7922 
---
> reduce redundancy in 24 host

- x/ibc/core/04-channel/types/channel.go
- x/ibc/core/04-channel/types/channel_test.go
> fix validate basic check in channels

- x/ibc/applications/transfer/keeper/relay.go
changes inspired by:
```
refundPacketToken spec does not return errors, but there are fallible operations in the code (ie. SendCoins and MintCoins). If we cannot 'mint vouchers back to sender' there is a problem. Either the code should clarify/assert that errors are not possible, or errors should be handled somehow more severely.
```
and discussion with @AdityaSripal 
ref: #7737 
---
> update transfer error messages

- client/rpc/rpc_test.go
- client/rpc/status.go
closes: issue from @alexanderbez on Discord
---
> Fix StatusCommand

- CHANGELOG.md
- client/keys/delete_test.go
- client/keys/show_test.go
- client/keys/update_test.go
- crypto/keys/hd/fundraiser_test.go
- crypto/keys/hd/hdpath.go
- crypto/keys/hd/hdpath_test.go
- crypto/keys/keybase_test.go
- crypto/keys/types_test.go
- crypto/ledger_test.go
- types/address.go
The original issue was filed against Ethermint:
https://github.com/cosmos/ethermint/issues/605
Thanks: @xiangjianmeng for the original bug report.
From: #7970
Closes: #7966
---
> crypto/hd: add 'm/' prefix to hd path

- go.mod
- types/coin.go
- types/coin_test.go
@odeke-em's modifications proposed in #7989 improve performance
quite significantly, yet they seem to break the denoms custom
validation mechanism introduced by @okwme.
This patch introduces a relatively small user-facing change as the client
application would need to call the new `SetCoinDenomRegex()` accessor
instead of the `CoinDenomRegex` variable directly in order to introduce
app-specific denom's validation.
---
> replace the CoinDenomRegex variable with SetCoinDenomRegex()

- CHANGELOG.md
- RELEASE_NOTES.md
- types/bench_test.go
- types/coin.go
- types/coin_test.go
- types/dec_coin.go
**This patch brings a client code breaking change. As such it requires a Stable Release Exception to be granted by the Stable Release Managers.** @clevinson @ethanfrey 
From: #7989
Closes: #7986
Co-authored-by: Federico Kunze <31522760+fedekunze@users.noreply.github.com>
Co-authored-by: Alessio Treglia <alessio@tendermint.com>
The changes introduced in #7450 to support denoms custom validation
caused a significance performance hit due to the use of closures
instead of compiled regular expressions. As the reporter described in #7986,
this represents a security threat since many ParseCoin invocations made
concurrently could cause the client application to run out of RAM.
The bug becomes visible by invoking ParseCoin concurrently 1000 times.
A benchmark test case is included in this PR. …
> types/Coin: compile and reuse Regexps to reduce massive RAM+CPU burn

- x/ibc/core/02-client/types/genesis.go
- x/ibc/core/02-client/types/genesis_test.go
- x/ibc/core/03-connection/types/genesis.go
- x/ibc/core/03-connection/types/genesis_test.go
- x/ibc/core/04-channel/types/genesis.go
- x/ibc/core/04-channel/types/genesis_test.go
- x/ibc/core/genesis_test.go
Aims to accomplish ensuring the next sequence for identifiers is greater than the maximum sequence already used. Also ensure the consensus state types match the client state types. Will not address ensuring the existence of clients for connections and connections for channels 
ref: #8073 
---
> increase ibc basic genesis validation

- types/query/pagination_test.go
- x/bank/keeper/grpc_query.go
Fixes an incoherent return which had:
(non-nil value, non-nil-non-grpc error)
to
(nil value, non-nil-gRPC error)
and it is a follow-up of PR #7814.
---
> x/bank/keeper: fix a missing gRPC error in AllBalances

- x/gov/spec/01_concepts.md
The x/gov docs state that
"Proposals can be accepted before the end of the voting period if they meet a special condition. Namely, if the ratio of `Yes` votes to `InitTotalVotingPower`exceeds 2:3, the proposal will be immediately accepted, even if the `Voting period` is not finished. `InitTotalVotingPower` is the total voting power of all bonded Atom holders at the moment when the vote opens."
This is not correct and not the current functionality of the module.  This PR removes the incorrect description from the governance docs.
closes: #XXXX
---
> Fix incorrect description in governance docs

- x/auth/client/cli/tx_multisign.go
- x/auth/client/cli/tx_sign.go
This is to correctly handle deferred Close()
calls on writable files.
---
> use named return value and closure

- x/ibc/applications/transfer/handler_test.go
- x/ibc/applications/transfer/keeper/relay.go
bug reported by @andrey-kuprianov in this [comment](https://github.com/cosmos/cosmos-sdk/pull/7993#issuecomment-741732078)
closes: #8120
---
> fix ibc-transfer receiving denom bug

- testutil/ioutil.go
- testutil/ioutil_test.go
- x/auth/client/cli/cli_test.go
- x/auth/client/cli/encode_test.go
- x/auth/client/rest/rest_test.go
- x/auth/client/tx_test.go
- x/distribution/client/cli/tx_test.go
- x/gov/client/cli/parse_test.go
- x/params/client/cli/tx_test.go
Files returned by WriteToNewTempFile are cleaned up
automatically at the end of a test case execution.
WriteToNewTempFile now relies on the TB.TempDir()
function provided by the testing std package.
TempFile returns a temporary file that can be used
within a test case and is automatically removed
at the end of the test execution.
---
> testutil: new TempFile function, simplify WriteToNewTempFile

- go.mod
- go.sum
Updates cosmos/go-bip39 to version v1.0.0 which
features performance upgrades that bring 12+ searches
down from 24.3us to 1.4us (so 108.33ns per fetch)
after PR https://github.com/cosmos/go-bip39/pull/2.
---
> go.mod: update cosmos/go-bip39 to v1.0.0

- go.mod
- snapshots/helpers_test.go
- snapshots/manager_test.go
- snapshots/store_test.go
- testutil/ioutil.go
- x/distribution/client/cli/cli_test.go
- x/gov/client/cli/cli_test.go
Also replace defer calls with testing.T.Cleanup()
---
> use testutil in test cases

- simapp/simd/cmd/root.go
Before:
```
➜  cosmos-sdk git:(master) ./build/simd start
{"level":"info","time":"2020-12-10T11:53:02+01:00","message":"starting ABCI with Tendermint"}
{"level":"info","module":"proxy","impl":{"Logger":{}},"time":"2020-12-10T11:53:02+01:00","message":"Starting multiAppConn service"}
{"level":"info","module":"proxy","connection":"query","module":"abci-client","impl":"marshaling error: json: unsupported type: abcicli.Callback","time":"2020-12-10T11:53:02+01:00","message":"Starting localClient service"}
{"level":"info","module":"proxy","connection":"snapshot","module":"abci-client","impl":"marshaling error: json: unsupported type: abcicli.Callback","time":"2020-12-10T11:53:02+01:00","message":"Starting localClient service"}
{"level":"info","module":"proxy","connection":"mempool","module":"abc …
```
> Switch LogFormat to Plain by default

- go.mod
- go.sum
Updates cosmos/go-bip39 to version v1.0.0 which
features performance upgrades that bring 12+ searches
down from 24.3us to 1.4us (so 108.33ns per fetch)
after PR cosmos/go-bip39#2.
From: #8127
Thanks: @odeke-em
---
> Launchpad: update cosmos/go-bip39 to v1.0.0

- x/auth/client/cli/broadcast.go
- x/auth/client/cli/cli_test.go
Add a fully E2E test to:
- create a tx with 2 signers (`val0` and `val1`) with sign mode direct
- make them sign one after the other
- broadcast the tx
- make sure the tx is successful by querying state
closes: #XXXX
---
> Add test with Multi Signers into Robert's TxSign PR

- CHANGELOG.md
closes: #8104 
Upon merging this PR into master, `v0.40.0-rc5` will be tagged its merge commit.
Waiting on:
---
> Update changelog for tagging v0.40.0-rc5

- x/ibc/core/02-client/keeper/client_test.go
- x/ibc/core/02-client/keeper/grpc_query_test.go
- x/ibc/core/02-client/types/height.go
- x/ibc/core/03-connection/keeper/handshake_test.go
- x/ibc/core/exported/client.go
- x/ibc/light-clients/07-tendermint/types/header_test.go
- x/ibc/light-clients/07-tendermint/types/proposal_handle_test.go
Currently `x/ibc/core/exported.Height` has `Decrement` method but doesn't have `Increment`.
This PR includes a small fix that adds `Increment` method to `Height` interface.
closes: #XXXX
---
> Add Increment method to Height interface

- client/broadcast.go
Follows up PR #4876 which removed the return on non-nil errors
to always return a non-nil REST response regardless of error.
The checks performed seem benign and the return result is the
same.
This change uses the reverse conditional refactoring method
to gut out nesting and many conditions.
Noticed while hunting through types.ParseABCILogs.
Fixes #8181
---
> client: remove redundant/repeated code

- x/ibc/light-clients/07-tendermint/types/upgrade.go
- x/upgrade/abci.go
- x/upgrade/abci_test.go
- x/upgrade/keeper/keeper.go
- x/upgrade/keeper/keeper_test.go
The following changes were manually tested by @colin-axner and I and we've confirmed that the client will upgrade and old connections will persist and that new connections can be made.
The main issue was a misunderstanding of the upgrade feature which would commit the plan Height and then halt, rather than committing the height before it and halting.
No changes were necessary to IBC, tho some more readable errors are introduced.
---
> Fix IBC upgrade: manually tested

- x/staking/client/cli/cli_test.go
- x/staking/simulation/genesis_test.go
- x/staking/simulation/params_test.go
- x/staking/types/params.go
> Update default historical header number for stargate

- x/ibc/core/04-channel/keeper/keeper.go
- x/ibc/core/04-channel/keeper/keeper_test.go
- x/ibc/core/04-channel/keeper/packet_test.go
Thanks @ancazamfir for alerting us to this bug!!!!
Here is the explanation from @AdityaSripal on why this is a bug
```
Thanks to @Anca’s report we found a bug in the timeout logic. We sometimes could not prove timeouts on UNORDERED channels if packets had already been relayed on the channel.
This is because the nonexistence proof for the packet receipt would contain a left proof which would prove the existence of a receipt at an earlier sequence
However, this proof would fail on Calculate since we cannot calculate the root of a proof that had an empty leaf value. And currently, packet receipts are simply empty byte strings stored on chain.
This would fail on VerifyNonmembership through the following sequence:
```
I have manually tested this fix with the relayer for both a clean channel …
> Fix IBC Timeout verification bug

- types/decimal.go
Simplify the code in Dec.Power to unconditionally divide by 2, since:
x /= 2
is the same result for both even and odd integers, and produces the
floor of the result of x/2 -> ⌊x/2⌋:
```
99/2 ~> 49.5 ⌊49.5⌋ = 49
98/2 ~> 49.0 ⌊49.0⌋ = 49
```
aka "integer truncation".
Fixes #7924
---
> types: unconditionally divide by 2 because of integer truncation ⌊x/2⌋

- Makefile
- client/docs/swagger-ui/swagger.yaml
- scripts/protoc-swagger-gen.sh
> Fix proto-swagger-gen

- x/ibc/core/04-channel/keeper/handshake.go
- Call connectionEnd.GetVersions() once in channel handshakes
- rename var counterPartyHops to counterpartyHops in channel handshake
ref: #7949
---
> minor channel fixes

- testutil/network/network.go
This is a 1 line change to fix something I found a while back
closes: #8000
> test: Use the bond denomination from the configuration, not the default

- proto/cosmos/base/tendermint/v1beta1/query.proto
The following errors are occurring when these protos are compiling because they exist in a sub-package `cosmos.base.tendermint` but are trying to refer to toplevel `.tendermint` types:
```
cosmos/base/tendermint/v1beta1/query.proto:87:3: "tendermint.types.BlockID" is resolved to "cosmos.base.tendermint.types.BlockID", which is not defined. The innermost scope is searched first in name resolution. Consider using a leading '.'(i.e., ".tendermint.types.BlockID") to start from the outermost scope.
cosmos/base/tendermint/v1beta1/query.proto:88:3: "tendermint.types.Block" is resolved to "cosmos.base.tendermint.types.Block", which is not defined. The innermost scope is searched first in name resolution. Consider using a leading '.'(i.e., ".tendermint.types.Block") to start from the outermost …
```
> Fix tendermint query proto scoping

- server/README.md
- server/export_test.go
- simapp/app_test.go
- simapp/genesis.go
- simapp/simd/cmd/root.go
- simapp/state.go
- simapp/test_helpers.go
- x/gov/genesis_test.go
- x/upgrade/abci_test.go
We are not sharing the `simapparams.EncodingConfig` in places where we sure share it. 
closes: #7685
---
> appcreator: Reuse encoding config instead of recreating it

- x/ibc/core/exported/client.go
- x/ibc/light-clients/06-solomachine/types/header.go
- x/ibc/light-clients/06-solomachine/types/misbehaviour_handle_test.go
- x/ibc/light-clients/07-tendermint/types/header.go
- x/ibc/light-clients/07-tendermint/types/misbehaviour.go
I'm not sure if this is required, but `ClientState` and `ConsensusState` have `proto.Message` so it seems to me `Header` and `Misbehaviour` should as well
closes: #XXXX
---
> ibc: add proto message to Header and Misbehaviour

- CHANGELOG.md
- codec/amino_codec_test.go
- docs/basics/app-anatomy.md
- simapp/app.go
- simapp/encoding.go
- simapp/simd/cmd/genaccounts_test.go
- simapp/simd/cmd/root.go
- x/auth/ante/sigverify_test.go
- x/auth/keeper/keeper_test.go
- x/auth/simulation/decoder_test.go
- x/auth/types/common_test.go
- x/auth/vesting/types/common_test.go
- x/bank/keeper/keeper_test.go
- x/capability/simulation/decoder_test.go
- x/distribution/simulation/decoder_test.go
- x/evidence/keeper/querier_test.go
- x/gov/keeper/common_test.go
- x/gov/simulation/decoder_test.go
- x/mint/simulation/decoder_test.go
- x/slashing/simulation/decoder_test.go
- x/staking/keeper/grpc_query_test.go
- x/staking/simulation/decoder_test.go
in https://github.com/cosmos/cosmos-sdk/commit/9bd42ace6b we renamed and market deprecated the `simapp.MakeEncodingConfig` function. We forgot about `MakeCodecs`, which is used only in tests. Also the SDK documentation with regards to `MakeCodecs` was outdated. 
Related to: https://github.com/cosmos/cosmos-sdk/issues/7642
---
> codecs: rename MakeCodecs rename and docs update

- x/mint/spec/02_state.md
> [docs] x/mint - general audit and cleanup

- .build.sh
Fix buildlib.sh install path in .build.sh.
---
> buildsystem: fix reproducible builds

- server/rosetta/README.md
> [Rosetta] add: rosetta docs

- CHANGELOG.md
Sorry I forgot to add the changelog for #8359
closes: #XXXX
---
> 8359 changelog entry

- x/evidence/legacy/v038/types.go
- x/evidence/types/evidence.go
- x/ibc/light-clients/07-tendermint/types/consensus_state.go
- x/upgrade/keeper/keeper.go
- x/upgrade/legacy/v038/types.go
- x/upgrade/types/plan.go
Co-authored-by: mergify[bot] <37929162+mergify[bot]@users.noreply.github.com>
backport #8282 
---
> backport: fix zero time checks (#8282)

- x/ibc/core/02-client/keeper/grpc_query_test.go
- x/ibc/core/02-client/types/query.go
- x/ibc/core/03-connection/keeper/grpc_query_test.go
- x/ibc/core/03-connection/types/msgs.go
- x/ibc/core/03-connection/types/query.go
- x/ibc/core/04-channel/keeper/grpc_query_test.go
- x/ibc/core/04-channel/types/query.go
backport 99aaa5cd795de5c16ab6c414575fd78581370da3 to release v0.40.1
---
> Add missing unpack interfaces functions to IBC (#8359)

- CHANGELOG.md
- docs/architecture/adr-024-coin-metadata.md
- docs/core/proto-docs.md
- go.sum
- proto/cosmos/bank/v1beta1/query.proto
- x/bank/client/cli/cli_test.go
- x/bank/client/cli/query.go
- x/bank/client/rest/grpc_query_test.go
- x/bank/client/rest/query_test.go
- x/bank/keeper/genesis_test.go
- x/bank/keeper/grpc_query.go
- x/bank/keeper/grpc_query_test.go
- x/bank/keeper/keeper.go
- x/bank/keeper/keeper_test.go
- x/bank/types/errors.go
- x/bank/types/query.pb.go
- x/bank/types/query.pb.gw.go
> backport: client denom metadata queries

- CHANGELOG.md
- x/auth/client/rest/rest_test.go
- x/ibc/applications/transfer/module.go
- x/ibc/applications/transfer/types/codec.go
- x/ibc/applications/transfer/types/msgs.go
- x/ibc/applications/transfer/types/msgs_test.go
thanks @fedekunze for doing all the work
I copied over the relevant code for `MsgTransfer` amino registration. Will quickly do basic tests with the relayer to ensure everything still functions fine
closes: #8266 
---
> IBC amino for `MsgTransfer` only, credit: @fedekunze

- CHANGELOG.md
- x/bank/module.go
- x/bank/types/balance.go
- x/bank/types/balance_test.go
- x/bank/types/genesis.go
- x/bank/types/genesis_test.go
- x/bank/types/metadata.go
- x/bank/types/metadata_test.go
- x/bank/types/supply.go
> stargate: balance and metadata validation

- x/ibc/applications/transfer/module.go
As the attribute value of the event, set Acknowledgement formatted with "%v". 
However, since Acknowledgement contains a pointer, its value is non-deterministic.
My understanding is that the value of event attribute must be deterministic.
closes: #XXXX
---
> ibc-transfer: fix non-deterministic attribute value

- crypto/armor_test.go
- crypto/keys/internal/benchmarking/bench.go
- crypto/keys/secp256k1/bench_test.go
- simapp/sim_bench_test.go
- store/cache/benchmark_test.go
- store/cachekv/store_bench_test.go
- store/cachekv/store_test.go
- store/iavl/store_test.go
- store/rootmulti/store_test.go
- types/address_bench_test.go
- types/coin_benchmark_test.go
- types/decimal_test.go
- x/auth/keeper/keeper_bench_test.go
- x/bank/bench_test.go
- x/mint/types/minter_test.go
With this change, we'll get details on the number of
allocations performed by code. Later on when we have
continuous benchmarking infrastructure, this change
will prove useful to flag regressions.
Fixes #8459
---
> all: ensure b.ReportAllocs() in all the benchmarks

- docs/core/cli.md
- server/util.go
allows clients access values in env variables
Signed-off-by: Artur Troian <troian.ap@gmail.com>
allows clients access values in env variables
closes #8179
---
> fix: bind values from env variables to flags

- store/rootmulti/store.go
See https://github.com/cosmos/cosmos-sdk/pull/8396#discussion_r565654207
---
> store/multistore: revert a height limit increase from #8396

- CHANGELOG.md
- x/bank/types/metadata.go
- x/bank/types/metadata_test.go
ref https://github.com/cosmos/cosmos-sdk/pull/8417#issuecomment-766189845
Thanks @iramiller
> bank: additional client metadata validation

- snapshots/helpers_test.go
- snapshots/store_test.go
The use testing.T.TempDir() seems to cause test failures
in CI environvements in those cases where temporary
directories' subdirs are created with permissions that
are different from the defaults used by testing.T.TempDir().
The snapshots package's tests seem to be heavily affected,
thus this replaces testing.T.TempDir() occurrences with
ioutil.TempDir() calls.
Related upstream issue:
- golang/go#40853
---
> snapshots: fix flaky tests

- CHANGELOG.md
- x/ibc/core/04-channel/keeper/packet.go
- x/ibc/core/04-channel/types/events.go
Closes #8445 
Please backport to `0.41.x` branch if merged to master (non-consensus breaking, as events are not in any header hash)
closes: #XXXX
---
> Add packet_connection attribute to packet lifecycle methods

- CHANGELOG.md
- x/bank/types/metadata.go
- x/bank/types/metadata_test.go
> backport #8479

- CHANGELOG.md
> Add changelog for key migration fix

- CHANGELOG.md
- server/tm_cmds.go
If the user specifies an incorrect `--home`, then the old behaviour
would automatically populate it with fresh values, but we should
fail instead.
Any `appd tendermint show-*` subcommands should not create files, for predictability and ease of debugging.
closes: #8478
---
> fix: tendermint subcommands should not create missing files

- simapp/test_helpers.go
- x/bank/keeper/genesis.go
- x/bank/keeper/genesis_test.go
- x/bank/keeper/grpc_query_test.go
- x/bank/keeper/keeper.go
- x/bank/keeper/keeper_test.go
- x/bank/keeper/querier_test.go
- x/crisis/handler_test.go
- x/evidence/keeper/keeper_test.go
- x/staking/genesis_test.go
- x/staking/handler_test.go
- x/staking/keeper/slash_test.go
- x/staking/keeper/validator_test.go
> [Bank Refactor] Frojdi jonathan/remove setsupply

- CHANGELOG.md
- crypto/keyring/legacy.go
- crypto/keyring/legacy_test.go
Ref: https://github.com/cosmos/cosmos-sdk/pull/8436#pullrequestreview-576204999 
---
> Remove Info Importer from legacy keybase

- snapshots/helpers_test.go
- snapshots/store_test.go
> snapshots: fix flaky tests [0.41-cherry-pick]

- server/grpc/grpc_web.go
- snapshots/helpers_test.go
- snapshots/store_test.go
- x/authz/client/cli/cli_test.go
- x/authz/keeper/keeper_test.go
- x/feegrant/ante/fee_test.go
- x/feegrant/client/cli/cli_test.go
- x/feegrant/client/cli/query.go
- x/feegrant/client/rest/grpc_query_test.go
- x/feegrant/genesis_test.go
- x/feegrant/simulation/decoder_test.go
- x/feegrant/simulation/genesis_test.go
- x/feegrant/types/basic_fee_test.go
- x/feegrant/types/expiration_test.go
- x/feegrant/types/grant.go
- x/feegrant/types/grant_test.go
- x/feegrant/types/msgs.go
- x/feegrant/types/periodic_fee_test.go
Document with inline comments the changes introduced
in https://github.com/cosmos/cosmos-sdk/pull/8475.
Run make format.
---
> snapshots: document use of ioutil.TempDir()

- CHANGELOG.md
- docs/architecture/README.md
- docs/architecture/adr-038-state-listening.md
ADR-038 State Listening
This PR introduces an ADR for the state listening features discussed in #7888 and #7889, and is foundational to syncing state to an external database (#7099)
[Tentative implementation branch](https://github.com/i-norden/cosmos-sdk/tree/multistore_state_listening)
closes: #7888 and #7889
---
> ADR 038: State Listening

- x/simulation/log.go
From: #8217
Closes: #6784
Thanks: @PrathyushaLakkireddy for the original patch.
Co-authored-by: Alessio Treglia <alessio@tendermint.com>
Co-authored-by: Anil Kumar Kammari <anil@vitwit.com>
---
> Launchpad: simulation: close open files, fix error checks

- x/bank/types/balance.go
- x/bank/types/balance_test.go
Closes: #8530
From: #8531
Thanks: @odeke-em for pointing this out.
---
> 0.41 backport: bank: don't ignore errors returned by Balance.GetAddress()

- x/auth/ante/ante_test.go
- x/auth/ante/fee_test.go
- x/auth/ante/testutil_test.go
- x/auth/vesting/handler_test.go
> [Bank refactor]: finalize removal of setbalances from auth

- types/query/filtered_pagination_test.go
- types/query/pagination_test.go
> [Bank refactor] fix pagination tests

- types/query/filtered_pagination_test.go
- types/query/pagination_test.go
closes: #XXXX
cc\ @anilCSE 
---
> Cleanup pagination tests

- CHANGELOG.md
- x/staking/keeper/keeper.go
- x/staking/keeper/validator.go
- x/staking/keeper/validator_bench_test.go
- x/staking/keeper/validator_test.go
- x/staking/teststaking/validator.go
This PR removes the `GetValidator` caching that is currently present, allowing for concurrent queries. As shown inside #8545, the removal of the caching does not impact performances in a negative way. Indeed, it improves them by quite a lot (~ 52% increase in ns/op).
Closes: #8545
---
> Removed GetValidator caching to fix concurrency error

- x/ibc/core/02-client/keeper/grpc_query.go
> ibc : replace strings.Contains to bytes.Contains

- types/bench_test.go
- types/int.go
- types/int_test.go
- types/uint.go
- types/uint_test.go
Instead of using len((*math/big.Int).Bytes()) == 0, which expensively
creates a byte slice and marshals a value, on the majority hot path,
instead use the cheaper method .BitLen() to check if 0.
Benchmarking results, just from types:
```shell
name                                           old time/op    new time/op    delta
CoinsAdditionIntersect/sizes:_A_1,_B_1-8          132ns ± 2%     126ns ±13%   -4.55%  (p=0.050 n=10+10)
CoinsAdditionIntersect/sizes:_A_5,_B_5-8         1.41µs ± 3%    1.41µs ± 2%     ~     (p=1.000 n=10+10)
CoinsAdditionIntersect/sizes:_A_5,_B_20-8        2.30µs ± 1%    2.27µs ± 3%     ~     (p=0.066 n=10+10)
CoinsAdditionIntersect/sizes:_A_1,_B_1000-8      30.9µs ± 3%    30.7µs ± 1%     ~     (p=0.218 n=10+10)
CoinsAdditionIntersect/sizes:_A_2,_B_1000-8      31.4µs ± …
```
> types: use (*math/big.Int).BitLen() == 0 to check if value is 0

- x/gov/types/proposal.go
> Optimize create proposal

- CHANGELOG.md
- x/staking/keeper/keeper.go
- x/staking/keeper/validator.go
- x/staking/keeper/validator_bench_test.go
- x/staking/keeper/validator_test.go
- x/staking/teststaking/validator.go
backports #8546
* Removed GetValidator caching to fix concurrency error
* Fixed linting and added CHANGELOG entry
* Moved benchmark test into its own file
* Moved CHANGELOG entry to bug fix
* Update CHANGELOG.md
Co-authored-by: Cory <cjlevinson@gmail.com>
Co-authored-by: Amaury <amaury.martiny@protonmail.com>
Co-authored-by: Cory <cjlevinson@gmail.com>
Co-authored-by: mergify[bot] <37929162+mergify[bot]@users.noreply.github.com>
closes: #XXXX
---
> [backport/v0.41.x] Removed GetValidator caching to fix concurrency error (#8546)

- baseapp/grpcrouter.go
- baseapp/grpcserver.go
- client/grpc_query.go
- server/grpc/server.go
- server/grpc/server_test.go
- server/start.go
- server/types/app.go
- testutil/network/util.go
backports #8549
* Make gRPC requests go through tendermint Query
* Remove commented code
* Dry run in InitChain?
* Save type of first run
* Add metadata in repsonse
* Factorize some code
* Fix lint
* Update comments
* Fix md test
* Fix test expected
* Don't put RunGRPCQuery as clientCtx method
* Update baseapp/grpcserver.go
Co-authored-by: Robert Zaremba <robert@zaremba.ch>
* Address review comments
Co-authored-by: Robert Zaremba <robert@zaremba.ch>
closes: #XXXX
---
> [backport/v0.41.x]: Make gRPC requests go through tendermint Query (#8549)

- docs/core/cli.md
- server/util.go
allows clients access values in env variables
From: #8337
> [backport/v0.41.x]: fix: bind values from env variables to flags

- x/crisis/spec/01_state.md
- x/crisis/spec/02_messages.md
- x/crisis/spec/03_events.md
Backport of #8269 
* update docs
* review changes
closes: #XXXX
---
> [backport/v0.41.x] x/crisis - general audit and cleanup (#8269)

- codec/types/any.go
- codec/types/any_test.go
Avoids a bleed out attack in which a node can be made to allocate
memory slowly or very fast in small strides, by sending bad data
to code that invokes NewAnyWithCustomTypeURL, in which we
unconditionally returned a new Any object. On a 64-bit machine,
this would waste 96 bytes per invocation even on error.
Added a test to ensure zero allocations with a fixed error returned.
Also added a benchmark which shows reduction in wasted allocations and
wasted CPU time:
```shell
name                                            old time/op    new time/op    delta
NewAnyWithCustomTypeURLWithErrorReturned-8      142ns ± 6%      55ns ±12%   -61.65%  (p=0.000 n=9+10)
name                                            old alloc/op   new alloc/op   delta …
```
> codec/types: avoid unnecessary allocations for NewAnyWithCustomTypeURL on error

- crypto/hd/hdpath.go
- crypto/hd/hdpath_test.go
Detected during my audit, right before fuzzing, the code that
checked for presence of hyphens per path segment assumed that
the part would always be non-empty. However, with paths such as:
* m/4/
* /44/
* m/4///
it'd panic with a runtime slice out of bounds.
With this new change, we now:
* firstly strip the right trailing slash
* on finding any empty segments of a path return an error
Fixes #8557
---
> crypto/hd: make DerivePrivateKeyForPath error and not panic on trailing slashes

- x/gov/simulation/decoder.go
- x/gov/simulation/decoder_test.go
The code in NewDecodeStore decoded the wrong proposal due
to a typographical error, but the tests used the exact same
value for the key value pairs hence the typo could never be caught.
I noticed it during an audit of the code, and I've fixed the
tests to pass in varying values for the various key value pairs.
Fixes #8570
---
> x/gov/simulation: fix wrong NewDecodeStore Proposal decoding + proper tests

- .mergify.yml
to backport a pr add the label `backport-to-v0.41.x`
for every release branch, we will need to replace or add an entry. 
closes: #XXXX
---
> add backport label to prs

- x/bank/types/metadata_test.go
adds an additional test case when the display denom is the base denom (exponent = 0)
> bank: additional denom metadata test case

- CHANGELOG.md
- RELEASE_NOTES.md
- go.mod
- go.sum
> Release v0.41.2

- testutil/network/network.go
* Tendermint's `DefaultLogLevel` is now a string.
closes: #XXXX
---
> fix testutil/network build

- CHANGELOG.md
- RELEASE_NOTES.md
Urgent maintenance release. This fixes a build failure in v0.41.2
---
> Release v0.41.3

- server/util.go
This PR fixes the wrong filename (`app.toml`) in the following error message, when reading `config.toml`:
`Error: failed to read in app.toml: While parsing config: (18, 12): unescaped control character U+000A`
closes: #7476
---
> fix wrong filename in error message

- x/auth/spec/01_concepts.md
- x/auth/spec/05_vesting.md
- x/auth/spec/07_params.md
- x/bank/spec/02_keepers.md
- x/bank/spec/03_messages.md
- x/distribution/spec/02_state.md
- x/distribution/spec/04_messages.md
- x/distribution/spec/README.md
* basic code clean up
* revert MsgVerifyInvariant
* review changes
* review changes
* review changes
* review changes
* review changes
* review changes
Co-authored-by: mergify[bot] <37929162+mergify[bot]@users.noreply.github.com>
closes: #XXXX
---
> backport: x/{auth, bank, distr} docs basic cleanup (#8268)

- types/address/hash.go
Recent linter update created new issues in master. This solves issues in types/address - which in fact are false positives.
closes: #8670
---
> linter: ignore false positives in types/address

- types/address/hash.go
- types/address/hash_test.go
Changing the unsafe string -> bytes conversion
closes: #8670
---
> rework unsafe string -> bytes conversion #8674

- client/keys/migrate.go
- codec/legacy/codec.go
- crypto/keyring/keyring.go
ref: #8639 
I have no idea what the `keys migrate` was doing, but imo it was bugged for multiple reasons:
- imo we should have two `--home` flags: one for the location of the old keyring, and one for the location of the new keyring. I added a `--old-home` flag to it.
- In practise for Gaia, we would have `--old-home ~/.gaiacli --home ~/.gaiad`
- If both are same, then it's an in-place migration
- the previous version migrated a `TypeLocal` to a `TypeLocal` (that's correct), a `TypeOffline` to a `TypeOffline` (correct too), but migrated `Type{Ledger,Multi}` both to `TypeOffline` (why???). Anyways, now the migration migrates to the correct keyring type.
I followed Sahith's test steps with a ledger key, and could migrate & sign with a tx with the new keyring
We should test:
---
Before we can …
> Fix `keys migrate` command

- scripts/protoc-swagger-gen.sh
- scripts/protocgen.sh
Adding indentation to multi-line commands - to make it more clear that a command has multiple lines.
Context: https://github.com/cosmos/cosmos-sdk/pull/8559#discussion_r582921803  
When temporally removing some section from the scripts they got indented and made changes in other PR.
---
> scripts: indent multiline commands

- CHANGELOG.md
Adds a notice in changelog warning non-hub Cosmos SDK based chains to not use the v0.41.x series due to bug in evidence's usage of bech32 prefixes (#8461).
This has also been added to github release notes [here](http://github.com/cosmos/cosmos-sdk/releases/v0.41.3).
---
> Add warning notice in changelog for v0.41.x bug (ref: #8461)

- .github/workflows/proto-docker.yml
I have an arm based mac and cat run this image. 
I think this works. Will need to test when deployed
---
> proto-docker: add arm 

- x/bank/types/balance.go
- x/bank/types/balance_test.go
- x/bank/types/genesis_test.go
allow accounts to have a balance of 0 in genesis
closes: #8626 
---
> auth: allow 0 coin accounts in genesis

- Makefile
Previously, we set build_tags before updating the options for DB backend.
This does't work with BadgerDB - it BUILD_TAGS which must be included in build_tags.
---
> Makefile: fix build_tags update

- CHANGELOG.md
- store/cachekv/store.go
- x/bank/types/balance.go
- x/bank/types/balance_test.go
Backports the genesis speed ups in #8719 to 0.41.x to improve node startup performance.
---
> Backport genesis speed ups to 0.41.x

- CHANGELOG.md
- store/cachekv/store.go
Backports the KVCache optimizations from #8719 to launchpad.
______
______
For admin use:
> Backport KVCache speeds ups to launchpad.

- server/grpc/server_test.go
- x/auth/tx/service.go
- x/auth/tx/service_test.go
- x/auth/tx/xauthclient.go
companion PR of #8734.
#8734 solves the issue in the correct way, but introduces breaking changes. This PR solves the same issue, without intoroducing breaking changes, but with some duplicate code.
---
> Use x/auth/client for querying Txs

- client/keys/migrate.go
- crypto/keyring/keyring.go
Avoid namespace clash with the InfoImporter interface
that already exists in the v0.41 release series.
---
> Rename InfoImporter -> LegacyInfoImporter

- x/staking/bench_test.go
This benchmark examines how ValidateGenesis behaves.
In a follow-up issue, I'll show how it reveals an inefficiency
that'll affect trying to load repeatedly retrieve Validators'
ConsAddress values.
Updates #8744
---
> x/staking: add ValidateGenesis benchmark

- crypto/keys/internal/benchmarking/bench.go
genPrivKey rejects invalid fieldelems, so we must use a real reader
instead of the zero reader.
closes: #8741
---
> crypto/keys/internal: use crypto/rand.Reader for generating private key

- x/slashing/keeper/infractions.go
Change absent validator info log to debug.
closes: #XXXX
---
> slashing: absent val to DEBUG

- RELEASE_NOTES.md
> update: release notes for v0.41.4

- simapp/sim_bench_test.go
- types/address_bench_test.go
Some benchmarks panics.
closes: #8762
---
> all: fix some benchmarks panics by honoring skip if set

- types/address.go
Fixes the `test-race` warnings from simultaneous read and write to the address cache
Ref: https://github.com/cosmos/cosmos-sdk/pull/8717#issuecomment-789646701
---
> Lock mutex on getting element from cache

- x/staking/client/rest/query.go
- x/staking/types/msg.go
closes #8760
introduced in https://github.com/cosmos/cosmos-sdk/pull/8512#discussion_r578120187, too bad the gogoproto-generated files don't export those as constants.
---
> Fix typo in querying events

- x/feegrant/simulation/decoder_test.go
This seems to be an unintended change from https://github.com/cosmos/cosmos-sdk/pull/8780. Reverting it
closes: #XXXX
---
> Revert unintended skip test in feegrant

- x/auth/legacy/v040/migrate.go
ref: https://github.com/cosmos/cosmos-sdk/issues/8776#issuecomment-790552126
When migrating genesis to v0.40, set pub_key to null if account is multisig as a quick fix
closes: #8776
---
> fix multisig account pubkeys migration

- store/cachekv/memiterator.go
Use list.Len()
closes: #8795
---
> mem: use list.Len

- CHANGELOG.md
- RELEASE_NOTES.md
CHANGELOG and RELEASE NOTES
---
> finalize changelog and release notes

- x/gov/client/cli/cli_test.go
- x/gov/client/rest/grpc_query_test.go
- x/gov/client/rest/rest_test.go
- x/gov/client/utils/utils.go
- x/gov/client/utils/utils_test.go
Fix `q gov proposals` command's mishandling of the
--status parameter's values.
Closes: #8806
---
> x/gov: fix NormalizeProposalType() return values

- store/cachekv/memiterator.go
- store/cachekv/store.go
- types/kv/kv.go
- types/kv/list.go
Reduces CPU burn by using a typed List to avoid the expensive type
assertions from using an interface. This is the only option for now
until Go makes generics generally available.
The change brings time spent on the time assertion cummulatively to:
580ms down from 6.88s
Explanation:
The type assertions were showing up heavily in profiles:
* Before this commit
```shell
Total: 42.18s
ROUTINE ======================== github.com/cosmos/cosmos-sdk/store/cachekv.newMemIterator
in /Users/emmanuelodeke/go/src/github.com/cosmos/cosmos-sdk/store/cachekv/memiterator.go
14.01s     18.87s (flat, cum) 44.74% of Total
.          .     17:	items      []*kv.Pair
.          .     18:	ascending  bool
.          .     19:}
.          .     20:
.          .     21:func newMemIterator(start, end []byte, items …
```
> store/cachekv: use typed types/kv.List instead of container/list.List

- CHANGELOG.md
- types/errors/errors.go
- x/auth/ante/sigverify.go
- x/auth/legacy/legacytx/stdtx.go
- x/auth/signing/sig_verifiable_tx.go
- x/auth/testutil/suite.go
- x/auth/tx/builder.go
- x/auth/tx/builder_test.go
> update SigVerifiableTx.GetPubKeys to return an error

- .github/workflows/release-sims.yml
- .github/workflows/sims.yml
- .github/workflows/test.yml
Upstream's latest changes are causing mayhem in
the build pipelines. This change reverts upstream's
latest commit.
Upstream issue: https://github.com/rokroskar/workflow-run-cleanup-action/issues/16
---
> ci: revert cleanup action's upstream latest changes

- crypto/keyring/keyring.go
This PR automatically trusts the calling application with its data,
avoiding all the annoying keychain popups that appears when dealing with
keys (list, add...).
closes: #8809
---
> Keyring: Add trust to macOS Keychain for caller app by default

- CHANGELOG.md
> merge v0.42.0 changelog

- CHANGELOG.md
> v0.42.1 Changelog update

- x/bank/app_test.go
- x/bank/handler_test.go
> Fix SendToModuleAccountTest

- x/distribution/types/fee_pool_test.go
- x/distribution/types/params.go
- x/distribution/types/params_internal_test.go
- x/distribution/types/params_test.go
> x/distribution: fix module's parameters validation

- .github/workflows/test.yml
> ci: test detection must not hide errors

- x/auth/client/cli/cli_test.go
- x/auth/client/rest/rest_test.go
- x/authz/client/cli/tx_test.go
- x/authz/client/rest/grpc_query_test.go
CLI tests must be excluded by race detection due
to a well-known Tendermint issue.
Closes: #8923
---
> add +nobuild flags to all relevant test cases

- .github/workflows/test.yml
cherry-pick 641b13ee47d59c838cc05d1b288a496c4d9f3301
---
> backport test failure detection ci fix (#8924)

- testutil/network/util.go
This PR adds the ability to specify custom `x/auth` accounts and `x/bank` balances inside the genesis state when running CLI unit tests. 
The rationale behind this is allowing custom chains that develop custom `AccountI` implementations to initialize the genesis state with their custom implementation as well. 
closes: #XXXX
---
> Allow to specify custom accounts and balances inside in-process local testing networs

- .deepsource.toml
- client/context_test.go
- x/auth/ante/ante_test.go
- x/auth/client/rest/rest_test.go
- x/auth/tx/builder_test.go
- x/distribution/legacy/v043/store_test.go
- x/gov/legacy/v043/store_test.go
- x/slashing/legacy/v043/store_test.go
- x/staking/legacy/v043/store_test.go
Hey, I'm a Developer Outreach at [DeepSource](https://deepsource.io/) and ran DeepSource analysis on my fork of the repo. It found some interesting [code quality improvements](https://deepsource.io/gh/akshgpt7/cosmos-sdk/) to consider.
This PR fixes a few of the issues detected for you to assess if it is right for you.
Happy to provide the tweaks separately otherwise :)
- Clean up copied struct fields with type conversion
- Merge variable declaration with assignment
- Fix unnecessary typecasting on `bytes.Buffer`
- Replace `bytes.Compare` with `bytes.Equal`
- Add `.deepsource.toml` file for continuous analysis on bug risks/performance/code-quality issues on new changes.
---
> chore: refactor code quality issues

- CHANGELOG.md
- x/genutil/client/cli/migrate.go
- x/genutil/client/cli/migrate_test.go
- x/genutil/client/cli/validate_genesis_test.go
- x/genutil/legacy/v043/migrate.go
- x/gov/legacy/v040/genesis.pb.go
- x/gov/legacy/v040/gov.pb.go
- x/gov/legacy/v043/json.go
- x/gov/legacy/v043/json_test.go
- x/gov/legacy/v043/keys.go
- x/gov/legacy/v043/store.go
- x/gov/legacy/v043/store_test.go
closes: #8822 
To Test:
- run a 0.42 node for a couple of blocks
- stop the node, run `simd export > test.json`
- on this branch, run `simd migrate v0.43 test.json`
---
> Add 0.43 CLI JSON `migrate` command

- proto/cosmos/bank/v1beta1/genesis.proto
- x/bank/keeper/genesis.go
- x/bank/keeper/genesis_test.go
- x/bank/types/genesis.go
> Fix genesis supply handling

- types/address.go
- types/address_race_test.go
`lru.Get` is not safe for concurrent access. Besides doing a lookup it also manipulates the structure by moving the data to the front. So `RWMutex` can't be used to protect the cache.
---
> fix race condition in address.String

- crypto/ledger/ledger_test.go
Updates ledger tests to use proto for pubkey marshaling instead of bech32.
This branch merges to `robert/rm-bech32-pk`. Once it will be merged, I will update this branch to merge into `master`.
Related to:  Remove bech32 PubKey support #7477 
---
> Update ledger bech32 tests

- docs/ibc/custom.md
- docs/ibc/integration.md
- docs/ibc/overview.md
- docs/ibc/relayer.md
copied over from ibc-go [pr](https://github.com/cosmos/ibc-go/pull/90)
closes: #8966 
---
> fix IBC links

- docs/cn/README.md
- docs/cn/basics/README.md
- docs/kr/README.md
- docs/ru/readme.md
For Stargate we only updated the English documentation. Which means, the Korean, Chinese and Russian documentation is outdated. In this PR I propose to add deprecation notes. 
---
> docs: added deprecation notes for non English docs.

- x/auth/keeper/keeper.go
Updates documentation about `maccPerms` parameter for `NewAccountKeeper`
---
> x/auth: update NewAccountKeeper docs

- x/auth/client/cli/cli_test.go
- x/auth/client/cli/tx_sign.go
- x/auth/client/tx.go
Backport #9026 
(backporting manually since mergify is not working)
Co-authored-by: Alessio Treglia <alessio@tendermint.com>
---
> [Backport] Add ledger/multisig detection in SignTx functions (#9026)

- CHANGELOG.md
- x/bank/keeper/view.go
- x/bank/types/errors.go
- x/bank/types/key.go
- x/bank/types/key_test.go
Currently, AddressFromBalancesStore uses the input key without any
validation, so an empty key or an invalid key length cause it panics.
This commit fixes the problem, by introducing new InvalidKey type, which
will be returned to the caller when an invalid key was passed.
Found by fuzzing added in #9060.
---
> x/bank/types: fix AddressFromBalancesStore panics with invalid keys

- go.mod
- go.sum
- store/types/listening_test.go
- testutil/testdata/tx.go
- types/query/pagination.go
- x/auth/keeper/migrations.go
- x/auth/legacy/v043/store.go
- x/auth/tx/service.go
- x/auth/tx/service_test.go
- x/bank/keeper/keeper_test.go
- x/upgrade/keeper/keeper.go
- x/upgrade/keeper/keeper_test.go
> bump tendermint core

- go.mod
- go.sum
- x/staking/client/rest/grpc_query_test.go
> Backport #9081: bump tendermint core

- CHANGELOG.md
- RELEASE_NOTES.md
Changelog & release notes for v0.42.4
---
> update changelog for v0.42.4

- cosmovisor/upgrade.go
currently, `getter.Get` require compressed zip to have `bin` directory to wrap the binary.
But, for some download url from github release of cosmos sdk chain, they may not have this structure.
closes: #8494
---
> cosmovisor: move binary to UpgradeBin from directory (fix #8494)

- simapp/app_test.go
- types/module/module.go
This PR cleans up a small snippet of code in types/module/module.go 
Currently, to check if a module exists in the fromVM map, we check for the default/nil value in the map. 
This PR utilizes the 2nd return value from map accesses, a boolean, which is true if the key exists in the map, false otherwise. This makes not only the code a bit more readable, but also the documentation surrounding it. Ref: [In-Place store migration docs](https://github.com/cosmos/cosmos-sdk/pull/8967/files#diff-7919f886ac1c280f5bc85e12992892df7f160c4ab535e878d2f1510f6d11489cR79-R81). 
closes: N/A
---
> module/types code hygiene - utilize map access 2nd return value

- x/bank/types/key.go
- x/bank/types/key_test.go
addrLen is encoded in a byte, so it's an uint8. The code in
AddressFromBalancesStore cast it to int for bound checking, but wrongly
use "addrLen+1", which can be overflow.
To fix this, just cast addrLen once and use it in all places.
Found by fuzzing added in #9060.
Fixes #9111
---
> x/bank/types: fix AddressFromBalancesStore address length overflow

- .github/workflows/check-docs.yml
Ref: https://github.com/cosmos/cosmos-sdk/pull/9124#issue-616251319
- added a workflow to run `npm run build` when a PR is labeled with `docs`
- the workflow will check if it builds succcessfully
---
> ci: check docs build

- x/auth/legacy/v043/store.go
ref: https://github.com/cosmos/cosmos-sdk/issues/9070#issuecomment-816843849
---
> Add comment on x/auth hacky migration script

- CHANGELOG.md
- client/keys/show.go
- client/keys/show_test.go
> fix show multisig query

- internal/conv/string.go
- internal/conv/string_test.go
UnsafeStrToBytes is currently not safe for -d=checkptr=2, since when it
cast from smaller struct (string) to bigger struct ([]byte). That causes
checkptr complains as the casting straddle multiple heap objects.
To fix this, we have to get the string header first, then use its fields
to construct the slice.
New implementation performs the same speed with the old (wrong) one.
```
name                old time/op    new time/op    delta
UnsafeStrToBytes-8    25.7ns ± 1%    25.7ns ± 3%   ~     (p=0.931 n=10+17)
name                old alloc/op   new alloc/op   delta
UnsafeStrToBytes-8     7.00B ± 0%     7.00B ± 0%   ~     (all equal)
name                old allocs/op  new allocs/op  delta
UnsafeStrToBytes-8      0.00           0.00        ~     (all equal)
```
While at it, also simplify …
> internal/conv: fix wrong string to bytes implementation

- fuzz/oss-fuzz-build.sh
Add oss fuzz build script, so we can make change in our repo instead of creating PR to oss-fuzz repo when we make change to fuzz functions.
Updates #7921
---
> fuzz: add oss-fuzz build script

- x/auth/ante/ante.go
- x/auth/ante/basic.go
- x/auth/ante/basic_test.go
Add NewTxTimeoutHeightDecorator() to be consistent with other antehandler functions. 
closes: #XXXX
---
> auth: consistency in antehandler

- fuzz/README.md
While at it, also update example package path.
---
> fuzz: add oss-fuzz build status link

- crypto/types/compact_bit_array.go
- crypto/types/compact_bit_array_test.go
Ensure that we don't pass overflowed values into make, because
a clever attacker could see that to cause:
(bits+7)/8
to become negative, they just have to make (bits+7) become negative
simply by >=maxint-6
but also reject unreasonably large element count like >2**32, which
while arbitrary is super duper large for a bit array.
Fixes #9162
---
> crypto/types: check for overflow and unreasonably large element count

- types/decimal.go
- types/decimal_test.go
Otherwise, NewDecFromStr may accept very large input, causing Dec
methods panic, e.g Dec.TruncateInt
Found by oss-fuzz: https://oss-fuzz.com/testcase-detail/6454129938530304
Fixes #9160
---
> types: make NewDecFromStr returns error for too large decimal

- types/decimal.go
- types/decimal_test.go
From: #9157
Closes: #9160
Thanks: @cuonglm for the patch
---
> backport: make NewDecFromStr returns error for too large decimal

- x/gov/keeper/querier_test.go
When testing with -race, sometimes the random source generate the same
string for consecutive calls, causing duplicated voter address. So the
number of votes in DB is not 20.
To fix this, we ensure unique addresses are generated, by using a map
for tracking which one was produced, and skip the duplicated address and
generated new one. Testing with:
```
go test -race -v -count=1000 -run=TestPaginatedVotesQuery
```
now passes.
Updates #9010
---
> x/gov/keeper: fix flaky TestPaginatedVotesQuery

- CHANGELOG.md
- x/staking/keeper/msg_server.go
- x/staking/types/events.go
This PR adds a new attribute inside the event types `delegate`. This is useful to return the new shares amount that cannot be queried otherwise without having to perform a new gRPC query. 
The rationale behind this is to allow state parsers (such as [BDJuno](https://github.com/forbole/bdjuno)) to handle properly the `MsgDelegate` parsing, storing a new row that represents the delegation and its associated shares amount. 
Currently, in order to do so we have to query the gRPC to get the shares amount. With this change, this won't be needed anymore as the new shares amount will be returned inside the event itself. 
closes: #XXXX
---
checked off. If any of the checklist items are not applicable, please leave …
> Added a "new_shares" attribute inside the delegate event type

- CHANGELOG.md
- store/internal/proofs/create.go
- store/internal/proofs/create_test.go
Otherwise, an empty key as input or present in data can cause a panic at
runtime.
Caught by oss-fuzz: https://oss-fuzz.com/testcase-detail/4647668077953024
Fixes #9233
---
> store/internal: validate keys before calling ProofsFromMap

- store/cachekv/store.go
Benchmark for store/cachekv:
```
name                          old time/op    new time/op    delta
CacheKVStoreIterator500-8       23.4µs ± 1%    23.3µs ± 1%     ~     (p=0.095 n=5+5)
CacheKVStoreIterator1000-8      46.7µs ± 1%    46.2µs ± 0%   -0.96%  (p=0.008 n=5+5)
CacheKVStoreIterator10000-8      457µs ± 1%     455µs ± 1%     ~     (p=1.000 n=5+5)
CacheKVStoreIterator50000-8     2.59ms ± 2%    2.47ms ± 1%   -4.64%  (p=0.008 n=5+5)
CacheKVStoreIterator100000-8    7.33ms ± 3%    6.91ms ± 1%   -5.75%  (p=0.008 n=5+5)
CacheKVStoreGetNoKeyFound-8      423ns ± 1%     391ns ± 2%   -7.41%  (p=0.008 n=5+5)
CacheKVStoreGetKeyFound-8        267ns ± 3%     264ns ± 2%     ~     (p=0.595 n=5+5)
name                          old alloc/op   new alloc/op   delta
CacheKVStoreIterator500-8       5.18kB …
```
> store/cachekv: reduce allocation when convert []byte -> string in map key

- .github/labeler.yml
> update labeler.yml with shortened labels

- fuzz/crypto/types/compactbitarray/marshalunmarshal/main.go
CompactUnmarshal returns a nil compact bitarray for "null", it causes
false positive alert reported by oss-fuzz.
See: https://oss-fuzz.com/testcase-detail/6372206180433920
---
> fuzz/crypto: fix wrong panic for CompactUnmarshal

- proto/cosmos/slashing/v1beta1/genesis.proto
Sets the right name of the field in the comment for `missed_blocks`
> Minor doc fix for `missed_blocks` proto field

- x/ibc/testing/chain.go
linter was doing a false positive in IBC tests and blocking one PRs.
closes: https://github.com/cosmos/cosmos-sdk/issues/9332
---
> fix SA5011 static check in ibc/../chain.go

- CHANGELOG.md
- RELEASE_NOTES.md
> Update Changelog and RL for v0.42.5

- store/cachemulti/store.go
- store/cachemulti/store_test.go
- store/rootmulti/store.go
Both `store.GetStore` and `store.GetKVStore` are missing `nil` checks which yield to more ugly panics.
---
> fix: add missing nil check in store.GetStore

- CHANGELOG.md
- x/ibc/applications/transfer/client/cli/cli.go
- x/ibc/applications/transfer/client/cli/query.go
When coins are sent via IBC MsgTransfer, they are escrowed in a module account specific to the channel. But with current commands it does not appear possible to get the module account address, and thus to query the balance of escrowed coins. This PR fixes that by introducing a new command:
```
gaiad query ibc-transfer escrow-address <port> <channel id>
```
It doesn't actually query a node, just returns the result of calling `GetEscrowAddress`. This could conceivably go under `gaiad debug`, but figured it made sense under `query ibc-transfer`. 
With this you can now easily see how many coins are escrowed on a channel:
```
gaiad query bank balances $(gaiad query ibc-transfer escrow-address transfer channel-119)
```
Note this will need to be back-ported to ibc-go - …
> CLI: `query ibc-transfer escrow-address`

- docs/architecture/adr-043-nft-module.md
> Adding clarity to ADR 043 nft data field

- CHANGELOG.md
- baseapp/abci.go
- types/context.go
- types/context_test.go
Adds the current block header hash obtained during `abci.RequestBeginBlock` to the `Context`
> feat: add header hash to `Context`

- contrib/images/simd-env/Dockerfile
This PR fixes the following error that was raised when running the `liveliness-test` workflow: 
```
docker: Error response from daemon: OCI runtime create failed: invalid mount {Destination:[ Type:bind Source:/var/lib/docker/volumes/76458935a8a7eefe579a08a9df14debff7251d8c7c70a52aa4f76bfe6962cb94/_data Options:[rbind]}: mount destination [ not absolute: unknown.
```
This was due to the fact that the volumes enclosed inside the Dockerfile should be written between double quotes (`"`). This can be read from the [Docker documentation](https://docs.docker.com/engine/reference/builder/#notes-about-specifying-volumes):
> Keep the following things in mind about volumes in the `Dockerfile`.
> 
> - [...]
> - **JSON formatting**: The list is parsed as a JSON array. You must enclose words with …
> fix: CI Liveliness test 

- x/upgrade/abci_test.go
- x/upgrade/types/plan.go
- x/upgrade/types/plan_test.go
Closes: #9413
In https://github.com/cosmos/cosmos-sdk/pull/9415 an update to cosmvisor was proposed related in order to fix the cosmvisor for the following change:
```
c6af0ed87ed x/upgrade/types/plan.go          (2021-03-13 40) 	return fmt.Sprintf("Height: %d", p.Height)
``` 
I propose to rollback the above change rather than updating cosmvisor. 
Note: we don't need to update documentation or regexp, because these are correct (it was not changed in c6af0ed87ed)
---
> fix: rollback height->Height in x/upgrade plan.DueAt formatting

- CHANGELOG.md
- x/bank/keeper/genesis.go
- x/bank/keeper/send.go
> fix: Bank module init genesis optimization

- client/flags/flags.go
This is a follow up pull request to #9134 / #9122.
The use of backticks around `--memo` in the flag description causes the input type to show up as `--memo`:
```
regen tx bank send -h
--note --memo              Note to add a description to the transaction (previously --memo)
```
And without backticks around `--memo`:
```
regen tx bank send -h
--note string              Note to add a description to the transaction (previously --memo)
```
---
> fix: note flag description

- CHANGELOG.md
- simapp/simd/cmd/testnet.go
- types/coin.go
> fix: Fix testnet command

- CHANGELOG.md
- x/ibc/core/02-client/genesis.go
- x/ibc/core/03-connection/genesis.go
- x/ibc/core/04-channel/genesis.go
backport of [fix on ibc-go](https://github.com/cosmos/ibc-go/pull/200)
closes: #XXXX
---
> backport: fix ibc genesis export bug

- .mergify.yml
Mergify is currently using the default commit message (the first commit message), which does not always include a semantic type prefix and which does not always provide an accurate description. See [commit history](https://github.com/cosmos/cosmos-sdk/commits/master).
This pull request updates the configuration to use `title+body` for the commit message. See Mergify's [merge documentation](https://docs.mergify.io/actions/merge/).
---
I have...
I have...
> ci: use title+body for commit message

- simapp/simd/cmd/testnet.go
- simapp/simd/cmd/testnet_test.go
closes: #9372 
When using the `testnet` cli command, it creates nodes and balances, but does **not** update the supply. When using this in conjunction with `add-genesis-account` which **does** update the supply, it creates an invalid genesis file. This PR updates the testnet command to properly set the supply.
---
I have...
I have...
> fix: testnet cli command update genesis supply

- .github/labeler.yml
It's just causing noise...
---
I have...
I have...
> ci: Remove "Type: Docs" label from labeler action

- CHANGELOG.md
- x/ibc/core/02-client/client/utils/utils.go
Backport of [ibc-go change](https://github.com/cosmos/ibc-go/pull/192). Fixes the `query ibc client header` command and allows querying by height for the header and node-state command. This allows easier venerability of which IBC tokens belong to which chains 
closes: #XXXX
---
> Backport: IBC query header/node-state fixes

- CHANGELOG.md
- baseapp/abci.go
- baseapp/baseapp_test.go
- Sets the header hash on every block (ref #9390). Previously was only set during initialization for `deliverState`.
- Closes #9514
---
I have...
I have...
> fix: set header hash every block

- CHANGELOG.md
- baseapp/baseapp.go
Closes: #XXXX
---
I have...
I have...
> feat: return trace value from baseapp

- CHANGELOG.md
- docs/core/proto-docs.md
- proto/cosmos/gov/v1beta1/gov.proto
- x/gov/keeper/grpc_query.go
- x/gov/keeper/grpc_query_test.go
- x/gov/types/gov.pb.go
Manually tested.
Before:
```
./build/simd q gov votes 1
pagination:
next_key: null
total: "0"
votes:
- option: VOTE_OPTION_UNSPECIFIED
options:
- option: VOTE_OPTION_YES
weight: "1.000000000000000000"
proposal_id: "1"
voter: cosmos137kdgzutlhnqk0t4et7g45ghl5vxupxvl09wct
```
After:
```
./build/simd q gov votes 1
pagination:
next_key: null
total: "0"
votes:
- option: VOTE_OPTION_YES
options:
- option: VOTE_OPTION_YES
weight: "1.000000000000000000"
proposal_id: "1"
voter: cosmos137kdgzutlhnqk0t4et7g45ghl5vxupxvl09wct
```
---
I have...
your handle next to the items …
> fix: Correctly populate legacy Vote.Option field

- CHANGELOG.md
- server/start.go
- server/util_test.go
We introduced throwing an error when min-gas-price was empty in #9371 in 0.43. It seems like it may be too big of a CLI breaking change too soon. Internally at Regen we discussed of showing a warning in 0.43, and throwing the error in 0.44
---
I have...
I have...
> fix: Don't error on startup if min-gas-price is empty

- CHANGELOG.md
- x/ibc/applications/transfer/keeper/relay.go
- x/ibc/core/02-client/keeper/client.go
- x/ibc/core/02-client/keeper/proposal.go
- x/ibc/core/02-client/types/metrics.go
- x/ibc/core/keeper/msg_server.go
- x/ibc/core/types/metrics.go
backport of fix on [ibc-go](https://github.com/cosmos/ibc-go/pull/223)
Closes: #XXXX
---
I have...
I have...
> fix: correct ibc metric labels

- CHANGELOG.md
- baseapp/abci.go
- store/iavl/store.go
- store/rootmulti/store.go
- types/errors/abci.go
To let abci query response include more detailed error message with node started with `--trace`.
---
I have...
I have...
> feat!: support debug trace QueryResult

- CHANGELOG.md
- x/ibc/applications/transfer/module.go
Closes: #XXXX
The success attribute in transfer is emitting exactly the wrong value on the Stargate release. This is corrected on ibc-go. Backporting a non-breaking fix so full nodes may emit the correct attribute value.
Thanks to @sahith-narahari and @gamarin2 for noticing the bug.
---
I have...
I have...
> fix: Fix IBC Transfer Event

- CHANGELOG.md
- RELEASE_NOTES.md
Release notes for 0.42.7 which we're planning to release today.
---
I have...
I have...
> chore: v0.42.7 release notes & changelog

- x/bank/migrations/v043/json.go
- x/bank/migrations/v043/json_test.go
- x/bank/migrations/v043/keys.go
- x/bank/migrations/v043/store.go
- x/bank/migrations/v043/store_test.go
- x/genutil/migrations/v043/migrate.go
Closes: #9653 
---
I have...
I have...
> feat: add migrations for balances with zero coins

- CHANGELOG.md
- RELEASE_NOTES.md
- server/rosetta.go
ref: #9116 
---
I have...
I have...
> chore: Cleanup Changelog, add Rosetta to Release Notes as beta

- CHANGELOG.md
For more clarity about changes between rc-0 and rc-1 I've added RC-1 section and moved items there.
---
I have...
I have...
> chore: separate changes between 0.43.0-rc0 and 0.43.0-rc1

- CHANGELOG.md
- server/grpc/grpc_web.go
- server/grpc/server.go
- server/start.go
- server/types/app.go
- testutil/network/util.go
so it don't block other code from executing.
Closes #9703
---
I have...
I have...
> fix: start GRPCWebServer in goroutine

- server/grpc/grpc_web.go
While looking into #9704 I found that we don't need to wrap grpc web handler into HTTP HandlerFun.
---
I have...
I have...
> perf(grpcweb): remove useless HTTP HandlerFun wrapping

- CHANGELOG.md
> chore: Update Changelog with 0.42.7 section

- docs/architecture/adr-041-in-place-store-migrations.md
- docs/building-modules/upgrade.md
Ref: #9628
Update documentation to reflect changes in #9628.
---
I have...
I have...
> docs: fix migrations directory

- docs/ibc/integration.md
- docs/ibc/overview.md
Guessing that the IBC Overview page not rendering as the first page in the order, probably because the `order: 1` is in an inline comment
> docs: fix broken IBC spec link, IBC page order

- x/auth/tx/decoder.go
Apply post-merge reviews to a previous PR
ref: https://github.com/cosmos/cosmos-sdk/pull/9754#pullrequestreview-713819730
---
I have...
I have...
> refactor: Improve txRaw decoder code

- CHANGELOG.md
- crypto/keys/internal/ecdsa/privkey.go
Added missing changelog and updated a `p256Order` comment to remove misleading part.
---
I have...
I have...
> chore: added changelog for 9793 (secp256r1 tx malleability)

- CHANGELOG.md
- RELEASE_NOTES.md
Closes: #XXXX
---
I have...
I have...
> chore: Add Changelog and Release Notes for v0.42.8

- CHANGELOG.md
- x/genutil/client/cli/gentx.go
- x/genutil/client/cli/init_test.go
- x/genutil/client/testutil/suite.go
- x/staking/client/cli/flags.go
- Ensure input parity of validator public key input between `tx staking create-validator` and `gentx`, i.e the input is is the full JSON payload of the public key. e.g. `{"@type":"/cosmos.crypto.ed25519.PubKey","key":"<base64 payload>"}`
- Update CLI flag description.
closes: #9819
---
I have...
I have...
> fix!: update gentx val pub key input parsing

- CHANGELOG.md
- RELEASE_NOTES.md
Changelog and Release Notes update
---
I have...
I have...
> chore: prepare 0.42.9 release

- x/README.md
- x/auth/spec/04_keepers.md
- x/auth/spec/05_vesting.md
- x/auth/spec/06_params.md
- x/mint/spec/01_concepts.md
- x/slashing/spec/README.md
- x/staking/spec/05_end_block.md
- x/staking/spec/06_hooks.md
- x/staking/spec/07_events.md
Closes: #9858 
This pull request fixes the ordering of module spec documents.
---
I have...
I have...
> docs: fix module spec ordering

- client/context.go
- client/keys/add.go
- client/keys/add_test.go
- client/keys/export.go
- client/keys/export_test.go
- client/keys/import.go
- client/keys/import_test.go
Add a test case to reproduce the issue described in #9566. The test currently fails, and I've pointed some possible solutions over https://github.com/cosmos/cosmos-sdk/issues/9566#issuecomment-889281861. But I feel this needs more works in order to provide a more robust solution. I'll keep poking at better options, but taking any pointers if anyone has ideas.
> fix: file keyring fails to add/import/export keys when input is not stdin (fix #9566)

- CHANGELOG.md
- docs/core/proto-docs.md
- proto/cosmos/params/v1beta1/query.proto
- x/auth/types/query.pb.go
- x/group/types.pb.go
- x/params/keeper/grpc_query.go
- x/params/keeper/grpc_query_test.go
- x/params/keeper/keeper.go
- x/params/keeper/keeper_test.go
- x/params/types/proposal/query.pb.go
- x/params/types/proposal/query.pb.gw.go
- x/params/types/subspace.go
- x/params/types/subspace_test.go
closes: #9873
---
I have...
I have...
> feat: implement x/params get all subspaces/keys

- CHANGELOG.md
ref: #9116 
---
I have...
I have...
> chore: Update changelog with 0.42.8, 0.42.9 and 0.43.0

- CHANGELOG.md
- x/bank/keeper/keeper.go
- x/bank/migrations/v043/keys.go
- x/bank/migrations/v044/store.go
- x/bank/migrations/v044/store_test.go
- x/bank/types/key.go
Closes: #9643 
---
I have...
I have...
> fix!: remove denom from DenomMetadata key

- x/auth/client/cli/query.go
ref: user from #validators-verfied channel on Cosmos Discord
---
I have...
I have...
> fix: Fix CLI query tx docs for acc/seq

- CHANGELOG.md
- Makefile
Closes: #9964 
+ Fixing `app version` command
+ fixing format issue in the Makefile.
---
I have...
I have...
> fix(build): set a right version for the app

- simapp/sim_test.go
expected is meant to be 0 not the failed amount. The order doesnt matter greatly, but for consistency sake. 
---
I have...
I have...
> fix!: sims/test expect set to 0

- CHANGELOG.md
- x/bank/client/cli/query.go
Closes: #9977
---
I have...
I have...
> fix: fix the invalid argument for bank total supply cli query

- docs/building-modules/errors.md
Closes: #9598
The documentation states "Must be greater than one, as a code value of one is reserved for internal errors" and this was not implemented correctly in `v0.38.1`.
Previous: https://github.com/cosmos/cosmos-sdk/blob/v0.38.1/x/distribution/types/errors.go#L1-L21
Updated: https://github.com/cosmos/cosmos-sdk/blob/v0.43.0/x/distribution/types/errors.go#L1-L21
---
I have...
I have...
> docs: fix error example

- store/cachekv/store.go
So we don't burn un-necessary CPU in case of dirty store/delete.
```
name                          old time/op    new time/op    delta
CacheKVStoreIterator500-8       23.3µs ± 2%    23.4µs ± 1%    ~     (p=0.151 n=5+5)
CacheKVStoreIterator1000-8      47.0µs ± 2%    46.3µs ± 0%  -1.50%  (p=0.008 n=5+5)
CacheKVStoreIterator10000-8      462µs ± 3%     458µs ± 1%    ~     (p=0.690 n=5+5)
CacheKVStoreIterator50000-8     2.63ms ± 5%    2.51ms ± 2%  -4.63%  (p=0.032 n=5+5)
CacheKVStoreIterator100000-8    8.09ms ±21%    6.98ms ± 4%    ~     (p=0.151 n=5+5)
CacheKVStoreGetNoKeyFound-8      393ns ± 2%     397ns ± 2%    ~     (p=0.421 n=5+5)
CacheKVStoreGetKeyFound-8        269ns ± 5%     268ns ± 3%    ~     (p=1.000 n=5+5)
```
Fixes #9991
---
*All items are required. Please add a note to the item …
> perf: convert to string once in setCacheValue

- x/bank/bench_test.go
To ensure that benchmarking of all other commits can proceed without
errors, which block the entire process.
Updates #10023
I have...
I have...
> fix!: x/bank: skip failing BenchmarkOneBankSend* to avoid blocking benchmarking

- client/tx/legacy.go
- client/tx/legacy_test.go
- x/auth/ante/sigverify.go
Amino multisig update. It breaks the state machine and it's needed for the next SDK upgrade.
---
I have...
I have...
> fix!: Remove onlyAminoSigners in sequence check

- CHANGELOG.md
- x/auth/keeper/account.go
- x/auth/keeper/keeper.go
- x/auth/spec/04_keepers.md
- x/bank/keeper/send.go
- x/bank/types/expected_keepers.go
This PR adds a HasAccount method to the AuthKeeper, which lets you just check if an account exists, without unmarshalling it. This PR also fixes one unnecessary spot that it appears within in SendCoins. 
This PR is API breaking (Adds HasAccount to the AuthKeeper) but is not state machine breaking.
We found in the Osmosis epoch time, the many accesses to GetAccount's proto unmarshalling was a significant slowdown. This PR has been benchmarked to improve that performance! (As it halves the amount of proto unmarshals in SendCoins. There is still one more remaining, a subsidiary call within LockedCoins(), within SubtractCoins)
---
I have...
*All items …
> perf!: Add HasAccount to the AuthKeeper to save protobuf decoding time

- codec/amino_codec_test.go
We still use wrapped transactions so we should test marshaling.
---
I have...
I have...
> test: bring back Marshalling/unmarshalling of a wrapped tx test

- CHANGELOG.md
- client/tx/factory.go
- client/tx/tx.go
- client/tx/tx_test.go
- x/auth/client/tx.go
- x/genutil/client/cli/gentx.go
Since don't remove all legacy REST endpoints we don't need the 0155244d2a104af8722e04320bf3972eecc7e9b1 commit which breaks the API. Let's keep the v0.44 changes to the absolute minimum.
---
I have...
I have...
> chore: revert TxFactory changes

- CHANGELOG.md
- store/cachekv/store.go
- store/gaskv/store.go
Closes: #10072 
Significantly speeds up all the GasKvStore and CacheKVStore operations. Now Get/Set for these stores no longer even appears on my Osmosis benchmarks, saving ~8% of those benchmark's times. (Only one of the internal methods for setCacheValue appear -- will try to separately get a PR for reducing those memory allocations if #10026 is merged)
Talked to @alexanderbez about this on Discord, and he seemed in agreement with the approach of removing telemetry from these stores.
This does technically change telemetry, but I don't know if this is / should be considered a breaking change?
---
I have...
*All items are required. Please add a note …
> perf: Remove telemetry from wrappings of store

- CHANGELOG.md
- types/coin.go
Speedup coins.String() and coin.String()
In my local benchmarks, this >2x improves the time for balances with 1 coin, and further improves speed for strings with many balances. I did not benchmark on the two coin usecase
---
I have...
I have...
> perf: Improve the speed of coins.String()

- server/start.go
This pull request fixes the minimum-gas-price warning in the `release/v0.44.x` branch.
---
I have...
I have...
> fix: minimum-gas-price warning

- CHANGELOG.md
- types/coin.go
Speeds up coins.AmountOf() by removing many regex calls when users hold multiple tokens. I expose the AmountOfNoDenomValidation function publicly, because this is quite useful when you know that the denomination is pre-validated, as we do in usecases within Osmosis where we call this function.
(This function is a notable amount of our current epoch time after CacheKV store fixes at approximately 5%, all spent within the regex matching)
---
I have...
I have...
> perf: Speedup coins.AmountOf() by removing many regex calls

- types/address_test.go
Closes: #10163
---
I have...
I have...
> fix: bech32 address test to satisfy the specification (#10163)

- CHANGELOG.md
- crypto/keys/multisig/amino.go
- crypto/keys/multisig/multisig_test.go
Reverting https://github.com/cosmos/cosmos-sdk/pull/10169 because we are not sure if this correctly solves the issue and we don't want to block v0.44.1 release.
> fix: revert \#10169 (amino multisig key unmarshalling)

- .github/workflows/stale.yml
Avoid randomly closing issues. Stale bot now only works on PRs
---
I have...
I have...
> fix: dont close issues

- CHANGELOG.md
- x/staking/types/params.go
Closes: #XXXX
---
I have...
I have...
> chore!: remove unused KeyPowerReduction var

- CHANGELOG.md
- store/rootmulti/store.go
- types/module/module.go
- x/upgrade/keeper/keeper.go
Closes: #10188
1. iterate upgrade migrations by initgenesis order
2. forced deterministic iteration order in x/upgrade and store during upgrades
---
I have...
I have...
> fix: removed potential sources of non-determinism in upgrades

- CHANGELOG.md
- x/bank/migrations/v044/keys.go
- x/bank/migrations/v044/store.go
- x/bank/migrations/v044/store_test.go
- x/bank/types/key.go
- x/bank/types/key_test.go
Ref: https://github.com/cosmos/cosmos-sdk/pull/10060
Fixing x/bank/migrations/v44.migrateDenomMetadata - we could potentially put a wrong data in a new key if the old keys have variable length.
---
I have...
I have...
> fix: x/bank/044 migrateDenomMetadata

- README.md
The current link points to an old version of the Nameservice tutorial (still on Launchpad 🥶). Updated the link to to point to https://tutorials.cosmos.network There is a PR with the updated version opened in the tutorials repo and the most up-to-date version is hosted on https://docs.starport.network/guide/nameservice/
> docs: Update the tutorials link

- x/bank/keeper/migrations.go
- x/bank/migrations/v045/keys.go
- x/bank/migrations/v045/store.go
- x/bank/migrations/v045/store_test.go
In general, migrations in a `vX` package means that we're migration TO version X.
We added a new denom++address index in #9611, and this should go in 0.45. However, its migration went into `package v044` because it was done before the v044 security release. To avoid confusion, I'm renaming that package to v045
---
I have...
I have...
> chore: Rename v044 migrations to v045

- x/auth/spec/01_concepts.md
- x/auth/spec/03_antehandlers.md
- x/auth/spec/05_vesting.md
- x/auth/spec/README.md
- x/authz/spec/01_concepts.md
- x/authz/spec/03_messages.md
- x/authz/spec/05_client.md
Closes: #0178
Adds the requested differential language between auth and authz modules.  Resolves instances of future tense that were noticed.
---
I have...
- [NA] added `!` to the type prefix if API or client breaking change
- [NA] followed the guidelines for [building modules](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules)
- [NA] included the necessary unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [NA] added a changelog entry to `CHANGELOG.md`
- [NA] included comments for [documenting Go code](https://blog.golang.org/godoc)
- [NA] reviewed "Files changed" and left …
> docs: #10178 reference authz from auth

- client/keys/show_test.go
- crypto/keys/secp256k1/secp256k1_test.go
- go.mod
- go.sum
- types/bech32/bech32.go
- x/authz/client/testutil/grpc.go
- x/group/go.mod
- x/group/go.sum
Closes: #10082 
---
I have...
I have...
> build(deps): Use self-maintained btcutil (#10082)

- docs/architecture/adr-014-proportional-slashing.md
> chore: fix typo in adr-014-proportional-slashing.md

- CHANGELOG.md
- store/cachekv/store.go
We can shave off some milliseconds, but also cut down some Megabytes of
RAM consumed by only requesting from the cache if needed, but also using
the map clearing idiom which is recognized by the compiler to make fast
code.
Noticed in profiles from Tharsis' Ethermint per https://github.com/tharsis/ethermint/issues/710
- Before
* Memory profiles
```shell
19.50MB    19.50MB    134:	store.cache = make(map[string]*cValue)
18.50MB    18.50MB    135:	store.deleted = make(map[string]struct{})
15.50MB    15.50MB    136:	store.unsortedCache = make(map[string]struct{})
```
* CPU profiles
```go
.          .    118:	// TODO: Consider allowing usage of Batch, which would allow the write to
.          .    119:	// at least happen atomically.
150ms      150ms    120:	for _, key := range keys {
220ms …
```
> perf: store/cachekv: avoid a map lookup if unnecessary, clear maps fast, avoid keys sort

- crypto/keyring/keyring.go
add spaces in error message
closes #9974
replaces https://github.com/cosmos/cosmos-sdk/pull/9975
---
I have...
I have...
> fix: clear display and put address.String()

- .github/workflows/test.yml
- Makefile
- contrib/images/Makefile
- contrib/images/simd-env/Dockerfile
- contrib/images/simd-env/wrapper.sh
- docker-compose.yml
- gratuitous.go
Extracted from #10210.
Make the test more reproducible, so that it does not require coordination
between the build container and the run container.
- Use layers to more advantage.
- Include bash in the run container.
- Put writable output onto a volume.
**Note to reviewers:** I included a stub Go file to trigger the CI. That should be dropped before merging this change.
> build: fix build environment for the liveness test

- CHANGELOG.md
- x/upgrade/abci.go
- x/upgrade/keeper/keeper.go
Closes: #10531
Closes: #10428
Straw-man attempt to bring the plan.Info data in to upgrade-info.json file in a backward compatible way.
---
I have...
I have...
> feat: update x/upgrade keeper.DumpUpgradeInfoToDisk to support Plan.Info

- proto/cosmos/gov/v1beta2/genesis.proto
- proto/cosmos/gov/v1beta2/gov.proto
- proto/cosmos/gov/v1beta2/query.proto
- proto/cosmos/gov/v1beta2/tx.proto
Ref: #9810
Bumps gov proto files to v1beta2 and creates new `Proposal` type
---
I have...
I have...
> feat: create v1beta2 gov proto types

- CHANGELOG.md
- docs/core/upgrade.md
- types/module/module.go
This PR targets only `v0.44.x` release. For master we will have #10604
Closes: #10606
Fixes: #10591
---
I have...
I have...
> fix: always move auth module migration to the end

- CHANGELOG.md
- RELEASE_NOTES.md
> chore: 0.44.4 release notes

- CHANGELOG.md
- baseapp/abci.go
- baseapp/baseapp.go
- baseapp/baseapp_test.go
- baseapp/test_helpers.go
- types/errors/abci.go
Closes: #10618 
This is example implementation to emit ante events(especially of tx fee deduction) for the failed txs. 
The master branch has huge difference in ante handler side (changed to middleware), so I just made changes only for v0.44.x branch.
---
I have...
I have...
> fix: emit ante events even for the failed txs

- CHANGELOG.md
- go.mod
- go.sum
Bump IAVL to solve race condition bug.
---
I have...
I have...
> fix: upgrade IAVL

- CHANGELOG.md
- RELEASE_NOTES.md
> chore: Cosmos SDK v0.44.5 release notes

- CHANGELOG.md
- client/tx/tx.go
- client/tx/tx_test.go
- x/auth/client/testutil/suite.go
Be slightly less strict in a multi-signer TX:
- BEFORE: we don't allow any signer to be DIRECT
- AFTER: we allow 1 signer maximum to be DIRECT
Note: this only changes behavior in the CLI. In the antehandlers, we always allow any number of signers to be DIRECT.
This PR is to allow using transaction tips in the CLI.
---
I have...
I have...
> fix(cli): Allow max 1 DIRECT signer per tx

- CHANGELOG.md
- RELEASE_NOTES.md
> chore: v0.42.11 changelog and release notes

- CHANGELOG.md
- x/staking/client/cli/flags.go
- x/staking/client/cli/tx.go
- x/staking/client/testutil/cli_test.go
- x/staking/client/testutil/suite.go
Closes: #10660 
---
I have...
I have...
> fix: edit validator bug from the cli

- CHANGELOG.md
- contrib/rosetta/rosetta-cli/Dockerfile
- go.mod
- go.sum
A fix to rosetta was recently merged and tagged for an issue with rosetta causing tests to fail on chains with coins minted post genesis.  We should consume this fix: https://github.com/coinbase/rosetta-sdk-go/pull/358
Closes: #10706 
---
I have...
I have...
> feat: Update rosetta-sdk-go and rosetta-cli

- x/bank/keeper/keeper.go
- x/gov/client/utils/query.go
- x/upgrade/keeper/keeper.go
- x/upgrade/plan/info.go
Noticed while auding Tharsis' EVM module and stumbled down a hole where
I discovered this pattern of code that's quite expensive and unnecessary
where we had say:
fmt.Sprintf("%s.%s='%s'", types.EventTypeSubmitProposal,
types.AttributeKeyProposalID,
[]byte(fmt.Sprintf("%d", proposalID)))
where there was the use of `[]byte(fmt.Sprintf("%d", proposalID))`
which then invoked
fmt.Sprintf(...'%s'...)
yet however we could simply just invoke
fmt.Sprintf("%s.%s='%d'", types.EventTypeSubmitProposal,
types.AttributeKeyProposalID,
proposalID)
which saves a whole bunch of CPU and RAM cycles, as documented in
https://twitter.com/orijtech/status/1462100381803102213?s=20
or for a demo
https://dashboard.bencher.orijtech.com/benchmark/3245b8e4bbbd44a597480319aaa4b9fe
While also here, found spots that used …
> perf: x/*: remove unnecessary byte<->string conversions in fmt and read only bytes

- Makefile
Fixes the docs build process: re-enable building multiple versions. This should make the version selection work again:
Closes: #10228
Adjust Makefile: The issue was caused by changes on the local file system during build, which prevents the `git checkout` command from succeeding. These can be caused by:
* A changed mod.sum file
* Artifacts left over from building the previous version
This PR adjusts the makefile to ignore existing changes (`git clean` & `git reset`). The overall build process is not changed.
**Please note**: The actual build & deployment is triggered from the [cosmos docs repository](https://github.com/cosmos/docs). The `check-docs` action in this repository only checks building the updated branch's docs.
---
*All items are required. Please add a note to the item if the …
> fix: Adjust docs build steps in makefile to fix building all versions

- CHANGELOG.md
- store/cachekv/memiterator.go
- store/cachekv/store_bench_test.go
This PR provides extreme speedups to the iterator creation pattern used in upgrades from IBC v1 to v2. On Osmosis, executing an upgrade from a state export was taking us over 2 hours due to this bug. (We never let it finish) After this fix, it takes under 8 minutes. (There is then ~20-30 min time overhead for IAVL commit, but thats orthogonal)
Essentially the CacheKVStore previously would iterate over every deleted item in cache when constructing an iterator. In the upgrade logic, bank first migrates the entire store, rewriting everything. (And thus adding 100k + deletes, other upgrades added far more deletes as well. Guestimmated that Osmosis had around 500k deletes) Then in IBC's upgrade, you do at least two iterator constructions per IBC client, which on Osmosis there are ~2000.  This …
> perf: Speedup cachekv iterator on large deletions & IBC v2 upgrade logic

- .github/dependabot.yml
Closes: #10554
add dependabot to all go.mod locations
---
I have...
I have...
> chore: add dependabot to all go mod locations

- CHANGELOG.md
- types/module/configurator.go
- types/module/module.go
Closes: #10689
it'd also be good to add more fine-grained tracking of individual migrations,
but there doesn't seem to be a quick way of doing it.
Perhaps the best is to leave it to each migration implementation
to add its own internal logging?
---
I have...
I have...
> feat: extra logging in in-place store migrations

- x/feegrant/client/cli/tx.go
Closes: #XXXX
---
I have...
I have...
> chore: update feegrant `grant` description

- errors/abci_test.go
- errors/stacktrace.go
- errors/stacktrace_test.go
Fixes some test failures in `errors` that I'm almost certain didn't show up in #10779. Seems like all tests weren't running properly there.
---
I have...
I have...
> fix(errors): test failures

- CHANGELOG.md
- baseapp/baseapp.go
Closes: #10832
Solution: Return empty GasInfo.
---
I have...
I have...
> fix!: tx result don't report block gas used as tx gas used

- CHANGELOG.md
- baseapp/baseapp.go
- baseapp/block_gas_test.go
- baseapp/test_helpers.go
backport from #10770,  but used a different solution from the master one, because of difference in code structure.
---
I have...
I have...
> fix: revert tx when block gas limit exceeded (backport: #10770)

- x/slashing/keeper/hooks.go
- x/slashing/keeper/infractions.go
- x/slashing/keeper/keeper.go
- x/slashing/keeper/keeper_test.go
- x/slashing/keeper/signing_info.go
- x/slashing/types/expected_keepers.go
Create a slashing hook that allows external modules to register an execution when a validator has downtime.
Implementation details:
* Call hook in HandleValidatorSignature (x/slashing/keeper/infractions.go) which updates validator SignInfo data
* Defer hook execution in case it also wants to update validator SignInfo data
* Add methods to update SignInfo to slashing keeper interface(/x/slashing/types/expected_keepers.go)
Closes: #XXXX
---
I have...
I have...
> feat: Add AfterValidatorDowntime hook in slashing module

- CHANGELOG.md
- client/keys/add_test.go
- client/keys/delete_test.go
- client/keys/export_test.go
- client/keys/list_test.go
- client/keys/show_test.go
- crypto/ledger/ledger_mock.go
- crypto/ledger/ledger_test.go
- simapp/simd/cmd/testnet.go
- testutil/key.go
- testutil/key_test.go
- testutil/network/network.go
- testutil/testdata/known_values.go
- types/bech32/legacybech32/pk_test.go
A breaking change was backported to 0.45 RC: https://github.com/cosmos/cosmos-sdk/pull/10934
Cleaning it and moving the breaking "test" code to testutils
---
I have...
I have...
> chore: move server.GenerateCoinKey and server.GenerateSaveCoinKey to testutil

- x/bank/keeper/keeper.go
- x/bank/keeper/keeper_test.go
- x/bank/keeper/view.go
- x/bank/types/vesting.go
Remove `x/auth`'s vesting types dependency from the `x/bank` module in a non-state and API breaking manner.
---
I have...
I have...
> refactor: remove x/auth vesting dependency in x/bank

- CHANGELOG.md
- crypto/armor.go
- crypto/xsalsa20symmetric/symmetric.go
- crypto/xsalsa20symmetric/symmetric_test.go
The xsalsa20symmetric package is otherwise unused in Tendermint Core.
Move the dependency to a subpackage of crypto and update the imports.
No functional changes.
> chore: crypto/xsalsa20symmetric: remove dependency on tendermint core

- server/init.go
- server/init_test.go
- simapp/simd/cmd/testnet.go
- testutil/network/network.go
This reverts commit 8bb7a968cc8181cb10c8c15f10665d9f14ffe73c, because it introduced an API-beraking change.
Closes: #XXXX
---
I have...
I have...
> revert: "support custom mnemonics in in-process testing network"

- CHANGELOG.md
- RELEASE_NOTES.md
> chore: v0.44.6 changelog and release notes

- CHANGELOG.md
- RELEASE_NOTES.md
Release notes for 0.45.1
---
I have...
I have...
> chore: 0.45.1 Release Notes

- simapp/app.go
add comment in simapp as a notice to avoid mistakes when building app from sdk:
`genutil` module should init after `auth`.
Closes: #XXXX
---
I have...
I have...
> docs: add comment to guide the module order in SetOrderInitGenesis

- docs/run-node/run-node.md
Closes: #11042 
add note about modes in tendermint and local networks
---
I have...
I have...
> chore: add mention of modes from tendermint 0.35

- x/group/keeper/keeper_test.go
This PR fixes [few failing tests](https://github.com/cosmos/cosmos-sdk/blob/master/x/group/keeper/keeper_test.go#L1027) with some non-determinism in x/group
---
I have...
I have...
> fix: failing tests in x/group

- CHANGELOG.md
- baseapp/abci.go
- types/errors/abci.go
backport #9576
---
I have...
I have...
> feat!: support debug trace QueryResult (backport #9576)

- CHANGELOG.md
- types/coin.go
- types/coin_test.go
- types/dec_coin.go
- x/auth/vesting/types/vesting_account.go
Closes: #10995
Adds `Min()` and `Max()` operations on `sdk.Coins` for per-denom minimum and maximum.
Replaced an example of manual low-level construction of `Coins` with higher-level operators.
Upcoming enhancements to vesting accounts make heavy use of this pattern.
---
I have...
I have...
> feat: min and max operators on coins

- CHANGELOG.md
- client/tx/factory.go
- client/tx/tx_test.go
Closes: #11283
---
I have...
I have...
> fix: remove hardcoded pubkey from tx simulation

- CHANGELOG.md
- go.mod
- go.sum
- server/rollback.go
- server/util.go
- store/rootmulti/store.go
Closes: #10281
~Currently it has `panic: StoreBlockHeight (6) > StateBlockHeight + 1 (5)` error when start after rollback.~ fixed after update tendermint.
---
I have...
I have...
> feat: Implement rollback command

- CHANGELOG.md
- server/tm_cmds.go
Closes: #11336 
---
I have...
I have...
> fix(cli): fix the `show-address` cli cmd

- x/group/client/testutil/tx.go
Closes: #11168 
---
I have...
I have...
> refactor(tests): refactor group CLI tests to be independent

- .github/workflows/codeql-analysis.yml
Removes a duplicated go setup step from the codeql workflow.
---
I have...
I have...
> build: Remove duplicate go setup action in the codeql workflow.

- x/slashing/keeper/hooks.go
- x/slashing/keeper/infractions.go
- x/slashing/keeper/keeper.go
- x/slashing/types/expected_keepers.go
- x/staking/keeper/validator.go
Hooks are not required anymore to implement the slashing for downtime in CCV. The logic is now using the staking keeper interface definition from the slashing module.
The SDK changes are the following:
- /x/slashing/keeper/infractions.go - remove hook calls and don't update validators missed blocks when jailed
- /x/slashing/types/expected_keepers.go - remove `AfterValidatorDowntime` hook interface and add `IsJailed()` method to staking interface definition
- /x/staking/keeper/validator.go - implement `IsJailed()` method
Closes: #XXXX
---
I have...
your handle next …
> update: Remove slashing module hooks

- CHANGELOG.md
- contrib/devtools/Dockerfile
- x/genutil/collect.go
- x/genutil/gentx.go
- x/genutil/gentx_test.go
- x/genutil/types/genesis_state.go
Closes: #9304 
---
I have...
I have...
> fix: Improve gentx validation & error messages

- CHANGELOG.md
- server/config/config.go
- server/start.go
This PR will add api server flags to start command so we can enable api directly from command instead of modifying app.toml.
---
I have...
I have...
> feat: api server flags to start command

- .github/workflows/deploy-docs.yml
- .gitignore
- Makefile
Relates to: https://github.com/cosmos/docs/issues/17
Moves the GitHub Action that deploys the cosmos documentation to the `cosmos/cosmos-sdk` repository.
---
I have...
I have...
> ci: Add GitHub Actions for documentation deployment

- testutil/network/network.go
- x/evidence/types/genesis.go
- x/genutil/client/cli/init.go
Replace all occurance of `gensis` in code with `genesis`
---
I have...
I have...
> fix: genesis typo in error message

- CHANGELOG.md
- go.mod
- go.sum
- server/tm_cmds.go
- server/util.go
- Bump TM to 0.34.19
- Move TM commands to `tendermint` sub-command
Note, the `reset-all` command is partially broken in 0.34.17, but @cmwaters already resolved it so we're waiting on 0.34.18.
---
I have...
I have...
> chore: update TM dep

- x/distribution/types/expected_keepers.go
Gets rid of some dead code in the distribution module. Cleans up unused methods in distribution expected keepers.
---
I have...
I have...
> chore: clean up unused methods in distribution expected keepers

- CHANGELOG.md
- RELEASE_NOTES.md
> chore: v0.44.8 Release Notes

- CHANGELOG.md
- RELEASE_NOTES.md
> chore: v0.45.3 Release Notes

- server/start.go
Closes: #XXXX
https://github.com/cosmos/cosmos-sdk/pull/11460 introduced a bug where the error from `node.NewNode` is not being checked
---
I have...
I have...
> fix: check error returned from NewNode

- cosmovisor/go.mod
- cosmovisor/scanner.go
- cosmovisor/upgrade.go
- Normalize (lower-case) upgrade name when parsing the plan file
- Perform case-insensitive name comparison in `CheckUpdate`
- Minor linting/style cleanup
---
I have...
I have...
> refactor: cosmovisor name normalization & comparison

- store/cachemulti/store.go
- store/rootmulti/store.go
- store/types/store.go
- store/types/store_test.go
This PR adds the store name to each `tracekv`-emitted trace, making store tracing a little more useful and reliable for end-users.
---
I have...
I have...
> feat: add store name in `tracekv`-emitted store traces

- x/auth/keeper/grpc_query.go
- x/auth/keeper/grpc_query_test.go
The Juno halt was caused by a smart contract calling a SDK's gRPC query that was not deterministic (at least that's my understanding).
As such, a fix was proposed on cosmwasm to whitelist only the gRPC queries that are deterministic. For example, gRPC queries that return node-specific config would not be whitelisted.
In my opinion, all module queries MUST be deterministic, since they can be part of the state machine. This PR will also help adr-033.
i made a quick audit of all `x/*` grpc_query.go, to make sure all of them were deterministic. The only non-determinism I found was in auth's ModuleAccount, but it's introduced in v0.46 and not released yet.
---
please add links to any relevant follow up …
> fix: Make module queries deterministic

- .github/workflows/test.yml
- simapp/app.go
Closes: #11654 
pass the failure of artifact download. 
---
I have...
I have...
> chore: ignore artefact if not present

- x/group/keeper/invariants.go
- x/group/keeper/keeper_test.go
- x/group/keeper/msg_server.go
Closes: #11651 
I did an audit of all places where we use the group's `TotalWeight`, and made sure it can be 0.
---
I have...
I have...
> fix(group): Allow group total weight to be 0

- .github/workflows/lint.yml
- .github/workflows/sims.yml
- .github/workflows/tag.yml
- .github/workflows/test.yml
- CHANGELOG.md
- Makefile
- contrib/images/Makefile
- contrib/images/simd-dlv/Dockerfile
- contrib/images/simd-dlv/README.md
- contrib/images/simd-dlv/wrapper.sh
- contrib/rosetta/node/Dockerfile
- contrib/rosetta/rosetta-cli/Dockerfile
- docker-compose.yml
- go.mod
- go.sum
Closes: #11684
---
I have...
I have...
> chore: v0.45.x bump min go version to 1.17

- x/auth/middleware/basic_test.go
- x/auth/middleware/fee_test.go
- x/auth/middleware/gas_test.go
- x/auth/middleware/run_msgs_test.go
- x/auth/middleware/sigverify_test.go
- x/auth/middleware/tx_test.go
ref: #11087
---
I have...
I have...
> chore: add more tests in `middleware` for code cov

- CHANGELOG.md
- simapp/helpers/test_helpers.go
- simapp/test_helpers.go
- x/authz/simulation/operations.go
- x/bank/simulation/operations.go
- x/genutil/gentx_test.go
- x/gov/simulation/operations.go
- x/group/simulation/operations.go
- x/nft/simulation/operations.go
- x/simulation/util.go
- x/slashing/simulation/operations.go
Closes: #XXXX
---
I have...
I have...
> refactor: rename `GenTx` to `GenSignedMockTx` to avoid confusion with genutil/GenTx

- Dockerfile
- contrib/devtools/Dockerfile
- contrib/images/simd-dlv/Dockerfile
- contrib/images/simd-env/Dockerfile
- contrib/rosetta/rosetta-ci/Dockerfile
- contrib/rosetta/rosetta-cli/Dockerfile
closes: #11709
ref: https://github.com/cosmos/cosmos-sdk/pull/11663
Pin against Go versions in Dockerfiles
cc @faddat 
---
I have...
I have...
> fix: pin go version Dockerfiles

- CHANGELOG.md
- client/cmd.go
- client/cmd_test.go
- simapp/simd/cmd/cmd_test.go
- simapp/simd/cmd/root.go
Closes: #11508
---
I have...
I have...
> fix(cli): home flag gets ignored when running help

- fuzz/tests/types_parsetimebytes_test.go
CC @odeke-em. This fixes the fuzzing false positives such as `0600-06-01T0:51:07.000600600` vs `0600-06-01T00:51:07.000600600` as [you diagnosed](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=33530) on the OSS-Fuzz tracker.
> fix: normalize timestamps before roundtrip

- store/cachemulti/store.go
- store/rootmulti/store.go
- store/types/store.go
- store/types/store_test.go
Backporting #11587 
This feature is not breaking but requested by few teams.
We can't do it with mergifyio because we renamed the branch (see comments in https://github.com/cosmos/cosmos-sdk/pull/11646#issuecomment-1109932497)
---
I have...
I have...
> chore: backport #11587

- go.mod
- go.sum
- Published `v1.0.0-beta.1` of the math sub-module
- Remove `replace` directive in favor of the tagged version
ref: https://github.com/cosmos/cosmos-sdk/pull/11788
---
I have...
I have...
> chore: update math module dep

- docs/intro/sdk-app-architecture.md
> fix: docs link page miss

- x/gov/spec/01_concepts.md
Documentation fix to clarify censorship threshold language. This came up because the "No with Veto" proposal justification involves censorship at 1/3 + 1 voting power. See https://github.com/cosmos/governance/pull/32
---
I have...
I have...
> docs: clarify language about censor threshold as one third + 1

- server/export.go
present app export genesis will export to stderr,  not stdout, because [cobra `println` default is to stderr](https://pkg.go.dev/github.com/spf13/cobra#Command.Println)
`gaiad export > genesis_export.json` will not work
`gaiad export 2> genesis_export.json` will work
the fix makes gaiad export to print to stdout.
Closes: #XXXX
---
I have...
I have...
> fix: export genesis to stdout, not stderr

- x/genutil/client/cli/gentx.go
err is always nil, because txFactor doesn't
produce new errors
err is always nil, because txFactor doesn't
produce new errors
Closes: N/A
---
I have...
I have...
> fix: remove unnecessary err check in gentx

- CHANGELOG.md
- server/config/config.go
- server/config/toml.go
- server/grpc/server.go
- server/start.go
- testutil/network/util.go
Provide the ability for operators to set custom r/w gRPC options in `app.toml`. Note, operators are not required to update their `app.toml` as a safe guard is also added when values are 0 to use default values.
---
I have...
I have...
> feat!: support custom r/w gRPC options

- container/container.go
- container/container_test.go
Uncovered in #11900 
---
I have...
I have...
> fix(container): issue with multiple dependencies coming from an out struct

- container/container.go
- container/container_test.go
- container/module_key.go
Uncovered in #11900.
Also adds the new type `OwnModuleKey` for a module to retrieve its own module key rather than providing a module-scoped dependency to other modules.
---
I have...
I have...
> fix(container)!: fix issue providing a module-scoped dep from a module

- CHANGELOG.md
- x/gov/client/testutil/deposits.go
These tests were testing some odd conditions which shouldn't be possible in this module. Why they were passing? Because the test code had bugs itself. Check the issues below for more details.
Closes: #11936
Closes: #11926
---
I have...
I have...
> fix: x/gov client deposits tests

- types/events.go
- types/events_test.go
- x/bank/types/events.go
Add test on `StringifyEvents` (makes the behavior more clear for someone not familiar with the code)
---
I have...
I have...
> test: add test on `StringifyEvents`

- x/slashing/keeper/hooks.go
- x/slashing/keeper/keeper_test.go
- x/slashing/spec/01_concepts.md
- x/slashing/spec/05_hooks.md
Closes: #10312
This PR fixes the mismatch between the behavior and the comment, as discovered in the issue above.
---
I have...
I have...
> fix: update `StartHeight` signing info in `AfterValidatorBonded` hook when validator re-bonds

- store/cachekv/memiterator.go
- store/cachekv/store.go
- store/iavl/store.go
- store/streaming/constructor_test.go
- store/streaming/file/service.go
- store/streaming/file/service_test.go
Ref: https://github.com/cosmos/cosmos-sdk/issues/11362
---
I have...
I have...
> chore: store audit

- store/firstlast.go
- store/tools/ics23/iavl/README.md
- store/tools/ics23/iavl/helpers/helpers.go
- store/tools/ics23/smt/README.md
- store/tools/ics23/smt/helpers/helpers.go
- store/tools/ics23/smt/helpers/random.go
- store/tracekv/store.go
- store/types/store.go
- store/types/utils.go
- store/types/validity.go
ref: #11362 
---
I have...
I have...
> chore: store audit changes

- container/container.go
- container/container_test.go
- container/group.go
- container/testdata/example.dot
- container/testdata/example_error.dot
Closes: #11935
---
I have...
I have...
> chore: rename container.AutoGroupType to container.ManyPerContainerType

- math/uint.go
- math/uint_test.go
This change adds a negative value check to Uint.Unmarshal,
which coincidentally is fixed by refactoring for code reuse.
While here, added tests to ensure we don't regress.
Fixes #11995
> fix: math: fix Uint.Unmarshal's lack of negative value checking

- math/int.go
- math/uint.go
The specification of "copy", the builtin function per
https://pkg.go.dev/builtin#copy, says that it returns the minimum of
len(src) and len(dst) when invoked as:
copy(dst, src)
of which the prior code blindly assumed that everytime that
copy is invoked that the buffer provided had enough size
to accomodate the contents of *.MarshalTo but this isn't true
at all if len(data) is less than the values of .Marshal()
> math: derive marshalled byte length from copy, not blind assumptions

- CHANGELOG.md
- baseapp/abci.go
Currently the ante events for failed tx are not indexed at all, but ethermint need to rely on them to find some failed txs in json-rpc apis.
---
I have...
I have...
> fix: index ante events for failed tx

- simapp/app.go
- x/auth/client/testutil/suite.go
- x/auth/tx/service_test.go
ref: https://github.com/cosmos/cosmos-sdk/pull/11985#discussion_r879246885
---
I have...
I have...
> refactor: Add Tips decorator in simapp

- CHANGELOG.md
- container/build.go
- container/config.go
- container/container_test.go
Ref: https://github.com/cosmos/cosmos-sdk/issues/11917
The noun should be one which conveys the notion of a *core instruction*.  Other names for this type I've considered:
- Instruction
- Behavior
- Specification
- [Config](https://github.com/cosmos/cosmos-sdk/issues/11917#issuecomment-1135086189) (probably the most straighforward)
-  Trait
---
I have...
I have...
> refactor: rename container.Option to container.Config

- contrib/images/simd-dlv/Dockerfile
- contrib/images/simd-env/Dockerfile
- go.mod
- runtime/app.go
- simapp/app.go
- simapp/sim_test.go
Resolves simulation test failures introduced in #11924.
Symptom of this failure is the descriptive log message
```
Simulating... block 5/50, operation 500/753. Logs to writing to /home/mkoco/.simapp/simulations/2022-05-25_16:39:13.log
simulate.go:302: error on block  5/50, operation (534/753) from x/staking:
failed to execute message; message index: 0: amount is greater than the unbonding delegation entry balance: invalid request [/home/mkoco/go/pkg/mod/cosmossdk.io/errors@v1.0.0-beta.6/errors.go:187]
Comment: unable to deliver tx
```
originating in [x/staking/keeper/msg_server.CancelUnbondingDelegation](https://github.com/cosmos/cosmos-sdk/blob/16badb17be9ad98ec7143d6d45f6643a3c04a71f/x/staking/keeper/msg_server.go#L453).  I was not able to find a concrete fix other than re-adding a new …
> fix: app wiring simulation failures

- x/auth/ante/ante_test.go
- x/auth/ante/sigverify.go
- x/auth/ante/sigverify_test.go
Upstream of my change to Osmosis that makes recheck still check sequence numbers.
This has been incorporated into Terra and Secret Network.
https://github.com/osmosis-labs/cosmos-sdk/pull/58
The antehandler check updated (despite its name) is responsible for checking two things:
1) Sequence Numbers
2) Signatures
Previously on recheck, it skipped the entire check, and therefore skipped both of its responsibilities.
Now it only skips the signature verification component, which was the purpose of recheck. (To save the heavy comptutional burden)
Every node with a default mempool, runs this ante handler check in "recheck" mode, on every single tx in their mempool upon each block being committed. Any tx with an invalidated sequence number will then get evicted from the mempool, ensuring that …
> fix: Make rechecking a tx check the sequence number

- client/flags/flags.go
- docs/core/tips.md
- proto/cosmos/tx/v1beta1/tx.proto
Add some docs and client-facing comments about how tips are ignored if the TipDecorator is not added
---
I have...
I have...
> docs: Ignore tips when TipDecorator is absent

- CHANGELOG.md
- client/tx/factory.go
- x/bank/client/testutil/suite.go
Closes: #12074
---
I have...
I have...
> fix: running a tx with --dry-run returns an error

- types/coin_test.go
- types/events_test.go
Closes: #12112
Make certain test suites run sequentially.
---
I have...
I have...
> fix: Make Test Suites Run Sequentially

- .github/workflows/sims-045.yml
- .github/workflows/sims-046.yml
- remove 60 min timeouts on import sims due to long durations 
---
I have...
I have...
> chore: remove timeout on import sims for 0.45 and 0.46

- CHANGELOG.md
- x/genutil/migrations/v046/migrate.go
- x/staking/migrations/v043/keys.go
- x/staking/migrations/v046/json.go
- x/staking/migrations/v046/json_test.go
- x/staking/migrations/v046/keys.go
ref: #11880 
TEST:
```
./build/v045_node export > old.json
./build/v046_node migrate v0.46 old.json > new.json
./build/v046_node init alice
cp new.json ~/.simapp/config/genesis.json
./build/v046_node start --mode validator
```
The above script panicked on the `start` command before this PR.
---
I have...
I have...
> fix(staking): Fix JSON genesis migration

- CHANGELOG.md
- simapp/app.go
- types/module/simulation.go
This PR is intended to simplify the overhead of the simulation manager setup, in a non-breaking way.
Also removes some of the complexity out of trying to do this independently in your own app, by having a re-usable helper method in the module package (where it belongs) (https://github.com/osmosis-labs/osmosis/pull/1664)
If this conflicts with your plans for app-wiring feel free to just close this. However, as far as I can tell, its still helpful w/ app wiring for app-specific overrides and legacy modules.
---
I have...
> refactor: Simplify SimulationManager setup
