- CHANGELOG.md
- cmd/basecoin/main.go
- cmd/commands/tx.go
- demo/start.sh
- version/version.go
> v0.3.1 - hotfix

- app/app.go
- app/app_test.go
- cmd/commands/tx.go
- cmd/commands/utils.go
- cmd/commands/utils_test.go
- glide.lock
- plugins/counter/counter_test.go
- plugins/ibc/ibc_test.go
- scripts/print_test_account.go
- state/execution.go
- state/execution_test.go
- state/state_test.go
- tests/tmsp/tmsp_test.go
- types/account_test.go
- types/coin.go
- types/coin_test.go
- types/kvstore_test.go
- types/plugin_test.go
- types/test_helpers.go
- types/tx_test.go
Closes #41 
Added full set of unit testing, cleanup of existing changes, minor changes to non-test files
> More Tests + Cleanup

- CHANGELOG.md
- Dockerfile.dev
- Makefile
- RELEASE.md
- ROADMAP.md
- cmd/basecli/commands/auto.go
- cmd/basecli/main.go
- cmd/basecoin/commands/init.go
- cmd/basecoin/commands/start.go
- docs/guide/basecoin-basics.md
- docs/guide/basecoin-plugins.md
- docs/guide/ibc.md
- docs/guide/install.md
- docs/guide/key-management.md
- glide.lock
- glide.yaml
- plugins/ibc/ibc.go
- scripts/dist_build.sh
- tests/cli/basictx.sh
- tests/cli/common.sh
- tests/cli/counter.sh
- tests/cli/ibc.sh
- tests/cli/restart.sh
- version/version.go
Okay, everyone is now actually trying out the tools.  So let's figure out the bugs or UX issues that we want to clean up and release a new version soon. Mainly small-ish things that make us go hmmm.... when really using the code. Not so much new features.
I am using this as a placeholder for discussion.  [All issues for 0.6.1 should have a 0.6.1 tag](https://github.com/tendermint/basecoin/issues?q=is%3Aissue+is%3Aopen+label%3A0.6.1).  If it is a not-so-minor enhancement, but good for usability on the testnet, please add 0.6.x tag to mark it as a bugfix. 0.6.1 is really for top prio (high benefit/work ratio).
Also, [light-client fixes will be done in 0.10.3](https://github.com/tendermint/light-client/issues?q=is%3Aissue+is%3Aopen+label%3A0.10.3) in sync with this release.
> WIP: Release 0.6.1

- app/app.go
- app/app_test.go
- cmd/basecli/commands/cmds.go
- context.go
- docs/guide/counter/cmd/countercli/commands/counter.go
- docs/guide/counter/plugins/counter/counter_test.go
- errors/common.go
- modules/auth/bench_test.go
- modules/auth/signature_test.go
- modules/base/chain.go
- modules/base/chain_test.go
- modules/base/tx.go
- modules/base/tx_test.go
- modules/coin/bench_test.go
- modules/coin/handler_test.go
- stack/context.go
- stack/helpers_test.go
- stack/middleware_test.go
- stack/mock.go
- stack/recovery_test.go
> Add optional expiration height to tx

- docs/guide/basecoin-basics.md
- first part of #192 
- small fixes for flow (no need to start guide with a big warning, esp since it's the beginner guide)
> docs: clean up basecoin-basics

- client/commands/keys/new.go
We can use our ledger to sign our apps.  Thanks @wrl !
Requires PR in go-crypto to be merged first. https://github.com/tendermint/go-crypto/pull/37
> Support for nano ledger in basecli

- docs/basecoin-tool.rst
- docs/key-management.rst
- docs/overview.rst
- docs/roles-and-multi-sig.rst
> docs: some typos

- app/base.go
> tick endblock

- .gitignore
- Makefile
- examples/basecoin/cmd/basecoind/main.go
- glide.lock
- glide.yaml
- tools/Makefile
- tools/glide.lock
- tools/glide.yaml
- tools/go-vendorinstall/main.go
- tools/main.go
AFAIK there are a few pitfalls in trying to do this, and this appears to be the best way to go about it.  We'll need to copy the tools dir into our other projects.
> WIP: Vendor tools into tools/*

- client/query.go
Resolves #327 
This fixes the Errorf() parameters for an error message.
> Fix issue #327 - error message

- .gitignore
- Vagrantfile
closes #234 
Please merge by squashing the commits.
> Working Vagrantfile

- glide.lock
- glide.yaml
- store/rootmultistore.go
- store/rootmultistore_test.go
- store/wire.go
> Do not use global wire.Marshal*

- x/auth/store.go
I'm not sure that this is the best interface for go-wire Marshal, but it seems to match the interface for gob marshalling/unmarshalling.
> wire.UnmarshalBinary expects pointer to struct, never pointer pointer

- docs/design.md
- docs/guide.md
- examples/basecoin/app/init_handlers.go
- types/context.go
- x/bank/handler.go
- x/sketchy/handler.go
SDK2 going forward is deprecated...
> Merge sdk2 to develop

- examples/basecoin/LICENSE
- examples/basecoin/README.md
- examples/basecoin/glide.yaml
- examples/basecoin/tools/Makefile
* Add README.md to Basecoin
* Update licenses
* Remove shelldown from tools
> Basecoin readme

- examples/basecoin/app/app_test.go
> tests for basecoin/app

- docs/apps.md
Simple overview of the "levels" of apps
> docs: notes about the different apps

- Makefile
- docs/guide.md
- docs/sdk/overview.rst
- examples/kvstore/main.go
- examples/kvstore/tx.go
refs: https://github.com/tendermint/abci/issues/196
depends on: https://github.com/tendermint/abci/pull/197 and 
https://github.com/tendermint/tendermint/pull/1223
> rename dummy to kvstore

- Makefile
- examples/basecoin/Makefile
minor fix missing get_tools command specified in readme.md
> basecoin get_tools

- CHANGELOG.md
- store/rootmultistore.go
- store/types.go
- types/store.go
Rescued an old commit from Jae that was against a gaia branch.
@rigelrozanski did you need this ?
> REVIEW: Add GetCommitKVStore and CommitKVStore

- docs/sdk/lcd-rest-api.yaml
This is an OpenAPI definition for the LCD REST server.
Closes: #383
> Add REST API spec

- baseapp/baseapp.go
- baseapp/baseapp_test.go
- examples/basecoin/app/app_test.go
Solves #507 and #474 
Leads to new issue: https://github.com/cosmos/cosmos-sdk/issues/522
> baseapp: fix restarting

- baseapp/baseapp.go
Cleanup related to the fix for https://github.com/cosmos/cosmos-sdk/issues/474
> baseapp: introduce checkState and deliverState to wrap their ms and ctx

- Makefile
- examples/basecoin/Makefile
- examples/basecoin/glide.yaml
This should pass CI.
Please merge to develop. Or if that's too slow, rebase your other PRs on this...
It will make Circle Happy, it will make Frey happy, it will make *you* happy
:smile:
> Remove errant basecoin vendor mess

- baseapp/router.go
- examples/basecoin/app/app.go
> WIP: Add multiple routes simultaneously

- examples/basecoin/app/app_test.go
- types/errors.go
- types/tx_msg.go
- x/auth/ante.go
- x/auth/ante_test.go
- x/auth/mapper.go
- x/auth/mapper_test.go
- x/bank/tx.go
- x/bank/tx_test.go
This is another take on https://github.com/cosmos/cosmos-sdk/pull/436 based on the feedback from there.
Original issue is https://github.com/cosmos/cosmos-sdk/issues/483.
Note this does not address https://github.com/cosmos/cosmos-sdk/issues/455
Notes:
- ErrBadNonce -> ErrInvalidSequence
-  sdk.StdSignDoc and sdk.StdSignBytes
> Replay Protection

- client/builder/builder.go
- examples/basecoin/x/cool/commands/tx.go
- types/tx_msg.go
- x/bank/commands/sendtx.go
> fix cli to sign StdSignDoc. fixes #620

- baseapp/baseapp.go
Adding a check after route to prevent invalid msg type.
Issue: #618
> Fix Issue#618

- x/auth/ante.go
- x/auth/ante_test.go
> Fix auth handler public key issue

- client/builder/builder.go
- examples/basecoin/x/cool/commands/tx.go
- x/bank/commands/sendtx.go
lil' abstraction to clean things up a bit
> StdSignMsg logic into common helper functions

- examples/basecoin/app/app_test.go
- examples/basecoin/x/cool/types.go
- types/errors.go
- x/auth/ante.go
- x/auth/ante_test.go
- x/bank/errors.go
- x/bank/mapper.go
- x/bank/tx.go
> move some errors to sdk from bank

- Gopkg.lock
- store/iavlstore.go
- store/iavlstore_test.go
> added Subspace Iterator to IAVLTree

- CHANGELOG.md
- version/version.go
Thought I'd update the version and changelog as we prepare for a release.
Great work everyone!
> version and changelog

- types/coin.go
- types/coin_test.go
> sdk.Coin arithmetic operations

- Makefile
> Fixing Makefile for build on windows

- examples/basecoin/cmd/basecoind/main.go
- mock/app.go
> Move basecoin.db to ~/.basecoind/data

- x/stake/handler.go
> Allow clearing candidacy fields (closes #723)

- client/lcd/lcd_test.go
- client/lcd/root.go
- x/ibc/rest/root.go
- x/ibc/rest/transfer.go
`POST /ibc/{destChainID}/{address}/send`
https://github.com/cosmos/cosmos-sdk/issues/610
> REST IBC transfer endpoint

- Makefile
replaces https://github.com/cosmos/cosmos-sdk/pull/733
> make install

- .gitignore
- client/lcd/.gitignore
Cleanup the .gitignore file to remove unnecessary items. 
Ideally our tests don't leave directories behind so we shouldn't even need to ignore them ;)
Also found a .gitignore file in client/lcd ... do we need that for something ?
> cleanup gitignore

- x/ibc/commands/README.md
- x/ibc/commands/ibctx.go
- x/ibc/commands/relay.go
1. Fix bug in ibc cli 
2. Add documentation for demo
3. fmt -> tmlibs.log
> IBC hotfix

- examples/basecoin/cmd/basecoind/main.go
- examples/democoin/cmd/democoind/main.go
- examples/gaia/gaiad/main.go
- server/context.go
- server/init.go
- server/init_test.go
- server/reset.go
- server/show_node_id.go
- server/show_validator.go
- server/start.go
- server/start_test.go
- server/test_helpers.go
> More CLI fixes

- Makefile
- cmd/gaiad/main.go
- examples/basecoin/cmd/basecoind/main.go
- examples/democoin/cmd/democoind/main.go
- server/util.go
Final piece for https://github.com/cosmos/cosmos-sdk/issues/725
> add log_level flag

- examples/basecoin/app/app_test.go
- examples/basecoin/types/account.go
- examples/democoin/types/account.go
- types/coin.go
https://github.com/cosmos/cosmos-sdk/issues/787
> sort coins in genesis

- x/stake/errors.go
- x/stake/handler.go
- x/stake/handler_test.go
- x/stake/keeper_test.go
- x/stake/pool_test.go
- x/stake/test_common.go
- x/stake/tick_test.go
> Staking handler tests

- examples/democoin/cmd/democli/main.go
- examples/democoin/x/pow/commands/tx.go
Added the commands to democli but can't seem to get them working ...
> democli: add cool and pow commands

- server/init.go
- wire/wire.go
replaced https://github.com/cosmos/cosmos-sdk/pull/820
> MarshalJSONIndent

- CHANGELOG.md
- types/context.go
- types/context_test.go
> Add CacheContext

- client/core/context.go
> Recreate RPC client on WithNodeURI

- client/context/viper.go
- client/core/context.go
Ref https://github.com/cosmos/cosmos-sdk/pull/812 - cc @rigelrozanski @melekes
> Address PR comments on #812

- CHANGELOG.md
- baseapp/baseapp.go
- baseapp/baseapp_test.go
- client/lcd/lcd_test.go
- cmd/gaiad/main.go
- examples/basecoin/app/app.go
- examples/basecoin/app/app_test.go
- examples/basecoin/cmd/basecoind/main.go
- examples/democoin/app/app.go
- examples/democoin/app/app_test.go
- examples/democoin/cmd/democoind/main.go
Port updated examples & testcases from https://github.com/cosmos/cosmos-sdk/pull/779 to https://github.com/cosmos/cosmos-sdk/pull/859
> Swap all examples & testcases to use automatic DB namespacing

- CHANGELOG.md
- Gopkg.lock
- Gopkg.toml
- baseapp/baseapp.go
- baseapp/baseapp_test.go
- client/lcd/lcd_test.go
- client/rpc/block.go
- client/rpc/status.go
- cmd/gaiad/main.go
- docs/guide.md
- examples/basecoin/app/app.go
- examples/basecoin/app/app_test.go
- examples/basecoin/cmd/basecoind/main.go
- examples/democoin/app/app.go
- examples/democoin/app/app_test.go
- examples/democoin/cmd/democoind/main.go
- store/rootmultistore.go
- store/rootmultistore_test.go
- version/version.go
Depends on https://github.com/tendermint/tmlibs/pull/199 (released to https://github.com/tendermint/tmlibs/releases/tag/0.8.2-rc1)
> Support namespacing within RMS db

- Gopkg.lock
- baseapp/baseapp.go
- baseapp/baseapp_test.go
- baseapp/router.go
- client/lcd/lcd_test.go
- examples/basecoin/app/app.go
- examples/basecoin/app/app_test.go
- examples/democoin/app/app.go
- examples/democoin/app/app_test.go
- examples/democoin/x/pow/handler_test.go
- examples/democoin/x/pow/keeper_test.go
- examples/kvstore/main.go
- mock/app.go
- store/rootmultistore_test.go
- types/context.go
- types/context_test.go
- types/errors.go
- types/errors_test.go
- types/stdlib/stdlib_test.go
- x/auth/ante_test.go
- x/auth/context_test.go
- x/auth/mapper_test.go
- x/ibc/ibc_test.go
- x/simplestake/keeper_test.go
- x/stake/test_common.go
Making some changes as per convo with @cwgoes
> Remove codespace from router; Fix lcd_test

- .circleci/config.yml
Ref https://github.com/cosmos/cosmos-sdk/pull/880
> Add Golint to CircleCI

- x/stake/keeper.go
- x/stake/keeper_keys.go
- x/stake/keeper_test.go
- x/stake/tick.go
- x/stake/types.go
Ref https://github.com/cosmos/cosmos-sdk/issues/582
> Validator age ordering

- cmd/gaia/cli_test/cli_test.go
- server/tm_cmds.go
- x/stake/commands/flags.go
- x/stake/commands/tx.go
Closes #883 
Also while I was at it - declare candidacy now takes go-amino encoded pubkeys
> show_validator displays HEX

- CHANGELOG.md
- x/stake/handler.go
- x/stake/handler_test.go
- x/stake/keeper.go
- x/stake/keeper_test.go
- x/stake/rest/query.go
- x/stake/types.go
- x/stake/view_slash_keeper.go
- x/stake/view_slash_keeper_test.go
Closes https://github.com/cosmos/cosmos-sdk/issues/592
> Expose last bonding/unbonding block

- CHANGELOG.md
- cmd/gaia/app/app.go
- examples/basecoin/app/app.go
- examples/democoin/app/app.go
- x/auth/mapper.go
- x/auth/mapper_test.go
- x/stake/test_common.go
> Remove Account Mapper Seal

- client/keys/delete.go
- client/keys/show.go
- client/keys/update.go
- client/rpc/block.go
- client/rpc/validators.go
- examples/democoin/x/cool/client/cli/tx.go
- examples/democoin/x/pow/client/cli/tx.go
closes #885 
small PR did most of this already in a previous cleanup PR just a few missing
> cobra arg constraints

- CHANGELOG.md
- baseapp/baseapp.go
- cmd/gaia/app/app.go
- types/rational.go
- types/rational_test.go
- x/stake/client/cli/tx.go
- x/stake/handler.go
- x/stake/keeper.go
- x/stake/keeper_test.go
- x/stake/msg.go
- x/stake/pool.go
- x/stake/pool_test.go
- x/stake/test_common.go
- x/stake/tick.go
- x/stake/tick_test.go
- x/stake/types.go
- x/stake/view_slash_keeper_test.go
> rational extends big.Rat

- CHANGELOG.md
- baseapp/baseapp_test.go
- docs/guide.md
- docs/sdk/overview.rst
- examples/democoin/x/cool/types.go
- examples/democoin/x/pow/types.go
- examples/democoin/x/pow/types_test.go
- examples/democoin/x/simplestake/msgs.go
- examples/kvstore/tx.go
- mock/tx.go
- types/account.go
- types/tx_msg.go
- x/auth/baseaccount.go
- x/auth/baseaccount_test.go
- x/bank/msgs.go
- x/bank/msgs_test.go
- x/ibc/types.go
- x/stake/msg.go
> Remove Get function from Msg interface

- .circleci/config.yml
miniest PR 
race condition was fixed
> re-enable race check for cli test

- Gopkg.lock
- Gopkg.toml
- cmd/gaia/app/app_test.go
- types/rational.go
- types/rational_test.go
- x/stake/client/cli/query.go
- x/stake/client/rest/query.go
- x/stake/keeper.go
Uses GoAmino 0.9.9 which fixes MarshalAmino.
Also changed implementation of Rational.[Un]MarshalAmino.
> Use GoAmino 0.9.9 and change impl of Rational.MarshalAmino

- .circleci/config.yml
- Makefile
`make test` seems to not be deterministic
> makefile circle upgrade

- CHANGELOG.md
- server/export.go
Further increase ease-of-utility of state export & restoration
> Export all genesis information (closes #946)

- .circleci/config.yml
- Makefile
- tests/test_cover.sh
remove experimental bash features from ci
> remove go-cli tests from ci

- Dockerfile
Ref https://github.com/cosmos/cosmos-sdk/issues/947
> Update Dockerfile for gometalinter requirement

- CHANGELOG.md
- examples/democoin/x/cool/handler.go
- examples/democoin/x/pow/keeper.go
- examples/democoin/x/simplestake/keeper.go
- types/result.go
- types/tags.go
- types/tags_test.go
- x/bank/handler.go
- x/bank/keeper.go
- x/bank/keeper_test.go
- x/ibc/handler.go
- x/ibc/ibc_test.go
- x/stake/handler.go
Closes https://github.com/cosmos/cosmos-sdk/issues/850
Ref https://github.com/tendermint/tendermint/issues/1385
> ABCI response tagging

- x/stake/keeper.go
- x/stake/keeper_keys.go
- x/stake/keeper_test.go
Messy rebased merge to get some of @cwgoes work in
> fix fee distribution

- CHANGELOG.md
- examples/basecoin/app/app.go
- examples/basecoin/app/app_test.go
- x/auth/ante.go
- x/auth/baseaccount.go
- x/auth/baseaccount_test.go
- x/auth/handler.go
- x/auth/mapper.go
- x/auth/msgs.go
- x/auth/msgs_test.go
> Change PubKey

- server/util.go
> gaiad: print `unsafe_reset_all` only once

- CHANGELOG.md
- Gopkg.lock
- Gopkg.toml
- version/version.go
> update tm to 0.19.4. update changelog and version

- docs/sdk/lcd-rest-api.yaml
updated some parts of the rest spec to sync with actual state
> updated rest spec

- CHANGELOG.md
- Gopkg.lock
- Gopkg.toml
- client/tx/search.go
- version/version.go
> Bucky/tm 0.19.5

- .circleci/config.yml
ref: #1034 
- ensures the example binaries can be compiled
> CI: build the examples

- CHANGELOG.md
- Gopkg.lock
- x/ibc/client/cli/relay.go
> Autosequence IBC relay account nonces

- CHANGELOG.md
- x/stake/validator.go
> fixed duplicate pub_key in stake.Validator

- cmd/gaia/app/app.go
- examples/basecoin/app/app.go
- examples/democoin/app/app.go
- x/auth/ante.go
- x/auth/ante_test.go
- x/auth/context_test.go
- x/auth/feekeeper.go
- x/auth/feekeeper_test.go
- x/auth/mapper_test.go
Added Fee collection to Ante Handler using a Keeper that can be passed to the distribution module,
> Fee Collection in auth

- CHANGELOG.md
- store/cachekvstore.go
- store/dbstoreadapter.go
- store/gaskvstore.go
- store/iavlstore.go
- store/iavlstore_test.go
- types/store.go
- x/stake/keeper.go
> SubspaceIterator as helper function

- .circleci/config.yml
- CHANGELOG.md
- client/keys/utils.go
- client/lcd/lcd_test.go
- cmd/gaia/app/app_test.go
- cmd/gaia/cli_test/cli_test.go
- cmd/gaia/cmd/gaiacli/main.go
- examples/basecoin/cmd/basecli/main.go
- examples/democoin/x/simplestake/msgs.go
- server/start_test.go
- server/test_helpers.go
- tests/gobash.go
- tests/process.go
- tests/tests.go
- tests/util.go
- x/slashing/keeper_test.go
- x/slashing/test_common.go
- x/stake/client/cli/tx.go
- x/stake/errors.go
- x/stake/handler.go
- x/stake/handler_test.go
- x/stake/msg.go
- x/stake/msg_test.go
- x/stake/test_common.go
- x/stake/wire.go
> fix go-bash, add to ci

- Gopkg.lock
- Gopkg.toml
- client/keys/utils.go
- cmd/gaia/cli_test/cli_test.go
- server/tm_cmds.go
- types/account.go
- x/auth/client/cli/account.go
- x/bank/client/cli/sendtx.go
- x/stake/client/cli/query.go
- x/stake/client/cli/tx.go
- x/stake/delegation.go
- x/stake/test_common.go
- x/stake/validator.go
Remove bech32cosmos and use regular old bech32
> Switch from bech32cosmos to bech32

- cmd/gaia/cmd/gaiacli/main.go
- x/slashing/client/cli/flags.go
- x/slashing/client/cli/query.go
- x/slashing/client/cli/tx.go
- x/slashing/signing_info.go
- x/slashing/signing_info_test.go
Ref https://github.com/cosmos/cosmos-sdk/issues/1103
Ref https://github.com/cosmos/cosmos-sdk/issues/1102
> Fix minor slashing issues

- x/slashing/client/cli/query.go
- x/slashing/client/cli/tx.go
> fix for slashing with bech32 change

- .github/PULL_REQUEST_TEMPLATE.md
Add instructions on squash-merging, ref https://github.com/tendermint/coding/pull/63
> Update PR checkboxes

- client/lcd/root.go
Ref https://github.com/cosmos/cosmos-sdk/issues/973
> Feedback on REST server start

- CHANGELOG.md
- client/rpc/validators.go
- docs/sdk/lcd-rest-api.yaml
- docs/staking/intro.rst
- docs/staking/testnet.rst
- x/slashing/client/cli/query.go
> Fix docs for cli refactor

- CHANGELOG.md
- Gopkg.lock
- Gopkg.toml
- client/lcd/lcd_test.go
- server/init.go
- server/start.go
- server/tm_cmds.go
- version/version.go
> update for tm v0.19.9

- CHANGELOG.md
- cmd/gaia/app/app.go
- cmd/gaia/app/app_test.go
- cmd/gaia/cmd/gaiad/main.go
- examples/basecoin/app/app.go
- examples/basecoin/cmd/basecoind/main.go
- examples/democoin/app/app.go
- examples/democoin/cmd/democoind/main.go
- server/constructors.go
- server/export.go
- types/stake.go
- x/stake/genesis.go
- x/stake/validator.go
Closes https://github.com/cosmos/cosmos-sdk/issues/997.
> Export validators to genesis

- x/stake/keeper.go
- x/stake/keeper_keys.go
> 1015 Revoked Candidates in Stake

- CHANGELOG.md
- x/auth/client/cli/account.go
> gaiacli: Add error message for when account isn't found in gaiacli account

- CHANGELOG.md
- client/context/helpers.go
- client/context/types.go
- client/context/viper.go
- client/flags.go
- client/lcd/lcd_test.go
Addresses, in part, https://github.com/cosmos/cosmos-sdk/issues/1180.
> Add --gas flag to specify gas limit for a transaction

- .github/PULL_REQUEST_TEMPLATE.md
Note the header is optimized for the github edit box font
... edit >this< box to see the new comment in action
> PR template improvement

- Gopkg.lock
- Gopkg.toml
- server/tm_cmds.go
Update reset all syntax to what is at the head of tendermint develop.
> Update to tendermint develop

- cmd/gaia/app/genesis.go
Try to fix this issue : https://github.com/cosmos/cosmos-sdk/issues/1226
> fix not showing seed

- CHANGELOG.md
- x/stake/handler_test.go
- x/stake/inflation.go
- x/stake/inflation_test.go
- x/stake/keeper.go
- x/stake/keeper_test.go
- x/stake/shares.go
* [na] Updated all relevant documentation in docs 
- spec needs to be updated with inflation spec creation
* [na] Updated Basecoin / other examples
> Testnet bug develop

- cmd/gaia/testnets/STATUS.md
> Add update testnet guide to status

- .circleci/config.yml
Closes https://github.com/cosmos/cosmos-sdk/issues/1244, and we need to make the lint step optional for merge.
> Move metalinter installation to lint step

- baseapp/baseapp.go
- client/context/helpers.go
- client/input.go
- client/keys/add.go
- client/lcd/root.go
- client/rpc/root.go
- client/tx/search.go
- cmd/gaia/app/genesis.go
- examples/democoin/x/cool/errors.go
- examples/democoin/x/pow/errors.go
- server/export.go
- server/start.go
- server/start_test.go
- store/rootmultistore.go
- types/account.go
- types/coin.go
- types/errors.go
- x/auth/client/rest/query.go
- x/bank/errors.go
- x/ibc/client/cli/relay.go
- x/ibc/errors.go
- x/slashing/errors.go
- x/slashing/tick.go
- x/stake/client/rest/query.go
- x/stake/client/rest/tx.go
- x/stake/errors.go
- x/stake/keeper.go
- x/stake/msg.go
Check it out, I think thats's everything @rigelrozanski
> Set all Error strings 1st letters to lowercase. Fixes issue #1154

- Gopkg.lock
- Gopkg.toml
- server/tm_cmds.go
> Sync to tendermint develop's latest revision

- cmd/gaia/cli_test/cli_test.go
- tests/util.go
> gaia/cli_test: remove sleeps

- tests/util.go
> add comments

- docs/guides/guide.md
- types/store.go
> WIP: Documentation

- cmd/gaia/testnets/README.md
We've been giving our validator candidates solutions to common liveness problems in chat, but it should be in the readme too.
> update testnet readme with solutions to common problems

- cmd/gaia/testnets/README.md
This updates the testnet validator instructions to be more clear. It also addresses a couple of issues:
- https://github.com/cosmos/cosmos-sdk/issues/1302
- https://github.com/cosmos/cosmos-sdk/issues/1303
- https://github.com/cosmos/cosmos-sdk/issues/1304
cc @gamarin2 @adrianbrink
> Update testnet validator instructions

- docs/spec/other/bech32.md
Added a document to specify how bech32 is used within the cosmos ecosystem.
> Added a bech32 spec doc

- cmd/gaia/testnets/README.md
I've removed the other two seed nodes because they seem to be down.
> Fix seed nodes

- .circleci/config.yml
- CHANGELOG.md
- baseapp/baseapp.go
- client/lcd/lcd_test.go
- cmd/gaia/testnets/README.md
- examples/democoin/x/cool/app_test.go
- store/iavlstore_test.go
- types/errors.go
- types/gas.go
- x/auth/stdtx.go
- x/bank/msgs_test.go
- x/gov/keeper.go
Fixes typos and gofmts files. Doesn't fix mispellings in staking package, due to impending PR. 
What to change was determined from: https://goreportcard.com/report/github.com/cosmos/cosmos-sdk
> fix typos and gofmt files

- Gopkg.lock
- Gopkg.toml
> Pin exact versions

- docs/_attic/staking/local-testnet.rst
- docs/spec/staking/transactions.md
- x/stake/keeper.go
- x/stake/keeper_test.go
- x/stake/pool.go
- x/stake/validator.go
> Fix spelling changes

- .circleci/config.yml
- CHANGELOG.md
- Makefile
- client/tx/broadcast.go
- client/tx/sign.go
- examples/basecoin/app/app_test.go
- examples/democoin/x/oracle/oracle_test.go
- x/stake/types/delegation.go
> tools: Add go vet as a linter

- CHANGELOG.md
- Makefile
- client/context/helpers.go
- client/lcd/version.go
- tests/util.go
- tools/Makefile
- types/coin.go
- x/ibc/mapper.go
- x/slashing/tick.go
unconvert checks for unnecessary type conversions
ref #1417
> tools: add unconvert linter

- docs/core/examples/app1.go
- docs/core/examples/app2.go
- docs/core/examples/app3.go
- docs/core/examples/app4.go
My bad, I rebased my branch on develop without really saying anything, so the other PR is conflicting.
I just cherry picked the last commits from #1414
> Bucky aditya/docs core

- CHANGELOG.md
- Makefile
- baseapp/baseapp.go
- baseapp/helpers.go
- cmd/gaia/cmd/gaiacli/main.go
- cmd/gaia/cmd/gaiad/main.go
- examples/basecoin/cmd/basecli/main.go
- examples/basecoin/cmd/basecoind/main.go
- examples/democoin/cmd/democli/main.go
- examples/democoin/cmd/democoind/main.go
- examples/kvstore/main.go
- server/init.go
- server/mock/helpers.go
- server/start.go
- server/test_helpers.go
- server/testnet.go
- server/util.go
- store/iavlstore.go
- store/rootmultistore.go
- tests/util.go
- tools/Makefile
- types/lib/linear.go
- x/auth/ante.go
- x/auth/mapper.go
- x/auth/mock/app.go
- x/bank/keeper.go
- x/gov/genesis.go
- x/slashing/test_common.go
- x/stake/keeper/delegation.go
- x/stake/keeper/test_common.go
This linter ensures that all errors are checked.
This is disabled in the client directories, since its not needed on
those writes
ref #1417
> Tools: Add errcheck linter

- docs/core/examples/app4.go
> Fix build error on develop

- CHANGELOG.md
- Makefile
This adds a command to automatically fix gofmt and misspell errors.
> tools: Add make format

- examples/basecoin/app/app.go
- examples/basecoin/app/app_test.go
- examples/basecoin/cmd/basecli/main.go
- examples/basecoin/cmd/basecoind/main.go
- examples/basecoin/types/account.go
- server/init.go
- Remove any and all staking or slashing dependencies and logic
- Fix `SimpleAppGenState` to generate coin amounts as strings. The go-amino spec has changed, so this was causing a parsing error.
- Cleanup basecoin app test
- Added and improved godocs
- Cleaned up some formatting
<hr>
closes: #1269
> Fix basecoin Example

- store/iavlstore.go
- store/iavlstore_test.go
- store/prefixstore_test.go
State tree pruning to remove old versions, while keeping waypoints along the way to support state syncing later.
#1347 and tendermint/tendermint#828
> State tree pruning

- CHANGELOG.md
- client/keys/add.go
- client/lcd/lcd_test.go
> Fabo/Switch key creation REST output to bech32 address

- baseapp/baseapp_test.go
- cmd/gaia/cmd/gaiadebug/hack.go
- examples/basecoin/app/app.go
- examples/democoin/app/app.go
- examples/democoin/x/oracle/oracle_test.go
- wire/wire.go
- x/ibc/ibc_test.go
> Codec.Seal()

- examples/democoin/cmd/democoind/main.go
- server/init.go
- server/util.go
- server/util_test.go
* Renamed `AppendJSON` to `InsertKeyJSON`.
* Fixed writeGenesisFile by including appState directly part of the initial JSON encoding.
<hr>
closes: #983, #1531 (partially)
> Inconsistent Genesis Generation Key Order

- CHANGELOG.md
- client/keys/delete.go
- crypto/keys/keybase.go
> gaiacli, keys: Improve error message when deleting non-existant key

- CHANGELOG.md
- client/lcd/root.go
* Cleanup rest-server command
* Removed short-hands. This would cause a lot of headache anyway due to nesting so I think we should avoid them when we can.
<hr>
closes: #1501
> Fix LCD rest-server command

- CHANGELOG.md
- cmd/gaia/testnets/README.md
> Add Gov cmds for Gaia-7000

- CHANGELOG.md
- cmd/gaia/app/app.go
- cmd/gaia/cmd/gaiadebug/hack.go
- x/gov/test_common.go
- x/slashing/app_test.go
- x/slashing/test_common.go
- x/stake/app_test.go
- x/stake/genesis.go
- x/stake/genesis_test.go
> prevent zero power validators at genesis

- CHANGELOG.md
- baseapp/baseapp.go
- baseapp/baseapp_test.go
Replacing #1580 , cc @rigelrozanski @alexanderbez
> baseapp: Adding option functions to NewBaseApp

- examples/democoin/cmd/democoind/main.go
> democoin: fix genesis for amino

- CHANGELOG.md
- x/stake/keeper/validator.go
> R4R: Clearer staking logic

- cmd/gaia/cli_test/cli_test.go
Apparent fix for #1597, should keep that issue open though until we understand cause.
> Quick Fix for non deterministic cli test failures

- CHANGELOG.md
- crypto/keys/keybase.go
- crypto/keys/types.go
This is a temporary fix before we overhaul the current keybase API here, as we are blocking other things right now. (e.g. the faucet) see #1657
> crypto/keys: Allow one to export their private key

- CHANGELOG.md
- Gopkg.lock
- server/init.go
> R4R: Write moniker on 'gaiad init' and 'gaiad init gen-tx'

- CONTRIBUTING.md
> R4R: Update CONTRIBUTING.md

- x/gov/keeper.go
- x/gov/proposals.go
> Governance CLI test fixes

- .circleci/config.yml
- CONTRIBUTING.md
- Makefile
- tools/Makefile
This is so that validators can have a more minimal install, but we
can still install linters for developers. (And any other future dev
tools)
Closes #1703
For Admin Use:
> tools: add make {get, update, check}_dev_tools

- CHANGELOG.md
- Makefile
We now ensure that the Gopkg.lock is correct, and that the toml
doesn't depend on any branches, so this is no longer necessary.
Closes #1715
For Admin Use:
> tools: remove `rm -rf vendor/` from `make get_vendor_deps`

- cmd/gaia/testnets/README.md
> Update faucet link in gaia-7001 README

- CHANGELOG.md
- PENDING.md
- baseapp/baseapp.go
- examples/democoin/x/cool/handler.go
- examples/democoin/x/pow/handler.go
- types/context.go
- x/mock/test_utils.go
- x/slashing/app_test.go
- x/slashing/handler.go
Closes https://github.com/cosmos/cosmos-sdk/issues/1120
For Admin Use:
> R4R: Remove ctx.IsCheckTx

- .github/PULL_REQUEST_TEMPLATE.md
> R4R: Update PULL_REQUEST_TEMPLATE.md

- Makefile
Removing it was an accident. My bad.
Also `update_tools` was never in the phony interestingly.
For Admin Use:
> tools: Re-add get_tools to makefile

- PENDING.md
- x/gov/handler.go
- x/gov/tags/tags.go
- x/stake/tags/tags.go
Separate tags into a package to avoid duplicate strings throughout - consistent with tags design in stake - also a teeny bit of non-breaking cleanup
I've labelled as breaking changes, because some of the tag names have changed (one typo, but mostly CamelCase to dash spaces)
For Admin Use:
> R4R: Gov tags cleanup

- cmd/gaia/testnets/STATUS.md
Quick update on Gaia-7001 failure
> Gaia-7001 Consensus Failure

- PENDING.md
- cmd/cosmos-sdk-cli/cmd/init.go
I will write tests in a separate pull request
For Admin Use:
> Some fixes in cosmos-sdk-cli

- cmd/gaia/testnets/README.md
Partially addresses https://github.com/cosmos/cosmos-sdk/issues/1721
Documents how to build your own genesis.json from gen-txs.
> Add some instructions for rolling your testnet

- Gopkg.lock
- x/gov/proposals.go
Bug fixed during testnet internal testing.  Please ping sunny for more info.
> fixed proposaltype string bug

- docs/sdk/core/examples/app2.go
- docs/sdk/core/examples/app2_test.go
- docs/sdk/core/examples/app3.go
- docs/sdk/core/examples/app4_test.go
- x/gov/tally_test.go
> docs: Fix build errors on latest tendermint

- x/gov/tally_test.go
Cache calls to generating the privatekeys, remove repitition in validator
set creation.
For Admin Use:
> gov/tests: Cleanup test file

- x/mock/simulation/random_simulate_blocks.go
- x/mock/simulation/transition_matrix.go
- x/mock/simulation/types.go
- x/mock/simulation/util.go
Pr onto a PR, so default checklist deleted.
For Admin Use:
> simulation: Use transition matrices for simulating validator liveness

- README.md
> link to the new doc website in the readme!

- types/account_test.go
- types/coin_test.go
- types/context_test.go
- types/errors.go
- types/errors_test.go
- types/gas_test.go
- types/int.go
- types/int_test.go
- types/lib/linear_test.go
- types/rational_test.go
- types/result_test.go
- types/store_test.go
- types/tags_test.go
- types/utils_test.go
> Increase coverage of types/

- docs/sdk/core/examples/app4_test.go
- types/coin_test.go
- types/context_test.go
- x/bank/app_test.go
Update `types/coin_test.go` for `sdk.NewInt64Coin` and run `make format`.
For Admin Use:
> Fix develop from FF merge

- client/lcd/lcd_test.go
> Fix build error from BigDec PR in a test file

- CHANGELOG.md
- cmd/gaia/cmd/gaiacli/main.go
- x/stake/client/cli/query.go
> Cherry picked commits for PR 2021

- x/stake/client/cli/tx.go
> R4R compile bug in develop

- CODEOWNERS
the file at ./github/CODEOWNERS overides this one
For Admin Use:
> duplicate/old CODEOWNERS

- examples/basecoin/types/account.go
An outdated comment fixed to be less confusing.
For Admin Use:
> A comment fixed

- store/rootmultistore.go
- store/rootmultistore_test.go
> R4R: Reject duplicate storekey name

- .circleci/config.yml
A recent change in circle is causing issues with people opening PRs from forks: https://discuss.circleci.com/t/saving-cache-stopped-working-warning-skipping-this-step-disabled-in-configuration/24423/2
This removes our use of caching
> Fix Circle issue with merging from forks

- Makefile
- networks/local/README.md
- server/testnet.go
> R4R: Change gaiad testnet example output flag

- PENDING.md
- x/gov/client/rest/rest.go
> R4R: Change proposalID to proposal-id in gov REST

- cmd/gaia/app/app.go
- cmd/gaia/app/genesis.go
Closes https://github.com/cosmos/cosmos-sdk/issues/2097
For Admin Use:
> Correctly read/write governance state

- docs/DOCS_README.md
- docs/config.js
> docs: add config.js for ToC sidebar

- Makefile
Used to work on CircleCI but perhaps something got slower? Decreases `make test_sim_gaia_fast` from 200 blocks to 100 blocks, we'll run longer simulations before releases anyways.
One-line change.
______
For Admin Use:
> Decrease simulation length for CI

- docs/RELEASE_PROCESS.md
this should resolve the docs build issues
https://github.com/vuejs/vuepress/issues/767
> double curlies breaks vuepress - single curlies does not

- docs/config.js
This change will put the documentation into the right folder for website deployments.
______
For Admin Use:
> Updating config.js for docs website build process

- networks/remote/ansible/roles/update-datadog-agent/templates/datadog.yaml.j2
> DataDog hostname reporting fix

- Gopkg.lock
- client/context/context.go
- client/context/query.go
- client/flags.go
- client/lcd/root.go
- client/lcd/test_helpers.go
- server/export_test.go
- server/mock/app.go
- store/multistoreproof.go
- store/multistoreproof_test.go
- store/rootmultistore.go
- tests/util.go
http://jira.bianjie.ai/browse/IRISHUB-238
* Add multistore proof build in rootmultistore
* Enable "gaiacli rest-server" to verify multistore proof
* Add new option for rest-server command: --trust-node
Proceed from:
https://github.com/cosmos/cosmos-sdk/pull/2118
https://github.com/cosmos/cosmos-sdk/pull/2147
https://github.com/cosmos/cosmos-sdk/pull/2177
> R4R: Split LCD implementation PR, part one

- PENDING.md
- scripts/linkify_changelog.py
Just got this same PR merged for tendermint, figured I'd replicate it here.
______
For Admin Use:
> add script to make changelog links actual links

- .gitignore
- Gopkg.lock
- Gopkg.toml
upgrading hsm go client to latest version
> Upgrading ledger-goclient

- PENDING.md
- docs/spec/governance/state.md
- x/gov/endblocker_test.go
- x/gov/genesis.go
- x/gov/handler.go
- x/gov/keeper.go
- x/gov/keeper_test.go
- x/gov/procedures.go
- x/gov/proposals.go
This reverts commit 94b86f85c193c11bcc42c6c99619fad20103bb6b, reversing
changes made to 2a4edcca48e0a81226b231508349f1d060b09cc5.
______
For Admin Use:
> Revert "Merge PR #2217: Governance BFT Time"

- PENDING.md
- x/mock/simulation/random_simulate_blocks.go
> simulation: Stop on SIGTERM

- Gopkg.lock
- Gopkg.toml
- PENDING.md
- store/iavlstore.go
This has a measurable state machine performance improvement (2% at minimum according to simulation). I think we should try to get this into the next SDK release.
______
For Admin Use:
> update to iavl 0.11.0

- client/lcd/lcd_test.go
- x/stake/client/rest/query.go
- x/stake/client/rest/utils.go
- x/stake/stake.go
- x/stake/types/validator.go
- x/stake/types/validator_test.go
resolves #2297 
______
For Admin Use:
> R4R: Remove `BechValidator`

- store/rootmultistore.go
Closes: #2329
______
For Admin Use:
> R4R: RootMultiStore LoadVersion iterates over storesParams

- x/mock/doc.go
- x/mock/simulation/doc.go
These fell out of sync
______
For Admin Use:
> update doc.go for mock/simulation

- client/lcd/lcd_test.go
- client/lcd/root.go
- cmd/gaia/app/app.go
- cmd/gaia/cmd/gaiacli/main.go
- cmd/gaia/cmd/gaiadebug/hack.go
Disable the entrypoints to the IBC module from LCD, cli, debugcli, and rest interfaces, while it is still in development and not ready for exposure.
Disabled LCD IBC temporarily test since it will fail without the route existing.
- [n/a] Linked to github-issue with discussion and accepted design OR link to spec that describes this work.
- [n/a] Wrote tests
- [n/a] Updated relevant documentation (`docs/`)
- [n/a] Added entries in `PENDING.md` with issue # 
- [n/a] rereviewed `Files changed` in the github PR explorer
______
For Admin Use:
- Squashed all commits, …
> Remove IBC entrypoints

- PENDING.md
- docs/spec/governance/state.md
- x/gov/endblocker_test.go
- x/gov/genesis.go
- x/gov/handler.go
- x/gov/keeper.go
- x/gov/keeper_test.go
- x/gov/procedures.go
- x/gov/proposals.go
- x/gov/simulation/msgs.go
- x/mock/simulation/constants.go
closes #2195 
closes #2264
reimplements #2217
Turns out #2217 is likely not the cause of the non determinism.
______
For Admin Use:
> R4R: Goverance BFT Time 2: Electric Boogaloo

- PENDING.md
- baseapp/baseapp.go
Closes #1406
______
For Admin Use:
> baseapp: Automatically add action tags to messages

- docs/clients/service-providers.md
Moving service provider doc from https://github.com/cosmos/cosmos.network/pull/187 to here.
> R4R: Service Provider doc

- Gopkg.lock
- PENDING.md
- client/keys/show.go
Closes: #2388
______
For Admin Use:
> Remove dependency on tendermint/tmlibs

- x/gov/keeper.go
- x/gov/proposals.go
- x/gov/proposals_test.go
- x/gov/queryable.go
No externally facing change (the testcases were intended to prove this)
______
For Admin Use:
> remove redundant sprintf calls, improve a doc comment, write test

- client/keys/add.go
- tools/Makefile
- types/errors.go
- x/auth/ante.go
- x/bank/client/rest/sendtx.go
- x/gov/client/cli/tx.go
- x/gov/client/rest/rest.go
- x/gov/keeper.go
- x/ibc/client/cli/relay.go
- x/ibc/client/rest/transfer.go
- x/slashing/client/rest/tx.go
- x/slashing/keeper.go
- x/stake/client/rest/query.go
- x/stake/client/rest/tx.go
- x/stake/keeper/slash.go
- x/stake/keeper/validator.go
- x/stake/types/inflation_test.go
Remove remaining remnants of gocyclo. Not sure if this warrants a pending log update as there already is a pending entry from via #2211.
______
For Admin Use:
> R4R: Remove Remnants of gocyclo

- types/coin_test.go
I was curious how long this took since we don't take advantage of the coins already being sorted, so I wrote a couple benchmarks.
______
For Admin Use:
> types/coins: Add benchmarks for coins addition

- docs/sdk/sdk-by-examples/simple-governance/module-handler.md
- examples/democoin/x/cool/handler.go
- examples/democoin/x/pow/handler.go
- x/bank/handler.go
- x/ibc/handler.go
The reflection here just seemed strange to me. 
______
For Admin Use:
> Remove reflection from handlers

- docs/DOCS_README.md
- docs/README.md
see https://github.com/tendermint/tendermint/pull/2497
goes with https://github.com/cosmos/cosmos.network/pull/276
closes https://github.com/tendermint/devops/issues/41
commit with automatically be added to docs during the Jenkins build
> docs: add version

- docs/validators/validator-faq.md
> Fix typo val faq

- docs/PRIORITIES.md
> Update priorities file

- README.md
- docs/README.md
- docs/getting-started/installation.md
- docs/getting-started/networks.md
- docs/introduction/tendermint.md
- docs/sdk/clients.md
> update some links

- docs/.vuepress/config.js
> hotfix docs

- .circleci/config.yml
For whatever reason the `localnet` test was using a different Docker image with the wrong Go version.
The right Go version is now installed manually.
______
For Admin Use:
> R4R: Fix CircleCI

- PENDING.md
- x/distribution/types/codec.go
- x/distribution/types/dec_coin.go
- x/distribution/types/dec_coin_test.go
- x/distribution/types/delegator_info.go
- x/distribution/types/delegator_info_test.go
- x/distribution/types/errors.go
- x/distribution/types/fee_pool.go
- x/distribution/types/fee_pool_test.go
- x/distribution/types/genesis.go
- x/distribution/types/keepers.go
- x/distribution/types/msg.go
- x/distribution/types/msg_test.go
- x/distribution/types/test_utils.go
- x/distribution/types/validator_info.go
- x/distribution/types/validator_info_test.go
Ref #1671
Breakout PR for https://github.com/cosmos/cosmos-sdk/pull/2236
Just adds the types folder for distribution
______
For Admin Use:
> R4R: Distr-PR-4 Distribution Types

- x/stake/keeper/key.go
- x/stake/keeper/key_test.go
> R4R: Add tests for more staking key operations as requested

- Gopkg.lock
- Gopkg.toml
- PENDING.md
- types/context.go
> Update to tm version v0.25.0

- x/mock/simulation/random_simulate_blocks.go
Closes https://github.com/cosmos/cosmos-sdk/issues/2459
______
For Admin Use:
> R4R: Fix simulation proposer

- docs/spec/ibc/README.md
- tools/gometalinter.json
Closes https://github.com/cosmos/cosmos-sdk/issues/2457
______
For Admin Use:
> Fix IBC paper link

- store/prefixstore.go
- store/prefixstore_test.go
Closes: #2243
______
For Admin Use:
> R4R: Fix PrefixIterator

- baseapp/baseapp.go
> fix bounds checking and missing return

- client/lcd/lcd_test.go
- client/lcd/test_helpers.go
> R4R:  Fix gov deposit query lcd non-determinism

- types/utils.go
- x/stake/keeper/key.go
> WIP:  Fix non-determinism around unbonding queues

- x/gov/msgs.go
- x/gov/proposals.go
Closes #2512 and closes #2505
___
______
For Admin Use:
> R4R: Fixed naming for proposal id and time

- baseapp/baseapp.go
- cmd/gaia/app/app.go
- cmd/gaia/app/sim_test.go
- docs/spec/staking/hooks.md
- types/stake.go
- x/distribution/keeper/hooks.go
- x/distribution/types/validator_info.go
- x/slashing/hooks.go
- x/slashing/hooks_test.go
- x/stake/genesis.go
- x/stake/handler.go
- x/stake/keeper/delegation.go
- x/stake/keeper/hooks.go
- x/stake/keeper/keeper.go
- x/stake/keeper/slash.go
- x/stake/keeper/val_state_change.go
> Compare Jae/Chris branches

- examples/basecoin/cmd/basecoind/main.go
- examples/democoin/cmd/democoind/main.go
Fixes a typo in the json output for basecoin and democoin.
> R4R Typo fix

- x/mock/simulation/util.go
Previously was starting at 0, which was confusing in the logs
/cc @rigelrozanski 
______
For Admin Use:
> fix block offsets in printing simulation block number

- PENDING.md
- x/auth/mapper_test.go
Ref: https://github.com/cosmos/cosmos-sdk/issues/2652
I update the  benchmark of get account and add a benchmark for set account. and I add more coins for  test accounts.
> [R4R] Add benchmark for get and set account

- client/lcd/certificates.go
- client/lcd/certificates_test.go
Closes: #2664
______
For Admin Use:
> [R4R] Include DNS alt name in certificate

- client/lcd/root.go
- server/util.go
> Gaialite signal handling is broken, repair it

- PENDING.md
- server/util.go
Closes #2742
______
For Admin Use:
> [R4R] Fix TimeoutCommit

- Makefile
- cmd/cosmos-sdk-cli/cmd/init.go
- docs/intro/ocap.md
> fix examples tests

- CONTRIBUTING.md
> Add peer review comment

- PENDING.md
- cmd/gaia/init/gentx.go
Closes: #2804
______
For Admin Use:
> R4R: Check whether key passed with --name exists before redirecting to tx create-validator

- docs/README.md
fixes a dead link
same as https://github.com/tendermint/tendermint/pull/2849
______
For Admin Use:
> fix dead link

- docs/.vuepress/config.js
- docs/clients/lite/getting_started.md
- docs/clients/lite/specification.md
> R4R: DOCS: fix sidebar

- Gopkg.lock
- Gopkg.toml
- Makefile
- baseapp/baseapp.go
- baseapp/baseapp_test.go
- cmd/gaia/app/app.go
- cmd/gaia/cmd/gaiadebug/hack.go
- docs/examples/basecoin/app/app.go
- docs/examples/democoin/app/app.go
- docs/examples/kvstore/main.go
- server/mock/app.go
- store/cachekvstore.go
From testing/review of https://github.com/cosmos/cosmos-sdk/pull/2900.
- Update upstream versions consistently
- Linter fixes
- Pin revisions
- Rename `MountStoresIAVL` to `MountStores`
______
For Admin Use:
> WIP: Fixes to simulator improvements

- docs/gaia/join-testnet.md
- docs/gaia/validators/validator-setup.md
> R4R: Update genesis docs

- PENDING.md
- client/lcd/root.go
- cmd/gaia/cmd/gaiacli/main.go
- docs/examples/basecoin/cmd/basecli/main.go
- docs/examples/democoin/cmd/democli/main.go
Refactor that way we create and start Gaia Lite. This maintains the existing flexibility.
closes: #2907
----
______
For Admin Use:
> R4R: Refactor Gaia Lite bootstrapping

- docs/gaia/join-testnet.md
- docs/spec/ics/ics-030-signed-messages.md
> R4R: Fix Markdown File Path

- Gopkg.lock
- Gopkg.toml
- PENDING.md
- client/rpc/validators.go
> R4R: Update to Tendermint v0.27.0-dev0

- Gopkg.lock
- Gopkg.toml
Checkboxes n/a, just updating to fix https://github.com/tendermint/tendermint/pull/2941.
______
For Admin Use:
> Update to TM 0.27-dev1

- Gopkg.lock
- Gopkg.toml
> Update IAVL to 0.12.0

- docs/gaia/networks.md
> R4R: Update single node network bootstrapping documentation

- .circleci/config.yml
- PENDING.md
> changed docs deployment to trigger on every push to master/develop

- .circleci/config.yml
> hotfix get docs deploying on master

- client/keys/add.go
- cmd/gaia/cli_test/cli_test.go
Thanks to @cwgoes  for pointing this out.
______
For Admin Use:
> R4R: add command asks for encryption password once too many

- Makefile
- cmd/gaia/cli_test/cli_test.go
> R4R: Run cli test suite in parallel

- Gopkg.lock
- Gopkg.toml
Title
cc @jaekwon @cwgoes @rigelrozanski @alexanderbez @alessio
> R4R: Update to 0.27 final of Tendermint

- PENDING.md
- cmd/gaia/cmd/gaiareplay/main.go
- docs/spec/governance/overview.md
- docs/spec/governance/state.md
- x/gov/genesis.go
- x/gov/params.go
- x/gov/tally.go
- x/gov/tally_test.go
> R4R:  Governance Quorum

- x/stake/keeper/test_common.go
Fixes linter on `develop`, one-line change.
______
For Admin Use:
> R4R: Fix linter

- docs/gaia/join-testnet.md
- docs/gaia/ledger.md
- docs/gaia/validators/security.md
- docs/gaia/validators/validator-setup.md
> make sidebar titles nicer

- docs/.vuepress/config.js
same as https://github.com/tendermint/tendermint/pull/3014
______
For Admin Use:
> nice config options for docs

- docs/DOCS_README.md
- closes https://github.com/tendermint/devops/issues/114 and documents https://github.com/tendermint/devops/issues/117
- same as https://github.com/tendermint/tendermint/pull/3019
______
For Admin Use:
> update docs readme

- .gitignore
- docs/.vuepress/config.js
same as https://github.com/tendermint/tendermint/pull/3041
______
For Admin Use:
> add rpc link to docs navbar

- PENDING.md
- client/lcd/test_helpers.go
- cmd/gaia/app/app.go
- cmd/gaia/app/app_test.go
- cmd/gaia/app/sim_test.go
- cmd/gaia/cmd/gaiad/main.go
- cmd/gaia/cmd/gaiareplay/main.go
Closes https://github.com/cosmos/cosmos-sdk/issues/3147
We should figure out why this still worked in the testing CI script. Anyway, not a hard fix.
______
For Admin Use:
> R4R: Fix gaiad export

- .circleci/config.yml
- README.md
- docs/gaia/installation.md
- scripts/install/install_sdk_arm.sh
- scripts/install/install_sdk_bsd.sh
- scripts/install/install_sdk_ubuntu.sh
> update go version

- docs/intro/sdk-app-architecture.md
- [X ] Updated relevant documentation (`docs/`)
______
For Admin Use:
> [DOCS] Fix link to ABCI in SDK Application Architecture

- x/distribution/keeper/hooks.go
Add comment describing intent / safety.
______
For Admin Use:
> Add comment outlining safety of commission-withdraw

- .circleci/config.yml
- [] Updated relevant documentation (`docs/`)
______
For Admin Use:
> fixed makefile target in macos build job

- docs/gaia/validators/validator-setup.md
> R4R: s/steak/STAKE in validator-setup

- types/coin.go
- x/bank/keeper.go
- x/bank/keeper_test.go
- x/bank/msgs.go
closes: #3209
---- 
______
For Admin Use:
> R4R: Add IsValid check on sendCoins

- CHANGELOG.md
- types/coin.go
- types/coin_test.go
- x/bank/keeper.go
- x/bank/keeper_test.go
- x/bank/msgs.go
Hotfix for 0.29.1, following the [hotfix process](https://github.com/cosmos/cosmos-sdk/pull/3177/files#diff-ef3e75852e1f40a6cfbe0c151be27ef2R18) as I understand it.
This is a bit messy because we've since also made a change to require lowercase denominations, which we do *not* want to merge to GoS - I had to edit the changes a bit, we'll want to merge master back in afterwards and ensure we keep the state of the code on develop.
cc @zmanian 
______
For Admin Use:
> R4R: Hotfix v0.29.1 for GoS

- CHANGELOG.md
- PENDING.md
Merge master back to develop after #3214.
______
For Admin Use:
> Merge master back to develop

- .circleci/config.yml
- PENDING.md
- scripts/multisim.sh
> R4R: extended running time for multi-sim test

- x/gov/endblocker_test.go
- x/gov/genesis.go
- x/gov/genesis_test.go
- x/gov/keeper_test.go
- x/gov/params.go
- x/gov/querier_test.go
- x/gov/tally_test.go
- x/gov/test_common.go
> WIP:  Added test for governance queues import/export fix

- types/coin_test.go
> R4R: Increase coins test coverage

- cmd/gaia/cli_test/cli_test.go
- types/coin.go
- types/coin_test.go
- Fix `IsAnyGTE`
- Remove unused `IsAnyGT`
closes: #3262 
----
______
For Admin Use:
> R4R: Fix IsAnyGTE

- Gopkg.lock
- Gopkg.toml
- PENDING.md
> R4R: Upgrade Tendermint to 0.27.4

- docs/.vuepress/config.js
- docs/gaia/what-is-gaia.md
Just a quick little PR to add some clarity
> R4R: DOCS: Add What is gaia to docs

- Gopkg.lock
- Gopkg.toml
- PENDING.md
Closes: #3298
______
For Admin Use:
> R4R: Upgrade to latest tendermint

- PENDING.md
> Fix pending

- x/distribution/client/module_client.go
This is an error
______
For Admin Use:
> R4R: Change name of gaiacli query distr to dist

- Dockerfile
> R4R: updated dockerfile with makefile changes

- x/auth/account.go
- x/auth/simulation/fake.go
- Fix `Stringer` vesting account implementations (fixed tabbing and removed pubkey)
- Reconciled `SimulateDeductFee` with the ante handler
closes: #3355 
----
______
For Admin Use:
> R4R: Simulation Fee Deduction Fixes

- x/auth/simulation/fake.go
> fix sim fees

- x/distribution/keeper/delegation.go
- x/distribution/keeper/validator.go
- x/staking/keeper/slash.go
Closes https://github.com/cosmos/cosmos-sdk/issues/3370. Need to floor effective slash fraction.
Also adds several sanity checks.
______
For Admin Use:
> R4R: Floor slash fraction

- x/staking/types/params.go
- x/staking/types/pool.go
closes #3392 
also align to stay consistent with other `String()` functions in staking
______
For Admin Use:
> R4R: typo - update staking `String()`

- x/auth/account.go
closes: #3401
----
______
For Admin Use:
> R4R: Remove Pubkey field from BaseAccount#String

- .github/CODEOWNERS
- docs/.vuepress/config.js
- also updates CODEOWNERS
______
For Admin Use:
> fix docs navbar RPC link

- Makefile
- snapcraft.yaml.in
First draft of snap packaging for Linux distributions.
Packages are built from HEAD. No upload/publish actions are performed.
______
For Admin Use:
> R4R: Snap packaging

- Makefile
- cmd/gaia/app/app.go
- cmd/gaia/app/app_test.go
- cmd/gaia/app/export.go
- cmd/gaia/app/genesis.go
- cmd/gaia/app/sim_test.go
- cmd/gaia/cmd/gaiadebug/hack.go
- x/bank/app_test.go
- x/bank/bench_test.go
- x/bank/errors.go
- x/bank/genesis.go
- x/bank/handler.go
- x/bank/keeper.go
- x/bank/keeper_test.go
- x/bank/params.go
- x/bank/simulation/msgs.go
- x/distribution/keeper/test_common.go
- x/gov/endblocker_test.go
- x/gov/test_common.go
- x/ibc/app_test.go
- x/ibc/ibc_test.go
- x/slashing/app_test.go
- x/slashing/test_common.go
- x/staking/app_test.go
- x/staking/keeper/test_common.go
Closes: #3367
______
For Admin Use:
> R4R: Implement parameter-controlled bank/send switch-off

- .circleci/config.yml
- Makefile
- scripts/Makefile
Upgrade gometalinter
______
For Admin Use:
> Upgrade gometalinter

- .circleci/config.yml
Fixes CI on develop, previously failing due to resource exhaustion.
______
For Admin Use:
> R4R: Fix long multi-seed simulation

- .circleci/config.yml
- snapcraft-full.yaml.in
- snapcraft.yaml.in
> R4R: Autobuild snap

- client/config.go
- cmd/gaia/cmd/gaiacli/main.go
I don't think this needs a pending or anything else. Just a quick PR cc @alessio
> R4R: Fix usage of the config command in applications importing the SDK

- .circleci/config.yml
- README.md
- docs/gaia/installation.md
- scripts/install/install_sdk_arm.sh
- scripts/install/install_sdk_bsd.sh
- scripts/install/install_sdk_ubuntu.sh
Rationale: fixes upstream issue https://github.com/golang/go/issues/29903
______
For Admin Use:
> R4R: Upgrade to go 1.11.5

- PENDING.md
- x/distribution/alias.go
- x/distribution/client/common/common.go
- x/distribution/keeper/querier.go
> R4R distr query validators

- x/auth/params.go
- x/slashing/params.go
> R4R: Reconcile Genesis JSON Tags

- docs/gaia/delegator-guide-cli.md
> Fix table of content delegator guide

- docs/.vuepress/config.js
> Add delegator guide to website

- docs/.vuepress/config.js
Missing quote is breaking the build of the docs
> urgent: fix broken docs build

- Gopkg.lock
> R4R: Update dependancies

- client/lcd/test_helpers.go
> Ensure mint/inflation params respect flag supplied by the caller

- Gopkg.lock
- Gopkg.toml
- PENDING.md
closes: #3542
----
______
For Admin Use:
> Tendermint Upgrade

- docs/RELEASE_PROCESS.md
Update release procedure to ensure both master and develop sit on top of the same commit after release.
______
For Admin Use:
> R4R: Update RELEASE_PROCESS.md

- cmd/gaia/app/genesis.go
- cmd/gaia/app/genesis_test.go
> gaia/genesis.go: rename bondDenom to defaultBondDenom to avoid confusion

- docs/gaia/delegator-guide-cli.md
> DOCS: Improve Delegator Guide

- docs/gaia/delegator-guide-cli.md
> DOCS: fix withdraw

- docs/gaia/delegator-guide-cli.md
> Fix delegator guide typo

- crypto/keys/keybase_test.go
> R4R: Fix CI test failure

- docs/gaia/launch/launch-blog-1.md
Add launch comms blog 1 to SDK docs repo
______
For Admin Use:
> docs: add launch blog post.

- docs/gaia/delegator-guide-cli.md
- docs/gaia/ledger.md
Closes https://github.com/cosmos/cosmos-sdk/issues/3337
______
For Admin Use:
> DOCS: improve ledger docs

- CHANGELOG.md
- PENDING.md
Release PR to develop.
Corresponding PR to master: https://github.com/cosmos/cosmos-sdk/pull/3660.
______
For Admin Use:
> R4R: Release v0.32.0 back to develop

- cmd/gaia/cmd/gaiadebug/main.go
> add validator consensus pubkey for ease of pubkey conversion

- .circleci/config.yml
- Every version change will have its own docker image, ready to be pulled by clients
- CircleCi configuration push those tags, or override them if already present
______
For Admin Use:
> R4R CCI: Add tags for every version in docker repo

- docs/gaia/delegator-guide-cli.md
> Docs: Fix typo in delegator guide

- docs/gaia/deploy-testnet.md
> R4R: tutorial doc patch

- server/export.go
> R4R:  Fix errcheck lint

- PENDING.md
- client/keys/add.go
> R4R: Fix keys add --interactive regression

- docs/gaia/launch/blog-2-en.md
> docs: add launch blog post 2

- docs/translations/kr/gaia/gaiacli.md
- Fixed a few typos
- Added Korean descriptions for command line inputs
______
For Admin Use:
> DOCS: (KR) fix typo, add description

- docs/gaia/validators/validator-faq.md
Updating content 
______
For Admin Use:
> DOCS: Validator FaQ Review

- x/distribution/types/msg.go
> Fix improper distr msg tag

- PENDING.md
- server/export.go
Fixes: https://github.com/cosmos/cosmos-sdk/issues/3741
> Fix Export Panic

- PENDING.md
- cmd/gaia/app/app.go
- cmd/gaia/app/genesis.go
- cmd/gaia/cmd/gaiadebug/hack.go
- docs/gaia/validators/validator-setup.md
- x/slashing/app_test.go
- x/slashing/handler.go
- x/slashing/handler_test.go
- x/slashing/keeper.go
- x/slashing/keeper_contracts.go
- x/slashing/test_common.go
Allow unjailing when a validator has no self-delegation and during disabled transfers. We should run a long multisim w/ transfers disabled with said change.
closes: #3760
----
______
For Admin Use:
> Allow Validator w/ No Self-Delegation to Unjail (Transfers Disabled)

- PENDING.md
- cmd/gaia/app/app.go
- cmd/gaia/app/genesis.go
- cmd/gaia/cmd/gaiadebug/hack.go
- docs/gaia/validators/validator-setup.md
- x/slashing/app_test.go
- x/slashing/handler.go
- x/slashing/handler_test.go
- x/slashing/keeper.go
- x/slashing/keeper_contracts.go
- x/slashing/test_common.go
Reverts cosmos/cosmos-sdk#3762
> Revert "Allow Validator w/ No Self-Delegation to Unjail (Transfers Disabled)"

- x/staking/simulation/msgs.go
Pretty self-explanatory.
______
For Admin Use:
> R4R: Simulator: Make BeginRedelegate log message consistent with other log messages

- x/staking/types/msg.go
Pretty self-explanatory.
______
For Admin Use:
> R4R: Have MsgCreateValidator.UnmarshalJSON return an error rather than panic

- Gopkg.lock
- Gopkg.toml
- PENDING.md
- server/start.go
Fixes: https://github.com/cosmos/cosmos-sdk/issues/3781
> Update to Tendermint 0.31.0-rc0

- Gopkg.lock
- Gopkg.toml
- PENDING.md
- crypto/ledger_real.go
Closes #3681 
______
For Admin Use:
> Migrate repo to organization

- x/distribution/simulation/invariants.go
Disabling the distribution `CanWithdrawInvariant` invariant speeds up simulation noticeably.
/cc @jaekwon 
----
______
For Admin Use:
> Simulation Performance Improvements

- CHANGELOG.md
- PENDING.md
- x/distribution/simulation/invariants.go
> Release 0.33.0 to Develop

- types/coin.go
- types/coin_test.go
See #3678 
______
For Admin Use:
> Port IsAllGT from safe-coins PR

- .circleci/config.yml
- Fixes: #3848
-  force setup_dependencies to run also for tags
______
For Admin Use:
> Fix: CircleCI for Tags

- docs/gaia/join-mainnet.md
- Closes #3890 
______
For Admin Use:
> Fix link to genesis

- docs/gaia/launch/blog-3-en.md
> docs: create blog-3-en.md

- docs/_attic/sdk/core/app1.md
- docs/gaia/delegator-guide-cli.md
- docs/gaia/gaiacli.md
- docs/gaia/installation.md
- docs/gaia/validators/validator-faq.md
- docs/gaia/what-is-gaia.md
- docs/spec/governance/01_concepts.md
- docs/spec/governance/02_state.md
- docs/spec/slashing/04_begin_block.md
- docs/spec/staking/01_state.md
Nothing big here: Just a bunch of typos I stumbled upon while reading https://cosmos.network/docs/gaia/installation.html#install-gaia and other parts of the documentation. 
Does the SDK linter not spellcheck markdown files?
______
For Admin Use:
> Fix a bunch of typos while skimming through the docs

- .pending/improvements/sdk/3940-Codespace-shoul
- x/distribution/types/errors.go
close: #3940 
______
For Admin Use:
> Codespace should be lowercase.

- x/gov/genesis.go
> Gov ValidateGenesis fix

- client/flags.go
Fix typo from #3970.
/cc @petejkim
----
______
For Admin Use:
> Fix Flag Typo

- .pending/bugfixes/gaia/3996-Change-make-get
- docs/DOCS_README.md
> R4R: Change 'make get_tools' to 'make tools' in DOCS_README.md.

- client/lcd/lcd_test.go
closes https://github.com/cosmos/cosmos-sdk/issues/3739
I don't think merits pending entry
https://circleci.com/gh/cosmos/cosmos-sdk/93261?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
______
For Admin Use:
> disable non-deterministic lcd test

- crypto/keys/lazy_keybase_test.go
- crypto/keys/mintkey/mintkey_test.go
This aims to increase ./crypto package coverage.
______
For Admin Use:
> Increase crypto coverage

- .pending/features/gaia/3886-Implement-minting-module-querier-and-CLI-REST-clients
- client/lcd/lcd_test.go
- client/lcd/swagger-ui/swagger.yaml
- client/lcd/test_helpers.go
- cmd/gaia/app/app.go
- cmd/gaia/cmd/gaiacli/main.go
- docs/gaia/gaiacli.md
- x/mint/client/cli/query.go
- x/mint/client/module_client.go
- x/mint/client/rest/query.go
- x/mint/client/rest/rest.go
- x/mint/keeper.go
- x/mint/minter.go
- x/mint/params.go
- x/mint/querier.go
- x/mint/querier_test.go
- x/mint/test_common.go
* Implement minting querier
* Implement CLI and REST clients for the minting module/querier
closes: #3886
----
______
For Admin Use:
> Mint/Inflation Querier

- docs/gaia/validators/security.md
close: #3871
______
For Admin Use:
> R4R: Fix Documentation Inconsisteny #3871

- Makefile
Remove build from .PHONY, add it to clean
______
For Admin Use:
> Handle build/ directory correctly

- docs/spec/ibc/README.md
Update the IBC specification in this repo to link to the ICS repo (leaving the spec as-is, I don't think we need to delete it, just be clear that it won't be canonical).
______
For Admin Use:
> Link to latest IBC spec

- .pending/breaking/tendermint/4001-Upgrade-Tendermint-to-v0-31-1
- .pending/breaking/tendermint/4029-Upgrade-Tendermint-to-v0-31-3
- client/keys/show_test.go
- go.mod
- go.sum
> Update Tendermint to v0.31.3

- .pending/bugfixes/gaia/3999-fix-distribution-export
- CHANGELOG.md
- cmd/gaia/app/export.go
Merge hotfix release v0.33.1 into `master`. The `release/v0.33.1` branch is based off of `release/v0.33.0` which is already in `develop`. The corresponding fixe(s) in this are also already in `develop`.
----
______
For Admin Use:
> Hotfix release/v0.33.1 (master)

- x/mint/client/module_client.go
> Fix tiny typo

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/feature-request.md
Adds a version section to the bug report template.
----
______
For Admin Use:
> Update bug report template

- docs/.vuepress/config.js
> Fix docs build develop

- docs/.vuepress/config.js
Second attempt
______
For Admin Use:
> Fix docs build 2

- go.mod
- go.sum
> Update Tendermint to the 0.31.4 release

- cmd/gaia/app/sim_test.go
Fix build failure introduced with 722d122da7cfa77e00afacabe2624fc65c50cb35
______
For Admin Use:
> Fix develop's build

- .pending/improvements/gaiarest/4123-Fix-typo-url-er
- docs/clients/lite/getting_started.md
- docs/clients/lite/specification.md
- docs/clients/service-providers.md
> Fix typo, url error and outdated command description of doc clients.

- x/distribution/keeper/allocation.go
- x/distribution/keeper/delegation.go
- x/distribution/keeper/keeper.go
- x/gov/endblocker.go
- x/gov/keeper.go
- x/slashing/keeper.go
- x/slashing/tick.go
- x/staking/keeper/keeper.go
- x/staking/keeper/slash.go
Closes: #4124
______
For Admin Use:
> Add module-wide named loggers

- .pending/improvements/tendermint/Upgrade-tendermint-t
- go.mod
- go.sum
> Upgrade tendermint to 0.31.5

- docs/RELEASE_PROCESS.md
Updated release process document. Please review and discuss.
> R4R: Updated release process documentation

- cmd/gaia/contrib/sim/multisim.sh
> Better signal handling for multisim.sh

- cmd/gaia/contrib/sim/multisim.sh
> multisim.sh: avoid termination by lack of output

- .pending/breaking/gaia/4053-Add-inv-che
- CHANGELOG.md
- client/config.go
- client/lcd/test_helpers.go
- client/rpc/codec.go
- cmd/gaia/app/app.go
- cmd/gaia/app/app_test.go
- cmd/gaia/app/invariants.go
- cmd/gaia/app/sim_test.go
- cmd/gaia/cmd/gaiacli/main.go
- cmd/gaia/cmd/gaiad/main.go
- cmd/gaia/cmd/gaiareplay/main.go
- crypto/amino.go
- crypto/keys/hd/fundraiser_test.go
- crypto/keys/hd/hdpath_test.go
- x/auth/client/txbuilder/txbuilder.go
- x/mint/client/module_client.go
This cherry picks #4083 already on `develop` to v0.34.2.
----
______
For Admin Use:
> Cherry pick 4083 v0.34.2

- .pending/features/sdk/4099-Update-the-staking-validators-endpoint-to-support
- CHANGELOG.md
- client/lcd/swagger-ui/swagger.yaml
- client/tx/query.go
- types/staking.go
- x/staking/alias.go
- x/staking/client/rest/query.go
- x/staking/keeper/validator_test.go
- x/staking/querier/querier.go
- x/staking/querier/querier_test.go
- x/staking/types/validator.go
This cherry picks #4181 already on `develop` to v0.34.2.
----
______
For Admin Use:
> Cherry pick 4181 v0.34.2

- CHANGELOG.md
- cmd/gaia/cmd/gaiad/main.go
Set default invariant check period to `0`.
/cc @alessio 
----
______
For Admin Use:
> Set default invariant check period to 0

- CHANGELOG.md
- client/lcd/swagger-ui/swagger.yaml
- cmd/gaia/cmd/gaiad/main.go
Release v0.34.3 into `master`.
----
______
For Admin Use:
> Release v0.34.3 (master)

- .pending/features/sdk/3850-Add-rewards-and-commission-to-distribution-tx-tags
- cmd/gaia/app/export.go
- docs/spec/distribution/06_tags.md
- x/distribution/handler.go
- x/distribution/keeper/delegation.go
- x/distribution/keeper/delegation_test.go
- x/distribution/keeper/hooks.go
- x/distribution/keeper/invariants.go
- x/distribution/keeper/keeper.go
- x/distribution/tags/tags.go
Add `rewards` and `commission` tags to their respective txs.
closes: #3850 
----
______
For Admin Use:
> Add rewards and commission tags

- .github/PULL_REQUEST_TEMPLATE.md
- contrib/devtools/clog/README.md
> Change `sdkch` to `clog` in doc.

- client/utils/utils_test.go
Prep work for moving gaia out of the sdk repository.
______
For Admin Use:
> Remove client/utils dep on gaia

- .circleci/config.yml
- .pending/improvements/gaia/4261-Upgrade-toolcha
- README.md
- docs/cosmos-hub/installation.md
- docs/translations/cn/cosmos-hub/installation.md
- scripts/install/install_sdk_arm.sh
- scripts/install/install_sdk_bsd.sh
- scripts/install/install_sdk_ubuntu.sh
> Upgrade Go to 1.12.4

- .pending/improvements/gaiarest/2007-Return-200-status-code-on-empty-results
- CHANGELOG.md
- client/keys/add.go
- client/lcd/lcd_test.go
- cmd/gaia/app/export.go
- cmd/gaia/cli_test/cli_test.go
- cmd/gaia/cli_test/test_helpers.go
- docs/spec/distribution/06_tags.md
- x/auth/client/rest/query.go
- x/bank/client/cli/sendtx.go
- x/distribution/handler.go
- x/distribution/keeper/delegation.go
- x/distribution/keeper/delegation_test.go
- x/distribution/keeper/hooks.go
- x/distribution/keeper/invariants.go
- x/distribution/keeper/keeper.go
- x/distribution/tags/tags.go
- x/slashing/client/rest/query.go
- Cherry picked PRs from https://github.com/cosmos/cosmos-sdk/pulls?utf8=%E2%9C%93&q=is%3Apr+label%3Anext-minor-release+
- Updated CHANGELOG
- Removed pending log files
----
______
For Admin Use:
> Release v0.34.4: RC1

- CONTRIBUTING.md
> Update Contribution Docs

- CONTRIBUTING.md
CC @alexanderbez 
______
For Admin Use:
> R4R Contributing doc update

- .pending/improvements/tendermint/4290-Upgrade-tenderm
- go.mod
- go.sum
> Upgrade iavl v0.12.2

- CHANGELOG.md
> Add changelog back to master for v0.34.4

- client/context/context.go
> NodeURI and Client should be nil'd in generate-only mode

- x/gov/client/cli/tx.go
Resolve test_cli failure
______
For Admin Use:
> Fix deposit command

- server/util.go
closes: https://github.com/cosmos/cosmos-sdk/issues/4323
______
For Admin Use:
> server: run cleanupFunc before Exit

- x/auth/client/cli/sign.go
close: #4319
______
For Admin Use:
> Flag account and sequence should not be set when offline was not set.

- docs/clients/service-providers.md
- docs/cosmos-hub/gaiacli.md
- docs/translations/cn/clients/service-providers.md
- docs/translations/cn/cn-translation-progress.md
- docs/translations/cn/cosmos-hub/gaiacli.md
- docs/translations/cn/cosmos-hub/installation.md
> Align cn-doc to 7558f760 (2019-05-13) and fix some typo of en-doc.

- docs/.vuepress/config.js
- docs/cosmos-hub/hd-wallets.md
- docs/cosmos-hub/ledger.md
Intended to satisfy the spec for ["3rd Party Documentation" required by Ledger](https://github.com/cosmos/cosmos-sdk/compare/ledger-tutorial?expand=1)
- [ x] Linked to github-issue with discussion and accepted design OR link to spec that describes this work.
______
For Admin Use:
> docs/cosmos-hub/ledger.md Add full ledger tutorial

- .pending/breaking/sdk/4342-https-github-co
- go.mod
- go.sum
> Upgrade to go-amino v0.15.0

- .circleci/config.yml
- cmd/gaia/contrib/runsim/main.go
> set runsim's default maxprocs to match system's GOMAXPROCS

- .pending/bugfixes/gaiacli/4345-Improved-NanoX-detection
- go.mod
- go.sum
There have been reports of Nano X detection issues in gaiacli.
This PR fixes the problem by upgrading upstream dependencies.
Related PRs:
https://github.com/cosmos/ledger-cosmos-go/pull/8
https://github.com/cosmos/ledger-go/pull/2
______
For Admin Use:
> Updating upstream dependencies

- baseapp/baseapp.go
- cmd/gaia/cli_test/cli_test.go
- crypto/encode_test.go
- crypto/keys/hd/hdpath_test.go
- x/auth/client/cli/sign.go
I don't think this merits a CL entry 
REF https://github.com/cosmos/cosmos-sdk/issues/4267#issuecomment-493183347
______
For Admin Use:
> R4R: report card minor fixes

- .pending/breaking/sdk/4351-AddGenesisAccou
- cmd/gaia/cmd/gaiad/main.go
- x/auth/genaccounts/client/cli/genesis_accts.go
- x/genutil/client/cli/collect.go
- x/genutil/client/cli/init.go
- x/genutil/client/cli/init_test.go
This is an alternative patch to what is proposed in #4348
______
For Admin Use:
> R4R: remove x/ dependency on cmd/gaia

- docs/clients/lite/readme.md
- docs/clients/lite/specification.md
- docs/clients/service-providers.md
- docs/cosmos-hub/validators/validator-faq.md
- docs/intro/ocap.md
- docs/modules/README.md
- docs/spec/README.md
- docs/spec/distribution/README.md
- docs/spec/mint/README.md
Fixed broken links, spelling and added documentation in places.
- [ n/a ] Linked to github-issue with discussion and accepted design OR link to spec that describes this work.  -Dosumnetion fix
- [ x ] Updated relevant documentation (`docs/`)
- [ x ] rereviewed `Files changed` in the github PR explorer
______
For Admin Use:
>  Documentation Fixes

- client/keys/utils.go
- go.mod
- go.sum
> improve key table format

- client/context/context.go
closes: #4350
----
______
For Admin Use:
> Update default verifier path

- server/util.go
- version/command.go
- version/version.go
- x/auth/client/cli/multisign.go
- x/distribution/client/cli/query.go
- x/distribution/client/cli/tx.go
- x/gov/client/cli/query.go
- x/gov/client/cli/tx.go
- x/params/client/cli/tx.go
- x/staking/client/cli/query.go
- x/staking/client/cli/tx.go
replaces: #4361
closes: #4315
credit: @rigelrozanski 
----
______
For Admin Use:
> Use Build's Client/Server Name

- .pending/breaking/sdk/4104-Rename-gaiad-to
> Add missing pending log entry from gaia split

- .circleci/config.yml
> Remove reproducible_builds and macos_ci jobs from circleci config

- .pending/improvements/sdk/4379-close-db-write-
- store/rootmulti/store.go
db write batch should be closed.
______
For Admin Use:
> close db write batch after use

- simapp/sim_test.go
- x/auth/genaccounts/client/cli/genesis_accts.go
- x/auth/genaccounts/export.go
- x/auth/genaccounts/genesis_account.go
- x/auth/genaccounts/genesis_state.go
- x/auth/genaccounts/genesis_state_test.go
- x/auth/genaccounts/init.go
- x/auth/genaccounts/module.go
Change the internal type of the `x/auth/genaccounts` sub module `GenesisState`. This will allow _top level_ 100% backwards compatibility with the current mainnet (v0.34.x) genesis state.
closes: #4392
/cc @rigelrozanski @npinto 
----
______
For Admin Use:
> Refactor genaccounts genesis state

- x/auth/test_utils.go
- x/bank/keeper_test.go
- x/distribution/keeper/querier_test.go
- x/distribution/keeper/test_common.go
- x/gov/test_common.go
- x/slashing/app_test.go
- x/slashing/test_common.go
- x/staking/app_test.go
- x/supply/keeper/keeper_test.go
- x/supply/module.go
- x/supply/types/codec.go
> Fix all amino codec related panics for Fede

- docs/spec/SPEC-SPEC.md
- docs/spec/auth/07_params.md
- docs/spec/auth/README.md
- docs/spec/bank/05_params.md
- docs/spec/bank/README.md
- docs/spec/crisis/04_params.md
- docs/spec/crisis/README.md
- docs/spec/distribution/07_params.md
- docs/spec/distribution/README.md
- docs/spec/governance/06_params.md
- docs/spec/governance/README.md
- docs/spec/mint/04_params.md
- docs/spec/mint/README.md
- docs/spec/slashing/08_params.md
- docs/spec/slashing/README.md
- docs/spec/staking/07_params.md
- docs/spec/staking/README.md
With the advent of parameter change proposals in the next hub upgrade, I thought it'd be wise to have a consolidated section for parameters for each module that users can reference when making such proposals.
/cc @gamarin2 @mossid 
----
______
For Admin Use:
> Update Spec to include params

- CHANGELOG.md
- x/distribution/client/cli/tx.go
- x/distribution/client/cli/tx_test.go
Cherry picked non-breaking the following PRs which already exist on `master`:
- https://github.com/cosmos/cosmos-sdk/pull/4384
----
______
For Admin Use:
> Release v0.34.5 - RC2

- docs/intro/README.md
Spelling
______
For Admin Use:
> Fix Spelling on CosmosSDK Docs README.md

- CHANGELOG.md
> Update CHANGELOG from v0.34.6 Release

- x/staking/handler_test.go
- x/staking/keeper/delegation.go
- x/staking/keeper/delegation_test.go
> Port advisory patch to master

- CHANGELOG.md
- x/staking/keeper/delegation.go
Revert logic where `balance` is set to allow for proper gas consumption allowing nodes to sync from genesis.
closes: #4458
----
______
For Admin Use:
> Revert Gas Bug

- CHANGELOG.md
> Add CHANGELOG entry from v0.34.7

- x/staking/querier/querier.go
related: https://github.com/cosmos/cosmos-sdk/issues/2788
______
For Admin Use:
> refactor(querier): use err for return

- CHANGELOG.md
- x/staking/handler_test.go
- x/staking/keeper/delegation.go
Remove height conditional from the unbonding advisory patch. This will be the __only__ change in v0.35.0.
----
______
For Admin Use:
> Remove fork height patch

- types/address.go
ref: #4144 
PR #4300 was merged, and there are too many conflict when doing `rebase master`.
So I create a new PR to add go comment.
@alessio @jackzampolin 
______
For Admin Use:
> Add go comment for user defined address.

- docs/.vuepress/config.js
> Fix docs build

- .pending/bugfixes/sdk/4493-Fix-validator-o
- x/distribution/client/cli/query.go
closes: #4493
----
______
For Admin Use:
> Fix validator-outstanding-rewards command

- server/mock/tx.go
Remove unnecessary auth dependency from the server package.
Work carried out in the context of #4488
______
For Admin Use:
> Remove unused code in server/mock

- x/distribution/keeper/delegation.go
Previous patch inadvertently used `Equal` instead of `LTE` when comparing compounded final stake to single computation final stake.
----
______
For Admin Use:
> Allocate Rewards Calculation Patch

- x/staking/types/validator.go
- x/staking/types/validator_test.go
Closes: #4508
______
For Admin Use:
> Fix YAML encoding of staking.Validator

- .pending/breaking/sdk/4525-Remove---cors-f
- client/alias.go
- client/flags/flags.go
> Remove CORS flag, it's gone.

- x/auth/ante_test.go
Closes: #4528
______
For Admin Use:
> Test zero fee scenario

- client/context/query.go
- client/rpc/root.go
- client/utils/utils.go
- client/utils/utils_test.go
- x/auth/client/rest/query.go
> Minor Cleanup

- .pending/breaking/sdk/4536-The-auth-accoun
- x/auth/client/rest/query.go
> Add account JSON tag to AccountWithHeight

- .pending/improvements/sdk/Remove---print-respo
- client/alias.go
- client/context/context.go
- client/flags/flags.go
This flag isn't used anywhere and probably hasn't for quite some time.
----
______
For Admin Use:
> Remove print response flag

- .pending/bugfixes/sdk/4619-Close-iterators
- x/staking/keeper/validator.go
closes: #4619
----
______
For Admin Use:
> Close Staking Iterators

- simapp/utils_test.go
- x/distribution/alias.go
> Fix master Build

- .pending/breaking/sdk/refactor-bank-keeper
- x/bank/internal/keeper/keeper.go
> Refactor bank keeper by removing private funcs

- contrib/runsim/main.go
- contrib/runsim/notification.go
- go.mod
- go.sum
> R4R: push runsim logs to S3

- types/events.go
> Sort events by type

- x/supply/alias.go
- x/supply/module.go
> fix supply NewQuerierHandler

- .pending/improvements/sdk/4676-expose-simapp-f
- simapp/sim_test.go
- simapp/utils.go
- simapp/utils_test.go
> Expose simapp genState generators and utils

- simapp/sim_test.go
- simapp/utils.go
- simapp/utils_test.go
- x/staking/alias.go
- x/staking/types/keys.go
> Export sim funcs  pt2

- simapp/sim_test.go
- simapp/utils.go
- types/invariant.go
- x/bank/internal/keeper/invariants.go
- x/crisis/handler.go
- x/crisis/handler_test.go
- x/crisis/internal/keeper/keeper.go
- x/distribution/keeper/invariants.go
- x/gov/invariants.go
- x/simulation/simulate.go
- x/simulation/util.go
- x/staking/keeper/invariants.go
- x/supply/internal/keeper/invariants.go
> collect all invariants for a block before stopping

- .pending/improvements/tendermint/Upgrade-tendermint-i
- go.mod
- go.sum
- store/iavl/store.go
- store/rootmulti/proof_test.go
- store/rootmulti/store.go
> update tendermint/iavl to v0.12.3

- go.mod
- go.sum
- Upgrade to tendermint version `woohoo`
______
For Admin Use:
> Upgrade tendermint version

- docs/spec/supply/01_concepts.md
- simapp/app.go
- x/distribution/keeper/test_common.go
- x/mint/internal/keeper/test_common.go
- x/slashing/app_test.go
- x/slashing/test_common.go
- x/staking/app_test.go
- x/staking/keeper/test_common.go
- x/supply/alias.go
- x/supply/internal/keeper/bank_test.go
- x/supply/internal/keeper/test_common.go
- x/supply/internal/types/account_test.go
- x/supply/internal/types/permissions.go
- x/supply/internal/types/permissions_test.go
fixes #4702 
______
For Admin Use:
> Remove Basic Permission

- docs/architecture/adr-template.md
- This adr template comes from bez's commit last july
______
For Admin Use:
> Update ADR template

- docs/translations/kr/intro/sdk-app-architecture.md
ABCI 부분이 빠진 것 같아서 추가적으로 번역했습니다. 
19.07.21 새벽 1시 2019 HACKATOM 중 - CCCCCx5 팀 -
______
For Admin Use:
> ABCI Part Additional Translation

- .pending/bugfixes/_Sort-state-JSON-dur
- server/export.go
- x/genutil/client/cli/init.go
Supersedes #4294. We will need to get this in for v0.36.0
-----
______
For Admin Use:
> Sort genesis JSON before Output

- x/genutil/client/cli/migrate.go
> Sort JSON during migration

- types/coin.go
addresses #4746
______
For Admin Use:
> fix typo in panic message

- x/staking/types/expected_keepers.go
- x/supply/genesis.go
fixes #4778 
______
For Admin Use:
> Update staking/supply to use exported account interface

- simapp/utils.go
- x/nft/client/cli/tx.go
- x/nft/client/rest/tx.go
- x/nft/exported/nft.go
- x/nft/genesis_test.go
- x/nft/handler.go
- x/nft/handler_test.go
- x/nft/internal/keeper/collection_test.go
- x/nft/internal/keeper/invariants.go
- x/nft/internal/keeper/nft_test.go
- x/nft/internal/keeper/owners_test.go
- x/nft/internal/keeper/querier_test.go
- x/nft/internal/keeper/test_common.go
- x/nft/internal/types/collection_test.go
- x/nft/internal/types/msgs.go
- x/nft/internal/types/msgs_test.go
- x/nft/internal/types/nft.go
- x/nft/internal/types/nft_test.go
- x/nft/internal/types/test_common.go
- x/nft/simulation.go
- x/nft/test_common.go
> Minimal nft without name, description or image

- .circleci/config.yml
It seems the `sed` command in `upload_coverage` is not working correctly causing us to not actually ignore the files we want to ignore.
Disclaimer: I'm not a bash expert, so please don't judge too harshly 🙏 
closes #4820
----
______
For Admin Use:
> Fix upload_coverage CI Job

- docs/DOCS_README.md
- docs/interfaces/service-providers.md
- docs/spec/README.md
- docs/spec/slashing/04_begin_block.md
- docs/translations/cn/clients/service-providers.md
- docs/translations/cn/intro/ocap.md
- docs/translations/kr/clients/service-providers.md
- docs/translations/kr/modules/README.md
> R4R Fix a bunch of broken/incorrect links

- docs/.vuepress/config.js
> Edit link in docs should point to the master branch

- .pending/bugfixes/modules/_prevent-community-s
- x/distribution/keeper/proposal_handler.go
> Prevent community spend proposal from transferring funds to a ModuleAcc

- baseapp/baseapp.go
- client/context/query.go
- client/rpc/block.go
- client/rpc/status.go
- tests/util.go
- types/rest/rest.go
- x/auth/client/rest/broadcast.go
- x/auth/client/rest/encode.go
- x/auth/client/rest/query.go
- x/bank/client/rest/query.go
- x/genutil/client/rest/query.go
- x/staking/client/rest/query.go
Changes needed to make Gaia build/run correctly. Notable changes:
- Replace `PostProcessResponse` with `PostProcessResponseBare` in request handlers where it doesn't make sense to include/inject a height
- Fix `ParseQueryHeightOrReturnBadRequest`
- Fix height injection; allow BaseApp to inject height rather that the CLIContext
closes: #4841
----
______
For Admin Use:
> Various Updates for Gaia

- .pending/features/_4843-Add-RegisterEv
- codec/codec.go
closes: #4843
----
______
For Admin Use:
> Add RegisterEvidences

- simapp/utils.go
- x/genutil/legacy/v036/migrate.go
- x/supply/genesis.go
- x/supply/internal/types/genesis.go
- x/supply/legacy/v0_36/types.go
> Cleanup Supply Genesis State

- simapp/app.go
- simapp/sim_test.go
- x/crisis/internal/keeper/keeper.go
- x/crisis/internal/keeper/keeper_test.go
- x/crisis/module.go
> v0.36.0-rc4 🍒 Picks

- docs/.vuepress/config.js
> Fix docs build for 0.36

- docs/translations/kr/README.md
Fix broken gaia links in translated READEME.md
Signed-off-by: Hyung-Kyu Choi <hyungkyu.choi@gmail.com>
______
For Admin Use:
> Fix broken gaia links in translated READEME.md

- docs/spec/slashing/01_concepts.md
- docs/spec/slashing/02_state.md
- docs/spec/slashing/04_begin_block.md
This PR is not a complete refactor and cleanup of the existing slashing specs, but rather focuses on:
- Cleaning up and fixing markdown
- Usage of correct parameter names
- Helping clarifying certain concepts focusing on liveness 
ref: https://github.com/cosmos/cosmos-sdk/issues/4628
----
______
For Admin Use:
> Update Slashing Spec

- docs/architecture/README.md
- docs/architecture/adr-006-secret-store-replacement.md
ADR for the proposed change in [#4754](https://github.com/cosmos/cosmos-sdk/pull/4754)
@jessysaurusrex could you please give your views on whether the https://github.com/99designs/keyring should be audited before this change is adopted.
______
For Admin Use:
> [ADR-6] - secret-store-replacement.md

- CHANGELOG.md
- simapp/sim_test.go
- simapp/state.go
- simapp/utils.go
- x/simulation/config.go
- x/simulation/simulate.go
> simulation config

- docs/basics/tx-lifecycle.md
- cleanup markdown format
- improve some concepts
----
______
For Admin Use:
> Tx Lifecycle Doc Cleanup

- CHANGELOG.md
> Update CHANGELOG  - v0.37.0

- x/staking/keeper/validator_test.go
PR for #4925 
- [+] Linked to github-issue with discussion and accepted design OR link to spec that describes this work.
- [n/a] Wrote tests
- [n/a] Updated relevant documentation (`docs/`)
- [n/a] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [n/a] Re-reviewed `Files changed` in the github PR explorer
______
For Admin Use:
> Fix Validator tests

- baseapp/baseapp.go
Remove unnecessary nil check, because a nil slice has 0 length.
______
For Admin Use:
> Remove unnecessary nil check

- x/staking/keeper/validator.go
minor update to reduce code duplication
> Reuse ValidatorsPowerStoreIterator

- x/genutil/client/cli/collect.go
- x/genutil/client/cli/gentx.go
- x/genutil/client/cli/init.go
- x/genutil/client/cli/migrate.go
closes: #4962 
----
- [+] Linked to github-issue with discussion and accepted design OR link to spec that describes this work.
______
For Admin Use:
> Improve error reporting in genutil clis

- CHANGELOG.md
Addresses proposal [here](https://github.com/cosmos/cosmos-sdk/issues/4958#issuecomment-525524517).
Splits BREAKING CHANGES into:
- Client Breaking (breaks cli/REST routes)
- API Breaking (breaks core-sdk function signatures)
- State Machine Breaking
______
For Admin Use:
> Split Breaking Changes into Specific Subsections

- .circleci/config.yml
- README.md
- go.mod
- go.sum
> Go 1.13 Upgrade

- docs/architecture/README.MD
- docs/architecture/adr-011-generalize-genesis-accounts.md
A proposed ADR to allow custom account types to work easily with genesis.
Let me know if there are problems with the ADR format or style.
______
For Admin Use:
> [ADR-11] - Generalize Genesis Accounts

- Makefile
- simapp/sim_test.go
- simapp/utils.go
- x/simulation/simulate.go
- x/simulation/util.go
closes #4964 
fixes #4631 
______
For Admin Use:
> remove redundant invariant simapp check

- Makefile
> Fix test_sim_multi_seed_long make target

- simapp/sim_test.go
- simapp/state.go
- simapp/utils.go
> Export sim CLI flags

- baseapp/abci.go
Resetting is no longer necessary and is actually a bug.
______
For Admin Use:
> Remove inter-block cache reset in init-chain

- client/lcd/swagger-ui/swagger.yaml
> add where to find the event tags into the swagger

- x/auth/legacy/v0_38/migrate.go
- x/auth/legacy/v0_38/migrate_test.go
- x/auth/legacy/v0_38/types.go
- x/auth/types/account.go
- x/genutil/legacy/v0_38/migrate.go
Updated the genesis account migration to v0.38. Tested by running a local Gaia v2.0.0 network, migrating state, and finally restarting the network using the latest Gaia/SDK `master` commit. 
closes: #5046
---
______
For Admin Use:
> Fix Genesis Accounts Migration

- x/gov/client/rest/query.go
- x/gov/client/rest/tx.go
This is a follow on to https://github.com/cosmos/cosmos-sdk/pull/5038 which adds annotations for the routes in `/x/gov/client/rest`
> Swagger Auto Gen - Gov

- CHANGELOG.md
> Add changelog notes from v0.37.1

- contrib/devtools/Makefile
Update the tool targets to not pollute `go.{mod, sum}`.
We'll want to use the global install once it's implemented (ref: https://github.com/golang/go/issues/30515).
----
______
For Admin Use:
> Sanitize Tools Makefile

- x/bank/alias.go
- x/bank/internal/types/events.go
- x/crisis/alias.go
- x/crisis/internal/types/events.go
- x/distribution/types/events.go
- x/slashing/alias.go
- x/staking/types/events.go
> Expose/Alias Events (from internal pkgs)

- x/auth/client/cli/tx_sign.go
replaces: https://github.com/cosmos/cosmos-sdk/pull/5056
closes: #5053
credit: @wangkui0508
----
______
For Admin Use:
> Fix offline flag description

- go.mod
- go.sum
> Bump Tendermint version v0.32.5

- CHANGELOG.md
> Add v0.34.8 changelog section

- client/context/context.go
- client/context/verifier.go
- client/context/verifier_test.go
- x/ibc/04-channel/tests/types.go
Cherry-pick of https://github.com/cosmos/cosmos-sdk/pull/5136 that went into `master`.
----
______
For Admin Use:
> IBC Multi-Verifier Cherry Pick

- simapp/sim_test.go
- simapp/utils.go
Port of https://github.com/cosmos/cosmos-sdk/pull/5148 to the v0.37.x line.
----
______
For Admin Use:
> Use Genesis File Timestamp (v0.37.2)

- client/lcd/root.go
Closes #5151 
______
For Admin Use:
> Remove unused KeyBase (dead code)

- x/staking/types/msg.go
- x/staking/types/msg_test.go
solves #5112 
______
For Admin Use:
> Solves issue #5112.  implemented yaml marshaller in msg.go

- client/keys/migrate.go
- crypto/keys/keyring.go
- crypto/keys/keyring_test.go
> Handle New{,Test}Keyring errors

- CHANGELOG.md
- go.mod
- go.sum
> Release v0.34.9

- CHANGELOG.md
- go.mod
- go.sum
> Bump Tendermint version to v0.32.6

- CHANGELOG.md
> Include v0.34.9 in CHANGELOG

- CHANGELOG.md
- go.mod
- go.sum
Cherry pick https://github.com/cosmos/cosmos-sdk/pull/5175
----
______
For Admin Use:
> v0.37.2-RC2: cherry pick 5175

- x/bank/client/rest/query.go
- x/bank/client/rest/tx.go
- #5038 follow up for bank module
______
For Admin Use:
> Swagger Auto Gen - Bank  

- .golangci.yml
the bot does not contain deadline anymore only timeout since it is hardcoded into the bot
______
For Admin Use:
> Remove version from golangci

- docs/architecture/adr-006-secret-store-replacement.md
> Update ADR-006's progress

- x/ibc/03-connection/alias.go
- x/ibc/03-connection/keeper/querier.go
- x/ibc/05-port/keeper/keeper.go
- x/ibc/05-port/types/port.go
Update ICS 5 to use static port bindings (must happen in `app.go`).
______
For Admin Use:
> ICS 5 updates

- types/events.go
> Use existing struct

- CHANGELOG.md
> upgrading to ledger-cosmos-go v0.11.1

- docs/cn/clients/service-providers.md
> "auth/StdTx" -> "cosmos-sdk/StdTx"

- CHANGELOG.md
- go.mod
- go.sum
> v0.34.10-rc2: Bump Tendermint version to v0.31.11

- CHANGELOG.md
> add v0.34.10 changelog section

- CHANGELOG.md
- go.mod
- go.sum
> bump tendermint version to v0.32.7

- x/auth/ante/sigverify.go
> fix IncrementSequenceDecorator gas estimate

- CHANGELOG.md
> changelog: add v0.37.4 section

- docs/spec/README.md
this confused me for a second haha
> fix typo in link

- .circleci/config.yml
- Makefile
> add docs staging build

- docs/architecture/adr-006-secret-store-replacement.md
> Update ADR 006

- Makefile
Avoid `make test` prompting for password on dev machine.
______
For Admin Use:
> Run tests with passwordless keyring

- CHANGELOG.md
- x/auth/client/utils/tx.go
closes: #5303
credit @haasted 
----
______
For Admin Use:
> Fix Ignored Error During Tx Generate Only Mode

- x/ibc/02-client/client/cli/cli.go
- x/ibc/02-client/client/cli/query.go
- x/ibc/02-client/client/cli/tx.go
- x/ibc/02-client/client/rest/query.go
- x/ibc/02-client/client/utils/utils.go
- x/ibc/02-client/keeper/client_test.go
- x/ibc/03-connection/client/cli/cli.go
- x/ibc/03-connection/client/cli/query.go
- x/ibc/03-connection/client/cli/tx.go
- x/ibc/03-connection/client/rest/query.go
- x/ibc/03-connection/client/utils/utils.go
- x/ibc/04-channel/client/cli/cli.go
- x/ibc/04-channel/client/cli/query.go
- x/ibc/04-channel/client/cli/tx.go
- x/ibc/04-channel/client/rest/query.go
- x/ibc/04-channel/client/utils/utils.go
- x/ibc/04-channel/types/querier.go
- x/ibc/05-port/keeper/keeper_test.go
- x/ibc/20-transfer/client/cli/cli.go
- x/ibc/20-transfer/client/cli/query.go
- x/ibc/20-transfer/client/cli/tx.go
- x/ibc/20-transfer/client/rest/query.go
- x/ibc/20-transfer/client/utils/utils.go
- x/ibc/20-transfer/handler_test.go
- x/ibc/20-transfer/keeper/keeper_test.go
- x/ibc/20-transfer/keeper/relay_test.go
- x/ibc/20-transfer/types/msgs_test.go
Custom queries (i.e via `sdk.Queriers`) return empty proofs. This PR replaces them for direct store queries (i.e `store/<storeName>/key`).
NOTE: This is a patch for #5317 
______
For Admin Use:
> fix ibc proofs

- x/simulation/rand_util.go
- x/simulation/rand_util_test.go
Closes: #5372
______
______
For admin use:
> [x/simulation] RandSubsetCoins() should return sorted coinset

- types/coin.go
- types/dec_coin.go
- types/denom.go
- x/auth/ante/ante_test.go
- x/auth/simulation/genesis.go
- x/auth/types/params.go
- x/bank/internal/types/params.go
- x/crisis/internal/types/params.go
- x/distribution/keeper/params.go
- x/evidence/internal/types/params.go
- x/gov/types/params.go
- x/mint/alias.go
- x/mint/internal/types/genesis.go
- x/mint/internal/types/params.go
- x/params/keeper_test.go
- x/params/proposal_handler_test.go
- x/params/types/proposal_test.go
- x/slashing/handler_test.go
- x/slashing/internal/types/params.go
- x/staking/handler_test.go
- x/staking/types/params.go
Part II of https://github.com/cosmos/cosmos-sdk/pull/5359.
Reviewer, please review all `func validate*(i interface{}) error` functions.
______
______
For admin use:
> Params Validation II

- CONTRIBUTING.md
Edit typos and punctiations to clarify the meaning.
______
______
For admin use:
> Fix typos in the CONTRIBUTING.md.

- x/ibc/02-client/client/cli/query.go
- x/ibc/02-client/client/rest/query.go
- x/ibc/02-client/client/utils/utils.go
- x/ibc/02-client/keeper/keeper.go
- x/ibc/02-client/keeper/querier.go
- x/ibc/02-client/types/querier.go
Closes: #5369
Implement querying methods for Committers in both CLI and REST, currently only supports tendermint committers
______
______
For admin use:
> Implement Query Committer methods in ICS-02

- x/simulation/account_test.go
- x/simulation/rand_util_test.go
> Bump x/simulation coverage

- CHANGELOG.md
- types/uint.go
- types/uint_test.go
Add Mod method to Uint
Add RelativePower function for calculating x^y = z for uints, where x and y are scaled by some base, b. 
______
______
For admin use:
> Add mod, exponentiation for uint

- x/distribution/client/cli/query.go
- x/distribution/client/cli/tx.go
Closes: https://github.com/cosmos/cosmos-sdk/issues/5422
Fixed examples as reported in the issue 
______
______
For admin use:
> Modified examples in distribution module

- x/ibc/02-client/client/cli/tx.go
- x/ibc/03-connection/client/cli/tx.go
- x/ibc/03-connection/client/utils/utils.go
- x/ibc/04-channel/client/cli/tx.go
Closes: #5316
______
______
For admin use:
> fix CLI JSON param unmarshaling

- x/ibc/02-client/exported/exported.go
- x/ibc/02-client/exported/exported_test.go
- x/ibc/02-client/handler.go
- x/ibc/02-client/types/msgs.go
- x/ibc/03-connection/alias.go
- x/ibc/03-connection/keeper/handshake.go
- x/ibc/03-connection/keeper/handshake_test.go
- x/ibc/03-connection/keeper/keeper_test.go
- x/ibc/03-connection/types/connection.go
- x/ibc/03-connection/types/connection_test.go
- x/ibc/04-channel/alias.go
- x/ibc/04-channel/keeper/handshake.go
- x/ibc/04-channel/keeper/handshake_test.go
- x/ibc/04-channel/keeper/packet.go
- x/ibc/04-channel/types/channel.go
- x/ibc/04-channel/types/channel_test.go
Fixes informational finding from security audits
TODO: 
______
______
For admin use:
> Fix inconsistent string lookup functions

- docs/.vuepress/config.js
Closes: #XXX
The sidebar should link to the rendered tutorials, not the repo
______
______
For admin use:
> Update docs config.js

- types/result.go
Remove the deprecated `Events` from the `TxResponse` type in preparation for the 0.38 release.
______
______
For admin use:
> Remove (Deprecated) Events from TxResponse

- types/uint.go
- types/uint_test.go
Closes: N/A
Hey all! This PR adds some convenience methods to `sdk.Uint` that we used in the DEX demo. At @alessio's suggestion, I've included them in this PR. The methods are:
- `Incr()` : Increments the `Uint` by one.
- `Decr()`: Decrements the `Uint` by one.
- `Cmp()`: Compares two `Uints`, returning 0 if they are equal, 1 if a > b, and -1 if a < b.
I've found these to be super useful when using `sdk.Uint` instances as identifiers in SDK stores.
______
______
For admin use:
> Add convenience Incr() and Decr() methods to Uint

- CHANGELOG.md
> v0.37.5 Changelog Entry

- x/staking/keeper/val_state_change.go
Closes: #XXX
minor refactor and remove excessive comments
______
______
For admin use:
> use build-in iterator function

- go.mod
- go.sum
The original `replace` replaced `go-keychain` with a commit that I believe was too new for the version of keyring on macOS. Using commit as recommended by keyring repo.
______
______
For admin use:
> Fix go-keychain Dep

- client/rpc/validators.go
Fix pagination bug introduced by upgrade to 0.33.
______
______
For admin use:
> Fix /validatorsets REST Pagination

- CHANGELOG.md
- go.mod
- go.sum
Cherry pick commits:
- #5515
______
______
For admin use:
> v0.37.6 rc1

- CHANGELOG.md
Closes: #XXX
______
______
For admin use:
> v0.37.6 CHANGELOG

- x/auth/legacy/v0_38/migrate.go
- x/auth/legacy/v0_38/migrate_test.go
- x/auth/legacy/v0_38/types.go
- x/auth/types/account_test.go
- x/distribution/legacy/v0_38/types.go
- x/genutil/legacy/v0_38/migrate.go
Fix genesis state migration bugs found from v0.38.0-rc1.
TODO:
______
______
For admin use:
> v0.38 Migration Fixes

- CHANGELOG.md
> Add v0.38.0 changelog

- docs/building-modules/handler.md
- docs/core/events.md
Add to the docs of events and handler to set a new `EventManager` to the `Context`.
If not done, the event manager contains events from previous messages of the same block/transaction and returns events from other messages when calling:
```go
return sdk.Result{
Data:   GetProposalIDBytes(proposal.ProposalID),
Events: ctx.EventManager().Events(),
}
```
Based on existing code from the [Scavenge tuto](https://tutorials.cosmos.network/scavenge/tutorial/06-handler.html).
______
+ No issue is related.
+ It's only a documentation update
+ It's only a documentation update
+ It's only a documentation update
______
For admin use:
> Add to the docs of events and handler to set a new EventManager to the Context

- docs/cn/intro/README.md
______
- [- ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
______
For admin use:
> fix(docs): sdk tutorials link

- buf.yaml
> Fix Proto Linting

- x/bank/alias.go
> Add Missing Bank Genesis Aliases

- docs/using-the-sdk/quick-start.md
- x/gov/spec/01_concepts.md
- x/gov/spec/02_state.md
- x/gov/spec/03_messages.md
- x/gov/spec/04_events.md
Closes: #XXX
______
______
For admin use:
> docs: minor doc formatting & touchup of the scaffold section

- docs/basics/tx-lifecycle.md
Closes: #5623 
______
______
For admin use:
> docs: sentence about gas is not correct currently

- CHANGELOG.md
- docs/spec/bank/04_events.md
- docs/spec/staking/06_events.md
- x/bank/internal/keeper/keeper.go
- x/bank/internal/keeper/keeper_test.go
- x/gov/endblocker.go
- x/staking/handler.go
- x/staking/keeper/delegation.go
- x/staking/keeper/val_state_change.go
closes: #5573
______
______
For admin use:
> v0.37.7-RC1

- CHANGELOG.md
> Add v0.37.7 changelog entry

- .codecov.yml
Closes: #XXX
______
______
For admin use:
> fix codecov

- go.mod
- go.sum
Mac OS users will be presented with a warning at compile
time. No actual problems are resolved by keeping the replace
statement in place though.
______
______
For admin use:
> Remove replace statement

- go.mod
- go.sum
- x/auth/client/cli/query.go
- x/auth/client/query.go
- x/auth/client/rest/query.go
- x/gov/client/utils/query.go
- x/gov/client/utils/query_test.go
- x/staking/client/rest/utils.go
Closes: #XXX
______
______
For admin use:
> dep: bump tendermint version to 0.33.1

- server/export.go
- server/util.go
- x/distribution/types/params_test.go
- x/genutil/client/cli/init.go
- x/slashing/app_test.go
- x/staking/app_test.go
Closes: #5651
______
______
For admin use:
> Squash various linter warnings

- types/rest/rest_test.go
> Fix TestParseHTTPArgs

- docs/intro/overview.md
Closes: #XXX
______
______
For admin use:
> Replace Lino with Kava in docs

- x/auth/types/account_retriever.go
> Fix GetAccountWithHeight

- x/ibc/04-channel/keeper/keeper_test.go
- x/ibc/20-transfer/client/cli/tx.go
- x/ibc/20-transfer/client/rest/rest.go
- x/ibc/20-transfer/client/rest/tx.go
- x/ibc/20-transfer/handler.go
- x/ibc/20-transfer/handler_test.go
- x/ibc/20-transfer/keeper/relay.go
- x/ibc/20-transfer/keeper/relay_test.go
- x/ibc/20-transfer/types/msgs.go
- x/ibc/20-transfer/types/msgs_test.go
Closes: #5471 
______
______
For admin use:
> Fix Timeout bug

- x/auth/types/txbuilder.go
Closes: #XXX
______
______
For admin use:
> Get Uin64 directly instead of Int64

- docs/building-modules/README.md
- docs/building-modules/errors.md
- docs/building-modules/structure.md
Add a doc to module building docs describing error usage and definition guidelines.
Ref: https://github.com/cosmos/cosmos-sdk/issues/5662#issuecomment-588126804
/cc @marbar3778 
______
______
For admin use:
> Errors Guidelines Doc

- Makefile
- client/cmd_test.go
- codec/amino_codec_test.go
- codec/hybrid_codec_test.go
- codec/proto_codec_test.go
- types/address_bench_test.go
- types/decimal_test.go
- x/bank/client/rest/rest.go
- x/bank/types/key_test.go
- x/params/keeper/common_test.go
- x/params/keeper/keeper_test.go
- x/params/types/table_test.go
- x/staking/types/commission.go
- x/staking/types/delegation.go
- x/staking/types/params.go
- x/upgrade/client/cli/query.go
- x/upgrade/keeper/keeper.go
- x/upgrade/keeper/querier.go
Forked from #5705
______
______
For admin use:
> Exclude proto files from format

- .mergify.yml
Closes: #XXX
______
______
For admin use:
> fix config file

- version/command.go
- version/version_test.go
> Increase code coverage of version up to 100%

- .github/CODEOWNERS
[ci skip]
______
______
For admin use:
> Update CODEOWNERS as per @jaekwon's directives

- types/module/module_test.go
> Attempt to fix flaky tests

- x/slashing/handler_test.go
- x/staking/keeper/delegation.go
- x/staking/keeper/delegation_test.go
- x/staking/keeper/val_state_change.go
> Remove redundant staking APIs

- x/auth/client/cli/query.go
> Fix x/auth GET commands

- x/ibc/02-client/keeper/keeper.go
- x/ibc/03-connection/keeper/keeper_test.go
Ref https://github.com/cosmos/cosmos-sdk/issues/5762
> Debug timestamp issues

- x/ibc/20-transfer/types/msgs.go
Closes: #XXX
______
______
For admin use:
> Fix TransferMsg routing

- CHANGELOG.md
> Changelog v0.37.8

- go.mod
- go.sum
- x/distribution/spec/07_params.md
Update the `x/distribution` parameter document to stipulate the value restrictions.
ref: https://github.com/cosmos/cosmos-sdk/issues/5808
/cc @gavinly 
______
______
For admin use:
> Update params doc with restrictions

- client/input/input.go
- crypto/keys/keyring.go
- crypto/keys/keyring_test.go
- crypto/keys/mintkey/mintkey_test.go
- crypto/keys/types_test.go
- store/reexport.go
- types/module/module_test.go
- types/rest/rest_test.go
- types/staking_test.go
- version/version_test.go
- x/auth/ante/basic.go
> Fix various linter warnings

- go.sum
- server/pruning.go
- store/transient/store_test.go
- tests/mocks/account_retriever.go
- tests/mocks/tendermint_tm_db_DB.go
- tests/mocks/types_handler.go
- tests/mocks/types_invariant.go
- tests/mocks/types_module_module.go
- tests/mocks/types_router.go
- x/distribution/keeper/delegation_test.go
- x/distribution/keeper/querier_test.go
- x/distribution/module_test.go
- x/distribution/proposal_handler_test.go
- x/slashing/abci_test.go
- x/slashing/keeper/test_common.go
- x/staking/keeper/keeper_test.go
- x/staking/keeper/slash_test.go
> run go mod tidy && make format

- Makefile
- tests/mocks/account_retriever.go
- tests/mocks/tendermint_tm_db_DB.go
- tests/mocks/types_handler.go
- tests/mocks/types_invariant.go
- tests/mocks/types_module_module.go
- tests/mocks/types_router.go
Follow-up of #5847
______
______
For admin use:
> regenerate mocks, don't format autogenered files on make format

- client/keys/add.go
- client/keys/mnemonic.go
- go.mod
- go.sum
Thanks @fedekunze for pointing this out.
______
______
For admin use:
> Use cosmos' fork of github.com/bartekn/go-bip39

- CHANGELOG.md
> Add v0.38.2 Changelog

- docs/architecture/adr-003-dynamic-capability-store.md
For updates to the IBC spec as per https://github.com/cosmos/ics/pull/400.
Adds the ability for modules to release capabilities which they had previously claimed.
> Update ADR 3: add ReleaseCapability

- x/capability/alias.go
- x/capability/keeper/keeper.go
- x/capability/keeper/keeper_test.go
- x/capability/types/errors.go
- x/capability/types/types.go
- x/capability/types/types_test.go
ref: https://github.com/cosmos/cosmos-sdk/pull/5873.
/cc @cwgoes @AdityaSripal 
______
______
For admin use:
> x/capability: ReleaseCapability

- x/auth/client/tx.go
- x/auth/client/tx_test.go
> Fix parseQueryResponse

- x/ibc/04-channel/keeper/packet.go
- x/ibc/04-channel/keeper/timeout.go
- x/ibc/04-channel/types/events.go
Add events for acknowledgements, timeout & acknowledgement processing, and packet cleanup.
Closes https://github.com/cosmos/cosmos-sdk/issues/5660
> Add additional events to x/ibc

- client/tx/tx.go
Handle and return a non-nil error on `tx.SetMsgs`.
closes: #5934
______
______
For admin use:
> Handle and return error on tx.SetMsgs

- client/flags/flags.go
Closes: #XXX
______
______
For admin use:
> Bind Keyring Flag

- x/ibc/02-client/keeper/client_test.go
- x/ibc/02-client/keeper/keeper_test.go
- x/ibc/03-connection/alias.go
- x/ibc/03-connection/keeper/handshake_test.go
- x/ibc/03-connection/keeper/keeper.go
- x/ibc/03-connection/keeper/keeper_test.go
- x/ibc/03-connection/keeper/verify_test.go
- x/ibc/04-channel/alias.go
- x/ibc/04-channel/keeper/handshake_test.go
- x/ibc/04-channel/keeper/keeper_test.go
- x/ibc/04-channel/keeper/packet_test.go
- x/ibc/04-channel/keeper/timeout.go
- x/ibc/04-channel/keeper/timeout_test.go
- x/ibc/20-transfer/handler_test.go
- x/ibc/20-transfer/keeper/keeper.go
- x/ibc/20-transfer/keeper/keeper_test.go
- x/ibc/20-transfer/keeper/relay_test.go
- x/ibc/23-commitment/types/merkle_test.go
- x/ibc/ante/ante_test.go
Closes: #XXX
______
______
For admin use:
> Fix ibc-alpha lint

- CHANGELOG.md
- x/ibc/spec/README.md
Add `CHANGELOG.md` entries for the ibc module and updates to the spec.
______
______
For admin use:
> x/ibc: changelog

- x/bank/client/cli/tx.go
- x/crisis/client/cli/tx.go
- x/distribution/client/cli/tx.go
- x/slashing/client/cli/tx.go
- x/staking/client/cli/tx.go
This PR has fix for cliCtx in tx cli of crisis, distribution, staking and slashing modules. Also added ValidateBasic where it  was missing on cli side.
Reference: 1) https://github.com/cosmos/cosmos-sdk/pull/5941#discussion_r405879886
2) https://github.com/cosmos/cosmos-sdk/pull/5941#discussion_r405095795
______
______
For admin use:
> Fixed cliCtx in tx cli

- CHANGELOG.md
- go.mod
- go.sum
> v0.37.9 RC1

- CHANGELOG.md
> 0.37.9 Changelog

- CHANGELOG.md
- go.mod
- go.sum
> v0.38.3 RC1

- CHANGELOG.md
- go.mod
- go.sum
> v0.38.3 Release (#5973)

- CHANGELOG.md
> v0.38.3 changelog

- x/ibc/02-client/client/utils/utils.go
- x/ibc/02-client/keeper/keeper.go
- x/ibc/02-client/types/querier.go
- x/ibc/03-connection/keeper/handshake_test.go
- x/ibc/03-connection/keeper/keeper_test.go
- x/ibc/03-connection/keeper/verify_test.go
- x/ibc/04-channel/keeper/keeper.go
- x/ibc/07-tendermint/types/client_state.go
- x/ibc/types/keys.go
Closes: #5502
Description
Creates prefix store with prefix of clientID for each client instance.
Fix inconsistencies described here: https://github.com/cosmos/ics/issues/387
Some key formats that still differ from spec:
`clients/{identifier}/clientState`
And all `04-channel` keys are prefixed as described below
______
______
For admin use:
> Fix Prefixes and Create Prefix Store for Clients

- docs/architecture/adr-003-dynamic-capability-store.md
Updates the ADR to reflect the latest design choices in the implementation
______
______
For admin use:
> Update 03-ADR to latest implementation

- x/ibc/02-client/client/cli/cli.go
Closes: #5994 
ready for review 
______
______
For admin use:
> add cmd validation to ibc query cli cmd

- docs/core/events.md
fix an error link
______
______
For admin use:
> [DOCS]: fix the error link

- x/ibc/20-transfer/keeper/keeper.go
> Fix issue with capabilities when receiving packet

- CHANGELOG.md
- client/cmd_test.go
- x/ibc/09-localhost/types/localhost_test.go
- x/simulation/params.go
- x/simulation/simulate.go
- x/staking/types/genesis.go
Reverts cosmos/cosmos-sdk#6002
> Revert "Add consensus params into Simulation"

- CHANGELOG.md
- client/context/context.go
- types/rest/rest_test.go
- x/distribution/client/common/common_test.go
Bugfix only release.
Closes: #5964
______
______
For admin use:
> Release v0.37.10

- CHANGELOG.md
- x/staking/client/cli/tx.go
> Release v0.37.11

- client/rpc/status.go
> client/rpc: fix panic on status command

- .github/workflows/sims.yml
Closes: #XXX
______
______
For admin use:
> run diff in each job

- x/ibc/04-channel/keeper/handshake.go
- x/ibc/05-port/keeper/keeper.go
- x/ibc/20-transfer/handler.go
Add missing logs for IBC interactions.
ref: #5660 
______
______
For admin use:
> x/ibc: add logs

- .gitignore
- Makefile
- contrib/devtools/Makefile
Don't reinstall proto tools unconditionally every time
one runs make.
On most Linux systems, /usr/local is writable by root only.
Allow users to customise installation directory by passing
PREFIX to make command line, e.g.:
$ make PREFIX=~/.local
______
______
For admin use:
> Makefiles: various improvements

- x/ibc/types/errors.go
ref: https://github.com/cosmos/cosmos-sdk/issues/6107
______
______
For admin use:
> Fix IBC Error Code Registration

- x/ibc/07-tendermint/types/header.go
Closes: #XXX
camel-case SignedHeader in a snake-case json output of relevant commands looks strange
______
______
For admin use:
> add anotation for json/yaml marshal ibc/tendermint/header type

- x/ibc/module.go
Closes: #6082
cc: @anilCSE @aaronc @sahith-narahari 
______
______
For admin use:
> ibc default genesis state

- x/ibc/03-connection/client/cli/query.go
In cmd query `Args:    cobra.ExactArgs(1) required but never used`
______
______
For admin use:
> Args:    cobra.ExactArgs(1) required but never used

- .github/PULL_REQUEST_TEMPLATE.md
- .github/auto-comment.yml
this pr takes the pull request template checklist and has a bot comment it in the pr opposed to it being in the PR body. 
this bot needs to be added to this repo https://github.com/apps/auto-comment
> add comment bot for PR checklist

- CHANGELOG.md
- go.mod
- go.sum
Closes: #XXX
______
______
For admin use:
> release 0.37.12

- CHANGELOG.md
> update master with release changelog

- x/ibc/02-client/client/cli/query.go
- x/ibc/04-channel/client/cli/query.go
- x/ibc/20-transfer/client/cli/query.go
> x/ibc: add missing query height

- x/ibc/02-client/handler.go
- x/ibc/02-client/keeper/client.go
- x/ibc/03-connection/handler.go
- x/ibc/04-channel/handler.go
- x/ibc/ante/ante.go
- Add msg sender events to antehandler
- Move update events to keeper method
> Fix event emission on IBC msgs

- client/flags/flags.go
> Fix "max-body-bytes" CLI Flag Description

- client/keys/parse.go
- go.mod
- types/address.go
- types/bech32/bech32.go
- types/bech32/bech32_test.go
THis pr takes bech32 from tendermint and adds it directly to the sdk
does this need a changelog entry?
closes: #XXXX
> types: add bech32

- types/bech32/bech32_test.go
fix import to sdk version
closes: #XXXX
> bech32: use sdk version

- x/ibc/02-client/keeper/client_test.go
- x/ibc/02-client/keeper/keeper_test.go
- x/ibc/02-client/types/genesis_test.go
- x/ibc/03-connection/keeper/keeper_test.go
- x/ibc/04-channel/keeper/keeper_test.go
- x/ibc/07-tendermint/client/cli/tx.go
- x/ibc/07-tendermint/client/rest/rest.go
- x/ibc/07-tendermint/client/rest/tx.go
- x/ibc/07-tendermint/misbehaviour_test.go
- x/ibc/07-tendermint/types/client_state.go
- x/ibc/07-tendermint/types/client_state_test.go
- x/ibc/07-tendermint/types/msgs.go
- x/ibc/07-tendermint/types/msgs_test.go
- x/ibc/07-tendermint/update.go
- x/ibc/07-tendermint/update_test.go
- x/ibc/20-transfer/handler_test.go
- x/ibc/20-transfer/keeper/keeper_test.go
- x/ibc/ante/ante_test.go
- x/ibc/genesis_test.go
> ibc/07-tendermint: variable trust-level

- CHANGELOG.md
- x/distribution/types/codec.go
> x/distribution: register MsgFundCommunityPool

- x/ibc/03-connection/keeper/handshake.go
- x/ibc/03-connection/keeper/handshake_test.go
Closes https://github.com/cosmos/cosmos-sdk/issues/5908
> Alter connection handshake

- .github/workflows/update-qa.yml
This PR adds a GitHub actions workflow to update QA page for this repo.
> qa: add action to update qa page

- scripts/protocgen.sh
> Fix proto-gen find cmd

- baseapp/helpers.go
- baseapp/queryrouter.go
- baseapp/router.go
- docs/intro/sdk-app-architecture.md
- x/ibc/03-connection/types/connection.go
- x/ibc/03-connection/types/connection_test.go
- x/ibc/03-connection/types/genesis_test.go
- x/ibc/04-channel/types/channel_test.go
- x/ibc/04-channel/types/genesis_test.go
- x/ibc/04-channel/types/msgs_test.go
- x/ibc/05-port/keeper/keeper_test.go
- x/ibc/07-tendermint/types/client_state_test.go
- x/ibc/07-tendermint/types/msgs_test.go
- x/ibc/20-transfer/types/genesis_test.go
- x/ibc/20-transfer/types/msgs_test.go
- x/ibc/23-commitment/types/merkle_test.go
- x/ibc/24-host/validate.go
- x/ibc/24-host/validate_test.go
- x/ibc/genesis_test.go
closes: #6080
Test regex [here](regexr.com/54mop)
> x/ibc: alter id requirements

- .github/CODEOWNERS
See https://github.com/cosmos/cosmos-sdk/pull/6243#discussion_r426772231.
---
> CODEOWNERS: remove Peng

- .github/workflows/lint.yml
- .github/workflows/proto.yml
- .github/workflows/sims.yml
- .github/workflows/test.yml
- README.md
- types/tx/types.proto
have paths defined for proto changes
closes: #XXXX
---
> ci: test paths directive

- SECURITY.md
- docs/core/README.md
> docs: update SECURITY.md

- CHANGELOG.md
> v0.38.4 CL

- x/ibc/07-tendermint/client/cli/tx.go
> ibc/07-tendermint: fix CLI

- x/auth/types/stdtx.go
> Use len of Signers in the error message

- types/simulation/types.go
- x/bank/simulation/operations.go
- x/bank/types/msgs.go
- x/distribution/simulation/operations.go
- x/distribution/types/msg.go
- x/gov/simulation/operations.go
- x/slashing/simulation/operations.go
- x/slashing/types/msg.go
- x/staking/simulation/operations.go
- x/staking/types/msg.go
> Add msg type sim operations

- x/upgrade/module.go
This PR registers the `x/upgrade` module transactions cli commands properly. 
Closes: #6284
---
> Registered upgrade module tx commands

- x/upgrade/module.go
Reverts cosmos/cosmos-sdk#6285
> Revert "Registered upgrade module tx commands"

- client/lcd/root.go
- go.mod
- go.sum
- tests/util.go
> Bump Tendermint v0.33.5

- CHANGELOG.md
- go.mod
- go.sum
> v0.37.13-RC1

- CONTRIBUTING.md
> Revise Point Release Process

- x/auth/client/cli/tx_multisign.go
- x/auth/client/cli/tx_sign.go
> x/auth/client: remove duplicate flags

- docs/architecture/adr-024-coin-metadata.md
In order to allow clients to provide a rich multi token experience, it is very helpful to not only have a list of display options available on-chain but also help the client to choose one that is most likely a good choice for human interaction. This PR is an addition to #6253 which has the consequence, that most clients do not need any local token configuration at all. Of course, a client can always chose to use a different representation but the chain can provide one that can serve as a default or fallback for the majority of cases.
The goal this is working towards is already stated in the original PR
> We propose to have `x/bank` additionally keep track of metadata per `denom` in order to help clients, wallet providers, and explorers improve their UX and remove the requirement for …
> Add special treatment for base and display denomination

- README.md
Add a badge that tracks the total number of projects using the SDK:
- Docs: https://docs.sourcegraph.com/user/repository/badges
Screenshot: 
---
> readme: add sourcegraph badge

- x/ibc/04-channel/types/packet.go
> x/ibc: commit timeout timestamp

- docs/basics/gas-fees.md
closes: #XXXX
---
**Note**: some items not checked since this is just a minor documentation change (typo fix).
> Fixed typos.

- types/module/module_test.go
- types/router_test.go
- x/ibc/02-client/exported/exported.go
- x/ibc/04-channel/keeper/querier_test.go
- x/ibc/09-localhost/types/client_state.go
- x/ibc/23-commitment/types/merkle.go
- x/mint/client/cli/cli_test.go
- x/mint/client/testutil/helpers.go
closes: #XXXX
Run make format.
---
> Make format

- server/api/server.go
- server/config/config.go
- server/start.go
> Some small improve on API server.

- types/tx/signing/signature_data.go
- types/tx/tx_wrapper.go
- types/tx/tx_wrapper_test.go
- x/auth/signing/direct/direct_test.go
> 6385 wrapper tests

- x/ibc/04-channel/keeper/packet.go
- x/ibc/04-channel/keeper/packet_test.go
> ibc/04-channel: move UNORDERED channel ack to RecvPacket

- docs/building-modules/structure.md
> remove alias.go from docs

- simapp/cmd/simd/main.go
We support custom pruning options via granular flags, but these were never actually used...
---
> SimApp: Fix Pruning Custom Flags (Actually Use the Values)

- x/ibc/04-channel/alias.go
- x/ibc/04-channel/keeper/keeper.go
- x/ibc/04-channel/keeper/packet.go
- x/ibc/04-channel/keeper/packet_test.go
- x/ibc/04-channel/types/errors.go
- x/ibc/04-channel/types/events.go
> Remove CleanupPacket from 04-channel

- go.mod
- types/coin_test.go
Little improve on test coverage. 
---
> Add string test for coin and coins

- .github/PULL_REQUEST_TEMPLATE.md
It would be a useful reminder for me and I imagine others to check the CodeCov report when I'm submitting a PR.
---
> Add Review Codecov Report check to PR template

- x/params/spec/01_keeper.md
- x/params/spec/02_subspace.md
I am lately self-documenting for myself all the Cosmos SDK, some .md files use the 80 column convention. It is nice to have it, some IDEs or even vim by default does not break lines, so it is an improvement for readability.
We can close it if it is not needed.
closes: #XXXX
---
> Params Spec 80 column md.

- go.mod
- go.sum
- x/ibc/07-tendermint/misbehaviour.go
> deps: bump TM v0.33.6

- docs/package-lock.json
Fixed: removed `package-lock.json` and did npm install.
`live`: https://docs.cosmos.network
`staging`: https://docs.staging-cosmos.network/master
---
> docs: package-lock hotfix

- .github/workflows/stale.yml
add issues to stale bot. 
closes: #6584
> add issues to stale job

- x/ibc/03-connection/handler.go
- x/ibc/03-connection/keeper/keeper.go
- x/ibc/03-connection/types/events.go
ref: https://github.com/cosmos/cosmos-sdk/pull/6482#pullrequestreview-442567669
ref: https://github.com/cosmos/ics/issues/446
---
> x/ibc: minor fixes

- tests/util.go
Gut unnecessary test helpers.
---
> tests: cleanup unused functions

- server/util.go
- simapp/simd/cmd/genaccounts.go
- version/command.go
- version/version_test.go
- x/genutil/client/cli/collect.go
- x/genutil/client/cli/init.go
- x/genutil/client/cli/init_test.go
> version: Remove Viper

- x/genutil/client/cli/gentx.go
- x/genutil/client/cli/init.go
- x/genutil/client/cli/init_test.go
I was having trouble with `simd gentx` and this fixed it.
closes: #XXXX
---
> fix HomeFlag

- .github/workflows/test.yml
- std/pubkey.go
bump codecov to latest to see if it fixes anything
> ci: bump codecov

- x/ibc-transfer/module.go
- x/ibc/02-client/client/cli/cli.go
- x/ibc/02-client/client/cli/query.go
- x/ibc/02-client/module.go
- x/ibc/03-connection/client/cli/cli.go
- x/ibc/03-connection/client/cli/query.go
- x/ibc/03-connection/module.go
- x/ibc/04-channel/client/cli/cli.go
- x/ibc/04-channel/client/cli/query.go
- x/ibc/04-channel/module.go
- x/ibc/client/cli/cli.go
- x/ibc/module.go
> x/ibc: update CLI queries

- client/cmd_test.go
- client/keys/add_ledger_test.go
- client/keys/add_test.go
- client/keys/delete_test.go
- client/keys/export_test.go
- client/keys/import_test.go
- client/keys/list_test.go
- client/keys/migrate_test.go
- client/keys/mnemonic_test.go
- client/keys/show_test.go
- testutil/ioutil.go
- testutil/ioutil_test.go
- version/version_test.go
- x/auth/client/cli/broadcast_test.go
- x/auth/client/cli/encode_test.go
- x/genutil/client/cli/migrate_test.go
> testutil: simplify

- x/auth/types/txbuilder.go
ref: https://github.com/cosmos/cosmos-sdk/pull/6653#discussion_r452720974
cc @alessio 
---
> Fix godocs for NewTxBuilderFromFlags

- codec/json.go
Noticed from coverage reports and from offline consultation
with Alexander and Aaron, that this function can be removed.
> codec: remove unused and untest ProtoMarshalJSONIndent

- client/flags/flags.go
- docs/building-modules/structure.md
- x/distribution/client/cli/cli_test.go
- x/distribution/client/cli/query.go
- x/distribution/client/cli/tx.go
- x/distribution/client/testutil/helpers.go
- x/distribution/keeper/genesis.go
- x/distribution/module.go
- x/gov/client/cli/tx.go
- Remove Get/Post commands call in parent/root constructor. These are now used in the individual command constructors so we don't have to manually call them in tests - i.e. it was originally a code smell.
- Define Import/Export Genesis on the Keeper directly. Doc has been updated as well.
/cc @fedekunze @alessio @jgimeno  @amaurymartiny 
---
> x/distribution: CLI & Module Tweaks

- x/staking/simulation/genesis_test.go
> x/staking/simulation/genesis.go: add unit tests

- crypto/hd/hdpath.go
> crypto/hd: update godoc for ComputerMastersFromSeed

- x/slashing/simulation/operation_test.go
> x/slashing/simulation/operations.go: add unit tests

- x/ibc-transfer/simulation/genesis_test.go
> x/ibc-transfer/simulation/genesis.go: add unit tests

- x/ibc/simulation/genesis_test.go
> x/ibc/simulation/genesis_test.go: add unit tests

- x/staking/handler.go
> x/staking: wrap denom error

- .github/workflows/lint.yml
> bump version of ci linter

- .github/workflows/lint.yml
- x/staking/simulation/genesis_test.go
fix ci linter
closes: #XXXX
---
> ci: linteer version fix

- x/gov/simulation/genesis_test.go
> x/gov/simulation/genesis.go: add unit tests

- x/ibc/02-client/client/utils/utils.go
> Remove unnecessary IBC func 

- x/auth/types/account.go
- x/auth/types/account_test.go
> auth: remove custom JSON marshaling

- x/distribution/simulation/proposals_test.go
> x/distribution/simulation/proposals.go: add unit tests

- x/distribution/simulation/genesis_test.go
> x/distribution/simulation/genesis.go: add unit tests

- x/capability/simulation/genesis_test.go
> x/capability/simulation/genesis.go: add unit tests

- x/distribution/simulation/params_test.go
> x/distribution/simulation/params.go: add unit tests

- x/bank/simulation/genesis_test.go
> x/bank/simulation/genesis.go: add unit tests

- x/bank/simulation/params_test.go
> x/bank/simulation/params.go: add unit tests

- x/auth/simulation/params_test.go
> x/auth/simulation/params.go: add unit tests

- x/auth/simulation/genesis_test.go
> x/auth/simulation/genesis.go: add unit tests

- x/distribution/client/cli/cli_test.go
Wait for a height after the query height.
---
> fix TestGetCmdQueryCommunityPool

- x/staking/keeper/delegation.go
> fix: add call to iterator Close method

- .github/workflows/lint.yml
Thanks: @marbar3778 for the original patch.
---
> [ci] fix linter

- CHANGELOG.md
> CHANGELOG.mg: merge v0.39.0 back in

- client/context.go
- client/flags/flags.go
- server/README.md
- simapp/simd/cmd/root.go
- tests/mocks/types_module_module.go
- types/module/module.go
- types/module/module_test.go
- x/auth/module.go
- x/bank/module.go
- x/capability/module.go
- x/crisis/module.go
- x/distribution/module.go
- x/evidence/module.go
- x/genutil/module.go
- x/gov/module.go
- x/ibc-transfer/module.go
- x/ibc/module.go
- x/mint/module.go
- x/params/module.go
- x/slashing/module.go
- x/staking/module.go
- x/upgrade/module.go
- Cleanup old TODO's
- Remove dead code
- Add README's & pkg documentation
ref: https://github.com/cosmos/cosmos-sdk/issues/6779
---
> Docs & Cleanup

- client/tx/tx.go
- x/auth/types/client_tx.go
Minor godoc and structure cleanup while going through the new tx generation and signing flow.
---
> Code & Doc cleanup

- x/upgrade/doc.go
- x/upgrade/keeper/keeper.go
- x/upgrade/keeper/keeper_test.go
> x/upgrade: Fix ReadUpgradeInfoFromDisk

- codec/json.go
> Disable automatic camelCasing in proto JSON

- docs/.vuepress/config.js
- docs/package-lock.json
- docs/package.json
1.0.169 changes: https://github.com/cosmos/vuepress-theme-cosmos/pull/84
- newsletter signup form: zoho → mailerlite
- top banner (Stargate): https://github.com/cosmos/vuepress-theme-cosmos/pull/82#issue-455323605
- banner content will be updated via https://github.com/cosmos/cosmos.network/pull/47
---
> Docs config

- server/api/server.go
the ports https://github.com/cosmos/cosmos-sdk/pull/6855/files to master
closes: #XXXX
> cors: fix on master for posts

- x/ibc/04-channel/types/msgs.go
- x/ibc/04-channel/types/msgs_test.go
> Remove Ack Length Limit

- x/ibc/23-commitment/types/merkle.go
saw this during review of #6471 
closes: #XXXX
---
> fix nil check bug

- client/debug/main.go
- crypto/codec/amino.go
- crypto/keyring/types_test.go
- crypto/ledger/ledger_mock.go
- crypto/ledger/ledger_secp256k1.go
- crypto/types/multisig/codec.go
- go.sum
- std/pubkey.go
- types/address_bench_test.go
- types/address_test.go
- x/auth/ante/ante_test.go
- x/auth/ante/sigverify.go
- x/evidence/keeper/keeper_test.go
This PR makes updates to keys. 
closes: #XXXX
---
> tendermint: update 2 (key updates)

- x/ibc/05-port/keeper/keeper.go
Noticed that this [log](https://pastebin.com/UY8aXUdL) had an error when binding to a new port:
```
I[2020-07-30|17:35:55.639] port %s binded                               module=x/ibc/port transfer=(MISSING)
```
---
> x/ibc: fix log

- proto/ibc/localhost/localhost.proto
- x/ibc/09-localhost/types/client_state.go
- x/ibc/09-localhost/types/client_state_test.go
- x/ibc/09-localhost/types/codec.go
- x/ibc/09-localhost/types/errors.go
- x/ibc/09-localhost/types/keys.go
- x/ibc/09-localhost/types/localhost.pb.go
- x/ibc/09-localhost/types/localhost_test.go
- x/ibc/09-localhost/types/msgs.go
I took the diffs from #6254 and migrated localhost client state to be a proto encoded type. VerifyClientConsensusState now returns an error for localhost clients since they do not store consensus states.
Amino has to stay until client is fully migrated, but will be trivially removed after
---
> migrate localhost client state to proto

- go.sum
- server/util.go
- simapp/simd/cmd/root.go
> Add default node home into server helpers

- CHANGELOG.md
- go.mod
- go.sum
> v0.37: update tendermint version

- x/ibc/02-client/abci_test.go
- x/ibc/02-client/genesis.go
- x/ibc/02-client/keeper/client_test.go
- x/ibc/02-client/keeper/keeper.go
- x/ibc/02-client/keeper/keeper_test.go
- x/ibc/02-client/types/genesis.go
- x/ibc/09-localhost/types/codec.go
- x/ibc/types/codec.go
This is very silly, but it is the only short term solution I can think of to get the sims passing again. Basically the simapp, simulations use amino to encode/decode genesis, but IBC no longer supports amino for this. So the only fix outside of refactoring the sims (which seems to be non-trivial) is to ensure IBC genesis is empty. I don't think we have implemented simulation messages for IBC so the tests were using default genesis, exporting and importing a genesis with a single local host (which makes sense why we didn't get any consensus state issues). 
I tested locally a couple sims and they pass, but we will need to wait to find out if they pass on here
ref: #5917 
ref: [comment](https://github.com/cosmos/cosmos-sdk/pull/6878#issuecomment-670450269)
---
Before we can merge this PR, …
> don't create localhost in IBC genesis to fix sims

- CHANGELOG.md
- go.mod
- go.sum
> release: 0.37.14

- x/mint/abci.go
Only emit metric when a valid int64.
closes: #7023
---
> Fix mint metric

- contrib/devtools/Makefile
Noticed that proto-tools command was not updated to add this dependency
---
> Adds protoc-gen-gateway in proto-tools

- simapp/simd/cmd/testnet.go
> testnet: fix initGenFiles

- .github/workflows/test.yml
- contrib/localnet_liveness.sh
This PR adds a liveness script and a github action to run the same. It should help us detect simd breakages beforehand
Ref: https://github.com/cosmos/cosmos-sdk/pull/7072#discussion_r471506642
---
> Add liveness check gh action

- .github/workflows/test.yml
Thanks: @marbar3778 for the patch.
---
> unblock CI on Launchpad

- docs/package-lock.json
- docs/package.json
Preview: https://docs.staging-cosmos.network
- bump vuepress-theme-cosmos to 1.0.171
- minor UI fixes
- algolia docsearch
> bump docs theme to 1.0.171

- baseapp/baseapp_test.go
- types/events.go
- types/events_test.go
We're not handling the case where the config is empty, which means we index _all_ events.
---
> Fix MarkEventsToIndex

- x/ibc/04-channel/keeper/packet.go
- x/ibc/04-channel/keeper/packet_test.go
Followup PR to #7170 
Discrepancy caught by @colin-axner 
The test I wrote fails on master
---
> Fix setting NextSequenceAck

- .github/workflows/test.yml
- Makefile
- contrib/images/Makefile
- contrib/images/simd-env/Dockerfile
- contrib/images/simd-env/wrapper.sh
- contrib/localnet_liveness.sh
- docker-compose.yml
Local network functionality was recently broken in that it did not build the binaries or docker image locally correctly.
/cc @alessio @sahith-narahari 
---
> Fix Localnet

- x/ibc-transfer/keeper/keeper.go
- x/ibc-transfer/types/expected_keepers.go
- x/ibc/03-connection/keeper/verify_test.go
- x/ibc/04-channel/keeper/packet.go
- x/ibc/04-channel/keeper/packet_test.go
- x/ibc/07-tendermint/types/client_state_test.go
- x/ibc/handler.go
- x/ibc/handler_test.go
- x/ibc/testing/chain.go
- x/ibc/testing/coordinator.go
> Rename PacketExecuted to ReceiveExecuted

- x/ibc/02-client/exported/exported.go
- x/ibc/09-localhost/types/client_state.go
- x/ibc/09-localhost/types/client_state_test.go
- x/ibc/09-localhost/types/localhost_test.go
- x/ibc/light-clients/solomachine/types/client_state.go
> ibc: remove GetChainID

- x/auth/spec/02_state.md
Fix an incorrect `vesting` link in `auth` module state page
closes #7226 
---
> Fix vesting link in auth module

- x/ibc/02-client/client/utils/utils.go
- x/ibc/07-tendermint/types/misbehaviour_handle.go
Implements solution described here: https://github.com/cosmos/cosmos-sdk/pull/7211#issuecomment-686762033
Tests of this particular change will be held off until the final installment of the height issue which will retrieve epoch-numbers from chain-id and test all epoch-number related logic in Tendermint client
---
> 7211 followup

- simapp/simd/cmd/testnet.go
> simapp: merge node and client config directories

- go.sum
- snapshots/types/convert.go
- store/types/store.go
- x/distribution/client/rest/grpc_query_test.go
- x/gov/client/utils/query_test.go
- x/ibc/02-client/types/height_test.go
- x/ibc/07-tendermint/types/test_utils.go
- x/ibc/client/query.go
- x/params/client/rest/grpc_query_test.go
- x/slashing/client/rest/grpc_query_test.go
- x/staking/types/validator_test.go
> run make format && go mod tidy

- CHANGELOG.md
Add changelog entry from [0.39.1 release](https://github.com/cosmos/cosmos-sdk/blob/v0.39.1/CHANGELOG.md#v0391) to master brnach.
---
> Add changelog entry for 0.39.1

- .gitignore
> refresh .gitignore

- simapp/simd/cmd/root.go
- x/genutil/client/cli/collect.go
- x/genutil/client/cli/gentx.go
- x/genutil/client/cli/gentx_test.go
Custom command to allow backwards compatibility 
SEE: #7279
---
> custom commands for gentx and collect-gentxs

- .github/workflows/test.yml
Add build-simd-linux to make's command line.
---
> ci: fix liveness test job

- x/auth/vesting/handler_test.go
> Fix TestMsgCreateVestingAccount

- docs/basics/tx-lifecycle.md
Small fix in single word: `cacehd` -> `cached`
---
> docs: fix typo in tx-lifecycle

- crypto/keys/secp256k1/secp256k1.go
- go.sum
- types/tx/signing/signature.go
- types/tx/types.go
- x/auth/legacy/legacytx/stdsign.go
- x/auth/legacy/legacytx/stdtx.go
- x/auth/tx/sigs.go
- x/gov/client/rest/grpc_query_test.go
> make format && go mod tidy

- .github/workflows/test.yml
- Dockerfile
- Makefile
fix simapp dockerfile. Please do not merge this PR, I will push a new docker image with it after approvals agre given
closes: #7391 
---
> fix dockerfile

- Makefile
- go.sum
> Makefile: enable badgerdb conditional compilation

- go.mod
- go.sum
The release contains a fix for https://github.com/dvsekhvalnov/jose2go/issues/26,
which is needed for the file keyring backend to work with go 1.15.
closes: #XXXX
---
> Update 99designs/keyring to v1.1.6 for go 1.15

- crypto/keys/multisig/codec.go
- types/address_test.go
- types/coin_test.go
- types/config_test.go
- types/context_test.go
- types/decimal_internal_test.go
- types/decimal_test.go
- types/denom_internal_test.go
- types/events_test.go
- types/invariant_test.go
- types/result_test.go
- types/router_test.go
- types/staking_test.go
- types/store_test.go
- types/tx_msg_test.go
- x/genutil/utils.go
> types: tests -> test suites migration

- codec/types/interface_registry.go
- types/codec.go
while reviewing https://github.com/cosmos/cosmos-sdk/pull/7432, I found this proto registration, propose to use `cosmos.base` package as for other SDK primitives.
---
> proto register "cosmos.base.v1beta.Msg" interface

- docs/versions
This PR changes the order of docs versions in order to have `master` as the default version.
closes: #7468
---
> docs: set master as default version

- Makefile
- go.sum
> Makefile: s/TENDERMINT/COSMOS/

- x/upgrade/client/cli/tx.go
Change `"Submit a software upgrade proposal"`  for `"Submit a cancel previous software upgrade proposal"` on `cosmos-sdk/x/upgrade/client/cli/tx.go` in line `97`. 
closes: [Issue #64 on cosmosdevs/stargate](https://github.com/cosmosdevs/stargate/issues/64)
---
> Fix on gov module

- docs/architecture/README.md
found during review
closes: #XXXX
---
> Typo in docs

- CHANGELOG.md
> Update CHANGELOG to reflect ADR 031 features more clearly

- x/staking/legacy/v040/migrate_test.go
> Fix migrate test for Validator pubkey Any

- .gitignore
+ adding Emacs' `.dir-locals.el` to gitignore
+ order other entries
> gitignore: adding Emacs .dir-locals.el

- x/distribution/legacy/v036/types.go
- x/genutil/legacy/v036/migrate.go
- x/genutil/legacy/v038/migrate.go
- x/genutil/legacy/v039/migrate.go
- x/genutil/legacy/v040/migrate.go
- x/gov/legacy/v040/migrate.go
- x/gov/legacy/v040/migrate_test.go
Backport of #7601 fix to `v0.40.x` in preperation for RC1.
Making use of `release/v0.40.x` branch here, as that has branch protection, and previously used branch, `v0.40.x`, does not.
Refs: #7607, #7601 
closes: #XXXX
---
> [backports/v0.40.x]: Add CommunitySpendProposals in migration #7607

- docs/architecture/adr-020-protobuf-transaction-encoding.md
ref: @ebuchman's suggestion on Discord
---
> Add background for Sequence change in ADR-020

- docs/architecture/PROCESS.md
- docs/architecture/README.md
- docs/architecture/adr-template.md
Describe a process of creating and approving an ADR.
During the Architecture call on 2020-10-09 we discussed the current ADR process and when and how we should change an ADR status. We propose to review this current process and see how we can make it more efficient
closes: #7498
---
> ADR: add a process proposal

- Makefile
Fix regressions in Makefile introduced in #7364.
Closes: #7673
---
> fix check-test-* targets

- x/ibc/core/03-connection/client/cli/tx.go
- x/ibc/core/03-connection/keeper/grpc_query_test.go
- x/ibc/core/03-connection/keeper/handshake.go
- x/ibc/core/03-connection/keeper/handshake_test.go
- x/ibc/core/03-connection/keeper/keeper_test.go
- x/ibc/core/03-connection/simulation/decoder_test.go
- x/ibc/core/03-connection/types/connection.go
- x/ibc/core/03-connection/types/connection_test.go
- x/ibc/core/03-connection/types/genesis_test.go
- x/ibc/core/03-connection/types/msgs_test.go
- x/ibc/core/03-connection/types/version.go
- x/ibc/core/03-connection/types/version_test.go
- x/ibc/core/04-channel/keeper/handshake_test.go
- x/ibc/core/genesis_test.go
- x/ibc/core/keeper/msg_server.go
- x/ibc/core/simulation/decoder_test.go
- x/ibc/core/spec/01_concepts.md
- x/ibc/light-clients/06-solomachine/types/client_state_test.go
- x/ibc/light-clients/06-solomachine/types/codec_test.go
- x/ibc/light-clients/09-localhost/types/client_state_test.go
- x/ibc/testing/chain.go
various fixes added, not everything is fixed yet. To be merged into the existing pr for this change, not master
closes: #XXXX
---
> ibc change connection version string to proto

- x/ibc/core/04-channel/keeper/packet.go
- x/ibc/core/04-channel/types/events.go
Creates a separate write-ack event type and provides all necessary attributes to construct `MsgAcknowledgement`
This is necessary to support stateless relaying of asynchronous acknowledgements
closes: #7684
---
> Create separate Write-Ack Event

- .github/workflows/docker.yml
fix docker push
-->
closes: #XXXX
---
> docker fix

- x/ibc/applications/transfer/keeper/keeper.go
- x/ibc/applications/transfer/module.go
- x/ibc/applications/transfer/module_test.go
closes: https://github.com/cosmos/cosmos-sdk/issues/7761
---
> Don't claim channel capability on crossing hellos

- x/ibc/core/23-commitment/types/merkle.go
> Remove BatchProofs implementation

- x/ibc/applications/transfer/types/msgs.go
- x/ibc/applications/transfer/types/packet.go
- x/ibc/core/02-client/types/msgs.go
- x/ibc/core/03-connection/types/msgs.go
- x/ibc/core/04-channel/types/msgs.go
> ibc: validate signer address

- docs/package-lock.json
- docs/package.json
- bump vuepress-theme-cosmos 1.0.175
---
> docs: bump vuepress-theme-cosmos 1.0.175

- x/ibc/core/02-client/keeper/keeper.go
- x/ibc/core/02-client/keeper/keeper_test.go
> ibc: remove GetClientConsensusStateLTE

- docs/cn/basics/app-anatomy.md
> docs: fix broken url in handler cn/basics/app-anatomy.md

- docs/run-node/interact-node.md
- docs/run-node/keyring.md
- docs/run-node/run-node.md
- types/tx/types.go
In the process of building the Regen Ledger node following the docs, I discovered some little errors in docs and errors messages:
- Followed exactly https://docs.cosmos.network/master/run-node/, and found some outdated/forgotten flags
---
> Small fixes in docs and error messages

- CHANGELOG.md
Updates changelog for v0.40.0-rc3. RC3 will be tagged off of this merge commit.
---
> Update changelog for v0.40.0-rc3

- x/ibc/light-clients/07-tendermint/types/client_state.go
This error is already wrapped upstream with appropriate logic and now matches the other similar errors in this file
closes: #XXXX
---
> Remove redundancy in IBC error

- server/rosetta/cosmos/client/client.go
- server/rosetta/cosmos/conversion/data.go
- server/rosetta/errors.go
- server/rosetta/services/data.go
- server/rosetta/types.go
> add: support for balance tracking

- x/ibc/light-clients/06-solomachine/spec/01_concepts.md
- x/ibc/light-clients/06-solomachine/types/misbehaviour_handle.go
- x/ibc/light-clients/06-solomachine/types/misbehaviour_handle_test.go
> remove timestamp check from solomachine misbehaviour

- x/ibc/applications/transfer/types/trace.go
> move sdk denom validation to top of ValidateIBCDenom

- client/tx/factory.go
- simapp/simd/cmd/genaccounts.go
- types/coin.go
- types/coin_test.go
- types/dec_coin_test.go
- types/denom.go
- types/denom_internal_test.go
- types/rest/rest_test.go
- types/simulation/rand_util_test.go
- x/auth/vesting/client/cli/tx.go
- x/bank/client/cli/tx.go
- x/bank/client/testutil/cli_helpers.go
- x/distribution/client/cli/tx.go
- x/genutil/client/cli/gentx.go
- x/gov/client/cli/tx.go
- x/params/client/cli/tx.go
- x/upgrade/client/cli/tx.go
added `NormalizeCoins`/`ParseCoinsNormalized` utilities, and normalize(converting to the smallest unit registered) coins automatically in cli interface.
closes: #7623
---
> cli: convert coins to smallest unit registered

- docs/ibc/custom.md
- x/ibc/core/05-port/types/module.go
- x/ibc/core/spec/05_callbacks.md
> counterParty -> counterparty

- x/ibc/applications/transfer/types/keys.go
- x/ibc/applications/transfer/types/keys_test.go
addresses part 2 of #7737 
---
> add domain separation between port and channel for transfer escrow address

- server/config/config.go
- server/config/toml.go
- server/rosetta.go
- server/rosetta/config/config.go
- server/rosetta/cosmos/client/client.go
- server/rosetta/services/data.go
- server/rosetta/services/offline.go
- server/rosetta/types.go
- server/start.go
> Add rosetta into server command

- CHANGELOG.md
- crypto/hd/fundraiser_test.go
- crypto/hd/hdpath.go
- crypto/hd/hdpath_test.go
- crypto/keyring/keyring_ledger_test.go
- crypto/keyring/types_test.go
- crypto/ledger/ledger_test.go
- types/address.go
> crypto/hd: add 'm/' prefix to hd path
