cosmos/cosmos-sdk

CHANGELOG.md
RELEASE_NOTES.md
go.mod
go.sum

launchpad: bump tendermint to v0.33.9

---

CHANGELOG.md
version/version.go

version --long displays replaced build dependencies

---

.github/workflows/test.yml

exclude *.pb.gw.go files from codecov.io report

---

crypto/hd/hdpath_test.go

Testable examples were accidentally converted into tests.
---

revert tiny portion of #7970

---

.codecov.yml

The `.codecov.yml` was invalid.
You can validate the file via:
```sh
curl -X POST --data-binary @.codecov.yml https://codecov.io/validate
```
---

Fix codecov flag project config

---

.github/workflows/test.yml
go.mod
go.sum
x/ibc/light-clients/07-tendermint/types/fraction.go

Replaces https://github.com/cosmos/cosmos-sdk/pull/7988. Not sure why we're getting a `go mod` error on that PR.
---

Bump Tendermint v0.34.0

---

x/ibc/light-clients/07-tendermint/types/misbehaviour_handle.go
x/ibc/light-clients/07-tendermint/types/misbehaviour_handle_test.go

Fix tendermint misbehaviour trusted consensus state age check

---

server/rosetta/cosmos/client/client.go
server/rosetta/cosmos/conversion/data.go
server/rosetta/cosmos/conversion/tm_to_sdk.go
server/rosetta/services/construction.go
server/rosetta/services/data.go
server/rosetta/types.go

Add tx status to rosetta

---

CHANGELOG.md
store/rootmulti/store.go
store/rootmulti/store_test.go

Tagging v0.40.0-rc4 will occur immediately after this merge.
This contains one PR cherry-picked against rc3:
- #8048 Fix `SetInitialVersion`
v0.40.0-rc5 will be the next release candidate containing more a more significant changelog. We've opted to get this minor rc3 out first as it is needed by validators currently running the simulated upgrade for the currently undeway Stargate testnet.
---

v0.40.0-rc4

---

contrib/rosetta/configuration/run_tests.sh
contrib/rosetta/docker-compose.yaml
contrib/rosetta/node/Dockerfile
contrib/rosetta/rosetta-cli/Dockerfile

Try split images.

---

docs/.vuepress/config.js
docs/package-lock.json
docs/package.json

- version switcher on docs-staging
---

docs: add version switcher to docs-staging

---

types/query/pagination_test.go

types/query: fix pagination test

---

docs/.vuepress/config.js
docs/package-lock.json
docs/package.json

Ref: https://github.com/cosmos/cosmos-sdk/pull/8084
- Add version switcher to /v0.39 docs
---

docs: version switcher for /v0.39

---

x/auth/client/cli/tx_sign.go

handle deferred io.WriterCloser.Close() calls

---

CHANGELOG.md
go.mod
go.sum

- bump Tendermint (v0.32.14) version for cosmos hub (v2.0.14)
closes: #XXXX
---

bump tendermint version

---

x/bank/atlas/atlas.toml

Already [published](https://atlas.cosmos.network/modules/1/v0.39.2), just updated the manifest.
---

x/bank: update atlas manifest

---

x/auth/atlas/atlas-v0.39.1.md
x/auth/atlas/atlas.toml
x/bank/atlas/atlas-v0.39.1.md

Already published, just updated the manifest.
---

x/auth: update atlas manifest

---

go.mod
go.sum
server/rosetta/cosmos/construction.go
server/rosetta/cosmos/from_rosetta.go
server/rosetta/services/construction.go

update construction for 0.37

---

baseapp/params.go
baseapp/params_test.go

realized the error message is slightly incorrect
[ref](https://github.com/cosmos/cosmos-sdk/pull/8164#discussion_r542308506)
---

Improve evidence consensus param error message and test cases

---

x/ibc/light-clients/07-tendermint/types/upgrade.go
x/ibc/light-clients/07-tendermint/types/upgrade_test.go

This allows an IBC upgrade that doesn't bump the revision number to succeed. This is necessary as `x/upgrade` can create upgrades that modify the client (e.g. change unbonding period) without changing the chain-id
closes: #XXXX
---

Support IBC upgrade on same revision

---

proto/cosmos/upgrade/v1beta1/upgrade.proto
x/upgrade/types/proposal.go
x/upgrade/types/proposal_test.go

found while manually testing upgrades. Tested the fix manually on a live chain and tested that the test fails and then passes with the fix
closes: #XXXX
---

Fix IBC software upgrade proposals from automatically failing, add unpackinterfaces function

---

x/distribution/spec/README.md

Just a quick typo fix of a common word choice error.
---

docs: typo fix

---

contrib/rosetta/configuration/staking.ros
contrib/rosetta/configuration/transfer.ros
server/rosetta.go
server/rosetta/config/config.go
server/rosetta/cosmos/client/client.go
server/rosetta/cosmos/conversion/from_rosetta.go
server/rosetta/cosmos/conversion/to_rosetta.go
server/rosetta/services/construction.go
server/rosetta/services/data.go
server/rosetta/types.go
server/start.go
x/bank/types/msgs.go
x/staking/types/msg.go
x/staking/types/tx.pb.go

[Rosetta]: extend Rosetta API operations with custom sdk.Msgs

---

x/upgrade/doc.go

x/upgrade docs - general audit and cleanup

---

go.mod
go.sum

go.mod: update to cosmos/iavl@v0.15.3 for performance updates

---

client/rpc/block.go
client/rpc/rpc_test.go

closes: https://github.com/cosmos/gaia/issues/502
---

Fix Unregistered interface types.Evidence

---

x/distribution/keeper/msg_server.go

Set withdraw address with `msg.WithdrawAddress` instead of `msg.DelegatorAddress`.
---

 Fix setting withdraw address

---

docs/core/README.md
docs/core/grpc_rest.md
docs/core/proto-docs.md
docs/protodoc-markdown.tmpl
go.mod
go.sum
proto/cosmos/staking/v1beta1/tx.proto
proto/cosmos/tx/v1beta1/tx.proto
scripts/protocgen.sh
types/tx/tx.pb.go
x/staking/types/tx.pb.go

Add script to generate proto-docs

---

x/ibc/core/02-client/keeper/grpc_query.go
x/ibc/core/02-client/keeper/grpc_query_test.go

Fix ConsensusStates grpc query

---

contrib/githooks/pre-commit

… pre commit
closes: #XXXX
---

Fix pre commit path for statik.

---

CHANGELOG.md

Changelog updates for `v0.40.0-rc6`. RC6 will then be tagged off of this merge commit.
---

v0.40.0-rc6 Changelog Update

---

contrib/rosetta/docker-compose.yaml

Update rosetta cli.

---

x/genutil/client/cli/gentx.go
x/genutil/client/cli/gentx_test.go

Fix gentx command setting wrong amount

---

docs/ibc/custom.md
docs/ibc/overview.md

Update app guide to reflect latest IBC changes
---

Update IBC Application Guide

---

x/upgrade/client/cli/tx.go

Reverts cosmos/cosmos-sdk#8261

Revert "Fix upgrade tx commands not showing up in CLI"

---

x/evidence/doc.go
x/evidence/spec/01_concepts.md
x/evidence/spec/03_messages.md

x/evidence doc general audit & cleanup

---

CHANGELOG.md

Update changelog for v0.40.0-rc7.
---

Update changelog for v0.40.0-rc7

---

x/upgrade/client/cli/query.go
x/upgrade/client/rest/query.go

Using the REST API, GET /upgrade/current query returns an error.
`{"error":"UnmarshalBinaryBare expected to read prefix bytes F247B1FB (since it is registered concrete) but got 7B227479..."}
`
closes: #XXXX 
---

fix GET /upgrade/current query

---

CHANGELOG.md
RELEASE_NOTES.md

closes #stargate 
Rendered:
- [changelog](https://github.com/cosmos/cosmos-sdk/blob/clevinson/v0.40.0-final/CHANGELOG.md)
- [release notes](https://github.com/cosmos/cosmos-sdk/blob/clevinson/v0.40.0-final/RELEASE_NOTES.md)
[Diff vs v0.40.0-rc7](https://github.com/cosmos/cosmos-sdk/compare/v0.40.0-rc7...clevinson%2Fv0.40.0-final?diff=unified)
---

Stargate Release PR -- v0.40.0 Final

---

CHANGELOG.md
docs/versions

Few post-release cleanup items. I opted not to add RELEASE_NOTES.md into master, rather link them directly from the changelog. If people think its valuable to have master always have a copy of the most recent release's RELEASE_NOTES.md, then I can add that back into this PR.
- backport `v0.40.0` consolidated changelog to `master`
- add `release/v0.40.x` branch to docs pipeline, for rendering of `v0.40` docs on http://docs.cosmos.network
---

v0.40.0 Changelog backport & docs publish

---

x/bank/types/msgs.go
x/distribution/types/msg.go
x/staking/types/msg.go

[Rosetta] Add support for redelegate

---

server/rosetta/client_online.go
server/rosetta/conv_from_rosetta.go
server/rosetta/util.go

[Rosetta] Implement tx mempool endpoint 

---

contrib/rosetta/configuration/staking.ros
contrib/rosetta/docker-compose.yaml

[Rosetta] add: undelegate tests with rosetta-cli

---

.github/workflows/proto-docker.yml
CHANGELOG.md
buf.yaml
client/grpc/reflection/reflection.pb.gw.go
client/grpc/tmservice/query.pb.gw.go
contrib/devtools/dockerfile
docs/core/proto-docs.md
scripts/protocgen.sh
types/tx/service.pb.gw.go
x/auth/types/query.pb.gw.go
x/bank/types/query.pb.gw.go
x/distribution/types/query.pb.gw.go
x/evidence/types/query.pb.gw.go
x/gov/types/query.pb.gw.go
x/ibc/applications/transfer/types/query.pb.gw.go
x/ibc/core/02-client/types/query.pb.gw.go
x/ibc/core/03-connection/types/query.pb.gw.go
x/ibc/core/04-channel/client/utils/utils.go
x/ibc/core/04-channel/types/query.pb.gw.go
x/mint/types/query.pb.gw.go
x/params/types/proposal/query.pb.gw.go
x/slashing/types/query.pb.gw.go
x/slashing/types/slashing.pb.go
x/staking/types/query.pb.gw.go
x/upgrade/types/query.pb.gw.go

- push docker file for proto generation from cosmos-sdk
- add proto-doc to image
closes: #8358 
---

fix proto generation

---

.github/workflows/proto-docker.yml

- fix docker proto deployment
closes: #XXXX
---

proto: docker deployment

---

x/upgrade/client/rest/query.go

* fix cli queries
* fix codec issue
* revert cli
Co-authored-by: SaReN <sahithnarahari@gmail.com>
backport #8282 
---

backport: fix GET /upgrade/current query (#8280)

---

CHANGELOG.md
x/auth/client/cli/cli_test.go
x/auth/client/testutil/helpers.go
x/auth/tx/sigs.go

* fix signature only
* add test, changelog
* update test
* Update CHANGELOG.md
* address suggestions
Co-authored-by: Alessio Treglia <alessio@tendermint.com>
Co-authored-by: Federico Kunze <31522760+fedekunze@users.noreply.github.com>
backport #8287
---

backport: Fix sequence value in auth sign signature only (#8287)

---

CHANGELOG.md
types/errors/errors.go
types/errors/errors_test.go

backport a514131b88767cc58da9265b6b609bd4d9b60e6d to release v0.40.1
---

fix: wrappedError.Is (#8355)

---

CHANGELOG.md

Rebase changelog on 0.40.1 release
---

Update changelog after 0.40.1 release

---

docs/architecture/adr-035-rosetta-api-support.md

[Rosetta] change: revisit adr with the latest changes

---

server/rosetta/client_offline.go
server/rosetta/conv_to_rosetta.go

[Rosetta] change: disallow multiple msgs tx building

---

docs/.vuepress/config.js
docs/package-lock.json
docs/package.json
docs/versions

Ref: https://github.com/allinbits/design/issues/361 https://github.com/cosmos/vuepress-theme-cosmos/issues/91
`/v0.39`
- bump docs theme to 1.0.180
- update versions
- update versions on config.js
---

docs: update v0.39 docs

---

CHANGELOG.md
x/ibc/core/keeper/msg_server.go

Reorder IBC channel callbacks

---

docs/core/proto-docs.md
proto/cosmos/authz/v1beta1/tx.proto
types/errors/errors.go
x/authz/client/cli/flags.go
x/authz/client/cli/tx.go
x/authz/keeper/grpc_query.go
x/authz/keeper/keeper.go
x/authz/keeper/msg_server.go
x/authz/module.go
x/authz/types/authorizations.go
x/authz/types/codec.go
x/authz/types/errors.go
x/authz/types/keys.go
x/authz/types/msgs.go
x/authz/types/send_authorization.go
x/authz/types/tx.pb.go
x/staking/types/tx.pb.go

`x/authz` fixes

---

CHANGELOG.md
simapp/simd/cmd/genaccounts.go

simapp: increase supply balance when adding genaccount

---

CHANGELOG.md
simapp/simd/cmd/genaccounts.go

stargate: add balance to supply when creating a genacc

---

CHANGELOG.md
x/auth/client/rest/rest_test.go
x/ibc/applications/transfer/module.go
x/ibc/applications/transfer/types/codec.go
x/ibc/applications/transfer/types/msgs.go
x/ibc/applications/transfer/types/msgs_test.go

From: #8437
Closes: #8266
Thanks: @fedekunze
---

ibc: MsgTransfer amino JSON

---

CHANGELOG.md
RELEASE_NOTES.md

chore: update RELEASE_NOTES.md

---

CHANGELOG.md
RELEASE_NOTES.md
simapp/simd/cmd/genaccounts.go
x/auth/client/rest/rest_test.go
x/bank/module.go
x/bank/types/balance.go
x/bank/types/balance_test.go
x/bank/types/genesis.go
x/bank/types/genesis_test.go
x/bank/types/metadata.go
x/bank/types/metadata_test.go
x/bank/types/supply.go
x/ibc/applications/transfer/module.go
x/ibc/applications/transfer/types/codec.go
x/ibc/applications/transfer/types/msgs.go
x/ibc/applications/transfer/types/msgs_test.go
x/ibc/core/keeper/msg_server.go

Release v0.41.0

---

.github/workflows/docker.yml
.github/workflows/proto-docker.yml

- dont login when in ci. Avoids failing ci when outside contributors open PRs
merge at will. The bot cant do it
---

docker: avoid login when in PR

---

docs/core/context.md
docs/core/node.md

Fix typo in context and node docs

---

docs/core/grpc_rest.md

- Update port and default settings
- Bump links to 0.41
closes: #XXXX
---

docs: rest_grpc updates

---

go.mod
go.sum

backports #8573
Bumps [github.com/tendermint/tendermint](https://github.com/tendermint/tendermint) from 0.34.3 to 0.34.4.
- [Release notes](https://github.com/tendermint/tendermint/releases)
- [Changelog](https://github.com/tendermint/tendermint/blob/v0.34.4/CHANGELOG.md)
- [Commits](https://github.com/tendermint/tendermint/compare/v0.34.3...v0.34.4)
Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: mergify[bot] <37929162+mergify[bot]@users.noreply.github.com>
closes: #XXXX
---

[backport/v0.41.x] build(deps): bump github.com/tendermint/tendermint from 0.34.3 to 0.3.34.4

---

CHANGELOG.md

forward porting #8596 to master
---

Add v0.41.1 section in Changelog

---

go.mod
go.sum
testutil/network/network.go

Bump tendermint to v0.34.7

---

simapp/app_test.go
types/bench_test.go
x/ibc/light-clients/07-tendermint/types/proposal_handle_test.go

run make format

---

docs/core/baseapp.md

I got a little thrown off reading this. I think this is clearer 
closes: #XXXX
---

Update baseapp docs

---

client/grpc/reflection/reflection.pb.gw.go
client/grpc/tmservice/query.pb.gw.go
scripts/protocgen.sh
types/tx/service.pb.gw.go
x/auth/client/rest/rest_test.go
x/auth/types/query.pb.gw.go
x/authz/types/query.pb.gw.go
x/bank/types/query.pb.gw.go
x/distribution/types/query.pb.gw.go
x/evidence/types/query.pb.gw.go
x/feegrant/types/query.pb.gw.go
x/gov/types/query.pb.gw.go
x/ibc/applications/transfer/types/query.pb.gw.go
x/ibc/core/02-client/types/query.pb.gw.go
x/ibc/core/03-connection/types/query.pb.gw.go
x/ibc/core/04-channel/types/query.pb.gw.go
x/mint/types/query.pb.gw.go
x/params/types/proposal/query.pb.gw.go
x/slashing/types/query.pb.gw.go
x/staking/types/query.pb.gw.go
x/upgrade/types/query.pb.gw.go

gRPC gateway issue with colons in the account url path

---

CHANGELOG.md
go.mod
go.sum

Upgrade iavl from v0.14.1 to v0.14.3.
---

upgrade iavl to v0.14.3

---

CHANGELOG.md

merge 0.41 changelogs

---

Makefile

add tm version to make file
closes: #7963
---

add tm version to makefile

---

docs/.vuepress/config.js
docs/versions

Ref: https://github.com/cosmos/cosmos-sdk/pull/8672 and https://github.com/cosmos/cosmos-sdk/pull/8353#pullrequestreview-595960852
---

docs: tweak versions to 0.39, 0.41, master of launchpad/backports

---

docs/basics/app-anatomy.md
docs/cn/basics/app-anatomy.md

Change directory name '.appd' to '.app'.
closes: #XXXX
---

change dir '.appd' to '.app'

---

go.mod
go.sum

update tendermint to v0.34.8

---

.github/workflows/sims.yml
.github/workflows/tag.yml
.github/workflows/test.yml

build with go1.16

---

CHANGELOG.md

update changelog against v0.41.4

---

CHANGELOG.md
RELEASE_NOTES.md
x/evidence/types/evidence.go
x/evidence/types/evidence_test.go

Subsequent to merging, v0.42.0-rc0 should be tagged off of this commit.
closes: #8668 
---

v0.42.0-rc0 Release

---

docs/architecture/adr-041-in-place-store-migrations.md
x/bank/keeper/migrations.go
x/bank/legacy/v043/store.go
x/bank/legacy/v043/store_test.go
x/distribution/keeper/migrations.go
x/distribution/legacy/v043/helpers.go
x/distribution/legacy/v043/store.go
x/distribution/legacy/v043/store_test.go
x/gov/keeper/migrations.go
x/gov/legacy/v043/store.go
x/gov/legacy/v043/store_test.go
x/slashing/keeper/migrations.go
x/slashing/legacy/v043/store.go
x/slashing/legacy/v043/store_test.go
x/staking/keeper/migrations.go
x/staking/legacy/v043/store.go
x/staking/legacy/v043/store_test.go

After the shift of v0.42-> v0.43, all migration scripts should live in legacy/v043 folders, because that's the version where store migrations are needed.
---

Move all migration scripts to v043

---

server/test_helpers.go

server: wrap errors

---

.github/workflows/proto.yml

Allow proto CI to pass when no proto files changed

---

docs/.vuepress/config.js
docs/.vuepress/enhanceApp.js
docs/versions

closes https://github.com/allinbits/design/issues/400
closes: #XXXX
---

docs: update dropdown 0.41 → 0.42

---

docs/.vuepress/config.js

Ref: https://github.com/cosmos/cosmos-sdk/pull/8884
closes: #XXXX
---

docs: v0.42 version dropdown backport

---

docs/.vuepress/config.js
docs/.vuepress/enhanceApp.js
docs/versions

Ref: https://github.com/cosmos/cosmos-sdk/pull/8884
closes: #XXXX
---

docs: v0.39 version dropdown backport

---

CHANGELOG.md
RELEASE_NOTES.md

update changelog and RELEASE NOTES

---

x/auth/tx/service_test.go

exclude test from race detection

---

CHANGELOG.md

merge changelogs from v0.42.1 and v0.42.2

---

docs/architecture/adr-017-historical-header-module.md

Fix link to ICS2 on ADR017

---

docs/architecture/adr-015-ibc-packet-receiver.md

Two links changed to new IBC doc repo.
closes: #XXXX
---

Fix broken links to ICS26 in ADR015

---

docs/architecture/adr-026-ibc-client-recovery-mechanisms.md

Fix link to ICS007 on ADR026

---

docs/architecture/adr-003-dynamic-capability-store.md

Fix link to ICS005
closes: #XXXX
---

Fix broken links to ICS specs

---

x/bank/keeper/keeper.go
x/bank/keeper/keeper_test.go
x/staking/keeper/slash_test.go
x/staking/types/msg_test.go

Backport GHSA-2f3p-6gfj-jccq to v0.42.x.
Note, this is currently blocked on some IBC changes that are under review.
---

backport: GHSA-2f3p-6gfj-jccq

---

CHANGELOG.md
RELEASE_NOTES.md

finalise release changelog and notes

---

x/bank/keeper/keeper.go
x/bank/spec/02_keepers.md

ref: https://github.com/cosmos/cosmos-sdk/issues/8996
---

x/bank: doc & spec updates

---

.github/workflows/janitor.yml
.github/workflows/release-sims.yml
.github/workflows/sims.yml
.github/workflows/test.yml
crypto/armor.go

Fixes ci being cancelled randomly
closes: #XXXX
---

ci: add janitor

---

CHANGELOG.md
simapp/app.go
simapp/app_test.go
x/bank/app_test.go
x/bank/internal/keeper/keeper_test.go

backpoort GHSA-mvm6-gfm2-89xj

---

CHANGELOG.md
RELEASE_NOTES.md

launchpad: Finalize v0.39.3

---

Dockerfile

Remove plantuml install in docker. It isnt needed to run a node so we should avod installing it. 
closes: #XXXX
---

docker: remove plantuml install 

---

CHANGELOG.md

Update CHANGELOG with v0.42.3 & v0.42.4 stanzas

---

docs/package-lock.json
docs/package.json

docs: bump vuepress-theme-cosmos

---

x/authz/spec/01_concepts.md
x/authz/spec/README.md
x/feegrant/spec/01_concepts.md
x/feegrant/spec/README.md

This PR adds a section about gas consumption for x/authz & x/feegrant spec documentation. 
Related PRs: #8995 & #8604 
closes: #9068 
---

x/authz & x/feegrant: documentation for gas consumption

---

docs/pre.sh

Remove generation of plantuml docs to fix docs build. 
@hjorthjort will have to add a way to generate this and some docs. There should be a readme to the folder, or it should be moved out of docs. 
closes: #XXXX
---

docs: remove generation of plantuml docs

---

fuzz/oss-fuzz-build.sh
go.sum

fuzz: fix wrong path for fuzz/types packages

---

fuzz/types/parsecoin/fuzz.go

Since when ParseCoin was removed.
Updates #7921
---

fuzz/types/parsecoin: use ParseCoinNormalized

---

crypto/types/compact_bit_array.go
crypto/types/compact_bit_array_test.go

From: #9163
Closes: #9162
Thanks: @odeke-em for the patch.
---

crypto/types: check for overflow and unreasonably large element count

---

docs/README.md

the Quick Start Guide link is busted in https://github.com/cosmos/cosmos-sdk/blob/master/docs/README.md
how about we send folks to Starport? and fix a few minor editorial nits
closes: #XXXX
---

Update README.md to fix broken link to Quick Start Guide

---

fuzz/crypto/types/compactbitarray/marshalunmarshal/main.go
go.sum

Adds fuzzing for #9196
Updates #7921
Depends on #9196
---

fuzz/crypto: add {Get,Set}Index to compactbitarray fuzzing

---

docs/ibc/custom.md
docs/ibc/integration.md
docs/ibc/overview.md
docs/ibc/relayer.md

backport 0.42.x: Fix IBC doc links

---

x/staking/keeper/keeper.go

Removed unused container/list
closes: #XXXX
---

staking: remove unused list

---

go.mod
go.sum

bump IAVL to 0.16.0

---

x/bank/types/balance.go

The speed is the same as old implementation, but the new one uses slightly
less memory and make the code easier to maintain.
```
name                    old time/op    new time/op    delta
SanitizeBalances500-8      933µs ± 1%     935µs ± 1%     ~     (p=0.400 n=9+10)
SanitizeBalances1000-8    1.91ms ± 0%    1.92ms ± 0%   +0.58%  (p=0.000 n=10+10)
name                    old alloc/op   new alloc/op   delta
SanitizeBalances500-8      588kB ± 0%     556kB ± 0%   -5.41%  (p=0.000 n=9+9)
SanitizeBalances1000-8    1.18MB ± 0%    1.12MB ± 0%   -5.37%  (p=0.000 n=9+9)
name                    old allocs/op  new allocs/op  delta
SanitizeBalances500-8      5.02k ± 0%     4.02k ± 0%  -19.94%  (p=0.000 n=10+10)
SanitizeBalances1000-8     10.0k ± 0%      8.0k ± 0%  -19.93%  (p=0.000 n=9+10)
```
Fixes …

x/bank/types: use simpler implementation for sorting balance by address

---

baseapp/msg_service_router.go
x/authz/keeper/msg_server.go

Related to v0.43 API audit.
Rename: HandlerbyTypeURL -> HandlerByTypeURL
---

router: fix handler name

---

telemetry/metrics.go
telemetry/wrapper.go
version/command.go

v043 audit changes for telemetry/

---

CHANGELOG.md

Found a missing changelog entry for the addition of grpc-web support when auditing the server package for v0.43 (in #9218)
---

add CHANGELOG entry for grpc-web

---

x/evidence/spec/06_begin_block.md

just a few edits when I went to fix a typo
closes: #XXXX
---
- [x ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [x ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)

docs: minor edits and typo fix on 06_begin_block.md

---

docs/ibc/relayer.md

Added the ts-relayer to the implementations list in the documentation for relayers

docs: added the ts-relayer to the implementations list

---

types/module/module.go

Edits comment for `types/module/Manager#RegisterRoutes`. It looks like it was copy-pasted from `#RegisterRoutes`.
---
Most of these checkboxes are not applicable for obvious reasons.

types: fix godoc

---

simapp/README.md

This pull request updates the simapp instructions based on user feedback.
closes: #9365 
---

docs: update simapp instructions

---

simapp/simd/cmd/root.go

ref: https://github.com/cosmos/cosmos-sdk/issues/9407
The same change will need to be made against Gaia @shahankhatch.
---

fix: update simapp to use correct default broadcast mode

---

x/slashing/types/genesis.go

fix: typo in ValidateGenesis error message

---

client/broadcast.go

Closes: #XXXX
use the expected transaction hash from tendermint
---
I have...
I have...

fix:  update client error handling to use tx `Hash()` from Tendermint

---

docs/architecture/README.md

Closes: #XXXX
---
I have...
I have...

docs: Fix ADR 030 reference link

---

go.mod
go.sum

Bump tendermint verison
Closes: #XXXX
---
I have...
I have...

build(deps): tendermint version

---

CHANGELOG.md

0.42.5 and 0.42.6 have both been released. This PR forward-ports the Changelog updates to master.
---
I have...
I have...

chore: Update CHANGELOG with 0.42.5 and 0.42.6

---

x/bank/keeper/keeper_test.go

Ref: zero balance check for v0.43
---
I have...
I have...

test(bank): check that zero balances are deleted

---

cosmovisor/README.md

The pull request fixes the staking amount, adds the auto-restart option, and improves the user flow for the simd example. This pull request also fixes spelling and grammar, updates content for clarity, and applies consistent formatting.
---
I have...
I have...

docs: fix cosmovisor readme

---

.mergify.yml

Just in case we need to backport stuff for rc0
---
I have...
I have...

chore: Add mergify v0.43 backport

---

CHANGELOG.md

chore: add changelog entry for 9432

---

cosmovisor/README.md

Fix minor bug in cosmovisor readme
---
I have...
I have...

docs: Switch `on` to `true` in cosmovisor readme

---

client/flags/flags.go

Just a nit pick. Saw this while using the cli, thought I'd jump in and try to fix it.
---
I have...
I have...

fix: offline flag description.

---

x/gov/spec/01_concepts.md

Updating the spec to follow the implementation
ref: https://github.com/cosmos/cosmos-sdk/pull/9519#pullrequestreview-704117565
---
I have...
I have...

docs(gov): improve gov module spec

---

CHANGELOG.md

Not sure if we should add it as a new entry. Tentatively, I've added migration to the same item as the bug fix.

chore: added link to the state migration for zero balance prunning bug fix

---

CHANGELOG.md

chore: add missing bugfix (zero coins pruning) to the changelog

chore: add missing bugfix (zero coins pruning) to the changelog

---

docs/ibc/overview.md

Closes: #XXXX
---
I have...
I have...

fix broken link to IBC specs

---

CHANGELOG.md

ref: https://github.com/cosmos/cosmos-sdk/pull/9679#discussion_r667779885
---
I have...
I have...

chore: Add missing entry in 0.42.7 Changelog

---

docs/basics/app-anatomy.md

Fix typo in documentation, file app-anatomy.md
---
I have...
I have...

docs: Update app-anatomy.md

---

docs/basics/accounts.md

The digital key schemes table wasn't rendering correctly. This fix corrects the rendering.
Closes: #XXXX
---
I have...
- [N/A] provided a link to the relevant issue or specification
I have...

docs: Update accounts.md

---

proto/cosmos/group/v1beta1/query.proto
proto/cosmos/group/v1beta1/tx.proto
proto/cosmos/group/v1beta1/types.proto

Proto x/group files were not formatted. 
---
I have...
I have...

style: format x/group proto files

---

docs/core/upgrade.md

Not sure if this fix works, but currently the link takes you to a 404 at https://docs.cosmos.network/v0.43/v0.42/migrations/chain-upgrade-guide-040.html.
Don't we have 404 link checkers in the build process?
Why don't they detect this one?
Closes: #XXXX
---
I have...
I have...

broken link

---

docs/basics/app-anatomy.md

Change configued to configured under gRPC Query Services
Closes: #XXXX
---
I have...
I have...

fix: Update app-anatomy.md

---

Dockerfile

chore: Remove the redundant comma in Dockerfile

---

CHANGELOG.md

add missing changelog entry from #9859
---
I have...
I have...

chore: add missing changelog entry from #9859

---

cosmovisor/CHANGELOG.md
cosmovisor/README.md
cosmovisor/RELEASE_NOTES.md

Release Notes + Changelog
---
I have...
I have...

chore: prepare Cosmovisor v0.1.0 release

---

x/auth/spec/05_vesting.md

Closes: https://github.com/cosmos/cosmos-sdk/issues/9882
Add info about PermanentLockedAccount. Add info about MsgCreateVestingAccount.
---
I have...
I have...

docs: Fix vesting doc.

---

types/coin_benchmark_test.go

By padding coinName with number of digits of max coin size (1000).
Fixes #9903
---
I have...
I have...

test: fix BenchmarkCoinsAdditionIntersect panic

---

cosmovisor/testdata/download/cosmovisor/genesis/bin/autod
cosmovisor/testdata/repo/chain2-zip_bin/autod
cosmovisor/testdata/repo/ref_to_chain3-zip_dir.json
cosmovisor/upgrade_test.go

Closes: #9919
This pull request updates the location of the download binary used in cosmovisor tests.
---
I have...
I have...

fix: cosmovisor test download url

---

CHANGELOG.md
go.mod
go.sum

Bump Tendermint to v0.34.12 which addresses the egregious `ABCI#Query` log. 
ref: https://github.com/cosmos/cosmos-sdk/issues/9941
---
I have...
I have...

build(deps): bump TM to v0.34.12

---

cosmovisor/README.md
docs/migrations/chain-upgrade-guide-043.md

This pull request adds clarification to the upgrade guide and cosmovisor documentation around cosmovisor versions.
---
I have...
I have...

docs: clarify cosmovisor versions

---

RELEASE_NOTES.md

Closes: #XXXX
---
I have...
I have...

chore: remove incorrect EOL date for v0.42 in RELEASE_NOTES.md (release/v0.44.x)

---

x/simulation/simulate.go

Update `RequestInitChain` to include the genesis timestamp during simulations.
closes: #10075
---
I have...
I have...

fix: Update RequestInitChain in Simulations

---

x/feegrant/spec/05_client.md
x/feegrant/spec/README.md

Ref: #9707
Add `client.md` page to `feegrant` module spec.
---
I have...
I have...

docs: feegrant client spec

---

cosmovisor/README.md

Ref: #10137
Updating cosmovisor readme from feedback from PR #10137  
https://github.com/cosmos/cosmos-sdk/pull/10137#discussion_r710283543
https://github.com/cosmos/cosmos-sdk/pull/10137#discussion_r710285477
---
I have...
I have...

docs: updating cosmovisor readme

---

docs/README.md

minor edits while I was in here updating the Starport description, thanks
Closes: #XXXX
---
I have...
I have...

docs: update README for Starport description to match repo

---

CHANGELOG.md
RELEASE_NOTES.md
simapp/ante_handler.go
simapp/app.go
x/ibc/core/04-channel/types/errors.go
x/ibc/core/ante/ante.go

This is a backport of [#235](https://github.com/cosmos/ibc-go/pull/235) from the ibc-go repository. That PR implemented the rejection of redundant IBC transactions, which saves fees to relayers.
I have brought the ante decorator from ibc-go, but I didn't bright over the corresponding test file, since that would require bringing other dependencies of the ibc testing module that have been added to ibc-go in the meantime.
---
I have...
I have...

feat: backport reject redundant transactions from ibc-go

---

CHANGELOG.md
RELEASE_NOTES.md

Closes: #XXXX
---
I have...
I have...

chore: Changelog and Release Notes for 0.42.10

---

README.md

minor edits for consistent language for Starport and Cosmos SDK
Cosmos-SDK > Cosmos SDK
SDK > Cosmos SDK
add descriptive link text per https://developers.google.com/style/link-text
a few other (what I hope are) helpful edits for clarity
Closes: companion PR for https://github.com/cosmos/cosmos-sdk/issues/10180 
---
I have...
- [x ] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [x ] targeted the correct branch (see [PR Targeting](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [x ] provided a link to the relevant issue or …

docs:update README.md for Cosmos SDK consistent branding

---

cosmovisor/CHANGELOG.md
cosmovisor/README.md
cosmovisor/RELEASE_NOTES.md

chore: cosmovisor/v1.0.0 release notes

---

.github/workflows/cosmovisor-release.yml
cosmovisor/.goreleaser.yml

Closes: #10109
---
I have...
I have...

ci: setup cosmovisor goreleaser workflow

---

x/auth/middleware/basic.go

Ref: https://github.com/cosmos/cosmos-sdk/issues/10474
---
I have...
I have...

fix: middleware consumeTxSizeGas linting

---

crypto/keys/multisig/amino.go

Closes: #10042, amends fix of blocked PR #10113 to pass TestLegacyMultisig and ok with `make test`.
Modifies crypto/keys/multisig/amino.go
---
I have...
- [?] targeted the correct branch (see [PR Targeting](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
I have...

fix: TestLegacyMultisig test for #10042

---

docs/building-modules/module-manager.md
docs/intro/why-app-specific.md

Just some minor corrections I figured I'd fix while reading through the docs.
---
I have...
- I assumed minor doc fixes like this wouldn't need an issue.  Feel free to close the PR if not valuable. 👌🏻 
I have...

docs: Minor doc fixes

---

cosmovisor/README.md

We forgot to backport the filedump change from master to 0.44.x branch, so the autodownload doesn't work yet (until the next 0.44.x will be released)
---
I have...
I have...

doc: Update cosmosvisor README

---

.github/labeler.yml

Closes: #XXXX
---
I have...
I have...

ci: update labeler.yml

---

docs/architecture/adr-040-storage-and-smt-state-commitments.md

Fix typos and broken link in ADR-040.
---
I have...
I have...

docs: ADR-040: fix typos and broken link

---

docs/architecture/adr-033-protobuf-inter-module-comm.md

Just a typo. 
---
I have...
I have...

docs: Update adr-033-protobuf-inter-module-comm.md

---

CHANGELOG.md
x/auth/middleware/priority.go

Closes: #XXXX
---
I have...
I have...

chore: add changeling for priority 

---

docs/architecture/adr-044-protobuf-updates-guidelines.md

I've been telling people to add this `Since:` comment in some PRs, but noticed it's not documented anywhere. I updated the relevant PR from the conclusions of TX working group calls with @aaronc, @webmaster128 and myself.
---
I have...
I have...

docs(adr): Update protobuf guidelines with `Since`

---

docs/architecture/adr-045-check-delivertx-middlewares.md

Update ADR after we iterated on the code itself: #10527 
---
I have...
I have...

docs(adr): Update ADR-045 with new middleware interface

---

.mergify.yml

See deprecation message here: https://github.com/cosmos/cosmos-sdk/pull/10672/checks?check_run_id=4432872691
I simply followed this blog: https://blog.mergify.com/strict-mode-deprecation/
---
I have...
I have...

chore: Remove deprecated strict mode from mergify

---

CHANGELOG.md
client/tx/tx.go
server/rosetta/converter.go
simapp/helpers/test_helpers.go
x/auth/client/cli/tx_multisign.go
x/auth/client/cli/validate_sigs.go
x/auth/middleware/feegrant_test.go
x/auth/middleware/sigverify.go
x/auth/middleware/testutil_test.go
x/auth/middleware/tips_test.go
x/auth/migrations/legacytx/amino_signing_test.go
x/auth/signing/handler_map_test.go
x/auth/signing/sign_mode_handler.go
x/auth/signing/verify_test.go
x/auth/testutil/suite.go
x/auth/tx/aux_test.go
x/auth/tx/direct_aux.go
x/auth/tx/direct_aux_test.go
x/auth/tx/direct_test.go
x/auth/tx/legacy_amino_json_test.go

Closes: #10691 
---
I have...
I have...

refactor: Change SignerData.SignerIndex to PubKey

---

CHANGELOG.md
x/gov/types/content.go

The 5k character limit for governance proposals is something I've ran into several times now. This feels like an artificial constraint. The deposit is our mechanism to combat spam, and extra state used for this is really not a problem.
In this PR I propose raising this limit to 10k characters, to remove much of the immediate need for working around this 5k limit.
Closes: #XXXX
---
I have...
I have...

feat!: x/gov: raise max description length to 10k chars

---

client/keys/add.go

the command `gaiad keys add myKey --help` is printed as
```
--account uint32           Account number for HD derivation
--index uint32             Address index number for HD derivation
```
and it's not obvious that uint32 cannot accept its max value.
https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki#extended-keys
Please close this if it is not required, request changes if there is better way to do this.
---
I have...
I have...

chore(cli): Update keys add help message

---

Makefile
contrib/images/simd-env/Dockerfile

Closes: #10764 
---
I have...
I have...

fix(CI): `make localnet-start`

---

errors/go.mod

Small fix to #10779 so that I can tag and update go.mod's.
---
I have...
I have...

fix: errors go.mod has wrong module path

---

docs/core/grpc_rest.md

Spelling fix at line 41.
Closes: #XXXX
---
I have...
I have...

fix: Minor typo

---

proto/cosmos/group/v1beta1/events.proto

Closes: #XXXX
---
I have...
I have...

chore: fix group events proto

---

CHANGELOG.md

The changelog for #10529 links to the wrong PR. This commit will change the link to point it to the correct PR
---
I have...
I have...

fix: fixed an incorrect PR link for #10529

---

CHANGELOG.md
RELEASE_NOTES.md

chore: release v0.45 changelog

---

cosmovisor/go.mod
cosmovisor/go.sum
x/group/go.mod
x/group/go.sum

0.45 vs released, so we can bump cosmos-sdk dep in submodules.
---
I have...
I have...

chore: bump submodules cosmo-sdk dep

---

x/slashing/README.md

docs: Fix broken link in Slashing module

---

x/bank/keeper/send.go

performance boost as this is one of the most commonly emitted events
---
I have...
I have...

perf:  Deduplicate bech32 encoding in bank send events

---

orm/encoding/ormkv/key_codec.go
orm/internal/codegen/file.go
orm/internal/codegen/singleton.go
orm/internal/codegen/table.go

I've tested this locally running codegen and this PR changes this error message:
```
panic: nil field: unsupported key field
goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/orm/internal/codegen.newTableGen({0xc00000d938, 0xc0003c4100}, 0xc0003c0c60, 0xc0002d4c80)
/Users/arc/go/pkg/mod/github.com/cosmos/cosmos-sdk/orm@v1.0.0-alpha.3/internal/codegen/table.go:47 +0x3e5
github.com/cosmos/cosmos-sdk/orm/internal/codegen.fileGen.gen({0xc00000d938, 0xc0003c4100})
/Users/arc/go/pkg/mod/github.com/cosmos/cosmos-sdk/orm@v1.0.0-alpha.3/internal/codegen/file.go:32 +0x205
github.com/cosmos/cosmos-sdk/orm/internal/codegen.PluginRunner(0xc000137cc0)
/Users/arc/go/pkg/mod/github.com/cosmos/cosmos-sdk/orm@v1.0.0-alpha.3/internal/codegen/codegen.go:40 +0x159 …
```

fix(orm): bad error messages

---

orm/model/ormtable/table_impl.go
orm/model/ormtable/table_test.go
orm/model/ormtable/testdata/test_scenario.golden

fix `Table.Delete` method broken in #11103 
---
I have...
I have...

fix(orm): fix broken Table.Delete method

---

x/nft/keys.go
x/nft/msgs.go
x/nft/simulation/operations.go
x/nft/validation.go

Fix warnings in comments/documentation of nft module
---
I have...
I have...

chore: fix warnings in comments/documentation of nft module

---

orm/model/ormdb/json.go
orm/model/ormdb/module_test.go

Closes: #XXXX
---
I have...
I have...

fix(orm): ValidateJSON fails when tables are missing

---

CHANGELOG.md
baseapp/abci.go
types/errors/abci.go

backport #9576
---
I have...
I have...

feat!: support debug trace QueryResult (backport #9576)

---

x/authz/keeper/migrations.go
x/authz/migrations/v046/keys.go
x/authz/migrations/v046/keys_test.go
x/authz/migrations/v046/store.go
x/authz/migrations/v046/store_test.go

Closes: #XXXX
---
I have...
I have...

chore(authz): rename migrations v045 -> v046

---

docs/core/runtx_middleware.md
docs/core/store.md

Closes: #11235 
can't use relative links to files not within the docs folder. 
---
I have...
I have...

chore: move from relative links to git links

---

CHANGELOG.md

Closes: #XXXX
---
I have...
I have...

chore: fix changelog entry for #11177

---

CHANGELOG.md

add the changelog which is missing from the original PR.
---
I have...
I have...

Add missing changelog for state sync hooks feature

---

.github/workflows/docker.yml

GitHub asks users to define workflow permissions, see https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/ and https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token for securing GitHub workflows against supply-chain attacks.
StepSecurity is working on securing GitHub workflows and [OSSF Scorecards](https://github.com/ossf/scorecard) recommends using StepSecurity's secure-workflows online tool [app.stepsecurity.io](app.stepsecurity.io) to improve the security of GitHub workflows.
This repository has a Scorecards score of 6.3/10 with 10 being the most secure. The `Token-Permissions` category has a score of 0/10.
We have fixed one of the repo's workflows for you by adding …

fix: permissions for docker.yml

---

client/flags/flags.go
client/tx/factory.go
x/auth/client/cli/tips.go
x/auth/client/testutil/suite.go

Closes: #11321 
---
I have...
I have...

fix: Remove `--tipper` flag, set it to msg signer

---

.github/workflows/codeql-analysis.yml

Closes: #XXXX
---
I have...
I have...

ci: fix codeql

---

types/errors/doc.go
types/errors/errors.go

Closes: #11379
I have...
I have...

chore: deprecate types/errors aliases

---

.github/workflows/proto-docker.yml
Makefile
api/cosmos/feegrant/v1beta1/feegrant.pulsar.go
api/cosmos/feegrant/v1beta1/tx.pulsar.go
contrib/devtools/dockerfile

Closes: #11405
---
I have...
I have...

chore: fix proto docker

---

x/staking/spec/02_state_transitions.md

Closes: #11350 
---
I have...
I have...

docs: update `x/staking` begin unbonding docs

---

x/group/keeper/invariants.go
x/group/keeper/keeper.go
x/group/keeper/tally.go
x/group/proposal_test.go

Closes: #XXXX
---
I have...
I have...

fix: Try fix group sims issue

---

SECURITY.md

Fixed: https://hackerone.com/cosmos
Closes: #XXXX
---
I have...
I have...

fix: Broken HackerOne program link

---

x/bank/spec/README.md

MultiSend ref to bank/spec/README.md
Messages.md was missing reference to multisend
---
I have...
- [ x ] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ x ] added `!` to the type prefix if API or client breaking change
- [ x ] targeted the correct branch (see [PR Targeting](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [ x ] followed the guidelines for [building modules](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules) …

docs: Update MultiSend ref to bank/spec/README.md

---

.github/labeler.yml
.mergify.yml

We just created the `release/v0.46.x` branch. This PR adds mergify backport commands.
---
I have...
I have...

chore: Add mergify backport to v0.46.x

---

proto/cosmos/distribution/v1beta1/tx.proto

Added `since:` comment to changes in #11457 as requested by @amaurym

chore: add proto since: comments for #11457 updates to reward withdrawal responses

---

CHANGELOG.md
RELEASE_NOTES.md

Closes: #XXXX
---
I have...
I have...

chore: v0.44.7 release notes

---

CHANGELOG.md
RELEASE_NOTES.md

Wait for:
---
I have...
I have...

chore: v0.45.2 Release Notes

---

.github/workflows/deploy-docs.yml
.gitignore
Makefile
docs/output/CNAME

Set the `output` folder for building the docs back in `~` as it was being overwritten by each version build (effectively only keeping the latest).
---
I have...
I have...

ci: fix gh docs action

---

docs/versions

Small typo in the version file where there should only be *one* newline.
---
I have...
I have...

docs: versions should have only one new line

---

.github/workflows/sims.yml

removes git_diff check, it wasn't needed anymore
---
I have...
I have...

chore: remove git_diff check

---

CHANGELOG.md

Updates the changelog with the minors changes from `0.45` and `0.44`.
---
I have...
I have...

docs: update changelog with minors changes from `0.45` and `0.44`

---

CHANGELOG.md

Release notes for the v0.45.4 release.
---
I have...
I have...

chore: v0.45.4 release notes

---

proto/cosmos/bank/v1beta1/query.proto

I'm writing a parser and this extra semi-colon is causing issues. All else works great :)

chore: remove extra semi-colon

---

Makefile
docs/.vuepress/enhanceApp.js
docs/versions

Closes #11780 
---
I have...
I have...

docs: Fix master to main redirect

---

errors/abci_test.go
errors/errors_test.go
errors/go.mod
errors/stacktrace.go
errors/stacktrace_test.go
go.mod
go.sum
orm/go.mod
orm/go.sum
orm/model/ormdb/json.go
orm/model/ormtable/table_test.go
orm/types/ormerrors/errors.go
types/errors/doc.go
types/errors/errors.go

- Update the module path for the `errors` sub-module to `cosmossdk.io/errors`
- Pushed `errors/v1.0.0-beta.6` tag with updated module path
---
I have...
I have...

chore: update errors sub-module module path

---

.github/workflows/deploy-docs.yml

Docs are only rebuilt when there is change in the `docs` folder. However, there can be some documentation changes that does not happen in the `docs` folder (https://github.com/cosmos/cosmos-sdk/blob/main/docs/pre.sh).
---
I have...
I have...

ci: rebuild documentation on module doc change

---

codec/types/any_test.go

Disable `TestNewAnyWithCustomTypeURLWithErrorNoAllocation` until it's resolved as it's becoming very annoying to constantly rerun CI jobs due to this one test failing.
cc @odeke-em 
---
I have...
I have...

chore: disable TestNewAnyWithCustomTypeURLWithErrorNoAllocation

---

docs/core/transactions.md

Closes: #10426 
---
I have...
I have...

docs: Add docs for SIGN_MODE_DIRECT_AUX

---

CHANGELOG.md

Just a missing changelog entry from an already merged PR
Closes: #11726
---
I have...
I have...

chore: add missing changelog entry for #11737

---

docs/run-node/interact-node.md

Today, I'm going to use Go gRPC to interact with Cosmos SDK, but it is frustrating, the doc is totally outdated. I updated the doc while solving the problems.
---
I have...
I have...

docs: Update Go gRPC client usage

---

README.md

Closes: #11878
---
I have...
I have...

chore: remove latest version tag from README

---

x/mint/spec/03_begin_block.md

Closes: #11919
---
I have...
I have...

docs: document x/mint InflationCalculationFn

---

testutil/network/doc.go

I noticed the docs were outdated so I updated them. The referenced directory "testutil" has changed to "network"
---
I have...
I have...

chore: update testutil network docs

---

api/cosmos/orm/v1/orm.pulsar.go
api/cosmos/staking/v1beta1/query.pulsar.go
go.mod
go.sum
x/staking/types/query.pb.go

Closes: #11906
- Update dep to tag
- Re-execute `make proto-gen`
---
I have...
I have...

chore: update cosmossdk.io/api mod

---

x/gov/client/cli/tx.go
x/gov/simulation/decoder_test.go
x/gov/types/v1beta1/msgs_test.go
x/gov/types/v1beta1/proposal.go
x/gov/types/v1beta1/proposals_test.go

Closes: #11963
---
I have...
I have...

fix: make `submit-legacy-proposal` --type field not case-sensitive

---

.github/workflows/lint.yml
.github/workflows/release-sims.yml
.github/workflows/sims.yml
.github/workflows/test-race.yml
.github/workflows/test.yml

Disables changes introduced in https://github.com/cosmos/cosmos-sdk/pull/12043 until they can be resolved...
---
I have...
I have...

chore: disable build CI cache

---

x/gov/spec/01_concepts.md

Grammar fix: "casted" should be "cast"
- https://pasttenses.com/cast-past-tense
- https://writingexplained.org/cast-vs-casted
/x/gov/spec/01_concepts.md grammar fix: "casted" should be "cast"
See:
- https://pasttenses.com/cast-past-tense
- https://writingexplained.org/cast-vs-casted
---
I have...
- [X ] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ X] added `!` to the type prefix if API or client breaking change
- [] followed the guidelines for [building modules](https://github.com/cosmos/cosmos-sdk/blob/main/docs/building-modules)
*All items are required. Please …

docs: grammar fix in /x/gov/spec/01_concepts.md

---

.github/workflows/sims.yml

Closes: #XXXX
---
I have...
I have...

chore: add success slack message to sim testing

---

CHANGELOG.md

Add breaking changes to `CHANGELOG.md` 
Now keeper is passed as a reference, not a copy. 
Keeper set hooks no longer return a keeper, but change the keeper in place. 
reference: #12102 
Closes: #XXXX
---
I have...
I have...

fix: added breaking change in staking keeper api

---

fuzz/oss-fuzz-build.sh

test: update OSS-Fuzz build script for Go 1.18

---

CHANGELOG.md
x/crisis/keeper/keeper.go

the info log messages describing invariant checks use the index to state
progress (eg. `asserting crisis invariants inv=0/15`). this simple change
makes them 1-indexed (eg. `asserting crisis invariants inv=1/15`).
example before:
Closes: #XXXX
---
I have...
I have...

fix: update index of crisis invariant check logs

---

CHANGELOG.md
x/auth/vesting/msg_server.go

This is actually state-machine breaking, so reverting this...

Revert "fix: add base account getter (backport #12154)"

---

CHANGELOG.md
RELEASE_NOTES.md

Prepares the release notes + changelog for the v0.45.5 point release.
---
I have...
I have...

chore: v0.45.5 release notes + CL

---

x/mint/keeper/grpc_query_test.go
x/mint/keeper/querier_test.go
x/mint/module_test.go
x/mint/simulation/decoder_test.go
x/mint/spec/01_concepts.md
x/mint/testutil/app_config.go

Closes: #12234
---
I have...
I have...

feat: decouple `x/mint` from simapp

---

x/auth/spec/05_vesting.md

Fixes the code link under `### PermanentLockedAccount` to reference the `PermanentLockedAccount` message (instead of the `PeriodicVestingAccount` message).
---
I have...
I have...

docs: Fix vesting spec PermanentLockedAccount message code link

---

.github/workflows/proto.yml

This GH action always fails on main, while passing on the pull requests: https://github.com/cosmos/cosmos-sdk/actions/workflows/proto.yml
This is an attempt to fix that.
---
I have...
I have...

ci: remove proto breakage check action on main

---

simapp/helpers/test_helpers.go

`DefaultGenTxGas = 1000000` raises an error in some simulation case.
it was fixed in main branch but hasn't applied at 0.45.x.
I use cosmos sdk v0.45.5 but my project's simulation raise an error like below.
```go
simulate.go:300: error on block  19/100, operation (121/655) from x/staking:
out of gas in location: WritePerByte; gasWanted: 1000000, gasUsed: 1012350: out of gas [cosmos/cosmos-sdk@v0.45.5-0.20220523154235-2921a1c3c918/baseapp/recovery.go:55]
Comment: unable to deliver tx
```
---
I have...
your handle next to the items reviewed if you only reviewed …

fix: defaultGenTxGas to 10 times

---

README.md

**Changed files:**
* README.md
**Scope of the changes:**
Update link to Ignite CLI's repo.
---
I have...
I have...

docs(readme): update link to Ignite CLI

---

server/grpc/server.go

ref: #12357 
---
I have...
I have...

fix: register codec with grpc server

---

depinject/binding_test.go
depinject/errors.go
simapp/app.go
x/auth/tx/module/module.go
x/auth/tx/service_test.go
x/authz/keeper/grpc_query.go
x/bank/simulation/genesis.go
x/bank/types/params.go
x/distribution/abci_test.go
x/group/keeper/keeper_test.go
x/group/module/abci_test.go
x/nft/keeper/nft_batch_test.go
x/nft/simulation/operations.go

Recently we wrote an "every release" fumpt policy.  I use it quite intensely in my workflow and eh-- I guess all I can say is feel free to let me know if submitting these semi routinely is too obsessive.  I also did not add a changelog entry.  Basically, per my workflow, the sdk is now "green".  Happy to feedback/convo on this.
Thanks!
---
I have...
I have...

chore: fumpt

---

simapp/params/weights.go
x/feegrant/basic_fee_test.go
x/feegrant/client/testutil/cli_test.go
x/feegrant/client/testutil/suite.go
x/feegrant/filtered_fee_test.go
x/feegrant/grant_test.go
x/feegrant/keeper/genesis_test.go
x/feegrant/keeper/grpc_query_test.go
x/feegrant/keeper/keeper_test.go
x/feegrant/keeper/msg_server_test.go
x/feegrant/migrations/v046/store_test.go
x/feegrant/module/abci_test.go
x/feegrant/module/module.go
x/feegrant/periodic_fee_test.go
x/feegrant/simulation/decoder_test.go
x/feegrant/simulation/genesis_test.go
x/feegrant/simulation/operations.go
x/feegrant/simulation/operations_test.go
x/feegrant/testutil/app.yaml
x/feegrant/testutil/app_config.go

Closes: #12073
---
I have...
I have...

chore: decouple x/feegrant and simapp

---

x/feegrant/spec/01_concepts.md

There is an error in the description of the `period` for the feegrant `PeriodicAllowance` allowance type. After each period passes the `period_can_spend` is updated, not the `period_spend_limit`; the `period_spend_limit` should not change for the life of the grant.
Closes: #XXXX
---
I have...
I have...

docs: correct period description in PeriodicAllowance

---

simapp/app.go

Removes a leftover from the middleware implementation in v0.46 `app.go`.
---
I have...
I have...

refactor: remove `indexEventsStr` from `setAnteHandler`

---

CHANGELOG.md
simapp/helpers/test_helpers.go
simapp/test_helpers.go
x/authz/simulation/operations.go
x/bank/simulation/operations.go
x/distribution/simulation/operations.go
x/genutil/gentx_test.go
x/gov/simulation/operations.go
x/simulation/util.go
x/slashing/simulation/operations.go
x/staking/simulation/operations.go

backport of pull request #12374 
---
I have...
I have...

fix: Simulation is not deterministic due to GenTx (backport #12374)

---

.github/workflows/test.yml
contrib/devtools/Makefile

v0.45 has upgraded to go 1.18. Sims are now failing because `go get` is deprecated for installing package in go 1.18.
This PR fixes the Makefile.
(See #11708)
---
I have...
I have...

fix: use go install instead of go get in makefile

---

CHANGELOG.md

Fixes changelog migration links
---
I have...
I have...

fix: link in rest migration is wrong

---

x/staking/exported/exported.go
x/staking/keeper/migrations.go
x/staking/migrations/v3/keys.go
x/staking/migrations/v3/store.go
x/staking/migrations/v3/store_test.go
x/staking/migrations/v4/json.go
x/staking/migrations/v4/json_test.go
x/staking/migrations/v4/keys.go
x/staking/migrations/v4/migrations_test.go
x/staking/migrations/v4/store.go
x/staking/module.go

Closes: #XXXX
---
I have...
I have...

temporal commit

---

CHANGELOG.md

ref: #11096 
---
I have...
I have...

chore: Add Changelog for v0.46.0-rc3

---

api/cosmos/group/module/v1/module.pulsar.go
api/cosmos/tx/module/v1/module.pulsar.go
client/v2/internal/testpb/query.proto
core/internal/testpb/test.proto
orm/internal/testpb/bank.proto
orm/internal/testpb/test_schema.proto
proto/cosmos/auth/v1beta1/query.proto
proto/cosmos/auth/v1beta1/tx.proto
proto/cosmos/bank/v1beta1/tx.proto
proto/cosmos/base/snapshots/v1beta1/snapshot.proto
proto/cosmos/base/tendermint/v1beta1/query.proto
proto/cosmos/base/tendermint/v1beta1/types.proto
proto/cosmos/crypto/keyring/v1/record.proto
proto/cosmos/group/module/v1/module.proto
proto/cosmos/group/v1/types.proto
proto/cosmos/staking/v1beta1/tx.proto
proto/cosmos/tx/module/v1/module.proto
proto/cosmos/tx/signing/v1beta1/signing.proto
proto/cosmos/tx/v1beta1/service.proto

This is a simple run of make proto-all, AKA #11453 exposes **all the technical debts**. <3
---
I have...
I have...

make proto-all

---

.github/workflows/deploy-docs.yml
docs/.vuepress/config.js
docs/DOCS_README.md
docs/ko/README.md
docs/ru/README.md
docs/versions
docs/zh/README.md

Quick PR for little nits on the `docs.cosmos.network`.
I have been looking at https://github.com/cosmos/vuepress-theme-cosmos/blob/develop/layouts/GlobalLayout.vue, as it would be nice to have a banner that warns users when they are on the `main` branch documentation. Unfortunately, the banner is hard-coded to display https://v1.cosmos.network/top-banner/index.json...
I've used the trick to put the default version at the end of the `versions` file instead, and created https://github.com/cosmos/vuepress-theme-cosmos/issues/359.
Note: when backporting `docsBranch: "main"` should be changed to the correct branch.
---
I have...
*All items are required. …

docs: improve docs

---

CHANGELOG.md
go.mod
go.sum

Closes: #XXXX
---
I have...
I have...

chore: Bump to Tendermint v0.34.20

---

x/params/client/testutil/grpc.go
x/params/client/testutil/suite.go

Closes: #XXXX
---
I have...
I have...

Add "foo" subspace in x/params CLI test

---

CHANGELOG.md
docs/CosmWasm/README.md
x/README.md

Closes: N/A — I did not find an exact issue for this small contribution.
This is a very small contribution that adds CosmWasm to the sidebar of the documentation page and the **List of Modules** section.
For newcomers to the ecosystem, it may be difficult to find the resources to begin writing smart contracts on Cosmos blockchains. While there is very little detail here (I followed a pattern I saw with the IBC page, which is basically a stub but will be helpful in linking to external resources) I believe we need to have "smart contract" searchable by Algolia and the browser's "find in page" utility. So this PR is basically directing traffic for smart contract builders, who we know and love.
---
please …

docs: add cosmwasm to the sidebar and modules section

---

store/streaming/constructor_test.go

Removes a trivial simapp dependency from `store/`.
---
I have...
I have...

refactor: remove dependency on simapp from store test

---

x/README.md

Added mention to the NFT module in the readme in the x folder
Closes: #XXXX
Added mention to the NFT module in the readme in the x folder
---
I have...
- [x ] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ x] added `!` to the type prefix if API or client breaking change
- [ x] targeted the correct branch (see [PR Targeting](https://github.com/cosmos/cosmos-sdk/blob/main/CONTRIBUTING.md#pr-targeting))
- [ x] followed the guidelines for [building modules](https://github.com/cosmos/cosmos-sdk/blob/main/docs/building-modules)
- [ x] included the necessary unit and …

docs: mention NFT in module README 

---

Makefile
api/cosmos/staking/v1beta1/tx_grpc.pb.go
tx/textual/internal/testpb/1.proto
x/staking/types/tx.pb.go

The remote protos in the makefile were quite old.  This changes their version numbers in the makefile and remakes the protos & .pb.go files for the sdk. 
I have...
I have...

fix: make proto-all & update versions for main

---

x/bank/spec/README.md

docs: fix grammar

---

simapp/test_helpers.go

fix the error
```
simapp/test_helpers.go:27:2: ST1019: package "github.com/cosmos/cosmos-sdk/server/types" is being imported more than once (stylecheck)
"github.com/cosmos/cosmos-sdk/server/types"
^
simapp/test_helpers.go:28:2: ST1019(related information): other import of "github.com/cosmos/cosmos-sdk/server/types" (stylecheck)
servertypes "github.com/cosmos/cosmos-sdk/server/types"
```
---
I have...
I have...

fix: duplicate import

---

docs/run-node/txs.md

">" generate a blank file without the output better use --output-document
Closes: #XXXX
---
I have...
I have...

docs: ">" command isn't working properly

---

.github/workflows/lint.yml
CHANGELOG.md

We weren't checking out the code before asking for the diff, so CI could never run golangci-lint
---
I have...
I have...

ci: check out before calling technote/diff

---

.github/workflows/codeql-analysis.yml
.github/workflows/cosmovisor-release.yml
.github/workflows/e2e.yml
.github/workflows/legacy-test.yml
.github/workflows/lint.yml
.github/workflows/release.yml
.github/workflows/sims-045.yml
.github/workflows/sims-046.yml
.github/workflows/sims.yml
.github/workflows/test.yml
Dockerfile
contrib/images/simd-dlv/Dockerfile
contrib/images/simd-env/Dockerfile
contrib/rosetta/rosetta-ci/Dockerfile
contrib/rosetta/rosetta-cli/Dockerfile
simapp/app_legacy.go

Reverts cosmos/cosmos-sdk#12865
reverting cause it seems like something is broken with 1.19

Revert "update-ci-only"

---

x/staking/spec/06_hooks.md

Wasn't listed in the hooks section.
Closes: #XXXX
---
I have...
I have...

docs: add AfterDelegationModified x/staking hook

---

CHANGELOG.md
crypto/keyring/keyring.go
go.work.sum

https://github.com/cosmos/cosmos-sdk/pull/12455#issue-1294490355

feat: display attempts left in keyring passphrase prompt 

---

api/go.mod
api/go.sum
client/v2/go.mod
client/v2/go.sum
core/go.mod
core/go.sum
cosmovisor/go.mod
cosmovisor/go.sum
db/go.mod
db/go.sum
errors/go.mod
errors/go.sum
go.work.sum
orm/go.mod
orm/go.sum
store/tools/ics23/go.mod
store/tools/ics23/go.sum
types/events.go

- Fixes the linting issues introduced in https://github.com/cosmos/cosmos-sdk/pull/12781 (now that golangci is required)
- Run `go work sync`
---
I have...
I have...

chore: `go work sync` & `gofumpt`

---

CHANGELOG.md

Closes: #XXXX
---
I have...
I have...

chore: resolve conflict in #12781

---

CHANGELOG.md

Closes: #XXXX
---
I have...
I have...

resolve conflict

---

CHANGELOG.md

Closes: #12940 
---
I have...
I have...

chore: fix pr number changelog

---

go.mod
go.sum

Remove temporary replace that was added in #12958.
---
I have...
I have...

chore: remove temporary replace

---

README.md

- Links Awesome Cosmos Repo
- Wording
- Links to docs.cosmos.network instead of markdown files
---
I have...
I have...

docs: small readme tweaks

---

CHANGELOG.md
docs/basics/gas-fees.md

- https://github.com/cosmos/cosmos-sdk/pull/12958#discussion_r950781280
- Clean-up the unnecessary escaping of issue.
---
I have...
I have...

docs: remove unreleased tendermint upgrades from changelog

---

Makefile

Doing this to 45 and 46, because this will make merges easier.
---
I have...
I have...

chore: Update Makefile v46

---

fuzz/oss-fuzz-build.sh

fix(fuzz): fix OSS-Fuzz build

---

.github/workflows/deploy-docs.yml

Follow-up of #13143
`csplit` does not exist in https://hub.docker.com/r/tendermintdev/docker-website-deployment
See https://github.com/cosmos/cosmos-sdk/runs/8188475166?check_suite_focus=true
---
I have...
I have...

ci: add `csplit` for documetation building

---

.github/workflows/deploy-docs.yml

Use ghcr.io/cosmos/website-deployment image for building website.
---
I have...
I have...

ci: use ghcr.io cosmos website-deployment image

---

.github/workflows/deploy-docs.yml

Turns out the documentation is still not being built.
This PR investigates why.
---
I have...
I have...

ci: fix deploying action

---

.github/workflows/sims-045.yml
.github/workflows/sims-046.yml
.github/workflows/sims.yml
crypto/ledger/ledger_real.go

Fixes failing sims.
---
I have...
I have...

ci: fix sims gh actions and build error

---

CHANGELOG.md
x/group/client/cli/tx.go

Group's `withdraw-proposal` cmd was not added to the group module's CLI tx cmds. This PR adds it.
Closes: #13213 
ref: #10893
---
I have...
I have...

fix: Add withdraw proposal cmd to group's CLI tx cmds

---

.github/workflows/sims-045.yml
.github/workflows/sims-046.yml
.github/workflows/sims.yml

Apparently, we need to check out the repository for the sims success step:
https://github.com/cosmos/cosmos-sdk/runs/8261161326?check_suite_focus=true
---
I have...
I have...

ci: fix sims success messages

---

.github/workflows/proto-docker.yml

Closes: #XXXX
---
I have...
I have...

chore: add platforms to docker deploy

---

.github/workflows/docker.yml
Dockerfile
x/staking/client/cli/query_test.go
x/staking/client/cli/tx_test.go

Closes: #12424
---
I have...
I have...

chore: build docker without build-linux

---

CHANGELOG.md

Closes: #XXXX
---
I have...
I have...

chore: add changelog entries for previous versions

---

.github/workflows/gosec.yml

Closes: #XXXX
---
I have...
I have...

ci: use native paths instead of get-diff-action

---

README.md
x/staking/README.md

Fix typos
---
I have...
I have...

docs: fix typos

---

CHANGELOG.md
UPGRADING.md

Closes: #XXXX
quick pr that:
- adds `0.46.1` in the main changelog (and remove the corresponding issues from unreleased)
- improve upgrading.md sections
---
I have...
I have...

docs: improve changelog and upgrading.md sections

---

x/staking/keeper/unbonding.go
x/staking/keeper/unbonding_test.go
x/staking/types/keys.go

@marbar3778 @alexanderbez Here is a solution to your changes requested [here](https://github.com/cosmos/cosmos-sdk/pull/13122/files#r963837156). I think it's reasonably complete, but it is untested since you seem to have commented out all the unit tests. Putting this PR in so you can take a look.

chore: Add UnbondingType index to know which type of unbonding to deserialize to

---

api/cosmos/base/store/v1beta1/commit_info.pulsar.go
api/cosmos/base/tendermint/v1beta1/query.pulsar.go
api/cosmos/distribution/v1beta1/genesis.pulsar.go
api/cosmos/distribution/v1beta1/query.pulsar.go
api/cosmos/gov/v1beta1/genesis.pulsar.go
api/cosmos/group/v1/types.pulsar.go
api/tendermint/crypto/proof.pulsar.go
proto/cosmos/base/store/v1beta1/commit_info.proto
proto/cosmos/base/tendermint/v1beta1/query.proto
proto/cosmos/distribution/v1beta1/genesis.proto
proto/cosmos/distribution/v1beta1/query.proto
proto/cosmos/gov/v1beta1/genesis.proto
proto/cosmos/group/v1/types.proto
proto/tendermint/crypto/proof.proto
x/bank/keeper/deterministic_test.go

Closes: #13413
Fixed some spelling mistakes from comments.
---
I have...
I have...

docs: fixed spelling mistakes

---

baseapp/abci.go

Closes: #XXXX
---
I have...
I have...

docs: improve ABCI 1.0 godocs

---

UPGRADING.md

Closes: #XXXX
---
I have...
I have...

docs: update new modules in 0.46 UPGRADING.md

---

proto/cosmos/tx/v1beta1/service.proto

Closes: #13439
---
I have...
I have...

fix: remove extra `;` in `service.proto`

---

.github/workflows/staticmajor.yml
CHANGELOG.md

Closes: #XXXX
---
I have...
I have...

chore: add `v0.46.2` in main changelog

---

tests/go.mod
tests/integration/staking/keeper/unbonding_test.go
x/staking/README.md
x/staking/keeper/delegation.go
x/staking/keeper/params.go
x/staking/keeper/unbonding.go
x/staking/keeper/unbonding_test.go
x/staking/keeper/val_state_change.go
x/staking/keeper/validator.go
x/staking/types/delegation.go
x/staking/types/keys.go
x/staking/types/params_test.go

Start fixing the tests of #13122.
---
I have...
I have...

fix: fix IS tests

---

server/grpc/gogoreflection/fix_registration.go

Closes: #XXXX
---
I have...
I have...

chore: fix linting

---

client/tendermint.go

IBC-go uses Commit like:
```go
// QueryTendermintHeader takes a client context and returns the appropriate
// tendermint header
func QueryTendermintHeader(clientCtx client.Context) (ibctm.Header, int64, error) {
node, err := clientCtx.GetNode()
if err != nil {
return ibctm.Header{}, 0, err
}
info, err := node.ABCIInfo(context.Background())
if err != nil {
return ibctm.Header{}, 0, err
}
var height int64
if clientCtx.Height != 0 {
height = clientCtx.Height
} else {
height = info.Response.LastBlockHeight
}
commit, err := rpcclient.Commit(context.Background(), &height)
if err != nil {
return ibctm.Header{}, 0, err
}
page := 1
count := 10_000
validators, err := node.Validators(context.Background(), &height, &page, &count)
if err != nil {
return ibctm.Header{}, 0, err
}
protoCommit := commit.S …
```

fix: Update tendermint rpc client support for ibc-go compatibility

---

.github/workflows/project.yml

automate adding the pr to the project board

chore:  project automation

---

docs/docs/cosmwasm/_category_.json
docs/docs/ecosystem/README.md
docs/docs/ecosystem/_category_.json
docs/docs/ibc/README.md

merge cosmwasm and ibc sections into ecosystem section. A place where teams can post modules they have developed 
---
I have...
I have...

docs: create ecosystem section

---

docs/architecture/adr-050-sign-mode-textual-annex2.md
docs/architecture/adr-050-sign-mode-textual.md

Refs: #11970
Minor fixups to architecture docs. No major semantic changes are intended.
---
I have...
I have...

docs: Textual ADR minor fixes

---

server/start.go
simapp/simd/cmd/root.go

Follow up  on https://github.com/cosmos/cosmos-sdk/pull/13653
Adds (back) `iavl-disable-fastnode` flag to cmd, fix the description and rename the confusing variable name to `FlagDisableIAVLFastNode`
---
I have...
I have...

feat(cli): Add iavl-disable-fastnode cmd flag with proper description

---

types/mempool/mempool_test.go
types/mempool/nonce_test.go

Just cleans up the mempool tests from just merged #13645 to address merged conflicts in #13262 and overall improve the organization of test files.
---
I have...
I have...

chore: cleanup mempool tests

---

CHANGELOG.md
go.mod
go.sum

Manually bump iavl 0.19.4 in v0.45.x
---
I have...
I have...

build(deps): Bump github.com/cosmos/iavl from 0.19.3 to 0.19.4

---

Makefile
client/v2/internal/testpb/query.proto
orm/internal/testpb/bank_query.proto
orm/internal/testpb/test_schema_query.proto
proto/cosmos/auth/v1beta1/query.proto
proto/cosmos/bank/v1beta1/query.proto
proto/cosmos/distribution/v1beta1/query.proto
proto/cosmos/query/v1/query.proto
proto/cosmos/reflection/v1/reflection.proto
proto/cosmos/staking/v1beta1/query.proto
proto/cosmos/staking/v1beta1/staking.proto
proto/tendermint/abci/types.proto
proto/tendermint/types/evidence.proto
proto/tendermint/types/params.proto
proto/tendermint/types/types.proto
third_party/proto/google/protobuf/any.proto
tx/textual/internal/testpb/1.proto

Closes: #XXXX
---
I have...
I have...

chore: proto format

---

CHANGELOG.md

Closes: #XXXX
---
I have...
I have...

chore: add `0.46.4` changelog to main

---

.github/workflows/release.yml
CHANGELOG.md

ref https://github.com/cosmos/cosmos-sdk/pull/13674#issuecomment-1298832284
---
I have...
I have...

ci: notify for 0.46.x releases

---

CHANGELOG.md
runtime/app.go
store/iavl/store.go
store/iavl/store_test.go
types/context_test.go
x/bank/types/params.go
x/bank/types/params_test.go
x/gov/keeper/keeper.go

Closes: #XXXX
Came across unused code while working on the app wiring docs. Decided to just look through the codebase and remove the rest, I don't understand why we need to keep unused code.
To me, it seems like things we forgot to remove and were hidden by the unused golangci-lint comments.
Commented on each removal for clarification.
---
I have...
I have...

refactor: remove unused code

---

x/bank/keeper/keeper_test.go

Closes: #XXXX
---
I have...
I have...

tests: Add test to verify trying to send locked tokens raises an error

---

docs/architecture/adr-057-app-wiring-1.md

Pulls ADR 057 updates out of #12972, with all references to ADR 061 removed. Ref https://github.com/cosmos/cosmos-sdk/pull/12972#issuecomment-1299884969. 
---
I have...
I have...

docs: update ADR 057 app wiring

---

go.mod
go.sum
server/api/server.go
simapp/go.mod
simapp/go.sum
tests/go.mod
tests/go.sum

fork gogogateway to avoid the replace tag
---
I have...
I have...

chore: use gateway fork

---

x/staking/README.md

Closes: #XXXX
---
I have...
I have...

docs: staking param docs fix 

---

tests/integration/bank/keeper/keeper_test.go

Follow-up of #13690. We only added a mock test in that PR.
Added integration tests (basically the same as in https://github.com/cosmos/cosmos-sdk/pull/13750  and https://github.com/cosmos/cosmos-sdk/pull/13751)
---
I have...
I have...

chore: add `TestSendCoins_Invalid_SendLockedCoins` to intregration/e2e

---

simapp/app_legacy.go

Ensure `app_legacy.go` is as updated as `app.go`.
---
I have...
I have...

refactor: simplify app legacy

---

docs/src/css/custom.css
x/authz/README.md
x/capability/README.md
x/crisis/README.md
x/distribution/README.md
x/evidence/README.md
x/feegrant/README.md
x/gov/README.md
x/group/README.md
x/group/internal/orm/README.md
x/mint/README.md
x/nft/README.md
x/params/README.md
x/slashing/README.md
x/staking/README.md
x/upgrade/README.md

Most. Boring. Issue. Ever.
Follow-up of: https://github.com/cosmos/cosmos-sdk/pull/13755, https://github.com/cosmos/cosmos-sdk/pull/13745
---
I have...
I have...

docs: fix toc links

---

contrib/devtools/Dockerfile

When updating `ibc-go` to the latest proto and buf setup, `make proto-format` fails with:
```
find: clang-format: No such file or directory
```
Running the following to start the image, exec into the container and run the `find` cmd of `make proto-format` returns successfully.
```
docker run --name buf-proto -d -v $(pwd):/workspace --workdir /workspace ghcr.io/cosmos/proto-builder:0.11.0 sleep 1200
docker exec -it $CONTAINER_ID /bin/sh
apk add --no-cache clang-extra-tools \
&& clang-format --version
find ./ -name "*.proto" -exec clang-format -i {} \;
👍 👍 👍 
```
Closes: #13790
---
I have...
*All items are required. Please add a note if the item is not …

fix: adding clang-extra-tools for clang-format cosmos/proto-builder

---

Makefile

remove log that is printed every time. there is a log in the db options if this is forgotten, I believe that is enough to let the user know. 
---
I have...
I have...

chore: remove extra unneeded log

---

CHANGELOG.md
RELEASE_NOTES.md

Prepare 0.45.11 release.
---
I have...
I have...

chore: prepare 0.45.11 release

---

docs/.vuepress/config.js

Uses another index for vuepress than for docusaurus.
---
I have...
I have...

docs: update algolia index

---

baseapp/abci.go
baseapp/abci_v1_test.go
baseapp/baseapp.go
baseapp/options.go
simapp/app.go
types/abci.go

Closes: #13810
Ref: #13818 
This introduces a settable PrepareProposal handler so that applications have complete control over the ABCI 1.0 implementation.  The previous implementation is moved to an SDK default.
Also included is a demonstration of how to set custom mempool and handlers in SimApp.
---
I have...
I have...

feat: Settable PrepareProposal handler

---

.mergify.yml

Fixed typo in backport label 🥲

chore: update .mergify.yml

---

CHANGELOG.md
go.mod

Adds 0.46.5 changelog to main.
Adding to backport label to backport the retraction to 0.47 and sync the changelog.
---
I have...
I have...

chore: add 0.46.5 changelog to main

---

Makefile

golangci-lint now runs gofumpt when run with --fix, so we no longer need the gofumpt line here.  Also bumped to latest golangci-lint.
A simple change to the Makefile that removes references made to gofumpt, since it is now automatically run by `golangci-lint run ./... --fix`
---
I have...
I have...

chore: update makefile removing gofumpt, since golangci-lint replaces it

---

x/bank/keeper/migrations.go

Proper API to access bank store for 0.46.0 bank denom migration fix.
The original fix (https://github.com/cosmos/cosmos-sdk/pull/13891/files#diff-d4d8a522eca0bd1fd052a756b80d0a50bff7bd8e487105221475eb78e232b46aR109) requires bank module prefix Store. However this should not be exposed. The prefix store is a private keeper parameter, and should stay private in bank module. At the same time, we should not expect hack around to recreate the storage key for the bank module.
This PR adds a helper function for the bank migrator to properly call `v046.Migrate_V046_4_To_V046_5`.
---
I have...
*All items are required. Please add a note if the item is not …

feat(bank): enable 0.46.5 bank migration fix through migrator keeper

---

CHANGELOG.md
go.mod
go.sum

Closes: #XXXX
---
I have...
I have...

chore: bump tendermint to 0.34.24

---

fuzz/oss-fuzz-build.sh

OSS-Fuzz has made some changes that require a small modification to the build script.
Signed-off-by: AdamKorcz <adam@adalogics.com>
Closes: #XXXX
---
I have...
I have...

fix: fix broken OSS-Fuzz build 

---

proto/cosmos/distribution/v1beta1/genesis.proto
x/distribution/README.md
x/distribution/types/genesis.pb.go
x/staking/types/params_test.go

Fixes related to the audit (#13971)
---
I have...
I have...

docs: (x/distribution) Fix docs for v0.47

---

.github/workflows/docker.yml

Closes: #XXXX
---
I have...
I have...

chore: change image name to simapp 

---

api/cosmos/distribution/v1beta1/genesis.pulsar.go
simapp/app.go
simapp/app_test.go

Noticed that since we have CI testing simapp v1, that one test was failing: https://github.com/cosmos/cosmos-sdk/actions/runs/3560191051/jobs/5980063030
---
I have...
I have...

test: fix `TestSimAppExportAndBlockedAddrs` for simapp v1

---

.github/workflows/deploy-docs.yml
UPGRADING.md

Allows to deploy the docs directly from the GH Pages from the latest commit.
---
I have...
I have...

ci: allow to deploy docs manually

---

tx/textual/internal/cbor/cbor.go

Closes: #XXXX
---
I have...
I have...

refactor: camelCase textual/cbor

---

CHANGELOG.md
x/staking/types/delegation.go
x/staking/types/delegation_test.go

Discovered in https://github.com/cosmos/cosmos-sdk/pull/14046 that the `String()` function didn't print all fields.
Ref: https://github.com/cosmos/cosmos-sdk/pull/14046#discussion_r1034585432
---
I have...
I have...

fix: update redelegation stringer

---

store/rootmulti/store.go

Closes: #13904 
---
I have...
I have...

refactor: audit store package changes in 0.47 release

---

tools/rosetta/openapi/index.html
tx/textual/valuerenderer/valuerenderer.go

Fixes the latest bug discovered by SonarCloud:
https://github.com/cosmos/cosmos-sdk/runs/9784889414
---
I have...
I have...

fix: fix issues found by sonarcloud

---

x/nft/keeper/grpc_query.go

ref: #13991 
This PR adds back removed empty checks from grpc in x/nft for additional safeguard (from #14055)
---
I have...
I have...

refactor: Add back removed empty checks in grpc from x/nft audit

---

.github/PULL_REQUEST_TEMPLATE/docs.md
.github/workflows/stale.yml

update stale bot to close 30 day stale prs 
---
I have...
I have...

chore: update stale PR

---

simapp/test_helpers.go

Extracted from https://github.com/cosmos/cosmos-sdk/pull/13913 (as this one is still taking some time).
Running a test was creating an empty `data` folder in the current directory.
---
I have...
I have...

fix: stop creating `data` folder when running tests

---

proto/cosmos/consensus/v1/query.proto
proto/cosmos/consensus/v1/tx.proto
x/consensus/keeper/grpc_query.go
x/consensus/module.go
x/consensus/types/msgs.go

Closes: #XXXX
---
I have...
I have...

refactor: x/consensus audit changes

---

.github/workflows/test.yml

Closes: #XXXX
---
I have...
I have...

ci: remove unnecessary ci jobs

---

simapp/app.go

Closes: #XXXX
---
I have...
I have...

chore: set legacy router in app v1

---

.github/dependabot.yml
.github/labeler.yml
.github/workflows/test.yml
collections/CHANGELOG.md
collections/sonar-project.properties

Closes: #14221 - `SONAR_TOKEN_COLLECTIONS` needs to be added in the repo (cc @tac0turtle).
---
I have...
I have...

ci: add tooling for collections module

---

tools/rosetta/CHANGELOG.md
tools/rosetta/lib/errors/errors.go

Wrap tendermint erros as 500 to be [api compliant](https://www.rosetta-api.org/docs/models/Allow.html).
```
All Errors that this implementation could return. Any error that is returned during parsing that is not listed here will cause client validation to error.
```
---
I have...
I have...

fix: rosetta tendermint errors as internal

---

x/staking/keeper/historical_info_test.go
x/staking/keeper/keeper.go
x/staking/keeper/keeper_test.go
x/staking/keeper/msg_server.go
x/staking/keeper/params.go
x/staking/keeper/unbonding.go
x/staking/keeper/val_state_change.go
x/staking/migrations/v4/migrations_test.go
x/staking/types/keys.go
x/staking/types/msg.go

Ref: #14255 
Superficial changes, comments and go imports.
---
I have...
I have...

refactor: x/staking 0.47 audit

---

proto/cosmos/distribution/v1beta1/query.proto

Closes: #XXXX
Fixed a typo in distribution module `DelegationTotalRewards` query description.
---
I have...
I have...

fix: typo in distribution module query.proto

---

collections/CHANGELOG.md
collections/keyset.go
collections/keyset_test.go

Closes: #XXXX
---
I have...
I have...

feat(collections): keyset

---

server/grpc/grpc_web.go
server/start.go

- 2 small nits
ref: #14256
---
I have...
I have...

chore: audit server

---

docs/spec/SPEC_STANDARD.md

This PR fixes very minor typos in the spec template.
---
I have...
I have...

docs: minor fixes to spec template

---

x/gov/migrations/v3/convert.go

Small optimization to remove unnecessary for loop after the changes #14347.
Ref: https://github.com/cosmos/cosmos-sdk/pull/14347#discussion_r1055925322
---
I have...
I have...

feat: gov/v1.Proposal convertion to v1beta1.Proposal cleanup

---

tests/e2e/auth/suite.go

Closes: #XXXX
---
I have...
I have...

fix: attempt to fix flaky test TestCLISignBatch

---

x/mint/README.md
x/mint/types/minter.go

Closes: #14186
---
I have...
I have...

chore: fix mint comments on inflation rate

---

UPGRADING.md
client/pruning/main.go
server/util.go

Closes: #XXXX
---
I have...
I have...

chore: modify db support

---

store/cachekv/benchmark_test.go

- refactor the benchmark to remove import of `sdk "github.com/cosmos/cosmos-sdk/types"`
- change the benchmark a little bit to be more realistic.
---
I have...
I have...

remove sdk import from store package

---

UPGRADING.md
client/v2/autocli/query_test.go
simapp/app_config.go
testutil/configurator/configurator.go
types/module/module.go
x/auth/testutil/app_config.go
x/authz/testutil/app_config.go
x/capability/testutil/app_config.go
x/distribution/testutil/app_config.go
x/evidence/testutil/app_config.go
x/feegrant/testutil/app_config.go
x/group/testutil/app_config.go
x/mint/testutil/app_config.go
x/nft/testutil/app_config.go
x/params/testutil/app_config.go
x/slashing/testutil/app_config.go
x/staking/testutil/app_config.go

Replicates https://github.com/cosmos/cosmos-sdk/pull/14415, for `SetOrderInitGenesis` and `SetOrderExportGenesis`.
This allows to clean up the unnecessary addition of the runtime module added in: https://github.com/cosmos/cosmos-sdk/pull/13867
Added an UPGRADING.md section so that chains are aware of the clean-up they can do in v0.48.
---
I have...
I have...

chore: loosen assertions in `SetOrderInitGenesis` and  `SetOrderExportGenesis`

---

.github/workflows/test.yml
tools/rosetta/config.go

Closes: #XXXX
---
I have...
I have...

ci: dont run sonar if in draft mode

---

simapp/go.mod
simapp/go.sum
tests/go.mod
tests/go.sum

small PR to remove the client/v2 replace tag on simapp, introduced in the autocli pr
having it breaks build when using simapp standalone: https://github.com/julienrbrt/simapp/actions/runs/3836779597/jobs/6531322392
---
I have...
I have...

chore: bump client/v2 deps

---

tests/integration/distribution/keeper/allocation_test.go
tests/integration/distribution/keeper/delegation_test.go
tests/integration/distribution/keeper/grpc_query_test.go
tests/integration/distribution/keeper/keeper_test.go
tests/integration/distribution/keeper/msg_server_test.go
tests/integration/distribution/module_test.go
x/group/client/cli/prompt.go

Closes: #14494 
ref: #14145 #12332 
---
I have...
I have...

chore: Replace testify with gotest.tools in distribution integration tests

---

CHANGELOG.md
RELEASE_NOTES.md
UPGRADING.md

prepare for v0.47.0-rc1.
To be merged after: https://github.com/cosmos/cosmos-sdk/pull/14533.
---
I have...
I have...

chore: add v0.47.0-rc1 release notes

---

.github/workflows/issues.yml

Closes: #XXXX
---
I have...
I have...

chore: add action to add issues to project board when labeled

---

CHANGELOG.md
docs/docs/basics/03-accounts.md

Closes: #6500
Documentation of how to create a new key type for the keyring.
---
I have...
I have...

docs: new key type for keyring

---

docs/architecture/adr-template.md

add alternative to adr template so that authors can provide alternative designs for consideration. Not having alternatives leads the reviewer to not consider other designs
---
I have...
I have...

chore: add alternative adr section

---

go.mod
tests/go.mod

Small PR, I was checking the replaces for all versions (as it was a task here https://github.com/cosmos/cosmos-sdk/pull/14623) and noticed v0.47 contained replaces that are not necessary.
---
I have...
I have...

chore: remove unecessary replace in 0.47

---

store/streaming/file/service.go

move expensive check higher up to avoid setup then check
closes #13964 
---
I have...
I have...

refactor: move check to first step of function 

---

CHANGELOG.md
RELEASE_NOTES.md

Follow-up of https://github.com/cosmos/cosmos-sdk/pull/14623
---
I have...
I have...

chore: prepare 0.45.12 release

---

CHANGELOG.md

Add missing changelog to main.
---
I have...
I have...

chore: add v0.46.8 and v0.45.12 changelog to main

---

x/nft/simulation/operations_test.go

Tiny PR for nft failing test on main due to https://github.com/cosmos/cosmos-sdk/pull/14751.
---
I have...
I have...

test: fix nft simulation test

---

.github/workflows/codeql-analysis.yml
types/simulation/rand_util.go

I have looking at Cronos code yesterday and seen this PR: https://github.com/crypto-org-chain/cronos/pull/820.
I think we can use these queries and packs.
Closes: #XXXX
---
I have...
I have...

ci: improve codeql

---

go.mod
go.sum
simapp/go.mod
simapp/go.sum
store/iavl/store.go
tests/go.mod
tests/go.sum

update IAVL to RC.1 0.19.5
---
I have...
I have...

chore: update IAVL 

---

core/log/logger.go
core/util/logger.go

ref #14726 
this pr proposes adding the logger interface from tendermint into core in order to reduce the reliance on tendermint & enable the ability of removing tendermint as a go dependency from future modules. 
---
I have...
I have...

feat: logger interface

---

.github/workflows/issue_labeler.yml

Closes: #XXXX
---
I have...
I have...

chore: fix action 

---

go.mod
go.sum
simapp/go.mod
simapp/go.sum
tests/go.mod
tests/go.sum

Bump IAVL v0.19.5 (note, this targets v0.47) and backport to v0.45, v0.46.
I'll be cutting a v0.45 rc when this is done for testing on mainnets again later today.
---
I have...
I have...

chore: bump IAVL to v0.19.5

---

go.mod
go.sum
simapp/go.mod
simapp/go.sum
store/go.mod
store/go.sum
tests/go.mod
tests/go.sum
tools/cosmovisor/go.mod
tools/cosmovisor/go.sum
x/evidence/go.mod
x/evidence/go.sum
x/feegrant/go.mod
x/feegrant/go.sum
x/nft/go.mod
x/nft/go.sum
x/upgrade/go.mod
x/upgrade/go.sum

> // Using this replace directive as v0.20.0-alpha1 > v0.20.0-alpha.2
// This can be deleted when a v0.20.0-alpha3 is tagged or anything lexicographically above than v0.20.0-alpha1
An IAVL v0.20.0-alpha3 has been tagged, so we can do the above.
---
I have...
I have...

build: clean-up replaces

---

x/gov/simulation/operations.go

Fixes https://github.com/cosmos/cosmos-sdk/actions/runs/4132167165
We cannot cancel a proposal with invalid status.
---
I have...
I have...

fix: fix gov sims

---

baseapp/abci.go

Closes: #XXXX
---
I have...
I have...

fix: avoid broadcasting tx through query

---

UPGRADING.md
go.mod
go.sum
simapp/go.mod
simapp/go.sum
tests/go.mod
tests/go.sum

Follow-up task of https://github.com/cosmos/cosmos-sdk/pull/15060
This is for being able to cut an RC without replaces (once we have the CometBFT tags).
Once v0.47 is released, we should look into backporting features from main of rosetta and tag new releases for v0.47 here.
---
I have...
I have...

chore: bump rosetta to cometbft version in v0.47

---

ROADMAP.md

update roadmap doc with link and check marks 
---
I have...
I have...

chore: minor update to roadmap

---

docs/sidebars.js

Updates Swagger link in v0.47.
---
I have...
I have...

docs: update swagger link

---

CHANGELOG.md
RELEASE_NOTES.md

v0.46.11 has been tested by running Quicksilver and Mars nodes against their mainnet.
---
I have...
I have...

chore: prepare v0.46.11 release

---

ROADMAP.md

update completed items with check marks 
---
I have...
I have...

chore: update roadmap with completed items

---

x/staking/types/authz_test.go

This PR fixes the tests for #15164.
---
I have...
I have...

test: fix tests for adding MsgCancelUnbondingDelegation to Staking Authorization

---

x/auth/keeper/bech32_codec.go
x/auth/keeper/keeper.go
x/auth/module.go

Follow-up to #15326 to expose `address.Codec` via depinject. This is likely the simplest way for most modules that don't depend on x/auth otherwise to get an `address.Codec`.
---
I have...
I have...

feat(x/auth): add ProvideAddressCodec provider

---

client/pruning/main.go
server/start.go
server/util.go

ref: https://github.com/cosmos/cosmos-sdk/pull/15303#issuecomment-1462950372
cc @facundomedica

attempt to simplify

---

docs/.gitignore
docs/docs/tooling/00-protobuf.md
docs/post.sh
docs/pre.sh

ref: https://github.com/cosmos/cosmos-sdk/pull/15354#issuecomment-1464283664
missed that in the review.
---
I have...
I have...

docs: display rfc in docs

---

core/address/codec.go

move address codec to core to avoid sdk dependency in the future 
ill make a follow up pr migrating modules to use this
---
I have...
I have...

refactor: add address codec to core

---

client/v2/autocli/msg.go

Fix the issue where sub cmd was added to root cmd instead of creating the proper sub cmd tree. 
Previous Behavior 
New Behavior 
Closes: #XXXX
---
I have...
I have...

fix(autocli): Fix subcmd added to root cmd 

---

simapp/sim_test.go

Closes: #XXXX
---
I have...
I have...

fix: sims after merging #15303

---

CHANGELOG.md
RELEASE_NOTES.md

chore: prepare v0.47.0 release notes

---

tests/go.mod
tests/integration/aminojson/aminojson_test.go

@atheeshp this should fix tests

fix: address failing test

---

proto/README.md

Updates buf tag from `v0.47.0-rc3` to `v0.47.0`.
---
I have...
I have...

docs: update buf tag

---

x/auth/module.go
x/auth/vesting/module.go
x/authz/module/module.go
x/consensus/module.go
x/crisis/module.go
x/evidence/module.go
x/feegrant/module/module.go
x/group/module/module.go
x/mint/module.go
x/nft/module/module.go
x/params/module.go
x/slashing/module.go
x/upgrade/module.go

Quick PR cleaning up some module.go.
- `RegisterInvariants` is only called when a module implements the `HasInvariants` interface (https://github.com/cosmos/cosmos-sdk/blob/14ba0248b8080c1c9cdf0a5e599d92db30275c50/types/module/module.go#L183). No-op are not required
- `NewHandler` is a left-over of legacy routes.
- When a module without genesis do not need to implement `HasGenesis` interface (https://github.com/cosmos/cosmos-sdk/blob/14ba0248b8080c1c9cdf0a5e599d92db30275c50/types/module/module.go#L170)
---
I have...
your handle next to the items reviewed if you …

refactor: remove unnecessary modules methods

---

docs/docs/ecosystem/README.md

Closes: #XXXX
---
I have...
I have...

docs: update cosmwasm link

---

proto/cosmos/tx/v1beta1/service.proto

ref: https://github.com/cosmos/cosmos-sdk/issues/15437, https://github.com/cosmos/cosmos-sdk/issues/13439
If we add a test this should be added from main and backported the way down.
---
I have...
I have...

fix: remove extra `;` in service.proto

---

RELEASE_PROCESS.md

Actualize release process.
---
I have...
I have...

docs: sync release process

---

x/README.md

Quick fix for the broken vesting link
---
I have...
I have...

fix: broken vesting link

---

math/CHANGELOG.md

Update Changelog in preparation for tagging math/v1.0.0
---
I have...
I have...

chore: math v1.0.0

---

math/CHANGELOG.md

Fixing a changelog link.
---
I have...
I have...

chore(math): fix changelog link

---

CHANGELOG.md
RELEASE_NOTES.md

Closes: #XXXX
---
I have...
I have...

chore: prepare release notes for v0.47.1

---

client/tx/tx.go

Closes: #XXXX
---
I have...
I have...

docs: fix a typo

---

CHANGELOG.md
x/gov/abci.go
x/gov/abci_test.go
x/gov/types/events.go

Closes: https://github.com/cosmos/cosmos-sdk/issues/15445
---
I have...
I have...

feat: carry `x/gov` proposal execution error message

---

.github/workflows/lint.yml
.github/workflows/test.yml
Makefile
scripts/go-lint-all.sh

This PR adds a script, go-lint-all.sh and lints each module.
closes: #15586 
---
I have...
I have...

fix: use a script to lint each module

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/epics.md
.github/ISSUE_TEMPLATE/feature-request.md

add issue title and label to templates 
---
I have...
I have...

chore: add label and title to issue templates

---

CHANGELOG.md

Closes: #XXXX
---
I have...
I have...

chore: sync changelog with latest release

---

api/cosmos/consensus/v1/query.pulsar.go
api/cosmos/consensus/v1/query_grpc.pb.go
api/cosmos/crypto/ed25519/keys.pulsar.go
go.mod
proto/cosmos/consensus/v1/query.proto
simapp/app.go
x/consensus/keeper/keeper.go
x/consensus/keeper/keeper_test.go
x/consensus/module.go
x/consensus/types/query.pb.go
x/consensus/types/query.pb.gw.go

Follow-up of https://github.com/cosmos/cosmos-sdk/pull/15553.
Reverts the proto renamed here https://github.com/cosmos/cosmos-sdk/pull/15553#discussion_r1151108653
Firstly, for consistency, other params query request and response are called `QueryParamsRequest` and `QueryParamsResponse`, not `QueryGetParamsRequest`.
Secondly, because it was proto breaking.
---
I have...
I have...

revert(consensus): revert proto breaking change 

---

core/coins/format.go
core/coins/format_test.go
math/dec.go
math/dec_test.go
simapp/simd/cmd/testnet.go
tests/integration/bank/keeper/keeper_test.go
tests/integration/staking/keeper/grpc_query_test.go

works towards: 
* https://github.com/cosmos/cosmos-sdk/issues/15546
---
I have...
I have...

style: lints for core, math, simapp, and tests

---

tools/confix/cmd/mutate_test.go
tools/rosetta/lib/server/server.go

works towards: 
* https://github.com/cosmos/cosmos-sdk/issues/15546
---
I have...
I have...

Style: lints for tools

---

collections/codec/bool.go
collections/indexed_map.go
collections/indexes/reverse_pair.go

Closes: #XXXX
---
I have...
I have...

style: errors, collections

---

.github/workflows/gosec.yml

Disables gosec g101 in github actions gosec linter
---
I have...
I have...

ci: disable gosec g101 in actions

---

log/bench_test.go

This PR fixes two lint issues in the log package.  This is the first PR in a sequence.  Subsequent PR's will contain this one. 
---
I have...
I have...

style: fix lint issues in log (1/n)

---

.github/workflows/gosec.yml

Closes: #XXXX
---
I have...
I have...

ci: disable gosec G107 rule

---

tests/e2e/nft/test_helper.go
x/feegrant/expected_keepers.go
x/nft/client/cli/query.go
x/nft/client/cli/query_test.go
x/nft/expected_keepers.go
x/nft/genesis.go
x/nft/keeper/genesis.go
x/nft/keeper/grpc_query.go
x/nft/keeper/grpc_query_test.go
x/nft/keeper/keeper.go
x/nft/keeper/keeper_test.go
x/nft/keeper/msg_server.go
x/nft/keeper/msg_server_test.go
x/nft/module/module.go
x/nft/testutil/expected_keepers_mocks.go
x/staking/types/expected_keepers.go

ref #13140 
Removing global bech32 from nft module. This avoids the globals in validate basic, this will be handled in a different workscope (worked on after this one is completed)
---
I have...
I have...

refactor(nft): remove global bech32

---

tests/e2e/authz/query.go
tests/e2e/authz/tx.go
x/auth/keeper/bech32_codec.go
x/auth/module.go
x/authz/client/cli/query.go
x/authz/client/cli/query_test.go
x/authz/client/cli/tx.go
x/authz/client/cli/tx_test.go
x/authz/client/testutil/helpers.go
x/authz/expected_keepers.go
x/authz/keeper/genesis.go
x/authz/keeper/genesis_test.go
x/authz/keeper/grpc_query.go
x/authz/keeper/grpc_query_test.go
x/authz/keeper/keeper_test.go
x/authz/keeper/msg_server.go
x/authz/keeper/msg_server_test.go
x/authz/module/abci_test.go
x/authz/module/module.go
x/authz/testutil/expected_keepers_mocks.go

ref #13140 
remove global bech32 from authz, this avoids validatebasic and getsigners. Those will be done on a different pr 
---
I have...
I have...

refactor(authz):remove global bech32 

---

x/bank/app_test.go
x/bank/client/cli/tx.go
x/bank/client/cli/tx_test.go
x/bank/keeper/genesis_test.go
x/bank/keeper/keeper_test.go
x/bank/migrations/v2/json_test.go
x/bank/migrations/v2/store_test.go
x/bank/migrations/v3/store_test.go
x/bank/migrations/v4/gen_state_test.go
x/bank/simulation/genesis.go
x/bank/types/balance_test.go
x/bank/types/genesis_test.go
x/bank/types/msgs_test.go
x/bank/types/send_authorization_test.go

Closes part of: #14405 
---
I have...
I have...

refactor: remove aliases from types/math.go in bank module

---

simapp/app.go
x/upgrade/abci_test.go
x/upgrade/client/cli/parse_test.go
x/upgrade/client/cli/tx.go
x/upgrade/module.go

ref #13140 
remove global bech32 from upgrade
this avoids validate basic as this will come in a follow up pr
---
I have...
I have...

refactor(upgrade): remove global bech32 

---

x/gov/README.md

Closes: https://github.com/cosmos/cosmos-sdk/issues/15695
---
I have...
I have...

docs(gov): remove unimplemented section

---

.github/workflows/docker.yml
Dockerfile

Closes: https://github.com/cosmos/cosmos-sdk/issues/15670
We need to find a way to deprecate `interchainio/simapp`.
---
I have...
I have...

ci: backport docker job from main

---

x/nft/module/module.go

Fixes a style complaint in golanglint-ci from code that's been failing all the builds.

style(x/nft): fix golanglint-ci suggestion

---

.github/workflows/build.yml
.github/workflows/codeql-analysis.yml
.github/workflows/dependabot-update-all.yml
.github/workflows/dependencies-review.yml
.github/workflows/lint.yml
.github/workflows/release-confix.yml
.github/workflows/release-cosmovisor.yml
.github/workflows/release-rosetta.yml
.github/workflows/release.yml
.github/workflows/sims-045.yml
.github/workflows/sims-046.yml
.github/workflows/sims-047.yml
.github/workflows/sims-nightly.yml
.github/workflows/sims.yml
.github/workflows/test.yml
store/internal/conv/string_test.go

Bump Go version to latest Go.
Fixes failing dependency review job blocking PRs: https://github.com/cosmos/cosmos-sdk/actions/runs/4625849767
---
I have...
I have...

ci: bump go version

---

Dockerfile

ref: https://github.com/cosmos/cosmos-sdk/pull/15703#issuecomment-1498844066
---
I have...
I have...

build: install necessary deps in docker

---

docs/architecture/adr-064-abci-2.0.md

Add an upgrading section to ADR-064.
cc @sergio-mena @tac0turtle 
---
I have...
I have...

docs: Add Upgrading Section to ADR-064

---

store/cachekv/internal/mergeiterator.go
store/iavl/tree_test.go
store/internal/conv/string_test.go
store/mem/store.go
store/rootmulti/store.go
store/types/store_test.go

- Return an exported type rather than an unexported type, from an exported function
- Assign error values to _
- Add reason to nolint directive
- Remove ineffectual assignment
- Remove checked cast to same type as value
---
I have...
I have...

style: fix linting issues in store module

---

client/v2/autocli/flag/binary.go
client/v2/autocli/query_test.go

This was causing one set of linter failures.
---
I have...
I have...

style: gofumpt client/v2 module

---

x/upgrade/module.go

- Inconsistent receiver name (wasn't used in the method anyway)
- Unused field (removed, was used in embedded type anyway)
---
I have...
I have...

style: fix linter issues in x/upgrade

---

x/distribution/module.go
x/evidence/module.go

Continuing golangci-lint cleanup.
---
I have...
I have...

style: rename to ModuleInputs to fix lint issue

---

store/snapshots/helpers_test.go

Without this change, there were intermittent failures due to a non-empty t.TempDir() directory at the end of a test:
```console
$ go test  -run=LoadChunk$ ./snapshots/ -count=220 -failfast 
--- FAIL: TestManager_LoadChunk (0.01s)
testing.go:1225: TempDir RemoveAll cleanup: unlinkat /var/folders/.../T/TestManager_LoadChunk1472891739/001: directory not empty
FAIL
FAIL    cosmossdk.io/store/snapshots    0.177s
```
With this change, I can no longer reproduce the flaky failure:
```console
$ go test -run=LoadChunk$ ./snapshots/ -count=1000 -failfast
ok      cosmossdk.io/store/snapshots    15.722s
```
---
I have...
*All items are required. Please add a note …

test(store): ensure busy manager goroutine is finished

---

x/tx/decode/unknown_test.go

This fixes an intermittent test failure like:
---
I have...
I have...

fix: test sometimes receives an error string containing unicode

---

.github/workflows/dependencies-review.yml
.github/workflows/lint.yml

On the Dependency Review and Lint CI jobs, there was a warning:
Restore cache failed: Dependencies file is not found in
/home/runner/work/cosmos-sdk/cosmos-sdk. Supported file pattern: go.sum
Perform the repository checkout before the setup-go action, so that it can automatically use a build and module cache. This should eliminate those warnings, and it ought to slightly speed up both of those workflows.
---
I have...
I have...

ci: ensure checkout action happens before setup-go

---

.github/workflows/build.yml
.github/workflows/dependencies-review.yml
.github/workflows/lint.yml
.github/workflows/test.yml

Discovered by @mark-rushakoff. Our CI was stuck on required jobs after merge queue enabling.
This is an attempt to fix that. https://github.com/cosmos/cosmos-sdk/queue/main
---
I have...
I have...

ci: add `merge_queue` trigger for required workflows

---

x/tx/CHANGELOG.md
x/tx/signing/aminojson/time.go

Since math.MaxInt64 is an untyped constant, an explicit cast is required to support 32 arch, e.g. our arm docker builds. See https://github.com/golang/go/issues/23086.
This was surfaced bringing latest x/tx into simapp builds.
---
I have...
I have...

fix(x/tx): fix int64 usage for 32 bit platforms

---

x/auth/migrations/v5/doc.go
x/auth/module.go

The consensus version was not bumped in v0.47 because it was not necessary: https://github.com/cosmos/cosmos-sdk/pull/14483#discussion_r1062294196
However an empty migration stayed while it shouldn't have, meaning there is a discrepancy between the consensus version and the migrated version: https://github.com/cosmos/cosmos-sdk/pull/15830#discussion_r1167028540 
This PR fixes that.
Note, notice this targets v0.47, as this is updated here for main: https://github.com/cosmos/cosmos-sdk/pull/15830/files
---
I have...
your handle next to the items reviewed if you only …

fix: remove unnecessary migration

---

x/bank/app_test.go
x/bank/bench_test.go

Closes: #XXXX
---
I have...
I have...

refactor: update x/bank to comet v0.38

---

.github/workflows/test.yml
orm/model/ormtable/auto_increment.go
orm/sonar-project.properties

Closes: #XXXX
---
I have...
I have...

ci: run orm tests

---

CHANGELOG.md
simapp/app.go
simapp/sim_test.go
testutil/sims/simulation_helpers.go
testutil/sims/simulation_helpers_test.go
x/slashing/simulation/decoder.go
x/slashing/simulation/decoder_test.go

ref: https://github.com/cosmos/cosmos-sdk/actions/runs/4691327417/jobs/8315724907
run `go test . -run TestAppImportExport -Enabled=true -NumBlocks=50 -Genesis= -Verbose=true -Commit=true -Seed=1 -Period=5 -v -timeout 24h`
I have made some improvement to the kv diff comparing and displaying and fixed the fact that we weren't comparing all the stores. It overall improves the test.
---
I have...
I have...

test(sims): fix sim-import-export and improve sims

---

codec/collections.go
codec/collections_test.go
collections/README.md

Closes: #15897 
---
I have...
I have...

feat(codec): Add collections value codec for interfaces.

---

baseapp/abci.go
baseapp/baseapp.go
baseapp/info.go
core/comet/doc.go
core/comet/service.go
core/header/service.go
runtime/module.go
runtime/services.go
tests/integration/evidence/keeper/infraction_test.go
types/context.go
x/evidence/testutil/expected_keepers_mocks.go

Closes: #XXXX
---
I have...
I have...

WIP on comet block info

---

x/auth/tx/config.go

Ref: https://github.com/cosmos/cosmos-sdk/pull/15822#pullrequestreview-1394390691
---
I have...
I have...

refactor(x/auth): doc and remove deprecated fn from #15822

---

x/auth/keeper/keeper_bench_test.go
x/evidence/genesis_test.go

Closes: #XXXX
---
I have...
I have...

fix: benchmarks broken in 15818

---

client/v2/go.mod
client/v2/go.sum
go.mod
go.sum
simapp/go.mod
simapp/go.sum
store/go.mod
store/go.sum
tests/go.mod
tests/go.sum
tools/confix/go.mod
tools/confix/go.sum
tools/cosmovisor/go.mod
tools/cosmovisor/go.sum
tools/hubl/go.mod
tools/hubl/go.sum
tools/rosetta/go.mod
tools/rosetta/go.sum
x/circuit/go.mod
x/circuit/go.sum
x/evidence/go.mod
x/evidence/go.sum
x/feegrant/go.mod
x/feegrant/go.sum
x/nft/go.mod
x/nft/go.sum
x/upgrade/go.mod
x/upgrade/go.sum

I've been refreshing dependabot (https://github.com/cosmos/cosmos-sdk/network/updates) but it does not detect the new release. So doing the PR manually.
---
I have...
I have...

build(deps): bump cometbft to v0.37.1

---

CHANGELOG.md
Makefile
RELEASE_NOTES.md
go.mod
go.sum

Bump CometBFT to v0.34.28 in v0.46.
---
I have...
I have...

build(deps): bump cometbft to v0.34.28

---

CHANGELOG.md
x/gov/migrations/v3/convert.go

Closes https://github.com/cosmos/cosmos-sdk/issues/15977
---
I have...
I have...

chore(gov): improve proposal conversion error message

---

baseapp/abci_test.go
baseapp/baseapp_test.go
baseapp/block_gas_test.go
baseapp/test_helpers.go

Closes: #XXXX
---
I have...
I have...

refactor(baseapp): fix tests abci 2.0 

---

errors/CHANGELOG.md
errors/errors.go

This error is used to break out from callback iterators. If a callback returns this error then the iterator stops the iteration without returning an error.
---
I have...
I have...

feat(errors): Add ErrStopIterating

---

baseapp/abci.go
types/context.go

- Add `PrepareProposal` and `ProcessProposal` to the `Context` so app devs know the execution context. This is extremely useful in cases where tx validation happens via the AnteHandler but you may not want certain execution paths to be handled.
- Add a case to `FinalizeBlock` to only execute txs if they adhere to the `sdk.Tx` interface. This is so we do not wrongfully execute potential txs that are manually injected by the proposal as vote extensions.
---
I have...
I have...

chore: ABCI UX Improvements

---

x/tx/CHANGELOG.md

Will tag x/tx v0.6.2 after merge and remove several replace directives.
---
I have...
I have...

chore(x/tx): Update changelog for x/tx v0.6.2.

---

runtime/module.go
types/module/configurator.go
types/msgservice/validate.go

Closes: #XXXX
---
I have...
I have...

fix: proto registry errors in runtime related to proto.MergedRegistry

---

.github/workflows/build.yml
.github/workflows/codeql-analysis.yml
.github/workflows/dependabot-update-all.yml
.github/workflows/dependencies-review.yml
.github/workflows/lint.yml
.github/workflows/release-confix.yml
.github/workflows/release-cosmovisor.yml
.github/workflows/release-rosetta.yml
.github/workflows/release.yml
.github/workflows/sims-045.yml
.github/workflows/sims-046.yml
.github/workflows/sims-047.yml
.github/workflows/sims-nightly.yml
.github/workflows/sims.yml
.github/workflows/test.yml
simapp/app_v2.go

Bump Go to avoid dependency review check job fail on all PRs.
---
I have...
I have...

ci: bump go in CI

---

api/cosmos/staking/v1beta1/genesis.pulsar.go
proto/cosmos/staking/v1beta1/genesis.proto
x/gov/types/v1/gov.pb.go
x/gov/types/v1/tx.pb.go
x/gov/types/v1beta1/gov.pb.go
x/gov/types/v1beta1/tx.pb.go
x/staking/types/genesis.pb.go

Closes: #XXXX
---
I have...
I have...

chore: fix typo in staking's genesis proto

---

x/authz/keeper/msg_server.go

Closes: #XXXX
---
I have...
I have...

fix: fix authz granter error message

---

x/gov/keeper/msg_server.go

Message both checked at:
- x/gov msg server https://github.com/cosmos/cosmos-sdk/blob/main/x/gov/keeper/msg_server.go#L416
- x/gov keeper proposal https://github.com/cosmos/cosmos-sdk/blob/main/x/gov/keeper/proposal.go#L48 
This is unnecessary and  will lower down the transaction processing.
---
I have...
I have...

refactor: duplicate message verification at msg server and keeper

---

x/staking/simulation/operations_test.go

ref: #12272
---
I have...
I have...

fix(staking): fix staking test failures

---

x/authz/simulation/operations_test.go
x/bank/simulation/operations_test.go
x/distribution/simulation/operations_test.go
x/gov/abci_test.go
x/gov/simulation/operations_test.go
x/group/simulation/operations_test.go
x/staking/simulation/operations_test.go

ref https://github.com/cosmos/cosmos-sdk/issues/12272
Update the comments as well for modules not being touched on: https://github.com/cosmos/cosmos-sdk/pull/16091#discussion_r1190192438 (staking and feegrant not touched here as assigned in the EPIC)
---
I have...
I have...

test: update group/gov test for abci 2.0

---

CHANGELOG.md

Adds v0.45.15 and v0.45.16 changelog to main.
---
I have...
I have...

chore: add v0.45.x changelog to main

---

tests/integration/evidence/keeper/infraction_test.go
x/evidence/keeper/abci.go

Closes: #XXXX
---
I have...
I have...

fix(x/evidence): tests and nil guard for empty block info

---

math/CHANGELOG.md

ref: https://github.com/cosmos/cosmos-sdk/pull/16141#issuecomment-1547621619
---
I have...
I have...

chore: prepare math 1.0.1

---

x/staking/simulation/operations_test.go

ref: #12272
---
I have...
I have...

fix(staking): update the staking sim tests

---

docs/architecture/adr-047-extend-upgrade-plan.md

ref: https://github.com/cosmos/cosmos-sdk/pull/16150 && https://github.com/cosmos/cosmos-sdk/pull/16150#issuecomment-1550020671
After this PR, I'll close the relevant issues.
---
I have...
I have...

docs: retract adr-47

---

tools/hubl/go.mod
tools/hubl/go.sum

Closes: #XXXX
---
I have...
I have...

chore(hubl): remove unecessary replace breaking `go install`

---

baseapp/abci.go

Closes: #XXXX
---
I have...
I have...

chore: audit errors in ABCI methods

---

CHANGELOG.md
math/CHANGELOG.md
math/dec.go

Closes: #XXXX
Earlier optimization change set the base to 1 without correct precision. This PR fixes it so that the base is of the desired precision.
EDIT(@julienrbrt): See context here: https://github.com/osmosis-labs/cosmos-sdk/pull/451
I have...
I have...

fix: legacy dec power mut zero exponent precision

---

x/crisis/module.go
x/distribution/module.go
x/gov/module.go
x/mint/module.go
x/slashing/module.go
x/staking/module.go

Quick PR, that makes the params module optional as well when using App Wiring.
Some modules had this and some didn't, which was making the params module required (but chains starting from v0.47 do not need it at all).
---
I have...
I have...

chore: make params module optional in app wiring

---

x/bank/bench_test.go

Closes: #XXXX
---
I have...
I have...

fix: Fix x/bank Benchmarks

---

docs/.vuepress/config.js

Closes: #XXXX
---
I have...
I have...

chore: update sidebar v0.46

---

docs/.vuepress/config.js

Closes: #XXXX
---
I have...
I have...

chore: update sidebar v0.45

---

docs/architecture/adr-038-state-listening.md
store/streaming/abci/README.md

Closes: #XXXX
---
I have...
I have...

docs: update streaming docs

---

CHANGELOG.md
client/tx/factory.go
client/tx/tx_test.go
client/tx_config.go
types/module/testutil/codec.go

Closes: #XXXX
---
I have...
I have...

feat: support extension options for build tx (backport: #15992)

---

tests/integration/aminojson/aminojson_test.go

Fixes integration tests in #16254

fix intergration tests

---

baseapp/testutil/buf.lock
baseapp/testutil/buf.yaml
scripts/protocgen-pulsar.sh
scripts/protocgen.sh
testutil/testdata/buf.lock
x/tx/Makefile
x/tx/internal/testpb/buf.lock
x/tx/signing/aminojson/internal/buf.lock

Follow-up of https://github.com/cosmos/cosmos-sdk/pull/16343
Removes a forgotten buf warning after bump to buf 1.20.
Removes as well the `buf mod update` that were added in #16343 as I forgot to remove them when updating buf.
---
I have...
I have...

chore: remove buf warning

---

.github/workflows/consensuswarn.yml

This job (https://github.com/cosmos/cosmos-sdk/actions/runs/5153955747/jobs/9281817802?pr=16404) always fails because DeliverTx does not exist anymore.
---
I have...
I have...

ci: fix consensuswarn always failing

---

x/gov/README.md

Documentation states that the voting period should be less than the unbonding period to prevent double voting. However, that's not true as the voting power of the votes is calculated based on the state of the staking module at the end of the voting period. So, suppose an unbonding period of 1 day and a voting period of 14 days, you can think of the following attack:
1. Bond tokens through an address and vote.
2. Unbond
3. Move the tokens to another address and bond again.
4. Vote again.
This attack is not possible as when the votes are tallied, only the second address is going to have voting power so the first vote will be assigned 0 voting power.
---
please add links to any relevant follow up …

docs(gov): Voting period can be more than unbonding period

---

tools/cosmovisor/CHANGELOG.md
tools/cosmovisor/README.md
tools/cosmovisor/cmd/cosmovisor/add_upgrade.go
tools/cosmovisor/cmd/cosmovisor/config.go
tools/cosmovisor/cmd/cosmovisor/init.go
tools/cosmovisor/cmd/cosmovisor/init_test.go
tools/cosmovisor/cmd/cosmovisor/root.go
tools/cosmovisor/cmd/cosmovisor/version.go
tools/cosmovisor/flags.go
tools/cosmovisor/process.go
tools/cosmovisor/upgrade.go
tools/cosmovisor/upgrade_test.go

Closes: https://github.com/cosmos/cosmos-sdk/issues/12457
---
I have...
I have...

feat(cosmovisor): add `add-upgrade` command

---

.mergify.yml
collections/CHANGELOG.md
core/CHANGELOG.md
x/tx/CHANGELOG.md

After this PR, collections, tx and core will be tagged.
---
I have...
I have...

chore: prepare core,tx,collections changelogs and update mergify config for v0.5

---

.github/workflows/sims-050.yml
math/CHANGELOG.md

let's please watch out of changelog placement, otherwise it makes our life harder when tagging.
Follow-up of https://github.com/cosmos/cosmos-sdk/pull/16263
---
I have...
I have...

chore: fix concurrency group sims and math changelog

---

types/bech32/fuzz_test.go

Adds seeds and fuzzes ConvertAndEncode.

test: types/bech32: fuzz ConvertAndEncode

---

x/tx/signing/textual/fuzz_test.go

Adds a fuzzer to fuzz BytesValueRenderer's Parse
and Format methods.
Updates #15728

test: x/tx/signing/textual: fuzz BytesValueRenderer

---

x/tx/signing/textual/fuzz_test.go

Adds a fuzzer for MessageValueRenderer.Parse
Updates #15728

test: x/tx/signing/textual: fuzz MessageValueRenderer.Parse

---

.github/dependabot.yml

Let dependabot check cometbft versions in release branches to avoid doing those prs manually.
v0.46 will still be manual as we do not check with dependabot there.
---
I have...
I have...

ci: add cometbft version fetch in release branches by dependabot

---

CHANGELOG.md
tests/integration/distribution/keeper/grpc_query_test.go
tests/integration/distribution/keeper/msg_server_test.go
x/distribution/keeper/allocation.go
x/distribution/keeper/allocation_test.go
x/distribution/keeper/delegation_test.go
x/distribution/keeper/genesis.go
x/distribution/keeper/grpc_query.go
x/distribution/keeper/hooks.go
x/distribution/keeper/keeper.go
x/distribution/keeper/keeper_test.go
x/distribution/keeper/store.go
x/distribution/keeper/validator.go
x/distribution/migrations/v2/store_test.go
x/distribution/simulation/decoder_test.go
x/distribution/simulation/operations.go
x/distribution/simulation/operations_test.go
x/distribution/types/keys.go

Closes: #16572
---
I have...
I have...

refactor(distribution)!: use collections for validator accumulated commission state

---

x/gov/keeper/common_test.go
x/gov/keeper/keeper_test.go
x/mint/keeper/grpc_query_test.go
x/mint/keeper/keeper_test.go
x/mint/keeper/msg_server.go
x/mint/module.go
x/mint/types/errors.go
x/mint/types/keys.go

Closes: #16579 
- Redefines instead of reusing errors.
- Redefines instead of reusing module key names.  Note that a better solution to module keys as const strings is ModuleKeys as defined in ADR-33.
---
I have...
I have...

refactor: x/gov and x/mint no longer depend on each other

---

x/crisis/keeper/msg_server.go

went through crisis module, the changes are around errors and collections, no core logic changes. 
---
I have...
I have...

chore: audit crisis changes 

---

collections/CHANGELOG.md
collections/iter.go
collections/keyset.go
collections/map.go
collections/map_test.go

Closes: https://github.com/cosmos/cosmos-sdk/issues/16619
---
I have...
I have...

feat(collections): Add Clear method on Map and KeySet

---

docs/docs/run-node/01-run-node.md
tools/confix/cmd/home.go

ref: https://github.com/cosmos/cosmos-sdk/pull/16599#issuecomment-1598831221
---
I have...
I have...

docs: add explaination on how to change home folder globaly

---

x/distribution/client/cli/tx_test.go

This is the last cyclic dependency between x/* modules excluding x/params (deprecated, will be removed in 0.51) and x/simulation (undergoing a rewrite).
---
I have...
I have...

refactor(x/distribution): rm ref to x/gov from x/distribution

---

server/start.go

Closes: #XXXX
---
I have...
I have...

refactor: cleanup profiling code with equivalent one

---

x/consensus/autocli.go

ref: https://github.com/cosmos/cosmos-sdk/issues/15901
The consensus module had no CLI, this adds consistency between simd and hubl.
---
I have...
I have...

feat(consensus): wire autocli query

---

types/utils.go

there are users of this api, while it was removed due to inefficiencies  it is better to mark it as deprecated for a release  
---
I have...
I have...

chore: add sortJSON back & mark as deprecated

---

Makefile

[        TMCoreSemVer = "0.38.0-rc1"](https://github.com/cometbft/cometbft/blob/1dbb8caf19082ab6a52bee1f4fa93f4156a014be/version/version.go#L6)

build: delete CMTVERSION in Makefile

---

depinject/container_test.go
simapp/app_test.go
simapp/app_v2.go
x/auth/module.go

Closes: #XXXX
---
I have...
I have...

refactor: address codec factory

---

core/CHANGELOG.md
core/header/service.go

ref #16737 
add apphash to Info struct for header information. 
The question is should this be part of header or its own interface? 
cc @aaronc 
---
I have...
I have...

feat: add apphash to core header info

---

x/feegrant/msgs.go

Missed removing `GetSigners` method in last audit changes.
ref: #16508 
---
I have...
I have...

chore(feegrant): remove `GetSigners` in `msgs.go`

---

README.md

fix dead or old links to https://discord.gg/cosmosnetwork for security purposes
---
I have...
I have...

docs: README.md – update discord links 

---

x/evidence/README.md

Closes: https://github.com/cosmos/cosmos-sdk/issues/16694
---
I have...
I have...

docs(evidence): update cli docs

---

UPGRADING.md
tools/confix/data/v0.47-app.toml
tools/confix/diff.go
tools/confix/migrations.go
tools/confix/upgrade.go
tools/confix/upgrade_test.go

ref: https://github.com/cosmos/cosmos-sdk/issues/16698#issuecomment-1612947182
When auditing server, I tested that the configuration could be migrated without a problem with confix and there was a bug. Nothing to change in the package server itself.
---
I have...
I have...

chore(confix): audit

---

CHANGELOG.md

The removed two PR references got merged while resolving the conflicts.
---
I have...
I have...

chore: changelog correction

---

collections/CHANGELOG.md

Closes: #XXXX
---
I have...
I have...

chore(collections): prepare CHANGELOG.md for v0.3.0

---

store/CHANGELOG.md
store/iavl/tree_test.go
store/metrics/telemetry.go
store/pruning/manager.go
store/pruning/manager_test.go
store/rootmulti/store.go

ref: #16503
---
I have...
I have...

chore: store audit typo

---

tools/hubl/go.mod
tools/hubl/go.sum
tools/hubl/internal/remote.go

Hubl wasn't adding the validator address codec, while it was required.
Auth does not know the validator prefix, so we need to assume it in hubl.
---
I have...
I have...

fix(hubl): set validator address codec

---

client/v2/autocli/app.go
client/v2/autocli/builder.go
client/v2/autocli/common.go
client/v2/autocli/common_test.go
client/v2/autocli/flag/register.go
client/v2/autocli/msg.go
client/v2/autocli/msg_test.go
client/v2/autocli/query.go
client/v2/autocli/query_test.go
client/v2/go.mod
client/v2/internal/util/util.go

While doing https://github.com/cosmos/cosmos-sdk/issues/16743, found some quick improvements and fixes to be made in client/v2.
Improves and simplifies the client/v2 tests, some tests were wrong and harder to read.
Fix a bug in var arguments that weren't working (off by one error)
Add sane defaults, instead of having fallbacks (which are unclear without reading the whole code)
---
I have...
I have...

fix(client/v2): improve resolver and tests

---

x/gov/README.md

Closes https://github.com/cosmos/cosmos-sdk/issues/16908
Confirmed via https://github.com/cosmos/gaia/blob/353410e2902b7d947fe5b0633d14d19d8a97bd44/app/modules.go#L131

docs: describe `x/gov` usage on Cosmos Hub

---

simapp/app.go
simapp/upgrades.go

ref: https://github.com/cosmos/cosmos-sdk/issues/16864
Found nothing except https://github.com/cosmos/cosmos-sdk/pull/16865 and https://github.com/cosmos/cosmos-sdk/issues/16864#issuecomment-1628841760. The internal package  **will be removed only in the backported PR but not in the main branch**.
AFAIK, except for circuit, there have been no store changes.
Checked the UPGRADING.md for SimApp, and all the updates I wanted to do have already been done in my previous PR (https://github.com/cosmos/cosmos-sdk/pull/16696).
The v0.50 node I have that updates daily with the latest changes have had no troubles as well (https://github.com/julienrbrt/simapp)
---
please add links to any relevant follow up …

chore(simapp): audit

---

x/gov/README.md

Closes https://github.com/cosmos/cosmos-sdk/issues/16929
---
I have...
I have...

docs: clarify legacy proposal mention

---

x/auth/tx/adapter.go

Ref: #16693 
---
I have...
I have...

docs(x/auth): improve godoc for `GetSigningTxData`

---

x/group/README.md

accross -> across
---
I have...
I have...

docs(group): fix typo in README.md

---

CHANGELOG.md
x/staking/keeper/genesis.go
x/staking/keeper/keeper.go
x/staking/keeper/keeper_test.go
x/staking/keeper/val_state_change.go
x/staking/types/keys.go

Closes: #16375 
---
I have...
I have...

refactor: migrate LastTotalPower to use collections in x/staking

---

client/docs/config.json
client/docs/swagger-ui/swagger.yaml

Closes: #XXXX
---
I have...
I have...

chore(docs): regenerate swagger

---

tools/cosmovisor/CHANGELOG.md

Simply fix the URL of a change log entry
---
I have...
I have...

chore(cosmovisor): update CHANGELOG.md to fix incorrect URL

---

types/dec_coin.go
types/handler.go
types/module/genesis.go
types/tx/types.go
x/auth/tx/builder.go
x/auth/tx/builder_test.go
x/bank/simulation/operations.go
x/group/migrations/v2/migrate.go

Closes: https://github.com/cosmos/cosmos-sdk/issues/16475
The change of `MustAccAddressFromBech32` to use the address codec in `types`, made me look for other usage in the codebase where it could be replaced.
---
I have...
I have...

chore(types): audit

---

x/slashing/keeper/keeper.go
x/slashing/types/signing_info.go

Closes: #XXXX
---
I have...
I have...

fix(x/slashing): ValidatorSignInfo migration to collections was missing length prefix

---

testutil/collections.go

Closes: #XXXX
---
I have...
I have...

test: Add DiffCollectionsMigration

---

testutil/collections.go
testutil/collections_test.go

Closes: #XXXX
---
I have...
I have...

fix: DiffCollectionsMigration hash function not used correctly

---

x/gov/keeper/tally_test.go

Assert that votes are removed once tallied.
(This change follows the test I added here #17142, where I missed to assert that the votes are well removed once tallied)
---
I have...
I have...

test(gov): add missing assertion on TestTally

---

log/CHANGELOG.md
log/level.go

Avoid repeating parse log level.
---
I have...
I have...

perf(log): parse log level in filterFunc

---

.golangci.yml

The short linting job starts from the folder directly and does not skip the `fix_registration.go` file as it should.
Eg:
- https://github.com/cosmos/cosmos-sdk/actions/runs/5699736088/job/15448988620?pr=17183
- https://github.com/cosmos/cosmos-sdk/actions/runs/5696253965/job/15442267914?pr=17181
Fixing this will unblock PR touching server (#17183 and #17181) where the lint job is always failing due to this.
---
I have...
I have...

ci: skip `fix_registration.go` when using `LINT_DIFF=1`

---

docs/docs/core/02-context.md

Closes: #17034 
Adding `cometInfo` and `headerInfo` to context struct but also `streamingManager` to the docs.
---
I have...
I have...

docs: additional fields in context.go to be added to context.md

---

CHANGELOG.md
x/genutil/client/cli/migrate.go

Updates: https://github.com/crypto-org-chain/cronos/pull/1124
---
I have...
I have...

refactor: add MigrateHandler to allow reuse migrate genesis related function 

---

x/genutil/client/cli/migrate.go

Closes: #XXXX
---
I have...
I have...

fix: resolve migration map in MigrateHandler (#17301)

---

.github/ISSUE_TEMPLATE/documentation.md

add docs issue template to automate label setting
---
I have...
I have...

chore: add docs issue template

---

x/distribution/module.go

In #17115 a new migration was added but I forgot to increase the consensus version. This previous PR wasn't backported, so we don't need to backport this PR.
---
I have...
I have...

fix(x/distr): increase consensus version

---

x/gov/keeper/vote.go
x/gov/types/events.go

Closes: #XXXX
---
I have...
I have...

feat(x/gov): Emit VoterAddr

---

.github/workflows/build.yml
scripts/go-mod-tidy-all.sh

Follow-up of https://github.com/cosmos/cosmos-sdk/pull/17346
Dependabot triggers this script and it will always fail as `gomod2nix` won't be installed.
This fixes it.
---
I have...
I have...

fix(ci): install `gomod2nix` directly

---

CHANGELOG.md
x/gov/types/v1/msgs.go

This PR targets v0.47.x and wil be backported to v0.46 as well.
Partially backport https://github.com/cosmos/cosmos-sdk/pull/14880.
ref: https://github.com/cosmos/ibc-go/issues/4202#issuecomment-1678384284
---
I have...
I have...

feat(x/gov): add MsgSubmitProposal SetMsgs method

---

x/gov/client/cli/tx.go

fix the error sample in the comment.
Closes: #XXXX
---
I have...
I have...

chore(x/gov): update proposal.json go doc

---

x/staking/keeper/historical_info.go

Closes: #XXXX
---
I have...
I have...

perf: use store has instead of get in HistoricalInfo

---

collections/CHANGELOG.md

Closes: #XXXX
---
I have...
I have...

chore(collections): prepare changelog for v0.4.0 release

---

CHANGELOG.md

Adds v0.50.0-rc.0 changelog to main
---
I have...
I have...

chore: add 0.50.0-rc.0 changelog to main

---

client/grpc/cmtservice/status_test.go

ref: https://github.com/cosmos/cosmos-sdk/issues/17446
Temporarily disable this test as it blocks PRs 95% of the time.
https://github.com/cosmos/cosmos-sdk/pull/17443 got 0 pass of that test yet, blocking the PR.
---
I have...
I have...

test: disable `TestStatusCommand`

---

.github/workflows/test.yml
client/v2/go.mod
client/v2/go.sum

Bumps client/v2 to go 1.21 as it depends on the SDK.
Done as well for v0.50: https://github.com/cosmos/cosmos-sdk/pull/17453
---
I have...
I have...

chore: bump client/v2 to go.mod 1.21

---

x/gov/README.md

The `community-pool-spend` proposal type was deprecated in cosmos-sdk v0.47 ([source](https://github.com/cosmos/cosmos-sdk/blob/2db1247538657267122e0a4fb7e5f4cf979d396f/x/distribution/types/distribution.pb.go#L431-L440))
Closes: #XXXX
---
I have...
I have...

chore(docs): remove deprecated prop type

---

client/debug/main.go
x/auth/codec/bech32_codec.go

Tiny follow-up of https://github.com/cosmos/cosmos-sdk/commit/c6b0bb62ac700ef1c2453d41360fb4bcfbd6e72a for debug commands.
---
I have...
I have...

refactor(debug): use address codec in debug command

---

x/group/client/cli/tx.go

Closes: #17545 
Fixes the `proposal.json` example from the `submit-proposal` CLI help.
---
I have...
I have...

docs(x/group): fix submit-proposal help json example

---

store/rootmulti/store.go

change pruning info log level to debug, This helps reduce noise 
---
I have...
I have...

chore: change prune logging info to debug

---

x/auth/ante/fee.go

Closes https://github.com/cosmos/cosmos-sdk/issues/17553

docs: improve DeductFeeDecorator godoc

---

tools/cosmovisor/README.md

Closes: https://github.com/cosmos/cosmos-sdk/issues/17572
---
I have...
I have...

docs(cosmovisor): improve disclaimer for cosmovisor version

---

simapp/simd/cmd/commands.go

ref: https://github.com/cosmos/cosmos-sdk/pull/17513#discussion_r1304121268
note, this targets v0.50 branch as it has been fixed on main already in #17513
---
I have...
I have...

fix(simapp): fix example config template

---

.github/ISSUE_TEMPLATE/bug-report.yml

Seeing quite a few duplicate bugs being posted.
---
I have...
I have...

chore: improve issue template

---

UPGRADING.md
x/genutil/README.md

Closes: #XXXX
---
I have...
I have...

docs: add genesis changes in upgrading.md

---

x/upgrade/keeper/keeper.go

Closes: #XXXX
---
I have...
I have...

chore: remove println from upgrade keeper

---

client/config/config.go

Replaces "config.toml" with "client.toml" to avoid confusion between this and the cometbft config ("config.toml"); see: [server/main/util.go:236](https://github.com/cosmos/cosmos-sdk/blob/main/server/util.go#L236).
---
I have...
I have...

fix: typo in comment

---

tools/confix/data/v0.47-app.toml
tools/confix/data/v0.50-app.toml

Follow-up of https://github.com/cosmos/cosmos-sdk/pull/17649
---
I have...
I have...

chore(confix): update v0.47 and v0.50 config

---

x/staking/keeper/validator.go

Closes: #XXXX
---
I have...
I have...

refactor(staking): cleanup UnbondAllMatureValidators

---

docs/docs/build/packages/README.md
docs/docs/build/tooling/README.md

Closes: #XXXX
---
I have...
I have...

docs: add back removed readmes

---

store/iavl/tree.go

ref: https://github.com/cosmos/cosmos-sdk/pull/17600#discussion_r1317587742
---
I have...
I have...

chore: remove unecessary method

---

client/v2/internal/testpb/query.proto

AMessage used before defined, causing an error with @grpc/proto-loader lib
Closes: #XXXX
---
I have...
I have...

test: change order of proto definitions

---

core/CHANGELOG.md

add changelog for 0.11
Adds a note to not be used with 0.50.x or earlier 
---
I have...
I have...

chore(core): add changelog for 0.11 & 0.12

---

core/CHANGELOG.md
core/appmodule/module.go
x/upgrade/module.go

https://github.com/cosmos/cosmos-sdk/pull/17691/files#r1323053080
the above comment mentioned the interface IsUpgradeModule should be removed. this pr does this and removes it from the upgrade module 
---
I have...
I have...

refactor(core)!: remove unimplemented interface

---

docs/architecture/_category_.json
docs/docs/build/building-apps/_category_.json
docs/docs/build/building-modules/_category_.json
docs/docs/build/migrations/_category_.json
docs/docs/build/modules/_category_.json
docs/docs/build/packages/_category_.json
docs/docs/build/tooling/_category_.json
docs/docs/develop/advanced/_category_.json
docs/docs/develop/beginner/_category_.json
docs/docs/user/run-node/_category_.json
docs/rfc/_category_.json
docs/spec/_category_.json

To be backported
Closes: #XXXX
---
I have...
I have...

docs: update documentation order for `build` tab

---

client/v2/CHANGELOG.md
client/v2/autocli/flag/address.go

ref https://github.com/cosmos/cosmos-sdk/pull/17763#issuecomment-1721223539
---
I have...
I have...

chore(client/v2): explain breaking change v0.50 / v0.51 autocli

---

README.md

Thanks to Mary from IBC team for reporting! :)
---
I have...
I have...

docs: Banner in readme was missing

---

codec/address/bech32_codec.go

we were not checking for 0 length so we would bech32 "" which does have a value. 
---
I have...
I have...

fix: recreate legacy behaviour for addresscodec

---

codec/address/bech32_codec.go
x/feegrant/CHANGELOG.md
x/feegrant/client/cli/tx.go
x/feegrant/client/cli/tx_test.go
x/feegrant/filtered_fee_test.go
x/feegrant/grant.go
x/feegrant/grant_test.go
x/feegrant/keeper/genesis_test.go
x/feegrant/keeper/grpc_query_test.go
x/feegrant/keeper/keeper.go
x/feegrant/keeper/keeper_test.go
x/feegrant/keeper/msg_server_test.go
x/feegrant/migrations/v2/store_test.go
x/feegrant/module/abci_test.go
x/feegrant/msgs.go
x/feegrant/simulation/decoder_test.go
x/feegrant/simulation/genesis.go
x/feegrant/simulation/operations.go
x/feegrant/simulation/operations_test.go

ref: #13140 
remove calls to the global .String()
---
I have...
I have...

chore(feegrant): remove address.String() calls

---

CHANGELOG.md

Closes: #XXXX
---
I have...
I have...

chore: add v0.50.0-rc.1 to main changelog

---

x/auth/tx/builder.go

chore: remove duplicate check 

---

x/auth/keeper/grpc_query.go

chore(auth): return accId in error

---

store/dbadapter/store.go

chore(store): check value

---

CHANGELOG.md
x/gov/keeper/msg_server.go

removes telemetry for votes and proposals as the data will be incorrect 
---
I have...
I have...

refactor(x/gov): remove gov vote and proposal based telemetry

---

docs/learn/intro/01-why-app-specific.md

Capitalize D in beginning of paragraph
Closes: #XXXX
---
I have...

docs: Typo on Application - Specific  documentation

---

docs/build/building-apps/04-vote-extensions.md

Closes: #XXXX
---
I have...
I have...

chore: fixing typos and grammar for vote extension docs

---

collections/item.go
types/module/module.go
x/gov/keeper/migrations.go
x/gov/migrations/v5/store.go
x/gov/migrations/v5/store_test.go

The constitution isn't set in gov migration, which leads to an issue when exporting genesis after an upgrade.
Thanks @alpe for finding this!
---
I have...
I have...

fix(x/gov): set default constitution in gov migration

---

docs/rfc/README.md

Closes: #XXXX
---
I have...
I have...

chore(docs): rfc links

---

x/staking/keeper/msg_server.go

Closes: #XXXX
---
I have...
I have...

chore(staking): add delegator to events

---

client/flags/flags.go

Closes: #XXXX
---
I have...
I have...

fix:  comment on flag for textual

---

client/v2/autocli/testdata/help-echo-msg.golden

Follow-up of https://github.com/cosmos/cosmos-sdk/pull/18040 that broke client/v2 test.
https://github.com/cosmos/cosmos-sdk/actions/runs/6471531167/job/17570165087?pr=18025
---
I have...
I have...

test(client/v2): update golden file

---

math/int.go
x/gov/abci.go

Closes: #XXXX
---
I have...
I have...

chore: fix comments

---

types/bech32/bech32.go

Closes: #17494
---
I have...
I have...

chore: fix comments on bech32

---

x/tx/CHANGELOG.md

ref: https://github.com/cosmos/cosmos-sdk/issues/17456
---
I have...
I have...

chore: prepare x/tx v0.11.0

---

store/root/store.go
store/root/store_test.go
store/store.go

Update the `RootStore` interface to support branching the entire root store. This is analogous to supporting the `app.cms.CacheMultiStore()` call that's in use today.
---
I have...
I have...

feat(store/v2): root store branching

---

go.mod
go.sum
simapp/go.mod
simapp/go.sum
tests/go.mod
tests/go.sum

this pr bumps the store package to v1 of iavl, in preparation for the final release of 0.50 
---
I have...
I have...

chore(store): bump iavl to final v1

---

client/grpc/cmtservice/status_test.go
client/rpc/rpc_test.go
server/api/server_test.go
tests/e2e/auth/suite.go
tests/e2e/authz/grpc.go
tests/e2e/authz/tx.go
tests/e2e/bank/grpc.go
tests/e2e/bank/suite.go
tests/e2e/client/grpc/cmtservice/service_test.go
tests/e2e/distribution/grpc_query_suite.go
tests/e2e/distribution/withdraw_all_suite.go
tests/e2e/gov/deposits.go
tests/e2e/gov/grpc.go
tests/e2e/gov/tx.go
tests/e2e/group/suite.go
tests/e2e/mint/grpc.go
tests/e2e/staking/suite.go
tests/e2e/tx/benchmarks_test.go
tests/e2e/tx/service_test.go
tests/integration/server/grpc/server_test.go
testutil/network/interface.go
testutil/network/network.go
testutil/network/util.go
testutil/network/validator.go
x/auth/types/account_retriever_test.go

Closes: #XXXX
---
I have...
I have...

WIP: Network util cleanup, fix tests

---

.github/workflows/release.yml
RELEASE_NOTES.md
client/v2/go.mod
client/v2/go.sum
simapp/go.mod
tests/go.mod
tools/confix/go.mod
tools/confix/go.sum
x/circuit/go.mod
x/circuit/go.sum
x/evidence/go.mod
x/evidence/go.sum
x/feegrant/go.mod
x/feegrant/go.sum
x/nft/go.mod
x/nft/go.sum
x/upgrade/go.mod
x/upgrade/go.sum

Closes: #XXXX
---
I have...
I have...

chore: prepare v0.50 module tags

---

core/transaction/codec.go
core/transaction/validation.go
serverv2/transaction/codec.go
serverv2/transaction/errors.go
serverv2/transaction/valdiation.go
x/tx/decode/decode.go

this pr proposes the tx validator and tx codec interfaces with implementations
---
I have...
I have...

refactor(server): add tx codec and validation 

---

Dockerfile
RELEASE_PROCESS.md
contrib/images/simd-dlv/Dockerfile
contrib/images/simd-env/Dockerfile

The docker build on main has been failing for two months: https://github.com/cosmos/cosmos-sdk/pkgs/container/simapp/versions?filters%5Bversion_type%5D=tagged
This PR fixes it.
```sh
$ docker build -t simapp .
....
Successfully built eff772b17418
Successfully tagged simapp:latest
```
---
I have...
I have...

build: fix docker build on main

---

CHANGELOG.md
RELEASE_NOTES.md
tools/confix/CHANGELOG.md
x/upgrade/CHANGELOG.md

Closes: #XXXX
---
I have...
I have...

chore: prepare v0.50.2

---

.github/.codespellignore
.github/.misspell-fixer.ignore
.github/workflows/misspell.yml

ref https://github.com/cosmos/cosmos-sdk/pull/18683#issuecomment-1849635099
---
I have...
I have...

ci: use codespell instead of misspell-fixer

---

baseapp/baseapp.go

Make validateBasicTxMsgs all inclusive to do validation also checking if a message handler is available.
Fixes #18728

refactor(baseapp): move handler retrieval per sdk.Msg into validateBasicTxMsgs

---

x/auth/CHANGELOG.md
x/auth/client/cli/broadcast.go
x/auth/client/tx.go
x/auth/client/tx_test.go

Closes: #18065
- Restructure the output file of `sign-batch` cmd. With the old logic, when signing multiple transactions the output file is not even a valid json file (check `invalid_batch.json` in diff files).
- So I created a new `Txs` type to represent broadcast transactions in a file. Check `new_batch.json`
- Created encoder, decoder corresponding.
- Still keep single tx format, so `broadcast tx` now can broadcast both single tx format & multi txs format.
---
I have...
I have...

feat(x/auth): batch transactions file format & broadcast multi transactions

---

x/auth/client/tx.go

This PR fixes typos in the codebase.
Please review it, and merge if everything is fine.
If there are proto changes, run `make proto-gen` and commit the changes.

chore: fix spelling errors

---

x/genutil/client/cli/export.go

Fixes the staticmajor CI.
CC @odeke-em

ci: silence bogus resleak error

---

docs/learn/advanced/_category_.json
docs/learn/beginner/_category_.json
docs/learn/intro/_category_.json
docs/learn/learn.md

Updates the documentation with an overview page highlighting what is in the section. Closes issue in the docs repo. 
Closes: https://github.com/cosmos/cosmos-sdk-docs/issues/96
---
I have...
I have...

docs: add index page for learn section

---

docs/build/abci/01-prepare-proposal.md
docs/build/abci/02-process-proposal.md
docs/build/abci/03-vote-extensions.md
docs/build/abci/_category_.json

Updates for formatting for abci. Changing the order and headers so they are consistent. 
I have...
I have...

docs: formatting for main for abci

---

CHANGELOG.md
RELEASE_NOTES.md

Closes: #XXXX
---
I have...
I have...

chore: prepare v0.47.7

---

store/CHANGELOG.md
store/rootmulti/store.go

this pr adds a changelog entry for #18897
---
I have...
I have...

chore(store): add changelog for 18897 

---

types/handler.go

Closes: #18907
---
I have...
I have...

chore(docs): update AnteHandler godoc

---

tools/cosmovisor/README.md

rename 3 months ago, seems omit this link
---
I have...
I have...

docs: fix for links

---

x/gov/types/v1/params.go

minor typo in gov params.go
`less that` -> `less than`
---
I have...
I have...

chore(gov): fix typo

---

server/v2/appmanager/go.sum
server/v2/core/appmanager/app.go
server/v2/core/store/gas.go
server/v2/stf/gas.go

This pr adds a gas wrapper to stf allowing different gas configurations to be used and created 
---
I have...
I have...

chore(server/v2): add gas wrapper

---

server/v2/stf/go.mod
server/v2/stf/go.sum
server/v2/stf/stf.go

In the sync this morning we opted to not add recovery middleware, currently it is used to catch out of gas issue but we could do this via an error. We are seeking user feedback if they use recovery middleware, if not then we will not add it into server/v2
---
I have...
I have...

feat(server/v2): recovery 

---

x/gov/CHANGELOG.md
x/gov/abci.go
x/gov/abci_test.go
x/gov/keeper/deposit.go
x/gov/types/events.go

Proposal, as discussed on Slack.
I'll add a test if we go this way.
---
I have...
I have...

refactor(x/gov): log error when deposit refund error

---

testutil/network/network.go

ref: https://github.com/cosmos/cosmos-sdk/pull/18930/files#r1440028923
---
I have...
I have...

chore(testutil): use correct address codec

---

collections/CHANGELOG.md
depinject/CHANGELOG.md
errors/CHANGELOG.md
log/CHANGELOG.md
x/upgrade/CHANGELOG.md

Prepare log, errors, depinject minors.
---
I have...
I have...

chore: prepare log, errors and depinject minors

---

x/gov/keeper/msg_server_test.go
x/gov/types/v1/genesis_test.go
x/gov/types/v1/params.go

Fixed typos in x/gov changes `quorom` -> `quorum`
---
I have...
I have...

fix(x/gov): fix typos in x/gov

---

server/v2/appmanager/appmanager.go
server/v2/cometbft/abci.go
server/v2/core/appmanager/app.go
server/v2/core/event/event.go
server/v2/core/stf/stf.go
server/v2/core/store/gas.go
server/v2/stf/gas.go
server/v2/stf/stf.go
server/v2/stf/stf_builder.go
server/v2/stf/stf_router.go
server/v2/stf/stf_test.go
server/v2/stf/types.go

Closes: #XXXX
push todos from team calls and complete some 
---
I have...
I have...

chore(server/v2): push todos from sync

---

x/gov/types/v1/params.go

Extracted from https://github.com/cosmos/cosmos-sdk/pull/19101 as it needs to be backported.
---
I have...
I have...

fix(x/gov): check right params

---

math/uint.go

Closes: #XXXX
---
I have...
I have...

docs: documenting some panicking APIs

---

simapp/app_config.go
store/storage/rocksdb/iterator.go

Fix new lint error introduced by #18957

style: lint ci error

---

Makefile

This pr added a new `make help` function for displaying which commonly used commands that the Makefile supported. This is useful when a new developer goes to find a helpful tool for testing or building etc.
Note: the description of the commands may be incorrect. And I'm not sure if some commands were not added :)

chore: add `make help` to display the usage for project `Makefile`

---

.github/workflows/md-link-checker.yml

add slack notify for broken links 
---
I have...
I have...

chore: slack for broken links

---

CHANGELOG.md
RELEASE_NOTES.md
simapp/go.mod
tests/go.mod

Tested on:
- Juno
---
I have...
I have...

chore: prepare v0.47.8

---

docs/build/building-apps/04-security-part-1.md

This pr adds the well written security/footgun doc to the cosmos sdk docs. Thank you Roman Akhtariev and Alpin Yukseloglu for authoring and allowing us to host it on the cosmos sdk docs 
---
I have...
I have...

 chore: add security handbook

---

docs/learn/advanced/06-grpc_rest.md

Closes: #19174
Target `main` as suggestion and closed  #19189. Thanks! 
---
I have...
I have...

docs: fix typo in 06-grpc_rest.md

---

collections/CHANGELOG.md

Fix broken link on collections/CHANGELOG.md
---
I have...
I have...

chore(collections): fix broken link

---

server/v2/appmanager/go.mod
server/v2/cometbft/abci.go
server/v2/cometbft/go.mod
server/v2/cometbft/go.sum
server/v2/cometbft/utils.go
server/v2/core/store/types.go
server/v2/stf/stf.go
simapp/gomod2nix.toml

this pr adds consensus params query to initchain, i still need to look at how it would work on other places and if its needed 
---
I have...
I have...

chore(server/v2/cometbft): add consensus params query

---

crypto/keyring/keyring_test.go
crypto/keys/secp256k1/secp256k1_test.go
crypto/keys/secp256r1/privkey.go

Closes: #XXXX
---
I have...
I have...

chore: Fixed typos in the 'crypto' folder.

---

x/auth/CHANGELOG.md
x/auth/client/cli/tx_multisign.go

Closes:
#19191
---
I have...
I have...

fix(x/auth): set from flag in multi-sign command

---

server/v2/appmanager/appmanager.go
server/v2/appmanager/mock/storage.go
server/v2/cometbft/query.go
server/v2/stf/branch/changeset.go
server/v2/stf/branch/mergeiter.go
server/v2/stf/state.go
server/v2/stf/stf.go
server/v2/stf/stf_router.go
server/v2/stf/stf_test.go
server/v2/streaming/streaming_test.go

this pr is only lintinf fixes on the server/v2 branch 
---
I have...
I have...

chore(server/v2): linting fixes

---

docs/architecture/adr-070-unordered-transactions.md

Add section on deterministic transaction encoding.
---
I have...
I have...

docs: Update ADR-070

---

CHANGELOG.md
RELEASE_NOTES.md
go.mod
go.sum
simapp/go.mod
simapp/go.sum
tests/go.mod
tests/go.sum

Prepares v0.47.9
---
I have...
I have...

chore: prepare v0.47.9

---

CHANGELOG.md
RELEASE_NOTES.md
client/v2/CHANGELOG.md
go.mod
go.sum
simapp/go.mod
simapp/go.sum
tests/go.mod
tests/go.sum
x/circuit/go.mod
x/circuit/go.sum
x/evidence/go.mod
x/evidence/go.sum
x/feegrant/go.mod
x/feegrant/go.sum
x/nft/go.mod
x/nft/go.sum
x/upgrade/go.mod
x/upgrade/go.sum

Prepares v0.50.4
---
I have...
I have...

chore: prepare v0.50.4

---

runtime/v2/builder.go
runtime/v2/manager.go
runtime/v2/module.go

Follow-up of https://github.com/cosmos/cosmos-sdk/pull/19512 for runtime/v2
---
I have...
I have...

refactor(runtime/v2): extend mm

---

core/appmodule/v2/genesis.go
core/store/database.go
runtime/v2/manager.go
testutil/mock/types_mock_appmodule.go
testutil/mock/types_module_module.go
types/module/module.go
types/module/module_int_test.go
x/staking/module.go

Add godocs to a few areas and fix build errors 
---
I have...
I have...

chore(server/v2): add godocs

---

client/v2/go.mod
go.mod
scripts/dep-assert.sh
simapp/go.mod
store/go.sum
tests/go.mod
tests/starship/tests/go.mod
x/accounts/go.mod
x/auth/go.mod

reduce diff changes between server_modular & main by deleting unnecessary changes.
---
I have...
I have...

chore(serverv2): remove uncessary replaces

---

CHANGELOG.md
types/module/core_module.go

Closes: #XXXX
---
I have...
I have...

fix(types): check for HasABCIGenesis in CoreAppModuleBasicAdaptor

---

runtime/v2/builder.go
runtime/v2/manager.go
runtime/v2/migrations.go
runtime/v2/services/autocli.go
simapp/app_test.go
types/module/module.go
types/module/module_test.go

Wire the new hasgenesis api in runtime/v2 mm
---
I have...
I have...

refactor(runtime/v2): genesis refactors

---

server/v2/cometbft/abci.go
server/v2/cometbft/server.go

add txcodec to newserver 
---
I have...
I have...

chore: add txcodec

---

store/CHANGELOG.md

add release date to store 
---
I have...
I have...

chore(store): add release date

---

CHANGELOG.md

Closes: #XXXX
---
I have...
I have...

docs: fix changelog for v0.47.x-ics-lsm branch

---

x/bank/keeper/send.go

minor cleanup to reuse the fromAddrString.
Closes: #XXXX
---
I have...
I have...

reuse fromAddrString (minor cleanup)

---

client/v2/go.mod
x/accounts/defaults/lockup/go.mod
x/accounts/go.mod
x/auth/go.mod
x/authz/go.mod
x/bank/go.mod
x/circuit/go.mod
x/distribution/go.mod
x/epochs/go.mod
x/evidence/go.mod
x/feegrant/go.mod
x/gov/go.mod
x/group/go.mod
x/mint/go.mod
x/nft/go.mod
x/params/go.mod
x/protocolpool/go.mod
x/slashing/go.mod
x/staking/go.mod
x/upgrade/go.mod

Follow-up of https://github.com/cosmos/cosmos-sdk/pull/20096 otherwise `go mod tidy` adds it.
Basically, all modules that import the SDK.
---
I have...
I have...

build: set go 1.21.0 everywhere

---

client/v2/CHANGELOG.md
client/v2/go.mod
client/v2/go.sum
tools/confix/go.mod
tools/confix/go.sum
x/circuit/CHANGELOG.md
x/circuit/go.mod
x/circuit/go.sum
x/evidence/CHANGELOG.md
x/evidence/go.mod
x/evidence/go.sum
x/feegrant/CHANGELOG.md
x/feegrant/go.mod
x/feegrant/go.sum
x/nft/CHANGELOG.md
x/nft/go.mod
x/nft/go.sum
x/upgrade/CHANGELOG.md
x/upgrade/go.mod
x/upgrade/go.sum

Part of the release chores: https://github.com/cosmos/cosmos-sdk/pull/19998#issuecomment-2066165871
After this I'll tag the modules and open another PR with simapp bumped to use those.
---
I have...
I have...

build(deps): bump sdk in modules

---

go.mod
go.sum
simapp/go.mod
simapp/go.sum
tests/go.mod
tests/go.sum
tools/rosetta/go.mod
tools/rosetta/go.sum

Closes: #XXXX
---
I have...
I have...

chore: revert comet 0.37.6 upgrade due to go version bump

---

.github/workflows/pr-go-mod-tidy-mocks.yml

Closes: #XXXX
---
I have...
I have...

ci: run action in merge queue

---

go.mod
go.sum

Closes: #XXXX
Use hashicorp/go-getter v1.7.1 as v1.7.4 breaks tests. 
---
I have...
I have...

build(deps): revert hashicorp/go-getter to v1.7.1

---

x/upgrade/go.mod
x/upgrade/go.sum

ref: https://github.com/cosmos/cosmos-sdk/issues/20525
---
I have...
I have...

chore(x/upgrade): bump vulnerable `go-getter` library

---

CHANGELOG.md
RELEASE_NOTES.md
x/upgrade/CHANGELOG.md

Closes: #XXXX
https://github.com/cosmos/cosmos-sdk/pull/20381 got merged, so we are ready for the next patch release.
I will update the release notes to mention https://github.com/cosmos/cosmos-sdk/pull/20381 less succinctly.
https://github.com/cosmos/cosmos-sdk/compare/v0.50.6..release/v0.50.x
---
I have...
I have...

chore: prepare v0.50.7

---

CHANGELOG.md
RELEASE_NOTES.md

Closes: #XXXX
https://github.com/cosmos/cosmos-sdk/compare/v0.47.11...release/v0.47.x
---
I have...
I have...

chore: prepare v0.47.12

---

Dockerfile

Closes: #XXXX
---
I have...
I have...

fix: align Dockerfile for build-push-action

---

go.work.example
types/simulation/config.go

Trivial lint fix.
Also updates `go.work.example` to include tests/systemtests, removes simapp/v2 (it's not on main yet).
---
I have...
I have...

fix(types): fix linting error

---

CHANGELOG.md
x/staking/keeper/validator.go

Closes: #XXXX
Rolling back changes from https://github.com/cosmos/cosmos-sdk/pull/20548.
---
I have...
I have...

refactor!: revert #20548 - staking enblocker

---

CHANGELOG.md

Closes: #XXXX
---
I have...
I have...

docs: add changelog entry for v0.47.16-ics-lsm

---

server/v2/cometbft/server.go

Closes: #13788 
this pr is meant to test different clients for comet, the default one has a single mutex over all of abci, this pr moves to a client that only has a mutex over consensus 
we should do some profiling in the future to see what is best. With this client, all connections mempool, query and info are async and only consensus is synchronous. Im not sure what the benefit to being fully async here as consensus will still need to be sync 
---
I have...
Please see [Pull Request …

feat: use comet async clients 

---

.github/workflows/test.yml
.github/workflows/v2-test.yml

while reviewing #20801, realized the store/v2 tests is not covered
---
I have...
I have...

ci: store-v2 test CI/CD

---

tests/systemtests/cli.go
tests/systemtests/system.go
tests/systemtests/unordered_tx_test.go

Review feedback to compare
Build + copy binary to system tests
Run test with `go test -mod=readonly -tags='system_test' -v ./...  --run TestUnorderedTXDuplicate`
---
I have...
I have...

Review feedback and minor updates

---

go.mod
go.sum
simapp/go.mod
simapp/go.sum
tests/go.mod
tests/go.sum
tools/cosmovisor/go.mod
tools/cosmovisor/go.sum
tools/rosetta/go.mod
tools/rosetta/go.sum

Reverts cosmos/cosmos-sdk#20837

Revert "build(deps): Bump github.com/cometbft/cometbft from 0.37.5 to 0.37.8"

---

math/dec.go
math/dec_test.go

These are the last changes to be made to finish the testing for the apd library. Here I focused on the remaining functions as well as cleanup. 
Here I concentrated on the constraints of the decimal and tried to push the boundaries so we can see how far the precision goes.
---
I have...
I have...

feat(math): Upstream GDA based decimal type testing

---

server/v2/api/grpc/server.go
server/v2/api/grpcgateway/server.go
server/v2/cometbft/commands.go
server/v2/cometbft/server.go
server/v2/commands.go
server/v2/server.go
server/v2/server_test.go
server/v2/types.go
simapp/v2/simdv2/cmd/commands.go
simapp/v2/simdv2/cmd/root_di.go
simapp/v2/simdv2/cmd/root_test.go
simapp/v2/simdv2/cmd/testnet.go
simapp/v2/simdv2/main.go

Superseded https://github.com/cosmos/cosmos-sdk/pull/20831
---
I have...
I have...

refactor(server/v2): remove unneeded generic type parameters

---

crypto/keys/multisig/multisig.go

ibc-go reported that this broke some tests, we revisited the issue and fixed it here #21013
---
I have...
I have...

fix(crypto): revert #20438

---

simapp/app.go
x/tx/CHANGELOG.md
x/tx/signing/context.go
x/tx/signing/context_test.go

ref: https://github.com/cosmos/cosmos-sdk/pull/21073#issuecomment-2260016916
x/tx on main doesn't correspond to what v0.50 and lower can use (wrong core version).
Creating a v0.13.x branch and tagging  v0.13.4 after this.
---
I have...
I have...

chore: prepare x/tx v0.13.4

---

log/CHANGELOG.md

Useful to integration with v0.52.
Additionally I can see if the vangen fix works
---
I have...
I have...

chore: prepare log v1.4.0

---

runtime/store.go

realised we missed this so users cant use the memstore in testing 
---
I have...
I have...

chore: backport NewMemStoreService method

---

server/v2/stf/stf.go
server/v2/stf/stf_test.go

Closes: #XXXX
---
I have...
I have...

refactor(server/v2/stf): pass exec mode to validateTx

---

.github/workflows/test.yml

Closes: #XXXX
---
I have...
I have...

ci: run tests on push to release/v0.52.x

---

store/CHANGELOG.md
store/go.mod
store/go.sum

Prepares cosmossdk.io/store v1.1.1 that bumps iavl to 1.2.0
Avoids to bring in an indirect dep to broken iavl 1.1.2 (ref: https://github.com/cosmos/cosmos-sdk/issues/20489#issuecomment-2251582818)
---
I have...
I have...

build(deps): bump iavl in cosmossdk.io/store 1.1.x

---

CHANGELOG.md
RELEASE_NOTES.md

Prepares v0.47.14
---
I have...
I have...

chore: prepare v0.47.14

---

CHANGELOG.md

Closes: #XXXX
---
I have...
I have...

chore: correct date v0.47.14

---

CHANGELOG.md

Closes: #XXXX
---
I have...
I have...

docs: prepare v0.50.10-lsm release

---

docs/pre.sh

needed by https://github.com/cosmos/cosmos-sdk-docs/pull/211
---
I have...
I have...

docs: prepare 0.52 docs deployment

---

CHANGELOG.md
RELEASE_NOTES.md

~~Blocked on https://github.com/cosmos/cosmos-sdk/pull/21678, which is itself blocked on https://github.com/cosmos/cosmos-sdk/pull/22008~~
---
I have...
I have...

chore: prepare 0.52 beta.2

---

simapp/app.go

small change in simapp v0.50 for consistency
ref: https://github.com/cosmos/cosmos-sdk/issues/22200#issuecomment-2403465791
---
I have...
I have...

chore(simapp): be consistent with runtime

---

docs/build/_category_.json
docs/build/build.md

While fixing the script that was missing many things, it came up that the docs repo was just having static files on some versioned documentation files that weren't here:
---
I have...
I have...

docs: add docs boilerplate

---

tests/systemtests/upgrade_test.go

The artifact pulled from Docker runs on Linux only
---
I have...
I have...

chore: Set build tag for chain upgrade test

---

.github/workflows/test.yml

Backport from: https://github.com/cosmos/cosmos-sdk/pull/22468
---
I have...
I have...

build(deps): Bump actions/xxx-artifact from v3 to v4

---

tests/systemtests/upgrade_test.go

Fixes test setup for v0.50 artifact
---
I have...
I have...

test: fix chain upgrade (0.50 -> 0.52) test setup

---

x/staking/keeper/msg_server.go

Both SafelyIncreaseTotalLiquidStakedTokens and SafelyIncreaseValidatorLiquidShares should be called during CreateValidator if the address is a liquid staker.
I have...
I have...

fix: CreateValidator fn should increase liquid shares if a validator is a liquid staker

---

CHANGELOG.md
RELEASE_NOTES.md

Prepares v0.47 eol.
---
I have...
I have...

chore: prepare 0.47.15

---

RELEASE_NOTES.md

Closes: #XXXX
---
I have...
I have...

chore: 0.47.15 release notes

---

CHANGELOG.md

Closes: #XXXX
---
I have...
I have...

docs: add v0.50.11-lsm changelog

---

simapp/v2/go.mod
simapp/v2/go.sum

`cosmossdk.io/server/v2/cometbft` was still using a replace to a local dir, rather than already released `v1.0.0-beta.1`
---
I have...
I have...

build(deps): use server/v2/cometbft v1.0.0-beta.1

---

.github/workflows/build.yml
scripts/build/build.mk

Fixes CI with new sqlite go deps
---
I have...
I have...

ci: build simapp with sqlite deps

---

.github/workflows/build.yml
scripts/build/build.mk

Fixes CI for mac
---
I have...
I have...

ci: introduce sqlite build tag

---

client/keys/mnemonic.go

chore: typo mnemonic.go

---

tests/integration/rapidgen/rapidgen.go
tests/integration/staking/keeper/deterministic_test.go
tests/integration/tx/aminojson/aminojson_test.go

Closes: #22862
---
I have...
I have...

fix(tests): fix x/tx/aminojson test failure

---

CHANGELOG.md
tests/systemtests/fraud_test.go
x/auth/ante/sigverify.go

Closes: #XXXX
---
I have...
I have...

feat(x/auth/ante): allow custom verifyIsOnCurve when validate tx for public key (backport: #23128)

---

simapp/upgrades.go
simapp/v2/app_di.go
simapp/v2/go.mod
simapp/v2/go.sum
simapp/v2/upgrades.go

the push simd image is [fail](https://github.com/cosmos/cosmos-sdk/actions/runs/12714926382/job/35446103942)
---
I have...
I have...

fix(simapp/v2): add MigrateAccountNumberUnsafe for v050-to-v2

---

server/grpc/server.go

Interface clean up
---
I have...
I have...

refactor(server): use interface instead of full Application type

---

server/v2/cometbft/abci_test.go
server/v2/cometbft/utils.go
tests/integration/accounts/lockup/utils.go
tests/integration/distribution/genesis_test.go
x/accounts/defaults/lockup/continuous_locking_account_test.go
x/accounts/defaults/lockup/delayed_locking_account_test.go

Closes: #XXXX
---
I have...
I have...

fix: lint in `release/v0.52.x`

---

CHANGELOG.md
RELEASE_NOTES.md

Prepares v0.52.0-rc.2. No other changes happen in modules themselves so no need to bug them.
---
I have...
I have...

chore: prepare 0.52 rc.2

---

scripts/build/build.mk

---
fixes : `COSMOS_BUILD_OPTIONS=v2 make install` is broken since simapp is no longer in directory `./simapp/v2`.
I have...
I have...

ci: fix simapp dir in makefile

---

.github/CODEOWNERS

Closes: #XXXX
---
I have...
I have...

chore: set up branch codeowners

---

.github/workflows/docker.yml
.github/workflows/proto-docker.yml

Backport c0fafff8389e528f2b295497b8705b6f7d7e6380

chore: back port depot

---

.github/dependabot.yml
.github/pr_labeler.yml
.github/workflows/build.yml
.github/workflows/test.yml

removes hubl from CI as its not in this branch and makes some CI jobs fail.
---
I have...
I have...

ci: remove hubl

---

telemetry/metrics.go
telemetry/metrics_test.go
telemetry/wrapper.go

`git checkout main -- telemetry`

chore: set `telemetry` to `main`

---

simapp/app.go
simapp/app_config.go
simapp/app_di.go
simapp/app_test.go
simapp/simd/cmd/testnet_test.go
tests/integration/evidence/keeper/infraction_test.go
x/params/README.md
x/params/keeper/keeper.go
x/params/module.go

Closes: https://github.com/cosmos/cosmos-sdk/issues/23763
---
I have...
I have...

feat: deprecate `x/params`

---

CHANGELOG.md
client/tx/aux_builder.go

adds missing field to the tx body when signing with legacy amino.
---
I have...
I have...

fix: add missing field to unordered for amino json signing

---

.github/workflows/release-simd.yml

update version. 
---
I have...
I have...

ci: update go releaser version

---

.github/workflows/release-simd.yml

set the workdir for the release action and bump the releaser action version.
---
I have...
I have...

ci: bump release action and set workdir

---

.github/workflows/release-simd.yml
simapp/.goreleaser.yml

uses the same releaser methodology as in `tools`.
---
I have...
I have...

ci: use old releaser method

---

CHANGELOG.md
x/distribution/keeper/validator.go

Closes https://github.com/cosmos/cosmos-sdk/issues/23932

fix(x/distribution): vulnerable incrementReferenceCount in distribution (#19301)

---

CHANGELOG.md
x/simulation/mock_cometbft.go

Closes: #23807
Backport 
---
I have...
I have...

fix(sims): Use liveness matrix for validator sign status in sims (21952)

---

README.md
simapp/app.go
simapp/app_di.go
x/README.md

As i've been adding code, its been hard to reason about some the large simapp files.  This PR just formats and organizes a bit for better legibility

chore: clarify essential and supplmental modules

---

api/cosmos/app/runtime/v1alpha1/module.pulsar.go
proto/cosmos/app/runtime/v1alpha1/module.proto

Default pkg.go docs references to release version unless reference to unreleased beta version.
---
I have...
I have...

fix: update documentation links for module migrations and error types

---

client/rpc/rpc_test.go
testutil/network/network.go

- bump timeout
- fail test fast if we didnt reach the desired height

chore: attempt to fix flakey test

---

.github/workflows/dependencies-review.yml

vuln check comment was failing, trying github official script action to make the comment instead
---
I have...
I have...

fix(ci): vuln check comment

---

CHANGELOG.md
crypto/ledger/ledger_secp256k1.go

Closes: #[23797](https://github.com/cosmos/cosmos-sdk/issues/23797)
---
I have...
I have...

fix(crypto/ledger): Improve error message when deriving paths (#22116)

---

CHANGELOG.md
client/config/config_test.go
client/context.go
server/start.go
simapp/simd/cmd/root.go
simapp/simd/cmd/root_di.go

Closes: #23800
[Backport](https://github.com/cosmos/cosmos-sdk/pull/18345)
---
I have...
I have...

fix(client,server): consistently set env prefix between client/server

---

CHANGELOG.md
types/context.go

Closes: #23792
[Backport](https://github.com/cosmos/cosmos-sdk/pull/19966)
---
I have...
I have...

chore(optimize): Return BlockHeader by shallow copy in server Context

---

.github/workflows/dependencies-review.yml

Changes the vuln PR to just ignore the one specific faulty issue and fail for anything else

fix: vuln CI job

---

scripts/go-lint-changes.bash

last try.
---
I have...
I have...

ci: try running lint with just --new flag

---

store/cachemulti/store.go
store/rootmulti/store.go
store/types/store.go

Closes: #XXXX
---
I have...
I have...

refactor(store): use map.Copy for cleaner map handling

---

simapp/app.go

use maps.Clone to simplify the code
---
I have...
I have...

refactor(simapp): use maps.Clone to simplify the code

---

testutil/sims/app_helpers.go

Closes: #XXXX
---
I have...
I have...

chore(testutil): remove unnecessary error check

---

math/int_test.go
math/uint_test.go
store/pruning/manager.go

In Go 1.21, the standard library includes built-in [max/min](https://pkg.go.dev/builtin@go1.21.0#max) function, which can greatly simplify the code.
---
I have...
I have...

refactor: use the built-in max/min to simplify the code

---

x/auth/ante/testutil/expected_keepers_mocks.go

generate mocks
---
I have...
I have...

chore: gen mocks

---

baseapp/streaming.go
x/auth/ante/basic.go
x/auth/types/account.go
x/auth/types/genesis.go
x/gov/migrations/v4/store.go
x/group/keeper/msg_server.go
x/staking/keeper/msg_server.go
x/staking/migrations/v4/store.go

checked all with linters, We should be able to resolve all slice-related refactor in this PR.
Closes: #XXXX
---
I have...
I have...

chore(all): modernized code with slices

---

Makefile
baseapp/test_helpers.go
simapp/sim_test.go
testutils/sims/runner.go
x/simulation/simulate.go
x/slashing/simulation/operations.go
x/staking/simulation/operations.go

```
18b6e639f5 -(6 months ago) test: fix sims (backport #21735) (#21738)
fbfb6e59c9 -(7 months ago) fix(sims): OOM at sim-multi-seed-long run (backport #21503) (#21517)
b0652195d8 -(8 months ago) test(x/slashing): fix slashing sims (#20995)
dc5c16b0be -(8 months ago) fix (sims): state written in sims loop (#20936)
```
---
I have...
I …

fix(sims): Minor fixes

---

.github/workflows/gosec.yml

ci: fix gosec

---

store/types/utils.go

Closes: https://github.com/cosmos/cosmos-sdk/pull/23929
slices part seems already be replaced
---
I have...
I have...

chore: clean utils's SliceContains

---

x/auth/types/permissions.go

follow up: https://github.com/cosmos/cosmos-sdk/pull/24149 modify some missing cases.
Closes: #XXXX
---
I have...
I have...

refactor: slices.Contains

---

client/rpc/rpc_test.go

Part of #24082 
---
I have...
I have...

test(client/rpc): Fix flacky RPC client test

---

docs/docs/user/user.md

this was missing and caused the docs to fail to serve.
---
I have...
I have...

docs: add missing users doc

---

docs/docs/user/user.md

adds a missing doc.
---
I have...
I have...

docs: add missing user doc

---

.github/issue_labeler.yml

this yellow label has hurt me so

chore: remove issue labeler

---

x/tx/go.mod
x/tx/go.sum

This PR is part of #24114 and it migrates `x/tx` to CometBFT v1.0.1.
The only change is a dependency on the [api](https://github.com/cosmos/cosmos-sdk/pull/24463) and [core](https://github.com/cosmos/cosmos-sdk/pull/24469) modules that were upgraded to Comet v1.
---
I have...
I have...

feat(x/tx): Upgrade x/tx to CometBFT v1.0.1

---

CHANGELOG.md
crypto/codec/amino.go
crypto/hd/algo.go
crypto/hd/algo_test.go
crypto/keys/multisig/codec.go
crypto/ledger/encode_test.go

This PR is part of #24114
Comet v1 removed its `crypto/sr25519` implementation but the SDK depends on it. Since Sr25519 is reportedly not being used (per https://github.com/cometbft/cometbft/pull/3646), this PR just deletes these dependencies from the SDK.
[ADR 28](https://github.com/cosmos/cosmos-sdk/blob/main/docs/architecture/adr-028-public-key-addresses.md) has references to it, unclear if we should just fix it.
I have...
Please see [Pull Request Reviewer section in the contributing …

fix: Remove SDK dependency on CometBFT Sr25519

---

CHANGELOG.md
UPGRADE_GUIDE.md

- fix changelog
- make a small note for `x/protocolpool` in doc

chore: release prep

---

simapp/go.mod
simapp/go.sum
tests/go.mod
tests/go.sum

updates simapp and tests go.mod with newest client tag
---
please add links to any relevant follow up issues.  Your PR will not be merged unless you satisfy
all of these items.*
I have...

chore: update simapp and tests go mod with new client tag

---

simapp/go.mod
simapp/go.sum
tests/go.mod
tests/go.sum

chore: final tags updated

---

client/v2/go.mod
client/v2/go.sum
core/go.mod
core/go.sum
go.mod
go.sum
simapp/go.mod
simapp/go.sum
systemtests/go.mod
systemtests/go.sum
tests/go.mod
tests/go.sum
tests/systemtests/go.mod
tests/systemtests/go.sum
tools/benchmark/go.mod
tools/benchmark/go.sum
tools/confix/go.mod
tools/confix/go.sum
tools/cosmovisor/go.mod
tools/cosmovisor/go.sum
x/tx/go.mod
x/tx/go.sum

after this, I can create a `core` tag and use that

chore: create API tag and use

---

crypto/keys/secp256k1/internal/secp256k1/secp256_test.go
x/auth/keeper/keeper_bench_test.go
x/bank/bench_test.go
x/mint/types/minter_test.go
x/upgrade/internal/conv/string_test.go

The new pr for https://github.com/cosmos/cosmos-sdk/pull/25377 and signed.

refactor: use b.Loop() to simplify the code and improve performance
